import {flowTwoLegs,flowBankBorrowing,flowCreditCeiling,flowSecuritySettlement,flowCentralBankOperations,flowForeignPayment,flowFundCashMenu} from './capitalFlowFixtures';
import type {FlowStop} from './capitalFlowFixtures';
export type FlowLabId='C1'|'C2'|'C3'|'C4'|'C5'|'C6'|'C7';
export type FlowField={key:string;label:string;min:number;max:number;step:1};
export type FlowRow=readonly[label:string,value:string];
export type FlowDisplay={status:'OK';rows:readonly FlowRow[]}|FlowStop;
export type FlowLab={id:FlowLabId;title:string;assumption:string;initial:Readonly<Record<string,number>>;fields:readonly FlowField[];display(v:Readonly<Record<string,number>>):FlowDisplay;experiment:string;sourceIds:readonly number[]};
export function flowDisplayValue(x:unknown):string{if(x===null)return '未知／未识别（不是0）';if(typeof x==='number')return Number.isInteger(x)?String(x):`≈${Number(x.toPrecision(12))}`;if(typeof x==='boolean')return x?'是':'否';return String(x);}
function display<T extends object>(r:FlowStop|{status:'OK';value:T},labels:readonly(readonly[keyof T,string])[]):FlowDisplay{return r.status==='STOP'?r:{status:'OK',rows:labels.map(([key,label])=>[label,flowDisplayValue(r.value[key])] as const)};}
const f=(key:string,label:string,min=0,max=1_000_000):FlowField=>({key,label,min,max,step:1});
export const flowCanonicalInputs={
 c1:{assetsNetAcquisition:80,liabilitiesNetIncurrence:90,alternativeAssetsNetAcquisition:0,alternativeLiabilitiesNetIncurrence:10},
 c2:{initialLoans:80,initialHomeReserves:20,initialHomeDeposits:90,equity:10,newBorrowingForeign:10,spotCents:200},
 c3:{fundingRoom:20,equity:10,capitalFloorBps:1000,existingRWA:80,newLoanRiskWeightBps:10000,demand:30},
 c4:{totalHomePayment:100,primaryPct:40,unitPriceCents:500,availableExistingUnits:20},
 c5:{foreignAssetsInitial:10,spotCents:200,domesticClaimsInitial:80,bankReservesInitial:90,currencyInitial:0,equity:10,purchasedForeign:5,absorbedHome:10},
 c6:{foreignDue:10,foreignLiquid:4,confirmedForeignReceipts:3,homeCash:5,convertibleHomePct:100,spotCents:200},
 c7:{assetFace:100,executionPricePct:90,buyCapacityFace:20,cash:5,requestedCash:30},
} as const;
const definitions:readonly FlowLab[]=[
 {id:'C1',title:'同一个净额可以遮住两套交易腿',initial:flowCanonicalInputs.c1,
  fields:[f('assetsNetAcquisition','本情景外部资产净获得（同窗口本币整数；可为净回收）',-1_000_000),f('liabilitiesNetIncurrence','本情景外部负债净发生（同窗口本币整数；可为净偿还）',-1_000_000),f('alternativeAssetsNetAcquisition','替代情景外部资产净获得（同窗口本币整数）',-1_000_000),f('alternativeLiabilitiesNetIncurrence','替代情景外部负债净发生（同窗口本币整数）',-1_000_000)],
  assumption:'独立SYN，两替代情景同一交易窗口、同本币交易估值。A为居民外部资产净获得，L为居民外部负债净发生；FA=A−L，本课“净向内融资”N=L−A，两者方向相反。正负是各腿已净额化的交易，不是正负持仓。|A|+|L|只是教学规模指标，不是官方gross交易总量、未净成交量或存量。未给经常交易、重估与完整国家账。',
  display:v=>display(flowTwoLegs({assetsNetAcquisition:v.assetsNetAcquisition,liabilitiesNetIncurrence:v.liabilitiesNetIncurrence,alternativeAssetsNetAcquisition:v.alternativeAssetsNetAcquisition,alternativeLiabilitiesNetIncurrence:v.alternativeLiabilitiesNetIncurrence}),[['assetLeg','本情景资产净交易A（本币）'],['liabilityLeg','本情景负债净交易L（本币）'],['financialAccount','本情景FA=A−L（本币）'],['inwardNetFinancing','本情景N=L−A净向内融资（本币）'],['alternativeFinancialAccount','替代情景FA（本币）'],['alternativeInwardNetFinancing','替代情景N（本币）'],['teachingLegMagnitude','本情景|A|+|L|教学指标'],['alternativeTeachingLegMagnitude','替代情景|A|+|L|教学指标'],['officialGrossTurnover','官方未净交易总量'],['closingIip','完整期末外部头寸IIP'],['actualDomesticCredit','真实国内信用反应']]),
  experiment:'80/90与0/10的N均10，FA均−10，但教学规模170与10。将本情景A/L均改20，N=0仍有两项各20的净交易。把L改−10表示负债净偿还，不能说持有负数量债券；清空任一腿则STOP。',sourceIds:[1,2,3]},
 {id:'C2',title:'银行借入外币：新增资产和债务，不是新增权益',initial:flowCanonicalInputs.c2,
  fields:[f('initialLoans','起始本币贷款账面额（SYN本币整数）'),f('initialHomeReserves','起始本币央行准备金（SYN本币整数）'),f('initialHomeDeposits','起始本币存款负债（SYN本币整数）'),f('equity','起始权益（本币整数；严格正才可算杠杆）',1),f('newBorrowingForeign','本操作向非居民新借入外币（原外币整数）'),f('spotCents','固定S本币/一外币（整数百分刻度；200=2）',1)],
  assumption:'独立SYN，起始简化账只有本币贷款/央行准备金/存款/权益并严格平衡。时点t向非居民借入外币，同时取得等额外币非居民银行存款资产；按固定S折本币。此操作没有结售汇、国内新贷款、费用或本金重估。外币本金相抵不证明到期、信用或可用性匹配；净跨境交易可抵销而银行仍依赖外部续借。',
  display:v=>display(flowBankBorrowing({initialLoans:v.initialLoans,initialHomeReserves:v.initialHomeReserves,initialHomeDeposits:v.initialHomeDeposits,equity:v.equity,newBorrowingForeign:v.newBorrowingForeign,spotCents:v.spotCents}),[['foreignDepositAsset','新增外币非居民存款资产（外币）'],['foreignBorrowingLiability','新增外币非居民借款负债（外币）'],['proceedsHome','新增每侧折本币金额'],['initialAssets','起始总资产（本币）'],['finalAssets','操作后总资产（本币）'],['initialLiabilities','起始负债（本币）'],['finalLiabilities','操作后负债（本币）'],['finalEquity','操作后权益（本币）'],['initialLeverage','起始总资产/权益'],['finalLeverage','操作后总资产/权益'],['finalHomeReserves','操作后本币央行准备金'],['finalHomeDeposits','操作后本币存款'],['finalHomeLoans','操作后本币贷款'],['isolatedNewHomeLoan','隔离操作新增国内贷款（给定0）'],['futureActualLending','后续真实贷款审批'],['maturityMatched','外币资产和负债支付期限已匹配']]),
  experiment:'借10外币、S2，每侧增20：总资产100→120、负债90→110、权益10不增，杠杆10→12。初始准备金20、存款90、贷款80不动。借款改0是无新增借款，不是未知；只改单项起始账导致不平衡会STOP，不能自动填权益。',sourceIds:[2,4,5]},
 {id:'C3',title:'融资余量只是信贷菜单的一道门',initial:flowCanonicalInputs.c3,
  fields:[f('fundingRoom','给定合同融资余量（本币整数；不是可直接贷出的准备金）'),f('equity','给定教学权益额（本币非负整数）'),f('capitalFloorBps','给定教学资本比率下限（整数基点；1000=10%）',1,10_000),f('existingRWA','已有教学风险加权资产RWA（本币整数）'),f('newLoanRiskWeightBps','新贷款教学风险权重（整数基点；10000=100%）',1,20_000),f('demand','给定合格需求上限（本币整数；不是自动获批）')],
  assumption:'独立SYN，同一t的人为可行菜单：权益E、已有RWA、正资本下限k、正新风险权重w不变。合同融资余量与合格需求另行给定，不从C2收到的钱或央行准备金推导。资本余量=max(0,(E/k−RWA)/w)，可行新增额度取三门最小；先查整数资本差符号，不让舍入生成余量。这个上限不是实际批准量、PD、真实Basel合规或银行意愿。',
  display:v=>display(flowCreditCeiling({fundingRoom:v.fundingRoom,equity:v.equity,capitalFloorBps:v.capitalFloorBps,existingRWA:v.existingRWA,newLoanRiskWeightBps:v.newLoanRiskWeightBps,demand:v.demand}),[['capitalFloor','教学资本下限k（比例）'],['newLoanRiskWeight','教学新增风险权重w（比例）'],['capitalSlackNumerator','E×10000−RWA×k基点的整数差'],['initialStipulatedFloorSatisfied','起始满足本SYN下限（非法律合规）'],['capitalHeadroom','按教学资本门可增加贷款'],['fundingRoom','独立给定融资门上限'],['demand','独立给定需求门上限'],['feasibleCeiling','三门可行额度上限（非批准量）'],['fundingBinding','融资门达到共同最小值'],['capitalBinding','资本门达到共同最小值'],['demandBinding','需求门达到共同最小值'],['actualLoanApproved','真实贷款批准量'],['actualLenderAppetite','真实银行风险意愿'],['regulatoryCertification','真实监管合规认证']]),
  experiment:'E10、k10%、RWA80、w100%给资本余量20，与融资20并列，需求30，菜单20；融资改40仍20。需求0则菜单0，不能拿“钱已进来”否定需求门。RWA改100资本差恰为0，资本余量0；99/101分别正/负邻点，不能用浮点小正数跨过零边界。',sourceIds:[4,5]},
 {id:'C4',title:'一级融资与旧证券转手的收款人不同',initial:flowCanonicalInputs.c4,
  fields:[f('totalHomePayment','非居民已在岸同银行存款的本次支付额（本币整数）'),f('primaryPct','本次支付用于新发行比例（整数%；40=40%）',0,100),f('unitPriceCents','给定新旧单位同价格（本币百分刻度；500=5）',1),f('availableExistingUnits','居民旧持有人给定可售单位（整数）')],
  assumption:'独立SYN，本窗口T以前非居民付款人已持有足额同一居民结算银行的本币存款。按题设一级支付比例向居民发行人购买新单位，其余向居民旧持有人买旧单位；同一付款人、两个不同收款人，两价格固定同价、单位可分、无费用。不是此窗口又取得新境外现金/兑换。旧单位须足够且整数乘积验证。银行总存款负债只是三人间搬移，未必等于官方居民广义货币口径不变。',
  display:v=>display(flowSecuritySettlement({totalHomePayment:v.totalHomePayment,primaryPct:v.primaryPct,unitPriceCents:v.unitPriceCents,availableExistingUnits:v.availableExistingUnits}),[['unitPrice','给定单位价格（本币）'],['primaryCash','居民发行人收到新发行现金'],['secondaryCash','居民旧持有人收到转手现金'],['newIssuedUnits','新增加的发行单位'],['existingTransferredUnits','转手的已有单位'],['payerDepositChange','非居民付款人存款变化'],['issuerDepositChange','居民发行人存款变化'],['sellerDepositChange','居民旧卖方存款变化'],['totalBankDepositChange','三人合计银行存款负债变化'],['newSecurityExternalLiabilityTransaction','新增非居民持有证券负债交易'],['externalBankDepositLiabilityTransaction','非居民居民银行存款负债交易'],['combinedExternalNetLiabilityTransaction','以上两腿合计外部负债净交易'],['isolatedNewHomeLoan','隔离转账操作新增贷款（给定0）'],['actualInvestment','发行人后续真实投资'],['actualPriceImpact','真实市场价格影响'],['officialBroadMoneyChange','官方广义货币口径变化']]),
  experiment:'默认100中的40给发行人增8单位，60给旧卖方转12单位；不能说发行人得到100。非居民本窗口增持居民证券形成的外部负债交易+100（含60旧证券转手，并非新发行100）、外部存款负债−100抵销。可售旧单位改11会STOP，12恰好放行；一级比例100时旧转手0，不因此证明真实投资100。',sourceIds:[1,3,4]},
 {id:'C5',title:'购汇投放准备金与另行冲销是两笔账',initial:flowCanonicalInputs.c5,
  fields:[f('foreignAssetsInitial','央行起始给定可操作外币资产（外币整数）'),f('spotCents','操作中固定S（本币/外币百分刻度；200=2）',1),f('domesticClaimsInitial','央行起始国内债权（本币整数）'),f('bankReservesInitial','起始商业银行央行准备金（本币整数）'),f('currencyInitial','起始给定流通现金（本币整数）'),f('equity','央行起始简化权益（本币整数）'),f('purchasedForeign','第一笔央行购入外币资产（外币整数）'),f('absorbedHome','第二笔出售已持有国内债权吸收准备金（本币整数）')],
  assumption:'独立SYN，起始央行账按固定S精确平衡。央行先购给定可用外币资产，以新增本币银行准备金付款；随后另向居民银行出售已有国内债权，等额扣准备金。吸收不能超过国内债权或购买后准备金；现金不变、无利息/费用/新政策反馈。本实验明确假设央行操作，不说每次资本流入必然购汇，不替外国资产认证法定储备资格/授权，也不把基础货币视为贷款乘数。',
  display:v=>display(flowCentralBankOperations({foreignAssetsInitial:v.foreignAssetsInitial,spotCents:v.spotCents,domesticClaimsInitial:v.domesticClaimsInitial,bankReservesInitial:v.bankReservesInitial,currencyInitial:v.currencyInitial,equity:v.equity,purchasedForeign:v.purchasedForeign,absorbedHome:v.absorbedHome}),[['purchaseHome','购汇新增准备金（本币）'],['initialAssets','起始央行总资产（本币）'],['assetsAfterPurchase','仅购汇后总资产'],['finalAssets','两笔后总资产'],['initialBase','起始基础货币（准备金+现金）'],['baseAfterPurchase','仅购汇后基础货币'],['finalBase','两笔后基础货币'],['netBaseChange','两笔净基础货币变化'],['finalBankReserves','两笔后银行央行准备金'],['finalForeignAssetsHome','两笔后外币资产折本币'],['finalDomesticClaims','两笔后国内债权'],['finalEquity','两笔后简化权益'],['actualCreditResponse','真实国内信贷变化'],['actualInterestResponse','真实市场利率变化'],['sterilizationCost','真实冲销利息/财政成本']]),
  experiment:'S2购5外币投10准备金，基础90→100；另售10国内债权基础回90，净0；外国资产折本币20→30、国内80→70。吸收改0只有第一笔，基础增10；吸收81超过持有80会STOP。净基础0仍不能填真实信贷反应0或冲销无成本。',sourceIds:[4,6,8]},
 {id:'C6',title:'在到期T能用的外币才是付款菜单',initial:flowCanonicalInputs.c6,
  fields:[f('foreignDue','给定T外币到期付款（外币整数）'),f('foreignLiquid','T已确认可用外币流动资产（未计入单列收款；外币整数）'),f('confirmedForeignReceipts','T单列已确认可支配外币收款（不已含于流动资产；非预测；整数）'),f('homeCash','T本币现金金额（本币整数）'),f('convertibleHomePct','本SYN确认可兑换本币现金比例（整数%）',0,100),f('spotCents','本SYN确认兑换条件S（本币/外币百分刻度）',1)],
  assumption:'独立SYN，同一付款T，外币流动资产与单列收款均题设已确认可支配且不重叠：confirmedForeignReceipts不已包含在foreignLiquid中，不重复计数；本币现金只有给定合同允许比例可无费按S兑换。未承诺流入、被冻结资产、真实授权不能放入这些已确认栏。只兑换所需外币差额，余款保留；整数比较确认全覆盖与恰好0，不用微小浮点余数生成缺口。可用菜单不是法律违约、完整偿付能力或下一笔银行贷款审批。',
  display:v=>display(flowForeignPayment({foreignDue:v.foreignDue,foreignLiquid:v.foreignLiquid,confirmedForeignReceipts:v.confirmedForeignReceipts,homeCash:v.homeCash,convertibleHomePct:v.convertibleHomePct,spotCents:v.spotCents}),[['availableForeign','T已确认可用外币资产+收款'],['foreignStillNeeded','兑换前仍需外币'],['convertibleHomeCapacity','题设可兑换本币现金上限'],['homeUsed','实际计算需用的本币现金'],['boughtForeign','按给定条件可购外币'],['foreignGap','菜单仍缺外币（非违约认证）'],['homeEquivalentGap','上述外币缺口按S折本币'],['endingHomeCash','菜单操作后未用本币现金'],['foreignSurplusBeforeConversion','兑换前已可用外币的超额'],['actualConversionPermission','真实世界兑换授权证据'],['actualFundingRenewal','真实后续外部续借'],['legalDefault','真实法定违约判断']]),
  experiment:'到期10，已可用4+3，仍需3；本币5在S2可买2.5，缺0.5外币（折本币1）。可兑换比例改0则缺3，账有5本币不替外币。现金改6恰好补齐，改7只需用6仍留1；收款超过到期时不无故花掉本币现金。',sourceIds:[1,2,8]},
 {id:'C7',title:'本币基金也会受到卖出现金容量限制',initial:flowCanonicalInputs.c7,
  fields:[f('assetFace','给定本币资产面值单位库存（面值基准每单位1；整数）'),f('executionPricePct','给定候选执行价相对面值（整数%；90=0.9）',1,200),f('buyCapacityFace','同窗口给定买方可承接面值单位（整数）'),f('cash','基金起始本币可用现金（整数）'),f('requestedCash','本窗口给定现金需求（非推断法定赎回额；整数）')],
  assumption:'独立SYN，同窗口本币流动菜单，面值每单位1、候选执行价与买方容量均题设独立给定。按现金需求计算所需单位，执行单位受库存/容量约束；未给真实冲击函数、NAV/赎回规则、费用或完成付款。资产出售是给定条件菜单，不证真实市场成交；请求现金不自动扣除为已付赎回。非居民基金持有人关系需另查，不自动填国际收支净流出。',
  display:v=>display(flowFundCashMenu({assetFace:v.assetFace,executionPricePct:v.executionPricePct,buyCapacityFace:v.buyCapacityFace,cash:v.cash,requestedCash:v.requestedCash}),[['executionPrice','给定候选执行价（本币/面值单位）'],['cashNeed','现有现金之外的给定需求'],['desiredSaleFace','不计库存/容量时所需出售单位'],['executedSaleFace','给定菜单可执行出售单位'],['saleProceeds','给定菜单出售现金'],['attainableCash','起始现金+出售所得可用额'],['cashGap','菜单相对给定需求的现金缺口'],['saleLossRelativeToStipulatedPar','已售单位相对面值损失（负为增益）'],['remainingAssetFace','出售后未售面值库存（未扣赎回）'],['preUseAssetsAtGivenPrice','动用前全库存按给定价+现金'],['preUseAssetsAtStipulatedPar','动用前全库存按面值+现金'],['actuallyPaidRedemption','真实已支付赎回'],['finalPostRedemptionNav','真实完成赎回后的NAV'],['netCrossBorderOutflow','真实BOP净跨境流出'],['endogenousPriceImpact','已识别内生价格冲击']]),
  experiment:'需求30减现金5需25，0.9价理想售约27.7778，但容量20只得18，共23仍缺7；旧面值不是能花的现金。容量改30菜单恰可补齐，不证明赎回已付或实际价格维持0.9。价格200相对面值损失为负即增益，不冒称无成本公允套利。',sourceIds:[2,7,8]},
];
export const flowLabs:readonly FlowLab[]=definitions.map(l=>({...l,display:v=>l.fields.every(f=>Number.isSafeInteger(v[f.key])&&v[f.key]>=f.min&&v[f.key]<=f.max)?l.display(v):{status:'STOP',reason:'39项输入各有自己的整数域；缺失、清空、字符串、非有限或越界不能继承旧结果、默填0或跨用他课网格。'}}));
export const flowLabAudit=[
 {key:'seven independently stipulated valid defaults, unique C identities and exact complete raw key sets',passed:flowLabs.length===7&&new Set(flowLabs.map(l=>l.id)).size===7&&flowLabs.every(l=>l.assumption.includes('独立SYN')&&l.display(l.initial).status==='OK'&&l.fields.map(f=>f.key).sort().join('|')===Object.keys(l.initial).sort().join('|'))},
 {key:'39 complete integer controls with Chinese units; all blank paths STOP instead of stale default',passed:flowLabs.reduce((n,l)=>n+l.fields.length,0)===39&&flowLabs.every(l=>l.fields.every(f=>f.label.length>=10&&f.step===1&&l.display({...l.initial,[f.key]:NaN}).status==='STOP'))},
 {key:'fixed raw amount, sign, quotation, share and positive capital/risk grids do not inherit rate domains',passed:flowLabs[0].fields.every(f=>f.min===-1_000_000)&&flowLabs[2].fields.find(f=>f.key==='capitalFloorBps')?.min===1&&flowLabs[2].fields.find(f=>f.key==='newLoanRiskWeightBps')?.max===20_000&&flowLabs[6].fields.find(f=>f.key==='executionPricePct')?.max===200},
] as const;
