import {fxQuoteTranslation,fxCoveredReturn,fxUncoveredStates,fxConditionalRepricing,fxRelativePriceIndex,fxBalanceSheet,fxTradeInvoice} from './exchangeRateFixtures';
import type {FxStop} from './exchangeRateFixtures';
export type ExchangeRateLabId='C1'|'C2'|'C3'|'C4'|'C5'|'C6'|'C7';
export type ExchangeRateField={key:string;label:string;min:number;max:number;step:1};
export type ExchangeRateRow=readonly[label:string,value:string];
export type ExchangeRateDisplay={status:'OK';rows:readonly ExchangeRateRow[]}|FxStop;
export type ExchangeRateLab={id:ExchangeRateLabId;title:string;assumption:string;initial:Readonly<Record<string,number>>;fields:readonly ExchangeRateField[];display(v:Readonly<Record<string,number>>):ExchangeRateDisplay;experiment:string;sourceIds:readonly number[]};
export function exchangeRateDisplayValue(x:unknown):string{if(x===null)return '未知／未识别（不是0）';if(typeof x==='number')return Number.isInteger(x)?String(x):`≈${Number(x.toPrecision(12))}`;if(typeof x==='boolean')return x?'是':'否';return String(x);}
function display<T extends object>(r:FxStop|{status:'OK';value:T},labels:readonly(readonly[keyof T,string])[]):ExchangeRateDisplay{return r.status==='STOP'?r:{status:'OK',rows:labels.map(([key,label])=>[label,exchangeRateDisplayValue(r.value[key])] as const)};}
const f=(key:string,label:string,min:number,max=1_000_000):ExchangeRateField=>({key,label,min,max,step:1});
const quote=(key:string,label:string)=>f(key,label,1);
const amount=(key:string,label:string)=>f(key,label,0);
const rate=(key:string,label:string)=>f(key,label,-9_000,5_000);
export const exchangeRateCanonicalInputs={
 c1:{oldQuoteCents:700,newQuoteCents:875,foreignUnits:20},
 c2:{spotCents:1000,forwardCents:1040,homeReturnBps:400,foreignReturnBps:100},
 c3:{spotCents:1000,futureACents:800,futureBCents:1200,probabilityAPct:50,homeReturnBps:400,foreignReturnBps:100},
 // Both are alternative conditions at the same valuation t for the same maturity T, not successive trades.
 c4:{oldExpectedFutureCents:1000,newExpectedFutureCents:1030,oldHomeReturnBps:200,newHomeReturnBps:300,foreignReturnBps:100,oldExpectedExcessBps:0,newExpectedExcessBps:0},
 c5:{oldQuoteCents:1000,newQuoteCents:1100,homeIndexOld:100,homeIndexNew:120,foreignIndexOld:100,foreignIndexNew:100},
 c6:{homeAssets:100,homeLiabilities:0,foreignAssets:0,foreignLiabilities:10,oldQuoteCents:700,newQuoteCents:770},
 c7:{foreignReceipts:10,foreignPayments:6,homeFixedCost:20,oldQuoteCents:700,newQuoteCents:770},
} as const;
const definitions:readonly ExchangeRateLab[]=[
 {id:'C1',title:'正向报价、反向币值与同一外币金额',initial:exchangeRateCanonicalInputs.c1,fields:[quote('oldQuoteCents','旧S本币/1外币（整数百分刻度；700=7）'),quote('newQuoteCents','新S本币/1外币（整数百分刻度）'),amount('foreignUnits','给定同一外币金额（独立SYN整数）')],assumption:'独立SYN，S=本币/一单位外币；两个正报价用整数百分刻度，除100才是报价。外币金额不改变、无息/费用/新增交易。旧新数用于翻译同一金额，非真实市场成交或宏观因果；反向币值是1/S，不直接将百分率变号。',display:v=>display(fxQuoteTranslation({oldQuoteCents:v.oldQuoteCents,newQuoteCents:v.newQuoteCents,foreignUnits:v.foreignUnits}),[['oldQuote','旧S本币/1外币'],['newQuote','新S本币/1外币'],['quoteChangePct','S相对变化（%；上升本币贬值）'],['reverseQuoteChangePct','1/S本币反向币值变化（%）'],['oldHomeAmount','旧报价折本币金额'],['newHomeAmount','新报价折本币金额'],['homeAmountChange','纯换算本币金额变化'],['macroCause','真实汇率变化原因']]),experiment:'7到8.75是S升25%，反向币值降20%；20外币从140折到175。将新报价改560，S降20%而反向升25%。将外币金额改0是已知零，不是未知；清空报价或填0则STOP。',sourceIds:[2,6]},
 {id:'C2',title:'同一持有期covered收益：远期合同与理想基准',initial:exchangeRateCanonicalInputs.c2,fields:[quote('spotCents','给定现货S（本币/外币；1000=10）'),quote('forwardCents','给定同到期远期F（百分刻度）'),rate('homeReturnBps','同期间本币简单净回报（基点；400=4%）'),rate('foreignReturnBps','同期间外币简单净回报（基点）')],assumption:'独立SYN，一单位本币今天按S换外币，投资同到期无违约固定支付，并今天按F卖出全部到期外币。借贷/交易/保证金等实际成本未给；中间价算式不证明可执行套利。基点是给定整个持有期简单回报，不是政策年率。理想F是有条件现金流基准，真实预期现货仍未知。',display:v=>display(fxCoveredReturn({spotCents:v.spotCents,forwardCents:v.forwardCents,homeReturnBps:v.homeReturnBps,foreignReturnBps:v.foreignReturnBps}),[['spot','现货S本币/外币'],['forward','到期远期F本币/外币'],['idealForward','无费用同类支付的理想F'],['forwardPoints','给定F−S远期点（报价单位）'],['coveredReturnPct','外币投资套保后本币简单回报（%）'],['homeReturnPct','本币同期间简单回报（%）'],['coveredExcessPp','套保回报减本币回报（百分点）'],['executableProfit','真实可成交净套利利润'],['futureSpotExpectation','真实未来现货期望']]),experiment:'1.01×10.4/10−1=5.04%，对4%为+1.04百分点；理想F=10×1.04/1.01≈10.29703。两币回报都改0，理想F才等于S；没有融资/买卖价不能把正差叫免费利润。',sourceIds:[1]},
 {id:'C3',title:'两状态未对冲：算术、log与倒数先后顺序',initial:exchangeRateCanonicalInputs.c3,fields:[quote('spotCents','今天S（本币/外币；1000=10）'),quote('futureACents','同一未来日期A状态S（百分刻度）'),quote('futureBCents','同一未来日期B状态S（百分刻度）'),f('probabilityAPct','给定A概率（整数%；50=50%）',0,100),rate('homeReturnBps','同期间本币简单回报（整数基点）'),rate('foreignReturnBps','同期间外币简单回报（整数基点）')],assumption:'独立SYN，两个未来现货状态与物理概率由题设给定，不是估计/风险中性概率。外币支付固定且无违约/费，同一期本币回报另给。两个状态即使概率0也必须正且有效；π是算术预期外币本币回报减本币回报，不是EW的log rho。有限浮点log展示不证明风险补偿或套利。',display:v=>display(fxUncoveredStates({spotCents:v.spotCents,futureACents:v.futureACents,futureBCents:v.futureBCents,probabilityAPct:v.probabilityAPct,homeReturnBps:v.homeReturnBps,foreignReturnBps:v.foreignReturnBps}),[['meanFuture','E[S未来]（本币/外币）'],['expectedQuoteChangePct','算术预期S变化（%）'],['expectedForeignReturnPct','未对冲外币投资预期本币简单回报（%）'],['expectedSimpleExcessPp','给定算术预期超额π（百分点）'],['expectedLogQuoteChangePct','E[log(S未来/S今天)]×100（log尺度）'],['logOfMeanQuoteChangePct','log(E[S未来]/S今天)×100'],['meanReciprocal','E[1/S未来]（外币/本币）'],['reciprocalOfMean','1/E[S未来]（外币/本币）'],['expectedReverseQuoteChangePct','反向币值算术预期变化（%）'],['realStateProbabilities','真实物理概率估计'],['realRiskCompensation','真实风险补偿识别']]),experiment:'10的未来8/12各半，算术S变化0但预期log约−2.0411；E[1/S]=0.1041667不同1/10。未对冲回报1%、对本币4%差−3百分点。将两未来报价都设1000，Jensen差消失；不因此认证真实风险为0。',sourceIds:[2]},
 {id:'C4',title:'条件回价：加息与预期终点可以同时改变',initial:exchangeRateCanonicalInputs.c4,fields:[quote('oldExpectedFutureCents','基线给定算术E[S未来]（百分刻度）'),quote('newExpectedFutureCents','新情景给定算术E[S未来]（百分刻度）'),rate('oldHomeReturnBps','基线本币同期间回报（基点）'),rate('newHomeReturnBps','新情景本币同期间回报（基点）'),rate('foreignReturnBps','两情景给定外币同期间回报（基点）'),rate('oldExpectedExcessBps','基线给定π简单预期超额（基点）'),rate('newExpectedExcessBps','新情景给定π简单预期超额（基点）')],assumption:'独立SYN，对两个条件情景分别由π=G外E[S未来]/S−G本回价；π是给定简单超额，非EW log rho或已识别风险厌恶。G本+π须严格正；不是完整一般均衡/市场清算，也不从观察利率推真实预期。结果比较为人为同时固定条件的反事实，不识别加息因果；浮点残差单列。',display:v=>display(fxConditionalRepricing({oldExpectedFutureCents:v.oldExpectedFutureCents,newExpectedFutureCents:v.newExpectedFutureCents,oldHomeReturnBps:v.oldHomeReturnBps,newHomeReturnBps:v.newHomeReturnBps,foreignReturnBps:v.foreignReturnBps,oldExpectedExcessBps:v.oldExpectedExcessBps,newExpectedExcessBps:v.newExpectedExcessBps}),[['oldSpot','基线条件回价S'],['newSpot','新情景条件回价S'],['spotQuoteChangePct','S本币/外币相对变化（%）'],['reverseValueChangePct','反向本币价值变化（%）'],['expectedFutureRevisionPct','给定未来算术期望修订（%）'],['homeReturnChangePp','本币给定回报变化（百分点）'],['newExpectedQuoteChangePct','新S到给定未来期望的算术变化（%）'],['oldConditionResidual','基线有限浮点条件残差'],['newConditionResidual','新情景有限浮点条件残差'],['policyCausalEffect','真实政策加息因果效果'],['realSpotForecast','真实现货预测']]),experiment:'10.1/1.02≈9.90196；10.403/1.03=10.1，利率+1百分点同时预期终点+3%可使S升2%。只将新终点改1000，观察其他不变时S下降约0.970874%；当期升值与从低起点到未来终点预期贬值可同存。',sourceIds:[2,3]},
 {id:'C5',title:'相对价格指数：名义贬值不必实际贬值',initial:exchangeRateCanonicalInputs.c5,fields:[quote('oldQuoteCents','旧S本币/外币（整数百分刻度）'),quote('newQuoteCents','新S本币/外币（整数百分刻度）'),quote('homeIndexOld','本国指定价格指数旧值（正整数）'),quote('homeIndexNew','本国同口径价格指数新值（正整数）'),quote('foreignIndexOld','外国指定价格指数旧值（正整数）'),quote('foreignIndexNew','外国同口径价格指数新值（正整数）')],assumption:'独立SYN，固定各自价格指数定义，只计算相对所给旧期的qIndex=100×S新/S旧×I外新/I外旧÷I本新/I本旧。各国指数不是同篮子货币成本；起点100仅归一基准、不代表均衡。qIndex上升为本币实际贬值，与BIS REER上升代表升值方向相反；不是官方权重重算或绝对PPP估值。',display:v=>display(fxRelativePriceIndex({oldQuoteCents:v.oldQuoteCents,newQuoteCents:v.newQuoteCents,homeIndexOld:v.homeIndexOld,homeIndexNew:v.homeIndexNew,foreignIndexOld:v.foreignIndexOld,foreignIndexNew:v.foreignIndexNew}),[['nominalQuoteChangePct','名义S报价变化（%）'],['homePriceChangePct','本国价格指数变化（%）'],['foreignPriceChangePct','外国价格指数变化（%）'],['normalizedRealIndex','相对旧期100的本课qIndex'],['realQuoteChangePct','qIndex算术变化（%）'],['realLogChangePct','qIndex log变化×100（log尺度）'],['constantRealIndexRequiredQuoteChangePct','若主动固定qIndex所需S变化（%）'],['absolutePppLevel','真实绝对PPP报价水平'],['misvaluation','真实币值高低估程度'],['officialBisIndex','官方BIS REER重算值']]),experiment:'1.1/1.2=0.916667：S升10%而qIndex降8.3333%。外国新指数改110且主动固定qIndex时，所需S升9.0909%非20%−10%。两个本国指数同时乘2，变化不变；更换价格定义则不是改基。',sourceIds:[6,7,8]},
 {id:'C6',title:'币种错配：没有新借款的净权益重估',initial:exchangeRateCanonicalInputs.c6,fields:[amount('homeAssets','本币资产金额（SYN存量）'),amount('homeLiabilities','本币负债金额（SYN存量）'),amount('foreignAssets','外币资产原币金额（SYN存量）'),amount('foreignLiabilities','外币负债原币金额（SYN存量）'),quote('oldQuoteCents','旧S本币/外币（百分刻度；700=7）'),quote('newQuoteCents','新S本币/外币（百分刻度）')],assumption:'独立SYN，同一主体两日期资产负债原币金额固定、按给定S换算；无期间交易、经营费、衍生品/其他价格/违约减记。外币资产可自然对冲但不假定完全可用于当日付款；负账面权益不自动认证法律违约或贷款反应。币种分类不由居民/非居民持有关系推断。',display:v=>display(fxBalanceSheet({homeAssets:v.homeAssets,homeLiabilities:v.homeLiabilities,foreignAssets:v.foreignAssets,foreignLiabilities:v.foreignLiabilities,oldQuoteCents:v.oldQuoteCents,newQuoteCents:v.newQuoteCents}),[['netForeign','净外币资产（外币单位；负为净负债）'],['oldAssets','旧折本币资产'],['newAssets','新折本币资产'],['oldLiabilities','旧折本币负债'],['newLiabilities','新折本币负债'],['oldEquity','旧账面净权益'],['newEquity','新账面净权益'],['equityTranslationChange','纯汇率净权益变化（本币）'],['balanceResidual','有限浮点资产负债桥接残差'],['newBorrowing','本实验新增借款（给定0）'],['actualCreditResponse','真实银行或借款反应'],['legalDefault','真实法律违约判断']]),experiment:'100−10×7=30，100−10×7.7=23；差−7没有新增贷款。把外币资产改5是另情景65到61.5、差−3.5，不是原权益30不变；外币资产改10，两日权益均100但不证明支付期限已匹配。',sourceIds:[4,5]},
 {id:'C7',title:'贸易发票币种：固定收付与净现金换算',initial:exchangeRateCanonicalInputs.c7,fields:[amount('foreignReceipts','同一给定支付日外币收款（SYN）'),amount('foreignPayments','同日外币进口付款（SYN）'),amount('homeFixedCost','同日给定本币其他费用（SYN）'),quote('oldQuoteCents','基线换算S本币/外币（百分刻度）'),quote('newQuoteCents','反事实换算S本币/外币（百分刻度）')],assumption:'独立SYN，同一付款日两种换算报价；外币发票收付与本币费用固定，不是两期顺次实际成交。净现金仅为声明收款−付款−费用，没有库存/折旧/税/应计/对冲；不认证法定会计利润、出口数量、弹性或真实净出口因果。不同收付币种与日期需另分合同。',display:v=>display(fxTradeInvoice({foreignReceipts:v.foreignReceipts,foreignPayments:v.foreignPayments,homeFixedCost:v.homeFixedCost,oldQuoteCents:v.oldQuoteCents,newQuoteCents:v.newQuoteCents}),[['netForeignReceipts','净外币发票收款（外币）'],['oldHomeReceipts','基线折本币收款'],['newHomeReceipts','反事实折本币收款'],['oldHomeImportPayments','基线折本币进口付款'],['newHomeImportPayments','反事实折本币进口付款'],['oldIllustrativeNetCash','基线给定净现金（本币）'],['newIllustrativeNetCash','反事实给定净现金（本币）'],['netCashTranslationChange','纯换算净现金变化（本币）'],['realQuantityResponse','真实出口或进口数量反应'],['macroNetExportEffect','真实宏观净出口效果'],['statutoryAccountingProfit','法定会计利润']]),experiment:'70−42−20=8，77−46.2−20=10.8，差2.8而非收入增加7全变利润。将外币付款改10，给定净现金两情景均−20；净额0不证明无需垫付或期限对冲。',sourceIds:[4,5]},
];
const c4ComparisonClock='两情景共有同一估值日t、未来付款日T与t到T持有期；old/new是两个条件设定（或同终点新闻前后的预期），不是连续实际成交或不同到期日。';
export const exchangeRateLabs:readonly ExchangeRateLab[]=definitions.map(l=>({...l,assumption:l.id==='C4'?c4ComparisonClock+l.assumption:l.assumption,display:v=>l.fields.every(f=>Number.isSafeInteger(v[f.key])&&v[f.key]>=f.min&&v[f.key]<=f.max)?l.display(v):{status:'STOP',reason:'每个控件都须为护照规定的完整整数；缺失、清空、非有限及域外均不继承旧结果。'}}));
export const exchangeRateLabAudit=[
 {key:'seven independent SYN contracts, distinct IDs, valid complete default paths',passed:exchangeRateLabs.length===7&&new Set(exchangeRateLabs.map(l=>l.id)).size===7&&exchangeRateLabs.every(l=>l.assumption.includes('独立SYN')&&l.display(l.initial).status==='OK'&&l.fields.map(f=>f.key).sort().join('|')===Object.keys(l.initial).sort().join('|'))},
 {key:'all37 raw controls STOP when cleared, including zero-probability unused states',passed:exchangeRateLabs.reduce((n,l)=>n+l.fields.length,0)===37&&exchangeRateLabs.every(l=>l.fields.every(f=>l.display({...l.initial,[f.key]:NaN}).status==='STOP'))},
 {key:'quote/rate/probability/index/amount labels explicitly retain grids and object',passed:exchangeRateLabs.every(l=>l.fields.every(f=>f.label.length>=10&&f.step===1&&Number.isFinite(l.initial[f.key])))},
] as const;
