import { fiscalAutomaticRule, fiscalCapacityDiagnostic, fiscalFirstRound, fiscalPathMultipliers, fiscalResponseConvolution, fiscalTeachingLoop, fiscalTransferUses } from './fiscalPolicyFixtures';
import type { FiscalLabId } from '../lessons/fiscalPolicyConcepts';
export type FiscalField = {key:string;label:string;min?:number;max?:number;step:number};
export type FiscalLab = {id:FiscalLabId;title:string;assumption:string;initial:Readonly<Record<string,number>>;fields:readonly FiscalField[];outputs:(values:Readonly<Record<string,number>>)=>readonly (readonly [string,string])[]|null;experiment:string;sourceIds:readonly number[]};
const field=(key:string,label:string,step=1,min?:number,max?:number):FiscalField=>({key,label,step,min,max});
const amount=(value:number|null)=>value===null?'未定义／未识别':value.toFixed(5);
const vector=(values:readonly (number|null)[])=>`[${values.map(amount).join(', ')}]`;

export function fiscalC6FromControls(v:Readonly<Record<string,number>>) {
 if (![0,1].includes(v.baselineIncludes)) return null;
 return fiscalResponseConvolution({baselineLevels:[100,102,104,106],fiscalImpulses:[v.impulse0,v.impulse1,0,0],syntheticResponseKernel:[v.kernel0,v.kernel1,v.kernel2],baselineAlreadyIncludesTheseImpulseEffects:v.baselineIncludes===1});
}

export const fiscalLabs:readonly FiscalLab[]=[
 {id:'C1',title:'同一期间增量：预算账与产出账',assumption:'全部数值为同一基线与期间的SYN变化量，不是水平。G只指已交付购买；转移与税收不直接进入GDP。利息变化及其他财政项为0。私人／贸易变动为声明情景，非观察因果响应。',initial:{purchaseChange:10,transferChange:0,taxChange:0,consumptionChange:0,investmentChange:0,exportChange:0,importChange:0},fields:[field('purchaseChange','已交付政府购买变化 ΔG'),field('transferChange','现金转移变化 ΔTR'),field('taxChange','税款变化 ΔT；减税为负'),field('consumptionChange','私人消费变化 ΔC'),field('investmentChange','私人投资变化 ΔI'),field('exportChange','出口变化 ΔX'),field('importChange','进口变化 ΔM')],outputs:v=>{const r=fiscalFirstRound({deliveredPurchaseChange:v.purchaseChange,cashTransferChange:v.transferChange,taxRevenueChange:v.taxChange,observedPrivateConsumptionChange:v.consumptionChange,observedPrivateInvestmentChange:v.investmentChange,observedExportChange:v.exportChange,observedImportChange:v.importChange});return r?[['GDP变化的简化对账',amount(r.outputAccountingChange)],['初级赤字变化；非赤字水平',amount(r.primaryDeficitChange)],['转移本身的直接GDP记账',amount(r.transferDirectGDPEntry)],['已识别因果乘数',amount(r.causalMultiplier)],['福利效果',amount(r.welfare)]]:null;},experiment:'将G改0、TR改10、C改6：产出账6而财政增量仍10。再恢复，把M改10：产出账0。再次恢复固定基准，保持G=10、其他项0，再将I改−10：产出账0而初级赤字变化仍10，解释私人替代。',sourceIds:[1,7,8]},
 {id:'C2',title:'100户转移的现金用途',assumption:'两个独立教学组40户／60户，每户新增转移1。c为本期间消费用途比例，d为本金偿还比例；残余进入新增金融资产。没有识别MPC、进口、收入反馈或GDP。第三栏不是国民核算全部个人储蓄。',initial:{cConstrained:.7,dConstrained:.2,cLiquid:.3,dLiquid:.1},fields:[field('cConstrained','40户组消费用途比例',.05,0,1),field('dConstrained','40户组本金偿还比例',.05,0,1),field('cLiquid','60户组消费用途比例',.05,0,1),field('dLiquid','60户组本金偿还比例',.05,0,1)],outputs:v=>{const r=fiscalTransferUses([{id:'constrained',households:40,perHouseholdTransfer:1,syntheticConsumptionShare:v.cConstrained,syntheticDebtRepaymentShare:v.dConstrained},{id:'liquid',households:60,perHouseholdTransfer:1,syntheticConsumptionShare:v.cLiquid,syntheticDebtRepaymentShare:v.dLiquid}]);return r?[['总转移',amount(r.transfer)],['消费用途金额',amount(r.consumption)],['本金偿还金额',amount(r.debtRepayment)],['新增金融资产配置',amount(r.financialAssetAccumulation)],['现金用途闭合',r.budgetClosed?'100 = 消费 + 本金偿还 + 金融资产':'未闭合'],['已估计MPC',amount(r.estimatedMPC)],['总GDP反应',amount(r.totalGDPResponse)]]:null;},experiment:'提高60户组的消费比例，比较加权总额；将同一组c+d设大于1，应STOP，不允许负的残余资产伪造预算。',sourceIds:[4,5,7]},
 {id:'C3',title:'既有规则与新立法分开',assumption:'同一教学期间收入基线100、当前90、比例税率0.2。自动转移增加3是显式声明的原资格规则结果，不是由收入估计失业。另立法转移单独输入，税险／其他项目及行为反馈不在本局部账。',initial:{baselineIncome:100,currentIncome:90,taxRate:.2,baselineTransfer:0,automaticTransfer:3,discretionaryTransfer:0},fields:[field('baselineIncome','基线综合收入',1,0),field('currentIncome','当前综合收入',1,0),field('taxRate','不变比例税率',.05,0,1),field('baselineTransfer','基线转移',1,0),field('automaticTransfer','原资格规则触发的额外转移',1,0),field('discretionaryTransfer','另立法新增转移',1,0)],outputs:v=>{const r=fiscalAutomaticRule({baselineIncome:v.baselineIncome,currentIncome:v.currentIncome,unchangedTaxRate:v.taxRate,baselineTransfer:v.baselineTransfer,automaticTransferIncrease:v.automaticTransfer,discretionaryTransferIncrease:v.discretionaryTransfer});return r?[['基线税款',amount(r.baselineTax)],['当前税款',amount(r.currentTax)],['自动初级赤字增量',amount(r.automaticDeficitIncrease)],['基线可用收入',amount(r.baselineDisposable)],['原规则不变：无新政策可用收入',amount(r.noNewPolicyDisposable)],['另立法后可用收入',amount(r.withNewPolicyDisposable)],['裁量新增转移；非外生身份',amount(r.discretionaryImpulse)],['已识别因果乘数',amount(r.causalMultiplier)]]:null;},experiment:'把另立法转移改2：比较裁量2和自动5，勿将7全部称新刺激。修改收入后，自动转移仍是单独声明参数，必须重新解释资格而非默认算法已识别。',sourceIds:[2,3,5]},
 {id:'C4',title:'四轮反馈不等于无限极限',assumption:'固定价格和利率、需求决定输出、资源充足、无额外私人投资与融资反馈。m以新增收入为基数；模型轮非自动季度。所有系数是SYN声明，不采用IMF分组参数。',initial:{purchase:10,taxCut:0,c:.6,t:.2,m:.1,rounds:4},fields:[field('purchase','正的初始购买规模',1,0),field('taxCut','正的初始减税规模',1,0),field('c','声明边际消费比例 c',.05,0,1),field('t','比例税率 t',.05,0,1),field('m','每单位收入额外进口 m',.05,0,1),field('rounds','计入的模型轮数 N',1,1,10000)],outputs:v=>{const r=fiscalTeachingLoop({initialGovernmentPurchase:v.purchase,initialTaxCut:v.taxCut,consumptionShare:v.c,unchangedTaxRate:v.t,importPerIncomeShare:v.m,rounds:v.rounds});return r?[['净国内反馈 q',amount(r.q)],['首轮模型需求',amount(r.firstRound)],['N轮累计模型产出',amount(r.finiteRoundTeachingOutput)],['无限轮模型极限',amount(r.infiniteTeachingOutput)],['尚未计入的模型尾部',amount(r.remainingTeachingTail)],['无限轮购买模型内倍数',amount(r.purchaseMultiplierWithinModel)],['无限轮正减税模型内倍数',amount(r.taxCutMultiplierWithinModel)],['已识别现实乘数',amount(r.empiricalMultiplier)]]:null;},experiment:'N改1和20，解释有限／极限；购买0、减税10，先看到首轮6。c=1、t=m=0会STOP：本实验不定义q=1的有限无限比较。',sourceIds:[4,5]},
 {id:'C5',title:'三个比率、同一完整路径',assumption:'期间0／1／2是相同频率实质SYN流量，不是SAAR、年份或增长百分点。h同时作为时距与累计窗口终点；所有路径由作者声明，没有因果识别。',initial:{g0:10,g1:5,g2:0,y0:8,y1:7,y2:3,h:2},fields:[field('g0','期间0 ΔG'),field('g1','期间1 ΔG'),field('g2','期间2 ΔG'),field('y0','期间0 ΔY'),field('y1','期间1 ΔY'),field('y2','期间2 ΔY'),field('h','时距／累计窗口终点 h',1,0,2)],outputs:v=>{const r=fiscalPathMultipliers({spendingChanges:[v.g0,v.g1,v.g2],realOutputChanges:[v.y0,v.y1,v.y2],horizonIndex:v.h});return r?[['冲击比率 ΔY0/ΔG0',amount(r.impactRatio)],['时距比率 ΔYh/ΔG0',amount(r.horizonRatio)],['累计0…h比率',amount(r.cumulativeRatio)],['0…h累计产出差',amount(r.totalOutputChange)],['0…h累计购买差',amount(r.totalSpendingChange)],['窗口终点；从0开始计数',String(r.cumulativeWindowEndIndex)],['因果身份',r.causalStatus]]:null;},experiment:'h改0：累计变0.8，不偷偷包括后来支出。g0改0：初始分母比率未定义；g0=10、g1=−10、g2=0且h=2，累计分母为0，不能报告无限乘数。',sourceIds:[4,5,7,10]},
 {id:'C6',title:'重叠滞后与完整水平路径',assumption:'四期固定SYN基线[100,102,104,106]不含同一措施效应，冲量后两期固定0；线性核在滞后索引2（二期滞后）之后归零。非年化期间增长差；本实验既非预测也非估计。',initial:{impulse0:10,impulse1:5,kernel0:.8,kernel1:.5,kernel2:.2,baselineIncludes:0},fields:[field('impulse0','期间0新增冲量'),field('impulse1','期间1新增冲量'),field('kernel0','声明当期响应核 k0',.1),field('kernel1','声明一期滞后核 k1',.1),field('kernel2','声明二期滞后核 k2',.1),field('baselineIncludes','基线已含同一效应：0否／1是',1,0,1)],outputs:v=>{const r=fiscalC6FromControls(v);return r?[['四期产出水平差',vector(r.outputDifferences)],['含措施四期产出水平',vector(r.withPolicyLevels)],['期间增长率差：百分点，非年化',vector(r.growthDifferencePercentagePoints)],['核估计身份',r.estimatedKernel?'估计':'声明SYN核，未估计'],['预测身份',r.forecastStatus],['尾部条件',r.tailContract]]:null;},experiment:'期间1新增冲量改0：期间1仍有旧冲击的一期滞后5。基线已含改1，必须STOP；正水平差收缩时增长率效果可以为负。',sourceIds:[5,7,9]},
 {id:'C7',title:'资源不相容时拒绝伪预测',assumption:'需求与额外国内真实资源能力均为独立SYN声明，不是潜在GDP。只诊断固定需求模型相容性，没有价格、资源替代、贸易或生产函数。',initial:{requested:10,capacity:6},fields:[field('requested','请求额外国内真实产出',1,0),field('capacity','声明额外国内真实资源能力',1,0)],outputs:v=>{const r=fiscalCapacityDiagnostic({requestedAdditionalRealDomesticOutput:v.requested,declaredAdditionalRealDomesticCapacity:v.capacity});return r?[['固定需求与资源条件',r.incompatibleTeachingDemand?'不相容：需要新模型':'未发现这项声明约束冲突'],['声明资源差额',amount(r.capacityGap)],['实际产出响应',amount(r.actualOutput)],['价格／通胀响应',amount(r.inflation)],['进口响应',amount(r.imports)],['私人挤出响应',amount(r.privateCrowdingOut)]]:null;},experiment:'资源改12只关闭本项相容性警告，不证明真实产出10。恢复6，解释差额4为何不能自动分给通胀或进口。',sourceIds:[2,4,5]},
];
export const fiscalLabAudit=[
 {key:'C1–C7 each registered once',passed:fiscalLabs.map(({id})=>id).join('|')==='C1|C2|C3|C4|C5|C6|C7'},
 {key:'all initial lab outputs use valid same pure calculators',passed:fiscalLabs.every(lab=>lab.outputs(lab.initial)!==null)},
 {key:'every field has fixed finite input and unique key',passed:fiscalLabs.every(lab=>new Set(lab.fields.map(({key})=>key)).size===lab.fields.length&&lab.fields.every(({key})=>Number.isFinite(lab.initial[key])))},
 {key:'clearing any numeric field stops calculation',passed:fiscalLabs.every(lab=>lab.fields.every(({key})=>lab.outputs({...lab.initial,[key]:NaN})===null))},
] as const;
if(fiscalLabAudit.some(({passed})=>!passed))throw new Error('3.17 draft lab integrity failed');
