import { fiscalC1, fiscalC4, fiscalC5, fiscalC6, fiscalC7, fiscalCanonicalResults, fiscalFirstRound, fiscalPathMultipliers } from './fiscalPolicyFixtures';
export type FiscalChoice={id:string;label:string;value:number;diagnosis:string};
export type FiscalScenario={id:string;title:string;input:string;question:string;choices:readonly FiscalChoice[];correctId:string;explanation:string;sourceIds:readonly number[]};
const choice=(id:string,label:string,value:number,diagnosis:string):FiscalChoice=>({id,label,value,diagnosis});
const firstTransfer=fiscalFirstRound({...fiscalC1,deliveredPurchaseChange:0,cashTransferChange:10,observedPrivateConsumptionChange:6})!;
const imported=fiscalFirstRound({...fiscalC1,observedImportChange:10})!;
const window0=fiscalPathMultipliers({...fiscalC5,horizonIndex:0})!;
const response=fiscalCanonicalResults.c6;
export const fiscalScenarios:readonly FiscalScenario[]=[
 {id:'M1',title:'转移领取不是GDP直接增加',input:'同一SYN期间相对基线：政府新增转移10，无新增购买；家庭消费变化声明6，其他C/I/X/M变化0。',question:'支出侧简化GDP对账是多少？',correctId:'consumption-only',choices:[choice('double-transfer','16',16,'把转移本身10和私人消费6重复相加。转移先进入家庭预算，不直接进G。'),choice('consumption-only','6',firstTransfer.outputAccountingChange,'只把声明的新增消费6记入产出账；还没有因果识别。'),choice('ignore-consumption','0',0,'正确排除转移直接记账，却也丢掉了已声明的消费变化6。')],explanation:'G为0而ΔC为6，其余声明变化0，所以ΔY=6。财政初级赤字变化10和GDP对账6是两张账；消费声明不证明真实政策必然产生6，也不批准因果乘数0.6。',sourceIds:[1,7]},
 {id:'M2',title:'政府采购进口设备',input:'SYN已交付政府购买增加10，进口增加10，私人消费、投资、出口变化0。暂不模拟未来设备生产率。',question:'国内当期GDP的简化变化是多少？',correctId:'net-domestic',choices:[choice('omit-import','10',10,'只记G没有扣除M，把境外生产当成国内生产。'),choice('subtract-twice','−10',-10,'进口已在净出口扣一次，不能再次扣除同一10。'),choice('net-domestic','0',imported.outputAccountingChange,'同一期间G增加10与M增加10抵消；设备价值和未来生产率是其他问题。')],explanation:'ΔG−ΔM=10−10=0。这不是资金消失或设备没有福利，而是当前国内产出的范围；未来投入能否提高供给，需要另外证据。',sourceIds:[1,7]},
 {id:'M3',title:'赤字扩大不自动等于新刺激',input:'SYN收入100→90，原比例税率20%不变；原资格规则触发转移+3。没有新立法或新的购买决定。',question:'相对原规则不变基线，声明裁量新增转移是多少？',correctId:'no-new-policy',choices:[choice('no-new-policy','0',fiscalCanonicalResults.c3.discretionaryImpulse,'税款减少2、自动转移增加3属于原规则状态反馈，裁量处理0。'),choice('all-deficit','5',fiscalCanonicalResults.c3.automaticDeficitIncrease,'把自动预算反馈5误称新政策5；这会混淆经济→预算反向因果。'),choice('tax-only','2',fiscalCanonicalResults.c3.baselineTax-fiscalCanonicalResults.c3.currentTax,'税款减少2仍来自收入下降和旧税率，不是新减税决定。')],explanation:'自动赤字增量为2+3=5，裁量新增转移为0；若另立法加2，才记裁量2。裁量也不天然外生，这里没有估计因果效果。',sourceIds:[2,3,5]},
 {id:'M4',title:'人数权重不能丢掉',input:'同一SYN期间：40户每户转移1、消费比例0.7、本金偿还比例0.2；60户每户转移1、消费比例0.3、本金偿还比例0.1；残余进入新增金融资产。比例均为声明，非估计MPC。',question:'两组本期消费用途总额是多少？',correctId:'population-weighted',choices:[choice('coefficient-average','50',(.7+.3)/2*100,'简单平均两个消费比例后乘总人数，忽略40与60的不同权重。'),choice('one-person-per-group','1',.7+.3,'每组只算一户，把100户误当两户。'),choice('population-weighted','46',fiscalCanonicalResults.c2.consumption,'40×0.7+60×0.3=28+18=46。')],explanation:'总转移100，消费46、本金偿还14、新增金融资产40闭合。第三栏不是国民核算全部个人储蓄；46不是已识别GDP或现实MPC。',sourceIds:[4,5,7]},
 {id:'M5',title:'四轮不是无限极限',input:`SYN初始国内购买${fiscalC4.initialGovernmentPurchase}、正减税${fiscalC4.initialTaxCut}；声明消费比例c=${fiscalC4.consumptionShare}、不变比例税率t=${fiscalC4.unchangedTaxRate}、每单位收入额外进口m=${fiscalC4.importPerIncomeShare}，净国内反馈q=${fiscalCanonicalResults.c4.q}。计入包括首轮的N=${fiscalC4.rounds}轮；固定价格利率、资源充足，模型轮不是自动季度。`,question:'包括首轮的四轮累计教学产出是多少？',correctId:'four-rounds',choices:[choice('infinite-limit','约16.12903',fiscalCanonicalResults.c4.infiniteTeachingOutput,'用了无限轮极限，而题目只计四轮。'),choice('four-rounds','15.79272',fiscalCanonicalResults.c4.finiteRoundTeachingOutput,'10×(1+0.38+0.38²+0.38³)=15.79272。'),choice('first-round','10',10,'只计首轮，漏了已声明反馈的后三轮。')],explanation:'四轮贡献10+3.8+1.444+0.54872=15.79272，余尾约0.33631才到无限极限。所有系数是教学声明，准确级数不证明现实财政倍数。',sourceIds:[4,5]},
 {id:'M6',title:'时距分母仍是初始处理',input:'三期SYN ΔG=[10,5,0]、ΔY=[8,7,3]，时距h=2；全部同频真实期间流量。',question:'按本课horizon定义，期间2（第三个观测期间）的时距比率是多少？',correctId:'initial-denominator',choices:[choice('initial-denominator','0.3',fiscalCanonicalResults.c5.horizonRatio!,'时距分子为期间2的ΔY=3，分母为最初ΔG=10。'),choice('cumulative-estimand','1.2',fiscalCanonicalResults.c5.cumulativeRatio!,'18/15是三期累计比率，算术正确但估计对象不匹配。'),choice('different-period','1.4',7/5,'7/5是期间1当期路径比率，既换了期间又换了分母。')],explanation:'horizon(2)=3/10=0.3。期间2的G为0不使这个初始分母定义失效；初始G为0才使它未定义。SYN路径比率不自带因果识别。',sourceIds:[4,5]},
 {id:'M7',title:'窗口改变，累计两张账都改变',input:'期间0、1、2的独立SYN路径：ΔG=[10,5,0]、ΔY=[8,7,3]，同频实质期间流量、共同单位及同一基线，非SAAR。累计终点H从2改0。',question:'仅累计0…0窗口的比率是多少？',correctId:'matched-window',choices:[choice('full-window','1.2',fiscalCanonicalResults.c5.cumulativeRatio!,'仍用全部三期，忽略用户选择的窗口终点0。'),choice('matched-window','0.8',window0.cumulativeRatio!,'分子和分母都只计第0期，8/10=0.8。'),choice('mixed-window','约0.53333',8/15,'分子只计第0期，分母却计全部三期15，窗口不一致。')],explanation:'H必须同时限定分子分母。期限选择会改变问题，不能只更新界面标签而仍在后台累计未来期间。零累计分母应未定义，不报告无限乘数。',sourceIds:[5,7,10]},
 {id:'M8',title:'期间1还有旧冲击滞后',input:`期间0–3的SYN基线水平${JSON.stringify(fiscalC6.baselineLevels)}不含本措施；各期新增财政冲量${JSON.stringify(fiscalC6.fiscalImpulses)}。声明线性响应核（当期／一期／二期滞后）${JSON.stringify(fiscalC6.syntheticResponseKernel)}，此后归零；期间1的基线水平为102，期间0之前没有本措施冲量。`,question:'期间1由全部声明冲量得到的产出水平差是多少？',correctId:'overlapping-lags',choices:[choice('current-only','4',5*.8,'仅用新冲量5乘当期核0.8，漏掉旧10乘一期滞后0.5。'),choice('level-not-difference','111',response.withPolicyLevels[1],'111是基线102加差9后的水平，不是政策水平差。'),choice('overlapping-lags','9',response.outputDifferences[1],'新冲量4加旧冲量滞后5，共9。')],explanation:'ΔY1=5×0.8+10×0.5=9；含措施水平111。线性核、尾部归零和基线均SYN声明；若基线已含同一效应，不能再加9。',sourceIds:[5]},
 {id:'M9',title:'正水平差不等于正增长效果',input:'SYN基线[100,102,104,106]、含措施水平[108,111,108.5,107]。比较期间1→2的非年化增长率。',question:'处理增长率减基线增长率，百分点是多少？',correctId:'growth-difference',choices:[choice('growth-difference','约−4.21304个百分点',response.growthDifferencePercentagePoints[2]!,'100×(108.5/111−104/102)，两条完整路径分别计算增长。'),choice('currency-as-points','+4.5个百分点',response.outputDifferences[2],'把期间2的货币水平差4.5直接改名增长百分点。'),choice('level-percent','约+4.32692个百分点',4.5/104*100,'4.5/104是期间2相对基线的水平百分比，不是两条增长率之差。')],explanation:'期间2的政策水平仍高于基线，但优势从9缩到4.5，增长效果可为负。计算约−4.21304个百分点，没有使用BEA四次复利年化；若改年化定义，应分别重算两条增长。',sourceIds:[5,7,9]},
 {id:'M10',title:'资源缺口只是诊断',input:`同一SYN真实资源单位：请求额外国内真实产出${fiscalC7.requestedAdditionalRealDomesticOutput}，声明额外国内真实资源能力${fiscalC7.declaredAdditionalRealDomesticCapacity}。没有价格、进口或私人资源替代模型；资源能力不是潜在GDP。`,question:'已声明需求与额外资源能力的差额是多少，而非实际产出？',correctId:'capacity-gap',choices:[choice('capacity-as-output','6',6,'6是声明额外资源能力，不是差额；也不能直接当实际产出预测。'),choice('capacity-gap','4',fiscalCanonicalResults.c7.capacityGap,'声明需求10减资源6，差额4；实际产出和价格仍未知。'),choice('demand-as-gap','10',10,'10是请求需求，不是减去资源能力后的差额。')],explanation:'差额4说明固定需求教学路径不相容，需要新模型。不能把实际产出设min(10,6)=6，或把4全部填成通胀或进口；潜在GDP也不是本课教学硬上限。',sourceIds:[2,4,5]},
];
export const fiscalScenarioAudit=[
 {key:'ten M scenarios with static K twins',passed:fiscalScenarios.length===10&&new Set(fiscalScenarios.map(({id})=>id)).size===10},
 {key:'one correct path and two numerically distinct finite wrong paths',passed:fiscalScenarios.every(s=>s.choices.length===3&&s.choices.filter(c=>c.id===s.correctId).length===1&&new Set(s.choices.map(({id})=>id)).size===3&&new Set(s.choices.map(({value})=>value.toPrecision(12))).size===3&&s.choices.every(c=>Number.isFinite(c.value)&&c.diagnosis.length>10))},
 {key:'all A/B/C correct positions represented',passed:new Set(fiscalScenarios.map(s=>s.choices.findIndex(c=>c.id===s.correctId))).size===3},
] as const;
if(fiscalScenarioAudit.some(({passed})=>!passed))throw new Error('3.17 draft scenario integrity failed');
