import { cashOutLedger, housingC1, housingC2, housingC3, housingC4, housingC5, housingC6, housingC7, housingEquity, housingStress, newLoanCapacity, paymentClocks, recoveryWaterfall, spendingAggregation } from './housingCollateralFixtures';

export const housingFormat = (value: number | null, decimals = 3) => value === null ? '未定义／未估计' : value.toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
export type HousingLabId = 'C1' | 'C2' | 'C3' | 'C4' | 'C5' | 'C6' | 'C7';
export type HousingLabField = { key: string; label: string; min: number; max: number; step: number };
export type HousingLabDefinition = { id: HousingLabId; title: string; assumption: string; fields: readonly HousingLabField[]; initial: Readonly<Record<string, number>>; outputs: (values: Readonly<Record<string, number>>) => readonly (readonly [string, string])[] | null; experiment: string; sourceIds: readonly number[] };
const amount = (key: string, label: string, max = 200): HousingLabField => ({ key, label, min: 0, max, step: 1 });
const rate = (key: string, label: string): HousingLabField => ({ key, label, min: 0, max: 0.02, step: 0.001 });
const f = housingFormat;

export const housingLabs: readonly HousingLabDefinition[] = [
  { id: 'C1', title: '住房权益不是可付款现金', assumption: '单一家庭、一套住房；所有金额为 SYN 货币单位，债务为当前未偿本金。市值不是可立即实现的售价；没有自动补仓条款。', fields: [amount('price', '住房市值'), amount('firstLien', '一押余额'), amount('secondLien', '二押余额'), amount('cash', '可用现金')], initial: housingC1,
    outputs: (v) => { const r = housingEquity({ price: v.price, firstLien: v.firstLien, secondLien: v.secondLien, cash: v.cash }); return r && [['总抵押债务', f(r.debt)], ['房屋权益', f(r.equity)], ['一押 LTV', `${f(r.ltv * 100)}%`], ['合并 CLTV', `${f(r.cltv * 100)}%`], ['仍然可用的现金', f(r.liquidCash)], ['本模型价格触发的按揭追缴', '没有设定；不可推断']]; }, experiment: '把房价改为70，现金保持5。解释权益从20变为−10，但现金为什么不会机械变成−10。再加入二押，观察仅报一押LTV怎样漏掉风险。', sourceIds: [2, 5, 7] },
  { id: 'C2', title: '新买家的抵押、付款与首付三道门', assumption: 'SYN；新贷款月末等额本息，月息为小数而非年利率；240期。80%是教学LTV上限，付款预算已扣其他义务，不是任何法定DSR。审批／提款仍未知。', fields: [amount('price', '房价'), { key: 'maxLtv', label: '教学最高LTV（小数）', min: 0, max: 1, step: 0.05 }, { key: 'paymentBudget', label: '可用于P&I的月预算', min: 0, max: 2, step: 0.05 }, rate('monthlyRate', '新合同月息（小数）'), { key: 'months', label: '期数（月）', min: 1, max: 480, step: 1 }, amount('cash', '首付可用现金'), amount('fees', '购房费用')], initial: housingC2,
    outputs: (v) => { const r = newLoanCapacity({ price: v.price, maxLtv: v.maxLtv, paymentBudget: v.paymentBudget, monthlyRate: v.monthlyRate, months: v.months, cash: v.cash, fees: v.fees }); return r && [['抵押容量', f(r.collateralCap)], ['付款容量', f(r.paymentCap)], ['两者较小值', f(r.capacity)], ['按容量借满时自有资金＋费用', f(r.cashNeededAtCap)], ['首付资金缺口', f(r.cashGapAtCap)], ['绑定门槛', r.bindingGate === 'payment' ? '月付款' : r.bindingGate === 'collateral' ? '抵押' : '两者相等'], ['按容量完成购房可行性', r.feasibleAtCap ? '通过本实验现金门；并非实际批准' : '现金不足；并非实际成交']]; }, experiment: '先把最高LTV提高到90%，再把月息降为0.003。为什么第一步可能完全不增加容量？最后把可用现金补到40，区分借款可行性与贷款人批准。', sourceIds: [1, 2, 7] },
  { id: 'C3', title: 'cash-out必须经过清旧债和费用对账', assumption: '一次再融资成交；旧债本金75在同一次交割全部清偿，无保留二押。旧贷应计未付利息声明为0，其他交割收费均计入费用2；改变这些假设需另补资金用途。容量90、批准85、实际借入85是三栏不同证据。费用由成交池支付；金额SYN。', fields: [amount('capacity', '可借容量'), amount('approved', '已批准金额'), amount('drawn', '实际借入金额'), amount('dischargedDebt', '同次清偿旧债本金（未付利息=0）'), amount('fees', '全部另计交割费用')], initial: housingC3,
    outputs: (v) => { const r = cashOutLedger({ capacity: v.capacity, approved: v.approved, drawn: v.drawn, dischargedDebt: v.dischargedDebt, fees: v.fees }); return r && [['清偿与费用用途', f(r.closingUses)], ['真正额外现金', f(r.cashOut)], ['需另外提供的交割现金', f(r.cashRequired)], ['成交后的这笔新债存量', f(r.newDebt)], ['新旧存量差', f(r.netDebtIncrease)], ['旧债保留在新存量中？', '否；该旧债已经清偿']]; }, experiment: '把实际借入降至70；不能再把批准85当作现金。出现交割现金需求意味着必须补入外部现金才能完成旧债清偿，不能假定不足部分也已成功偿还。', sourceIds: [2, 9] },
  { id: 'C4', title: '固定、重置与新合同不是同一个时钟', assumption: '同一比较日余额70、剩余240月。FRM月息0.004不变；ARM仅在本日重置时改为0.006，本实验忽略cap并禁止解释为真实产品报价。税险0.1可独立变化。', fields: [amount('principal', '比较日本金'), rate('oldMonthlyRate', '原合同月息'), rate('resetMonthlyRate', '假设重置月息'), { key: 'remainingMonths', label: '比较日剩余月数', min: 1, max: 480, step: 1 }, { key: 'resetDueNow', label: '本日是否到ARM重置日（0否／1是）', min: 0, max: 1, step: 1 }, { key: 'income', label: '月收入', min: 0, max: 10, step: 0.1 }, { key: 'necessarySpending', label: '其他必要月支出', min: 0, max: 10, step: 0.1 }, { key: 'taxInsurance', label: '月税险及额外住房支出', min: 0, max: 5, step: 0.1 }], initial: { ...housingC4, resetDueNow: 0 },
    outputs: (v) => { if (![0, 1].includes(v.resetDueNow)) return null; const r = paymentClocks({ principal: v.principal, oldMonthlyRate: v.oldMonthlyRate, resetMonthlyRate: v.resetMonthlyRate, remainingMonths: v.remainingMonths, resetDueNow: v.resetDueNow === 1, income: v.income, necessarySpending: v.necessarySpending, taxInsurance: v.taxInsurance }); return r && [['FRM固定P&I', f(r.fixedPi, 6)], ['本日若重置后的ARM P&I', f(r.hypotheticalResetPi, 6)], ['当前ARM真正适用的P&I', f(r.currentArmPi, 6)], ['FRM含声明税险的总住房付款', f(r.fixedTotalHousingPayment, 6)], ['FRM月预算余额', f(r.fixedMonthlySurplus, 6)], ['ARM月预算余额', f(r.armMonthlySurplus, 6)], ['仅因房价下跌导致FRM P&I变化', f(r.priceTriggeredFixedPaymentChange)]]; }, experiment: '将重置标记从0改为1，再独立提高税险支出。为什么固定P&I、总住房账单和可支配现金不是同一条线？未来月份必须重新登记余额和剩余期数。', sourceIds: [7, 10] },
  { id: 'C5', title: '负权益和付款困难必须二维诊断', assumption: 'SYN；房价是快照，收入／必要支出／P&I是每月流量。未来12个月冻结这些数，现金仅用来填赤字；不计新融资、消费重配、税险、利息收入、收入恢复。不是违约模型。', fields: [amount('price', '住房市值'), amount('debt', '住房债务'), { key: 'income', label: '月收入', min: 0, max: 5, step: 0.1 }, { key: 'necessarySpending', label: '其他必要月支出', min: 0, max: 5, step: 0.1 }, { key: 'pi', label: '声明合同月P&I', min: 0, max: 5, step: 0.1 }, { key: 'cash', label: '起始可用现金', min: 0, max: 20, step: 0.1 }, { key: 'months', label: '冻结预算窗口（月）', min: 1, max: 120, step: 1 }], initial: housingC5,
    outputs: (v) => { const r = housingStress({ price: v.price, debt: v.debt, income: v.income, necessarySpending: v.necessarySpending, pi: v.pi, cash: v.cash, months: v.months }); return r && [['房屋权益', f(r.equity)], ['动用现金前月预算余额', f(r.monthlyBalance)], ['动用现金前月赤字', f(r.monthlyGap)], ['冻结赤字下现金可覆盖月数', f(r.cashRunwayMonths)], ['窗口累计赤字（未用现金）', f(r.windowGapBeforeCash)], ['动用现金后的窗口缺口', f(r.unfundedWindowGap)], ['实际逾期／违约／止赎', '均未知；没有事件观察']]; }, experiment: '对房价100／70与收入2／1.2交叉试四次。价格低不必产生付款困难，价格高也不保证月度现金足够；现金可覆盖7.5个月不是第7.5个月必然违约。', sourceIds: [2, 4, 5] },
  { id: 'C6', title: '实际处置以后才计算抵押回收不足', assumption: 'SYN；必须已成交，先支付费用，再按本实验声明的优先债50→次级债20分配；不设税留置权、担保、追索、减记或后续收款。这个排序不是KMV的HELOC排序，也不是通用法律规则。', fields: [amount('salePrice', '已成交售价'), amount('saleCosts', '优先支付的处置费用'), amount('seniorClaim', '声明优先债权'), amount('juniorClaim', '声明次级债权')], initial: housingC6,
    outputs: (v) => { const r = recoveryWaterfall({ salePrice: v.salePrice, saleCosts: v.saleCosts, seniorClaim: v.seniorClaim, juniorClaim: v.juniorClaim }); return r && [['净处置池', f(r.netProceeds)], ['优先债权抵押回收', f(r.seniorRecovery)], ['次级债权抵押回收', f(r.juniorRecovery)], ['业主剩余', f(r.ownerResidual)], ['优先债权抵押回收不足', f(r.seniorUnrecovered)], ['次级债权抵押回收不足', f(r.juniorUnrecovered)], ['最终法律追索／债权人损失', '未知；未计后续追偿、担保、成本与时间']]; }, experiment: '把售价改成40，解释优先债权为什么也会受损；再改成100，核对业主剩余27。售价是实际处置值，不能直接替换成全国指数或先前评估价。', sourceIds: [4, 6] },
  { id: 'C7', title: '异质家庭的合成支出响应怎样聚合', assumption: '100户：40流动性充足业主、40受限业主、20租户。每户住房价值快照冲击−10／−5／0 SYN；响应为下一12个月累计支出变化。0.02／0.06／0均为教学系数，不是经验MPC或国家乘数；无收入及价格第二轮反馈。', fields: [{ key: 'liquidResponse', label: '流动业主合成响应系数', min: 0, max: 1, step: 0.01 }, { key: 'constrainedResponse', label: '受限业主合成响应系数', min: 0, max: 1, step: 0.01 }, { key: 'constrainedShock', label: '受限业主每户价值冲击（SYN）', min: -50, max: 50, step: 1 }], initial: { liquidResponse: 0.02, constrainedResponse: 0.06, constrainedShock: -5 },
    outputs: (v) => { const r = spendingAggregation(housingC7.map((group, i) => i === 0 ? { ...group, syntheticResponse: v.liquidResponse } : i === 1 ? { ...group, syntheticResponse: v.constrainedResponse, perHouseholdValueShock: v.constrainedShock } : group)); return r && [['家庭总数', f(r.households, 0)], ['总住房价值冲击（SYN）', f(r.totalValueShock)], ['下一12月总合成支出响应（SYN）', f(r.totalSpendingChange)], ['每户平均支出变化', f(r.perHouseholdSpendingChange)], ['聚合响应／冲击比（非估计MPC）', f(r.aggregateResponseRatio, 6)], ['未加权系数均值（不可代替聚合）', f(r.unweightedResponseMean, 6)], ['全国总需求乘数／因果估计', '未估计']]; }, experiment: '把受限组价值冲击改为+10：两组价值冲击相互抵消，但支出响应并不抵消，聚合响应比变为未定义。这说明不能把分组系数简单平均后称为“住房财富效应”。', sourceIds: [2, 3] },
];

export const housingLabDefinitionsAudit = housingLabs.map((lab) => ({ key: `${lab.id} initial fields and pure output close`, passed: lab.fields.every(({ key, min, max }) => Number.isFinite(lab.initial[key]) && lab.initial[key] >= min && lab.initial[key] <= max) && lab.outputs(lab.initial) !== null }));
