import {jointCanonicalInputs,jointPurchasingPower,jointRandomPurchasingPower,jointConsolidation,jointInterestCost,jointRemittanceLedger,jointRealBudgetIdentity,jointLeeperRootConfiguration} from './jointPolicyFixtures';
import {jointLabs,jointDisplayValue} from './jointLabDefinitions';
import type {JointResult} from './jointPolicyFixtures';
import type {JointLabId} from './jointLabDefinitions';
function value<T>(r:JointResult<T>):T{if(r.status==='STOP')throw new Error(`Invalid scenario: ${r.reason}`);return r.result;}
export type JointScenario={id:string;labId:JointLabId;title:string;question:string;inputs:Readonly<Record<string,number>>;unit:string;correct:number;reason:string;wrong:readonly{value:number;label:string;diagnosis:string}[];sourceIds:readonly number[]};
const c=jointCanonicalInputs;
const cash={...c.c4,paidReservePrincipal:40,noninterestCashPrincipal:20};
const recovery={income:5,expense:0,initialDeferredEarningsRequirement:18};
const remit={income:25,expense:0,initialDeferredEarningsRequirement:18};
export const jointScenarios:readonly JointScenario[]=[
 {id:'M1',labId:'C1',title:'比例收益不能被近似替代',question:'给定价格路径中，单期净购买力收益的比例定义是多少？选择由比例式得到的值，不选线性近似。',inputs:c.c1,unit:'%',correct:value(jointPurchasingPower(5,2)).realScenarioPercent,reason:'支付总倍数1.05除价格总倍数1.02再减1，约2.94117647%；近似3%方便但不是本题精确比例。',wrong:[{value:5-2,label:'把差值近似当精确比例',diagnosis:'差值省略比例的价格分母，近似可以有用，但本题已明确比例定义。'},{value:2,label:'把价格涨幅当购买力收益',diagnosis:'价格涨幅是支付购买力的分母变化，不是持有人净收益。'}],sourceIds:[1,4]},
 {id:'M2',labId:'C2',title:'先倒数还是先平均',question:'两种价格情景各一半时，平均各情景的净购买力收益是多少？',inputs:c.c2,unit:'%',correct:value(jointRandomPurchasingPower(5,0,10,.5)).meanRealReturnPercent,reason:'0.5×5%+0.5×(105/110−1)×100≈0.22727273%，不等于把平均价格涨幅5%直接代入后所得0。',wrong:[{value:0,label:'先把平均价格代入',diagnosis:'一般不能将期望与取倒数交换；这个0是另一个问题的正确计算。'},{value:5,label:'固定名义率就等于固定真实收益',diagnosis:'两种情景购买力分母不同，即使名义支付固定，真实收益仍不同。'}],sourceIds:[4]},
 {id:'M3',labId:'C3',title:'内部60不能抹掉外部60',question:'交换瞬间，合并公共部门对私人持有者的外部本金总额是多少？',inputs:c.c3,unit:'SYN存量',correct:value(jointConsolidation(100,60)).consolidatedExternalPrincipal,reason:'内部国债对60抵消；私人长债40和银行准备金60都在公共部门外，合计100。',wrong:[{value:100-60,label:'只保留私人长债',diagnosis:'把央行负债一侧的准备金60漏掉，误将统计合并当外部债务减少。'},{value:0,label:'央行购债就注销全部外债',diagnosis:'购债是资产和负债重组，不是私人债权全部消失；本例连财政购买也为0。'}],sourceIds:[3,9]},
 {id:'M4',labId:'C4',title:'旧票息与准备金率各有一张账',question:'按给定一期本金及合约率，对外合约利息合计是多少？',inputs:c.c4,unit:'SYN期间流',correct:value(jointInterestCost(40,3,0,6,60,6,0)).totalExternalInterest,reason:'固定债40×3%=1.2，准备金60×6%=3.6，合计4.8；重定价债本金0不贡献费用。',wrong:[{value:100*.06,label:'全部本金按当前6%重定价',diagnosis:'既有固定息债仍按旧票息；本金100不是一种统一重定价合约。'},{value:40*.03,label:'准备金叫货币，所以漏掉其付息',diagnosis:'付息准备金是公共部门外部负债，合约费用3.6不能删除。'}],sourceIds:[3]},
 {id:'M5',labId:'C4',title:'现金契约利息0不是全部成本0',question:'另一个独立现金构成情景中，对外合约利息合计是多少？',inputs:cash,unit:'SYN期间流',correct:value(jointInterestCost(40,3,0,6,40,6,20)).totalExternalInterest,reason:'1.2固定债利息+2.4准备金利息+0现金契约利息=3.6。外部本金仍100，全部经济代价未知，替换额20不创造财政收入。',wrong:[{value:1.2+60*.06,label:'现金也按准备金率付息',diagnosis:'题设现金明确非付息，不能把它重新并入付息准备金60。'},{value:0,label:'有现金就让所有费用为0',diagnosis:'只现金契约利息为0；固定债与准备金费用仍为正，全部经济成本未计算。'}],sourceIds:[3]},
 {id:'M6',labId:'C5',title:'亏损叠加旧恢复要求',question:'本简化账中，期末尚需恢复的累计净收益是多少？',inputs:c.c5,unit:'SYN存量',correct:value(jointRemittanceLedger(20,30,5)).newDeferredEarningsRequirement,reason:'本期净收益−10叠加旧要求5，新要求15，简化汇款0；没有已知财政立即注资额。',wrong:[{value:30-20,label:'只记本期亏损',diagnosis:'漏掉期初累计恢复要求5；净收益流量不是期末累计存量。'},{value:0,label:'亏损自动由财政现款抹去',diagnosis:'本例没有这样的自动注资承诺；不能以0替代未知财政行为。'}],sourceIds:[6]},
 {id:'M7',labId:'C5',title:'正收益不一定立即汇款',question:'正净收益5、期初恢复要求18，期末尚需恢复的累计净收益是多少？',inputs:recovery,unit:'SYN存量',correct:value(jointRemittanceLedger(5,0,18)).newDeferredEarningsRequirement,reason:'5先抵减18，剩13，简化汇款仍0；“正收益”不等于“全部已可汇财政”。',wrong:[{value:18,label:'正收益不减少累计要求',diagnosis:'漏掉本期正净收益用于恢复的5。'},{value:0,label:'有正收益就恢复完毕',diagnosis:'5小于18，仍有13未恢复；不能不顾规模只看正负。'}],sourceIds:[6]},
 {id:'M8',labId:'C5',title:'超过恢复要求的余数',question:'正净收益25、旧恢复要求18，本例简化汇款是多少？',inputs:remit,unit:'SYN期间流',correct:value(jointRemittanceLedger(25,0,18)).simplifiedRemittance,reason:'先恢复18，余下7才简化汇款；本例不包含完整法定资本/盈余等调整。',wrong:[{value:25,label:'全部正收益立即汇款',diagnosis:'尚需先处理题设旧要求18，不能漏掉恢复门。'},{value:18,label:'把恢复金额当汇款',diagnosis:'用于恢复的18和对财政汇出的7是不同用途，不能互换。'}],sourceIds:[6]},
 {id:'M9',labId:'C6',title:'期末余额与融资净增量',question:'给定真实输入，一期结束时真实付息债余额是多少？不是问净增量或发行总额。',inputs:c.c6,unit:'SYN真实存量',correct:value(jointRealBudgetIdentity(100,3,10,5)).newRealBondPrincipal,reason:'100+3+10−5=108，净增量8；总发行需本金安排，名义价格未知。',wrong:[{value:3+10-5,label:'把净增量8当余额',diagnosis:'净融资流不是期末债务存量，余额还包括期初100。'},{value:100+10,label:'忽略利息与非付息净融资',diagnosis:'本例利息3与净融资5都有明确范围，不能只加初级赤字。'}],sourceIds:[3,5]},
 {id:'M10',labId:'C7',title:'规则斜率不等于根或OLS斜率',question:'按原模型单位，货币局部根αβ是多少？给出这个数不认证完整均衡。',inputs:c.c7,unit:'无量纲',correct:value(jointLeeperRootConfiguration(.8,2,1)).monetaryRoot,reason:'αβ=2×0.8=1.6；财政根1/0.8−1=0.25，两根配置I。正稳态与完整均衡仍未求解。',wrong:[{value:2,label:'把结构斜率α直接当根',diagnosis:'原模型根还需要折现参数β，不是仅看α>1。'},{value:.6,label:'把均衡OLS斜率冒认结构α',diagnosis:'正文独立OLS反例ρ=.6、β=.8的均衡斜率.75乘β给.6，却不等于题设结构α=2的根。额外ρ只是错路径说明，不是本C7新增参数。'}],sourceIds:[4]},
];
export function jointScenarioInputText(s:JointScenario){const lab=jointLabs.find(l=>l.id===s.labId)!;return lab.fields.map(f=>`${f.label}＝${jointDisplayValue(s.inputs[f.key])}`).join('；');}
const optionOrders:Readonly<Record<string,readonly number[]>>={M1:[0,1,2],M2:[1,2,0],M3:[1,0,2],M4:[2,0,1],M5:[0,2,1],M6:[2,1,0],M7:[1,2,0],M8:[1,0,2],M9:[0,1,2],M10:[2,0,1]};
export function jointOptions(s:JointScenario){const order=optionOrders[s.id];if(!order)throw new Error(`Missing option order: ${s.id}`);const records=[{id:`${s.id}-correct`,value:s.correct,diagnosis:s.reason,correct:true},...s.wrong.map((w,i)=>({id:`${s.id}-wrong-${i+1}`,value:w.value,diagnosis:w.diagnosis,correct:false}))];return order.map(i=>records[i]);}
export const jointScenarioAudit=[
 {key:'ten shared M/K scenarios, each three finite distinct closed values',passed:jointScenarios.length===10&&jointScenarios.every(s=>s.wrong.length===2&&jointOptions(s).every(o=>Number.isFinite(o.value))&&new Set(jointOptions(s).map(o=>o.value)).size===3)},
 {key:'every M/K retains all Chinese input labels from its same C contract',passed:jointScenarios.every(s=>{const l=jointLabs.find(l=>l.id===s.labId)!;return Object.keys(s.inputs).sort().join('|')===l.fields.map(f=>f.key).sort().join('|')&&l.display(s.inputs).status==='OK'&&l.fields.every(f=>jointScenarioInputText(s).includes(`${f.label}＝${jointDisplayValue(s.inputs[f.key])}`));})},
 {key:'stable option identities, one correct value and two unchanged diagnoses; no pre-answer evaluation labels',passed:jointScenarios.every(s=>{const o=jointOptions(s);return new Set(o.map(v=>v.id)).size===3&&o.filter(v=>v.correct).length===1&&o.find(v=>v.correct)?.value===s.correct&&s.wrong.every(w=>o.some(v=>!v.correct&&v.value===w.value&&v.diagnosis===w.diagnosis))&&o.every(v=>!Object.prototype.hasOwnProperty.call(v,'label'));})},
 {key:'fixed shared ABC ordering balances correct positions across ten M/K scenarios (3/4/3)',passed:'ABC'.split('').map((_,i)=>jointScenarios.filter(s=>jointOptions(s).findIndex(o=>o.correct)===i).length).join('/')==='3/4/3'&&jointScenarios.every(s=>optionOrders[s.id].length===3&&new Set(optionOrders[s.id]).size===3&&optionOrders[s.id].every(i=>Number.isInteger(i)&&i>=0&&i<3))},
] as const;
