import {jointCanonicalInputs,jointPurchasingPower,jointRandomPurchasingPower,jointConsolidation,jointInterestCost,jointRemittanceLedger,jointRealBudgetIdentity,jointLeeperRootConfiguration} from './jointPolicyFixtures';
import type {JointResult} from './jointPolicyFixtures';
export type JointLabId='C1'|'C2'|'C3'|'C4'|'C5'|'C6'|'C7';
export type JointField={key:string;label:string;min?:number;max?:number;step:number};
export type JointRow=readonly[label:string,value:string];
export type JointLabDisplay={status:'OK';rows:readonly JointRow[]}|{status:'STOP';reason:string};
export type JointLab={id:JointLabId;title:string;assumption:string;initial:Readonly<Record<string,number>>;fields:readonly JointField[];display(v:Readonly<Record<string,number>>):JointLabDisplay;experiment:string;sourceIds:readonly number[]};
export function jointDisplayValue(v:unknown):string {if(v===null)return '未知／未识别（不是0）';if(typeof v==='boolean')return v?'是':'否';if(typeof v==='number')return Number.isInteger(v)?String(v):`≈${Number(v.toPrecision(12))}`;return String(v);}
function display<T extends object>(r:JointResult<T>,labels:readonly(readonly[keyof T,string])[]):JointLabDisplay{return r.status==='STOP'?r:{status:'OK',rows:labels.map(([key,label])=>[label,jointDisplayValue(r.result[key])] as const)};}
const rate=(key:string,label:string,min=-99.99):JointField=>({key,label,min,max:100,step:.01});
const amount=(key:string,label:string,signed=false):JointField=>({key,label,min:signed?-1_000_000:0,max:1_000_000,step:1});
export const jointLabs:readonly JointLab[]=[
 {id:'C1',title:'给定单期购买力：比例与差值近似',assumption:'独立SYN，单期无违约／费用，名义本息与商品篮子价格路径给定；非随机均衡。净率输入以百分数表示、只能是整数基点，范围−99.99%至100%。最后除法与显示为浮点近似，不把输入情景认定为政策造成的价格。',initial:jointCanonicalInputs.c1,fields:[rate('nominalNetPercent','单期名义净收益率（%）'),rate('inflationScenarioPercent','给定单期价格涨幅（%）')],display:v=>display(jointPurchasingPower(v.nominalNetPercent,v.inflationScenarioPercent),[['grossNominal','名义本息总倍数'],['priceRatio','商品篮子价格总倍数'],['realScenarioPercent','给定情景净购买力收益（%）'],['linearApproximationPercent','名义减价格涨幅的线性近似（%）'],['approximationGapPercentagePoints','比例减线性近似（百分点）'],['stochasticExpectedRealReturn','随机预期真实回报'],['causalInflationResponse','政策对通胀的因果响应']]),experiment:'先手算105/102−1，再分别改名义7、价格6。较高名义率是否仍可有较低情景购买力收益？将价格清空或输入−100，应STOP而不是输出0。',sourceIds:[1,4]},
 {id:'C2',title:'两价格情景：先取倒数再平均',assumption:'独立SYN，一个固定名义支付、两种给定价格情景；两率各遵守C1域，概率以0至1输入、整数百分点网格（步长0.01）。即使概率0，另一情景也必须满足输入域。本实验不估计分布、不求政策利率；不是S/W的前瞻货币需求模型。',initial:jointCanonicalInputs.c2,fields:[rate('nominalNetPercent','固定单期名义净收益率（%）'),rate('inflationAPercent','价格情景A涨幅（%）'),rate('inflationBPercent','价格情景B涨幅（%）'),{key:'probabilityA',label:'情景A概率（0至1；0.50即50%）',min:0,max:1,step:.01}],display:v=>display(jointRandomPurchasingPower(v.nominalNetPercent,v.inflationAPercent,v.inflationBPercent,v.probabilityA),[['meanInflationPercent','给定分布平均价格涨幅（%）'],['realReturnAPercent','情景A净购买力收益（%）'],['realReturnBPercent','情景B净购买力收益（%）'],['meanRealReturnPercent','两情景平均净购买力收益（%）'],['plugInMeanReturnPercent','先平均价格再代入所得（%）'],['meanVersusPlugInGapPercentagePoints','先倒数再平均相对代入均值的差（百分点）'],['equilibriumNominalPolicyRate','均衡政策名义率'],['scenarioDistributionEstimated','是否估计了真实价格分布']]),experiment:'先算0%／10%各一半、固定名义5%的结果；把两情景改相同，应使两种平均相同。把概率改0或1可检查退化分布；不能将SYN概率说成真实预测。',sourceIds:[4]},
 {id:'C3',title:'瞬时面值交换：内部抵消与外部本金',assumption:'独立SYN，央行向私人银行以面值买政府长债；初始银行持有全部国债、央行没有国债／准备金／现金，无手续费、重估或当期财政购买。只展示交换瞬间；本金额为0至1e6的整数合成单位，购买不能超原债。非银行出售的存款层不在本例。',initial:jointCanonicalInputs.c3,fields:[amount('treasuryBondPrincipal','财政原国债本金（SYN）'),amount('centralBankPurchaseAtPar','央行面值购买额（SYN）')],display:v=>display(jointConsolidation(v.treasuryBondPrincipal,v.centralBankPurchaseAtPar),[['treasuryGrossBondPrincipal','财政单体国债负债本金'],['centralBankInternalBondAsset','央行持有内部国债资产'],['internalBondPairRemoved','合并抵消的内部资产／负债对'],['privateLongBondPrincipal','私人持有长期国债本金'],['paidReservePrincipal','银行准备金本金'],['consolidatedExternalPrincipal','合并公共部门外部本金总额'],['externalPrincipalReduction','本例外部本金减少额'],['fiscalSpendingCreatedBySwap','该交换创造的财政购买'],['marketRevaluation','市场重估'],['institutionalPermissionsMerged','统计合并是否合并法定权限']]),experiment:'手算100债／购买60，区分60内部抵消和40+60外部本金。把购买改100再改101：前者外部本金仍100，后者STOP。不把资产交换额填进财政购买G。',sourceIds:[3,9]},
 {id:'C4',title:'给定本金的一期利息：不同再定价门',assumption:'独立SYN，所有本金固定为一期初值、整数0至1e6；率对应同一教学期间、非现实年率，0%至100%且整数基点。固定债用旧票息，已声明本期重定价债用本期率，準备金用其付息率；排除本金偿还、费用融资、市场估值、资产收入与全部经济代价，不做债务预测。',initial:jointCanonicalInputs.c4,fields:[amount('fixedBondPrincipal','固定息债期初本金（SYN）'),rate('fixedCouponPercent','固定债旧票息（本期%）',0),amount('repricingBondPrincipal','已声明本期重定价债本金（SYN）'),rate('newBondRatePercent','重定价债本期率（%）',0),amount('paidReservePrincipal','付息准备金期初本金（SYN）'),rate('reserveRatePercent','准备金本期付息率（%）',0),amount('noninterestCashPrincipal','非付息现金期初本金（SYN）')],display:v=>display(jointInterestCost(v.fixedBondPrincipal,v.fixedCouponPercent,v.repricingBondPrincipal,v.newBondRatePercent,v.paidReservePrincipal,v.reserveRatePercent,v.noninterestCashPrincipal),[['fixedBondInterest','固定债利息（SYN期间流）'],['repricingBondInterest','重定价债利息（SYN期间流）'],['reserveInterest','准备金利息（SYN期间流）'],['noninterestCashContractualInterest','现金契约利息（SYN期间流）'],['totalExternalInterest','对外合约利息合计（SYN期间流）'],['externalPrincipal','期初外部本金总额（SYN存量）'],['principalRepaymentIncluded','是否计入本金偿还'],['inflationResponse','通胀响应'],['allEconomicCosts','全部经济代价'],['debtSafety','债务安全']]),experiment:'40固定债×3%与60准备金×6%给4.8；仅把准备金率改2%应给2.4。另设40准备金+20现金应给3.6、外部本金仍100；这是独立费用情景，不是净新增20融资。',sourceIds:[3]},
 {id:'C5',title:'简化净收益账：先恢复，再汇款',assumption:'独立SYN，受美国2026FAM指定小节启发，收入／费用／旧恢复要求均为0至1e6整数；亏损增加累计未恢复净收益，正净收益先抵减旧要求，余数才简化汇款。排除资本、盈余及所有其他法定调整，不复制完整联储账、不认定财政立即注资；输出不能自动接下一轮输入。',initial:jointCanonicalInputs.c5,fields:[amount('income','本期收入（SYN期间流）'),amount('expense','本期费用（SYN期间流）'),amount('initialDeferredEarningsRequirement','期初尚需恢复的累计净收益（SYN存量）')],display:v=>display(jointRemittanceLedger(v.income,v.expense,v.initialDeferredEarningsRequirement),[['netEarnings','本期净收益（SYN期间流）'],['newDeferredEarningsRequirement','期末尚需恢复的累计净收益（SYN存量）'],['simplifiedRemittance','本例简化汇款（SYN期间流）'],['automaticTreasuryCashInjection','财政自动立即注资'],['realFedBalanceForecast','实际联储余额预测'],['allLegalAccountingAdjustmentsIncluded','是否包含全部法定会计调整']]),experiment:'20收入／30费用／旧要求5应给新要求15、汇款0。另设5／0／18再设25／0／18，比较恢复要求13与汇款7；不要把亏损自动改写成财政现款10。',sourceIds:[6]},
 {id:'C6',title:'一期真实预算：期末余额不是发行总流量',assumption:'独立SYN，一期债务型、无违约／资产出售／外币／利息收入的真实账；本金与非付息净融资为0至1e6整数，初级赤字为±1e6整数（可为盈余），预先给定真实净率−99.99%至100%且整数基点。期末余额转负停止展示，不说经济不可能；价格已经在真实输入中，不能反推价格。输出可为分数或超输入上限，不具自动递归资格。',initial:jointCanonicalInputs.c6,fields:[amount('oldRealBondPrincipal','期初真实付息债余额（SYN存量）'),rate('realNetInterestPercent','预先给定本期真实净利率（%）'),amount('realPrimaryDeficit','真实初级赤字／负为盈余（SYN期间流）',true),amount('noninterestMoneyFinancingRealFlow','净新增非付息货币融资（真实SYN期间流）')],display:v=>display(jointRealBudgetIdentity(v.oldRealBondPrincipal,v.realNetInterestPercent,v.realPrimaryDeficit,v.noninterestMoneyFinancingRealFlow),[['realInterest','真实利息（SYN期间流）'],['realPrimaryDeficit','真实初级赤字（排除本例利息）'],['noninterestMoneyFinancingRealFlow','净新增非付息融资（不是负债替换额）'],['newRealBondPrincipal','期末真实付息债余额（SYN存量）'],['realDebtChange','真实付息债净增量（SYN期间流）'],['nominalPriceLevel','名义价格水平'],['inflation','通胀'],['moneyGrowthResponse','货币增长响应'],['isEmpiricalDebtToGDPRatio','是否为经验债务/GDP比率']]),experiment:'100期初／3%真实息／10初级赤字／5非付息净融资→期末108、净增8。把融资改200会进入本展示之外的净资产情形并STOP；这不证明政府不能有净资产。',sourceIds:[3,5]},
 {id:'C7',title:'Leeper局部两根：四严格配置与边界停止',assumption:'独立SYN，0<β<1，α/γ为原gross利率/通胀与税/真实旧债规则斜率；只计算根、使用绝对值。有限数域与1e−12近边界及浮点误差保护不构成第五经济区；正稳态截距、私人条件、互不相关创新与完整横截条件未求解。四区解释只在原模型局部条件内，不认证均衡、国家或政策。',initial:jointCanonicalInputs.c7,fields:[{key:'beta',label:'折现β（严格0至1之间）',min:0,max:1,step:.01},{key:'alpha',label:'货币规则斜率α（非百分数）',step:.01},{key:'gamma',label:'税对旧真实债斜率γ（非百分数）',step:.01}],display:v=>display(jointLeeperRootConfiguration(v.beta,v.alpha,v.gamma),[['monetaryRoot','货币根αβ'],['fiscalRoot','财政根β⁻¹−γ'],['absMonetaryRoot','货币根绝对值'],['absFiscalRoot','财政根绝对值'],['localRegion','局部根配置（非完整均衡认证）'],['monetaryResponseLabel','货币规则标签（active主动／passive被动）'],['fiscalResponseLabel','财政规则标签（active主动／passive被动）'],['calibratedPositiveSteadyState','是否校准正稳态'],['completeEquilibriumCertified','是否认证完整均衡'],['observedCountryClassification','真实国家分类'],['policyRecommendation','政策建议']]),experiment:'β=.8依次试(α,γ)=(2,1),(1,0),(1,1),(2,0)，得到I/II/III/IV。再试α=1、γ=3：财政根−1.75仍在外。α=1.25使计算货币根1，须STOP而非强选一类。',sourceIds:[4]},
];
export const jointLabAudit=[
 {key:'seven unique independent C records with exact valid canonical inputs',passed:jointLabs.length===7&&new Set(jointLabs.map(l=>l.id)).size===7&&jointLabs.every(l=>l.fields.map(f=>f.key).sort().join('|')===Object.keys(l.initial).sort().join('|')&&l.display(l.initial).status==='OK')},
 {key:'every empty input produces STOP, not a fabricated zero result',passed:jointLabs.every(l=>l.fields.every(f=>l.display({...l.initial,[f.key]:NaN}).status==='STOP'))},
 {key:'all labels are explicit, all fields finite and independent initial records unmutated',passed:jointLabs.every(l=>l.fields.every(f=>f.label.length>4&&Number.isFinite(l.initial[f.key]))&&l.assumption.includes('独立SYN'))},
] as const;
