import {sovereignDebtPeriod,sovereignRepricing,sovereignCashFinancing,sovereignFxTranslation,sovereignDatedFunds,sovereignStateWeight} from './sovereignDebtFixtures';
import {sovereignCanonicalInputs,sovereignPathFromControls,sovereignLabs,sovereignDisplayValue} from './sovereignLabDefinitions';
import type {SovereignLabId} from './sovereignLabDefinitions';
function value<T>(r:{status:'OK';value:T}|{status:'STOP';reason:string}):T{if(r.status==='STOP')throw Error(`Invalid authored scenario: ${r.reason}`);return r.value;}
export type SovereignScenario={id:string;labId:SovereignLabId;title:string;question:string;inputs:Readonly<Record<string,number>>;unit:string;correct:number;reason:string;wrong:readonly{value:number;diagnosis:string}[];sourceIds:readonly number[]};
const c=sovereignCanonicalInputs;
const steady={...c.c2,initialDebtRatioBps:5_250,horizon:1,switchAfterYears:1};
const changed={...steady,switchAfterYears:0};
const financing=value(sovereignCashFinancing({...c.c4,otherFinancing:0}));
export const sovereignScenarios:readonly SovereignScenario[]=[
 {id:'M1',labId:'C1',title:'债额增加，债率仍可下降',question:'按一期精确金额与当期GDP定义，期末债务/GDP是多少？不是问债额变化。',inputs:c.c1,unit:'%',correct:value(sovereignDebtPeriod(c.c1)).newDebtRatioPct,reason:'债额100+4−2=102；当期GDP100×1.02×1.03=105.06，债率102/105.06×100≈97.08737864%。债额增2不等于债率增2个百分点。',wrong:[{value:102,diagnosis:'102%使用旧GDP100作期末分母，遗漏给定名义GDP扩张；102本身也是金额，不能直接贴成比率。'},{value:102/105*100,diagnosis:'将真实2%与平减指数3%相加得精确总倍数1.05，遗漏交互项；本题给定乘积定义1.0506。'}],sourceIds:[1,2]},
 {id:'M2',labId:'C1',title:'稳定初级余额的负号',question:'固定本题给定费用与GDP路径，使期末债率仍为期初100%需要多少初级盈余金额PB？负值表示赤字。',inputs:c.c1,unit:'SYN金额',correct:value(sovereignDebtPeriod(c.c1)).stabilizingPrimaryAmount,reason:'目标期末债须105.06；PB*=100+4−105.06=−1.06。给定分母扩张大于费用允许条件赤字，不认证永久可持续或政策可行。',wrong:[{value:-1,diagnosis:'−1用增长加法近似、目标债105代替精确105.06；它不是本题精确金额。'},{value:1.06,diagnosis:'把所需初级赤字改成正盈余，颠倒PB盈余正号约定。原PB2是另一给定情景，不是目标PB。'}],sourceIds:[1,2]},
 {id:'M3',labId:'C2',title:'常数账的固定点，不是安全线',question:'初始52.5%、完整给定本期费用3%/GDP增长5%/PB当期GDP−1%，下一期债率是多少？',inputs:steady,unit:'%',correct:value(sovereignPathFromControls(steady)).finalDebtRatioPct,reason:'(1.03/1.05)×52.5%+1%=52.5%。它只是这个常数递推固定点，不是所有国家的共同安全阈值或无限期支持证明。',wrong:[{value:50,diagnosis:'50%先把累积因子近似成1+3%−5%=0.98，又把求下一期换成求近似规则的固定点；同题初始52.5%的近似下一期其实52.45%，本题用精确1.03/1.05。'},{value:100,diagnosis:'把C2默认期初100%直接当本题下一期值，同时漏掉本题期初已改52.5%及整期递推；即使从100%递推也应约99.095238%。'}],sourceIds:[2,4,5]},
 {id:'M4',labId:'C2',title:'未来条件改变，原固定点不再沿用',question:'从52.5%起，本期立即使用后段费用8%，其余给定条件不变，下一期债率是多少？',inputs:changed,unit:'%',correct:value(sovereignPathFromControls(changed)).finalDebtRatioPct,reason:'(1.08/1.05)×52.5%+1%=55%。只改本题给定下一期费用，没有证明现实率由债务造成。',wrong:[{value:52.5,diagnosis:'仍沿用3%旧费用对应的固定点，忽略前段期数0意味着本期已使用8%后段费用。'},{value:52.5+8-5+1,diagnosis:'56.5%把8%−5%当成直接加到债率的3个百分点，未让利率/增长总倍数作用于旧债率52.5%。'}],sourceIds:[2,4,5]},
 {id:'M5',labId:'C3',title:'相同本金，不同计费门',question:'在新计费年开始替换20且两组都占完整年的条件下，新完整年合约利息是多少？',inputs:c.c3,unit:'SYN年流量',correct:value(sovereignRepricing(c.c3)).newAnnualCost,reason:'未替换80×2%+已替换20×6%=2.8。只核合约费用，不核支付融资和旧债价格损益。',wrong:[{value:6,diagnosis:'把全部100按新6%收费，遗漏80旧固定债仍用2%的合同；新发行报价不自动重设这些旧固定合约。'},{value:2.4,diagnosis:'2.4对应20在年中替换、前后各半年；是另一个计费时钟的正确值，不是本题完整年值。'}],sourceIds:[2,6]},
 {id:'M6',labId:'C4',title:'本金滚动也需要钱',question:'只按本实验定义，总融资需求GFN是多少？额外现金积累另进入发行需要。',inputs:c.c4,unit:'SYN现金流',correct:financing.grossFinancingNeed,reason:'初级赤字3+利息2+到期本金20=25；积累现金4另影响发行，其他融资0。GFN不是已成交资金。',wrong:[{value:9,diagnosis:'9是同给定账在发行29、偿还20后的债务净增，不能替代要筹本金的GFN。'},{value:29,diagnosis:'29还包含额外现金积累4，是总发行需要；本题GFN按明确独立定义为25。'}],sourceIds:[1,3]},
 {id:'M7',labId:'C4',title:'多借的现金不是政府购买',question:'其他融资0、额外积累现金4，按面值需要总发行多少？不是问存量净增。',inputs:c.c4,unit:'SYN现金流',correct:financing.issuanceNeed,reason:'GFN25+现金积累4=发行需要29；偿还本金20后净增9，现金资产增4。未给期初债就不输出期末总债。',wrong:[{value:25,diagnosis:'只用GFN，漏掉题设额外现金积累4；不能让新增现金无资金来源。'},{value:9,diagnosis:'用净增9替代总发行29，漏掉用于偿还到期本金20的滚动资金；本金替换即使不增存量仍需资金。'}],sourceIds:[1,3]},
 {id:'M8',labId:'C5',title:'重估仅作用于正确币种',question:'e本币/外币报价上升25%，固定本期GDP100，期末本币统计总债金额是多少？',inputs:c.c5,unit:'SYN本币存量',correct:value(sovereignFxTranslation(c.c5)).newTotal,reason:'本币债60不直接换算；旧外币债已折本币40×1.25=50，总额110。反向外币/本币报价降20%，不创造新增借款。',wrong:[{value:125,diagnosis:'将全部100乘1.25，把本币债60也当成外币合同。持有人居住地不能改变合约币种。'},{value:92,diagnosis:'40除1.25得32+60=92，错误使用逆向换算；这是e下降20%的另一情景，不是e上升25%。'}],sourceIds:[1,6]},
 {id:'M9',labId:'C6',title:'账面有钱，今日仍可缺钱',question:'今日付款20、现金15其中限制10、未来才能交收资产30，今日未覆盖缺口是多少？',inputs:c.c6,unit:'SYN今日金额',correct:value(sovereignDatedFunds(c.c6)).gapToday,reason:'今日可自由用现金15−10=5、另今日承诺资金0，缺口20−5=15。它不认证违约已发生或长期不可持续。',wrong:[{value:5,diagnosis:'将全部现金15当可用，漏掉题设限制10；缺口不是只用总现金作减法。'},{value:0,diagnosis:'提前把未来交收资产30计入今日可用资金，借未来日期抹去今日缺口。'}],sourceIds:[1,3,6]},
 {id:'M10',labId:'C7',title:'同平均，状态匹配仍不同',question:'两状态各50%，权重0.8/1.2、余额10/2，逐状态加权均值E[mS]是多少？',inputs:c.c7,unit:'SYN加权金额',correct:value(sovereignStateWeight(c.c7)).weightedSurplus,reason:'0.5×0.8×10+0.5×1.2×2=5.2；均值乘积1×6=6，协变−0.8。只是给定状态加总，不是校准现实财政支持现值。',wrong:[{value:6,diagnosis:'把E[m]E[S]=6当E[mS]，删除本题非零协变；m不是提前平均完的常数。'},{value:10.4,diagnosis:'只加两状态乘积8+2.4=10.4，不乘各自概率50%，把不同情景当同时实现。'}],sourceIds:[2,4,5]},
];
const orders:Readonly<Record<string,readonly number[]>>={M1:[0,1,2],M2:[1,2,0],M3:[1,0,2],M4:[2,0,1],M5:[0,2,1],M6:[2,1,0],M7:[1,2,0],M8:[1,0,2],M9:[0,1,2],M10:[2,0,1]};
export function sovereignOptions(s:SovereignScenario){const order=orders[s.id];if(!order)throw Error(`Unknown option order ${s.id}`);const options=[{id:`${s.id}-correct`,value:s.correct,diagnosis:s.reason,correct:true},...s.wrong.map((w,i)=>({id:`${s.id}-wrong-${i+1}`,value:w.value,diagnosis:w.diagnosis,correct:false}))];return order.map(i=>options[i]);}
export function sovereignScenarioInputText(s:SovereignScenario){const l=sovereignLabs.find(l=>l.id===s.labId);if(!l)throw Error(`Missing lab ${s.labId}`);return l.fields.map(f=>`${f.label}＝${sovereignDisplayValue(s.inputs[f.key])}`).join('；');}
export const sovereignScenarioAudit=[
 {key:'ten shared M/K cases; 30 finite distinct neutral candidates and 20 diagnoses',passed:sovereignScenarios.length===10&&sovereignScenarios.every(s=>s.wrong.length===2&&new Set(sovereignOptions(s).map(o=>o.value)).size===3&&sovereignOptions(s).every(o=>Number.isFinite(o.value)&&o.diagnosis.length>30&&!Object.prototype.hasOwnProperty.call(o,'label')))},
 {key:'all scenario controls retain their actual same-C labels, paths and valid scope',passed:sovereignScenarios.every(s=>{const l=sovereignLabs.find(l=>l.id===s.labId)!;return l.display(s.inputs).status==='OK'&&Object.keys(s.inputs).sort().join('|')===l.fields.map(f=>f.key).sort().join('|')&&l.fields.every(f=>sovereignScenarioInputText(s).includes(f.label));})},
 {key:'shared fixed ordering gives one correct stable identity and balanced ABC 3/4/3',passed:sovereignScenarios.every(s=>sovereignOptions(s).filter(o=>o.correct).length===1&&new Set(sovereignOptions(s).map(o=>o.id)).size===3)&&[0,1,2].map(i=>sovereignScenarios.filter(s=>sovereignOptions(s).findIndex(o=>o.correct)===i).length).join('/')==='3/4/3'},
] as const;
