import {sovereignDebtPeriod,sovereignDebtPath,sovereignRepricing,sovereignCashFinancing,sovereignFxTranslation,sovereignDatedFunds,sovereignStateWeight} from './sovereignDebtFixtures';
import type {SovereignStop} from './sovereignDebtFixtures';
export type SovereignLabId='C1'|'C2'|'C3'|'C4'|'C5'|'C6'|'C7';
export type SovereignField={key:string;label:string;min:number;max:number;step:1};
export type SovereignRow=readonly[label:string,value:string];
export type SovereignDisplay={status:'OK';rows:readonly SovereignRow[]}|SovereignStop;
export type SovereignLab={id:SovereignLabId;title:string;assumption:string;initial:Readonly<Record<string,number>>;fields:readonly SovereignField[];display(v:Readonly<Record<string,number>>):SovereignDisplay;experiment:string;sourceIds:readonly number[]};
export function sovereignDisplayValue(x:unknown):string{if(x===null)return '未知／未识别（不是0）';if(typeof x==='boolean')return x?'是':'否';if(typeof x==='number')return Number.isInteger(x)?String(x):`≈${Number(x.toPrecision(12))}`;return String(x);}
function display<T extends object>(r:SovereignStop|{status:'OK';value:T},labels:readonly(readonly[keyof T,string])[]):SovereignDisplay{return r.status==='STOP'?r:{status:'OK',rows:labels.map(([key,label])=>[label,sovereignDisplayValue(r.value[key])] as const)};}
const money=(key:string,label:string,signed=false):SovereignField=>({key,label,min:signed?-1_000_000:0,max:1_000_000,step:1});
const bps=(key:string,label:string,min=-9_000):SovereignField=>({key,label,min,max:5_000,step:1});
const field=(key:string,label:string,min:number,max:number):SovereignField=>({key,label,min,max,step:1});
export const sovereignCanonicalInputs={
 c1:{oldDebt:100,oldGdp:100,interest:4,primarySurplus:2,sfa:0,realGrowthBps:200,deflatorBps:300},
 c2:{initialDebtRatioBps:10_000,horizon:5,interestBps:300,laterInterestBps:800,switchAfterYears:5,realGrowthBps:500,deflatorBps:0,primaryCurrentGdpBps:-100,sfaCurrentGdpBps:0},
 c3:{stock:100,replaced:20,oldCouponBps:200,newCouponBps:600},
 c4:{primaryDeficit:3,interest:2,amortization:20,additionalContingentCash:0,cashAccumulation:4},
 c5:{domesticOld:60,foreignOldTranslated:40,quoteChangeBps:2_500,gdp:100},
 c6:{dueToday:20,cashToday:15,restrictedCash:10,settlesLaterAsset:30,committedTodayFunds:0},
 c7:{probabilityAPct:50,weightABps:8_000,weightBBps:12_000,surplusA:10,surplusB:2},
} as const;
export function sovereignPathFromControls(v:Readonly<Record<string,number>>){
 if(!Number.isSafeInteger(v.horizon)||v.horizon<1||v.horizon>10||!Number.isSafeInteger(v.switchAfterYears)||v.switchAfterYears<0||v.switchAfterYears>10||![v.interestBps,v.laterInterestBps].every(x=>Number.isSafeInteger(x)&&x>=-9_000&&x<=5_000))return {status:'STOP',reason:'路径长度/变率年与前后段率必须符合护照，即使本次某段未使用。'} as const;
 return sovereignDebtPath({initialDebtRatioBps:v.initialDebtRatioBps,steps:Array.from({length:v.horizon},(_,i)=>({interestBps:i<v.switchAfterYears?v.interestBps:v.laterInterestBps,realGrowthBps:v.realGrowthBps,deflatorBps:v.deflatorBps,primaryCurrentGdpBps:v.primaryCurrentGdpBps,sfaCurrentGdpBps:v.sfaCurrentGdpBps}))});
}
const definitions:readonly SovereignLab[]=[
 {id:'C1',title:'一期金额与精确债率：同一账，两种变化',initial:sovereignCanonicalInputs.c1,fields:[money('oldDebt','期初名义债务（独立SYN）'),money('oldGdp','旧期名义GDP（SYN；必须>0）'),money('interest','本期给定债息（SYN流量）'),money('primarySurplus','本期初级盈余；负为赤字（SYN）',true),money('sfa','本期其他增债调整；可负（SYN）',true),bps('realGrowthBps','真实净增长（基点；200=2%）'),bps('deflatorBps','GDP平减指数净变化（基点）')],assumption:'独立SYN，一期同币种名义金额、无利息收入/FX/违约；金额整数不超过1e6，PB/SFA可有号。旧GDP>0；旧债0只接本例I0。增长与平减指数是净率、−9000至5000整数基点（−90%至50%）；不是CPI或已估计政策效果。稳定PB只固定给定费用与GDP路径。',display:v=>display(sovereignDebtPeriod({oldDebt:v.oldDebt,oldGdp:v.oldGdp,interest:v.interest,primarySurplus:v.primarySurplus,sfa:v.sfa,realGrowthBps:v.realGrowthBps,deflatorBps:v.deflatorBps}),[['nominalGdpFactor','名义GDP总倍数ρ'],['newGdp','当期GDP金额'],['newDebt','期末名义债额'],['debtAmountChange','债额净变化'],['newDebtRatioPct','期末债/GDP（%）'],['debtRatioChangePp','债率变化（百分点）'],['implicitInterestPct','债息/旧债（%；零债未定义）'],['stabilizingPrimaryAmount','固定债率所需PB金额；负为赤字'],['stabilizingPrimaryPct','所需PB/当期GDP（%）'],['sovereignSafety','真实主权安全']]),experiment:'手算102/105.06。改GDP平减指数为0基点，辨别金额和债率；恢复基准后将旧债、债息、初级盈余均设0，SFA仍0；金额账可算而零债平均费用未定义。清空GDP或输入0会STOP，不把除零平均费填0。',sourceIds:[1,2]},
 {id:'C2',title:'有限路径：常数条件与未来变率',initial:sovereignCanonicalInputs.c2,fields:[field('initialDebtRatioBps','初始债率（基点；10000=100%）',0,100_000),field('horizon','给定有限期数（1至10）',1,10),bps('interestBps','前段给定名义费用率（基点）'),bps('laterInterestBps','后段给定名义费用率（基点）'),field('switchAfterYears','前段期数；之后使用后段率',0,10),bps('realGrowthBps','每期真实净增长（基点）'),bps('deflatorBps','每期GDP平减指数净变化（基点）'),field('primaryCurrentGdpBps','PB/当期GDP（基点；−100=−1%）',-5_000,5_000),field('sfaCurrentGdpBps','SFA/当期GDP（基点）',-5_000,5_000)],assumption:'独立SYN，1至10期显式给定路径；余额/SFA均为每期当期GDP份额，不是固定名义金额。两段费用与固定增长/平减指数是控件情景，不是预测。初始与每期债率限定0至1000%；内部整数网格有理数精确递推，显示小数不回接。前后段未用也必须有效，域外停止不认证经济不可持续。',display:v=>{const r=sovereignPathFromControls(v);if(r.status==='STOP')return r;return {status:'OK',rows:[...r.value.rows.map(x=>[`第${x.period}期债率（%）`,sovereignDisplayValue(x.debtRatioPct)] as const),['最后一期债率（%）',sovereignDisplayValue(r.value.finalDebtRatioPct)],['相对初始变化（百分点）',sovereignDisplayValue(r.value.changePp)],['内部递推',r.value.internalArithmetic],['无限期支持/TVC证明',sovereignDisplayValue(r.value.infiniteHorizonProof)]]};},experiment:'五期300基点费用/500基点真实增长/PB−100基点可手算首期99.095238%。初始改5250基点则同条件52.5%不变；前段期数改0，费用800基点，下一期为55%。这不是国家安全线。',sourceIds:[2,4,5]},
 {id:'C3',title:'完整计费年：面值替换与平均票息',initial:sovereignCanonicalInputs.c3,fields:[money('stock','原固定本金存量（SYN；>0）'),money('replaced','新计费年开始替换本金（SYN）'),bps('oldCouponBps','未替换旧票息（年化基点）',0),bps('newCouponBps','替换后新合约票息（年化基点）',0)],assumption:'独立SYN，新计费年开始按面值替换指定旧本金；两组均占完整计费年、其余旧固定合约不重设。非负年票息0至5000整数基点。无折溢价、手续费、新赤字、期内支付融资安排或市场价格估计；替换不能超本金。年中替换是另一时钟，须另分段。',display:v=>display(sovereignRepricing({stock:v.stock,replaced:v.replaced,oldCouponBps:v.oldCouponBps,newCouponBps:v.newCouponBps}),[['unchangedStock','仍按旧票息本金'],['replaced','已替换新票息本金'],['oldAnnualCost','替换前完整年费用'],['newAnnualCost','替换后完整年费用'],['costChange','年度费用变化'],['averageCouponPct','平均合约票息（%）'],['entireStockWasReplaced','是否替换全部存量'],['marketPriceChange','旧债市场价格变化']]),experiment:'80×2%+20×6%=2.8。把替换额改100平均为6%；改101则STOP。若改成年中各半年，需另算2.4，不能给本函数偷偷换计费日。',sourceIds:[2,6]},
 {id:'C4',title:'独立现金账：GFN、总发行需要与净增',initial:sovereignCanonicalInputs.c4,fields:[money('primaryDeficit','初级赤字正数（SYN现金流）'),money('interest','债息（SYN现金流）'),money('amortization','到期本金偿还（SYN现金流）'),money('additionalContingentCash','未包含赤字的或有付款（SYN）'),money('cashAccumulation','额外现金积累（SYN；非购买）')],assumption:'独立SYN现金/面值同期间账，利息收入0、其他融资0、无FX/应计/折溢价、现金只积累不提款。或有付款只接未记赤字者，不自动认证会计分类；全部金额非负整数≤1e6。未给期初债，所以只输出存量净增，不生成期末总债。总发行是需要，不是融资成功。',display:v=>display(sovereignCashFinancing({primaryDeficit:v.primaryDeficit,interest:v.interest,amortization:v.amortization,additionalContingentCash:v.additionalContingentCash,cashAccumulation:v.cashAccumulation,otherFinancing:0}),[['grossFinancingNeed','本实验总融资需求GFN'],['issuanceNeed','本实验总发行需要'],['debtNetIncrease','偿还本金后债务净增'],['cashAssetChange','现金资产增加'],['issuanceMinusGfn','发行需要减GFN'],['contingentAlreadyInDeficit','本例已计入赤字的额外或有付款（固定0）'],['actualIssuance','现实发行成交'],['defaultProbability','真实违约概率']]),experiment:'3+2+20=25，另积累4需发行29、净增9。仅把到期本金改0，GFN和发行下降但给定其余条件净增仍9。不得将救助同时填赤字与额外或有付款。',sourceIds:[1,3]},
 {id:'C5',title:'外币重估：e报价方向与本币统计债',initial:sovereignCanonicalInputs.c5,fields:[money('domesticOld','旧本币合同债（SYN）'),money('foreignOldTranslated','旧外币债已按旧e折本币（SYN）'),bps('quoteChangeBps','e本币/外币报价变化（基点）'),money('gdp','固定当期GDP（SYN；>0）')],assumption:'独立SYN，一种外币，e=本币/一单位外币；旧外币金额已按旧e折算。e净变化−9000至5000整数基点；+2500即e升25%，不是本币反向价值降25%。固定GDP，无利息/PB/SFA/新增借款、外汇资产对冲或汇率因果识别。',display:v=>display(sovereignFxTranslation({domesticOld:v.domesticOld,foreignOldTranslated:v.foreignOldTranslated,quoteChangeBps:v.quoteChangeBps,gdp:v.gdp}),[['oldTotal','旧总债本币金额'],['quoteFactor','e新/e旧总倍数'],['foreignNewTranslated','期末外币折本币金额'],['newTotal','期末本币总债金额'],['translationChange','纯换算债额变化'],['debtRatioPct','本实验当期债率（%）'],['ratioChangePp','换算债率变化（百分点）'],['reverseQuoteChangePct','反向外币/本币报价变化（%）'],['newBorrowing','本例新增借款到账']]),experiment:'60+40×1.25=110。把e变化改−2000基点，应为92；反向报价同时涨25%，不是涨20%。非居民持有的本币债不能因此填到外币金额。',sourceIds:[1,6]},
 {id:'C6',title:'今日日期资金：限制现金与未来交收',initial:sovereignCanonicalInputs.c6,fields:[money('dueToday','今日到期付款总额（SYN）'),money('cashToday','账上今日现金（SYN）'),money('restrictedCash','其中按给定条件受限现金（SYN）'),money('settlesLaterAsset','只能未来交收的资产（SYN）'),money('committedTodayFunds','另已给定今日可用承诺资金（SYN）')],assumption:'独立SYN同币种日期账；今日到期额已含题设付款，不再加一次本金/息。限制现金≤账上现金，未来资产即使有价值也不计今日可用；另今日资金没有包含在账上现金中。权限、可用性和承诺是给定情景，不认证现实法律/成交。整数≤1e6，gap0不等于国家安全，gap>0不等于违约已发生。',display:v=>display(sovereignDatedFunds({dueToday:v.dueToday,cashToday:v.cashToday,restrictedCash:v.restrictedCash,settlesLaterAsset:v.settlesLaterAsset,committedTodayFunds:v.committedTodayFunds}),[['unrestrictedCash','今日可自由用现金'],['usableToday','今日可用资金合计'],['gapToday','今日未覆盖付款缺口'],['excessToday','今日付款后剩余可用资金'],['settlesLaterExcluded','明确排除的未来交收资产'],['bookCashAndLaterAssets','账面现金加未来资产'],['coveredToday','仅给定条件今日是否覆盖'],['defaultOccurred','现实违约是否已发生']]),experiment:'15−10=5，今日付款20缺15，不因未来资产30消失。另今日可用资金改15则gap0；限制改16则STOP，不能截零掩盖非法输入。',sourceIds:[1,3,6]},
 {id:'C7',title:'有限两状态：平均乘积与逐状态加权',initial:sovereignCanonicalInputs.c7,fields:[field('probabilityAPct','状态A概率（整数%；50即50%）',0,100),field('weightABps','mA整数万分刻度（8000=0.8）',1,100_000),field('weightBBps','mB整数万分刻度（12000=1.2）',1,100_000),money('surplusA','状态A未来初级余额（有号SYN）',true),money('surplusB','状态B未来初级余额（有号SYN）',true)],assumption:'独立SYN，两状态同一未来支付；m是给定今日衡量权重、不是情景概率/利率/已平均常数。m用整数万分刻度保持输入精度、必须正；p为整数百分点网格0至100%，余额可有号整数±1e6。只核有限E[mS]恒等式及浮点残差，不校准SDF、不输出债价或证明无穷期TVC。',display:v=>display(sovereignStateWeight({probabilityAPct:v.probabilityAPct,weightABps:v.weightABps,weightBBps:v.weightBBps,surplusA:v.surplusA,surplusB:v.surplusB}),[['meanWeight','E[m]平均权重'],['meanSurplus','E[S]平均余额'],['weightedSurplus','E[mS]逐状态加权余额'],['productOfMeans','E[m]E[S]均值乘积'],['covariance','Cov(m,S)协变'],['identityResidual','有限浮点加总残差'],['calibratedDiscountFactor','现实贴现因子校准'],['infiniteHorizonProof','无限期预算/TVC证明'],['sovereignSafety','真实主权安全']]),experiment:'等概率得5.2/6/−0.8；交换余额2/10得6.8/6/+0.8。两权重都改10000得协变0；概率0或100是合法退化分布，但另状态也须符合护照。',sourceIds:[2,4,5]},
];
export const sovereignLabs:readonly SovereignLab[]=definitions.map(lab=>({...lab,display:v=>lab.fields.every(f=>Number.isSafeInteger(v[f.key])&&v[f.key]>=f.min&&v[f.key]<=f.max)?lab.display(v):{status:'STOP',reason:'每个输入都须为声明范围内的完整整数网格，未使用情景也不能缺失。'}}));
export const sovereignLabAudit=[
 {key:'seven distinct independent SYN records; all defaults and exact control paths valid',passed:sovereignLabs.length===7&&new Set(sovereignLabs.map(l=>l.id)).size===7&&sovereignLabs.every(l=>l.assumption.includes('独立SYN')&&l.display(l.initial).status==='OK'&&l.fields.map(f=>f.key).sort().join('|')===Object.keys(l.initial).sort().join('|'))},
 {key:'clearing every control produces STOP including unused future-rate control',passed:sovereignLabs.every(l=>l.fields.every(f=>l.display({...l.initial,[f.key]:NaN}).status==='STOP'))},
 {key:'all visible fields label their actual amount, rate, probability or dimensionless grid',passed:sovereignLabs.every(l=>l.fields.every(f=>f.label.length>=10&&f.step===1&&Number.isFinite(l.initial[f.key])))},
] as const;
