import {surpriseCanonicalInputs,surpriseEvaluators} from './surpriseFixtures';
import type {SurpriseLabId} from './surpriseFixtures';
import {surpriseLabs,surpriseNumber} from './surpriseLabDefinitions';
type WrongPath=Readonly<{value:number;diagnosis:string}>;
export type SurpriseScenario=Readonly<{id:string;labId:SurpriseLabId;title:string;question:string;unit:string;resultKey:string;correct:number;correctIndex:0|1|2;explanation:string;wrong:readonly [WrongPath,WrongPath];sourceIds:readonly number[]}>;
function numberResult(id:SurpriseLabId,key:string):number{const r=surpriseEvaluators[id](surpriseCanonicalInputs[id]);if(r.status==='STOP'||typeof r.value[key]!=='number')throw Error('Fixed numeric question must have a valid disclosed value '+key);return r.value[key];}
export const surpriseScenarios:readonly SurpriseScenario[]=[
 {id:'1',labId:'C1',title:'同一增长相对指定共识',question:'宣布增长200bp，上期100bp、指定共识300bp、替代100bp；仅求宣布减指定共识。',unit:'基点（宣布减指定共识）',resultKey:'relativeToConsensusBp',correct:numberResult('C1','relativeToConsensusBp'),correctIndex:0,explanation:'200−300=−100bp。宣布增长2%、比上期好100bp、相对替代好100bp分别成立，但都不是所问指定共识差。价格方向仍未知。',wrong:[{value:100,diagnosis:'100=200−100是相对上期改善或另给替代代理差；用它替指定共识，偷换了比较参照。'},{value:200,diagnosis:'200是本期宣布增长水平的基点表达，没有减去代理。增长水平不能冒成相对共识意外。'}],sourceIds:[1,2,9]},
 {id:'2',labId:'C1',title:'改善并不等超过共识',question:'仍用200/100/300/100bp四输入，仅求本期增长比上期改善多少。',unit:'基点（本期减上期）',resultKey:'improvementFromPreviousBp',correct:numberResult('C1','improvementFromPreviousBp'),correctIndex:1,explanation:'200−100=100bp，比上期改善1个百分点。−100bp回答相对共识的另一问题；本题不由增长改善推股价或福利。',wrong:[{value:-100,diagnosis:'−100=200−300是相对指定共识的差。把共识当上期值，就把时间改善换成预测误差。'},{value:200,diagnosis:'200是本期增长的基点水平；漏减上期100。它不是改善幅度，也不是权益收益。'}],sourceIds:[1,2,9]},
 {id:'3',labId:'C2',title:'调查中位数保存什么',question:'五回答100/100/200/400/700bp、教材事后宣布200bp；仅求调查中位预测。',unit:'基点（调查中位）',resultKey:'surveyMedianBp',correct:numberResult('C2','surveyMedianBp'),correctIndex:2,explanation:'排序后第三位为200bp；均值1500/5=300bp，宣布减中位为0bp。中位预测与相对中位差是不同量，0差不消去各人差。',wrong:[{value:300,diagnosis:'300是算术均值，保存加总平均而非排序中央。汇总名为共识不能让均值等于中位。'},{value:0,diagnosis:'0=200−200是宣布减中位的差，不是中位数本身。将统计位置换成预测误差，漏掉所问对象。'}],sourceIds:[2,4]},
 {id:'4',labId:'C2',title:'相对均值与相对中位不同',question:'同一五回答和宣布200bp，仅求宣布减调查算术均值。',unit:'基点（宣布减均值）',resultKey:'retrospectiveActualMinusMeanBp',correct:numberResult('C2','retrospectiveActualMinusMeanBp'),correctIndex:0,explanation:'均值(100+100+200+400+700)/5=300bp，宣布200−300=−100bp。相对中位0不是同一差，也不能用绝对距离去掉方向。',wrong:[{value:0,diagnosis:'0是200减中位200，偷偷更换了汇总规则；本题指定算术均值。'},{value:100,diagnosis:'100取了|200−300|的绝对距离，丢掉低于代理的方向。题目没有求绝对误差。'}],sourceIds:[2,4]},
 {id:'5',labId:'C3',title:'截止可得代理，不是截止意外',question:'旧300bp在1公开、新200bp在4公开，cut3、公告5、教材事后actual200bp；仅求cut3可用代理。',unit:'基点（截止可用冻结代理）',resultKey:'asOfFrozenProxyBp',correct:numberResult('C3','asOfFrozenProxyBp'),correctIndex:2,explanation:'1≤3<4，因此cut3仅旧代理300bp公开可用。实际200到公告5才可得，cut3实际/意外仍未知；事后相对冻结旧代理−100bp也不是本题。',wrong:[{value:200,diagnosis:'200取了在4才公开的新代理，或直接取后来实际值；二者都不能进入cut3。本题所问代理的公开时钟被越过。'},{value:0,diagnosis:'0把截止尚未知道的实际/意外填成零，又拿它冒名已公开的代理；本题旧代理明确可用300，不存在缺失可用代理。'}],sourceIds:[4,5,7]},
 {id:'6',labId:'C4',title:'本期差不吸收上期修订',question:'本期宣布200bp、匹配预测150bp；上期first200bp/revised100bp。仅求本期差。',unit:'基点（本期匹配差）',resultKey:'currentMatchedDifferenceBp',correct:numberResult('C4','currentMatchedDifferenceBp'),correctIndex:1,explanation:'200−150=50bp。本期强于指定代理0.5个百分点；上期修订100−200=−100bp是另一参考期，另定义算术和−50bp不能叫本期headline差。',wrong:[{value:-50,diagnosis:'−50=50+(100−200)把上期修订加入本期差。算术和可另定义，但无消息权重和目标定义不能冒成本期意外或总价格冲击。'},{value:-100,diagnosis:'−100仅为同一上期修订差，漏掉本期200减150；参考期偷换使本期正差被替成上期负修订。'}],sourceIds:[2,6,8]},
 {id:'7',labId:'C5',title:'公告后使用合法冻结尺',question:'actual250bp、frozen225bp、scale25bp；train2/model2/cut3/announce4。求公告后使用合格事前冻结正尺的标准化。',unit:'无量纲（公告后、合格冻结尺）',resultKey:'retrospectiveStandardizedUsingEligibleFrozenScale',correct:numberResult('C5','retrospectiveStandardizedUsingEligibleFrozenScale'),correctIndex:2,explanation:'训练与选型2≤cut3、正尺度25已给，公告后(250−225)/25=1。cut3并不知道actual，截止raw/std仍未知；结果1不是事前已知特征或PIT认证。',wrong:[{value:25,diagnosis:'25=250−225是原始基点差，漏除25bp尺度，因此单位仍为基点而非标准化无量纲。'},{value:0,diagnosis:'0把截止尚不可得的标准化未知填成零，又拿来回答公告后问题；这里公告后正尺合格可算1。合法尺度0的反例是另一个条件，不在本题。'}],sourceIds:[2,5]},
 {id:'8',labId:'C6',title:'联合条件价格回报',question:'一期CF100→102，总所需回报500→1000bp；求两套联合条件模型价格之间的回报。',unit:'%（联合条件模型回报）',resultKey:'jointModelReturnPercent',correct:numberResult('C6','jointModelReturnPercent'),correctIndex:0,explanation:'前价格100/1.05=2000/21，后102/1.10=1020/11；后/前−1=−29/1100，即−29/11%。CF增加2%不足以确定价格，分母同时改变；这不是现实股票或GDP映射。',wrong:[{value:2,diagnosis:'2%只按CF102/100−1计算，暗中固定所需回报，漏掉5%变10%的分母条件。'},{value:-28/11,diagnosis:'−28/11%=2%+(1.05/1.10−1)×100%将两个单改回报相加，漏联合交互余项−1/11%。各单改属不同反事实，不能冒精确联合。'}],sourceIds:[1,3,9]},
 {id:'9',labId:'C6',title:'未来支付与当前条件价格',question:'仍用CF100→102、总回报500→1000bp，求消息后条件模型价格。',unit:'SYN金额（消息后模型价格）',resultKey:'modelPriceAfter',correct:numberResult('C6','modelPriceAfter'),correctIndex:1,explanation:'后现金流102除以后同一期总所需回报因子1.10，价格1020/11约92.7273。不能用旧5%分母或把未来支付直接当今日价格，单期条件结果不认证真实证券。',wrong:[{value:2000/21,diagnosis:'2000/21是旧CF100与旧5%条件的旧价格。消息后分子和分母都已变，沿用旧价格丢掉整次更新。'},{value:102,diagnosis:'102是未来一期权益现金流，漏除同一期总所需回报因子1.10；支付与今日条件价格的时间对象不同。'}],sourceIds:[1,3,9]},
 {id:'10',labId:'C7',title:'降息动作与较紧的调查式差',question:'旧目标125bp、新目标100bp、冻结目标代理75bp；路径代理100→125bp。仅求新目标相对目标代理差。',unit:'基点（调查式目标差）',resultKey:'retrospectiveTargetRelativeToFrozenSurveyProxyBp',correct:numberResult('C7','retrospectiveTargetRelativeToFrozenSurveyProxyBp'),correctIndex:1,explanation:'100−75=25bp，高于指定代理。100−125=−25bp才是实际动作；路径另25bp有不同期限对象。本题不是GSS原2003期货13bp或正交因子。',wrong:[{value:-25,diagnosis:'−25=100−125是新减旧的降息动作，而不是新减事前代理75。动作宽松与相对预计较紧可以同时成立。'},{value:0,diagnosis:'0=100−100用公告后目标覆写事前代理，再宣布没有意外。事前冻结75不能被后来新目标倒填；也不能从降息标签推目标差零。'}],sourceIds:[3]},
];
export function surpriseOptions(s:SurpriseScenario):readonly Readonly<{id:'A'|'B'|'C';value:number;correct:boolean;diagnosis:string}>[]{let w=0;return (['A','B','C'] as const).map((id,index)=>index===s.correctIndex?{id,value:s.correct,correct:true,diagnosis:'正确推理：'+s.explanation}:{id,value:s.wrong[w].value,correct:false,diagnosis:'这条路径错在哪里：'+s.wrong[w++].diagnosis});}
export function surpriseScenarioInputText(s:SurpriseScenario):string{const lab=surpriseLabs.find(l=>l.id===s.labId);if(!lab)throw Error('Missing lab');return lab.fields.map(f=>f.label+' = '+surpriseNumber(lab.initial[f.key])).join('；');}
export const surpriseScenarioAudit=[
 {key:'ten fixed independent questions with one correct and two distinct declared numeric wrong paths',passed:surpriseScenarios.length===10&&new Set(surpriseScenarios.map(s=>s.id)).size===10&&surpriseScenarios.every(s=>{const o=surpriseOptions(s);return Number.isFinite(s.correct)&&o.length===3&&o.filter(x=>x.correct).length===1&&new Set(o.map(x=>x.value)).size===3;})},
 {key:'all ten fixed questions retain full37-field lab subset, unit and complete three diagnoses',passed:surpriseScenarios.every(s=>s.unit.length>0&&surpriseScenarioInputText(s).length>60&&surpriseOptions(s).every(o=>o.diagnosis.length>=40))},
] as const;
