import type { LessonReading, LessonReference } from './types';

export const lesson401References: LessonReference[] = [
  {
    id: 1,
    authors: 'International Monetary Fund',
    year: '2025',
    accessedAt: '2026-09-16',
    title: 'Integrated Balance of Payments and International Investment Position Manual, Seventh Edition (BPM7)',
    publication: 'White Cover (Pre-Edited) Version, March 2025',
    url: 'https://www.imf.org/-/media/files/data/statistics/bpm6/draft-bpm7-wcv.pdf',
    use: '编写者核读手册印刷页12–30（第2章§§2.2–2.39）、82–85与96–97（第3章§§3.84–3.96、3.145–3.149）、122–127（第4章§§4.1–4.15）、239–243与262–264（第6章§§6.1–6.10、6.57–6.65）、265–280（第6章§§6.69–6.123及Boxes 6.5–6.6）、281–287（第7章§§7.1–7.8）、307–310（第8章§§8.1–8.13）、323–328（第9章§§9.1–9.10）并补核§§9.21–9.23、§§14.28–14.29、609–615（第19章§§19.4–19.18）、652–653（第20章§§20.27–20.30）、839–853（Annex 11）及874–895（Annex 13）。支持居民—非居民边界、复式记账、三大账户、金融账户功能类别、资产/负债符号、债务减免与单方面核销的分类边界、统计差异、IIP流量—存量桥、储备资产、镜像数据和修订机制。它是2025年3月白皮书预编辑版；不支持声称已核读1076个物理页全本、最终排版页码不再变化、任何经济体已完成BPM7迁移、现实数据为BPM7口径，亦不提供因果、危机预测或福利结论。',
  },
  {
    id: 2,
    authors: 'International Monetary Fund',
    year: '2025',
    accessedAt: '2026-09-16',
    title: 'BPM7 Annex 13 (V7): Changes from BPM6',
    publication: 'BPM7 official final-chapters annex; 23-page standalone PDF, file metadata modified 4 April 2025',
    url: 'https://www.imf.org/-/media/files/data/statistics/bmp7/final-chapters/draft-bpm7-annex-13-v7-changes-from-bpm6.pdf',
    use: '编写者核读本地官方PDF全部23个物理页，并与来源1手册Annex 13印刷页874–895交叉核对。支持“总体框架大体延续、术语与标准分项发生具体变化”：credit/debit扩展为credit/revenue与debit/expenditure，net errors and omissions改称statistical discrepancy，integrated IIP及汇率、其他价格、其他数量变化进入标准分项，并新增NIR、加密资产、SPE、服务与部门细分等处理。不支持把名称变化误写成经济关系改变，也不支持推断现实BPM6序列已自动重分类为BPM7。',
  },
  {
    id: 3,
    authors: 'International Monetary Fund',
    year: 'undated current-linked document',
    accessedAt: '2026-09-16',
    title: 'Coordinated Portfolio Investment Survey: Frequently Asked Questions',
    publication: 'IMF Data, CPIS FAQ; four-page document using BPM6 terminology',
    url: 'https://data.imf.org/-/media/CPIS/Frequently-Asked-Questions.pdf',
    use: '编写者核读全部4个物理页。支持CPIS/SEFER/SSIO的资产方采集与派生负债逻辑、IIP和CPIS因时点/覆盖/版本而出现差异、头寸差不能可靠分离交易与汇率/价格/其他数量变化，以及历史期可被修订。不支持把CPIS当作全口径BOP、把派生负债当无误差真值、从两期头寸直接识别资本流，或在未核当期元数据时宣称所有经济体覆盖与频率相同。',
  },
  {
    id: 4,
    authors: 'European Central Bank',
    year: '2026',
    accessedAt: '2026-09-16',
    title: 'Euro area and national balance of payments and international investment position statistics',
    publication: 'Quality Report (data to Q2 2025), published 22 May 2026; transmissions through 31 October 2025',
    url: 'https://www.ecb.europa.eu/press/bopips/html/ecb.bopips202606.en.html',
    use: '编写者核读Executive Summary与Statistical developments、§6.2、§7.1、§8及Box 1。支持现实统计差异需按绝对值、相对毛流量与符号持续性诊断，货物BOP与海关数据存在经济所有权/实物流动概念差异，双边镜像会受漏报、标准采用、估值、时点、分类与伙伴归属影响，并明确该报告展示的数据仍按BPM6。不支持把欧元区约1%的平衡机制或报告中的国别比率设为全球阈值，也不支持把统计差异或镜像差异自动解释成资本外逃、欺诈或单一漏项。',
  },
  {
    id: 5,
    authors: 'International Monetary Fund',
    year: 'current dataset page; November 2025 explanatory update',
    accessedAt: '2026-09-16',
    title: 'Balance of Payments and International Investment Position Statistics (BOP/IIP), World and Country Group Aggregates',
    publication: 'IMF Data dataset BOP_AGG, historically BOPSY',
    url: 'https://data.imf.org/Datasets/BOP_AGG',
    use: '编写者核读当前数据页的Description、Metadata入口与Latest Updates。支持当前可下载世界/组别BOP与IIP数据明确“based on BPM6 methodology”，国别项以实际报送为主，而世界和组别汇总会把已报数据与对未报告经济体的估计结合；页面列示2025年11月说明文件。不支持声称本课已下载或冻结任何数值、不同序列拥有相同版本/覆盖/发布时间、估计等于观测，或把该实时BPM6数据页改贴BPM7标签。',
  },
  {
    id: 6,
    authors: 'European Central Bank',
    year: 'current methodology page',
    accessedAt: '2026-09-16',
    title: 'Balance of payments and international investment position',
    publication: 'ECB Statistics, current BOP/IIP concepts, data links, sources and methods',
    url: 'https://www.ecb.europa.eu/stats/balance_of_payments_and_external/balance_of_payments/html/index.en.html',
    use: '编写者核读Balance of payments、International investment position及Sources and methods段落。支持BOP记录欧元区居民与非居民交易、current/capital/financial三账户、复式记账、IIP资产负债及NIIP，以及以交易、价格/汇率重估和其他数量变化调节IIP；页面同时明确当前概念与定义以BPM6和欧盟方法为依据。不支持把欧元区制度外推为全球编制状态，不支持声称ECB现行序列已切换BPM7，也不把完整头寸变化等同于当期交易或央行干预。',
  },
  {
    id: 7,
    authors: 'European Central Bank',
    year: '2023',
    accessedAt: '2026-09-16',
    title: 'The exchange of balance of payments, international investment position statistics – BPM6 – booklet',
    publication: 'ECB BPM6 reporting booklet, April 2023; official page identifies the booklet as outdated',
    url: 'https://www.ecb.europa.eu/press/bpm6/pdf/ecb.bopips202304~696e0ec50b.en.pdf',
    use: '编写者核读印刷页17–18（PDF物理页18–19；§5.1、Table 8及§5.2）。支持BPM6传输中的“credits/assets为正、debits/liabilities为正、余额为credit−debit、净金融/IIP概念为资产净增加−负债净增加”以及updates-and-revisions传输机制。不支持把传输符号与一笔交易的复式credit/debit位置混为一谈，也不支持用2023且已标旧的技术手册证明2026当前法律、当前数据状态或BPM7实现。',
  },
  {
    id: 8,
    authors: 'International Monetary Fund, Statistics Department',
    year: '2025',
    accessedAt: '2026-09-16',
    title: 'Release of New Standards for Macroeconomic Statistics (BPM7)',
    publication: 'IMF Policy Paper No. 2025/023, 11 July 2025; DOI 10.5089/9798229015073.007',
    url: 'https://www.imf.org/en/publications/policy-papers/issues/2025/07/10/release-of-new-standards-for-macroeconomic-statistics-bpm7-568453',
    use: '编写者核读本地官方PDF全部7个物理页。支持BPM7于2025年3月发布白皮书预编辑版、integrated IIP和其他变化进入核心框架、NIR及数字化/全球化更新，以及建议2029–2030实施窗口；文件也明确后续最终版本与多语种流程。不支持把目标窗口当成每国实际完成日期、把白皮书冒称最终排版版，或用政策发布文件替代具体账户定义、现实数据版本和国别实施证据。',
  },
  {
    id: 9,
    authors: 'IMF Committee on Balance of Payments Statistics',
    year: '2026',
    accessedAt: '2026-09-16',
    title: 'IMF Committee on Balance of Payments Statistics 2025 Annual Report',
    publication: 'International Monetary Fund, March 2026',
    url: 'https://www.imf.org/-/media/files/publications/balance-of-payments-statistics/abpea2025001.pdf',
    use: '编写者核读物理页1–2、5–6、9–13与17–18，包括Executive Summary、§§2–5、§§10–17及Box 1。支持截至报告时BPM7仍是白皮书预编辑版、最终英文排版版预期约在2026年第四季度、2024年有190个经济体仍按BPM6报送BOP，以及全球不对称来自漏报、覆盖、标准采用、估计/源数据、分类、时点与伙伴归属等多种因素。不支持保证未来发布日期、把报告期全球合计当当前实时值、把总不对称分配给某国，或从不对称直接识别违法流动和因果。',
  },
];

export const balanceOfPaymentsSourceArchiveLedger = [
  {
    sourceId: 1,
    localPath: 'tmp/research/4-01-draft/imf-bpm7-white-cover-2025.pdf',
    physicalPages: 1076,
    fileBytes: 7367226,
    sha256: 'a770e733fed4b20ad8b487ba2281e06d49cf8ff7402a691ab0ae2db3231127e7',
    identity: 'IMF BPM7 White Cover (Pre-Edited), March 2025',
    actualReadScope: '仅核读来源1 use字段列出的章节、段落与附录；未冒称全本逐页核读。',
    evidenceBoundary: '用于概念与方法口径；不是最终排版版、实时国别数据、PIT数据或因果证据。',
  },
  {
    sourceId: 2,
    localPath: 'tmp/research/4-01-draft/imf-bpm7-annex13-changes-from-bpm6.pdf',
    physicalPages: 23,
    fileBytes: 326444,
    sha256: '07c0bf65bf5dd04e2863733669384856c8f28b48cf78eaed966ef2ebaf221b9e',
    identity: 'IMF BPM7 Annex 13 (V7), Changes from BPM6',
    actualReadScope: '核读全部23个物理页，并与白皮书手册中的Annex 13交叉核对。',
    evidenceBoundary: '用于版本差异与术语迁移；不能证明现实数据已经完成迁移。',
  },
  {
    sourceId: 8,
    localPath: 'tmp/research/4-01-draft/imf-policy-paper-bpm7-release-2025.pdf',
    physicalPages: 7,
    fileBytes: 236719,
    sha256: 'a9a927fe09c8925d69e61247f561f29bcf4fea1de15871a79d9c902de79c9ddb',
    identity: 'IMF Policy Paper 2025/023, Release of New Standards for Macroeconomic Statistics (BPM7)',
    actualReadScope: '核读全部7个物理页。',
    evidenceBoundary: '用于发布、更新主题与实施目标窗口；不是逐项账户定义或国别实施证明。',
  },
] as const;

export const lesson401ReadingList: LessonReading[] = [
  {
    title: '阅读路线一：先把“跨境”还原为居民—非居民关系',
    scope: 'BPM7第2章印刷页12–30，重点§§2.2–2.21；第3章§§3.145–3.149；第4章§§4.1–4.15，重点§§4.10–4.15；ECB当前页Balance of payments段落',
    reason: '先固定经济领土、居民身份、应计记录与交易边界，再进入账户。货物移动、付款币种和账户所在地都不能单独替代居民—非居民判定。BPM7用于概念，ECB页只说明当前欧元区BPM6实践。',
    url: lesson401References[0].url,
    group: 'core',
    links: [{ label: 'ECB当前方法页（BPM6）', url: lesson401References[5].url }],
  },
  {
    title: '阅读路线二：用一笔交易学复式，不用总表背平衡式',
    scope: 'BPM7第3章§§3.84–3.96与第8章§§8.1–8.13；ECB当前页复式记账段落',
    reason: '逐笔写出提供的经济价值和取得的金融对项。两条记录是同一交易的两面，不要求纸币越境；概念复式恒等并不保证来自不同现实来源的汇总表没有统计差异。',
    url: lesson401References[0].url,
    group: 'core',
    links: [{ label: 'ECB复式与账户概览', url: lesson401References[5].url }],
  },
  {
    title: '阅读路线三：分别掌握current、capital与financial的余额方向',
    scope: 'BPM7第2章§§2.20–2.30、第6章§§6.1–6.10与6.57–6.65、第8章；Annex 13全部23页；ECB 2023 booklet印刷页17–18（PDF物理页18–19）',
    reason: 'current/capital余额用revenue减expenditure，financial余额用资产净取得减负债净发生。再把金融账户拆成直接、证券、衍生品、其他与储备等功能类别，而不是期限或稳定性标签。把交易的credit/debit位置、数据传输的正号和账户余额方向分开，才能避免“资本流入必为金融账户正数”的常见符号错误。',
    url: lesson401References[1].url,
    group: 'core',
    links: [{ label: 'ECB BPM6符号与修订', url: lesson401References[6].url }],
  },
  {
    title: '阅读路线四：统计差异是诊断量，不是万能漏项桶',
    scope: 'BPM7第2章§§2.25–2.27；ECB 2026 Quality Report §6.2；BOPCOM 2025 Annual Report §§10–13',
    reason: '采用本课固定定义D=FAB−(CAB+KAB)，再观察规模、相对毛流量和符号持续性。差异暴露观测系统未闭合，却不自动定位漏项账户，更不能未经证据解释为资本外逃。',
    url: lesson401References[3].url,
    group: 'evidence',
    links: [{ label: 'BOPCOM全球不对称', url: lesson401References[8].url }],
  },
  {
    title: '阅读路线五：从金融交易走到integrated IIP',
    scope: 'BPM7第7章§§7.1–7.8、第9章§§9.1–9.10与第19章§§19.4–19.18；CPIS FAQ物理页3',
    reason: '把期初头寸、交易、汇率变化、其他价格变化、其他数量变化和期末头寸逐列桥接。两期头寸之差混合交易与持有损益，不能直接改名为资本流。',
    url: lesson401References[0].url,
    group: 'models',
    links: [{ label: 'CPIS头寸与交易边界', url: lesson401References[2].url }],
  },
  {
    title: '阅读路线六：储备资产先问控制与可用性，再问头寸变化',
    scope: 'BPM7第6章§§6.69–6.123及Boxes 6.5–6.6；ECB当前页financial account与IIP调节段落',
    reason: '储备资产是金融账户中的特定功能类别，不是央行所有外币资产。期末储备变化还包含汇率、价格和其他数量变化，因此不能仅凭头寸差反推干预；简单覆盖率也不是完整充足性判断。',
    url: lesson401References[0].url,
    group: 'systems',
    links: [{ label: 'ECB当前账户和IIP概览', url: lesson401References[5].url }],
  },
  {
    title: '阅读路线七：镜像数据是第二测量系统，不是裁决者',
    scope: 'BPM7 Annex 11印刷页839–853；CPIS FAQ全部4页；ECB 2026 Quality Report §8及Box 1',
    reason: '先记录伙伴归属、覆盖、估值、时点、分类和版本差，再比较本方与对手方。资产方资料可以帮助派生负债，却仍受非参与、托管链、漏报和修订影响。',
    url: lesson401References[2].url,
    group: 'evidence',
    links: [{ label: 'BPM7伙伴经济附录', url: lesson401References[0].url }, { label: 'ECB双边不对称', url: lesson401References[3].url }],
  },
  {
    title: '阅读路线八：把每一个现实数值贴上口径与版本时钟',
    scope: 'IMF BOP_AGG当前页Description/Latest Updates；ECB当前页Sources and methods；ECB booklet §5.2',
    reason: '下载前记录发布时间、观测期、修订期、覆盖与方法版。本课的概念主线使用BPM7预编辑版，但当前IMF BOP_AGG和ECB数据入口仍明确使用BPM6；双标签不能互相替换。',
    url: lesson401References[4].url,
    group: 'rules',
    links: [{ label: 'ECB当前BPM6口径', url: lesson401References[5].url }, { label: 'ECB updates-and-revisions', url: lesson401References[6].url }],
  },
  {
    title: '阅读路线九：只把BPM6→BPM7变化写到证据允许的粒度',
    scope: 'BPM7 Annex 13 standalone全部23页；IMF Policy Paper 2025/023全部7页',
    reason: '区分“名称改变”“标准分项新增”“分类改变”“补充分解”和“实施安排”。总体会计框架大体延续，不应把术语更新讲成历史序列自动断裂；白皮书也不能冒称最终排版版。',
    url: lesson401References[1].url,
    group: 'rules',
    links: [{ label: 'IMF发布与实施政策文件', url: lesson401References[7].url }, { label: '官方PDF', url: 'https://www.imf.org/-/media/files/publications/pp/2025/english/ppea2025023.pdf' }],
  },
  {
    title: '阅读路线十：用发布状态和不对称报告约束当前叙述',
    scope: 'BOPCOM 2025 Annual Report物理页5–6、9–13、17–18；IMF Policy Paper全部7页',
    reason: '报告说明2024报送仍以BPM6为主、BPM7处于预编辑版到最终版及2029–2030目标窗口的过渡，并列出全球/双边不对称的多源成因。因此教材只能讲方法与证据边界，不能虚构实时迁移、单一误差来源或国别因果。',
    url: lesson401References[8].url,
    group: 'systems',
    links: [{ label: 'IMF BPM7发布文件', url: lesson401References[7].url }],
  },
];
