import type {LessonReference,LessonReading} from './types';
export const lesson321References:LessonReference[]=[
 {id:1,authors:'International Monetary Fund',year:'2025（March白封面预编辑版）',accessedAt:'2026-09-15',title:'Integrated Balance of Payments and International Investment Position Manual, Seventh Edition',publication:'BPM7 white-cover/pre-edited，1076页；所引版本不等于各国历史统一实施',url:'https://www.imf.org/-/media/files/data/statistics/bpm6/draft-bpm7-wcv.pdf',use:'作者沿用上节明确的chapter2、储备、经常/金融账户选段；本节先实读原PDF50–53的2.1–2.12及281–285的6.9–6.19文字，完整初稿审查后另补读原PDF55的2.17–2.18及Box2.1开头，新增阅读钟单独保留。支持居民—非居民交易、IIP存量/重估桥、直接投资关系与投票权定义；不是通读1076页或OECD/CDIS全部指南。6.12的10%即时影响关系与超过50%控制不得互换，也不证明直接投资全是新建厂房。附属关系、证券交易和具体法律需各自条件。'},
 {id:2,authors:'Stefan Avdjiev, Robert N. McCauley and Hyun Song Shin',year:'2015',accessedAt:'2026-09-15',title:'Breaking free of the triple coincidence in international finance',publication:'BIS Working Papers No524，October2015，41页原PDF',url:'https://www.bis.org/publications/working-paper-524-breaking-free-triple-coincidence-international-finance.pdf',use:'作者实读原PDF1–11及16–22全文文字，并实际看PDF10的Graph1原图；12–15、23–41和其引用论文未通读/复算。支持居住地、货币和合并决策主体边界不必重合、净额可遮蔽融资腿及离岸公司债务经集团/银行回流的机制。它的历史总量和回归不是本课校准，净本金匹配不等于到期/信用匹配；本课所有数值另外设定。'},
 {id:3,authors:'Claudio Borio and Piti Disyatat',year:'2015',accessedAt:'2026-09-15',title:'Capital flows and the current account: Taking financing (more) seriously',publication:'BIS Working Papers No525，20October2015，50页；不混同2011WP346',url:'https://www.bis.org/publications/working-paper-525-capital-flows-and-current-account-taking-financing-more-seriously.pdf',use:'作者先实读原PDF5–18完整文字，随后补读1–4封面、摘要与目录；19–50完整模型/Annex及底层论文未通读。支持储蓄所释放真实资源与有日期支付融资的区别，以及经常账户净数不直接显示金融中介融资需要。CA与储蓄投资恒等式仍有统计条件和资源含义，不被本课宣布无用；原模型多次周转不是通用贷款乘数或已解决全部国际宏观争论。'},
 {id:4,authors:'Michael McLeay, Amar Radia and Ryland Thomas',year:'2014',accessedAt:'2026-09-15',title:'Money creation in the modern economy',publication:'Bank of England Quarterly Bulletin2014Q1，14–27；原PDF14页',url:'https://www.bankofengland.co.uk/-/media/boe/files/quarterly-bulletin/2014/money-creation-in-the-modern-economy.pdf',use:'作者实际读14页全部文字、参考文献及署名，并看原PDF3Figure1；其余图与ChartA数据未全部原图/底层复现，引用论文未逐篇取得。支持贷款创造存款、偿还回流，以及单家银行的盈利/风险/支付融资约束和总系统区别。UK2014的制度、利率和存款占比不是2026全世界现状；银行总存款负债不等于任何既定居民广义货币口径，央行准备金也不自动乘出贷款。'},
 {id:5,authors:'Carlos Cantú, Catherine Casanova, Rodrigo Alfaro, Fernando Chertman, Gerald Cisneros, Toni dos Santos, Roberto Lobato, Calixto Lopez, Facundo Luna, David Moreno, Miguel Sarmiento and Rafael Nivin',year:'2022',accessedAt:'2026-09-15',title:'How capital inflows translate into new bank lending: tracing the mechanism in Latin America',publication:'BIS Working Papers No1051，17November2022，35页原PDF',url:'https://www.bis.org/publications/working-paper-1051-how-capital-inflows-translate-new-bank-lending-tracing-mechanism-latin-america.pdf',use:'作者实际读原PDF1–23文字并看PDF13的Graph1与Equation1；24–35、Annex、各国原贷款登记数据与所引论文未通读/复估。支持按流入类型、银行资金/资本特征和借款风险区分信贷传导，使用多银行企业及企业—时点控制仍有识别条件。Chile未进入贷款增长meta而进入定价，低资本组也不等于不达法定下限；异质结果不被本课偷作统一系数、随机外生冲击或自动审批规则。'},
 {id:6,authors:'Jang-Yung Lee',year:'1997',accessedAt:'2026-09-15',title:'Sterilizing Capital Inflows',publication:'IMF Economic Issues No7，23页；原件imprint为February1997，网页/电子书列期另有March，引用年份不捏造同日',url:'https://www.imf.org/external/pubs/ft/issues7/issue7.pdf',use:'作者实际读本次取得23页全部文字、preface及出版署名；底层WP96/53、历史国别回归、其他系列册和当前法律未读/复现。支持央行已购汇情形下的冲销工具、市场替代与成本约束；不会由每笔私人流入自动推出当局购汇。本课C5明确选“卖既有国内债权”而非任何工具同账；净基础抵销不保证信贷/利率/价格全无影响。旧HTML与电子书正文入口返回403的记录保留，原PDF实际取得并校验。'},
 {id:7,authors:'Financial Stability Board',year:'2023',accessedAt:'2026-09-15',title:'Revised Policy Recommendations to Address Structural Vulnerabilities from Liquidity Mismatch in Open-Ended Funds',publication:'20December2023，42页原PDF；高层非约束性政策建议，非各国直接生效法律',url:'https://www.fsb.org/uploads/P201223-1.pdf',use:'作者实际读原PDF1–8及14–17完整文字；9–13、18–42、Annex与IOSCO底层文件未全文读。14页scope排除MMF与ETF；15页footnote15说明先动优势与成本/NAV调整条件，单纯预期未来跌价并不构成此概念。支持基金流动性错配和成本分配工具的条件机制，不认证任何具体基金授权、闸门、实时兑付或2026执行成效；借贷工具还可能增加杠杆/互联。'},
 {id:8,authors:'International Monetary Fund',year:'2022',accessedAt:'2026-09-15',title:'Review of the Institutional View on the Liberalization and Management of Capital Flows',publication:'Policy Paper releasepackage，98页；staff22February、Board21March、release30March2022分别保留',url:'https://www.imf.org/-/media/files/publications/pp/2022/english/ppea2022008.pdf',use:'作者实际读原PDF1–6及9–12全文文字、另读官方Capital Flows FAQ所列全部实质问答；7–8、13–98、四背景说明/Annex和具体法域法律未通读。支持资本流益处与币种/存量/本币资产市场风险的条件讨论及合资格的预防性政策范围；不是所有流入应被拦截的最优结论、宏观调整替代或当前国家政策许可。取得历史原件不认证最新实施、因果效果、福利和PIT。'},
];
export const lesson321ReadingList:LessonReading[]=[
 {title:'第一遍：先重建钱和银行账本',scope:'BoE2014原PDF1–7，尤其Figure1与贷款创造存款、单家银行限制；再读8–14回流与QE',reason:'把借款、存款、准备金与权益分别放到谁的两侧，明白“外资进来”和“银行发新贷款”是不同操作。英国旧年制度只作当时例子。',url:lesson321References[3].url,group:'core'},
 {title:'第二遍：把国家净额拆回融资腿',scope:'WP524原PDF5–11，随后16–22公司债/集团回流；再补12–15及23–41尚未由作者全文读完的经验和结论',reason:'对每条腿同时注明居住身份、支付币种、决策集团与期限，不拿合并国籍取消本地居民账，也不把教学170当未净交易gross。',url:lesson321References[1].url,group:'systems'},
 {title:'第三遍：资源约束与支付融资同时存在',scope:'WP525原PDF5–18（printed1–14）；19–50模型与Annex另行深化，别混入2011WP346版本',reason:'按每个部门有日期现金流重建融资，再核净经常账户与储蓄投资关系。不要由资源恒等式决定银行资金路线，亦不要反向宣称真实资源无限。',url:lesson321References[2].url,group:'models'},
 {title:'第四遍：校准统计边界而不是猜资金意义',scope:'BPM7所列March2025版本2.1–2.12、2.17–2.18（原PDF55）、6.9–6.19；进一步查相关金融账户分类和完整Annex6，后两项需另读',reason:'把存量重估与交易、直接投资投票关系与真实新投资分开；10%影响不是超过50%控制，基金份额还存在指定分类例外。',url:lesson321References[0].url,group:'rules'},
 {title:'第五遍：识别银行信贷供给的条件经验',scope:'WP1051原PDF1–23，逐country/supply-demand模型读；24–35完整结果、限制和Annex由读者继续',reason:'先理解企业—时点比较如何控制共同需求，再查银行暴露分配、样本和测量差异。Chile定价/增长覆盖不同，不把meta系数移成C3的审批量。',url:lesson321References[4].url,group:'evidence'},
 {title:'第六遍：用旧文识别冲销的两笔操作',scope:'Lee EconomicIssues7原PDF全文23页；底层WP96/53另取，不把两者当同一份完整阅读',reason:'手画央行购汇和后续吸收准备金，逐工具检查是卖资产还是发行负债。利息、资产替代和持续流入可能保留反馈，旧年国别不是现行指导。',url:lesson321References[5].url,group:'systems'},
 {title:'第七遍：基金现金压力与先动成本',scope:'FSB2023原PDF14–17，回看1–8；剩余建议/Annex和IOSCO另读，特别注意14scope与15footnote15',reason:'先问谁承担交易成本和估值调整，再讨论赎回时机；只预期价格跌不是先动优势。MMF/ETF不在该修订建议范围，不能凭本文宣布某基金必须设闸门。',url:lesson321References[6].url,group:'rules'},
 {title:'第八遍：益处、风险与可检验研究各归其位',scope:'IMF2022releasepackage原PDF1–6、9–12，再完整读7–8及13–98的论证/背景；官方FAQ另作为导航',reason:'把投资/风险分担的益处接到制度和金融能力，把预防性措施条件与宏观调整分开。读完机制地图后再独立设计PIT事件/银行样本，不能把阅读当政策效果评估。',url:lesson321References[7].url,group:'systems',links:[{label:'IMF官方Capital Flows FAQ',url:'https://www.imf.org/en/about/faq/capital-flows'}]},
];
