import type {LessonReference,LessonReading} from './types';
export const lesson322References:LessonReference[]=[
 {id:1,authors:'National Bureau of Economic Research',year:'2025（页内修订2025-10-07）',accessedAt:'2026-09-15',title:'Business Cycle Dating Procedure: Frequently Asked Questions',publication:'NBER美国商业周期定年官方FAQ；本次实际取得HTML全文主要问答与滞后表',url:'https://www.nber.org/research/business-cycle-dating/business-cycle-dating-procedure-frequently-asked-questions',use:'编写者实际读全部main实质问答和公告延迟表；未另取FRED/Excel、全部历史公告/数据vintage。支持广度/深度/持续、多个活动指标、无固定两季度GDP定义、扩张方向不要求回旧峰，以及事件参考日不等公告可得日。美国机构程序不普遍化为全球法则；历史滞后示例不改成未来固定公告延迟。web入口403与随后实际curl200原件获取分开保留。'},
 {id:2,authors:'Arthur F. Burns and Wesley C. Mitchell',year:'1946',accessedAt:'2026-09-15',title:'Measuring Business Cycles — Working Plans',publication:'NBER经典专著首章，printed3–22；本次原PDF23页含出版前页，不能采用网页自动citation误列2019',url:'https://www.nber.org/system/files/chapters/c2980/c2980.pdf',use:'编写者读原PDF1–8选段文字，并实际看原整页4/7/8；部分扫描OCR两面对页交错，原页7/8中央完整定义/方法段另以真图核读。另读官方书目TOC，不称560页专著或首章其余全文已读。支持反复但非严格定时、aggregate与micro时序/单位问题；时代性的时长描述不当今日恒定周期。后续章节仅列为读者深化路线，不归编写者个人已读。'},
 {id:3,authors:'Claudio Borio',year:'2012',accessedAt:'2026-09-15',title:'The financial cycle and macroeconomics: What have we learnt?',publication:'BIS Working Papers No395，10December2012；原PDF38页',url:'https://www.bis.org/publications/working-paper-395-financial-cycle-and-macroeconomics-what-have-we-learnt.pdf',use:'编写者实际读原PDF1–14全部文字；15–38、底层文献、原图及数据未通读/复算。支持作者明确的信用房地产金融周期视角、历史中期特征和活动/金融反馈框架，不代表统一共识、自然16年时钟、必然危机或全体宏观模型已被否定。合同和损失传导在本课明列条件，不用论文名给缺失因果系数背书。'},
 {id:4,authors:'Mathias Drehmann, Claudio Borio and Kostas Tsatsaronis',year:'2012',accessedAt:'2026-09-15',title:'Characterising the financial cycle: don’t lose sight of the medium term!',publication:'BIS Working Papers No380，13June2012；原PDF43页；后续文件modified日期不改首次发表钟',url:'https://www.bis.org/publications/working-paper-380-characterising-financial-cycle-dont-lose-sight-medium-term.pdf',use:'编写者实读原PDF1–11及33全部文字并真看原PDF11；未读12–32/34–43完整结果/Annex或取代码复现。支持所选七国1960–2011数据覆盖、real/log变换与不同频带/峰谷规则的测量区别。原PDF11/33均写5年并括40季度，单位不一致保留未解，不静改20季度或按40实现。历史危机资料有当时版本/专家调整，不能倒称用2026数据库。'},
 {id:5,authors:'Stijn Claessens, M. Ayhan Kose and Marco E. Terrones',year:'2011',accessedAt:'2026-09-15',title:'How Do Business and Financial Cycles Interact?',publication:'IMF Working Paper WP11/88，April2011；原PDF55页',url:'https://www.imf.org/-/media/websites/imf/imported-full-text-pdf/external/pubs/ft/wp/2011/_wp1188.pdf',use:'编写者实读原PDF1–13全部文字；14–55回归结果、Appendix、原图和底层数据未通读/重估。支持44国分组/起点不同且截至2007Q4的样本、经典水平峰谷/居中窗口方法、恢复水平段与固定窗口幅度的区别及共动对象。未包含2008/COVID不补作当前经验；相关/相位同相不独立认证因果、显著性或危机预报。'},
 {id:6,authors:'Iñaki Aldasoro, Stefan Avdjiev, Claudio Borio and Piti Disyatat',year:'2020',accessedAt:'2026-09-15',title:'Global and domestic financial cycles: variations on a theme',publication:'BIS Working Papers No864，official11May2020；稿件5May与网页发布钟分开，原PDF32页',url:'https://www.bis.org/publications/working-paper-864-global-and-domestic-financial-cycles-variations-theme.pdf',use:'编写者实读原PDF1–9全部文字；10–32、Annex、原Graph1、底层价格/流量数据及估计未读/重跑。支持国内信用房地产与全球风险价格/融资视角在变量、尺度和覆盖上不同；日频价格因子与季度流量因子不无条件互换。各序列国家覆盖及起点不同，858价格资产等原资料不作为本课校准，不宣称重估因子或全球统一周期。'},
 {id:7,authors:'James D. Hamilton',year:'2017',accessedAt:'2026-09-15',title:'Why You Should Never Use the Hodrick-Prescott Filter',publication:'NBER Working Paper No23429，May2017；本次原PDF47页；2018期刊100(5):831–843仅metadata对应',url:'https://www.nber.org/system/files/working_papers/w23429/w23429.pdf',use:'编写者实际读原PDF1–19全部文字，含脚注16及替代量定义；20–47完整证明/结果、图数据与代码未读/复现。支持HP可能产生动态伪影、端点/信息依赖与参数选择警示；不据标题宣布所有去趋势无用。脚注16的OLS未来系数影响/渐近性质不是有限PIT认证，替代回归及无参数差分不被三点均值冒名复现或判普遍最优。2018期刊全文未由编写者阅读。'},
 {id:8,authors:'Luc Laeven and Fabián Valencia',year:'2026',accessedAt:'2026-09-15',title:'Systemic Banking Crises Database: 1970–2025',publication:'IMF Working Paper WP26/94，official15May2026；URL路径14May、封面May分别保留；原PDF47页',url:'https://www.imf.org/-/media/files/publications/wp/2026/english/wpiea2026094-source-pdf.pdf',use:'编写者实读原PDF1–2及5–9完整文字，并真看原PDF7；3–4/10–47全部结果/Appendix、数据ZIP及事件标签未取/复算。支持具体系统银行危机条件、严重损失例外、borderline及版本更新；164包含边界事件，不能全称严格系统危机。2026不良贷款脚注有三年内至少倍增等条件；详细阈值与摘要等号措辞不擅消歧。特定2023事件未满足该定义不等无风险，旧事件年份也不等2026标签在旧时刻可得。'},
 {id:9,authors:'Luc Laeven and Fabián Valencia',year:'2018',accessedAt:'2026-09-15',title:'Systemic Banking Crises Revisited',publication:'IMF Working Paper WP18/206，14September2018；原PDF48页；作为独立旧版本比较',url:'https://www.imf.org/-/media/files/publications/wp/2018/wp18206.pdf',use:'编写者先实读原PDF1–2及5–7全部文字和官方publication metadata，来源预备审查后另于2026-09-16T01:46:36Z补读原PDF9完整文字，核151与日期含borderline的直接说明；新增阅读钟另存，不倒改旧passport。其余全文/数据未读/复算；旧脚注不擅添加2026的倍增条件。原则延续不等每一细则逐字同版；未取得2020版本，不冒称已审核完整全部更新链或把2018/2026当同一文件身份。'},
 {id:10,authors:'Michael McLeay, Amar Radia and Ryland Thomas',year:'2014',accessedAt:'2026-09-15',title:'Money creation in the modern economy',publication:'Bank of England Quarterly Bulletin2014Q1，printed14–27；原PDF14页',url:'https://www.bankofengland.co.uk/-/media/boe/files/quarterly-bulletin/2014/money-creation-in-the-modern-economy.pdf',use:'编写者本轮较早为3.21逐段读完14页全部文字/参考并真看原PDF3Figure1；3.22原件字节精确复用，不称后来复制时再次全文读。支持贷款/偿还两侧、权益与盈利/风险/融资限制，辅助本课已另给损失的封闭记账直觉。其余图数据/底层论文未全部复现，UK2014不泛化当前所有国家制度、法律、M2或系统危机定义。核销不是现金偿还属于本课明确账桥。'},
];
export const lesson322ReadingList:LessonReading[]=[
 {title:'阅读路线一：先把活动、方向与公告分开',scope:'NBER FAQ全部主要问答与公告滞后表；历史公告和数据vintage若用于研究须另取得',reason:'边读边写“对象—参考期—公开时点—版本”，不要把两季GDP口号替机构程序，也不要把最终低谷贴回实时输入。美国程序的适用范围要保留。',url:lesson322References[0].url,group:'core'},
 {title:'阅读路线二：经典周期为什么不是固定振荡器',scope:'Burns–Mitchell Working Plans printed3–22完整首章；专著第4章Dating56–114、第6章unit203–269、第7章trend270–309由读者继续',reason:'编写者只读开篇选段，后列章是深化目标不是已读声明。读时把aggregate共动、个体异步、单位与参照拆开，历史时长不改成当前倒计时。',url:lesson322References[1].url,group:'core',links:[{label:'NBER专著官方目录',url:'https://www.nber.org/books-and-chapters/measuring-business-cycles'}]},
 {title:'阅读路线三：金融周期视角与有条件的反馈',scope:'WP395原PDF1–14先读，再完整15–38及其引用文献；后两项编写者未全文核读',reason:'把作者的信用房地产镜头接到谁的合同、抵押和承损，分清观察事实、候选机制与政策主张。不要将平均中期时长或五个特征当无条件定律。',url:lesson322References[2].url,group:'systems'},
 {title:'阅读路线四：周期是怎样被测量出来的',scope:'WP380方法开篇原PDF1–11，随后完整Annex及结果；原PDF11/33的5年40季度异常须以勘误/代码另核',reason:'逐项记变量、real/log处理、频率、频带、居中窗口与样本端点。原文单位异常不靠常识静改，也不据未读附录声称算法复现。',url:lesson322References[3].url,group:'models'},
 {title:'阅读路线五：经典相位、恢复与跨国经验的边界',scope:'WP11/88原PDF1–13方法和样本，然后14–55全部经验结果/Appendix',reason:'比较活动和金融代理怎样定峰谷、怎样量恢复与共动；分组覆盖截至2007Q4。进一步读回归时单独问识别与样本依赖，不能从方法段推出尚未复算的因果。',url:lesson322References[4].url,group:'evidence'},
 {title:'阅读路线六：国内与全球不是同一个代理',scope:'WP864原PDF1–9框架/覆盖，再读10–32结果/Annex及所引价格因子研究',reason:'把国内信用房地产、全球风险价格和跨境流量各自放到时间尺度。原数据频率和国家覆盖不统一，不拿一个全球因子替每家银行的支付约束。',url:lesson322References[5].url,group:'systems'},
 {title:'阅读路线七：特征、系数与模型选择的训练时钟',scope:'Hamilton2017WP23429原PDF1–19，尤其脚注16；20–47完整证明/结果与代码由读者另查，2018期刊版亦需另读',reason:'不只查输入滞后，还查参数估计及选择是否用了未来。三点均值不是任何原算法复现，方法批评与严格PIT/样本外价值需要不同证据。',url:lesson322References[6].url,group:'models'},
 {title:'阅读路线八：把危机定义读成条件而非一个标签字',scope:'2026WP26/94原PDF1–2/5–9先逐条读，再完整其余结果/Appendix和数据说明',reason:'单列困境、重大介入、严重损失例外与borderline，记录分母/窗口/脚注。164不能全改成严格系统危机，现实金融风险也不被这个数据库穷尽。',url:lesson322References[7].url,group:'rules'},
 {title:'阅读路线九：旧版本比较与历史可得性',scope:'2018WP18/206原PDF1–2/5–7对比2026定义；完整旧附录及2020中间版本需读者另取得',reason:'原则延续不代字节同版，每次条件与旧事件补录要带版本钟。今天用新版重估历史是新事后研究，不是2012原论文复制或实时预报。',url:lesson322References[8].url,group:'evidence'},
 {title:'阅读路线十：回到账本，闭合活动与金融的主体桥',scope:'BoE2014原14页全文，尤其贷款与偿还记账、权益及单家银行约束；现行会计/法域另查',reason:'先手画贷款毛额、偿还、核销和承损，再问下一步谁真正改变报价或授信。记账正确不证明供给冲击、法律危机、全体制度或生产指标。',url:lesson322References[9].url,group:'systems'},
];
