import {lesson301} from './lesson-3-01';
import {lesson314,canonicalCreditCycleStateExample} from './lesson-3-14';
import {cycleCanonicalInputs,cycleEvaluators} from '../components/cycleFixtures';
import type {CycleResult} from '../components/cycleFixtures';
import {cycleLabs} from '../components/cycleLabDefinitions';
function required<T>(r:CycleResult<T>):T{if(r.status==='STOP')throw Error('Invalid canonical cycle '+r.reason);return r.value;}
const draftPreparedAt='2026-09-16T01:42:32Z';
const prerequisites=[
 {lessonId:lesson301.id,revision:lesson301.revision,reviewStatus:lesson301.reviewStatus,actualLesson:lesson301,reviews:lesson301.reviews,canonicalNumericalState:null,producerMarker:{field:null,reviewFrozenAt:null,meaning:'current lesson record does not expose a separate canonical numerical/approved-body freeze marker; actual r6 reviews preserved'},numericValuesConsumed:false,numericCalibration:false},
 {lessonId:lesson314.id,revision:lesson314.revision,reviewStatus:lesson314.reviewStatus,actualLesson:lesson314,reviews:lesson314.reviews,canonicalNumericalState:canonicalCreditCycleStateExample,producerMarker:{field:'auditTimestamps.reviewFrozenAt',reviewFrozenAt:canonicalCreditCycleStateExample.auditTimestamps.reviewFrozenAt,meaning:'actual named upstream review marker preserved; not reinterpreted as historical availability or fabricated new approved-body clock'},numericValuesConsumed:false,numericCalibration:false},
] as const;
export const canonicalCycleStateExample={
 schemaVersion:'canonicalBusinessFinancialCycleState.v1',stateId:'3.22-independent-SYN-r1',
 scopePassport:{draftPreparedAt,registeredAt:'2026-09-16T01:56:14Z' as string|null,observedCountry:null,semanticPrerequisites:['3.01','3.14'],noCommonCountryTrajectory:true,scenarios:cycleLabs.map(l=>({id:l.id,scope:l.passport})),classificationIsNotCause:true},
 inputLineage:[],semanticPrerequisiteStates:prerequisites,
 clockState:{draftPreparedAt,informationCutoff:null as string|null,ownReviewFrozenAt:'2026-09-16T02:40:56.342Z' as string|null,referenceDate:null,firstPublishedAt:null,revisedAt:null,officialAnnouncementAt:null,parameterTrainingCutoff:null,modelSelectionCutoff:null,obtainedAt:null,historicalAvailabilityVerified:false,eachExperimentIsIndependent:true,c4:'t cutoff with disclosed ex-post t+1 counterfactuals, never available asOf centered amount',c5:'same two reference quarters; synthetic inclusive release ordinals, first strictly before revision',labelVersions:'2018 and 2026 publications are separate, old event year does not imply old label availability'},
 unitContract:{indices:'positive raw safe integers1..1000000, same measurement basis within each experiment',amounts:'native SYN raw safe integers0..1000000; initial C7 equity must be positive and exact ledger closed',losses:'integer percent0..100 of explicitly recognized loan losses, not house-price changes',ordinals:'synthetic safe integer sequencing0..1000000, not actual calendar/announcement latency',observations:'one shared window positive N1..1000000, nonnegative integer marginals and feasible four-cell joint table',ratios:'same-window nominal credit stock/output flow; growth percent differs from percentage-point ratio change',calculation:'safe integer sums/products/zero-sign tests before finite division; twelve-digit display is presentation only, not exact rational country trajectory',missing:'unknown real or as-of unavailable objects are null, not numeric0; illegal raw/ledger/time/table input STOP has no stale value'},
 directionState:{input:cycleCanonicalInputs.C1,result:required(cycleEvaluators.C1(cycleCanonicalInputs.C1)),suppliedEarlierPeakNotDatedByProgram:true},
 creditRatioState:{input:cycleCanonicalInputs.C2,result:required(cycleEvaluators.C2(cycleCanonicalInputs.C2)),notOfficialCreditGap:true},
 loanStockState:{input:cycleCanonicalInputs.C3,result:required(cycleEvaluators.C3(cycleCanonicalInputs.C3)),otherAdjustmentsExplicitlyExcludedOnlyHere:true},
 futureDependenceState:{input:cycleCanonicalInputs.C4,result:required(cycleEvaluators.C4(cycleCanonicalInputs.C4)),notHpHamiltonOrWp380Replication:true},
 vintageState:{input:cycleCanonicalInputs.C5,result:required(cycleEvaluators.C5(cycleCanonicalInputs.C5)),notActualHistoricalDatabase:true},
 concordanceState:{input:cycleCanonicalInputs.C6,result:required(cycleEvaluators.C6(cycleCanonicalInputs.C6)),independentMarginalBaselineNotTest:true},
 lossCapacityState:{input:cycleCanonicalInputs.C7,result:required(cycleEvaluators.C7(cycleCanonicalInputs.C7)),recognizedLossStipulatedNotGeneratedFromPrices:true},
 actualActivityState:{realGDP:null,employment:null,income:null,production:null,officialBusinessPhase:null,realRecoveryDate:null,potentialOutput:null},
 actualFinancialPhaseState:{realCredit:null,realPropertyPrices:null,globalAssetPriceFactor:null,estimatedFinancialPhase:null,cycleLength:null,originalWp380CodeThreshold:null},
 systemicCrisisLabelState:{observedEvent:null,legalInsolvency:null,actualSystemicCrisis:null,selectedHistoricalLabelVersion:null,actualLabelPublicationDate:null,versionDescriptions:['Laeven–Valencia2018 WP18/206','Laeven–Valencia2026 WP26/94 includes borderline in stated total'],notUniversalRiskDefinition:true},
 trainingState:{realFilter:null,realCoefficients:null,rollingTrainingWindow:null,actualModelChoice:null,asOfFeatureArchive:null,futureCoefficientInfluenceCertifiedAbsent:false},
 creditBehaviorState:{actualLoanDemand:null,actualLoanSupply:null,approvedLoans:null,actualLoanPricing:null,recognizedRealLoss:null,actualCapitalRepair:null},
 policyResponseState:{observedMonetaryAction:null,observedFiscalAction:null,resolutionRules:null,actualTransmission:null,optimalPolicy:null},
 regimeState:{observedInstitutionalRegime:null,statisticalBreak:null,estimatedLatentState:null,structuralBreak:null,predictedSwitch:null},
 feedbackState:{actualIncomeToLoss:null,actualLossToCredit:null,actualCreditToSpending:null,actualPriceCollateralFeedback:null,autoRecursivePath:false},
 identificationState:{historicalPITVerified:false,causalEffect:null,forecastPerformance:null,empiricalIndependence:null,statisticalSignificance:null,sourceReadingIsNotReplication:true,preflightIsNotWholeLessonApproval:true},
 evidenceState:{mode:'independent-SYN-with-declared-primary-reading',observedSeriesImported:false,numericCalibration:false,productionEligibility:false,twoFullApprovalsRegistered:true},
 dynamicDataPassports:[],boundaryRoutes:['3.01 activity and measurement','3.14 credit commitments and feedback','3.11/3.15/3.16 conditional net-worth maturity/property interfaces','Chapter1 orders and Chapter2 heterogeneous institutions','3.21 domestic entry and Chapter4 global lenses','Chapter5 institutions and Chapter6 expectations','7.07 regime switching/structural break and Chapter7 falsifiable research'],
} as const;
export const canonicalCycleFields=['schemaVersion','stateId','scopePassport','inputLineage','semanticPrerequisiteStates','clockState','unitContract','directionState','creditRatioState','loanStockState','futureDependenceState','vintageState','concordanceState','lossCapacityState','actualActivityState','actualFinancialPhaseState','systemicCrisisLabelState','trainingState','creditBehaviorState','policyResponseState','regimeState','feedbackState','identificationState','evidenceState','dynamicDataPassports','boundaryRoutes'] as const satisfies readonly(keyof typeof canonicalCycleStateExample)[];
const s=canonicalCycleStateExample;
const inputs=[s.directionState.input,s.creditRatioState.input,s.loanStockState.input,s.futureDependenceState.input,s.vintageState.input,s.concordanceState.input,s.lossCapacityState.input];
export const canonicalCycleAudit=[
 {key:'all26 top-level fields exactly enumerated with no silent extras',passed:Object.keys(s).length===26&&canonicalCycleFields.length===26&&new Set(canonicalCycleFields).size===26&&canonicalCycleFields.every(k=>Object.hasOwnProperty.call(s,k))},
 {key:'actual Master3.01 r6 and3.14 r1 lesson/review/state identities preserved without consuming numbers',passed:prerequisites[0].actualLesson===lesson301&&prerequisites[0].revision==='3.01-r6'&&prerequisites[0].reviews===lesson301.reviews&&prerequisites[0].reviewStatus==='double-reviewed'&&prerequisites[0].canonicalNumericalState===null&&prerequisites[1].actualLesson===lesson314&&prerequisites[1].revision==='3.14-r1'&&prerequisites[1].reviews===lesson314.reviews&&prerequisites[1].canonicalNumericalState===canonicalCreditCycleStateExample&&prerequisites[1].producerMarker.reviewFrozenAt==='2026-09-14T17:03:09+08:00'&&prerequisites.every(p=>!p.numericValuesConsumed&&!p.numericCalibration)&&s.inputLineage.length===0},
 {key:'seven independent exact canonical input identities and no auto-recursive country path',passed:inputs.every((input,i)=>input===cycleLabs[i].initial)&&s.scopePassport.noCommonCountryTrajectory&&!s.feedbackState.autoRecursivePath},
 {key:'draft/registration/body-review clocks not conflated with real historical availability',passed:Number.isFinite(Date.parse(draftPreparedAt))&&(s.scopePassport.registeredAt===null||Number.isFinite(Date.parse(s.scopePassport.registeredAt)))&&(s.clockState.ownReviewFrozenAt===null||Number.isFinite(Date.parse(s.clockState.ownReviewFrozenAt)))&&!s.clockState.historicalAvailabilityVerified},
 {key:'known conditional zero distinct from gross40, asOf null, legal unknown and nonpositive equity',passed:s.loanStockState.result.netStockChange===0&&s.loanStockState.result.newGrossLending===40&&s.futureDependenceState.result.retrospectiveResidualA===0&&s.futureDependenceState.result.asOfCenteredResidual===null&&s.lossCapacityState.result.stipulatedOutputChange===0&&s.lossCapacityState.result.equityB===-6&&s.lossCapacityState.result.leverageB===null&&s.systemicCrisisLabelState.actualSystemicCrisis===null},
 {key:'whole-body approval registration matches its own freeze clock, never certifies observed data, causal/PIT/forecast or production',passed:s.evidenceState.twoFullApprovalsRegistered===(s.clockState.ownReviewFrozenAt!==null)&&!s.evidenceState.observedSeriesImported&&!s.evidenceState.numericCalibration&&!s.evidenceState.productionEligibility&&!s.identificationState.historicalPITVerified&&s.identificationState.causalEffect===null&&s.identificationState.forecastPerformance===null&&s.dynamicDataPassports.length===0},
] as const;
