import type { LessonReading, LessonReference } from './types';

export type DollarFundingSourceId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18;

export const lesson405References: LessonReference[] = [
  {
    id: 1,
    authors: 'Committee on the Global Financial System',
    year: '2020',
    accessedAt: '2026-09-16',
    title: 'US dollar funding: an international perspective',
    publication: 'BIS, CGFS Papers No 65',
    url: 'https://www.bis.org/publications/cgfs-paper-65-us-dollar-funding-international-perspective.pdf',
    use: '核读PDF文件页6–21、39–45、53–56及68–69。支持美元融资网络跨主体、地区与工具分布，支持银行、货币市场基金、交易商和最终用款人的多层连接，也支持price—quantity—access与basis边界。报告不能提供2026实时规模、逐实体缺口、统一危机脚本或单一因果份额。',
  },
  {
    id: 2,
    authors: 'Committee on the Global Financial System',
    year: '2026',
    accessedAt: '2026-09-16',
    title: 'Foreign currency funding risk and cross-border liquidity',
    publication: 'BIS, CGFS Papers No 71',
    url: 'https://www.bis.org/publications/cgfs-paper-71-foreign-currency-funding-risk-and-cross-border-liquidity.pdf',
    use: '核读PDF文件页6–20、28–34及39–40。支持按法律实体、币种、booking location、nationality与期限观察外币资金风险，支持衍生品滚续、内部资本市场和央行后备的条件性。聚合调查不能识别每个实体，也不证明集团资源可无条件跨境转移。',
  },
  {
    id: 3,
    authors: 'Claudio Borio, Robert McCauley & Patrick McGuire',
    year: '2022',
    accessedAt: '2026-09-16',
    title: 'Dollar debt in FX swaps and forwards: huge, missing and growing',
    publication: 'BIS Quarterly Review feature',
    url: 'https://www.bis.org/publications/qr-202212/dollar-debt-fx-swaps-and-forwards-huge-missing-and-growing',
    use: '支持FX swap、forward与currency swap包含未来美元交付腿，传统表内债务统计会遗漏部分gross义务，短期限会制造rollover clock。历史gross notional不是净债务、损失、明日缺口或逐实体压力，也不能忽略法律净额与现金流方向。',
  },
  {
    id: 4,
    authors: 'Claudio Borio, Robert McCauley, Patrick McGuire & Vladyslav Sushko',
    year: '2016',
    accessedAt: '2026-09-16',
    title: 'Covered interest parity lost: understanding the cross-currency basis',
    publication: 'BIS Quarterly Review feature',
    url: 'https://www.bis.org/publications/qr-201609/covered-interest-parity-lost-understanding-cross-currency-basis',
    use: '核读全文中CIP定义、framework、hedging demand、limits to arbitrage与结论。支持basis是直接与合成资金成本之间的相对价格，且需求与中介资产负债表成本可令偏离持续。它不支持把basis符号直接翻译为全球美元短缺、违约概率或确定因果。',
  },
  {
    id: 5,
    authors: 'Wenxin Du, Alexander Tepper & Adrien Verdelhan',
    year: '2017 working-paper version',
    accessedAt: '2026-09-16',
    title: 'Deviations from Covered Interest Rate Parity',
    publication: 'NBER Working Paper 23170; later published in the Journal of Finance',
    url: 'https://www.nber.org/papers/w23170',
    use: '核读84页NBER工作论文版本，支持CIP偏离的持续性、横截面和季末模式与受约束套利/资产负债表成本一致。没有把该版本冒充Journal of Finance publisher final；论文样本中的系数、货币和时期不能当实时通用参数。',
  },
  {
    id: 6,
    authors: 'Stefan Avdjiev, Wenxin Du, Catherine Koch & Hyun Song Shin',
    year: '2016',
    accessedAt: '2026-09-16',
    title: 'The dollar, bank leverage and the deviation from covered interest parity',
    publication: 'BIS Working Papers No 592',
    url: 'https://www.bis.org/publications/working-paper-592-dollar-bank-leverage-and-deviation-covered-interest-parity.pdf',
    use: '核读官方43页工作论文。支持美元、银行杠杆状态和CIP偏离在其模型与样本中共同变化，并把美元作为全球银行资产负债表影子价格的经验代理之一。它不建立“美元上涨必然导致basis变化”的恒等式，也不能替代逐实体现金流证据。',
  },
  {
    id: 7,
    authors: 'Victoria Ivashina, David S. Scharfstein & Jeremy C. Stein',
    year: '2012 working-paper version',
    accessedAt: '2026-09-16',
    title: 'Dollar Funding and the Lending Behavior of Global Banks',
    publication: 'Federal Reserve Board FEDS 2012-74; later published in QJE',
    url: 'https://www.federalreserve.gov/pubs/feds/2012/201274/index.html',
    use: '核读Federal Reserve完整HTML工作论文。支持2011年美国MMF对欧元区银行撤资、美元融资压力和币种特定贷款收缩之间的历史机制与横截面设计。Harvard作者PDF与QJE publisher final未读；该样本不能外推为所有银行、时期或法域的固定反应。',
  },
  {
    id: 8,
    authors: 'Financial Stability Board',
    year: '2020',
    accessedAt: '2026-09-16',
    title: 'Holistic Review of the March Market Turmoil',
    publication: 'Financial Stability Board',
    url: 'https://www.fsb.org/uploads/P171120-2.pdf',
    use: '核读60页官方PDF。支持2020年现金争夺中NBFI赎回、保证金、dealer capacity与跨市场/跨境反馈并存，也支持公共措施改变市场功能。它不支持单因归责，不应把USD cross-currency basis与Treasury cash–futures basis trade混为同一对象，也不是下一次危机的机械脚本。',
  },
  {
    id: 9,
    authors: 'Financial Stability Board',
    year: '2022',
    accessedAt: '2026-09-16',
    title: 'US Dollar Funding and Emerging Market Economy Vulnerabilities',
    publication: 'Financial Stability Board',
    url: 'https://www.fsb.org/uploads/P260422.pdf',
    use: '核读PDF文件页4–11、23–30及38–42。支持新兴市场美元债、非银资金链、赎回/资产出售以及自然和金融对冲的异质性。核心样本与部分回归不代表全部经济体，不提供2026当前风险排名或个别主体的hedge ratio。',
  },
  {
    id: 10,
    authors: 'Board of Governors of the Federal Reserve System',
    year: 'current FAQ, updated through 2022',
    accessedAt: '2026-09-17',
    title: 'Swap Lines FAQs',
    publication: 'Federal Reserve Board',
    url: 'https://www.federalreserve.gov/newsevents/pressreleases/swap-lines-faqs.htm',
    use: '支持第一层对手是Federal Reserve与外国央行，交易包含初始与到期反转的两币腿；外国央行决定本地资格、分配和抵押并承担其私人对手信用关系。它不支持私人机构直接向Fed借款、自动获配或无限覆盖。',
  },
  {
    id: 11,
    authors: 'Federal Reserve Bank of New York',
    year: 'current operations page',
    accessedAt: '2026-09-17',
    title: 'Central Bank Swap Arrangements',
    publication: 'New York Fed Markets & Policy Implementation',
    url: 'https://www.newyorkfed.org/markets/international-market-operations/central-bank-swap-arrangements',
    use: '支持并与来源10交叉验证当前五家standing对手方及操作结构。当前页面只证明设施和对手方安排，不证明某私人实体资格、当期用量、下一次操作时间或政策效果。',
  },
  {
    id: 12,
    authors: 'Board of Governors of the Federal Reserve System',
    year: 'current FAQ; structure updated 2024',
    accessedAt: '2026-09-16',
    title: 'FIMA Repo Facility — FAQs',
    publication: 'Federal Reserve Board',
    url: 'https://www.federalreserve.gov/monetarypolicy/fima-repo-facility-faqs.htm',
    use: '支持获批FIMA account holder以其Treasury collateral与SOMA进行repo，期限为overnight或seven-calendar-day，并采用抵押、margin和backstop pricing。它不是私人银行窗口，不支持无Treasury、无批准、无结算准备或无限额度，也不保证随后向本地私人部门分配。',
  },
  {
    id: 13,
    authors: 'Mark Choi, Linda S. Goldberg, Robert Lerman & Fabiola Ravazzolo',
    year: '2022',
    accessedAt: '2026-09-16',
    title: 'The Fed’s Central Bank Swap Lines and FIMA Repo Facility',
    publication: 'Federal Reserve Bank of New York Economic Policy Review, 28(1)',
    url: 'https://www.newyorkfed.org/medialibrary/media/research/epr/2022/epr_2022_fima-repo_choi.pdf',
    use: '核读PDF文件页7–13及机制图。支持swap line与FIMA在对手方、货币/抵押物流和历史用途上的差异，并讨论FIMA减少被迫出售Treasury的候选渠道。历史表格中的旧期限条款不能覆盖2024更新后的FAQ，低使用量也不单独识别设施效果。',
  },
  {
    id: 14,
    authors: 'Bank for International Settlements',
    year: '2019',
    accessedAt: '2026-09-16',
    title: 'Reporting guidelines for the BIS international banking statistics',
    publication: 'BIS Statistical Reporting Guidelines',
    url: 'https://www.bis.org/publications/reporting-guidelines-bis-international-banking-statistics.pdf',
    use: '核读PDF文件页5–12及21–35。支持LBS按residence和unconsolidated记录并含intragroup，CBS按nationality和consolidated记录且排除intragroup。两套聚合口径不能直接相加，也不提供完整衍生品现金腿、逐实体余额或实时funding access。',
  },
  {
    id: 15,
    authors: 'Bank for International Settlements',
    year: '2026',
    accessedAt: '2026-09-16',
    title: 'Global liquidity indicators: methodology',
    publication: 'BIS Statistics',
    url: 'https://www.bis.org/statistics/gli/gli_methodology.pdf',
    use: '核读PDF文件页1–10。支持GLI按借款人residence与币种跟踪非银的银行贷款和国际债券，并包含估计与覆盖假设。GLI不是全部全球美元融资、完整FX-swap义务或实体级access账本，不能单独判定shortage。',
  },
  {
    id: 16,
    authors: 'Bank for International Settlements',
    year: '2015 background note',
    accessedAt: '2026-09-16',
    title: 'Global liquidity indicators: background and interpretation',
    publication: 'BIS Statistics background',
    url: 'https://www.bis.org/publications/global-liquidity-indicators-background-and-interpretation',
    use: '支持全球流动性不可直接观察，应结合price与quantity等互补指标。它不提供一个固定综合报警器、危机阈值或逐主体美元缺口。',
  },
  {
    id: 17,
    authors: 'Committee on Payments and Market Infrastructures',
    year: '2016',
    accessedAt: '2026-09-16',
    title: 'Correspondent banking — final report',
    publication: 'BIS, CPMI Papers No 147',
    url: 'https://www.bis.org/cpmi/publ/d147.pdf',
    use: '核读PDF文件页13–14与47。支持correspondent代表respondent持有存款并提供支付及其他服务，服务可能包含贷款。由此采取的证据推论是：仅看到payment message或route不能证明funding exposure；具体余额、overdraft、信用额度和提款仍需合同/账户证据。该推论不是CPMI原句。',
  },
  {
    id: 18,
    authors: 'Basel Committee on Banking Supervision',
    year: '2026; published 1 January',
    accessedAt: '2026-09-17',
    title: 'Liquidity risk management and supervision',
    publication: 'Basel Consolidated Guidelines, LQY10',
    url: 'https://www.bis.org/committees/bcbs/basel-consolidated-guidelines/module/lqy/10',
    use: '核读LQY10.26–.35与.52–.57（cash-flow maturity）、.48–.50、.63–.70与.131–.132（transferability）、.3、.31、.34、.75–.77与.136–.139（marketability/funding value）。支持现金流期限、跨实体/币种转移限制、资产可变现性与融资价值需要分别验证。“Published 01 Jan 2026”是网页发布日期，不称为监管生效日。它不把本课G_pre或任何SYN公式变成监管比率，也不授权用账面抵押品直接抵减现金缺口。',
  },
];

export const lesson405ReadingList: LessonReading[] = [
  { title: '路线一：先把美元资金风险放进实体与期限', scope: 'CGFS 71 Executive Summary、§§2–4', reason: '用legal entity、currency、booking location、nationality与horizon替代“某国缺美元”的模糊说法，并理解集团资源为何未必能及时转移。', url: lesson405References[1].url, group: 'core' },
  { title: '路线二：画出美元工具拓扑', scope: 'CGFS 65 §2.3/Table 1与§4', reason: '比较deposit、CP、CD、repo、FX swap和bond在抵押、期限、报表位置及未来义务上的差异；工具名称相同不等于route可达。', url: lesson405References[0].url, group: 'core' },
  { title: '路线三：完整画FX swap的两期现金腿', scope: 'BIS 2022 feature与technical discussion', reason: '理解对冲可以缩小表内币种错配，却留下未来美元交付与滚续时钟；gross notional、净债务和现金缺口要分开。', url: lesson405References[2].url, group: 'models' },
  { title: '路线四：basis必须连同报价护照一起读', scope: 'BIS 2016 framework；Du–Tepper–Verdelhan working paper', reason: '从清洁CIP关系进入hedging demand和受约束套利，训练自己在缺少pair、方向、tenor、side与rate basis时主动输出null。', url: lesson405References[3].url, group: 'models', links: [{ label: 'NBER working paper', url: lesson405References[4].url }] },
  { title: '路线五：用2011历史案例学习可证伪机制', scope: 'Ivashina–Scharfstein–Stein Introduction、data/background、results', reason: '观察研究如何利用不同银行对美国MMF的事前依赖与币种内贷款变化检验供给机制，同时保留样本和版本边界。', url: lesson405References[6].url, group: 'evidence' },
  { title: '路线六：把2020写成多渠道反馈而不是单因故事', scope: 'FSB 2020 Executive Summary与propagation；CGFS 65 §6.1', reason: '区分cross-currency basis和Treasury cash–futures basis trade，并把赎回、margin、dealer capacity与资产出售放入同一动态系统。', url: lesson405References[7].url, group: 'systems', links: [{ label: 'CGFS 65', url: lesson405References[0].url }] },
  { title: '路线七：分别画swap line与FIMA', scope: 'Fed FAQs；NY Fed current operations/EPR', reason: '逐层标出Fed、外国央行、FIMA account holder与本地recipient，防止把官方设施写成私人机构可直接调用的总水管。', url: lesson405References[9].url, group: 'rules', links: [{ label: 'NY Fed current page', url: lesson405References[10].url }, { label: 'FIMA FAQ', url: lesson405References[11].url }, { label: 'NY Fed EPR', url: lesson405References[12].url }] },
  { title: '路线八：统计口径不能互换', scope: 'BIS IBS guidelines与GLI methodology', reason: '对比residence/unconsolidated与nationality/consolidated口径，并列出GLI估计成分和coverage gaps，避免把宏观面板当实体资金账。', url: lesson405References[13].url, group: 'evidence', links: [{ label: 'GLI methodology', url: lesson405References[14].url }] },
  { title: '路线九：correspondent支付路由不是融资余额', scope: 'CPMI 147 §2.1与Glossary', reason: '理解correspondent可提供多种服务，但payment message本身不说明余额方向、overdraft、credit line、提款和期限；证据推论必须说清楚。', url: lesson405References[16].url, group: 'rules' },
];

export const dollarFundingEvidenceGroups = [
  { key: 'entity-horizon', title: '实体、币种、期限与内部转移', supports: '具体法律实体的外币现金流、衍生品期限、集团/host约束和后备访问。', doesNotSupport: '不从国别或集团净额推出某分行周五可付款，也不把unknown转成0。', sourceIds: [2, 14, 18] as const },
  { key: 'network-tools', title: '工具拓扑与多层美元网络', supports: '银行、非银、MMF、dealer、repo、CP/CD、bond与最终用款人的连接和替代门。', doesNotSupport: '不把工具名称当可执行route，不把历史规模当当前逐实体余额。', sourceIds: [1, 7, 17] as const },
  { key: 'fx-cip', title: 'FX swap、CIP与basis', supports: '两期现金腿、未来美元义务、清洁CIP、hedge demand与资产负债表约束。', doesNotSupport: '不把gross notional当损失，不把basis符号当统一shortage或因果标签。', sourceIds: [3, 4, 5, 6] as const },
  { key: 'stress-feedback', title: '美元升值、margin、抵押与2020反馈', supports: '资产价值和现金腿分离、haircut/settlement、赎回、dealer capacity与被迫出售的反馈。', doesNotSupport: '不声称美元升值对所有主体同向，不把2020当下一次危机剧本。', sourceIds: [1, 8, 9, 18] as const },
  { key: 'official', title: 'Swap line、FIMA与本地onward', supports: '主权第一层、FIMA官方账户repo和独立本地操作的对手方、抵押与结算差异。', doesNotSupport: '不保证私人资格、获配、足额、实时用量或政策效果，也不声称三类穷尽全球官方路径。', sourceIds: [10, 11, 12, 13] as const },
  { key: 'measurement', title: 'LBS、CBS、GLI与多指标诊断', supports: '统计覆盖、residence/nationality口径和全球流动性需结合价格与数量。', doesNotSupport: '不把聚合统计当实体cash ledger、完整FX衍生品或固定综合报警器。', sourceIds: [14, 15, 16] as const },
] as const;

export const dollarFundingFailedSourceLedger = [
  { title: 'Ivashina–Scharfstein–Stein Harvard author PDF', request: 'https://scholar.harvard.edu/files/stein/files/ivashina-scharfstein-qje-2015.pdf', status: 'HTTP 403 on the recovery pass', resolution: '保留失败；正文只称已读Federal Reserve FEDS HTML工作论文，不暗示QJE publisher final或Harvard PDF已读。', sourceIds: [7] as const },
  { title: 'Du–Tepper–Verdelhan publisher final', request: 'https://onlinelibrary.wiley.com/doi/10.1111/jofi.12620', status: 'publisher record available; final full text not used', resolution: '实质证据来自已归档NBER Working Paper 23170；正文明确版本，不把工作论文页码归给Journal of Finance final。', sourceIds: [5] as const },
  { title: 'Basel legacy SRP/55 URL', request: 'https://www.bis.org/basel_framework/chapter/SRP/55.htm', status: 'legacy/stale route; not used as current source', resolution: '改用并归档当前官方Basel Consolidated Guidelines LQY10网页，同时保存其2008底层原则官方PDF；正文使用精确LQY10段落号，并将Published 01 Jan 2026只写作发布日期。', sourceIds: [18] as const },
] as const;
