import type { DollarFundingSourceId } from './dollarFundingReferences';

export type DollarFundingFormula = {
  kind: 'definition' | 'author-syn' | 'measurement-template';
  expression: string;
  variables: readonly { symbol: string; meaning: string }[];
  explanation: string;
  stopRule: string;
};

export type DollarFundingConcept = {
  id: string;
  label: string;
  title: string;
  question: string;
  intuition: string;
  actors: string;
  constraints: string;
  behavior: string;
  transmission: string;
  feedback: string;
  formula?: DollarFundingFormula;
  counterexample: string;
  evidenceBoundary: string;
  interfaces: { from: string; to: string };
  sourceIds: readonly DollarFundingSourceId[];
  sourceNote: string;
};

export const dollarFundingConcepts: readonly DollarFundingConcept[] = [
  {
    id: 'dollar-funding-mechanism-01',
    label: 'ENTITY / CURRENCY / HORIZON PASSPORT',
    title: '美元缺口属于具体法律实体、结算币种和日期窗口；集团“总体有钱”不能替代周五能否付款。',
    question: '为什么一个全球银行集团美元净资产为正，伦敦分行仍可能在本周五出现美元融资压力？',
    intuition: '把集团想成一栋有很多上锁房间的大楼。整栋楼拥有足够水，并不表示三楼在消防检查前能把地下室的水搬上来：法律实体、监管边界、内部额度、时区、支付账户和操作流程都可能把资源隔开。美元融资首先是“谁在何时必须交付多少美元”的问题，而不是抽象的全球美元总量问题。',
    actors: '法律实体承担合同，booking office登记头寸，集团司库尝试跨实体调拨，correspondent与支付系统完成结算，home/host监管者可能限制转移，最终收款方只关心约定日是否收到美元。National ownership与booking location都重要，但回答的问题不同：前者描述集团归属，后者更接近当地实体和支付时钟。',
    constraints: '只有同一法律实体、同一交付币种、同一窗口且属于可执行净额集合的现金腿才能相互抵消。集团合并报表会消除内部头寸，residence统计会保留当地实体，二者不可随意相加。若entity、currency、value date、direction或netting set缺失，正确输出是null或STOP，不是用国别平均数补齐。',
    behavior: '资金部门先建立passport，再决定可用现金、合同流入、合同流出和或有流出；随后才询问私人续作、抵押融资、内部转移或官方渠道。没有passport时，交易员可能看到“集团流动性充足”而继续持仓，但结算团队仍会因为某个账户余额不足而卖资产或借入隔夜美元。',
    transmission: '局部实体缺口会先改变最短期限的报价和数量，再传到资产出售、保证金、客户贷款与跨境内部资金。若多家机构同时在相同value date寻找美元，dealer和FX-swap中介的资产负债表占用上升，局部问题便可能转化为市场价格与access的共同收紧。',
    feedback: '资产出售压低抵押品价值，haircut或margin上升又扩大同一实体的现金需求；母行若抽回其他地区资金援助该实体，压力还会迁移。相反，及时且可执行的内部调拨可以切断反馈，但“历史上常援助”不是本次不可撤销承诺。',
    formula: {
      kind: 'measurement-template',
      expression: 'passport = (legal entity, settlement currency, as-of, horizon, value dates, netting set)',
      variables: [
        { symbol: 'legal entity', meaning: '承担合同与付款义务的独立法律主体，不以集团简称替代' },
        { symbol: 'horizon H', meaning: '从as-of之后到明确截止时刻的现金窗口' },
        { symbol: 'netting set', meaning: '法律上可执行且日期、币种和对手方条件相容的抵消集合' },
      ],
      explanation: '这是观察模板而非风险比率；它规定哪些现金腿可以进入同一问题。',
      stopRule: '实体、币种、方向、value date或netting基础任一缺失，就停止净额结论；unknown不能按零处理。',
    },
    counterexample: '纽约母行持有100美元现金、伦敦子行周五欠80美元，但转移需要host批准且最早下周一到账。集团净现金为+20并不改变伦敦实体周五的80美元交付缺口。',
    evidenceBoundary: 'CGFS 71和BIS统计指南支持entity/location/nationality/tenor的区分；它们不提供这个合成例子的金额，也不证明所有跨境调拨都会受阻。',
    interfaces: { from: '接收4.01居民—非居民账本与4.03货币服务对象；不把宏观流量当实体cash。', to: '把通过护照的实体与窗口交给4.05.2期限梯及4.06全球银行；passport不完整则数值分支STOP。' },
    sourceIds: [2, 14, 18],
    sourceNote: '来源2提供外币资金passport，来源14固定统计口径，来源18补充跨实体/币种转移限制；均不支持用聚合值代替个体。',
  },
  {
    id: 'dollar-funding-mechanism-02',
    label: 'BANK MATURITY LADDER / PRE-ACTION GAP',
    title: '银行美元资金风险是一条期限梯：稳定存款、可逃逸批发资金和到期融资不能压成一个负债总额。',
    question: '为什么拥有长期美元资产且账面净值为正的银行，仍可能在7日内被迫缩表？',
    intuition: '偿付能力像整年的收入，流动性像明天早上要付的账单。十年后收回的优质美元贷款不能自动支付明天到期的commercial paper；一笔看似可续作的repo也必须先把旧融资的还款腿写进流出，再把新交易作为另一条尚待准入与结算的路线。',
    actors: '企业和零售存款人、MMF与其他现金投资者、同业银行、repo对手、债券投资者、银行司库和贷款客户共同构成期限梯。每类资金在保险、抵押、信用敏感度、通知期、行为稳定性与市场准入上不同；资产端也有合同回款、可出售证券和不可迅速变现的贷款。',
    constraints: '存量不是现金流。窗口内必须分别登记期初可用现金、合同流入、合同流出、stress/contingent流出和最低现金缓冲；collateral市值或haircut后capacity只能作为potential metadata，不能在交易尚未成交时抵减缺口。旧融资到期与新rollover必须有不同transaction和cash-leg ID。',
    behavior: '当短端投资者缩短期限或拒绝续作，银行先提高报价、转向secured funding或FX swap，再尝试内部调拨、出售资产、收缩新贷款或使用符合条件的官方渠道。哪个动作先发生取决于价格、可借数量、抵押品、额度、结算速度与管理层限制，而不是工具名称。',
    transmission: '短期资金退出会从银行负债端进入资产端：贷款承诺可能被重新定价或不续作，企业削减投资与库存；若银行卖出证券补现金，价格影响和margin会传给持有相同资产的非银。期限梯因此把“融资市场”与“实体信用”连接起来。',
    feedback: '被迫缩表可能改善单家银行未来现金，但会降低市场深度、压低资产价格和收紧其他机构抵押能力；其他机构同时缩表时，个体理性变成系统性正反馈。若稳定存款、长债或官方安排确实在窗口内可达，反馈也可能被缓冲。',
    formula: {
      kind: 'author-syn',
      expression: 'N_pre = C₀ + Iᶜ_H − Oᶜ_H − Oˣ_H − Cmin_H;  G_pre = max(0, −N_pre)',
      variables: [
        { symbol: 'C₀', meaning: '该实体在as-of可立即使用的USD cash' },
        { symbol: 'Iᶜ_H / Oᶜ_H', meaning: '完整UTC value timestamp落在前瞻窗口(as-of, horizonEnd]内的美元合同流入/流出' },
        { symbol: 'Oˣ_H', meaning: '窗口内明确给定的stress、margin或contingent draw流出' },
        { symbol: 'Cmin_H', meaning: '合成设计明示的最低现金缓冲；未知则STOP' },
        { symbol: 'G_pre', meaning: '行动前合成现金缺口，不含sale、rollover、repo、FX swap、内部或官方路线' },
      ],
      explanation: '这是本课唯一SYN-2教学式，所有项均为USD cash；不是LCR、监管公式、违约概率或post-action余额。',
      stopRule: 'route输入、collateral capacity、unknown flow或post-action receipt混入时立即STOP；value timestamp没有明确UTC时区或窗口开闭边界不明时同样STOP。本课不输出G_post。',
    },
    counterexample: '合成实体有15美元haircut后抵押能力，但没有交易、承诺或窗口内value date；C₀=25、I=50、Oᶜ=120、Oˣ=20、Cmin=0时，G_pre仍为65而不是50。',
    evidenceBoundary: 'CGFS 65/71与Basel流动性原则支持现金流、资产可变现性和funding access分开；G_pre的变量和数值完全是作者SYN，不是官方指标。',
    interfaces: { from: '接收4.05.1通过护照的entity/currency/H，不读取其他实验。', to: '只把pre-action gap和期限桶交给4.05.4路线讨论；SYN-2本身不执行任何融资动作。' },
    sourceIds: [1, 2, 18],
    sourceNote: '来源约束期限化分析与现金/capacity分离；公式与K3=65只验证教学记账。',
  },
  {
    id: 'dollar-funding-mechanism-03',
    label: 'NBFI / CORPORATE CASH NEED',
    title: '非银与企业即使持有美元资产或已经套保，也可能因为赎回、保证金和承诺提款先缺现金。',
    question: '为什么“美元资产很多”或“汇率风险已对冲”不能证明机构没有美元融资风险？',
    intuition: '一套房子的价值足以覆盖一年支出，不代表今天能用房产支付保证金。基金可以持有高价值美元证券，却因赎回与variation margin需要立即交付现金；企业可以有未来美元出口收入，却在债券付息日之前没有足够到账。价值、最终偿付能力和今天的cash leg必须分栏。',
    actors: '养老金、保险、开放式基金、对冲基金、中央清算参与者、出口企业、跨国公司和银行授信提供者面临不同现金时钟。投资者赎回、CCP或双边对手的margin call、企业的commercial paper到期和信用额度提款，都会把压力带入美元需求。',
    constraints: 'Natural hedge要求收入币种、金额和日期与债务服务匹配；金融hedge要求instrument、方向、ratio、maturity、margin和rollover清楚。资产市值不能在缺少owner、encumbrance、settlement和price impact时变成现金。若这些字段未知，只能说影响unknown，不能假定0%或100%套保。',
    behavior: '非银可能先动用现金、卖最流动资产、降低hedge ratio或滚动FX swap；企业可能抽取银行承诺、提前换汇或削减资本开支。压力期这些动作会与银行自身防守重叠：基金赎回CP/CD，同时企业提款，银行负债减少而资产承诺增加。',
    transmission: '赎回和margin把资产价格变化转成即时美元流出；银行信用承诺又把企业的预防性现金需求转成银行资产扩张。若非银卖出Treasury或信用债，价格和haircut反馈会触及并未直接借美元的其他持有人。',
    feedback: '资产出售令波动和margin进一步上升，增加下一轮现金需求；企业提款可能让银行削减新贷款，反过来提高企业预防性现金偏好。若资产到期、出口收款或可执行credit line在窗口内到账，链条可以缓冲，但必须有日期与合同证据。',
    counterexample: '一个养老金100%对冲美元债券的终值汇率风险，却以一周FX swaps滚动两年资产；美元急升时它可能收到资产价值收益，同时因swap或衍生品保证金在今天流出美元。这不是“对冲失败”，而是价值风险与现金流时钟不同。',
    evidenceBoundary: 'CGFS 65/71、BIS 2022与FSB 2022支持NBFI/企业的期限、margin与hedge异质性；不提供任何特定机构的头寸、margin规则或违约结论。',
    interfaces: { from: '接收4.03资产服务与3.13主体特定金融条件，不复制其SYN数值。', to: '把价值—现金分离交给4.05.6、4.05.9与4.05.10，并向4.07全球金融周期输出异质主体门。' },
    sourceIds: [1, 2, 3, 9],
    sourceNote: '四个来源共同支持hedged不等于funded；任何主体方向仍要由其passport决定。',
  },
  {
    id: 'dollar-funding-mechanism-04',
    label: 'FUNDING TOOL TOPOLOGY / SUBSTITUTION GATES',
    title: 'CP、CD、repo、FX swap与长期债券不是一个价格不同的菜单；每条路线有不同的资产负债表、抵押和结算门。',
    question: '当commercial paper市场关闭时，为什么一家机构不能无条件“改借repo”或“改做FX swap”？',
    intuition: '融资工具像跨河的不同桥：一座要求门票，一座只让卡车通过，一座在对岸要求返程。看到桥存在，不等于你的车辆、时间和证件都合格。Repo需要合格且未占用的抵押品；FX swap需要另一币种现金、对手方额度与未来反向交付；长期债券需要市场窗口与发行准备。',
    actors: '现金投资者、MMF、银行、dealer、repo clearing/settlement体系、FX dealer、评级机构、债券承销商和内部风险委员会分别控制一部分route。借款人无法只根据headline price选择工具，因为quantity与access可能在价格出现之前先收缩。',
    constraints: '每条route至少要通过eligibility、capacity、counterparty、limit、collateral/non-USD cash、documentation与settlement timing。Secured不表示无风险或自动成交；off-balance-sheet不表示没有未来现金腿；spot FX是资产交换而不是自带未来返还的融资合同。',
    behavior: '主体会比较边际成本与可执行性，先使用已建文档和额度的渠道；压力加深时提高报价、缩短期限、质押优质资产或延长负债。若route只收到indicative quote或capacity estimate，专业账本仍把cash receipt记为null。',
    transmission: '某一渠道关闭会把需求推向其他渠道，抬高repo rate、basis或债券spread，并占用dealer资产负债表；替代需求还可能挤出原本使用该渠道的其他主体。工具间连接使局部市场故障扩散，但每条边必须通过自身门。',
    feedback: '替代融资增加抵押品占用与未来rollover，可能缓解今天却加重下一桶；若市场看到主体快速消耗优质抵押品，也可能收紧信用额度。反之，多样且真正可执行的资金来源能降低对单一短期渠道的依赖。',
    formula: {
      kind: 'measurement-template',
      expression: 'route feasible = eligibility ∧ capacity ∧ counterparty ∧ documentation ∧ settlement-in-H',
      variables: [
        { symbol: 'eligibility', meaning: '主体、工具、抵押品和法域均符合规则' },
        { symbol: 'capacity', meaning: '额度与资产约束下的上限，不是已收现金' },
        { symbol: 'settlement-in-H', meaning: '确定value date落入当前窗口且状态可执行' },
      ],
      explanation: '逻辑式强调所有门同时通过；任何一项false都使route不可用，unknown使结果null。',
      stopRule: '只有quoted price、未验证capacity或缺少value date时，不得产生receipt或post-action余额。',
    },
    counterexample: '一家银行有可交易Treasury，但已全部质押给CCP；repo市场报价正常也不能让同一抵押品再次融资。另一家有欧元现金却没有FX counterparty额度，FX swap同样不可执行。',
    evidenceBoundary: 'CGFS 65提供工具比较与网络；CGFS 71和Basel原则支持准入与可变现性门。来源不保证任一具体route可替代，也不提供本课合成router参数。',
    interfaces: { from: '接收4.05.2的pre-action问题，但不读取SYN-2状态或数值。', to: '把可执行route概念交给4.05.5–4.05.9；任何现金都要另建immutable cash leg。' },
    sourceIds: [1, 2, 18],
    sourceNote: '来源支持工具差异和路线门，不支持“有市场=有现金”。',
  },
  {
    id: 'dollar-funding-mechanism-05',
    label: 'ROLLOVER CLOCK / RESIDUAL MATURITY',
    title: '滚续风险取决于剩余期限和行为窗口：长期资产可以由每天重开的短期资金支持，直到某天无法重开。',
    question: '为什么一项原始期限十年的融资资产组合，仍可能在隔夜或一周窗口内出现危机？',
    intuition: '租约写十年，不代表每十年才付一次房租。长期资产的经济期限与资金的剩余期限是两只时钟；只要短期融资反复续作，今天看似稳定，但每个到期日都是一次重新取得对手方同意的事件。',
    actors: '银行以存款、CP/CD、repo、FX swaps和债券支持美元资产；非银也常以短期repo或FX swap支持较长期持仓。投资者决定是否续作与期限，dealer决定报价与额度，运营团队决定能否按时settle。',
    constraints: '必须用residual maturity而非original maturity，把O/N、7d、30d、90d分别入桶。预期续作不是合同流入，旧融资到期不能因“通常会roll”而删除。新rollover是新transaction，含新receipt、未来repayment与费用腿。行为稳定性可以作为情景，不可替代法定value date。',
    behavior: '压力早期常表现为期限缩短而非价格暴涨：投资者仍愿意借，却只借O/N；借款人因此增加每天重融资的频率。随后quantity与access恶化，主体提高现金缓冲、延长负债或减少资产。',
    transmission: '短期限把小概率拒绝放大成高频事件，也把不同市场的日历聚合到少数结算日。多个主体同时roll时，dealer capacity、collateral settlement与支付系统出现拥堵，价格和access收紧再传到信贷供给。',
    feedback: '期限缩短提高未来rollover需要，使投资者更关注主体每日流动性，进一步偏好更短期限；主体为防守而囤积现金又减少向他人提供资金。若长期稳定资金确实到位，负反馈可以切断这条链。',
    formula: {
      kind: 'definition',
      expression: 'rollover need_H = maturing obligations_H − executable contractual inflows_H',
      variables: [
        { symbol: 'maturing obligations_H', meaning: '窗口内所有本金、利息和相关结算腿' },
        { symbol: 'executable inflows_H', meaning: '已存在合同且能在H内到账的流入，不含预期新交易' },
      ],
      explanation: '该定义强调旧到期先完整出现；之后的融资选择属于另一route。',
      stopRule: '若只有rollover ratio而没有gross maturities、value dates或新旧transaction身份，禁止计算净需要。',
    },
    counterexample: '两家银行都借100美元：A为90-day CD且剩余89天，B为连续O/N repo且明早到期。原始名义相同，但7日资金风险完全不同；把二者都标“短期批发融资”会丢掉关键时钟。',
    evidenceBoundary: 'CGFS 65/71与BIS FX-swap研究支持期限错配和滚续；不提供个别机构未来续作概率或通用行为期限。',
    interfaces: { from: '接收4.05.2期限梯与4.05.4工具身份。', to: '把到期腿交给4.05.6 FX-swap与4.05.9 collateral route；向7.11流动性螺旋输出rollover clock。' },
    sourceIds: [1, 2, 3],
    sourceNote: '来源共同支持剩余期限与rollover；概率和阈值保持未校准。',
  },
  {
    id: 'dollar-funding-mechanism-06',
    label: 'FX SWAP / TWO-DATE CASH LEGS',
    title: 'FX swap把两次币种交换绑在一起：今天取得美元，会同时创造到期日返还美元的合同腿。',
    question: '为什么FX swap既能对冲或融资，又可能留下表外美元滚续需要？',
    intuition: '你今天用欧元换到美元，同时承诺未来按预定远期价格把交易反过来。第一腿解决今天的美元，第二腿把问题搬到到期日；若底层资产两年到期而swap只有一周，你必须重复打开这扇门。',
    actors: '美元资产持有人、出口商、银行、养老金和保险通过FX dealer交易；净额协议、collateral support、结算系统与内部额度决定现金腿如何表现。监管和统计系统若只看表内借款，可能看不到完整的未来美元交付。',
    constraints: '每笔交易必须写currency pair、spot quote direction、notional direction、spot/forward value date、forward rate、netting set、margin currency与roll schedule。Gross notional不是净负债或损失；market value可能很小而未来gross delivery很大。Spot leg和forward leg不能相互删除，除非法律和结算净额条件明确。',
    behavior: '投资者用短期swap降低长期美元资产的汇率风险或取得美元资金；basis扩大时可能降低hedge ratio、缩短/延长tenor、改用cash borrowing或卖资产。Dealer为净方向需求分配资产负债表和限额。',
    transmission: '未来美元腿在少数到期日集中，会把汇率套保需求转成美元rollover需求；若dealer收紧，forward points和basis变化，套保成本进入跨境资产配置。保证金和settlement还可把远期风险提前变成今天的cash demand。',
    feedback: '美元升值或波动上升可能提高对冲需求与margin，扩大dealer占用；basis和quote width上升又改变持仓与hedge ratio，进一步改变净需求。若自然美元收入匹配到期，或长期swap锁定同一horizon，反馈可能较弱。',
    formula: {
      kind: 'measurement-template',
      expression: 't: pay foreign / receive USD;  T: pay USD / receive foreign at F',
      variables: [
        { symbol: 't', meaning: 'spot leg的value date，不一定就是trade date' },
        { symbol: 'T', meaning: 'forward/reversal leg的明确到期日' },
        { symbol: 'F', meaning: '与S使用同一报价方向的forward rate' },
      ],
      explanation: '两条腿共同定义交易；“表外”是报告位置，不是没有义务。',
      stopRule: '方向、pair、两个value dates、notional或netting未知时，未来美元cash leg为null；不得从headline notional生成缺口。',
    },
    counterexample: '一笔明天到期的100美元swap与一笔两年后到期的100美元swap有相同notional，却对7日窗口含义相反。只按notional求和会把远期远离窗口的交易误写成明日短缺。',
    evidenceBoundary: 'BIS 2022与CGFS 71支持表外美元义务、gross/net和rollover边界；不提供本课任何实体级swap book或明日总量。',
    interfaces: { from: '接收4.05.3的hedge/funding分离与4.05.5期限时钟。', to: '把完整两期现金腿交给4.05.7 CIP账本和4.11 FX Hedging；SYN-4不读取SYN-2。' },
    sourceIds: [2, 3],
    sourceNote: '来源支持结构和测量盲区；direction与实体必须另行证明。',
  },
  {
    id: 'dollar-funding-mechanism-07',
    label: 'CIP / QUOTE PASSPORT BEFORE BASIS',
    title: 'Covered interest parity先是一条现金流复制关系；cross-currency basis只有连同报价护照才有方向含义。',
    question: '新闻说“basis为−40bp”时，我们究竟还缺哪些信息，才能讨论美元融资成本？',
    intuition: '同一条坡度若不知道地图朝向，就不能判断向东还是向西下坡。Basis的正负取决于货币对、spot/forward报价方向、哪条利率腿加点、借入哪种货币、tenor、bid/ask与抵押条件；单独一个数字没有稳定的“紧张”翻译。',
    actors: '现金借贷者、FX-swap用户、dealer、套利者、货币基金与跨境投资者比较直接美元融资和通过另一货币合成美元的成本。研究者选择利率基准、期限与报价侧，清算/抵押制度又影响可执行成本。',
    constraints: '清洁CIP要求两个策略起止现金流可比：同一value dates、计息基础、信用/抵押、bid/ask和可执行数量。现实basis可包含hedging demand、credit、liquidity、balance-sheet、regulatory、year-end与settlement楔子；偏离不等于无风险套利。',
    behavior: '当合成美元相对昂贵，借款者会比较cash borrowing、FX swap、repo和缩表；套利者只有在资本、杠杆、限额、margin和执行成本允许时才扩大头寸。Price可能缓慢调整，而quantity或tenor先变化。',
    transmission: 'basis改变跨境套保后的资产回报与银行边际资金成本，进入债券需求、贷款报价和货币配置；但它只是网络一个价格。若term quote消失，屏幕上的短端basis稳定也不能说明access正常。',
    feedback: '净hedging demand占用dealer资产负债表，扩大relative cost；basis扩大又令部分用户撤回、延期或减仓，形成供需反馈。季末报告成本等制度时钟可制造可预测波动，而不必等同系统性危机。',
    formula: {
      kind: 'definition',
      expression: 'F/S = (1 + r_f·τ)/(1 + r_USD·τ)  under one declared quote convention',
      variables: [
        { symbol: 'S / F', meaning: '相同“外币单位/美元”或“美元/外币”方向的spot/forward' },
        { symbol: 'r_f / r_USD', meaning: '同tenor、day-count、信用/抵押和side下的外币/美元利率' },
        { symbol: 'τ', meaning: '一致的计息年分数' },
      ],
      explanation: '这是无basis、单期、教学化复制关系；页面实验会明确使用的方向和加点腿。',
      stopRule: 'pair、quote direction、rate basis、tenor、borrow/lend side或bid/ask任一缺失，basis解释输出null。',
    },
    counterexample: '两个数据商都报“−40bp”，一个把basis加在非美元腿，另一个加在美元腿；若不读定义，两人可能对同一市场给出相反融资方向。即使定义相同，小额indicative quote也不能证明大额可执行。',
    evidenceBoundary: 'BIS 2016、Du et al.与CGFS 65 Annex B支持CIP、hedge demand和受约束套利；不提供唯一符号约定、实时shortage量或交易信号。',
    interfaces: { from: '接收4.05.6完整两期现金腿和3.20 FX报价方向。', to: '把quote passport与relative cost交给4.05.8中介约束及4.11；缺字段则保持null。' },
    sourceIds: [1, 4, 5],
    sourceNote: '来源支持basis机制与边界；任何−40bp例子只属SYN。',
  },
  {
    id: 'dollar-funding-mechanism-08',
    label: 'HEDGING DEMAND × DEALER BALANCE SHEET',
    title: 'Basis可以在平静期持续：净套保需求遇到有成本的中介资产负债表，套利不是无限且即时。',
    question: '如果CIP是一条无套利关系，为什么偏离不会立刻归零？',
    intuition: '两座水库水位不同，但连接水管有容量和通行费。套利者必须借一边、贷另一边、做FX swap、占用信用额度、资本、杠杆和结算资源；当管道昂贵或容量有限，价差可以在交易成本以上仍持续。',
    actors: '出口商、养老金、保险、资产管理人形成方向性套保需求；global bank与dealer把两边现金和衍生品连接起来；内部transfer pricing、leverage ratio、信用限额、监管报告日和风险预算决定边际capacity。',
    constraints: 'Dealer capacity不是一个公开可直接观察的常数；balance-sheet proxy与basis共同变化不自动证明单向因果。套利还面临信用、funding、margin、settlement、model与tail risk。Quantity/access可能收紧而价格因央行或少量成交看似稳定。',
    behavior: '中介会扩大bid–ask、减少tenor、降低quote size、提高内部balance-sheet charge或优先服务核心客户。终端用户则调整hedge ratio、延后交易、改变资产配置或改用其他币种。',
    transmission: '中介影子价格进入FX-swap basis、repo、跨境贷款与hedged asset return；若多种业务共享资本和限额，一处占用可挤出另一处做市或贷款。非美国市场于是通过中介约束而非单纯政策利率差受到影响。',
    feedback: '美元与波动变化可提高套保需求，中介成本上升扩大basis，basis又促使持有人卖出美元资产或缩减hedge；头寸减少可能最终缓和需求，也可能通过价格下跌和margin先放大压力。',
    counterexample: '季度末basis扩大可以与报表约束一致，却不必伴随银行即将违约或实体美元缺口暴增；反过来，某期限quote完全消失时，最近一笔basis可能没有明显变化，但access已经恶化。',
    evidenceBoundary: 'BIS 2016、Du et al.与Avdjiev et al.支持需求—中介约束框架和样本模式；论文proxy、系数和时点不等于逐dealer真实capacity或普适因果。',
    interfaces: { from: '接收4.05.7具护照的basis，不读取其缺字段数值。', to: '把balance-sheet shadow cost交给4.05.11多层链和4.07全球金融周期；不输出shortage=yes/no。' },
    sourceIds: [4, 5, 6],
    sourceNote: '三篇研究共同支持limits to arbitrage；均不授权单指标诊断。',
  },
  {
    id: 'dollar-funding-mechanism-09',
    label: 'COLLATERAL / HAIRCUT / MARGIN',
    title: '有Treasury不等于已有美元：所有权、未占用数量、资格、haircut、额度与结算共同决定潜在capacity。',
    question: '为什么一家持有高质量美元证券的机构仍会卖资产，而不是直接抵押借款？',
    intuition: '抵押品像可以申请信用额度的房产，不是银行账户里的现金。它可能属于另一个实体、已经质押、对当前对手不合格、要扣haircut、受额度限制，或无法在付款前完成settlement。只有交易状态和value date都通过，capacity才会变成具体cash leg。',
    actors: '资产所有者、custodian、repo dealer、CCP、央行设施、风险与运营团队共同决定collateral location和可用性。Market value、eligible value、unencumbered amount、allocated quantity、borrowing value和settled cash是六个不同对象。',
    constraints: '对同一lot，sale、private repo、official repo和secured onward的分配总和不能超过unencumbered marked value。Haircut后的数值是upper bound；缺owner、pool ID、eligibility、haircut、limit、currency conversion或settlement time时capacity为null。Capacity不能进入G_pre，也不能被称为realised receipt。',
    behavior: '主体先解押或搬运证券，再比较sale与repo；压力中对手可能提高haircut、减少eligible set或缩短tenor。若时间不够或capacity小于缺口，主体会出售更易成交资产、囤积现金或削减其他支付。',
    transmission: 'Haircut和margin上升提高美元现金需求，迫使卖出资产；价格下跌又减少borrowing value和净值，影响更多机构。优质资产成为共同抵押品时，局部结算或dealer约束可以跨市场传导。',
    feedback: '被迫出售压低市值，haircut提高进一步收缩capacity，形成典型流动性螺旋；官方或私人repo若真正可达可缓冲fire sale，但会创造未来repurchase与margin腿，而不是消除风险。',
    formula: {
      kind: 'author-syn',
      expression: 'capacity_a ≤ min(K_a, Σⱼ eligibleⱼ,a · (1−hⱼ,a) · qⱼ,a)',
      variables: [
        { symbol: 'qⱼ,a', meaning: '分配给route a的USD marked value，不是数量乘市值后的USD²' },
        { symbol: 'hⱼ,a', meaning: 'route和资产特定haircut，范围[0,1)' },
        { symbol: 'K_a', meaning: '已验证route cap；未知时不得假定无限' },
      ],
      explanation: '横线capacity只是上限。已结算realised receipt只归history/C0 attribution；只有不可撤销可执行且完整UTC value timestamp落在(as-of, horizonEnd]的未来receipt才进入当前X_H。',
      stopRule: '同一collateral重复分配、U>V、owner/pool/eligibility缺失或把capacity当cash时STOP。',
    },
    counterexample: '30美元Treasury分配给sale 8、private repo 12、FIMA repo 10，可计算27.90美元总capacity；在没有成交、binding amount和value date时，仍不能写“已收到27.90”。',
    evidenceBoundary: 'CGFS/FSB与Fed FIMA材料支持haircut、margin、抵押和fire-sale路径；capacity公式、30单位和haircut均为作者SYN，不是设施实时额度。',
    interfaces: { from: '接收4.03有效安全资产容量和4.04 repo/basis边界。', to: '把capacity与cash分离交给4.05.10压力反馈及4.05.14 FIMA；RECON-X只作作者静态测试。' },
    sourceIds: [1, 8, 12, 13, 18],
    sourceNote: '来源支持机制与官方资格；SYN分配不代表任何现实账户。',
  },
  {
    id: 'dollar-funding-mechanism-10',
    label: 'DOLLAR APPRECIATION / HETEROGENEOUS FEEDBACK',
    title: '美元升值不是统一冲击：未对冲债务人、本币收入企业、自然对冲出口商和套保投资者的现金路径不同。',
    question: '为什么美元升值既可能提高某主体偿债负担，也可能让另一主体在最终价值改善时遭遇即时margin压力？',
    intuition: '同一汇率变化像潮水：负债写在美元而收入是本币的主体水位上升；拥有美元收入的出口商可能受益；持有美元资产但做了衍生品套保的基金，最终本币价值更稳定，却可能今天先交保证金。方向来自资产负债表，不来自DXY本身。',
    actors: '未对冲企业、自然对冲出口商、银行、养老金、保险、开放式基金、dealer和CCP都有不同币种与期限。DXY只是一个货币篮子，未必对应主体实际currency pair、trade-weight或支付日。',
    constraints: '必须知道FX quote方向、债务/资产/收入币种、hedge ratio、maturity、margin currency与value dates。账面translation effect、经济净值、合同debt service和现金margin不可混为一个数字。缺信息时只输出unknown。',
    behavior: '未对冲债务人可能提前买美元、削减支出或寻求重组；出口商可用未来收入偿债；套保投资者可能卖流动资产补margin或降低hedge。银行会根据客户提款和抵押状态调整额度。',
    transmission: '主体买美元和卖本地资产可进一步推动汇率与本地利率；margin销售把外汇波动传到债券和股票；银行若同时面对外币负债和客户提款，会收缩跨境或本地贷款。',
    feedback: '汇率贬值削弱本币净值、提高债务服务和风险权重，融资收紧又压低资产与增长，可能继续推升美元需求。自然hedge、储备、资本管制或官方流动性可削弱链条，但作用依赖具体准入和时间。',
    formula: {
      kind: 'measurement-template',
      expression: 'home-currency debt service = USD payment × (home currency per USD)',
      variables: [
        { symbol: 'USD payment', meaning: '明确value date的美元本金、利息或margin现金腿' },
        { symbol: 'home currency per USD', meaning: '必须声明方向；上升表示美元相对本币升值' },
      ],
      explanation: '该式只描述未对冲的名义换算方向；自然收入、金融hedge、税和价格传导需另列。',
      stopRule: '若quote方向、付款日、hedge或自然收入未知，不输出净影响；DXY变化不能代替主体汇率。',
    },
    counterexample: '美元上涨10%：进口商的美元债本币负担上升，美元收入出口商可能形成自然缓冲；100%套保的美元债券基金终值汇率风险下降，却仍可能因衍生品市值变化产生即时cash margin。',
    evidenceBoundary: 'CGFS 65、FSB 2022与CGFS 71支持这些异质路径；不支持美元每次上涨都代表全球shortage或所有主体同向损失。',
    interfaces: { from: '接收3.20汇率护照、4.05.3价值/现金分离和4.05.9 margin。', to: '把主体特定反馈交给4.07、4.08与7.11；不从DXY单独生成状态标签。' },
    sourceIds: [1, 2, 9],
    sourceNote: '来源支持异质性和反馈；具体方向始终由主体passport决定。',
  },
  {
    id: 'dollar-funding-mechanism-11',
    label: 'MMF → CP/CD/REPO → DEALER/BANK → BORROWER',
    title: '最终储蓄者与最终用款人之间隔着多层市场；一层缩短期限或收回数量，会沿银行和dealer传到非美国信贷。',
    question: '为什么美国短期投资者改变MMF配置，可能影响境外银行给企业的美元贷款？',
    intuition: '企业并非直接向每位MMF投资者借款，但中间层把资金连接起来：MMF持有银行CP/CD或参与repo，dealer和银行再把美元提供给客户。第一层撤资后，中间层必须替代资金、卖资产或缩减最终贷款。',
    actors: 'MMF与cash investors决定可接受发行人、期限和数量；全球银行发行CP/CD、借repo并提供贷款；dealer在repo和证券市场中介；corporate与NBFI最终使用美元；correspondent可能提供支付、账户和其他服务。',
    constraints: '每条边都要分price、quantity、tenor与access。Correspondent payment route本身不证明credit exposure：只有账户余额方向、overdraft/credit合同、可用额度、提款和期限证据齐全，funding exposure才能从null转为数值。Payment message数量不能当贷款额。',
    behavior: '压力中MMF可缩短maturity、减少某类发行人或赎回资产；银行提高报价、转向repo/FX swap、动用内部资源并削减币种特定贷款；dealer降低quote size和库存承载。企业可能提前提款，进一步加大银行美元资产。',
    transmission: '资金链在负债端收紧，经过银行内部资金定价进入美元贷款的价格与数量；非美国企业即使没有直接接触美国MMF，也会看到credit line、贸易融资或银团贷款变化。',
    feedback: '企业预防性提款提高银行现金需求，银行防守性收缩又让企业更愿意囤积现金；MMF看到银行风险上升继续缩短期限。官方后备、稳定存款或长期债可以缓冲，但都需要独立route证据。',
    counterexample: '一笔美元支付通过纽约correspondent路由，不等于correspondent向外国银行提供了同额贷款；它可能只是用respondent既有存款完成结算。没有余额与信用合同，funding exposure必须保持null。',
    evidenceBoundary: 'CGFS 65和Ivashina et al.支持MMF—银行—贷款历史链；CPMI 147支持correspondent定义。Payment≠funding是基于定义的证据推论，不是CPMI原句或逐笔观测事实。',
    interfaces: { from: '接收4.05.4 route与4.05.8中介约束。', to: '把多层链交给4.06跨境银行与4.07全球周期；correspondent字段不完整时输出null。' },
    sourceIds: [1, 7, 17],
    sourceNote: '来源1/7支持资金与贷款链；来源17限定支付服务证据，不能由消息流猜信用。',
  },
  {
    id: 'dollar-funding-mechanism-12',
    label: 'INTRAGROUP TRANSFER / RING-FENCING',
    title: '内部资本市场是第一道缓冲，也是冲击迁移通道；资金能否跨实体移动取决于法律、监管、额度与运营时钟。',
    question: '为什么总部拥有美元缓冲，host实体仍可能削减当地贷款？',
    intuition: '家庭成员愿意借钱不等于银行转账已到账。跨国集团内部支持还要经过公司法、监管许可、内部限额、抵押或资本要求、时区和支付流程；压力时各实体同时争夺同一缓冲，总部还要决定先救谁。',
    actors: '母行、分行、子行、集团司库、home与host监管者、内部风险委员会和支付运营团队共同决定transfer。分行与子行法律地位不同，集团合并数据可能看不见资源实际位置。',
    constraints: '只有legal、regulatory、operational和time gates都通过，且amount与value date不可撤销，内部transfer才形成recipient cash leg。历史平均流量、管理层意向或未提款额度不能当作receipt。Transfer本身还可能创造另一实体的现金流出和监管后果。',
    behavior: '集团会把美元从盈余实体调往压力实体、改变内部价格、出售集中资产或缩减某地区业务；host可能ring-fence本地流动性，home也可能要求保留母行缓冲。',
    transmission: '援助某地可缓解当地贷款收缩，却把资金从其他地区抽走；若transfer受阻，host实体会更依赖本地市场或官方工具。集团网络因此既分散风险，也把冲击跨境重分配。',
    feedback: '子实体压力上升会提高总部对所有内部敞口的风险评估，进一步收紧内部限额；反之，预先建立的operational readiness与明确额度可降低不确定性。政策协调或ring-fencing变化会改变下一轮网络结构。',
    formula: {
      kind: 'measurement-template',
      expression: 'T_e,H is cash-eligible only if legal ∧ regulatory ∧ operational ∧ binding amount ∧ value-date-in-H',
      variables: [
        { symbol: 'T_e,H', meaning: '进入recipient实体窗口H的内部美元cash receipt' },
        { symbol: 'binding amount', meaning: '不可撤销或条件已满足的确定金额，不是意向' },
      ],
      explanation: '这是route gate，不是集团最优配置模型。Provider实体的对应outflow必须另记。',
      stopRule: '任一gate、source entity、amount或value date未知时T为null；不得依据集团总现金补0或满额。',
    },
    counterexample: '母行宣布“可提供最多50”，但host批准未完成且value date未知。50是capacity或意向，不是子行本周现金；若子行据此少借50，账本会产生虚假缺口闭合。',
    evidenceBoundary: 'CGFS 71与BIS统计口径支持内部资本市场、location/nationality和约束；不证明所有host会ring-fence或任何transfer将被拒绝。',
    interfaces: { from: '接收4.05.1实体passport和4.05.2 pre-action ladder。', to: '把可执行内部route交给4.06银行网络；不进入SYN-2，只在独立研究账本中登记。' },
    sourceIds: [2, 14],
    sourceNote: '来源支持条件性内部缓冲；金额、时间和批准均需个案证据。',
  },
  {
    id: 'dollar-funding-mechanism-13',
    label: 'SOVEREIGN SWAP LINE / TWO-LEVEL ROUTING',
    title: 'Federal Reserve swap line的第一层由FRBNY执行FOMC授权、与外国央行完成主权货币互换；私人机构只能经过本地第二层安排。',
    question: '为什么“Fed开了swap line”不等于一家外国银行可以直接向Fed借美元？',
    intuition: '这不是Fed向全球银行开放一个网页按钮，而是两级物流。第一层，Fed与外国央行交换美元和该央行货币，并约定反转；第二层，外国央行按本地规则决定哪些机构可参加、要交什么抵押、何时分配、价格和期限为何。',
    actors: 'FOMC授权安排，FRBNY执行swap operation；foreign central bank、其本地合格对手、支付与抵押系统以及本地监管者分别承担不同角色。第一层对Fed的合同义务人和对手信用风险承担者是foreign central bank；本地私人机构信用关系由外国央行/本地安排承担。',
    constraints: '必须把first leg与local onward分成不同transaction和cash legs。Layer A至少要有FRBNY与foreign-central-bank实体、对手准备度、Fed contractual obligor/counterparty risk bearer（必须是foreign central bank）、declared term、FCY-per-USD rate、USD interest/compensation，以及initial USD IN、initial FCY OUT、reversal USD OUT、reversal FCY IN四腿的不可变ID、正金额、完整UTC timestamp和独立settlement status。两条initial必须同刻，两条reversal必须同刻且等于initial+term；initial FCY必须等于USD principal×声明rate后按本SYN声明的两位FCY最小结算单位四舍五入。到期按同一汇率返还原数量FCY，即reversal FCY=initial FCY，而reversal USD=principal+USD interest/compensation；该compensation不增加FCY返还量。本课1–30个整数日历日只是SYN实验输入域，不是官方期限上限；官方材料支持next day至最长3个月。Layer A本身不创建Layer C，因而local onward risk在这层为N/A。在同一as-of下，realised腿只归历史/C0 attribution；committed_executable腿只在(as-of, horizonEnd]内进当前前瞻桶。Layer C还必须使用与upstream不同且不可变的transaction、cash-leg与source-event IDs，并保留自己的还款腿。Standing line存在不保证某机构符合本地规则或本次获得足额。',
    behavior: '外国央行可在条件允许时向本地机构开展美元操作，缓解市场access和期限压力；私人机构仍要权衡价格、抵押和声誉并提交bid。Fed与外国央行的交易不能直接登记为私人银行receipt。',
    transmission: '第一层扩大官方美元可用性，第二层若及时覆盖边际需求，可缓解FX-swap basis、期限缩短和资产出售；若资格、抵押或操作时间不匹配，压力仍会落在未覆盖实体。政策宣布也可能改变预期，但宣布与settled cash必须分开。',
    feedback: '市场功能改善可减少私人对手防守和fire sale；若参与污名、操作间隔或抵押限制使使用不足，价格信号可能继续紧张。外汇与银行压力又影响未来政策设计和standing arrangements。',
    formula: {
      kind: 'measurement-template',
      expression: 'Layer A = {USD IN, FCY OUT}_initial + {USD OUT, FCY IN}_reversal; Layer C = separate local transaction',
      variables: [
        { symbol: 'Layer A', meaning: '主权第一层，四条独立两币现金腿共用配对时点与声明term；不是Treasury repo' },
        { symbol: 'Layer C', meaning: '本地独立operation，资格、抵押、信用和结算由本地安排决定' },
      ],
      explanation: 'A可以成为C的upstream provenance，但A不自动创造C；每层均有自己的passport、每条cash leg都有自己的时间戳与状态。',
      stopRule: '缺layer、fixed entities、counterparty readiness、foreign-central-bank Fed obligor、term/rate/interest、四条currency legs、immutable IDs、per-leg status或UTC settlement schedule，以及任一金额为0、FCY两位结算量或配对关系冲突时，该层null/STOP。Quoted/unavailable必须在不读取隐藏交易腿的情况下提前返回。',
    },
    counterexample: 'Fed与某外国央行的100美元initial腿在2026-09-17T09:00Z已结算，当as-of也是该时刻时，它只能进入外国央行的历史/C0 attribution，不能再进当期X_H；若本地拍卖尚未公告，某银行更不能把这100登记为自己的可用现金。',
    evidenceBoundary: 'Fed FAQ与NY Fed current page支持FOMC授权、FRBNY执行、当前对手、next day至最长3个月期限、结构与信用关系；不提供私人获配、当期使用量、无限容量或未来政策保证。本课1–30日仅是实验输入域。',
    interfaces: { from: '接收4.02核心货币制度与4.05.12实体边界。', to: '把分层官方route交给4.06/4.07；SYN-6只比较access，不读取SYN-2缺口。' },
    sourceIds: [10, 11, 13],
    sourceNote: '当前机制以来源10–11为准，来源13提供历史物流图；旧名单/条款不覆盖当前页面。',
  },
  {
    id: 'dollar-funding-mechanism-14',
    label: 'FIMA REPO / OFFICIAL ACCOUNT-HOLDER ROUTE',
    title: 'FIMA是获批官方账户持有人以Treasury作抵押取得美元的repo后备；它与swap line的币种腿和私人准入逻辑不同。',
    question: '为什么FIMA与swap line都能提供官方美元，却不能合并成同一种“Fed全球水管”？',
    intuition: 'Swap line第一层用外国央行货币换美元；FIMA则由获批官方账户持有人把自己的Treasury暂时换成美元并约定回购。一个依赖主权货币互换关系，另一个依赖官方账户、Treasury collateral、haircut/margin、limit和repo settlement。',
    actors: 'Fed/SOMA与approved FIMA account holder是直接repo对手；custodian与settlement体系搬运Treasury和美元。账户持有人可把美元留作自身用途、干预FX市场，或按自己的规则建立另一笔本地操作；私人机构通常不是FIMA直接对手。',
    constraints: '当前FAQ允许overnight或seven-calendar-day term。Transaction passport必须无条件登记approved holder、holder-owned且唯一分配的eligible Treasury、initial USD/Treasury legs、repurchase amount/date、initial margin、limit、不可变的transaction/leg/source-event IDs，以及必需现金腿各自的UTC timestamp和status。O/N reverse timestamp必须精确等于initial+1 calendar day，七日必须精确等于initial+7 calendar days；输入域必须容纳D30 initial与D31/D37 reverse。Fed FAQ支持Treasury充分抵押与类discount-window margining，但不公开证明本课逐笔additional-margin schedule；因此该腿是可选author-SYN stress-ledger extension，只在选择complete时才要求amount/status/timestamp，并严格满足initialTimestamp < marginTimestamp < repurchaseTimestamp。Realised腿必须不晚as-of并只归历史/C0 attribution；committed_executable腿必须晚as-of，且只在(as-of, horizonEnd]内进当前X_H或O_H。Treasury holdings、eligibility或limit未知时capacity为null。Onward allocation不是设施自动步骤。',
    behavior: '符合条件的官方持有人可在不立即出售Treasury的情况下临时取得美元，比较repo后备价格与市场融资/资产出售；若随后支援本地系统，必须另建本地recipient、资格、抵押和repayment legs。',
    transmission: 'FIMA可改变官方储备管理者的sale-versus-repo选择，候选地减轻Treasury卖压并改善其美元access；但传到私人市场要经过资产持有人资格、持仓、额度、结算和可能的本地onward门。',
    feedback: '若后备降低fire sale，抵押品价格和市场深度可改善，反过来提高私人融资capacity；若设施定价、限额或操作准备不匹配，市场仍可能出售资产。使用量低既可表示压力小，也可表示价格或access门，不能单独识别效果。',
    formula: {
      kind: 'measurement-template',
      expression: 'Layer B X_H requires approved holder ∧ unique eligible holder-owned Treasury allocation ∧ complete per-leg UTC timestamps/statuses ∧ immutable IDs ∧ term/date match ∧ committed initial timestamp ∈ (as-of, horizonEnd]',
      variables: [
        { symbol: 'Layer B', meaning: 'Fed/SOMA与FIMA account holder之间的direct repo' },
        { symbol: 'X_H', meaning: '当前前瞻窗口内的binding scheduled USD receipt；已结算realised腿只进历史/C0 attribution，本期X_H=0' },
      ],
      explanation: 'Initial与repurchase cash legs必须分别保留状态与时间戳。本课可选author-SYN additional-margin cash leg若启用，也必须单独登记状态与时间戳；它在initial同刻/之前或repurchase同刻/之后都不属于该repo。若另有local onward，它是新的Layer C transaction。',
      stopRule: '把私人银行写成FIMA直接借款人、missing/duplicate/conflicting ID、抵押重复分配、receipt超过margin/limit capacity、O/N timestamp≠initial+1 calendar day、7-day timestamp≠initial+7 calendar days、启用的author-SYN additional-margin timestamp≤initial或≥repurchase、realised timestamp>as-of、committed timestamp≤as-of或将capacity当receipt时STOP/null。',
    },
    counterexample: '若as-of=2026-09-17T09:00Z，合成FIMA七日交易可在2026-09-19T09:00Z（D2）收到9.10、在2026-09-26T09:00Z（D9）偿还9.15；在7日窗口中只有committed initial receipt进X_H，repurchase进下一桶。同一输入域也必须允许D30 initial配D37 reverse；若把两者都限在D30内，就会拒绝合法的七日期限。',
    evidenceBoundary: 'Fed 2024结构FAQ支持资格、Treasury repo、O/N/7日、充分抵押与类discount-window margining；NY Fed EPR支持历史机制图。它们不支持私人直接准入、无条件onward、本课9.10/9.15合成金额，也不公开证明本课的逐笔additional-margin schedule；后者只是author-SYN扩展。',
    interfaces: { from: '接收4.03安全资产服务、4.05.9 collateral passport与4.05.13官方分层。', to: '把官方account-holder route及null gates交给4.07和储备管理研究；不进入SYN-2。' },
    sourceIds: [12, 13],
    sourceNote: '当前期限和资格以来源12为准；来源13的旧overnight-only表格仅作历史记录。',
  },
] as const;
