import type { LessonReading, LessonReference } from './types';

export const lesson408References = [
  {
    id: 1,
    authors: 'International Monetary Fund',
    year: '2025',
    accessedAt: '2026-09-22',
    title: 'Integrated Balance of Payments and International Investment Position Manual, Seventh Edition',
    publication: 'BPM7 white-cover / pre-edited version, March 2025',
    url: 'https://www.imf.org/-/media/files/data/statistics/bpm6/draft-bpm7-wcv.pdf',
    use: '支持按居民—非居民、资产／负债、直接投资／证券投资／其他投资／储备资产记录跨境交易，并把交易与汇率、价格和其他数量变化分开；不支持把金融账户净额称为现金总成交、把头寸差分全部称为资本流，或由统计分类直接推断因果与福利。',
  },
  {
    id: 2,
    authors: 'World Bank and International Monetary Fund',
    year: '2014–present',
    accessedAt: '2026-09-22',
    title: 'Quarterly External Debt Statistics: SDDS Methodology',
    publication: 'World Bank QEDS methodology and 2013 External Debt Statistics Guide implementation',
    url: 'https://www.worldbank.org/en/programs/debt-statistics/sdds-methodology',
    use: '支持把外债按部门、工具、原始期限、币种及未来一年本金和利息到期表拆分；不支持将年度IDS、季度QEDS、全部公共及私人债务视为覆盖完全相同，也不提供某主体真实可动用外汇或续借概率。',
  },
  {
    id: 3,
    authors: 'Kristin J. Forbes and Francis E. Warnock',
    year: '2012',
    accessedAt: '2026-09-22',
    title: 'Capital Flow Waves: Surges, Stops, Flight, and Retrenchment',
    publication: 'Journal of International Economics 88(2), 235–251; NBER Working Paper 17351',
    url: 'https://doi.org/10.3386/w17351',
    use: '支持分开非居民驱动的gross inflow与居民驱动的gross outflow，并将其极端增加／减少分别研究为surge、stop、flight、retrenchment；不支持用单期符号、净流量或本课AUTHOR-SYN直接贴事件标签，也不把相关因素自动解释为结构因果。',
  },
  {
    id: 4,
    authors: 'Fernando Broner, Tatiana Didier, Aitor Erce, and Sergio L. Schmukler',
    year: '2013',
    accessedAt: '2026-09-22',
    title: 'Gross Capital Flows: Dynamics and Crises',
    publication: 'Journal of Monetary Economics 60(1), 113–133',
    url: 'https://doi.org/10.1016/j.jmoneco.2012.12.004',
    use: '支持居民与非居民gross flows规模大、波动高且在危机中可能同时收缩，净额会遮蔽两侧行为；其跨国平均和危机分类不等于每个新兴经济体的固定反应，更不能从国家总量恢复具体法律实体、币种与结算链。',
  },
  {
    id: 5,
    authors: 'Marcel Fratzscher',
    year: '2012',
    accessedAt: '2026-09-22',
    title: 'Capital Flows, Push versus Pull Factors and the Global Financial Crisis',
    publication: 'Journal of International Economics 88(2), 341–356',
    url: 'https://doi.org/10.1016/j.jinteco.2012.05.003',
    use: '支持全球共同条件与本地制度／风险／基本面共同解释2005–10高频投资组合流，且权重随危机和恢复阶段改变；不支持把push/pull当互斥二元真因、把基金流覆盖成完整BOP资本流，或搬运固定系数到其他时期。',
  },
  {
    id: 6,
    authors: 'Robin Koepke',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'What Drives Capital Flows to Emerging Markets? A Survey of the Empirical Literature',
    publication: 'Journal of Economic Surveys 33(2), 516–540',
    url: 'https://doi.org/10.1111/joes.12273',
    use: '支持push/pull效应依流量工具、投资者和时期而异：portfolio、banking与FDI不能共用一个驱动模型；综述归纳不是新的统一因果识别，也不支持用“本地基本面好”保证短期投资组合流稳定。',
  },
  {
    id: 7,
    authors: 'Swarnali Ahmed Hannan',
    year: '2018',
    accessedAt: '2026-09-22',
    title: 'Revisiting the Determinants of Capital Flows to Emerging Markets: A Survey of the Evolving Literature',
    publication: 'IMF Working Paper 18/214',
    url: 'https://doi.org/10.5089/9781484378281.001',
    use: '支持新兴市场资本流结构、gross/net口径和push/pull研究随数据与全球环境演化，流量类别的决定因素不同；工作论文综述不认证任何国家当前风险、单一最优模型或政策效果。',
  },
  {
    id: 8,
    authors: 'Eugenio M. Cerutti, Stijn Claessens, and Damien Puy',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Push Factors and Capital Flows to Emerging Markets: Why Knowing Your Lender Matters More Than Fundamentals',
    publication: 'Journal of International Economics 119, 133–149',
    url: 'https://doi.org/10.1016/j.jinteco.2019.04.006',
    use: '支持全球共同波动集中在银行、投资组合债券与股票流，且共同基金依赖、市场流动性和基准纳入与跨国敏感度相关；不支持基本面永远无关、投资者构成是随机分配，或把样本相关直接写成政策保护／伤害因果。',
  },
  {
    id: 9,
    authors: 'Gaston Gelos, Pietro Patelli, and Ilhyock Shim',
    year: '2024',
    accessedAt: '2026-09-22',
    title: 'The US Dollar and Capital Flows to EMEs',
    publication: 'BIS Quarterly Review, September 2024',
    url: 'https://www.bis.org/publications/qr-202409/us-dollar-and-capital-flows-emes',
    use: '支持外部融资由外币银行贷款向本币债券与股票迁移、美元与不同类型EME流量的样本关系及其时变性，并明确区分BOP portfolio flows与基金申赎流；不支持把美元指数当外生冲击、把基金数据库当全部跨境持有者，或将样本关系变成固定预测规则。',
  },
  {
    id: 10,
    authors: 'Committee on the Global Financial System',
    year: '2021',
    accessedAt: '2026-09-22',
    title: 'Changing Patterns of Capital Flows',
    publication: 'CGFS Papers No 66',
    url: 'https://www.bis.org/publications/cgfs-paper-66-changing-patterns-capital-flows',
    use: '支持用push、pull和pipes三层分析资本流的收益、风险、极端波动及金融中介结构，并记录GFC后与疫情初期结构变化；委员会报告不是因果系数表，也不支持把资本开放、储备或任何工具视为跨国统一处方。',
  },
  {
    id: 11,
    authors: 'Nicolas E. Magud, Carmen M. Reinhart, and Esteban R. Vesperoni',
    year: '2012',
    accessedAt: '2026-09-22',
    title: 'Capital Inflows, Exchange Rate Flexibility, and Credit Booms',
    publication: 'IMF Working Paper 12/41',
    url: 'https://www.imf.org/external/pubs/ft/wp/2012/wp1241.pdf',
    use: '支持在其新兴市场样本中，资本流入繁荣、汇率制度与国内信用增长及外币信贷构成存在条件性关系；不支持资本流入必然创造贷款、汇率弹性是随机处理，或由跨国平均推出任一银行的信贷供给。',
  },
  {
    id: 12,
    authors: 'Deniz Igan and Zhibo Tan',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'Capital Inflows, Credit Growth, and Financial Systems',
    publication: 'IMF Working Paper 15/193',
    url: 'https://www.imf.org/external/pubs/ft/wp/2015/wp15193.pdf',
    use: '支持资本流类别与公司信用增长的关系随金融体系结构而异，并讨论抵押品需求和银行供给两条候选通道；面板相关和异质回归不识别每笔流入的用途，也不支持把FDI、portfolio和other investment合并成同一信贷冲击。',
  },
  {
    id: 13,
    authors: 'Carlos Cantú, Catherine Casanova, Rodrigo Alfaro, Fernando Chertman, Gerald Cisneros, Toni dos Santos, Roberto Lobato, Calixto López, Facundo Luna, David Moreno, Miguel Sarmiento, and Rafael Nivin',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'How Capital Inflows Translate into New Bank Lending: Tracing the Mechanism in Latin America',
    publication: 'BIS Working Papers No 1051',
    url: 'https://www.bis.org/publications/working-paper-1051-how-capital-inflows-translate-new-bank-lending-tracing-mechanism-latin-america',
    use: '支持用五国信贷登记数据比较不同银行资产负债表与借款人风险下的贷款数量和价格反应；结果具有国家、银行、借款人和设计边界，不支持把弱银行等同违规银行、把meta结果当全球参数，或由资本流量单独识别贷款需求与供给。',
  },
  {
    id: 14,
    authors: 'Stefan Avdjiev, Michael Chui, and Hyun Song Shin',
    year: '2014',
    accessedAt: '2026-09-22',
    title: 'Non-financial Corporations from Emerging Market Economies and Capital Flows',
    publication: 'BIS Quarterly Review, December 2014, 67–77',
    url: 'https://www.bis.org/publications/non-financial-corporations-emerging-market-economies-and-capital-flows',
    use: '支持境外附属公司发债所得可经集团贷款、对非关联方信贷或跨境银行存款进入本地，使公司成为“替代中介”的候选机制；不支持从发行公告推断资金已回流、由居住地统计恢复集团全部风险，或把所有公司外债视为实体投资。',
  },
  {
    id: 15,
    authors: 'Michael Chui, Ingo Fender, and Vladyslav Sushko',
    year: '2014',
    accessedAt: '2026-09-22',
    title: 'Risks Related to EME Corporate Balance Sheets: The Role of Leverage and Currency Mismatch',
    publication: 'BIS Quarterly Review, September 2014, 35–47',
    url: 'https://www.bis.org/publications/risks-related-eme-corporate-balance-sheets-role-leverage-and-currency-mismatch',
    use: '支持把企业杠杆、外币负债、收入币种、对冲、滚续与本地银行反馈逐项检查；不支持把外币债本身等同未对冲敞口、将出口商与本地收入企业视为同向，或由聚合资本率排除分布尾部。',
  },
  {
    id: 16,
    authors: 'Boris Hofmann, Nikhil Patel, and Steve Pak Yeung Wu',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'Original Sin Redux: A Model-based Evaluation',
    publication: 'BIS Working Papers No 1004',
    url: 'https://www.bis.org/publications/working-paper-1004-original-sin-redux-model-based-evaluation',
    use: '支持本币外债降低借款人外币错配但可能把货币风险迁移到受约束的外国投资者，全球金融冲击仍可通过本币债券传导；模型校准不证明每个国家同幅反应，也不意味着本币债与外币债风险等价。',
  },
  {
    id: 17,
    authors: 'Carol Bertaut, Valentina Bruno, and Hyun Song Shin',
    year: '2023',
    accessedAt: '2026-09-22',
    title: 'Original Sin Redux: Role of Duration Risk',
    publication: 'BIS Working Papers No 1109',
    url: 'https://www.bis.org/publications/working-paper-1109-original-sin-redux-role-duration-risk',
    use: '支持较长期本币债减轻借款人rollover risk，却提高外国持有人duration与汇率联合损失、并可能放大基金流动；不支持“期限越长越脆弱”的单调国家结论，期限对借款人和投资者的风险迁移必须分栏。',
  },
  {
    id: 18,
    authors: 'Claudio Raddatz, Sergio L. Schmukler, and Tomás Williams',
    year: '2017',
    accessedAt: '2026-09-22',
    title: 'International Asset Allocations and Capital Flows: The Benchmark Effect',
    publication: 'Journal of International Economics 108, 413–430',
    url: 'https://doi.org/10.1016/j.jinteco.2017.06.007',
    use: '支持全球股票与债券基准变动影响主动和被动基金配置、资本流、价格与汇率，公告与实施时点需分开；不支持把全部BOP portfolio flows归因于基准、把指数纳入当随机处理无条件成立，或由基金样本推出全部投资者。',
  },
  {
    id: 19,
    authors: 'Jimmy Shek, Ilhyock Shim, and Hyun Song Shin',
    year: '2018',
    accessedAt: '2026-09-22',
    title: 'Investor Redemptions and Fund Manager Sales of Emerging Market Bonds: How Are They Related?',
    publication: 'Review of Finance 22(1), 207–241',
    url: 'https://doi.org/10.1093/rof/rfx050',
    use: '支持把最终投资者申赎、基金经理主动交易与估值变化拆分，并显示其样本内经理销售可强化赎回销售；不支持固定放大系数、所有基金都顺周期，或将基金持仓变化直接等同BOP交易。',
  },
  {
    id: 20,
    authors: 'Peter Hördahl and Giorgio Valente',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'Emerging Market Bond Flows and Exchange Rate Returns',
    publication: 'BIS Working Papers No 1042',
    url: 'https://www.bis.org/publications/working-paper-1042-emerging-market-bond-flows-and-exchange-rate-returns',
    use: '支持其EME面板中债券流与后续汇率回报的资产定价关系，以及流量、汇率和金融条件可能形成反馈；不支持预测每次贬值、确定因果方向，或把特定基金／债券流代表完整资本账户。',
  },
  {
    id: 21,
    authors: 'Guillermo A. Calvo',
    year: '1998',
    accessedAt: '2026-09-22',
    title: 'Capital Flows and Capital-market Crises: The Simple Economics of Sudden Stops',
    publication: 'Journal of Applied Economics 1(1), 35–54',
    url: 'https://doi.org/10.1080/15140326.1998.12040516',
    use: '支持国际信用骤停如何迫使吸收和相对价格调整的经典机制，以及期限／股权结构可能改变脆弱性；理论机制不提供通用事件阈值，不等于所有gross-flow stop都形成货币、银行或主权危机。',
  },
  {
    id: 22,
    authors: 'International Monetary Fund',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'Review of the Institutional View on the Liberalization and Management of Capital Flows',
    publication: 'IMF Policy Paper 2022/008',
    url: 'https://doi.org/10.5089/9798400204593.007',
    use: '支持资本流可带来收益也可能放大脆弱性，surge识别应结合多种方法、部门和吸收能力，CFM／CFM-MPM只在条件下讨论；不支持把流入一概有害、把措施替代必要宏观调整，或从教材机制推出当前法域建议。',
  },
  {
    id: 23,
    authors: 'International Monetary Fund',
    year: '2023',
    accessedAt: '2026-09-22',
    title: 'Integrated Policy Framework—Principles for the Use of Foreign Exchange Intervention',
    publication: 'IMF Policy Paper 2023/061',
    url: 'https://www.elibrary.imf.org/view/journals/007/2023/061/article-A001-en.xml',
    use: '支持FX intervention应放入货币、财政、宏观审慎与资本流工具的整体反应，并显式考虑储备有限、可信度、错配和多边外溢；不支持把储备总额当无限缓冲、每次贬值都应干预，或由机制课给出福利最优组合。',
  },
  {
    id: 24,
    authors: 'International Monetary Fund',
    year: '2016',
    accessedAt: '2026-09-22',
    title: 'Guidance Note on the Assessment of Reserve Adequacy and Related Considerations',
    publication: 'IMF Policy Paper, June 2016',
    url: 'https://www.imf.org/external/np/pp/eng/2016/060316.pdf',
    use: '支持储备充足评估需结合出口收入、广义货币、短期债务和其他负债等潜在外汇流失来源，而非只看一个储备／进口月数；指标是风险评估输入，不证明储备可无成本动用、主体现金缺口已覆盖或政策最优。',
  },
  {
    id: 25,
    authors: 'Andrés Fernández and Alejandro Vicondoa',
    year: '2026',
    accessedAt: '2026-09-22',
    title: 'Capital Flows to Emerging Markets: Disentangling Quantities from Prices',
    publication: 'IMF Working Paper 26/60',
    url: 'https://doi.org/10.5089/9798229043540.001',
    use: '支持在其模型与样本中，融资价差具有很强的共同成分、主要由共同信用供给冲击解释，而资本流数量大多是国别特质波动、特质需求与供给冲击贡献相近；不支持把价和量互作代理、把net-flow proxy视为完整gross flow，也不支持把依赖动态因子模型与符号／零限制的2026工作论文结果当最终共识、实时预测器或国家固定参数。',
  },
  {
    id: 26,
    authors: 'Bank for International Settlements, Monetary and Economic Department',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Reporting Guidelines for the BIS International Banking Statistics',
    publication: 'Bank for International Settlements, July 2019, 62 pp.',
    url: 'https://www.bis.org/publications/reporting-guidelines-bis-international-banking-statistics',
    use: '支持LBS按银行所在地／居住地、非合并并保留跨境集团内头寸，以及CBS按母行国籍全球合并并消除集团内头寸等schema定义，也支持币种、部门、工具、期限与调整变化字段；不支持把国家聚合存量或adjusted change直接当新增贷款、逐笔交易、贷款供给shock或单体现金路线，也不支持把LBS与CBS机械相加。',
  },
  {
    id: 27,
    authors: 'Bank for International Settlements',
    year: '2026',
    accessedAt: '2026-09-22',
    title: 'BIS Global Liquidity Indicators: Methodology',
    publication: 'Bank for International Settlements, January 2026 methodology vintage',
    url: 'https://www.bis.org/statistics/gli/gli_methodology.pdf',
    use: '支持GLI按借款人居住地、部门、币种和银行贷款／国际债务证券渠道描述对非银行借款人的外币信用，并要求保存估算、调整、修订和方法vintage；不支持把GLI称为全部资本流、市场流动性、基金申赎、未对冲净敞口或外生全球金融周期shock。',
  },
  {
    id: 28,
    authors: 'International Monetary Fund, Statistics Department',
    year: '2017',
    accessedAt: '2026-09-22',
    title: 'Coordinated Portfolio Investment Survey Guide, Third Edition',
    publication: 'International Monetary Fund, title-page year 2017; ©2018 and electronic publication 2018',
    url: 'https://data.imf.org/-/media/iData/External-Storage/Documents/390C683A8FA24B58B7EBBBB33B82AD3B/en/CPIS-Guide-Third-Edition.pdf',
    use: '支持CPIS核心为居民持有非居民发行证券的跨境资产头寸，按发行人居住经济体及证券股权／基金份额、长短期债务证券等字段编制，并要求记录持有人、币种、覆盖、保密与vintage；不支持从头寸差恢复交易、估值、基金赎回、最终投资者、资金用途或实时portfolio flow。',
  },
  {
    id: 29,
    authors: 'Rita Mesias and International Monetary Fund',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'The Coordinated Direct Investment Survey Guide 2015',
    publication: 'International Monetary Fund, Manuals & Guides, 8 October 2015',
    url: 'https://www.imf.org/en/publications/manuals-guides/issues/2016/12/31/the-coordinated-direct-investment-survey-guide-2015-42945',
    use: '支持CDIS为按直接投资关系与即时对手经济体编制的年末头寸统计，区分股权／基金份额、债务工具、资产／负债、反向投资与关联企业关系；不支持把FDI头寸直接解释为当期交易、greenfield投资、最终控制来源、稳定资金、国内资本形成或因果效果。',
  },
] as const satisfies readonly LessonReference[];

export type EmCapitalFlowSourceId = (typeof lesson408References)[number]['id'];

export const emCapitalFlowEvidenceGroups = [
  { key: 'measurement', title: '对象与口径：交易、头寸、gross legs与净额', supports: 'BPM7与gross-flow文献允许把谁在何时买卖何种跨境债权，与汇率／价格重估及另一侧居民行为分开；BIS与IMF方法指南进一步固定银行、外币信用、证券和直接投资头寸的统计镜头。', doesNotSupport: '国家净额或任何一套头寸统计都不能恢复成交总量、主体现金、期限表、最终风险承担或危机标签。', sourceIds: [1, 2, 3, 4, 26, 27, 28, 29] as const },
  { key: 'drivers', title: '来源：push、pull与pipes交互而非二选一', supports: '全球条件、本地回报／风险、投资者类型和市场结构共同决定不同类别流量，权重随时期变化；前沿模型还显示融资价差共同性强而数量主要是特质波动。', doesNotSupport: '任一VIX、美元、利差、基本面指标或价量共同因子都不能单独命名结构冲击。', sourceIds: [5, 6, 7, 8, 9, 10, 25] as const },
  { key: 'composition', title: '合同结构：股权、债券、银行、直接投资的退出与风险不同', supports: '工具、投资者、币种和期限结构改变流入怎样进入银行、企业、政府及二级市场。', doesNotSupport: 'FDI永远稳定、债务永远有害、本币债没有外部风险，或portfolio必然用于二级市场。', sourceIds: [1, 6, 9, 10, 14] as const },
  { key: 'bank-credit', title: '国内入口：外部融资不自动变成新增信贷', supports: '银行资产负债表、借款人风险、资金去向和本地金融结构决定贷款价格与数量反应。', doesNotSupport: '一单位资本流入对应一单位贷款、相关增长必为供给，或跨国平均适用于每家银行。', sourceIds: [11, 12, 13, 14] as const },
  { key: 'currency-maturity', title: '币种与期限：偿付能力和流动性必须分栏', supports: '外币错配、自然／金融对冲、到期墙、rollover access和本币债持有人风险迁移共同塑造脆弱性。', doesNotSupport: '外币债等于未对冲净敞口、本币债等于无外部风险，或长期债只带来稳定。', sourceIds: [2, 15, 16, 17, 24] as const },
  { key: 'funds-benchmarks', title: '资产管理：基准、申赎与市场深度形成共同交易', supports: '基准权重、最终投资者申赎和基金经理交易能改变国别配置并与价格／汇率反馈。', doesNotSupport: '基金流等于BOP portfolio flow、主动基金不受基准影响，或所有本地投资者都被动承接。', sourceIds: [8, 18, 19, 20] as const },
  { key: 'waves-feedback', title: '骤停与反馈：stop、flight、价格调整和危机不是同义词', supports: 'gross两侧可同时收缩，外部融资骤停可经汇率、资产价格、抵押和信用反馈进入实体经济。', doesNotSupport: '单季负值就是sudden stop、stop必然危机，或相关先后足以识别传播方向。', sourceIds: [3, 4, 19, 20, 21] as const },
  { key: 'buffers-policy', title: '缓冲与政策接口：容量是多维、有限且内生的', supports: '本地投资者基础、外汇市场深度、储备、宏观审慎与资本流管理会改变传导菜单。', doesNotSupport: '一个储备比率或制度标签给出韧性排名，或4.08能够提前解决4.09的政策自主与福利问题。', sourceIds: [10, 22, 23, 24] as const },
] as const;

export const lesson408ReadingList: readonly LessonReading[] = [
  { title: 'Forbes & Warnock — Capital Flow Waves', scope: 'gross inflow/outflow及surge/stop/flight/retrenchment', reason: '先用四象限替代“热钱进出”一句话，并核对论文对阈值、趋势和因果的保留。', url: lesson408References[2].url, group: 'core', guide: '最短核心 40–55 分钟：定义与Figure 1 → 方法 → 主结果 → 结论；写下每种事件由谁的gross leg定义。' },
  { title: 'CGFS — Changing Patterns of Capital Flows', scope: 'push、pull、pipes、收益、风险与政策全景', reason: '建立全课总地图，再把银行、基金、企业和市场结构分别接回具体管道。', url: lesson408References[9].url, group: 'core', guide: '最短核心 60–80 分钟：Executive summary → Chapters 1–3 → policy表；不把委员会总结当单一因果研究。' },
  { title: 'BPM7 + World Bank QEDS', scope: '交易／存量／重估与币种／期限数据字典', reason: '把流量新闻还原为居民、工具、方向和时钟，并知道真实到期墙需要哪些字段。', url: lesson408References[0].url, group: 'rules', guide: '规则路线：BPM7综合框架与金融账户章节；配读QEDS的sector、maturity、currency及debt-service tables。', links: [{ label: 'QEDS方法', url: lesson408References[1].url }] },
  { title: 'Cerutti, Claessens & Puy — Knowing Your Lender', scope: '流量类型、投资者基础与全球敏感度', reason: '理解“基本面影响流量水平”和“投资者结构影响全球beta”不是同一命题。', url: lesson408References[7].url, group: 'evidence', guide: '证据路线 45–70 分钟：数据分类 → factor方法 → market structure交互 → robustness与结论。' },
  { title: 'Gelos, Patelli & Shim — US Dollar and Capital Flows to EMEs', scope: '外部融资结构、美元与时变敏感度', reason: '把外币银行贷款、本币债券、股票和基金流拆开，并辨BOP交易与基金申赎。', url: lesson408References[8].url, group: 'evidence', guide: '先读Graph 1–2的数据构造，再读drivers和time-varying结果；不要把最新样本关系外推成规则。' },
  { title: 'Cantú et al. — Capital Inflows into Bank Lending', scope: '五国贷款登记与银行／借款人异质性', reason: '从国家资本流走到银行—企业价格和数量，同时看到需求控制与跨国可比性的限制。', url: lesson408References[12].url, group: 'evidence', guide: '读研究设计、各国数据、meta结果与限制；分别记录贷款价格、数量、银行资本和借款人风险。' },
  { title: 'Avdjiev, Chui & Shin；配读 Chui, Fender & Sushko', scope: '境外企业发债、回流路线、杠杆与币种错配', reason: '理解离岸发债公告为何不能直接等于国内投资，也不能被居住地统计完全捕捉。', url: lesson408References[13].url, group: 'systems', guide: '先画境外附属—总部—银行三条资金路线，再配读企业收入币种、hedge与rollover反馈。', links: [{ label: '配读 · EME corporate balance sheets', url: lesson408References[14].url }] },
  { title: 'Hofmann, Patel & Wu；配读 Bertaut, Bruno & Shin', scope: 'original sin redux、币种风险迁移与duration', reason: '比较借款人外币错配减少的收益，与外国持有人汇率／久期损失造成的新传导。', url: lesson408References[15].url, group: 'models', guide: '模型路线 60–90 分钟：基准模型 → 外币／本币债比较 → 政策实验；再读duration证据。', links: [{ label: '配读 · Duration risk', url: lesson408References[16].url }] },
  { title: 'Raddatz, Schmukler & Williams；配读 Shek, Shim & Shin', scope: 'benchmark effect、redemption与经理销售', reason: '把指数权重、最终投资者现金流、经理主动交易和估值四个对象分开。', url: lesson408References[17].url, group: 'models', guide: '先读benchmark事件与配置结果，再读基金持仓分解；核对两篇样本都不等于全部BOP流。', links: [{ label: '配读 · Redemptions and sales', url: lesson408References[18].url }] },
  { title: 'Calvo — Simple Economics of Sudden Stops', scope: '外部融资骤停与吸收／相对价格调整', reason: '读懂经典约束如何把融资access变成实体调整，同时保留现代gross-flow定义与事件标签差异。', url: lesson408References[20].url, group: 'models', guide: '30–45 分钟：机制、融资结构、政策讨论；另与Forbes–Warnock的gross事件定义对照。' },
  { title: 'IMF Institutional View + IPF FXI Principles', scope: '吸收能力、CFM/MPM、FXI与多工具边界', reason: '把政策写成状态依赖菜单，而不是“开放或管制”“浮动或干预”二元口号。', url: lesson408References[21].url, group: 'systems', guide: '先读IV的surge与stock vulnerability框架，再读FXI的frictions、reserve trade-off和multilateral effects。', links: [{ label: '配读 · FXI principles', url: lesson408References[22].url }] },
  { title: 'Fernández & Vicondoa — Quantities versus Prices', scope: '融资价差的强共同成分与资本流数量的特质供需分解', reason: '作为前沿深化，训练“价和量的共同性本身可能不同”：该样本中价差共同性强、数量主要是国别特质波动；保留2026工作论文与识别限制。', url: lesson408References[24].url, group: 'evidence', guide: '前沿路线 60–90 分钟：net-flow proxy与spread measurement → common/idiosyncratic variance → sign/zero restrictions → robustness → model mapping。' },
] as const;
