import type {LessonReference,LessonReading} from './types';
export const lesson320References:LessonReference[]=[
 {id:1,authors:'Claudio Borio, Robert McCauley, Patrick McGuire and Vladyslav Sushko',year:'2016',accessedAt:'2026-09-15',title:'Covered interest parity lost: understanding the cross-currency basis',publication:'BIS Quarterly Review, September2016,45–64；四作者原季度文章，非五作者2018修订WP590',url:'https://www.bis.org/publications/covered-interest-parity-lost-understanding-cross-currency-basis_1.pdf',use:'作者实际读本次取得20页全部文字，并看原PDF4–5的BoxA报价与公式；图表和回归未逐图复现、所引论文未逐篇读。支持同期限covered现金流基准、套保需求与中介约束下的条件性偏离；不认证当前基差、可成交套利或全部现货决定因素。原文历史Libor不是当前基准操作指令。本课套保超额按外币投资本币回报减本币回报自定义，不冒充原文另一币种腿的basis符号。'},
 {id:2,authors:'Charles Engel and Kenneth D. West',year:'2005',accessedAt:'2026-09-15',title:'Exchange Rates and Fundamentals',publication:'Journal of Political Economy113(3),485–517；当前作者托管的已发表排版33页文件',url:'https://www.ssc.wisc.edu/~cengel/PublishedPapers/EngelWestJPE.pdf',use:'作者实际读PDF1–14全部文字，覆盖引言、SectionII直觉与III模型，原PDF8–9公式图实际看过；15–33、完整实证和Appendix未读、原数据未复算。支持log本币/外币报价、Eq6中UIP偏离rho的正号定义、条件前瞻解和近随机游走的限制；不把其log式变成本课精确简单期望回报、不校准当前b或认证预测无效。C4是本课另定简单超额π的代数条件回价，非复现完整货币/Taylor模型。'},
 {id:3,authors:'Benoît Cœuré',year:'2017',accessedAt:'2026-09-15',title:'Monetary policy, exchange rates and capital flows',publication:'ECB speech, 3 November 2017, 18th Jacques Polak Annual Research Conference, IMF, Washington D.C.；不混同脚注3所引11 July演讲',url:'https://www.ecb.europa.eu/press/key/date/2017/html/ecb.sp171103.en.html',use:'作者实际读这份11月3日官方演讲全部正文与脚注，并重新核H1/日期/脚注3；所引7月演讲、研究/幻灯片未全部取得。支持预期利率路径、信号和组合再平衡的条件渠道，以及价格可能先于预期资金流调整；演讲中的相关与识别讨论不是本课已认证因果系数，不移植其历史事件或数值为现时政策。政策宣布、已经计价的预期与意外信息必须分别核。'},
 {id:4,authors:'Jonathan Kearns and Nikhil Patel',year:'2016',accessedAt:'2026-09-15',title:'Does the financial channel of exchange rates offset the trade channel?',publication:'BIS Quarterly Review,December2016,95–113；实际19页PDF，非当前HTML自动同版',url:'https://www.bis.org/publications/does-financial-channel-exchange-rates-offset-trade-channel_1.pdf',use:'作者实际读PDF1–5完整文字，包括发票币种/进口投入/定价和金融资产负债表渠道、初始经验方法；6–19的全部结果、表、Appendix与引用论文未读或复算。支持贬值效果取决于现金流和净币种暴露、金融约束可部分抵消贸易渠道；不声称所有贬值都收缩产出，不取原文回归作本课因果参数。C6/C7为独立换算账，未生成真实贷款或数量反应。'},
 {id:5,authors:'International Monetary Fund',year:'2025（white-cover/pre-edited）',accessedAt:'2026-09-15',title:'Integrated Balance of Payments and International Investment Position Manual, Seventh Edition',publication:'BPM7,March2025白皮预编辑版，1076页；不是最终编辑印本、各国统一实施或历史数据自动更新声明',url:'https://www.imf.org/-/media/files/data/statistics/bpm6/draft-bpm7-wcv.pdf',use:'作者实际读封面/指定版本页与PDF50–59的chapter2.1–2.28及2.29开头，PDF303–309的6.69–6.91，345–348的8.1–8.15，363–366的9.7–9.13和完整Box9.1文字；未通读1076页、完整Annex/编制指南/法律。支持CA+KA与FA符号、IIP存量—交易—重估桥、储备控制和可用性等指定定义。本课未导入国家数据，不把会计闭合变成现汇原因；表图仅指定文字阅读，非全部原图或编制程序复现。'},
 {id:6,authors:'Luis A.V. Catão',year:'2007',accessedAt:'2026-09-15',title:'Why Real Exchange Rates?',publication:'Finance & Development,September2007,46–47；旧年官方原PDF题名，非当前HTML迁移题名',url:'https://www.imf.org/external/pubs/ft/fandd/2007/09/pdf/basics.pdf',use:'作者实际完整读两页原PDF正文、侧栏公式与页脚；未据其历史故事、图示或概括生成当前国家估值。支持本币/外币报价下名义与真实相对价格的区别、PPP的条件与真实锚可能变化。文章美元币值的方向描述在教学中重新按S=本币/外币桥接，不盲抄“汇率上升”。换算定义不证明真实均衡、回归速度、可成交汉堡套利或短期预测。'},
 {id:7,authors:'Tim Callen；Sarwat Jahan更新',year:'2017选编更新版（文件制作元数据）',accessedAt:'2026-09-15',title:'Purchasing Power Parity: Weights Matter',publication:'Back to Basics: Economics Concepts Explained,Finance & Development,44–45；图来源WEOSeptember2017，首次原作日期未以PDF元数据冒认',url:'https://www.imf.org/-/media/files/publications/fandd/back-to-basics/callen-purchasing-power-parity.pdf',use:'作者实际完整读两页更新选编原PDF，含PPP与market换算、测量局限、更新署名和图题/图内提取文字；图数据未取得或复算，不把历史ICP/WEO数字当当前事实。支持统计跨国购买力换算与真实可成交FX用途不同。未核全部ICP价格/方法或当前覆盖，不认证福利排名，也不保证现货收敛到统计PPP转换率。'},
 {id:8,authors:'Bank for International Settlements statistics',year:'当前定义页（取得2026-09-15）',accessedAt:'2026-09-15',title:'Effective exchange rates — overview, metadata and FAQs',publication:'BIS Data Portal当前说明；底层方法文章2006与后续更新另列，不将网页时钟当历史PIT',url:'https://data.bis.org/topics/EER',use:'作者实际读About/Metadata/Methodology摘要/Glossary和全部FAQ；没有取得完整权重/指数数据或完整2006方法论文。支持几何贸易权重、相对CPI调整、指数上升为升值和基期100不说明高低估。本课qIndex上升为贬值，与其方向相反；只解释方向和范围，不称BIS重算器。页面现时发布日/基年/权重说明不被自动当全历史版本，所有实证与指数计算仍待读。'},
];
export const lesson320ReadingList:LessonReading[]=[
 {title:'第一遍：Catão真实汇率两页原文',scope:'2007原PDF1–2（印46–47）全文，重点侧栏eP*/P与指数/均衡差别；先核报价方向',reason:'用最小相对价格桥把名义币值、商品购买力和经验均衡分开，不用一个q或汉堡价生成现实高低估评级。',url:lesson320References[5].url,group:'core'},
 {title:'第二遍：BIS covered现金流与约束',scope:'2016四作者QR20页全文；重点BoxA原PDF4–5及套保需求/资产负债表约束节，图和实证须另核',reason:'先按同到期借贷与远期合同复算，再讨论观察偏离为何可能持续；凡使用basis符号，必须注明哪一币种腿和计价。',url:lesson320References[0].url,group:'models'},
 {title:'第三遍：Engel–West模型原式',scope:'PDF7–14，SectionIII A/B/C；需要时回查PDF1–7的前瞻结构与限制',reason:'把rho与信息集、利率单位、no-bubbles和模型闭合条件带着读，不凭利差独立算当前均衡，也不把原log式偷换成有限简单回报。',url:lesson320References[1].url,group:'models'},
 {title:'第四遍：ECB演讲的预期与资金流',scope:'2017官方演讲全部正文/脚注，按signal和portfolio-rebalancing分层；所引实证论文另行取得',reason:'理解信息何时先进入价格、实际流量何时才发生，比较替代解释；演讲相关和条件叙述不等于个人已完成因果识别。',url:lesson320References[2].url,group:'systems'},
 {title:'第五遍：贸易和金融渠道的原经验文章',scope:'Kearns–Patel2016完整19页，包括6–19尚未由作者读完的结果/表/Appendix和局限',reason:'将发票、进口投入与数量选择接到净外币暴露、银行资金和融资约束，检验贸易权重与融资币种权重为什么回答不同问题。',url:lesson320References[3].url,group:'evidence'},
 {title:'第六遍：BPM7的账户与日期定义',scope:'当前白皮预编辑版chapter2.1–2.28；6.69–6.91；8.1–8.15；9.7–9.13/Box9.1。章页和版本须按原件核，全部附录另计',reason:'先把CA+KA=FA的符号、IIP重估与交易、储备可用性辨清，再研究真实资本流；统计版本不能替法律权限或现货因果。',url:lesson320References[4].url,group:'rules'},
 {title:'第七遍：统计PPP与有效汇率的方法',scope:'Callen/Jahan更新双页PDF1–2（印刷44–45）全文；BIS当前About/Metadata/Glossary/allFAQ，再另读官方所链2006方法论文和现行数据说明',reason:'明确各自基期、篮子/贸易伙伴权重、方向和用途；指数100不等均衡，统计PPP不是交易汇率。本课没有下载/重算底层数据。',url:lesson320References[6].url,group:'evidence',links:[{label:'BIS当前EER定义',url:lesson320References[7].url}]},
 {title:'第八遍：对近随机游走解释作研究复盘',scope:'Engel–West2005余下PDF15–33实证/结论/Appendix按页内标题读；先核数据定义与原程序，再锁滚动PIT/OOS对照',reason:'模型兼容近随机游走不证明“基本面无关”；不可拒绝单位根、Granger预测帮助与结构因果不同。作者未读完整余下或重估，不把阅读路线当已执行实验。',url:lesson320References[1].url,group:'systems'},
];
