import type { GlobalBanksSourceId } from './globalBanksReferences';

export type GlobalBanksFormula = {
  kind: 'definition' | 'author-syn' | 'measurement-template';
  expression: string;
  variables: readonly { symbol: string; meaning: string }[];
  explanation: string;
  stopRule: string;
};

export type GlobalBanksConcept = {
  id: string;
  label: string;
  title: string;
  question: string;
  intuition: string;
  actors: string;
  constraints: string;
  behavior: string;
  transmission: string;
  feedback: string;
  formula?: GlobalBanksFormula;
  counterexample: string;
  evidenceBoundary: string;
  interfaces: { from: string; to: string };
  sourceIds: readonly GlobalBanksSourceId[];
  sourceNote: string;
};

export const globalBanksConcepts: readonly GlobalBanksConcept[] = [
  {
    id: 'global-banks-mechanism-01',
    label: 'ENTITY FIRST / GROUP IS NOT ONE WALLET',
    title: '全球银行集团不是一个钱包：合并报表消除内部头寸，却不能消除法律实体、币种与时间边界。',
    question: '为什么集团层面资本与流动性看似充足，某个境外实体仍可能缩减当地贷款？',
    intuition: '把全球银行想成一座由多家公司和办事处组成的建筑，而不是一只可以随时伸手取钱的钱包。合并报表把集团内部的“我欠你、你对我有债权”抵销，是为了看集团对外的净关系；这项会计动作没有把现金搬过法域，也没有替子公司取得董事会、监管或结算批准。理解跨境信贷的第一步不是看集团名字，而是找出哪个法人拥有贷款、哪个办事处记账、哪个实体需要资本和现金。',
    actors: '最终控制母行决定集团战略，银行法人承担合同与监管义务，分行是母行法人在异地的经营部分，子公司通常是独立法人，booking office记录头寸，集团司库安排内部资金，home和host监管者分别从合并与当地角度施加约束。借款人面对的是具体贷款人和合同，而不是抽象的集团标志。',
    constraints: '集团层面的资本、流动性覆盖率（Liquidity Coverage Ratio，LCR）或现金总量不能直接代替实体层面的资本、流动性、显著币种、抵押品所在地与可转移性。内部资金还受公司法、关联交易、税务、监管隔离（ring-fencing，即host以法律或监管方式限制当地资源被集团调走）、内部限额、时区和支付系统影响。任一关键实体身份未知时，只能输出partial或null，不能把母行国籍当成法律债权人。',
    behavior: '冲击发生后，管理层先决定哪些实体留存资源、哪些上划、哪些下拨，再决定削减哪国、哪类客户或哪种产品。分行可能通过母行账簿快速调整，也可能因东道国限制而无法转出；子公司可能依靠本地存款缓冲，也可能因独立资本不足而先缩贷。组织形态改变可选动作，却不预先决定方向。',
    transmission: '当某实体无法取得资本或可执行资金，约束会进入贷款报价、额度、期限、抵押和续作，而不是凭“集团压力”直接跳到GDP。母行若从另一地区抽资救援，原压力可能迁移；若另一实体有本地稳定融资，集团冲击可能被隔断。于是同一集团能同时在一个市场扩张、另一个市场收缩。',
    feedback: '目的地贷款变化会改变客户现金流、贷款表现和附属机构利润，进而改变集团下一轮资本与资金配置。内部支持可以形成负反馈，但共同损失、监管限制与违约上升也可能形成正反馈。这个闭环停在银行—借款人—银行，不提前声称形成了全球金融周期或系统性传染。',
    formula: {
      kind: 'definition',
      expression: 'A_ext,e + I_A,e = L_ext,e + I_L,e + E_e',
      variables: [
        { symbol: 'A_ext,e / L_ext,e', meaning: '实体e对集团外部的资产与负债' },
        { symbol: 'I_A,e / I_L,e', meaning: '实体e对集团内其他实体的债权与债务' },
        { symbol: 'E_e', meaning: '实体e权益；不能由集团现金自动补成' },
      ],
      explanation: '集团合并时内部资产和内部负债相消；实体账上真实发生的资金移动与约束仍然存在。',
      stopRule: '若实体、法人关系、记账地或内部头寸方向未知，不得把集团合并值分摊给实体。',
    },
    counterexample: '母行有100单位现金，子公司有20单位资本缺口。即使法律允许母行借给子公司，集团内贷款只增加子公司的现金和负债，不增加其权益；“集团有钱”不能自动解除子公司的资本约束。',
    evidenceBoundary: 'BIS与Basel材料支持集团、实体、分行、子公司和可转移性需要分开；它们不提供本课合成金额，也不证明任何具体银行当前的内部安排。',
    interfaces: { from: '接收2.06资产负债表恒等式与4.05实体资金状态，只接语义，不读取其SYN数值。', to: '向后续单元交付明确的parent group、legal entity、office与borrower身份。' },
    sourceIds: [1, 3, 6, 7, 8],
    sourceNote: '定义来自官方统计与监管文本；实体可用资源仍需逐案证据。',
  },
  {
    id: 'global-banks-mechanism-02',
    label: 'NATIONALITY / BOOKING / BORROWER AXES',
    title: '一笔贷款同时有三张地理身份证：母行国籍、记账办事处所在地与借款人居住地。',
    question: '“法国银行在伦敦向巴西企业贷款”为什么不能被一个country字段完整表示？',
    intuition: '同一笔贷款像一封有发件集团、寄件网点和收件人地址的邮件。母行国籍回答谁最终控制银行，booking residence回答资产在哪个经济体的办事处账上，borrower residence回答债权面对哪个经济体的直接借款人。三者可以完全不同，而且分别决定统计归属、监管覆盖和冲击传导。',
    actors: '母行国籍由最终控制者决定；伦敦分行或子公司的居住地由经济领土与机构单位规则确定；巴西企业则按自身居住地归类。统计机构、监管者与研究者会选择不同轴做聚合，因此同一交易可以同时进入英国所在地数据、法国银行国籍数据和对巴西债权数据。',
    constraints: 'home、host与counterparty country不是资金流方向。Booking office也不必是做出授信决策、筹得资金或最终承担风险的地点。最小护照必须分别保存parentBankNationality、bookingOfficeResidence、immediateCounterpartyResidence和officeType；缺一项就不能进行需要该轴的聚合。',
    behavior: '冲击发生后，集团可能在母国统一收紧风险限额，host监管者可能限制当地实体调拨，booking office可能更改记账或转让资产，借款人则寻找替代贷款。不同轴决定观察到的是母行共同反应、当地市场反应还是借款国需求，不能用一个国别标签替代。',
    transmission: '母国资本损失可以横跨多个host；同一host监管变化可影响多种国籍银行；同一借款国需求冲击又可同时影响多地记账的银行。只有把三轴保留，研究才可能把home、host与borrower共同变化分开，避免把同步变化误判为单一全球冲击。',
    feedback: '若某借款国贷款恶化，损失会沿资产所有权回到具体booking entity，再进入母行合并资本；母行的重新配置又影响其他host。三轴因此不只是统计标签，而是反馈路径的地址系统，但地址本身并不能证明因果。',
    counterexample: '法国母行的英国分行以美元向巴西公司贷款：银行国籍是法国，记账所在地是英国，借款人居住地是巴西，币种是美元。把这笔贷款只标为“美国相关”或“法国跨境贷款”都会丢失至少一层。',
    evidenceBoundary: 'BIS 2020与2024材料明确区分home、host、booking location与counterparty；它们支持定位，不支持据此推出谁实际提供了边际资金或政策冲击的因果方向。',
    interfaces: { from: '接收4.01 residence语言与本课实体身份。', to: '向LBS/CBS、home-host识别及下游章节交付三轴护照。' },
    sourceIds: [1, 2, 3, 9],
    sourceNote: '三轴是分析键，不是三个可以任意相加的总量。',
  },
  {
    id: 'global-banks-mechanism-03',
    label: 'LBS / CBS AS DIFFERENT CAMERAS',
    title: 'LBS与CBS是两台不同相机：一个从所在地看未合并头寸，一个从母行国籍看全球合并风险。',
    question: '为什么LBS和CBS对同一银行体系给出不同数字，却都可能正确？',
    intuition: '在本课的标准基准情景里，一台相机站在每个城市门口，记录当地银行办事处对外以及与非居民关联office之间的跨境头寸；另一台相机把reporting-area母行的全球网络合成一张集团照片，并在合并边界内消掉内部往来。相片不同不是数据冲突，而是观察单位和合并规则不同。先问相机在哪里、拍了谁，再比较数字。',
    actors: 'LBS报告主体是某地居民银行办事处，标准CBS基准按reporting-area最终控制母行的国籍合并全球业务。报告央行执行口径，BIS汇总，研究者则必须匹配reporting population、instrument、counterparty、currency、valuation/sign、maturity、time、vintage与risk basis后才可并列使用。',
    constraints: '标准跨境LBS保留与非居民related offices的集团内头寸；居民office之间的国内头寸不属于这个跨境聚合。标准CBS对reporting-area银行集团做全球合并并抵销合并边界内往来；特定reporting-population例外可能以standalone／unconsolidated方式报告并保留集团内头寸。二者覆盖、频率、币种和CBSI/CBSG分解不同，不能逐格join、相加或用差额自动解释遗漏。',
    behavior: '问题若关心美元从某host办公室流向哪里，会优先使用LBS；若关心法国银行集团对巴西的全球合并暴露，会使用CBS。若研究内部资本市场，需要LBS保留的intragroup position；若研究集团国别风险，需要CBS。选错镜头会让真实机制在统计上消失。',
    transmission: '冲击可能表现为LBS中的集团内部资金反转，却在CBS中因合并抵销而不可见；也可能表现为CBS总债权稳定，但booking location与融资来源发生迁移。两台相机合用能形成机制假说，却只有在共同护照和额外微观数据下才能识别因果。',
    feedback: '监管、合并范围或实体重组会改变数据覆盖与断点，新的统计图又可能影响市场叙事与政策反应。研究者若把口径差异当经济冲击，会制造伪反馈；因此每次更新都要保存vintage、break和reclassification。',
    formula: {
      kind: 'measurement-template',
      expression: 'Lens = (reporting unit, consolidation, intragroup treatment, allocation basis, instrument, time, vintage)',
      variables: [
        { symbol: 'reporting unit', meaning: '所在地银行办事处或按母行国籍合并的银行集团' },
        { symbol: 'intragroup treatment', meaning: '标准跨境LBS保留非居民related-office头寸；标准consolidated CBS在合并边界内抵销' },
        { symbol: 'allocation basis', meaning: 'LBS、CBSI或CBSG；原始路线与担保人风险重分配另存' },
      ],
      explanation: '比较数字前必须让镜头护照和reporting population可比；这不是把LBS转成CBS的万能公式，例外报告者须回到产品元数据。',
      stopRule: '任一镜头的范围、时间、币种或风险口径未知时，不计算差额含义，更不能相加。',
    },
    counterexample: '在标准reporting-area集团情景下，一家外国分行从非居民母行跨境借40再向当地客户贷60：LBS会保留40的集团内负债，consolidated CBS会抵销这40但保留对客户的合并债权。若reporter属于standalone例外或两office同为本地居民，处理就不能照搬。',
    evidenceBoundary: 'BIS reporting guidelines与2024镜头文章支持这些标准口径和reporting-population例外；它们不能把LBS/CBS差异直接解释为隐藏杠杆、资本外逃或风险转移。',
    interfaces: { from: '接收三轴身份。', to: '向信用路线、存量桥和识别设计交付有护照的统计对象。' },
    sourceIds: [1, 2, 5],
    sourceNote: '官方定义说明“看见什么”，不说明“为什么变化”。',
  },
  {
    id: 'global-banks-mechanism-04',
    label: 'DIRECT CROSS-BORDER / LOCAL AFFILIATE ROUTES',
    title: '同一外国借款人的银行信用有两条主路线：境外办事处直接跨境放贷，或外国银行当地附属机构本地放贷。',
    question: '为什么“外国银行参与”不等于“跨境贷款”，而跨境贷款也不等于外币贷款？',
    intuition: '借款人既可以从境外银行账户直接收到贷款，也可以走进本国的一家外资银行分行或子公司取得当地贷款。前者由booking office与borrower跨越居住地边界定义，后者双方同处一地。银行国籍和贷款币种是另外两条轴，不能替代居住地判断。',
    actors: '境外母行或区域booking hub、当地分行、当地子公司、借款企业、当地存款人、跨境批发资金提供者与home/host监管者共同决定路线。外国附属机构可以用当地存款、当地批发、集团内资金或多种组合支持贷款。',
    constraints: '在CBS常用口径中，foreign claims包含直接跨境claims与外国附属机构当地claims；international claims包含跨境claims加当地外币claims，排除当地本币当地claims。公式只在同一CBSI产品与范围内成立，不能拿LBS与贷款登记册的数字拼成恒等式。',
    behavior: '面对跨境融资或监管收紧，银行可以把业务从母行直贷转向当地附属机构，也可以反向集中到区域中心。路线迁移会改变资金来源、期限、币种和监管约束；集团债权总量不变时，东道国对外部资金的敏感度仍可能改变。',
    transmission: '直接跨境路线通常更直接暴露于境外资产负债表和批发资金条件；当地附属机构若有稳定本地存款，可能缓冲外部冲击，但母行限额、品牌、资本与内部风险管理仍能传导。任何方向都需具体组织与融资证据。',
    feedback: '借款人若转向本地附属机构，东道国存款、资本与监管成为新约束；若当地贷款恶化，损失又回写母行。路线替代可以缓和总信用数量，却可能改变利率、期限与币种风险。',
    formula: {
      kind: 'definition',
      expression: 'ForeignClaims = XBC + LCFX + LCLC; InternationalClaims = XBC + LCFX',
      variables: [
        { symbol: 'XBC', meaning: '从境外booking office对该国借款人的跨境债权' },
        { symbol: 'LCFX', meaning: '外国银行当地附属机构对当地居民的外币当地债权' },
        { symbol: 'LCLC', meaning: '外国银行当地附属机构对当地居民的本币当地债权' },
      ],
      explanation: '公式训练foreign claims与international claims的覆盖，固定为同一外国借款国和CBSI口径。',
      stopRule: '产品、合并范围、币种、国家或CBSI身份不一致时，不计算两项总量。',
    },
    counterexample: '一家德国银行的墨西哥子公司用比索存款向墨西哥企业发放比索贷款。这是外国银行当地本币债权，却不是跨境债权，也不是外币贷款。',
    evidenceBoundary: 'BIS 2019/2025与IMF 2015支持路线定义及历史本地化；不支持宣称当地路线永远安全或跨境路线永远脆弱。',
    interfaces: { from: '接收三轴护照与统计镜头。', to: '向法律形态、目的地重配与借款人替代交付originationRoute。' },
    sourceIds: [1, 3, 4, 12],
    sourceNote: '路线由居住地定义；币种、银行国籍与CBSG风险分类必须另存。',
  },
  {
    id: 'global-banks-mechanism-05',
    label: 'BRANCH / SUBSIDIARY GATES',
    title: '分行与子公司改写传导门，但没有“分行一定更灵活、子公司一定更安全”的普遍排序。',
    question: '法人形态怎样改变资本、流动性、母行责任与东道国ring-fencing，而又为何不能单独决定韧性？',
    intuition: '分行通常是母行同一法人的异地部分，子公司通常是另行注册的法人。这个差异像同一本账的异地柜台与另一家公司：前者与母行责任连接更直接，后者有自己的资本与治理。然而真实资金能否移动还要经过当地规则、币种、内部限额与运营时钟，名称不是万能答案。',
    actors: '母行董事会、分行管理层、子公司董事会、home supervisor、host supervisor、resolution authority、存款保险与集团司库共同塑造门。借款人与存款人还会根据法律责任和保护安排改变行为，进一步影响资金稳定性。',
    constraints: '分行虽非独立法人，也可能面对host流动性、资产维持、报告或ring-fencing要求；子公司虽有独立资本，仍可接受母行贷款、增资或担保，也受集团风险限额影响。具体法域差异很大，Basel原则不能替代当地法律。',
    behavior: '集团会在分行与子公司之间选择业务、资金和风险的记账结构。冲击时，分行可能迅速获得母行支持，也可能被母行直接抽资；子公司可能依靠本地存款与资本继续贷款，也可能因关联交易上限或独立资本不足收缩。',
    transmission: '法人形态改变home/host约束的作用点，从而改变冲击速度、损失归属和重组方式。它还影响统计镜头：分行与子公司在所在地数据中都是当地办事处，但在法律责任和合并层面不同。',
    feedback: '危机经验可能推动host强化本地资本或ring-fencing，进而改变下一阶段集团组织。加强当地保护可以提高本地韧性，却也可能减少集团跨境风险共担；效果方向依冲击来源和约束组合。',
    counterexample: '若分行受到严格的当地资产维持上限，而资本充足、存款稳定的子公司可在本地留存资金，则子公司当期贷款容量可能更高。换一个host或母行冲击，排序可以反转。',
    evidenceBoundary: 'BIS、Basel与IMF材料支持法律形态和home/host约束重要；不支持用全球统一参数给分行与子公司排序。',
    interfaces: { from: '接收实体层级与信用路线。', to: '向typed transfer state和目的地配置交付officeType及条件约束。' },
    sourceIds: [3, 7, 8, 12, 13],
    sourceNote: '原则性监管文本必须与具体法域事实分开。',
  },
  {
    id: 'global-banks-mechanism-06',
    label: 'LBS CLAIMS / CREDIT PERIMETER',
    title: 'Claims与credit的工具范围不同：先锁定数据产品，再解释数量。',
    question: '为什么“银行claims下降”不能被直接改写成“银行少发了同额贷款”？',
    intuition: 'Claim是债权人金融资产的较宽概念；在本课使用的LBS工具口径中，贷款/存款与债务证券构成credit，正市值衍生品和其他剩余工具会让claims更宽。未提款承诺是比较项，不属于这两个LBS小计。2.06已经讲过申请、批准、承诺、提款、发放和余额的生命周期；这里不重讲，只把它当防止误读的护栏。',
    actors: '贷款与存款、债务证券、衍生品、其他应收工具分别由不同合同和估值规则产生；统计报告者按产品元数据聚合，研究者必须先读instrument perimeter。借款人、授信部门与交易部门的行为不能从一个claims总量中被自动恢复。',
    constraints: '衍生品正市值是对手方暴露，不是同额贷款；名义本金更不能替代正市值。未提款承诺是潜在敞口，不是LBS claims或credit余额。CBS claims又排除衍生品并使用不同覆盖，因此不存在跨LBS/CBS通用的claims公式。',
    behavior: '银行可在贷款、证券和衍生品之间重配；债券价格或衍生品市值也会改变claims，而借款人未收到新现金。反过来，银行可收紧审批而旧贷款余额暂时不变。使用错误工具范围会把估值和供给行为混成一件事。',
    transmission: '只有把工具拆开，才能判断变化首先进入企业贷款、银行同业存款、证券投资还是衍生品暴露，再连接到借款人融资。聚合claims适合描述资产暴露，不足以单独识别边际信贷供给。',
    feedback: '市场价格令证券或衍生品claims变化，可能随后影响资本与贷款行为；这种反馈具有时间顺序。若直接把当期估值变化叫作缩贷，会把后续行为倒置成当期原因。',
    formula: {
      kind: 'definition',
      expression: 'LBS credit = loans/deposits + debt securities; LBS claims = credit + positive-MV derivatives + other residual instruments',
      variables: [
        { symbol: 'LBS credit', meaning: '本课声明口径中的贷款/存款与债务证券' },
        { symbol: 'positive-MV derivatives', meaning: '对报告银行为正的公允价值，不是名义本金' },
        { symbol: 'undrawn commitment', meaning: 'LBS小计之外的比较项；不得加入claims或credit' },
      ],
      explanation: '这是LBS工具口径。进入CBS或其他贷款数据时必须重新读取元数据。',
      stopRule: '数据产品、工具或估值基础未知时，不计算；选择CBS时禁止沿用本式。',
    },
    counterexample: '贷款/存款50、债券20、正市值衍生品6、其他剩余工具4、未提款承诺12时，LBS credit为70、LBS claims为80，承诺12单列。把它们相加成92会混合当前资产和潜在义务。',
    evidenceBoundary: 'BIS正式定义支持LBS工具分类；它不说明贷款申请、审批和提款的微观变化，后者需要贷款级数据。',
    interfaces: { from: '接收2.06贷款生命周期作为guardrail与本课statisticalLens。', to: '向存量桥、贷款要约和识别设计交付instrument perimeter。' },
    sourceIds: [1, 4],
    sourceNote: 'undrawn commitment只作比较，不被称为LBS报告工具。',
  },
  {
    id: 'global-banks-mechanism-07',
    label: 'CBSI / CBSG RISK ALLOCATION',
    title: '担保可以重分配统计风险，却不会把原始借款人、记账地或贷款现金路线搬到担保人那里。',
    question: '为什么CBSI与CBSG的国家风险地图会不同，而原始跨境或当地放款路线仍然不变？',
    intuition: '企业A借钱、母公司B提供合格担保。CBSI按即时对手方把债权放在A；CBSG按担保人基础可能把相关风险金额分配给B。担保像损失承担的第二地址，不是把当初的收款人改名。原始路线始终由booking office和即时借款人的居住地关系决定。',
    actors: '即时借款人、担保人、信用保护提供者、贷款银行、法律顾问、风险部门和统计报告者决定风险能否按CBS规则转移。母行责任、担保和信用衍生品各有条件，guarantor也不等于完整的最终经济损失模型。',
    constraints: '护照必须同时保存immediateCounterpartyResidence、guarantorResidence、allocationBasis、riskTransferAmount和originationRoute。CBSG可能改变reportedLocationClass，却不改变借款合同、booking office、币种与现金腿。缺少风险转移桥时不能从CBSI推导CBSG。',
    behavior: '银行可能因合格担保调整定价或资本占用，也可能在担保人恶化后同时收紧多个借款人。研究者若只按直接借款国聚合，会遗漏共同担保风险；只看CBSG又可能看不到资金最初流向的经济体。',
    transmission: '担保把一个借款人的潜在损失连接到另一主体和法域，形成跨国风险关联；信用供给仍通过原贷款合同进入借款人。两张风险地图与原始路线联合保存，才能区分资金去向和报告风险归属。',
    feedback: '担保人信用恶化会重估保护价值，银行重新分配限额，多个被担保借款人可能同步受影响；借款人违约又消耗担保人资源。风险转移随合同和时间变化，必须保留as-of与vintage。',
    counterexample: '巴西子公司向伦敦分行借美元，美国母公司提供合格担保。CBSI可能归巴西，CBSG可能把相应风险归美国，booking office仍在英国，originationRoute仍是英国到巴西的cross-border。',
    evidenceBoundary: 'BIS指南支持CBSI与guarantor-basis CBSG；它不证明担保在法院、破产或压力期必然足额执行，也不提供违约概率（probability of default，PD）或违约损失率（loss given default，LGD）。',
    interfaces: { from: '接收三轴、原始路线与工具身份。', to: '向目的地配置、识别与网络层分别交付originationRoute和reportedLocationClass。' },
    sourceIds: [1, 2, 5],
    sourceNote: '风险重分配与现金路线永久分栏。',
  },
  {
    id: 'global-banks-mechanism-08',
    label: 'STOCK / FLOW / LBS ADJUSTED CHANGE',
    title: '期末减期初不是新增贷款：存量变化要穿过交易、重估、核销、出售、重分类与报告断点。',
    question: '为什么跨境claims下降10，可能既不是银行主动缩贷10，也不是借款人少获得10？',
    intuition: '仓库里货物比上季少10，可能因为少进货、多出货、货物损坏、计价变化或仓库边界改变。银行债权存量也一样：发放与偿还是交易，汇率、证券价格、核销、贷款出售、并购和数据断点也能改变期末数。',
    actors: '银行发放与回收贷款，借款人提款与偿还，交易部门买卖债权，会计核销，市场价格和汇率改变估值，统计机构记录断点和重分类。研究者需要决定目标是gross origination、net transaction、LBS adjusted change还是end stock。',
    constraints: '一般会计桥要为每一项声明符号；LBS的官方变化序列主要调整汇率和series breaks，仍可能含其他估值与write-down影响。CBS因币种构成不足不计算相同的adjusted-change序列，禁止自行把CBS存量差贴上同一标签。',
    behavior: '压力期银行可能停止新贷但旧贷款尚未到期，存量短期不降；也可能出售贷款使账面存量下降而借款人合同继续存在。借款人集中偿还也会造成下降，却可能反映需求或现金改善。',
    transmission: '错误的存量解释会把估值冲击当信贷供给，继而错误连接到投资与就业。正确桥接要求把行为事件和会计变化对齐，再把剩余部分标为未解释，而不是用叙事补齐。',
    feedback: '市场贬值与核销压低资本，下一期可能真正收紧供给；因此估值变化虽不是当期新贷流量，却可能成为后续行为输入。时间顺序必须显式保存。',
    formula: {
      kind: 'measurement-template',
      expression: 'ClosingStock = OpeningStock + Transactions + FXValuation + PriceValuation + WriteOffs/OtherVolumeChanges + Breaks/Reclassifications',
      variables: [
        { symbol: 'Transactions', meaning: '发放、偿还、买卖等期间交易，按声明符号记账' },
        { symbol: 'Valuation', meaning: '汇率或价格造成、并非交易的变化' },
        { symbol: 'Breaks/Reclassifications', meaning: '报告边界、方法、并购或分类改变' },
      ],
      explanation: '这是作者的一般会计地图；BIS LBS adjusted change只是在其方法下调整汇率与series breaks的近似流量。',
      stopRule: '产品、币种、估值基础、break或vintage不清时，不把原始差分称为贷款流；CBS不得套用LBS标签。',
    },
    counterexample: '英国办事处持有100欧元贷款，欧元对报告货币贬值10%，没有发放或偿还，报告存量也可能下降约10；称为“缩贷10”会颠倒因果。',
    evidenceBoundary: 'BIS指南支持存量与LBS adjusted-change边界；不提供贷款级gross origination，也不识别供需。',
    interfaces: { from: '接收4.01头寸—交易桥与本课工具边界。', to: '向目的地重配和实证设计交付measurement identity。' },
    sourceIds: [1, 2, 17],
    sourceNote: '只有LBS使用该官方调整标签；调整仍不是因果。',
  },
  {
    id: 'global-banks-mechanism-09',
    label: 'SHOCK PASSPORT BEFORE TRANSMISSION',
    title: '先给冲击办护照：母行资本损失、核心币种融资、母国政策、东道国损失与监管变化不是一个“风险厌恶”变量。',
    question: '为什么不同来源的冲击可能产生相似贷款下降，却要求完全不同的识别和反例？',
    intuition: '看到发烧不等于知道病因。贷款下降可以来自母行资本受损、核心币种融资受限、host贷款损失、监管上限、借款需求下降或银行主动改变组合。若一开始把它们压成“全球情绪”，后续所有方向都无法证伪。',
    actors: '母行、集团司库、home央行与监管者、host监管者、当地附属机构、资金提供者和借款人分别可能产生冲击。每个冲击要保存对象、事件时点、币种、期限、事前暴露、宣布与生效日期以及是否被研究设计识别。',
    constraints: '冲击必须在行为结果之前定义，不能用贷款下降反推冲击。政策变化常同时发生并可能被预期；资本损失与融资流出可相关；host需求与资产质量可能共同变化。没有独立时钟和事前暴露，只能称候选条件。',
    behavior: '资本冲击可能促使降低风险加权资产（risk-weighted assets，RWA）、增资或重配贷款；融资冲击先影响期限和币种；home监管可能跨host作用；host规则影响同地不同国籍银行；需求冲击则使多家银行面对同一借款人同时少贷。反应向量有助于区分来源。',
    transmission: '带护照的冲击先进入特定约束，再通过内部配置和贷款要约传递；没有护照的risk-off会跳过关键中介。多个冲击可以叠加，但必须分别记录再建交互，不能事后挑选最符合叙事的单因。',
    feedback: '贷款收缩会恶化当地经济并产生新损失，使最初外生冲击逐步内生化。识别窗口要尽量捕捉早期相对反应，长期则承认双向因果和一般均衡。',
    counterexample: '两家外国银行都在某国少贷：一家母行资本受损，另一家只因同一客户需求下降。聚合结果相同，但第一家可能在其他国家也重配，第二家会在同一借款人的所有贷款关系中同步变化。',
    evidenceBoundary: '历史论文展示特定母行、资金与政策冲击的识别；不支持把任一市场指标视为实时、全局且唯一的银行冲击。',
    interfaces: { from: '接收4.05资金状态、2.06资本/风险状态和home/host事件，只保留各自身份。', to: '向typed transfer、贷款要约和识别设计交付shock passport。' },
    sourceIds: [9, 10, 11, 14, 15, 16],
    sourceNote: '历史识别结论依样本；正文不使用普适冲击系数。',
  },
  {
    id: 'global-banks-mechanism-10',
    label: 'TYPED UPSTREAM TRANSFER / CONDITIONAL LENDING',
    title: '4.06不重新判定内部资金能否移动；它只研究已带状态的上游结果怎样条件性改变贷款容量。',
    question: '为什么realised、committed executable、quoted only、unavailable与null必须在进入贷款决策前分开？',
    intuition: '上一节已经负责检查资金路线。到了本节，银行贷款团队接收的不是一句“母行会支持”，而是一条带提供方、接收方、金额、币种、value timestamp和状态的记录。只有已经realised的现金属于as-of资源；未来已承诺的腿仍有自己的时钟，报价与未知更不能被当成现金。',
    actors: '4.05的资金状态、提供实体、接收分行或子公司、集团司库、当地贷款团队与资本/风险管理部门构成接口。4.06观察这些状态如何进入loan-offer vector，而不重复法律、监管、抵押和结算资格审查。',
    constraints: '必须保留canonical枚举realised、committed_executable、quoted_only、unavailable和null。若把一条realised cash leg加入贷款资源，基线必须明确排除该腿，防止双计。Committed executable只在其未来value date与决策窗口相容时单列，不能改写为已到账。',
    behavior: '贷款团队会把已到账资金与资本、风险、集中度和当地监管容量联合考虑。相同的20单位realised现金，对资本受限子公司可能不增加贷款，对流动性受限分行则可能扩大报价；差异是条件组合，不是法人形态本身的单因效应。',
    transmission: '上游状态通过利率、额度、期限和审批影响借款人，而不是从集团资金直接跳到贷款余额。若资金为null，专业输出是贷款容量unknown；若unavailable，相关路线贡献为0，但其他本地资源仍可继续计算。',
    feedback: '贷款增加会占用现金和资本，改变下一轮上游需求；贷款不良又可能令母行撤回支持。接口因此是动态的，但每一轮都要保存独立as-of和不可重复cash-leg ID。',
    counterexample: '母行口头表示愿意支持20，但状态只是quoted_only；若页面仍把当地可贷资源增加20，就同时越过了4.05的资格、承诺与结算门。正确结果是该腿不进入realised基线。',
    evidenceBoundary: 'CGFS、Basel和FRBNY研究支持内部市场与可转移性重要；本单元不声称其合成状态是现实银行交易，也不重新计算上游可执行性。',
    interfaces: { from: '从4.05只显式导入现有五值status enum及可核验时钟约束，不读取其SYN数值或现实状态；身份、金额、zero/null和容量映射属于4.06本地合同，因此numerical inputLineage仍为空。', to: '向贷款要约和目的地配置交付条件性资源状态，不交付因果系数。' },
    sourceIds: [6, 7, 10, 11],
    sourceNote: '资金资格属于4.05；贷款配置属于4.06。',
  },
  {
    id: 'global-banks-mechanism-11',
    label: 'LOAN-OFFER VECTOR',
    title: '资产负债表约束通过贷款要约传导：利率、额度、审批、期限、抵押、契约与续作必须保留为向量。',
    question: '为什么“银行收紧”不能只用一个贷款余额或一个利差表示？',
    intuition: '银行不是只有“贷”与“不贷”两个按钮。它可以保持名义额度却提高费用，维持利率却缩短期限，要求更多抵押，降低审批概率，限制提款，拒绝续作或转向另一币种。借款人感受到的是一组合同条件，而非一个情绪分数。',
    actors: '关系经理、授信委员会、定价与风险团队、贷款运营、借款人和担保人共同形成要约。监管资本、流动性、集中度、行业限额和内部风险预算分别作用于不同条款。',
    constraints: 'price、quantity和non-price terms需要同一借款人、产品、期限、币种和时点护照。已批准额度不等于提款，报价不等于成交，续作和新发放不同。若只观察余额，无法知道银行改变了审批、条款还是客户需求。',
    behavior: '约束变紧时，银行会优先调整资本或流动性占用高、信息劣势大或关系价值低的贷款；也可能保留核心客户额度、减少新客户或缩短commitment。借款人则比较总成本与可替代性，决定提款、偿还或更换渠道。',
    transmission: '要约向量先影响借款人可获得现金与风险承担，再影响库存、投资、就业与对冲。不同条款还改变未来反馈：短期限提高rollover风险，外币贷款增加币种敏感度，更高抵押要求把资产价格引入信用供给。',
    feedback: '企业预防性提款会消耗银行流动性，迫使银行收紧其他客户；提高利率可能恶化逆向选择与违约，反过来削弱资本。稳定关系、长期合约和承诺也可能缓冲反馈。',
    counterexample: '贷款余额本季不变，但银行把新授信审批率从80%降到40%，期限从三年缩到一年并提高抵押要求。仅看存量会得出“供给未变”，实际边际条件已显著收紧。',
    evidenceBoundary: '证据必须逐项对齐：SLOOS与ECB Bank Lending Survey问卷直接观察银行报告的standards、spreads、maximum size／maturity、collateral与covenants等变化；贷款关系研究观察特定样本的数量与替代；申请级approval、单笔合同、renewal和实际提款仍需各自微观数据。BIS聚合claims通常不观测这些条款，本课把未被当前来源直接观察的维度保留为概念候选或unknown。',
    interfaces: { from: '接收带身份冲击，以及由导入枚举／时钟约束和4.06本地情景身份共同构成的条件输入。', to: '向借款人替代和识别设计交付price/quantity/terms outcomes。' },
    sourceIds: [14, 15, 18, 19, 20, 21],
    sourceNote: '问卷、申请、合同、提款与余额是不同证据层；没有对应层级数据时，该条款方向保持unknown。',
  },
  {
    id: 'global-banks-mechanism-12',
    label: 'CROSS-DESTINATION REALLOCATION',
    title: '集团可以跨国家、行业、币种与产品重配：集团总资产稳定，不等于每个目的地信贷稳定。',
    question: '为什么某国跨境贷款下降，既可能是集团去杠杆，也可能只是资产重新配置？',
    intuition: '一个有限行李箱可以在不同口袋间重新分配重量，总重量不变时某个口袋仍会变空。全球银行在资本、资金与风险预算下选择不同国家、客户、币种和产品；总资产只看到箱子重量，看不到谁被拿走了资源。',
    actors: '集团资产负债管理委员会、国家与行业业务线、区域中心、当地附属机构、客户经理和风险部门争夺稀缺容量。home/host政策、盈利、关系价值、风险权重、当地融资和退出成本影响排序。',
    constraints: '必须区分gross expansion与contraction、目的地share、资产出售与自然到期、币种与instrument。一个国家下降和另一个上升不能自动净成“无冲击”；集团稳定也不能证明内部没有强烈传导。',
    behavior: '母行受限时可能保护核心市场和高关系价值客户，削减外围或批发业务；也可能因host ring-fencing无法抽资，只能在其他地区缩表。某地规则收紧还可能把业务迁往另一个booking hub而非减少最终借款人信用。',
    transmission: '重配把母国或集团冲击不均匀地输出到多个host，形成异质贷款反应。若多家银行采用相似排序，某些目的地可能集中失去供给；若其他银行反向进入，总信用更稳定。',
    feedback: '退出后的市场份额与客户关系会改变未来盈利和再进入成本，影响下一轮配置。目的地损失恶化又可能把原本战略性撤退变成资本驱动的进一步收缩。',
    counterexample: '集团总foreign claims保持90，但在同一决策窗口把A从40降到20、B从30升到50、C保持20。总量不变，A仍少20；这只是条件性配置桥，不证明管理层动机，也不等于A的总信用下降20。',
    evidenceBoundary: 'BIS地理数据、IMF与ECB历史研究支持目的地异质与重配；不提供普适的核心/外围分类，也不识别未观测管理层动机。',
    interfaces: { from: '接收originationRoute、entity、risk basis与measurement identity。', to: '向借款人替代与4.07交付typed bank-credit edges，而非common factor。' },
    sourceIds: [3, 9, 12, 13, 17],
    sourceNote: '一个集团跨目的地重配不能被命名为global financial cycle。',
  },
  {
    id: 'global-banks-mechanism-13',
    label: 'BORROWER SUBSTITUTION / TOTAL FINANCING',
    title: '一家全球银行撤退只是第一步：借款人能否转向其他银行、债券、贸易信用或内部现金，决定总融资缺口。',
    question: '为什么双边贷款减少20，借款人总融资可能只减少3，也可能接近减少20？',
    intuition: '一家商店断货不等于整座城市没有商品；顾客能否换店取决于其他商店是否有货、是否认识顾客、商品是否同质和换店成本。贷款也一样：替代需要信息、抵押、关系、规模、币种和市场准入，不能假定一比一。',
    actors: '受冲击全球银行、其他外国银行、本地银行、债券与非银投资者、贸易伙伴、企业内部资金和借款人共同形成替代网络。大型透明企业与小型关系型借款人的选择通常不同。',
    constraints: '替代比较必须使用相同借款人、时间、币种、期限和用途；数量替代也可能伴随更高利率、更短期限或更强抵押。若只观察原银行，total financing与real outcome必须保持unknown。',
    behavior: '借款人会先动用承诺或现金缓冲，再申请其他银行、发行债券、延迟投资或减少库存。替代银行需要评估信息和限额，可能只接纳优质客户；这会改变样本平均借款人质量并产生选择效应。',
    transmission: '替代充分时，银行特定冲击主要改变价格和关系结构；替代不充分时，现金缺口进入企业决策。金融深化、债券市场和贷款人多样性可以缓冲，共同冲击也可能让多个替代渠道同时关闭。',
    feedback: '换贷削弱原关系银行的信息资本，改变未来融资成本；企业削减活动会恶化其他银行资产质量，使替代能力下降。新贷款人进入则可能分散集中度并缓冲下一轮冲击。',
    formula: {
      kind: 'definition',
      expression: 'ΔTotalFinancing = ΔShockedRoute + ΔOtherBanks + ΔBonds/NBFI + ΔTradeCredit + ΔInternalCash',
      variables: [
        { symbol: 'ΔShockedRoute', meaning: '原全球银行或原路线的融资变化' },
        { symbol: 'ΔOtherBanks / Bonds/NBFI', meaning: '同借款人同窗口的其他银行、债券与非银行金融机构（non-bank financial institution，NBFI）替代变化' },
        { symbol: 'ΔInternalCash', meaning: '企业内部资金；未观察时保持unknown而非0' },
      ],
      explanation: '恒等式强调总融资需要全覆盖；它不是替代率模型。',
      stopRule: '缺少替代渠道或需求状态时，不从原渠道变化推出总融资与实体结果。',
    },
    counterexample: '全球银行少贷20、本地银行多贷12、债券多5，则原路线为−20、当前已覆盖银行渠道为−8、已观察all-financing为−3。只有银行渠道清单complete时，−8才可升级为all-bank；三个口径必须同时显示，不能挑一个代表全部。',
    evidenceBoundary: '匹配银行—借款人研究支持替代分析；聚合跨境统计没有完整借款人融资，不足以声称总信用或投资结果。',
    interfaces: { from: '接收贷款要约与目的地撤退。', to: '向识别、实体反馈与4.08交付substitution status及coverage。' },
    sourceIds: [12, 15, 18, 19],
    sourceNote: '原路线、全部银行与全部融资是三个不同结果口径。',
  },
  {
    id: 'global-banks-mechanism-14',
    label: 'SUPPLY IDENTIFICATION / BORROWER-TIME GATE',
    title: '同时少贷不等于供给冲击：同一借款人、多银行关系与事前暴露把银行供给和借款需求分开。',
    question: '怎样证明贷款下降来自银行侧，而不是借款人投资机会或信用质量同时变差？',
    intuition: '如果同一家公司同时向银行A和B借款，外部冲击只打到A，而A相对B更明显缩贷，证据比“衰退时所有贷款都下降”更接近供给。borrower×time fixed effects相当于在同一时刻吸收公司共同需求与质量，再比较贷款人差异。',
    actors: '处理银行、对照银行、共同借款人、政策或融资冲击、贷款登记系统和研究者构成设计。理想数据保存事前暴露、申请、批准、金额、条款、提款和借款人替代融资。',
    constraints: '冲击暴露必须在结果前确定；银行选择借款人可能非随机；关系强度、币种、产品和到期结构可同时不同。Borrower×time固定效应识别同一借款人的相对银行供给，不保留只有一家银行的借款人，也不自动识别总信用。',
    behavior: '研究者先锁定处理、对照、事件时钟和预趋势，再估计相对贷款反应；随后汇总借款人的全部银行和债券融资，才能检验替代和实体结果。并购、实体重组、政策预期和同时发生的host需求冲击都要检查。',
    transmission: '局部设计把机制链的“冲击→银行要约”一段变得可证伪；若再观察企业融资和真实结果，才可延伸到“要约→企业行为”。缺失任何一段时，应停在已识别边界。',
    feedback: '较长窗口中，银行缩贷会改变借款人质量和需求，原本对照也被反馈污染；因此短期相对供给、长期总融资和一般均衡要分层报告。结论不能超出样本银行、国家与冲击。',
    formula: {
      kind: 'measurement-template',
      expression: 'Loan_ijt = β(PreExposure_j × Post_t) + Borrower_i×Time_t FE + controls + ε_ijt',
      variables: [
        { symbol: 'i / j / t', meaning: '借款人、银行与时间；结果位于同一借款人的银行关系' },
        { symbol: 'PreExposure', meaning: '冲击前确定的银行暴露，不由结果倒推' },
        { symbol: 'Borrower×Time FE', meaning: '吸收同一借款人同期共同需求与质量变化' },
      ],
      explanation: 'β是特定设计中的相对贷款供给反应，不是总信用或普适结构参数。',
      stopRule: '没有共同借款人、事前暴露、明确时钟或可辩护对照时，不使用“已识别供给冲击”。',
    },
    counterexample: '某国衰退时外国银行和本地银行都少贷。没有同一借款人比较或外生银行暴露，数据同时符合需求下降、风险恶化和供给收紧，不能只选供给叙事。',
    evidenceBoundary: 'Peek–Rosengren、Schnabl和Khwaja–Mian展示不同识别策略；每篇只支持其特定样本、冲击与结果，不能把系数跨国跨期复用。',
    interfaces: { from: '接收shock passport、loan-offer vector与substitution coverage。', to: '交付descriptive、accounting、identified-local或unknown证据状态。' },
    sourceIds: [9, 14, 15, 18, 19],
    sourceNote: '局部相对供给不是总融资，更不是一般均衡。',
  },
  {
    id: 'global-banks-mechanism-15',
    label: 'HOST OUTCOME / PARENT FEEDBACK',
    title: '东道国结果可能回写母行：把贷款、企业行为、违约、拨备与资本画成待检验的反馈候选。',
    question: '全球银行传导为什么不是母国到东道国的一次性单向箭头？',
    intuition: '系统上存在一条需要逐箭头验证的候选链：银行缩贷可能影响企业；企业反应可能改变现金流与抵押价值；随后才可能出现违约、拨备、当地实体利润或母行资本变化，并进入下一轮配置。会计上能画出这条链，不等于当前三组文献已经在同一银行、借款人和时钟中证实完整闭环。',
    actors: '借款企业、员工与供应商、当地银行与附属机构、母行、抵押品市场、审计和拨备体系、home/host监管者共同闭合链条。不同主体反应速度从日内资金到季度贷款和多年实体结果不等。',
    constraints: '反馈结论需要企业总融资、行为、违约、抵押价值、银行损失和资本的时间排序。只观察外国银行claims无法证明GDP、就业或违约路径；反向因果和政策响应会随窗口增长。',
    behavior: '作为候选机制，替代不充分的企业可能先使用现金、削减支出或拖延付款；银行可能提高拨备、处置不良资产并收紧限额；母行也可能注资、出售业务或从其他市场回撤。每个“可能”都需要独立观测，host政策还会同时改变借款人与银行约束。',
    transmission: '企业活动→抵押价格、借款人损失→当地实体拨备、当地实体→母行资本、母行资本→其他host配置是四段不同箭头。当前来源直接支持其中若干前段或历史单向通道，后半段在本课保持conceptual／unobserved；若当地存款、资本和替代融资稳定，候选链可被截断。',
    feedback: '只有当同一证据包按时间连接企业结果、违约、拨备、实体利润／资本和下一轮跨host配置时，才可称“观察到反馈闭环”。本课只交付可证伪的反馈候选，不把局部案例拼成已证实闭环或危机预测器。',
    counterexample: '全球银行对一国少贷15，但本地银行和债券完全补足数量，企业投资未变，则“缩贷→产出下降→违约→母行损失”的链在借款人替代处被切断；原银行仍可能失去关系和未来收益。',
    evidenceBoundary: 'Source 19支持特定危机样本中贷款人暴露与企业融资／就业，source 14支持历史home→host贷款通道，source 12支持路线与替代；三者都没有共同验证borrower loss→provision→parent capital→next allocation。后四段因此明确标为概念候选或未观测。',
    interfaces: { from: '接收总融资结果与证据身份。', to: '向4.07–4.09和7.10–7.16交付类型化信用边、反馈候选与严格guardrail。' },
    sourceIds: [12, 14, 19],
    sourceNote: '逐箭头证据不能由跨样本文献自动拼接；替代和政策还可能在任一段形成负反馈。',
  },
];
