import type { LessonReading, LessonReference } from './types';

export const lesson406References = [
  {
    id: 1,
    authors: 'Bank for International Settlements',
    year: '2019',
    accessedAt: '2026-09-17',
    title: 'Reporting guidelines for the BIS international banking statistics',
    publication: 'BIS International Banking Statistics',
    url: 'https://www.bis.org/publications/reporting-guidelines-bis-international-banking-statistics.pdf',
    use: '支持LBS/CBS、residence/nationality、合并与集团内抵销、工具覆盖、immediate/ultimate risk、剩余期限和调整后变化的正式口径；不解释某个存量为何变化，也不能从聚合表识别银行供给因果。',
  },
  {
    id: 2,
    authors: 'McGuire, Patrick; von Peter, Goetz; Zhu, Sonya',
    year: '2024',
    accessedAt: '2026-09-17',
    title: 'International finance through the lens of BIS statistics: residence versus nationality',
    publication: 'BIS Quarterly Review, March',
    url: 'https://www.bis.org/publications/qr-202403/international-finance-through-lens-bis-statistics-residence-vs-nationality',
    use: '支持所在地镜头与国籍镜头回答不同问题，以及二者如何观察全球银行；不支持把两套统计逐格相加或把银行国籍当成记账地。',
  },
  {
    id: 3,
    authors: 'Hardy, Bryan; McGuire, Patrick; von Peter, Goetz',
    year: '2024',
    accessedAt: '2026-09-17',
    title: "International finance through the lens of BIS statistics: the geography of banks' operations",
    publication: 'BIS Quarterly Review, December',
    url: 'https://www.bis.org/publications/qr-202412/international-finance-through-lens-bis-statistics-geography-banks-operations',
    use: '支持home、host、booking location和借款人所在地构成多轴地理，以及当地融资结构与韧性相关；不提供所有分行或子公司的固定稳定性排序。',
  },
  {
    id: 4,
    authors: 'Ehlers, Torsten; Hardy, Bryan; McGuire, Patrick',
    year: '2025',
    accessedAt: '2026-09-17',
    title: 'International finance through the lens of BIS statistics: the international dimensions of credit',
    publication: 'BIS Quarterly Review, March',
    url: 'https://www.bis.org/publications/qr-202503/international-finance-through-lens-bis-statistics-international-dimensions-credit',
    use: '支持直接跨境与经当地银行间接形成的国际信用、claims与credit的工具边界；不支持把所有当地外币贷款都称为直接跨境贷款，也不提供单家银行因果系数。',
  },
  {
    id: 5,
    authors: 'Bank for International Settlements',
    year: 'n.d.',
    accessedAt: '2026-09-17',
    title: 'Consolidated banking statistics',
    publication: 'BIS Data Portal',
    url: 'https://data.bis.org/topics/CBS',
    use: '支持CBS当前数据产品、元数据和下载入口；动态数据可被修订，页面存在不等于本课加载了当前快照，更不支持逐家银行识别。',
  },
  {
    id: 6,
    authors: 'Committee on the Global Financial System',
    year: '2026',
    accessedAt: '2026-09-17',
    title: 'Foreign currency funding risk and cross-border liquidity',
    publication: 'CGFS Papers No 71, Bank for International Settlements',
    url: 'https://www.bis.org/publications/cgfs-paper-71-foreign-currency-funding-risk-and-cross-border-liquidity.pdf',
    use: '支持把实体、币种、记账地、期限和集团内部资金移动联合观察，以及压力期可转移性可能下降；不把本课FCFR合成式升级为官方指标，也不证明任一银行当前受限。',
  },
  {
    id: 7,
    authors: 'Basel Committee on Banking Supervision',
    year: '2019',
    accessedAt: '2026-09-17',
    title: 'LCR10: Definitions and application',
    publication: 'Basel Framework',
    url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lcr?allChapters=true',
    use: '支持LCR在集团、法律实体、分行、子公司与显著币种层面的监测，以及法律、监管和操作转移限制；Basel标准不是所有法域直接生效的同一法律，也不证明某个约束在某日binding。',
  },
  {
    id: 8,
    authors: 'Basel Committee on Banking Supervision',
    year: '2024',
    accessedAt: '2026-09-17',
    title: 'Core Principles for effective banking supervision',
    publication: 'Basel Framework, BCP',
    url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/bcp?allChapters=true',
    use: '支持母国合并监管、东道国监管及跨境监督合作的原则边界；不代替特定法域的公司法、破产法或实体级审批证据。',
  },
  {
    id: 9,
    authors: 'Avdjiev, Stefan; Hardy, Bryan; McGuire, Patrick; von Peter, Goetz',
    year: '2020',
    accessedAt: '2026-09-17',
    title: 'Home sweet host: Prudential and monetary policy spillovers through global banks',
    publication: 'BIS Working Papers No 853',
    url: 'https://www.bis.org/publications/working-paper-853-home-sweet-host-prudential-and-monetary-policy-spillovers-through-global-banks.pdf',
    use: '支持home与host政策层可能通过全球银行产生不同溢出，并展示nationality×host维度的识别设计；结论依工具、样本与美元贷款设定，不是普遍方向或固定参数。',
  },
  {
    id: 10,
    authors: 'Cetorelli, Nicola; Goldberg, Linda S.',
    year: '2010',
    accessedAt: '2026-09-17',
    title: 'Global Banks and International Shock Transmission: Evidence from the Crisis',
    publication: 'Federal Reserve Bank of New York Staff Reports No 446',
    url: 'https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr446.pdf',
    use: '支持全球银行内部资本市场能够把冲击跨业务与地区传递、缓冲或迁移的历史证据；不说明内部支持无限、即时或对每个法律实体都可执行。',
  },
  {
    id: 11,
    authors: 'Cetorelli, Nicola; Goldberg, Linda S.',
    year: '2011, rev. 2012',
    accessedAt: '2026-09-17',
    title: 'Liquidity Management of U.S. Global Banks: Internal Capital Markets in the Great Recession',
    publication: 'Federal Reserve Bank of New York Staff Reports No 511',
    url: 'https://www.newyorkfed.org/medialibrary/media/research/staff_reports/sr511.pdf',
    use: '支持美国全球银行在危机中按实体与市场重新分配流动性的历史机制；不支持把样本中的平均反应当作今天任意银行的可用额度或现金流。',
  },
  {
    id: 12,
    authors: 'International Monetary Fund, Monetary and Capital Markets Department',
    year: '2015',
    accessedAt: '2026-09-17',
    title: 'International Banking after the Crisis: Increasingly Local and Safer?',
    publication: 'Global Financial Stability Report, April, Chapter 2',
    url: 'https://www.imf.org/-/media/websites/imf/imported-flagship-issues/external/pubs/ft/gfsr/2015/01/pdf/_c2pdf.pdf',
    use: '支持危机后直接跨境贷款回撤、当地附属机构贷款和银行间替代的历史结构变化；不支持未来必然继续本地化，也不证明当地模式在每次冲击中都更安全。',
  },
  {
    id: 13,
    authors: 'McGuire, Patrick; von Peter, Goetz',
    year: '2016',
    accessedAt: '2026-09-17',
    title: "The resilience of banks' international operations",
    publication: 'BIS Quarterly Review, March',
    url: 'https://www.bis.org/publications/qr-201603/resilience-banks-international-operations',
    use: '支持当地债权由当地资金支持与危机后收缩较小相关，非核心、跨境与外币融资依赖与更大收缩相关；观察性分解不建立跨时期普适的因果排序。',
  },
  {
    id: 14,
    authors: 'Peek, Joe; Rosengren, Eric S.',
    year: '1996',
    accessedAt: '2026-09-17',
    title: 'The International Transmission of Financial Shocks: The Case of Japan',
    publication: 'Federal Reserve Bank of Boston Working Paper No. 96-1',
    url: 'https://www.bostonfed.org/-/media/Documents/Workingpapers/PDF/wp96_1.pdf',
    use: '支持日本母行冲击与美国分支贷款之间的工作论文版本历史传导设计；样本、时期与房地产渠道特殊，不能外推为所有母国冲击的固定效应。期刊版本发表于American Economic Review 87(4), 1997。',
  },
  {
    id: 15,
    authors: 'Schnabl, Philipp',
    year: '2012',
    accessedAt: '2026-09-17',
    title: 'The International Transmission of Bank Liquidity Shocks: Evidence from an Emerging Market',
    publication: 'Journal of Finance 67(3)',
    url: 'https://doi.org/10.1111/j.1540-6261.2012.01737.x',
    use: '支持以秘鲁银行—企业关系区分外部银行流动性冲击与企业需求的识别思路；局部相对供给结果不自动给出企业总融资、投资或一般均衡。',
  },
  {
    id: 16,
    authors: 'Berrospide, Jose; Correa, Ricardo; Goldberg, Linda S.; Niepmann, Friederike',
    year: '2016',
    accessedAt: '2026-09-17',
    title: 'International Banking and Cross-Border Effects of Regulation: Lessons from the United States',
    publication: 'International Finance Discussion Papers No. 1180, Board of Governors of the Federal Reserve System',
    url: 'https://www.federalreserve.gov/econresdata/ifdp/2016/files/ifdp1180.pdf',
    use: '支持监管变化经银行组织形式和境外业务产生跨境反应的美国证据；不意味着任何监管收紧都必然降低国外总信用。',
  },
  {
    id: 17,
    authors: 'Emter, Lorenz; Schmitz, Martin; Tirpák, Marcel',
    year: '2018',
    accessedAt: '2026-09-17',
    title: 'Cross-border banking in the EU since the crisis: what is driving the great retrenchment?',
    publication: 'ECB Working Paper Series No 2130',
    url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2130.en.pdf',
    use: '支持欧盟危机后跨境银行回撤与银行、借款国和政策因素的历史分解；不支持把欧盟样本当作全球统一机制或实时状态。',
  },
  {
    id: 18,
    authors: 'Khwaja, Asim Ijaz; Mian, Atif',
    year: '2008',
    accessedAt: '2026-09-17',
    title: 'Tracing the Impact of Bank Liquidity Shocks: Evidence from an Emerging Market',
    publication: 'American Economic Review 98(4)',
    url: 'https://doi.org/10.1257/aer.98.4.1413',
    use: '支持同一借款人面对多家银行时分离银行供给与借款需求，以及检验替代的基本识别逻辑；该设计仍依其冲击、数据覆盖与可比贷款关系，不是聚合BIS数据的属性。',
  },
  {
    id: 19,
    authors: 'Chodorow-Reich, Gabriel',
    year: '2014',
    accessedAt: '2026-09-17',
    title: 'The Employment Effects of Credit Market Disruptions: Firm-level Evidence from the 2008–9 Financial Crisis',
    publication: 'Quarterly Journal of Economics 129(1)',
    url: 'https://doi.org/10.1093/qje/qjt031',
    use: '支持在观察关系银行暴露、替代融资和企业结果时研究信用冲击的实体效应；没有这些额外数据时，外国银行贷款下降不能被直接写成就业或投资下降。',
  },
  {
    id: 20,
    authors: 'Board of Governors of the Federal Reserve System',
    year: 'n.d.',
    accessedAt: '2026-09-17',
    title: 'Senior Loan Officer Opinion Survey on Bank Lending Practices',
    publication: 'Federal Reserve data and survey program',
    url: 'https://www.federalreserve.gov/data/sloos.htm',
    use: '支持把授信标准与贷款条款分开观察；历次问卷可覆盖审批标准、利差、额度、期限、抵押与契约等维度。它是银行层问卷证据，不等于申请级审批概率、单笔合同、实际成交或跨国因果效应。',
  },
  {
    id: 21,
    authors: 'European Central Bank',
    year: '2024',
    accessedAt: '2026-09-17',
    title: 'Bank lending survey for the euro area — The questionnaire, April 2024',
    publication: 'ECB Bank Lending Survey questionnaire',
    url: 'https://www.ecb.europa.eu/stats/ecb_surveys/bank_lending_survey/pdf/ecb.bls_questionnaire.en.pdf',
    use: '支持贷款标准、总体条款、利差、非利息费用、额度、期限、抵押和契约等问卷维度的正式定义；不直接观测单笔申请批准、提款、续作合同，也不把受访银行净比例变成企业级因果结果。',
  },
] satisfies readonly LessonReference[];

export type GlobalBanksSourceId = (typeof lesson406References)[number]['id'];

export const lesson406ReadingList = [
  { title: '先建立两台统计相机', scope: 'BIS 2019 §§1–2、4及BIS 2024 residence vs nationality', reason: '第一遍只追踪LBS与CBS的观察单位、合并规则和集团内头寸处理。', guide: '先读定义与图示，再拿同一笔贷款分别问“记在哪里”和“母行是谁”。', url: lesson406References[0].url, group: 'core', links: [{ label: '配对阅读：residence vs nationality', url: lesson406References[1].url }] },
  { title: '跨境路线、当地路线与信用口径', scope: 'BIS 2025全文，重点Box A', reason: '把direct、indirect、claims与credit分开，避免把外币、本地与跨境混为一谈。', guide: '重画本课C2，并写下每一项为何进入FC或IC。', url: lesson406References[3].url, group: 'core' },
  { title: '全球银行的地理组织', scope: 'BIS 2024 geography全文', reason: '把nationality、host、booking location、branch/subsidiary与融资结构连接。', guide: '关注组织形态为何改变冲击路径，而不是记住某年规模。', url: lesson406References[2].url, group: 'core' },
  { title: '法律实体与可转移性', scope: 'Basel LCR10.3–10.9与BCP home-host条款', reason: '理解合并流动性为何不等于任一实体可用现金。', guide: '把每个“应该监测”与“现实中已经binding”严格分开。', url: lesson406References[6].url, group: 'rules', links: [{ label: '配对阅读：Core Principles', url: lesson406References[7].url }] },
  { title: '内部资本市场的两篇经典研究', scope: 'FRBNY SR446 §§II–IV；SR511 §§1–2与结论', reason: '观察集团如何传递、吸收或迁移冲击，并学习其证据上限。', guide: '先画实体T-account，再读作者如何从数据识别重新配置。', url: lesson406References[9].url, group: 'models', links: [{ label: '配对阅读：SR511', url: lesson406References[10].url }] },
  { title: '从跨境银行到跨国本地银行', scope: 'IMF GFSR 2015 Chapter 2', reason: '理解危机后路线重构、当地附属机构与替代，而不是只看总跨境claims。', guide: '把历史描述、回归证据和政策判断分栏记录。', url: lesson406References[11].url, group: 'systems' },
  { title: '母行冲击如何进入东道国贷款', scope: 'Peek–Rosengren 1996 working paper（1997 AER journal version）；Schnabl 2012', reason: '比较两种经典识别：母行资产负债表冲击与同一借款人的多银行关系。', guide: '逐篇写出处理、对照、冲击时钟、需求控制、样本和不可外推之处。', url: lesson406References[13].url, group: 'evidence', links: [{ label: '配对阅读：Schnabl 2012', url: lesson406References[14].url }] },
  { title: 'Home、host与监管溢出', scope: 'BIS WP853；Fed IFDP1180', reason: '学习母国和东道国规则如何沿不同实体与路线产生替代或回撤。', guide: '不要只读系数；先确认政策工具、银行维度、借款地与货币。', url: lesson406References[8].url, group: 'rules', links: [{ label: '配对阅读：IFDP1180', url: lesson406References[15].url }] },
  { title: '从相对供给走向借款人总融资', scope: 'Khwaja–Mian 2008；Chodorow-Reich 2014', reason: '训练“银行A少贷”与“企业总融资/真实活动下降”之间需要哪些替代证据。', guide: '先复现borrower×time思路，再检查债券、其他银行和企业结果覆盖。', url: lesson406References[17].url, group: 'evidence', links: [{ label: '配对阅读：Chodorow-Reich 2014', url: lesson406References[18].url }] },
  { title: '把“银行收紧”拆成可观察条款', scope: 'Federal Reserve SLOOS；ECB Bank Lending Survey questionnaire', reason: '逐项核对标准、价格、额度、期限、抵押和契约哪些被问卷直接观察，哪些仍只是理想研究字段。', guide: '做一张term-by-term矩阵：survey observable、contract observable、application observable与当前unknown分栏。', url: lesson406References[19].url, group: 'evidence', links: [{ label: '配对阅读：ECB BLS questionnaire', url: lesson406References[20].url }] },
] satisfies readonly LessonReading[];

export const globalBanksEvidenceGroups = [
  { key: 'lens', title: '统计镜头与对象身份', supports: 'LBS/CBS、residence/nationality、合并与集团内头寸处理。', doesNotSupport: '不从聚合统计推出单家银行现金、意图或因果。', sourceIds: [1, 2, 5] as const },
  { key: 'route', title: '跨境与当地附属机构路线', supports: 'foreign claims、international claims、local claims与direct/indirect credit的覆盖。', doesNotSupport: '不把外币等同跨境，不把foreign-bank local lending误写为跨境。', sourceIds: [1, 3, 4, 12] as const },
  { key: 'entity', title: '实体、币种与可转移性', supports: '集团、实体、分行、子公司、显著币种及home/host转移限制。', doesNotSupport: '不证明任何特定银行的内部额度、批准或已结算现金。', sourceIds: [6, 7, 8] as const },
  { key: 'internal', title: '内部资本市场与重新配置', supports: '危机样本中全球银行跨实体和市场调配资金的机制。', doesNotSupport: '不把历史平均反应当实时额度或普适方向。', sourceIds: [10, 11, 13] as const },
  { key: 'policy', title: 'Home-host政策溢出', supports: '特定政策、样本与货币下的跨境贷款反应和路线替代。', doesNotSupport: '不声称所有监管收紧都减少东道国总信用。', sourceIds: [9, 16, 17] as const },
  { key: 'identification', title: '供给识别、贷款条款、替代与实体结果', supports: '母行冲击、同一借款人多银行关系、问卷可见条款、替代融资与真实结果的分层证据。', doesNotSupport: '问卷不等于单笔合同或申请记录；双边贷款下降也不能直接升级为总融资、投资或就业下降。', sourceIds: [14, 15, 18, 19, 20, 21] as const },
] as const;

export const globalBanksFailedSourceLedger = [
  { title: 'BIS reporting-guidelines legacy landing response', request: 'legacy URL saved as bis-2019-international-banking-statistics-guidelines.pdf', status: 'HTML response under a .pdf suffix', resolution: '原字节保留；正文改用经file/pdfinfo验证的62页current PDF，失败对象不算已读PDF。', sourceIds: [1] as const },
  { title: 'BIS WP853 legacy landing response', request: 'legacy URL saved as bis-wp853-home-sweet-host.pdf', status: 'HTML response under a .pdf suffix', resolution: '原字节保留；正文改用经验证的25页current PDF。', sourceIds: [9] as const },
  { title: 'BIS 2016 direct PDF legacy route', request: 'https://www.bis.org/publ/qtrpdf/r_qt1603g.pdf', status: 'curl recovered HTML rather than PDF', resolution: '本地对象保留但不当作PDF；正文只链接当前BIS文章页并明确未使用伪PDF页码。', sourceIds: [13] as const },
  { title: 'Basel Framework monolithic PDF path', request: 'https://www.bis.org/baselframework/BaselFramework.pdf', status: 'HTTP 404 on 2026-09-17', resolution: '保留失败记录；使用当前官方LCR与BCP HTML段落，不暗示已归档完整PDF。', sourceIds: [7, 8] as const },
] as const;
