import type { GlobalBanksSourceId } from './globalBanksReferences';

export type GlobalBanksCheck = {
  id: string;
  kind: 'M' | 'K';
  title: string;
  question: string;
  options: readonly [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
  answer: string;
  trap: string;
  sourceIds: readonly GlobalBanksSourceId[];
};

export type GlobalBanksResearchQuestion = {
  question: string;
  design: string;
  evidenceNeeded: string;
  whatWouldWeakenIt: string;
  reject: string;
  sourceIds: readonly GlobalBanksSourceId[];
};

export type GlobalBanksInterface = readonly [name: string, payload: string, guardrail: string];

export const globalBanksThesis = {
  centralQuestion: '一个发生在母国、核心货币融资环境或母行资产负债表上的冲击，如何穿过全球银行集团的合并约束、法律实体与内部资本市场，分别改变直接跨境贷款与境外分行／子公司的当地贷款供给；哪些条件会缓冲、阻断、迁移或反转这种传导？',
  statement: '全球银行不是一个可以无摩擦调度的统一钱包。冲击只有在集团与实体约束、已经由4.05判定的可执行内部转移状态、home／host规则、币种期限、贷款要约和借款人替代依次通过后，才会成为某一目的地的信贷供给变化；当地融资、实体资本、替代贷款人与政策支持可以切断它，集中损失、不可转移资源、外币错配和借款人违约则可能放大并把结果反馈给母行。',
  causalChain: 'home／parent shock → group shadow cost与binding-constraint candidates → entity／route loan-offer vector → borrower acceptance与financing substitution → total financing、activity与collateral → defaults、provisions与affiliate profit → subsidiary／parent capital与liquidity → next allocation round',
  boundaries: [
    '集团合并资源 ≠ 任一法律实体、币种与期限上的可执行资源',
    '银行国籍 ≠ 记账办事处居住地 ≠ 即时借款人居住地',
    '外国银行当地放贷 ≠ 直接跨境放贷；跨境 ≠ 外币',
    'LBS claims ≠ LBS credit ≠ loan origination ≠ commitment',
    'CBSG风险重分配 ≠ 原始借款人、记账地或现金路线迁移',
    '单一银行路线回撤 ≠ 借款人总融资收缩 ≠ 全球金融周期',
  ],
} as const;

export const globalBanksCoreRoute = [
  {
    time: '00–08分钟',
    title: '先画集团树，再给每一层实体命名',
    conceptIds: ['global-banks-mechanism-01', 'global-banks-mechanism-02'],
    task: '从parent group一路标到legal entity、branch／subsidiary与booking office，并分别填写母行国籍、记账地和即时借款人居住地。',
    exit: '能解释合并报表为何不是一只钱包，也不会用一个country字段覆盖三条地理轴。',
  },
  {
    time: '08–20分钟',
    title: '选择统计相机，并拆开两条贷款路线',
    conceptIds: ['global-banks-mechanism-03', 'global-banks-mechanism-04'],
    task: '对同一头寸分别写出LBS与CBS观察单位，再用booking office与即时借款人的居住地判断direct cross-border或local affiliate route。',
    exit: '能说明LBS与CBS为何都可能正确，并拒绝把外国银行、跨境和外币当成同义词。',
  },
  {
    time: '20–30分钟',
    title: '法律形态和工具口径分两道门处理',
    conceptIds: ['global-banks-mechanism-05', 'global-banks-mechanism-06'],
    task: '比较branch与subsidiary的责任、资本、流动性和home／host约束，再把LBS credit、claims及承诺分栏。',
    exit: '能给出法律形态排序反转的条件，并算清credit 70、claims 80、commitment 12为何不能相加。',
  },
  {
    time: '30–39分钟',
    title: '风险地址与现金路线分栏，再搭存量—流量桥',
    conceptIds: ['global-banks-mechanism-07', 'global-banks-mechanism-08'],
    task: '同时保存即时借款人与担保人，分开originationRoute和reportedLocationClass；随后把存量变化拆为交易、重估、核销、其他数量变化和断点。',
    exit: '知道CBSG能改风险归属却不能搬动原始现金路线，也不会把期末差额直接叫新增贷款。',
  },
  {
    time: '39–52分钟',
    title: '先给冲击办护照，再分清上游接口与本地情景合同',
    conceptIds: ['global-banks-mechanism-09', 'global-banks-mechanism-10'],
    task: '区分母行资本、核心币种融资、home政策、host损失与监管冲击；从4.05只导入五值status enum及可核验的时间格式、窗口、冲突和单cash-leg状态约束，provider／receiver／office／ID／金额／币种／value timestamp与zero/null映射全部由4.06本地情景合同声明。',
    exit: '不会用“风险厌恶”替代冲击身份，也不会在4.06重新判断内部资金路线是否可执行。',
  },
  {
    time: '52–64分钟',
    title: '把约束写进贷款要约，再观察跨目的地重配',
    conceptIds: ['global-banks-mechanism-11', 'global-banks-mechanism-12'],
    task: '分别记录价格、数量、期限、契约、抵押、续作和审批，并比较同一as-of与决策窗口下的目的地、行业、币种和产品配置。',
    exit: '能解释集团总量不变为何仍可发生当地急剧回撤，并且不把一次集团重配命名为全球金融周期。',
  },
  {
    time: '64–76分钟',
    title: '从单一路线退到借款人总融资',
    conceptIds: ['global-banks-mechanism-13'],
    task: '把受冲击路线、same-bank-other-route、其他外国银行、本地银行、债券／非银、贸易信用与内部现金逐栏登记；先报covered-bank，只有银行清单complete才报all-bank。',
    exit: '知道−20、−8与−3可以同时正确，但−8只有在银行渠道覆盖完整时才可称all-bank；未观察渠道保持unknown。',
  },
  {
    time: '76–88分钟',
    title: '用同一借款人—同期比较守住供给识别门',
    conceptIds: ['global-banks-mechanism-14'],
    task: '锁定事前银行暴露、事件时钟、共同借款人、对照银行与borrower×time固定效应，并列出预趋势、并购、政策预期和样本选择风险。',
    exit: '能把相对银行供给、借款人总融资、实体结果与一般均衡四个结论层级分开。',
  },
  {
    time: '88–90分钟',
    title: '给下游出口加类型，不在本课提前闭合系统',
    conceptIds: [],
    task: '把实体、路线、工具、币种、期限、冲击时钟、贷款要约与证据等级打包；分别注明4.07–4.09与7.10–7.16还要识别什么。',
    exit: '不会把bank-credit transmission candidate升级为common factor、脆弱性排名、政策最优或系统性传染。',
  },
  {
    time: '90–95分钟',
    title: '标注东道国—母行反馈候选，并做三道退出检查',
    conceptIds: ['global-banks-mechanism-15'],
    task: '按日内资金、季度贷款与多季度企业结果分时钟，把总融资→活动→违约／拨备→实体／母行资本→下一轮配置逐箭头标成supported、conceptual或unobserved。',
    exit: '能指出反馈在哪一环被替代或政策切断、当前证据最多支持到哪一环，并拒绝把跨样本片段拼成已观察闭环。',
  },
] as const;

export const globalBanksEntryVocabulary = [
  ['Global bank', '在多个法域通过母行、分行、子公司或其他办事处经营的银行集团；分析时仍须落到具体法人和office。'],
  ['Parent group', '最终控制下的集团层级，用于战略、合并与内部配置；不是所有实体可即时支取的共同账户。'],
  ['Bank nationality', '按最终控制母行归属形成的集团国籍轴；不同于办事处和借款人的居住地。'],
  ['Residence', '统计主体与某经济领土具有主要经济联系的归属；不是国籍、币种或付款路径。'],
  ['Legal entity', '依法持有资产、承担负债并接受资本、流动性和破产规则的主体。'],
  ['Booking office', '把头寸登记在账上的具体办事处；不必等于授信决策地、筹资地或风险最终归属地。'],
  ['Branch', '通常属于母行或另一银行法人本身的异地办事处，不是第二个独立法人。'],
  ['Subsidiary', '由母行控制但通常另行注册、拥有自身资本和治理的法人。'],
  ['Home jurisdiction', '母行及集团合并监管所在法域；不能替代host对当地实体或office的规则。'],
  ['Host jurisdiction', '分行、子公司或其他office经营所在法域；其规则可能限制当地资源的使用与转移。'],
  ['Cross-border claim', 'booking office与即时对手方居住地不同的债权；与银行国籍和贷款币种分别判断。'],
  ['Local claim', 'booking office与即时对手方位于同一经济体的债权；外资银行当地贷款仍可属于local。'],
  ['Origination route', '仅由booking office residence与即时借款人residence关系确定的crossBorder或local原始放贷路线。'],
  ['Reported location class', '在声明的CBSI或CBSG分配基础下得到的统计位置类别；风险重分配时可变，原始路线不随之变化。'],
  ['LBS', '按所在地、未合并记录银行办事处国际头寸的BIS统计；标准跨境口径保留与非居民related offices的集团内头寸，居民office之间国内头寸不在该跨境聚合。'],
  ['CBS', '标准基准按reporting-area母行国籍对全球业务合并，集团内部头寸在合并边界内抵销；standalone／unconsolidated例外须查reporting-population元数据。'],
  ['CBSI', 'consolidated banking statistics on an immediate-counterparty basis，按即时对手方分配债权。'],
  ['CBSG', 'consolidated banking statistics on a guarantor basis，按合格担保或信用保护重分配相关风险；历史上常称ultimate-risk basis。'],
  ['Foreign claims', '在同一CBSI借款国范围内，跨境债权加外国附属机构当地债权；不是所有外币债权。'],
  ['International claims', '在同一CBSI范围内，跨境债权加外国附属机构当地外币债权，不含当地本币当地债权。'],
  ['Intragroup position', '同一集团实体或office之间的债权或负债；是否进入LBS／CBS取决于跨境范围、reporting population与合并边界，不能写成无条件通则。'],
  ['Claim', '报告银行拥有的金融资产权利；覆盖取决于具体数据产品，不能自动等于贷款。'],
  ['Credit', '本课LBS口径下由loans/deposits与debt securities构成的信用小计；比LBS claims窄。'],
  ['Loan balance', '某时点仍未偿还的贷款存量；不同于申请、审批、承诺、提款和期间新增。'],
  ['Commitment', '银行在条件满足时允许未来提款的承诺额度；未提款部分不是当前贷款现金或LBS claims小计。'],
  ['Positive-market-value derivative', '对报告银行具有正公允价值的衍生品资产；不是名义本金，也不是同额贷款。'],
  ['Immediate counterparty', '当前合同债务人或直接借款人，是CBSI分配和原始路线判断的对手方。'],
  ['Guarantor', '在合格担保或保护安排下承担相关信用风险的主体；不是原始现金收款人。'],
  ['Risk transfer amount', '从即时对手方风险地图转向担保人风险地图的合格金额；必须保留合同、基础和as-of。'],
  ['Stock', '某个as-of时点的余额，不是一个窗口内发放、偿还或交易的数量。'],
  ['Gross origination', '窗口内新发放贷款的总额，尚未扣除偿还、出售或其他减少。'],
  ['Transaction flow', '窗口内因实际交易造成的变化；与汇率、价格、核销和报告断点分开。'],
  ['LBS adjusted change', 'BIS按其方法对LBS存量变化进行汇率与series-break调整后的近似变化，仍不等于纯新增贷款。'],
  ['Shock passport', '记录冲击来源、对象、币种、期限、事件时点、事前暴露与识别状态的最小身份。'],
  ['Upstream enum + local scenario contract', '4.05实际提供并被本课导入的是五值status enum与可核验时钟约束；provider、receiver、office、金额、币种、value timestamp、IDs、zero/null与容量映射属于4.06本地author-SYN合同，不能伪称上游字段级schema。'],
  ['Loan-offer vector', '银行给定借款人的利率、额度、审批、期限、抵押、契约、币种和续作条件集合。'],
  ['Cross-destination reallocation', '集团在国家、行业、币种或产品之间移动有限贷款预算；可在集团总量稳定时发生。'],
  ['Borrower substitution', '借款人转向其他银行、债券、非银、贸易信用或内部现金以替代受冲击路线。'],
  ['Borrower×time fixed effects', '在同一借款人同一时间内比较多家贷款人，用来吸收借款人共同需求与质量变化的设计工具。'],
  ['Relative credit-supply effect', '在特定识别假设下，同一借款人不同贷款人之间的相对供给反应；不是总融资或一般均衡效应。'],
  ['Evidence ceiling', '由数据、设计和版本决定的最高可声明结论等级；定义、描述、会计桥和因果识别彼此不能自动升级。'],
  ['Global financial cycle', '跨国家资产价格、资本流动与风险承担的共同因子或共振概念，归4.07；单个集团重配不能使用该标签。'],
  ['Null / partial', '关键身份或证据缺失时的专业输出；不等于经济零、无风险或没有传导。'],
  ['author-SYN', '作者构造、只用于教学的合成数据；它可以验证恒等式与边界，但不是现实银行观测、估计值或校准结果。'],
  ['M / K', 'M是机制辨析题（Mechanism），K是口径或计算题（Knowledge／calculation check）；两者都只检验本课学习目标。'],
  ['STOP', '由于身份、口径、单位或时钟不合格而有类型地拒绝计算；STOP不是经济值0，也不是“没有风险”。'],
  ['PIT', 'point-in-time：证明信息在历史决策时点已经可得的版本纪律；今天下载到的修订值不自动具有PIT资格。'],
  ['OOS', 'out-of-sample：在未参与设定、拟合或选择的样本外区间检验；页面算例与历史案例都不构成OOS。'],
  ['P1 / P2 / P3', '审稿严重度标签：P1为根本性阻断，P2为必须修正的实质问题，P3为较小问题；标为implementation required的P3也必须改正文。'],
  ['Sealed delta', '正文双审通过后，只允许审批元数据发生的最小变更；同两位审稿人还要确认这组变更没有偷改已批准内容。'],
  ['LCR', 'Liquidity Coverage Ratio，流动性覆盖率；集团指标不能自动代替某法律实体或显著币种的可执行流动性。'],
  ['Ring-fencing', 'host以法律、监管或内部治理方式隔离当地资本、流动性或资产，限制集团自由调拨。'],
  ['RWA', 'risk-weighted assets，风险加权资产；它是资本约束中的风险口径，不等于贷款面值或现金支出。'],
  ['PD / LGD', 'probability of default与loss given default，即违约概率与违约损失率；担保风险重分配不自动给出这两个参数。'],
  ['NBFI', 'non-bank financial institution，非银行金融机构；债券与NBFI融资是潜在替代渠道，不应与银行贷款静默合并。'],
] as const;

export const globalBanksChecks: readonly GlobalBanksCheck[] = [
  {
    id: 'M1',
    kind: 'M',
    title: '集团不是一只钱包',
    question: '母行合并报表显示流动性充足，但境外子公司仍缩减贷款，哪项解释最完整？',
    options: ['集团资源仍要通过法人、币种、home／host、内部限额与时间门，才能成为子公司可用资源', '集团级LCR足以证明每个子公司的同币种现金都可调用', '只要子公司缩贷，就可以据此反推出它已经资不抵债', '合并净额可按各实体资产占比直接分摊为可用现金'],
    correct: 0,
    answer: '合并层面的资源与实体可执行资源是不同对象；资本不足也不能仅靠集团内借款自动补成权益。',
    trap: '把会计合并与现金、资本或法律权利的实际迁移混为一谈。',
    sourceIds: [1, 6, 7, 8],
  },
  {
    id: 'K1',
    kind: 'K',
    title: '两台相机的C1桥',
    question: '同一SYN共同loans/deposits + debt-securities core内，X=80为对host外部跨境claims，G=40为对host附属机构的跨境intragroup claims，L=60为附属机构对host居民的当地外部claims。正确结果是哪项？',
    options: ['Comparable-core LBS跨境claims=80，CBSI foreign claims=100，因为G与L都只在各自镜头中出现一半', '两套共同核心结果取平均130，可以得到共同口径的集团暴露', 'Comparable-core LBS跨境claims=140，CBSI foreign claims=120，因为CBSI保留G而LBS纳入L', 'Comparable-core LBS跨境claims=120，CBSI foreign claims=140，二者差额=20'],
    correct: 3,
    answer: '在共同loans/deposits + debt-securities core与全部比较门一致时，LBS保留G，所以X+G=120；CBSI合并抵销G并纳入L，所以X+L=140；桥为L−G=20。',
    trap: '把不同观察单位的两个聚合量相加，或误以为CBSI“遗漏”了被合并的集团内头寸。',
    sourceIds: [1, 2, 5],
  },
  {
    id: 'M2',
    kind: 'M',
    title: '三条地理轴',
    question: '法国母行的英国分行向巴西公司发放美元贷款，哪组标签正确？',
    options: ['银行国籍法国、booking residence英国、借款人residence巴西，但美元币种使路线归美国', '银行国籍英国、booking residence英国、借款人residence巴西，因此路线由银行品牌决定', '银行国籍法国、booking residence英国、借款人residence巴西、originationRoute为cross-border', '银行国籍法国、booking residence巴西、借款人residence巴西，因此路线local'],
    correct: 2,
    answer: '国籍看最终控制母行，booking residence看记账office，路线看booking office与即时借款人的居住地；币种另列。',
    trap: '用美元计价、银行品牌或借款国中的任一字段覆盖其他地理轴。',
    sourceIds: [1, 2, 3],
  },
  {
    id: 'K2',
    kind: 'K',
    title: 'CBSI路线分解',
    question: '同一CBSI借款国范围内，XBC=40、LCFX=10、LCLC=50。Foreign claims与international claims分别是多少？',
    options: ['50与100，因为international claims包含当地本币而foreign claims不含', '90与50，因为foreign claims排除当地外币当地债权', '100与90，因为international claims只排除一部分当地本币债权', '100与50，因为foreign claims含三项而international claims只含XBC与LCFX'],
    correct: 3,
    answer: 'Foreign claims=40+10+50=100；international claims=40+10=50；当地本币50不是跨境，也不进入international claims。',
    trap: '把local-currency local claims当成跨境或外币债权，或者把公式移到CBSG口径。',
    sourceIds: [1, 3, 4],
  },
  {
    id: 'M3',
    kind: 'M',
    title: '法律形态没有固定排名',
    question: '关于branch与subsidiary，哪项说法符合本课边界？',
    options: ['分行与母行同属一法人，所以host层约束通常可以忽略', '法律形态改变约束作用点，但韧性方向取决于本地资金、资本、ring-fencing、币种、内部限额与冲击来源', '子公司单独资本化，所以母行冲击只会影响分行路线', '若两者在CBS中同属一个集团，法律责任和可转移性即可视为相同'],
    correct: 1,
    answer: 'branch通常不是独立法人，subsidiary通常是独立法人，但任一形态的贷款能力都由多项条件共同决定，排序可以反转。',
    trap: '把一个组织标签当成跨法域、跨冲击的固定韧性参数。',
    sourceIds: [3, 7, 8, 12, 13],
  },
  {
    id: 'K3',
    kind: 'K',
    title: 'LBS claims与credit',
    question: 'LBS loans/deposits=50、debt securities=20、正市值derivatives=6、other residual instruments=4、undrawn commitments=12。正确小计是哪项？',
    options: ['credit=50，claims=80，债务证券只进入claims', 'credit=70，claims=92，因为承诺属于当前金融资产', 'credit=70，claims=80，commitments 12单列', 'credit=80，claims=70，因为衍生品只改变credit'],
    correct: 2,
    answer: 'LBS credit=50+20=70；LBS claims=70+6+4=80；未提款承诺是LBS小计之外的潜在暴露比较项。',
    trap: '把承诺加入当前claims，或把这一LBS公式无条件搬到CBS。',
    sourceIds: [1, 4],
  },
  {
    id: 'M4',
    kind: 'M',
    title: '担保不搬现金路线',
    question: '巴西借款人从英国booking office借款，美国母公司提供合格担保。切换CBSI到CBSG后，什么可以改变？',
    options: ['原始借款人仍在巴西，但originationRoute随担保人改为英国到美国', 'reportedLocationClass与风险归属可按合格转移改变，但originationRoute仍由英国office与巴西借款人决定', 'booking office仍在英国，但CBSG会把现金收款人重写为美国母公司', '贷款币种是否为美元可以由CBSG风险地址推导'],
    correct: 1,
    answer: 'CBSG重分配的是报告风险，不改写合同借款人、记账office、币种或原始现金路线。',
    trap: '把风险地图的第二地址误认为现金最初流向。',
    sourceIds: [1, 2, 5],
  },
  {
    id: 'K4',
    kind: 'K',
    title: '存量下降不是自动缩贷',
    question: '一笔100欧元贷款没有发放、偿还或出售，但欧元相对报告货币贬值10%。报告存量约下降10时，最专业的结论是什么？',
    options: ['先把10记为净交易流，因为存量已真实下降', '将10视为借款人偿还，除非银行证明存在新发放', '把10当作CBS adjusted change，再用币种权重还原交易', '先记为FX valuation effect；没有交易桥不能称贷款供给流'],
    correct: 3,
    answer: '期末差额包含汇率重估；只有把交易、估值、核销、其他数量变化和断点分开后，才可讨论贷款行为。',
    trap: '把stock difference、BIS LBS adjusted change、gross origination与identified supply shock当成同一量。',
    sourceIds: [1, 2, 17],
  },
  {
    id: 'M5',
    kind: 'M',
    title: '4.05只通过枚举与时钟约束进入',
    question: '4.06收到一条内部支持记录status=quoted_only、amount=20。应怎样进入当前贷款资源？',
    options: ['不加入realised资源；保留导入的状态值，资格与结算仍属于4.05，而本课只按明确的4.06本地情景合同映射贷款容量', '将20列为当前现金但另加quoted折扣，避免完全忽略信息', '由4.06重新检查抵押品与结算，再决定是否把报价升级为可用', '把20作为子公司资本缓冲，因为报价来自母行'],
    correct: 0,
    answer: '4.06只消费canonical状态；quoted_only不是现金，realised cash也必须带不晚于as-of的value timestamp且避免与基线重复。',
    trap: '在本课重算4.05资金路线，或把意向、报价、现金和资本混在一起。',
    sourceIds: [6, 7, 10, 11],
  },
  {
    id: 'K5',
    kind: 'K',
    title: '稳定集团总量下的重配',
    question: '同一as-of与forward decision horizon，baseline为A40、B30、C20；counterfactual为A20、B50、C20。哪项正确？',
    options: ['集团净变化为0，因此A的局部变化在经济上可以忽略', 'A下降20、B上升20、集团预算仍为90；这是条件性重配场景', 'A下降20足以证明集团总量也收缩20，只是B的增长尚未结算', 'A与B反向变化说明共同全球因子已被识别'],
    correct: 1,
    answer: '两种互斥配置都合计90；A的−20与B的+20必须同时显示。场景不证明管理意图、因果或共同全球因子。',
    trap: '用集团总量遮蔽目的地变化，或把一个集团的配置选择升级为4.07的概念。',
    sourceIds: [3, 9, 12, 13, 17],
  },
  {
    id: 'M6',
    kind: 'M',
    title: '同一借款人识别的是局部相对供给',
    question: '对同一借款人同一时期，事前暴露于冲击的银行A比银行B更明显缩贷。borrower×time设计最多直接支持哪项？',
    options: ['在设计假设下，样本内银行A相对B的贷款供给反应不同', '该国企业结果的变化可以归因于银行A而无需替代融资数据', '样本内共同借款人的总融资与A的贷款同额下降', '处理银行的相对变化代表所有银行共同的全球因子'],
    correct: 0,
    answer: '共同借款人比较可以更接近局部相对供给；总融资还需覆盖其他银行、债券等替代，实体结果和一般均衡需要额外数据。',
    trap: '把局部相对系数外推成总信用、宏观结果或全球共同因子。',
    sourceIds: [14, 15, 18, 19],
  },
  {
    id: 'K6',
    kind: 'K',
    title: '路线回撤与总融资',
    question: '受冲击全球银行路线减少20，本地银行增加12，债券融资增加5。三个可观察口径分别是什么？',
    options: ['路线−3、covered-bank−3、all observed financing−3，因为可观察渠道应净额化后再分类', '路线−20、covered-bank−20、all observed financing−3，因为本地银行不属于替代银行渠道', '路线−20、已覆盖银行渠道−8、all observed financing−3；只有银行渠道覆盖完整时才能把−8称为all-bank', '路线−8、covered-bank−3、all observed financing+17，因为增加项应单独累计'],
    correct: 2,
    answer: '原路线为−20；加上已观察本地银行后covered-bank channels为−8；再加债券后all observed financing为−3。只有same-bank-other-route、其他外国银行和本地银行等银行渠道覆盖完整时，−8才可升级为all-bank；其他缺失渠道保持unknown。',
    trap: '只挑一个口径代表全部，或把未观察渠道默填为0。',
    sourceIds: [12, 15, 18, 19],
  },
];

const answerPositions = globalBanksChecks.map(check => check.correct);
const answerCounts = [0, 1, 2, 3].map(position => answerPositions.filter(value => value === position).length);
const exactPeriod = (period: 2 | 3 | 4) => answerPositions.every((value, index) => index < period || value === answerPositions[index - period]);
const moduloFour = (value: number) => ((value % 4) + 4) % 4;
const hasMonotoneFourCycle = answerPositions.some((_, start) => start <= answerPositions.length - 4 && [1, -1].some(step => {
  const first = answerPositions[start];
  return [0, 1, 2, 3].every(offset => answerPositions[start + offset] === moduloFour(first + step * offset));
}));

export const globalBanksAnswerOrderAudit = {
  sequence: answerPositions,
  expectedSequence: [0, 3, 2, 3, 1, 2, 1, 3, 0, 1, 0, 2] as const,
  counts: answerCounts,
  exactlyBalanced: answerCounts.every(count => count === 3),
  noExactPeriod234: !([2, 3, 4] as const).some(period => exactPeriod(period)),
  noMonotoneFourCycle: !hasMonotoneFourCycle,
} as const;

export const globalBanksUnderstandingQuestions = [
  '为“法国母行—英国分行—巴西借款人—美国担保人”的贷款填写最小position passport，并说明哪些字段不会因CBSI切换到CBSG而改变。',
  '用一个集团树解释parent group、legal entity、office、branch、subsidiary与booking office分别处于什么层级。',
  '构造一个集团流动性充足但当地子公司因资本约束而无法扩大贷款的反例，并解释内部借款为何不等于增资。',
  '把同一头寸分别放进LBS和CBS镜头，指出报告单位、合并方式、集团内头寸处理和最适研究问题。',
  '在共同loans/deposits + debt-securities core及nationality／host／CBSI／reporting population／valuation-sign／currency／sector／maturity／as-of／vintage／benchmark scope全部匹配后，手算C1的X=80、G=40、L=60；解释为什么120与140不能相加、也不能判断哪个更“真实”。',
  '手算C2的XBC=40、LCFX=10、LCLC=50；逐项说明foreign claims、international claims、cross-border和foreign-currency为什么不是同义词。',
  '给出一组条件使branch贷款容量高于subsidiary，再改变一个约束令排序反转；不要把差异归因于法律形态单因。',
  '手算C3的credit 70、claims 80与commitment 12，并说明正市值derivative与notional为何不同。',
  '画出即时借款人、担保人与银行三方关系；分别标CBSI、CBSG、riskTransferAmount、originationRoute和reportedLocationClass。',
  '为一个期末claims下降案例分解origination、repayment、sale、write-off、FX、price、reclassification与break，并把无法观测项留为unknown。',
  '解释BIS LBS adjusted change为何仍只是近似流量，以及为什么不能给CBS存量差贴同一标签。',
  '分别为母行资本损失、核心币种融资冲击、home政策、host资产质量冲击和host监管变化填写shock passport。',
  '把4.05的realised、committed_executable、quoted_only、unavailable与null接到4.06；说明每种状态能否进入当前base cash以及为什么本课不重新裁决。',
  '复核C4：共同抽象20如何分别映射到两个不同receiver/cash-leg IDs，并在各自互斥情景中只计一次；为何25与30之差不是法律形态因果效应。',
  '为同一借款人写一份loan-offer vector，至少包含price、quantity、approval、maturity、collateral、covenant、currency与renewal。',
  '复核C5的A40／B30／C20与A20／B50／C20，解释same asOf、same horizon、conservation与groupRetrenchment声明各守住什么边界。',
  '复核C6的−20、+12、+5：先报告bilateral route与covered-bank，再列same-bank-other-route、其他外国银行和本地银行是否complete；只有完整时才升级all-bank，并说明需求未知时为何只能写ACCOUNTING_ONLY。',
  '为同一借款人—多银行设计写出事前暴露、事件时钟、预趋势、固定效应、样本进入条件与至少三项竞争解释。',
  '把反馈候选按日内／日频资金、季度贷款与多季度企业结果分时钟，并逐箭头标出supported、conceptual或unobserved；指出替代、政策与稳定当地存款在哪一环切断传导。',
  '从4.07、4.08、4.09与7.10–7.16任选三个下游接口，写出可交付payload、仍需识别的对象和一句禁止越界的结论。',
] as const;

export const globalBanksPassportRules = [
  ['01 · parentGroupId', '最终控制集团的稳定ID；集团名称只能显示，不能替代ID或被当作可调用钱包。'],
  ['02 · parentBankNationality', '按最终控制者保存母行国籍；不得用booking location、借款国或币种推断。'],
  ['03 · reportingLegalEntityId', '真正持有、报告或承担该头寸的银行法人ID；缺失时不得分配资本、流动性或合同责任。'],
  ['04 · officeId', '法人内部具体记账办事处的稳定ID；同一法人不同office不可因品牌相同而合并。'],
  ['05 · officeType', '本课本地情景枚举只接受head_office、branch或subsidiary；branch通常是office，subsidiary通常是另一legal entity，officeType与legalEntityId必须并存。'],
  ['06 · bookingOfficeResidence', '按统计居住地规则保存记账office所在地；它决定原始路线的一端，不等于贷款决策地或资金来源地。'],
  ['07 · immediateCounterpartyResidence / sector', '同时保存即时借款人居住地与部门；这是原始路线和CBSI分配的对手方，未知不得由担保人补写。'],
  ['08 · guarantorResidence / sector', '无合格担保时为null；有担保时另存担保人居住地与部门，不覆盖即时借款人。'],
  ['09 · allocationBasis', '明确LBS、CBSI或CBSG；不同basis的数量不得静默join、相加或互换。'],
  ['10 · riskTransferAmount', '记录按声明规则转移到担保人基础的金额；无合同与规则桥时保持null，不能由两个总量残差反推。'],
  ['11 · originationRoute', '只比较bookingOfficeResidence与immediateCounterpartyResidence，得到crossBorder或local；切换CBSG不得改写。'],
  ['12 · reportedLocationClass', '在CBSI或CBSG分配对象下另行得到crossBorder／local或null；永远不覆盖originationRoute。'],
  ['13 · instrument', '区分loan/deposit、debt security、positive-MV derivative、other residual、commitment等；先读数据产品perimeter再汇总。'],
  ['14 · currency', '保存合同或报告所需币种；外币、跨境、foreign bank三种属性互不推断。'],
  ['15 · remainingMaturity', '从reference／as-of date到该claim最终合同约定付款日（final contractually scheduled payment）的剩余期间；nextScheduledPaymentDate、nextResetDate与upstreamValueTimestamp必须另列，不得复用本字段。'],
  ['16 · stock / flow basis', '明确end stock、gross origination、transaction flow、net flow、author bridge或LBS adjusted change；不同basis不得共用flow标签。'],
  ['17 · asOf / vintage', '保存完整参考时点、数据下载／发布版本和方法状态；今天看到的修订值不能冒充历史PIT。'],
  ['18 · statistical lens / reporting unit', '写清报告单位、合并范围、intragroup treatment与覆盖；缺镜头护照时不解释LBS/CBS差额。'],
  ['19 · unit / valuation basis', '金额、币种、面值／市值、正市值／notional及符号规则必须显式；单位不相容时STOP。'],
  ['20 · break / reclassification flags', '并购、实体重组、方法变化、系列断点与重分类单列；不得把它们塞进经济交易。'],
  ['21 · shock identity / clock', '记录shockType、affected entity、币种、期限、announcement、effective time、事前暴露与识别状态；结果不得反向生成冲击。'],
  ['22 · 4.06-local scenario identity', 'provider／receiver legalEntityId、officeId、officeType、transactionId、cashLegId、amount、currency和valueTimestamp均由406-c4-local-scenario-v1声明，不是4.05现有字段级schema；branch可同法人不同office，subsidiary须为不同法人，两个互斥情景使用不同receiver与cash-leg IDs。'],
  ['23 · imported status + local treatment', '只从4.05导入realised、committed_executable、quoted_only、unavailable、null五值枚举及可核验时钟约束；realised／committed时序谓词与quoted／unavailable已知0、null STOP、各自base排除各自cash leg的容量映射均由4.06本地合同明确，不能反向宣称为4.05通用语义。'],
  ['24 · loan-offer vector', '同一borrower、product、currency、maturity与decision time下分别保存price、quantity、approval、collateral、covenant、renewal和其他non-price terms。'],
  ['25 · allocation dimensions', '目的地、sector、currency、product和business line各有稳定ID；同一group total下的互相抵销仍要保留。'],
  ['26 · borrower financing coverage', '列明shocked route、same-bank-other-route、other-foreign-bank、domestic-bank、bonds/NBFI、trade credit与internal cash；只有银行渠道清单complete时才称all-bank，其他情况只报covered-bank并把缺失项留为unknown。'],
  ['27 · evidence state / ceiling', '对definition、SYN、observed、PIT、accounting-only、identified-local、OOS与production逐项登记；页面计算或来源权威性不自动升级等级。'],
  ['28 · null / partial reason', '缺少必要身份、口径或桥接证据时输出null或partial并给理由；不得继承旧值、静默填0或用最近可得记录代替。'],
] as const;

export const globalBanksEvidenceBoundaries = [
  '官方BIS定义能够确定LBS、CBSI、CBSG、工具范围、居住地与合并规则“是什么”，不能说明某个数量“为什么变化”，更不能替单家银行识别意图或约束。',
  'BIS聚合存量和LBS adjusted change只在各自产品、覆盖、as-of与vintage内描述暴露；它们不是贷款申请、审批、承诺、提款、gross origination或已识别供给冲击。',
  'Basel LCR与Core Principles支持实体、显著币种、home／host和转移限制需要被监测；原则性标准不证明具体法域规则一致，也不证明某家银行某日的限制binding。',
  '历史论文只支持其样本、时期、冲击、对照与结果变量；1990年代日本银行、全球金融危机、秘鲁或欧盟样本的系数都不是今天任意银行的结构参数。',
  '六个author-SYN实验只验证定义、恒等式、边界、STOP和条件方向；它们没有现实银行输入，不证明当前规模、因果、预测、收益、交易、政策或生产资格。',
  'Observed、PIT、identified causal、OOS、forecast与production是独立证据状态；当前官网下载、教材双审、构建通过或页面交互都不能代替历史时点版本和样本外验证。',
  '同一借款人的多银行比较最多在假设成立时识别局部相对供给；借款人总融资、投资、就业、一般均衡和福利结论需要替代融资及相应结果数据。',
  '4.06只输出类型化bank-credit transmission candidate；它不重做4.05资金路线，不把集团重配叫global financial cycle，也不提前给4.08脆弱性、4.09政策自主或第七章系统性结论。',
] as const;

export const globalBanksResearchQuestions: readonly GlobalBanksResearchQuestion[] = [
  {
    question: '母行资本损失是否使事前更依赖该母行的境外office相对收紧贷款要约？',
    design: '在冲击前冻结母行损失暴露和office关系，比较同一host、行业、币种与borrower-time中的贷款人反应，分开branch与subsidiary并检查预趋势。',
    evidenceNeeded: '母行资本损失时钟、实体树、事前所有权与内部关系、贷款申请／审批／条款、共同借款人和同期政策记录。',
    whatWouldWeakenIt: '处理组在冲击前已差异趋势，结果由借款人构成或并购驱动，或共同借款人内相对反应消失。',
    reject: '用母行股价下跌与国别总贷款同期下降直接声称资本渠道。',
    sourceIds: [10, 14, 15, 18],
  },
  {
    question: '当地稳定融资占比能否缓冲母行或核心币种融资冲击对local-affiliate lending的传导？',
    design: '锁定冲击前local funding share、法律实体与币种，在相同host和借款人需求控制下估计异质反应，并允许冲击来源与法律形态交互。',
    evidenceNeeded: '实体级负债结构、币种期限、typed upstream state、当地贷款要约与home／host限制。',
    whatWouldWeakenIt: 'local funding share由预期冲击内生调整、与借款人质量不可分，或不同定义下结果不稳健。',
    reject: '从聚合当地存款多直接推出所有外国附属机构更安全。',
    sourceIds: [3, 6, 11, 12, 13],
  },
  {
    question: '同一冲击下，branch与subsidiary的贷款调整差异由哪些实体约束而不是法律标签本身解释？',
    design: '匹配home、host、business mix、local funding、capital、currency和borrower composition，逐项加入可转移性及当地约束，报告条件效应而非统一排序。',
    evidenceNeeded: 'office与legal-entity mapping、当地资本和流动性、ring-fencing、内部限额、贷款合同与冲击时钟。',
    whatWouldWeakenIt: '实体字段缺失、组织形式在冲击前因预期而改变，或结论只在一个法域标签上成立。',
    reject: '预设branch一定灵活或subsidiary一定稳健。',
    sourceIds: [3, 7, 8, 12, 16],
  },
  {
    question: 'CBSI到CBSG的风险重分配能否预测随后跨借款国同步收紧，而不改变原始现金路线？',
    design: '同时保存即时借款人与担保人网络，用事前共同担保暴露和担保人冲击检验贷款要约；originationRoute固定，reportedLocationClass另行更新。',
    evidenceNeeded: '贷款级借款人、担保合同、riskTransferAmount、CBSI/CBSG桥、担保人冲击和贷款条款。',
    whatWouldWeakenIt: '担保不可执行、风险转移字段不完整，或结果只来自同一借款人行业冲击。',
    reject: '把CBSG国别变化解释成现金跨境流向改变。',
    sourceIds: [1, 2, 5],
  },
  {
    question: 'LBS adjusted decline中有多少可由真实贷款交易解释，而非FX、价格、核销、出售或报告断点？',
    design: '先按BIS方法保留adjusted change，再以贷款级发放、偿还、出售、核销与估值逐项桥接；剩余项保持unexplained。',
    evidenceNeeded: '同一vintage的LBS元数据、币种构成、series breaks、贷款级交易与会计调整。',
    whatWouldWeakenIt: '工具或覆盖无法匹配、break无法复原，或贷款交易只覆盖少数报告者。',
    reject: '把CBS原始存量差或LBS adjusted change直接命名为gross origination。',
    sourceIds: [1, 2, 17],
  },
  {
    question: '4.05已realised的内部资金是否仅在流动性而非资本约束binding的实体扩大边际贷款要约？',
    design: '只导入4.05五值status enum与可核验时钟约束；provider／receiver／office／IDs、金额、币种、value timestamp、zero/null与贷款容量映射由4.06本地研究合同声明。按事前资本、流动性、风险和集中度约束分组，每个互斥情景的基线显式排除各自cash leg以防双计。',
    evidenceNeeded: '本地情景声明的provider／receiver／cash-leg IDs、导入的status值、value timestamp、实体资本和流动性、风险限额及贷款要约；若未来接真实4.05记录，须另有字段级版本契约。',
    whatWouldWeakenIt: '上游状态无法审计、cash leg已含在基线、约束状态由事后贷款结果定义，或只有余额没有要约。',
    reject: '在4.06重新计算transfer eligibility，或把quoted_only当realised cash。',
    sourceIds: [6, 7, 10, 11],
  },
  {
    question: '集团总loan-book budget稳定时，哪些事前特征预测目的地、行业、币种与产品间的重配？',
    design: '固定同一asOf和forward horizon，分解conserved reallocation与declared group retrenchment，使用冲击前关系价值、local funding、risk weight和退出成本。',
    evidenceNeeded: '实体级多目的地配置、共同币种与工具、同窗口baseline／counterfactual或观察到的决策记录，以及集团总量桥。',
    whatWouldWeakenIt: '总量口径不守恒、目的地ID变化、资产出售与自然到期混合，或所谓事前特征含未来信息。',
    reject: '看到A降B升就声称管理意图或global financial cycle。',
    sourceIds: [3, 9, 12, 13, 17],
  },
  {
    question: '全球银行路线回撤后，借款人替代为何在不同规模、透明度与关系强度的企业间不同？',
    design: '在借款人层面联合观察原路线、其他银行、债券／非银、贸易信用与内部现金，预先定义覆盖率并比较价格和非价格条款。',
    evidenceNeeded: '全银行贷款登记、债券发行、贸易信用、现金流、企业特征和同窗贷款要约。',
    whatWouldWeakenIt: '替代渠道仅覆盖大企业、未观察渠道被填0，或需求下降同时解释所有融资变化。',
    reject: '用一家银行少贷的数值直接代表企业总融资缺口。',
    sourceIds: [12, 15, 18, 19],
  },
  {
    question: 'home与host政策变化如何分别影响direct cross-border与local-affiliate loan-offer vectors？',
    design: '用政策生效时钟与事前home／host暴露构造差异，保持nationality、booking residence、borrower residence与originationRoute，检验路线替代而非只看总claims。',
    evidenceNeeded: '政策原文与生效日期、银行组织地图、路线与币种贷款条款、共同借款人和同期宏观政策。',
    whatWouldWeakenIt: '政策被充分预期、与其他规则同步、银行改变法律实体或样本构成，或跨路线口径不可比。',
    reject: '把监管收紧统一解释为host总信用下降。',
    sourceIds: [8, 9, 16, 17],
  },
  {
    question: '哪一组可观察链条足以把局部贷款供给冲击连接到企业活动、违约、附属机构利润和母行下一轮配置？',
    design: '分开短期相对供给、中期总融资与长期反馈窗口；用替代融资、企业结果、贷款表现、拨备、利润和资本形成逐段可失败的中介检验。',
    evidenceNeeded: '贷款关系、全部融资、企业投资／就业／现金流、抵押价值、违约、拨备、附属机构利润和集团配置。',
    whatWouldWeakenIt: '替代完全切断融资缺口、企业结果在冲击前已恶化、政策同时补足，或时间顺序与反馈方向不一致。',
    reject: '仅凭外国银行claims下降就声称就业下降、母行损失或跨国传染。',
    sourceIds: [12, 14, 18, 19],
  },
];

export const globalBanksInterfaces: readonly GlobalBanksInterface[] = [
  ['4.07 Global Financial Cycle', '交付parentBankNationality、bookingOfficeResidence、reportingLegalEntityId、officeType、immediateCounterpartyResidence、originationRoute、reportedLocationClass、instrument、currency、remainingMaturity、shockClock、asOf／vintage、loan price／quantity／terms、response和evidence ceiling。', '这只是类型化bank-credit transmission candidate；不得称为common factor、risk-on／risk-off状态或global financial cycle。'],
  ['4.08 Emerging Markets', '交付目的地对外国银行的依赖、direct-cross-border／local-affiliate构成、贷款人集中度、币种、期限、行业、替代融资覆盖和已观察贷款反应。', '不得从“新兴市场”或外国银行标签直接推出脆弱性排名、资本流危机或总信用结果。'],
  ['4.09 Policy Autonomy / Capital Controls', '交付branch／subsidiary形态、当地融资占比、上游transfer status、home／host约束身份、贷款币种和外部银行依赖。', '不估计货币自主、资本管制有效性、最优制度或福利；这些需要独立政策与反事实识别。'],
  ['7.10 Cross-asset Coupling', '交付按目的地、币种、工具和资产暴露分型的bank-credit state，以及明确的冲击与贷款时钟。', '单一信贷边不能推出跨资产相关、共振方向或状态切换。'],
  ['7.11 Liquidity Spiral', '交付上游funding constraint如何进入loan adjustment以及可能的loan-sale／asset-action candidate。', '4.05仍拥有cash need、margin、haircut与route settlement；没有价格—抵押—融资回路证据时不得闭合流动性螺旋。'],
  ['7.12 Leverage Cycle', '交付parent／affiliate capital、leverage、risk-weight与loan-book adjustment candidates。', '资本或贷款变化不自动构成杠杆周期，更不能把现金约束、风险意愿和资本约束压成一个状态。'],
  ['7.13 Fire Sales', '交付constrained lending、loan-sale或asset-sale candidate、borrower substitution和loss feedback。', '没有观察到的出售、有限市场深度与price impact时，不得声称fire sale。'],
  ['7.14 Systemic Fragility', '交付共同母行、贷款人、目的地、币种、行业与担保人couplings及各边的证据身份。', '集中度、网络密度或共同标签本身不是系统性脆弱性；必须证明冲击传播与缓冲失败。'],
  ['7.15 Early Warning', '交付期限缩短、审批下降、条款收紧、集团内反转、LBS adjusted decline、贷款人集中与替代恶化等研究候选。', '没有PIT版本、预注册阈值、基线与OOS验证时，不得发布通用预警阈值或预测资格。'],
  ['7.16 Financial Networks', '交付ownership、intragroup funding、cross-border claim、local claim、guarantee、commitment与credit等不同typed edges。', 'payment、funding、credit、guarantee、commitment与ownership边绝不折叠为一种网络关系。'],
];

export const globalBanksInvariants = [
  '全球银行集团不是一只钱包；合并抵销不产生实体可用现金、资本或法律权限。',
  'parent group、reporting legal entity、office与business line分别建模；同名品牌不能替代稳定ID。',
  'branch是法人office维度，subsidiary通常是另一legal entity；officeType与reportingLegalEntityId不得互相覆盖。',
  'bank nationality、booking-office residence与immediate-counterparty residence始终保留为三条独立地理轴。',
  'residence不是nationality、币种、开户地或支付路径；任一字段不得由另一字段推断。',
  'originationRoute只由bookingOfficeResidence与immediateCounterpartyResidence比较得到。',
  'foreign bank、foreign claim、foreign-currency loan与cross-border claim不得作同义词。',
  'local claim可以由外国银行附属机构发放，也可以是外币；local不等于本国银行或本币。',
  '在本课benchmark中，跨境LBS按所在地、未合并，并保留与非居民related offices的跨境intragroup；standard reporting-area CBS按母行国籍全球合并并在合并边界内抵销intragroup。具体产品、reporting population及standalone／unconsolidated例外必须读取元数据，不能由LBS／CBS标签推断。',
  'LBS与CBS是不同统计镜头；未匹配reporting unit、consolidation、instrument、counterparty、currency、time与vintage时不得比较，更不得相加。',
  'C1只使用 precisely named Comparable-core LBS cross-border claims into host 与 Comparable-core CBSI foreign claims on host；X／G／L都只含loans/deposits + debt securities共同核心，二者都不是各自系统完整总量。',
  'C1中LBS=X+G，CBSI=X+L，桥为L−G；公式只对冻结且一致的nationality、host、CBSI、reporting population、valuation/sign、currency、external sector、maturity、as-of、vintage与benchmark reporting scope教学范围成立。',
  'ForeignClaims=XBC+LCFX+LCLC与InternationalClaims=XBC+LCFX只在同一外国借款国、同一CBSI合并范围内使用。',
  'C2不接受CBSG；CBSG风险重分配不得改写XBC、LCFX、LCLC的原始放贷路线。',
  'Claim、credit、loan、application、approval、commitment、drawdown、origination、balance、guarantee与payment均为不同对象。',
  'LBS credit只在本课声明口径下包含loans/deposits与debt securities；LBS claims另含正市值derivatives与other residual instruments。',
  'positive-market-value derivative不是derivative notional；undrawn commitment不进入C3的LBS claims或credit小计。',
  'LBS claims公式不得复制到CBS；CBS claims排除derivatives并把derivatives、guarantees与commitments放在其他暴露类别。',
  '即时借款人与担保人必须同时保存；CBSG分配不能删除或改写immediate counterparty。',
  'CBSG可改变reportedLocationClass与报告风险地图，不能改变booking office、originationRoute、币种或原始现金收款人。',
  'riskTransferAmount缺合同与统计规则桥时为null，不以CBSI和CBSG聚合差额倒推。',
  'stock、gross origination、transaction flow、net flow与adjusted change分别命名；期末减期初绝不自动称为新增贷款。',
  '一般stock-flow bridge必须显式列出transactions、FX valuation、price valuation、write-offs／other volume changes与breaks／reclassifications，并声明各项符号。',
  'BIS LBS adjusted change只是经汇率与series-break调整后的近似变化，仍可能含其他估值或write-down影响。',
  'CBS因所需币种构成不足不使用同一BIS adjusted-change标签；不得自行制造CBS adjusted flow。',
  'shock必须先于结果定义并保存对象、币种、期限、事前暴露、announcement与effective clock；不得用贷款下降反推冲击。',
  '母行资本、核心币种融资、home政策、host资产质量与监管冲击不得压成一个risk-aversion变量。',
  '4.06从4.05只导入五值status enum及时间格式、窗口、冲突和单cash-leg状态约束，不消费不存在的字段级transfer schema，也不重新判断transfer eligibility、抵押、法律门、承诺或settlement。',
  'upstream status只允许realised、committed_executable、quoted_only、unavailable或null；provider／receiver／office／IDs、金额、币种与value timestamp由406-c4-local-scenario-v1单独声明。',
  '在4.06本地C4合同中，只有value timestamp不晚于as-of的realised情景贡献可进入当前资源；每个互斥情景的基线必须排除各自scenario cash leg以防双计。',
  '在4.06本地C4合同中，committed_executable保持未来时点的prospective contribution；quoted_only与unavailable为该fixture中的known-zero/base-only映射，null为unknown／STOP；这些处理不得外推为4.05通用字段语义。',
  '内部转移现金不是权益；流动性缓解不能自动解除资本、风险、集中度或当地监管约束。',
  'loan offer是price、quantity、approval、maturity、collateral、covenant、currency与renewal向量；贷款余额不能替代整个向量。',
  '报价不等于审批，审批不等于commitment，commitment不等于drawdown，drawdown不等于期末balance。',
  '集团总资产或loan-book budget稳定可以与目的地急剧回撤并存；目的地变化不得被净额总量隐藏。',
  'C5 baseline与counterfactual必须共享asOf、forward horizon、currency、instrument和唯一destination IDs；它们不是t0／t1观察存量。',
  'C5只有在明确groupRetrenchment时允许counterfactual总量低于baseline，并分别报告reallocation与group shrinkage。',
  '一个集团的跨目的地重配不是global financial cycle；4.07拥有共同因子与risk-on／risk-off共振的命名权。',
  '单一贷款人或路线回撤不等于all-bank credit下降，更不等于borrower total financing或real activity下降。',
  'C6必须同时显示shocked route、covered-bank与all-observed-financing；只有same-bank-other-route、other-foreign-bank、domestic-bank等银行渠道清单complete时才可额外显示all-bank，其他未观察渠道保持unknown。',
  '需求未被固定或识别时，替代恒等式只标ACCOUNTING_ONLY，不能声称identified supply effect。',
  'borrower×time fixed effects只在共同借款人、多银行关系与事前冲击暴露等假设成立时识别局部相对供给。',
  '局部相对供给系数不是总融资、实体结果、宏观乘数、福利或一般均衡参数。',
  '预趋势、anticipation、并购、实体重组、同时发生的需求与政策、样本选择和外部效度必须显式检查。',
  '日内／日频资金动作、季度贷款调整与多季度企业结果使用不同时间钟；不得用同一期相关闭合反馈。',
  '反馈候选顺序必须保留loan offer、borrower acceptance、substitution、total financing、activity／collateral、defaults／provisions、affiliate profit与parent state；每条箭头须独立标注supported、conceptual或unobserved。',
  '当地存款、实体资本、替代融资与政策支持可能形成负反馈；共同损失、集中母行暴露、transfer restriction和外币错配可能放大，但方向不预设。',
  '缺少必要identity key、unit、basis、asOf或vintage时输出partial／null／STOP，绝不静默补0或继承旧结果。',
  '六个author-SYN fixtures相互独立，不读取彼此状态，也不读取4.05任何SYN数值；数值只验证恒等式与条件机制。',
  '官方定义、历史研究、SYN、observed、PIT、identified causal、OOS、forecast与production状态逐项独立。',
  '课程不硬编码当前BIS聚合数值；动态门户存在不等于已加载、冻结或验证当前快照。',
  '教材审阅、TypeScript构建、浏览器、打印和PDF检查只能证明有限内容与呈现合同，不证明现实因果、预测或生产资格。',
  '本课不提供银行个体诊断、监管合规、资本配置、国家脆弱性、投资、交易或政策处方。',
] as const;
