import type { LessonReading, LessonReference } from './types';

export const lesson407References = [
  {
    id: 1,
    authors: 'Miranda-Agrippino, Silvia; Rey, Hélène',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'The Global Financial Cycle',
    publication: 'Handbook of International Economics, Volume 6, Chapter 1; CEPR Discussion Paper 16580',
    url: 'https://cepr.org/publications/dp16580',
    use: '支持把全球金融周期表述为资产价格、资本流、风险承担和金融体系流动性的共同运动，并综述多类中心货币政策冲击；不支持把所有共同运动归结为单一美国利率、单一VIX或恒定跨国系数。',
  },
  {
    id: 2,
    authors: 'Miranda-Agrippino, Silvia; Rey, Hélène',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'U.S. Monetary Policy and the Global Financial Cycle',
    publication: 'Review of Economic Studies 87(6), 2754–2776',
    url: 'https://doi.org/10.1093/restud/rdaa019',
    use: '支持以动态因子模型从全球风险资产价格中提取共同因子，以及其样本中美国货币紧缩后风险资产、全球中介杠杆与信用收缩的识别结果；不支持把该因子当可直接交易的观测价格，也不证明每次risk-off都由Fed意外紧缩触发。',
  },
  {
    id: 3,
    authors: 'Rey, Hélène',
    year: '2015, revised 2018',
    accessedAt: '2026-09-22',
    title: 'Dilemma not Trilemma: The Global Financial Cycle and Monetary Policy Independence',
    publication: 'NBER Working Paper 21162; Jackson Hole symposium paper',
    url: 'https://doi.org/10.3386/w21162',
    use: '支持“全球周期会约束开放经济体金融条件”和dilemma命题的经典提出，并把中心货币政策、银行杠杆、资本流与信用联系起来；这是需要检验和辩论的研究命题，不是“浮动汇率完全无用”或“各国没有任何政策自主性”的定义性结论。',
  },
  {
    id: 4,
    authors: 'Cerutti, Eugenio M.; Claessens, Stijn; Rose, Andrew K.',
    year: '2017',
    accessedAt: '2026-09-22',
    title: 'How Important is the Global Financial Cycle? Evidence from Capital Flows',
    publication: 'BIS Working Papers No 661; IMF Working Paper 17/193',
    url: 'https://www.bis.org/publications/working-paper-661-how-important-global-financial-cycle-evidence-capital-flows',
    use: '支持关键反证：在其85国、1990–2015、按方向和类型拆分的季度资本流样本中，中心变量与共同因子合计通常解释不到四分之一变异；不否认全球因子对资产价格、信用或压力期可能重要，也不把低平均解释度等同于零尾部风险。',
  },
  {
    id: 5,
    authors: 'Jordà, Òscar; Schularick, Moritz; Taylor, Alan M.; Ward, Felix',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Global Financial Cycles and Risk Premiums',
    publication: 'IMF Economic Review 67(1), 109–150',
    url: 'https://doi.org/10.1057/s41308-019-00077-1',
    use: '支持长期历史样本中全球资产同步主要与风险溢价而非无风险利率或现金流同步相关，以及浮动汇率下效应较弱但不消失的结果；不把历史平均分解外推为实时因果归因。',
  },
  {
    id: 6,
    authors: 'Aldasoro, Iñaki; Avdjiev, Stefan; Borio, Claudio; Disyatat, Piti',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'Global and Domestic Financial Cycles: Variations on a Theme',
    publication: 'BIS Working Papers No 864',
    url: 'https://www.bis.org/publications/working-paper-864-global-and-domestic-financial-cycles-variations-theme',
    use: '支持区分以全球资产价格/资本流为核心的较短GFCy与以国内信用/房地产为核心的较长国内金融周期，并说明两者可能异步、危机时更易汇合；不支持用同一滤波窗口或同一相位标签替代二者。',
  },
  {
    id: 7,
    authors: 'Cboe Global Indices',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Cboe® Volatility Index',
    publication: 'Cboe VIX Index calculation methodology, last revised 26 July 2019',
    url: 'https://cdn.cboe.com/resources/vix/VIX_Methodology.pdf',
    use: '支持VIX由实时SPX期权买卖中间报价构造、表示S&P 500未来恒定30个日历日预期波动率并按年化表达；不支持把VIX定义为全球风险偏好、结构冲击、全球金融周期或所有资产的共同因子。',
  },
  {
    id: 8,
    authors: 'Bruno, Valentina; Shin, Hyun Song',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'Cross-Border Banking and Global Liquidity',
    publication: 'Review of Economic Studies 82(2), 535–564',
    url: 'https://doi.org/10.1093/restud/rdu042',
    use: '支持全球银行与当地银行互动、杠杆周期以及本币升值—银行杠杆—跨境银行流的模型和46国面板证据；不支持把汇率方向当机械因果开关，亦不覆盖所有非银和证券组合渠道。',
  },
  {
    id: 9,
    authors: 'Avdjiev, Stefan; Bruno, Valentina; Koch, Catherine; Shin, Hyun Song',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'The Dollar Exchange Rate as a Global Risk Factor: Evidence from Investment',
    publication: 'IMF Economic Review 67(1), 151–173; BIS Working Paper 695',
    url: 'https://www.bis.org/publications/working-paper-695-dollar-exchange-rate-global-risk-factor-evidence-investment',
    use: '支持美元强弱、美元跨境银行信用与新兴市场投资之间的经验关联及金融渠道解释；不支持用美元指数单独识别风险承担因果，也不意味着美元升值对所有主体方向相同。',
  },
  {
    id: 10,
    authors: 'Boehm, Christoph E.; Kroner, T. Niklas',
    year: '2023',
    accessedAt: '2026-09-22',
    title: 'The US, Economic News, and the Global Financial Cycle',
    publication: 'Federal Reserve Board International Finance Discussion Papers 1371',
    url: 'https://doi.org/10.17016/IFDP.2023.1371',
    use: '支持在美国宏观数据发布时间窗内，27国股指、VIX和商品价格同步跳动的高频事件证据，并区分系统性政策反应与直接风险承载渠道；事件研究结论依识别窗口和排除限制，不穷尽季度或危机期全部来源。',
  },
  {
    id: 11,
    authors: 'Forbes, Kristin J.; Warnock, Francis E.',
    year: '2012',
    accessedAt: '2026-09-22',
    title: 'Capital Flow Waves: Surges, Stops, Flight, and Retrenchment',
    publication: 'Journal of International Economics 88(2), 235–251; NBER Working Paper 17351',
    url: 'https://doi.org/10.3386/w17351',
    use: '支持必须分开非居民驱动的surge/stop与居民驱动的flight/retrenchment，并显示全球风险与极端资本流事件相关；论文明确不把关联升级为结构因果，净流量也不能替代四种gross-flow行为。',
  },
  {
    id: 12,
    authors: 'Batini, Nicoletta; Durand, Luigi',
    year: '2021',
    accessedAt: '2026-09-22',
    title: 'Facing the Global Financial Cycle: What Role for Policy?',
    publication: 'IMF Working Paper 2021/034',
    url: 'https://doi.org/10.5089/9781513569451.001',
    use: '支持国家对共同资本流因子的暴露具有显著且随时间变化的异质性，并提供资本流管理、宏观审慎、货币与汇率政策相关的实证结果；工作论文不是对任何国家、任何时点的最优政策处方。',
  },
  {
    id: 13,
    authors: 'Obstfeld, Maurice; Ostry, Jonathan D.; Qureshi, Mahvash S.',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'A Tie That Binds: Revisiting the Trilemma in Emerging Market Economies',
    publication: 'Review of Economics and Statistics 101(2), 279–293',
    url: 'https://doi.org/10.1162/rest_a_00740',
    use: '支持较固定汇率会放大全球金融冲击传导，而更灵活汇率仍可提供部分货币政策自主性的实证反论；不声称浮动汇率完全隔绝资产价格、信用或风险溢价冲击。',
  },
  {
    id: 14,
    authors: 'Powell, Jerome H.',
    year: '2018',
    accessedAt: '2026-09-22',
    title: 'Monetary Policy Influences on Global Financial Conditions and International Capital Flows',
    publication: 'Federal Reserve Board speech',
    url: 'https://www.federalreserve.gov/newsevents/speech/powell20180508a.htm',
    use: '支持“外部溢出存在”与“美国政策作用常被夸大”可以同时成立，并澄清trilemma从未承诺浮动汇率完全隔绝外部冲击；演讲是政策解释与证据综述，不是新的结构估计。',
  },
  {
    id: 15,
    authors: 'International Monetary Fund',
    year: '2020–present',
    accessedAt: '2026-09-22',
    title: 'Integrated Policy Framework',
    publication: 'IMF policy framework overview',
    url: 'https://www.imf.org/en/topics/ipf-integrated-policy-framework',
    use: '支持外汇市场不完美或脆弱性较高时，汇率弹性可能不足以完全隔离冲击，政策组合需依冲击与国情选择；不支持一刀切资本管制、外汇干预或宏观审慎，也不把所有工具视为同等有效。',
  },
  {
    id: 16,
    authors: 'Caldara, Dario; Ferrante, Francesco; Queralto, Albert',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'International Spillovers of Tighter Monetary Policy',
    publication: 'Federal Reserve Board FEDS Notes',
    url: 'https://www.federalreserve.gov/econres/notes/feds-notes/international-spillovers-of-tighter-monetary-policy-20221222.html',
    use: '支持把美国紧缩溢出拆成汇率、需求与金融渠道，并强调美元贸易/金融角色、外币错配和外国政策响应改变净效应；模型比较不等于某次现实事件的已识别贡献分解。',
  },
  {
    id: 17,
    authors: 'Bodenstein, Martin; Cuba-Borda, Pablo; Queralto, Albert',
    year: '2023',
    accessedAt: '2026-09-22',
    title: 'The Transmission of Global Risk',
    publication: 'Federal Reserve Board FEDS Notes',
    url: 'https://www.federalreserve.gov/econres/notes/feds-notes/the-transmission-of-global-risk-20230627.html',
    use: '支持同时比较美国excess bond premium、外国信用利差、VIX和全球金融周期因子，并展示这些指标相关但不等同；预测关系不能自动解释结构来源或政策反事实。',
  },
  {
    id: 18,
    authors: 'Bank for International Settlements',
    year: 'current data product',
    accessedAt: '2026-09-22',
    title: 'Global liquidity indicators',
    publication: 'BIS Data Portal',
    url: 'https://data.bis.org/topics/GLI',
    use: '支持按借款人居住地、币种和工具观察对非银借款人的外币银行贷款与国际债券信用；聚合GLI不是实体现金账本、全球因子、实时PIT数据或供给因果。',
  },
  {
    id: 19,
    authors: 'Stock, James H.; Watson, Mark W.',
    year: '2002',
    accessedAt: '2026-09-22',
    title: 'Macroeconomic Forecasting Using Diffusion Indexes',
    publication: 'Journal of Business & Economic Statistics 20(2), 147–162',
    url: 'https://doi.org/10.1198/073500102317351921',
    use: '支持从大量序列提取少数潜在共同因子的统计思想；不支持把主成分自动命名为风险偏好、把样本内解释度当因果，或忽略标准化、窗口、缺失值与实时修订。',
  },
  {
    id: 20,
    authors: 'Obstfeld, Maurice; Zhou, Haonan',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'The Global Dollar Cycle',
    publication: 'Brookings Papers on Economic Activity, Fall 2022, 361–427',
    url: 'https://www.brookings.edu/articles/the-global-dollar-cycle/',
    use: '支持以美元计价资产回报和广义美元共同运动理解全球美元周期，并强调风险、美国相对增长与资产需求的联合作用；不支持把美元汇率当唯一全球金融状态或固定方向因果变量。',
  },
  {
    id: 21,
    authors: 'Forbes, Kristin J.; Rigobon, Roberto',
    year: '2002',
    accessedAt: '2026-09-22',
    title: 'No Contagion, Only Interdependence: Measuring Stock Market Comovements',
    publication: 'Journal of Finance 57(5), 2223–2261',
    url: 'https://doi.org/10.1111/0022-1082.00494',
    use: '支持危机期收益异方差会使未经校正的相关系数变化成为不可靠的传染检验，并提供特定假设下的校正框架；不支持把其样本中的“未发现新增传染”外推为所有危机、资产或模型都不存在传染。',
  },
  {
    id: 22,
    authors: 'Bekaert, Geert; Harvey, Campbell R.; Ng, Angela',
    year: '2005',
    accessedAt: '2026-09-22',
    title: 'Market Integration and Contagion',
    publication: 'Journal of Business 78(1), 39–69',
    url: 'https://doi.org/10.1086/426519',
    use: '支持在含时变beta的全球与区域因子模型中，把危机期超出基本面/正常整合关系的额外共动作为待检验传染命题；不支持把残差相关本身、单一相关跃升或任意模型遗漏自动命名为传染。',
  },
] as const satisfies readonly LessonReference[];

export type GlobalCycleSourceId = (typeof lesson407References)[number]['id'];

export const globalCycleEvidenceGroups = [
  {
    key: 'object-measurement',
    title: '对象与测量：潜在共同因子、VIX、美元、利率和资本流不是同一个量',
    supports: '动态因子与主成分回答“哪些序列共同动”；VIX、美元与中心利率各有独立的市场口径和经济含义。',
    doesNotSupport: '不能因高相关就把代理变量命名为潜在因子，更不能从因子本身识别冲击来源。',
    sourceIds: [1, 2, 4, 7, 17, 19] as const,
  },
  {
    key: 'drivers',
    title: '来源：美国货币政策是重要候选之一，不是唯一全球开关',
    supports: '高频工具变量、事件窗和长期风险溢价研究显示美国政策或美国宏观信息可以产生广泛金融反应。',
    doesNotSupport: '每次全球risk-off都由Fed造成；系统性政策响应、增长消息、风险承载与其他中心冲击必须竞争。',
    sourceIds: [2, 3, 5, 10, 14, 16] as const,
  },
  {
    key: 'intermediaries-dollar',
    title: '中介与美元：资产负债表、外币错配和全球银行把冲击放大或迁移',
    supports: '全球银行杠杆、美元汇率、跨境信用与实体投资之间存在理论和样本内经验通道。',
    doesNotSupport: '美元升值对所有主体都为负、银行渠道覆盖所有证券基金与企业内部融资、或者聚合信用变化就是供给因果。',
    sourceIds: [8, 9, 16, 18, 20] as const,
  },
  {
    key: 'heterogeneity',
    title: '异质暴露：同一全球状态不会产生同幅、同号、同时反应',
    supports: '币种错配、投资者基础、市场深度、制度与政策选择会改变国家/资产的beta和局部残差。',
    doesNotSupport: '用固定国家排名、固定beta或“新兴市场”单一标签跨时期外推。',
    sourceIds: [4, 6, 9, 12, 13, 15] as const,
  },
  {
    key: 'flows',
    title: '资本流：gross inflow、gross outflow与net flow必须分开',
    supports: 'surge、stop、flight、retrenchment来自不同决策主体；全球因子平均解释力依流量类型、频率与样本而异。',
    doesNotSupport: '净流出等于外国投资者撤资，或平均低R²等于压力期全球因素无关。',
    sourceIds: [4, 11, 12] as const,
  },
  {
    key: 'policy-debate',
    title: '政策争论：dilemma与trilemma不是二选一口号',
    supports: '金融条件溢出、政策利率自主性、汇率缓冲、宏观审慎与资本流管理是不同结果变量和工具。',
    doesNotSupport: '浮动汇率毫无作用、开放经济没有任何货币自主性，或某个政策工具在所有冲击下都最优。',
    sourceIds: [3, 12, 13, 14, 15] as const,
  },
  {
    key: 'contagion-identification',
    title: '传染识别：相关上升先校正异方差，再检验超出共同与区域因子的额外传播',
    supports: '危机期条件相关会受波动率构成影响；直接传染命题需要在明确全球/区域因子、正常整合关系和识别假设之后检验额外共动。',
    doesNotSupport: '相关从0.3升至0.8、残差相关为正或危机期共同因子增强，本身都不能命名传播方向或传染。',
    sourceIds: [21, 22] as const,
  },
] as const;

export const lesson407ReadingList: readonly LessonReading[] = [
  {
    title: 'Miranda-Agrippino & Rey — The Global Financial Cycle',
    scope: 'Handbook综述的定义、事实、传导与研究争论',
    reason: '先读摘要、Sections 2–4 与结论，建立“现象—测量—冲击—中介—政策”五层框架；不要从任一图直接推演实时交易信号。',
    url: 'https://cepr.org/publications/dp16580',
    group: 'core',
    guide: '最短核心 45–60 分钟：摘要 → Sections 2–4 的小标题、核心图 → 结论；只记录对象、测量与证据边界。',
  },
  {
    title: 'Miranda-Agrippino & Rey — U.S. Monetary Policy and the GFCy',
    scope: '动态因子与外部工具识别',
    reason: '精读Sections 2–4：先看共同因子怎样构造，再看美国政策冲击怎样识别，最后核对结论没有把两者写成同义词。',
    url: 'https://doi.org/10.1093/restud/rdaa019',
    group: 'models',
    guide: '模型路线 60–90 分钟：Sections 2–4；先因子构造，再识别工具，最后对照结论的局部外推范围。',
  },
  {
    title: 'Cerutti, Claessens & Rose — How Important is the GFCy?',
    scope: '资本流中的反证与解释度边界',
    reason: '重点读abstract、measurement和conclusion，理解“全球因子存在”与“它解释大多数资本流变异”是两个不同命题。',
    url: 'https://www.bis.org/publ/work661.pdf',
    group: 'evidence',
    guide: '反证路线 35–50 分钟：摘要 → 数据/measurement表 → 结论；记下对象、频率与“不到四分之一”的样本范围。',
  },
  {
    title: 'Jordà et al. — Global Financial Cycles and Risk Premiums',
    scope: '长期资产同步与风险溢价',
    reason: '围绕现金流、无风险利率与风险溢价三分法阅读；留意历史覆盖和汇率制度异质性。',
    url: 'https://doi.org/10.1057/s41308-019-00077-1',
    group: 'evidence',
    guide: '证据路线 45–70 分钟：摘要 → 风险溢价分解图表 → 汇率制度异质结果 → 结论。',
  },
  {
    title: 'Aldasoro et al. — Global and Domestic Financial Cycles',
    scope: '全球周期与国内信用/房地产周期的对象和频率',
    reason: '用Table 1与结论复核：两种周期会相交，但变量、频率、政策问题与危机含义不相同。',
    url: 'https://www.bis.org/publ/work864.pdf',
    group: 'systems',
    guide: '系统路线 30–45 分钟：Table 1 → 全球/国内周期频率比较 → 结论；不必首遍通读估计附录。',
  },
  {
    title: 'Bruno & Shin — Cross-Border Banking and Global Liquidity',
    scope: '中介杠杆、汇率与跨境银行流',
    reason: '先读模型直觉，再读46国面板；分别记下模型预测、估计关系和不能覆盖的非银渠道。',
    url: 'https://doi.org/10.1093/restud/rdu042',
    group: 'models',
    guide: '模型路线 60–90 分钟：模型直觉与主要命题 → 46国面板主表 → 结论；分开模型预测和经验关系。',
  },
  {
    title: 'Forbes & Warnock — Capital Flow Waves',
    scope: 'surge / stop / flight / retrenchment',
    reason: '用gross inflow/outflow四象限替代“资本进出”一句话；再检查论文对因果的明确保留。',
    url: 'https://doi.org/10.3386/w17351',
    group: 'evidence',
    guide: '数据路线 35–50 分钟：四种gross-flow定义 → 事件识别 → 全球因素表 → 因果保留。',
  },
  {
    title: 'Obstfeld, Ostry & Qureshi — A Tie That Binds',
    scope: 'dilemma/trilemma的经验争论',
    reason: '比较“政策利率自主”与“金融条件完全隔绝”两个不同问题，避免把部分缓冲误写成完全免疫。',
    url: 'https://doi.org/10.1162/rest_a_00740',
    group: 'models',
    guide: '争论路线 45–60 分钟：研究问题 → 制度分类与主结果 → 结论；分别记录autonomy与insulation。',
  },
  {
    title: 'IMF — Facing the Global Financial Cycle',
    scope: '异质beta与政策缓冲',
    reason: '重点读time-varying sensitivity和政策变量的识别限制；不要将跨国平均结果直接处方化。',
    url: 'https://doi.org/10.5089/9781513569451.001',
    group: 'systems',
    guide: '政策证据路线 45–70 分钟：摘要 → time-varying sensitivity → 主要政策回归 → 内生性与外推限制。',
  },
  {
    title: 'Forbes & Rigobon；配读 Bekaert, Harvey & Ng — Contagion Identification',
    scope: '异方差偏误、正常相互依赖与因子过滤后的额外共动',
    reason: '先理解为什么危机相关上升不是传染证据，再比较时变全球/区域因子如何定义待检验的额外共动；两篇都不能被简化成“永远没有传染”。',
    url: 'https://doi.org/10.1111/0022-1082.00494',
    group: 'core',
    guide: '最短核心 60–90 分钟：Forbes–Rigobon 摘要、异方差直觉和结论；再读 Bekaert–Harvey–Ng 摘要、两因子设定与结论。',
    links: [{ label: '配读 · Market Integration and Contagion', url: 'https://doi.org/10.1086/426519' }],
  },
] as const;
