import type {LessonReference,LessonReading} from './types';
const accessedAt='2026-09-15';
export const lesson318References:LessonReference[]=[
 {id:1,authors:'European Central Bank',year:'2016-05-25',accessedAt,title:'What are interest rates and what is the difference between nominal and real interest rates?',publication:'ECB official explainer',url:'https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me/html/nominal_and_real_interest_rates.en.html',use:'作者实际完整读解释正文及其例子；支持名义合同与购买力区别。原网页名义减通胀是差值近似，本课精确比例另按定义推导；未导入、核图或复算原网页历史数据，不借它认证随机均衡或政策因果。'},
 {id:2,authors:'European Central Bank',year:'当前官方方法页；不虚构原始发布日期',accessedAt,title:'Transmission mechanism of monetary policy',publication:'ECB official monetary-policy methods',url:'https://www.ecb.europa.eu/mopo/intro/transmission/html/index.en.html',use:'作者实际完整读主体传导正文，支持未来短率预期、融资/资产/汇率/信用/需求与不确定滞后。没有量化系数、真实路径或联合财政因果估计；政策短率不等于所有借款合同。'},
 {id:3,authors:'Bank for International Settlements',year:'2023',accessedAt,title:'Monetary and fiscal policy: safeguarding stability and trust',publication:'BIS Annual Economic Report 2023, Chapter II; Box A',url:'https://www.bis.org/publications/aer-2023/monetary-fiscal-policy-safeguarding-stability-trust',use:'作者实际读官方HTML政策交互引入、完整Box A及接续指定段；保留43页PDF，实际核读PDF3–5 Box A/脚注并看原图，不称通读整章、annex或复算图数据。支持内部抵消、QE对外期限转换、付息准备金/非付息货币、费用与支持；stylised Graph A1不是观察数据，其近似债务/GDP式不是本课已复现的精确路径，FTPL段带无违约条件。'},
 {id:4,authors:'Eric M. Leeper',year:'1991-02',accessedAt,title:'Equilibria under “active” and “passive” monetary and fiscal policies',publication:'Journal of Monetary Economics 27(1), 129–147; DOI 10.1016/0304-3932(91)90007-B',url:'https://uva.theopenscholar.com/files/eric-leeper/files/eb34e1939af0017d5d0bf4c81b51a2e69f2f_8.pdf',use:'作者实际读UVA作者托管期刊排版19页全文文字（含参考），原图核Fisher/规则/四区/脚注；不称逐篇读参考文献、取得另供附录或完整复现非线性证明。支持原gross规则、绝对根四局部区、正稳态/创新/终端限定及OLS结构身份反例；固定禀赋/购买、一次性税，不支持现实GDP乘数或国家分类。'},
 {id:5,authors:'Thomas J. Sargent; Neil Wallace',year:'1981 Fall',accessedAt,title:'Some Unpleasant Monetarist Arithmetic',publication:'Federal Reserve Bank of Minneapolis Quarterly Review 5(3), 1–17; DOI 10.21034/qr.531',url:'https://fedinprint.org/item/fedmqr/41665',use:'官方身份页已核；官方PDF交付本次403，作者实际读CORE取得扫描本主文印1–7全部及Appendix A印8–9，B/C印10–17未读。第三方19页含期刊前页，未证明与官方字节等价，不发布全文镜像。支持完整初级赤字路径、R>n/债券吸收/货币需求条件、固定T与共同限额两比较、第二例预期可能性；未复算数表算法/福利，更不认证现代加息必通胀。'},
 {id:6,authors:'Board of Governors of the Federal Reserve System',year:'January 2026',accessedAt,title:'Financial Accounting Manual for Federal Reserve Banks: Chapter 1, Balance Sheet',publication:'Official FAM; §§11.86, 11.96, 12.36',url:'https://www.federalreserve.gov/aboutthefed/chapter-1-balance-sheet.htm',use:'作者实际完整读上述三个指定小节，不称全手册。支持准备金费用、汇款与恢复汇款前净盈余要求；C5为排除资本/盈余及其他法定调整的SYN简化，不导入Fed实际亏损、IORB值或预测，不证明财政自动立即注资、无成本或无限财务独立。'},
 {id:7,authors:'Narayana Kocherlakota',year:'2011',accessedAt,title:'Central Bank Independence and Sovereign Default',publication:'Federal Reserve Bank of Minneapolis, official speech; author views',url:'https://www.minneapolisfed.org/speeches/2011/central-bank-independence-and-sovereign-default',use:'作者实际完整读官方正文、全部9尾注与参考目录，未逐篇读所引论文。带条件违约例示、协调失败与救助权衡；尾注3无泡沫、7无风险短率区别、8Taylor确定性争议、9仍需财政支持均保留。不把演讲当联储政策、全局定理、国家评级；其SW书目卷号错写，采用另核官方5(3)。'},
 {id:8,authors:'Boris Hofmann; Marco Lombardi; Benoît Mojon; Athanasios Orphanides',year:'2021-07',accessedAt,title:'Fiscal and monetary policy interactions in a low interest rate world',publication:'BIS Working Papers No 954; author views',url:'https://www.bis.org/publications/working-paper-954-fiscal-and-monetary-policy-interactions-low-interest-rate-world',use:'作者实际读当前交付51页PDF4–6引言及9/13/14指定模型/校准页，不称整篇/附录或复现模拟。货币主导、半结构校准、学习与下限的条件反馈；QE归一化和部分符号需代码桥接，本课不移植量化系数或图表。当前下载2026-09-15、服务器Last-Modified2025，封面2021不证明历史字节等价或PIT。'},
 {id:9,authors:'Silvana Tenreyro',year:'2023-04-04',accessedAt,title:'Quantitative easing and quantitative tightening',publication:'Bank of England, official speech; author views',url:'https://www.bankofengland.co.uk/speech/2023/april/quantitative-easing-quantitative-tightening-speech-silvana-tenreyro',use:'作者实际完整读官方指定“QE is an asset swap”段与银行/非银行出售、政府债范围脚注；另读部分财务/目标段，不称完整演讲/所有脚注/参考论文，也未看Chart1。用于资产交换与财政购买区别、银行准备金/存款层及财务成本不等宏观评价；不说QE总财富效应0、货币渠道0或给英国通胀作因果贡献。'},
];
export const lesson318ReadingList:LessonReading[]=[
 {title:'先把“名义”和“购买力”读成两张账',scope:'ECB nominal/real explainer完整正文；再读传导页各主体、预期与滞后段',reason:'零背景先确认率、合同、未来路径与私人行为的对象，不用直接进入确定性证明。',url:lesson318References[0].url,group:'core',guide:'手算105/102−1；指出网页差值近似与本课比例定义不同。再用一句话说明固定工具路径为何不同于固定响应规则。',links:[{label:'ECB传导机制',url:lesson318References[1].url}]},
 {title:'BIS2023 Chapter II：先读Box A，再向外扩展',scope:'核心读Box A全部含脚注；深化再读全章政策交互及annex（后者不冒充作者已通读）',reason:'在财政单体、央行单体与合并公共部门之间来回对账，理解付息准备金与现金为什么不能共用免费融资故事。',url:lesson318References[2].url,group:'core',guide:'画出内部国债资产/负债60和外部40+60；每次看到ΔM，检查是否排除了付息准备金。原图是示意，不提取成真实数据。'},
 {title:'Leeper1991：模型单位、规则、四区与识别',scope:'第一次读印129–134设定及规则，再读138–141四区与OLS；深化通读129–147及另寻作者数学附录',reason:'同一文献同时展示联合闭合的重要性和均衡拟合不等于结构身份；先分清固定禀赋模型不解释哪些现实产出。',url:lesson318References[3].url,group:'models',guide:'写出gross R/π、税对真实旧债及两个绝对根；试γ=3的负根，解释III与IV不同。根程序不能验证正稳态或完整横截条件。'},
 {title:'Sargent–Wallace1981：先追完整路径，而不是背结论',scope:'核心主文印1–7含脚注4/5；深化Appendix A印8–9，再自行研读B/C印10–17算法（作者未读B/C）',reason:'理解货币增长实验、给定D(t)、真实R>n、有限债券吸收与预期型货币需求如何共同产生条件结论。',url:lesson318References[4].url,group:'models',guide:'分别列固定T/各自终值与共同限额/内生T，不能合并；检查第二例的初始价格和债重估。官方下载若仍受限，第三方扫描也不当历史PIT或官方字节等价证明。'},
 {title:'Fed FAM2026：恢复要求不是财政当日现金',scope:'完整读Chapter1 §§11.86, 11.96, 12.36；其他法律/资本小节只在需要时另核',reason:'分清收入、准备金费用、净收益、递延记录和汇款，防止把会计术语改写成无条件政策融资。',url:lesson318References[5].url,group:'rules',guide:'对照C5注明排除的资本/盈余和其他法定调整；查出哪句话支持汇款恢复机制，哪句话根本不支持实际联储损益预测。'},
 {title:'Kocherlakota2011：正文和九尾注必须一起读',scope:'完整官方speech、9尾注；深化其所引论文需另读原文，不借目录冒充已读',reason:'一个违约反例能修正无违约故事，但不能删掉财政支持、货币服务、无泡沫与确定性争议。',url:lesson318References[6].url,group:'models',guide:'把正文强承诺例子与尾注9放在同一页；指出无风险政策率与财政收益率、流动性协调失败与支持不足的差别。'},
 {title:'BIS954：先核货币主导与学习假设',scope:'核心PDF4–6及指定模型/校准页；深化自行读全51页与模型实现（作者未完整复现）',reason:'低利率下的联合反馈可以和财政主导经典模型有不同闭合；不因题名“interaction”就当成同一个制度。',url:lesson318References[7].url,group:'models',guide:'读模型变量归一化和保护条件再解释数字，未核清QE与财政符号时不要复制量化响应。封面年份与当前交付时间分开。'},
 {title:'Tenreyro2023：先读交换机制，再区分评价层次',scope:'核心“QE is an asset swap”全部与银行/非银行出售、政府债范围脚注；其余宏观数量论证另行完整核读',reason:'理解资产换手、准备金负债和存款层；财务成本、宏观目标与没有购债的基线不能互相替代。',url:lesson318References[8].url,group:'core',guide:'标出本课仅私人银行出售；若改为非银行，另加商业银行存款层，不能把公众直接写成准备金持有人。'},
];
