import type { LessonReading, LessonReference } from './types';

export const lesson311References: LessonReference[] = [
  { id: 1, authors: 'Ben S. Bernanke & Mark Gertler', year: '1989; NBER version 1986', title: 'Agency Costs, Net Worth, and Business Fluctuations', publication: 'American Economic Review 79(1), 14–31; NBER Working Paper 2015', url: 'https://www.nber.org/papers/w2015', use: '【模型】支持把企业家净值写成代理成本、外部融资溢价与投资波动之间的状态变量；不支持把净值下降机械等同于流动性枯竭，也不提供跨法域通用的溢价弹性。' },
  { id: 2, authors: 'Ben S. Bernanke, Mark Gertler & Simon Gilchrist', year: '1999; NBER version 1998', title: 'The Financial Accelerator in a Quantitative Business Cycle Framework', publication: 'Handbook of Macroeconomics, vol. 1C, chapter 21; NBER Working Paper 6455', url: 'https://www.nber.org/papers/w6455', use: '【模型】支持“净值下降→外部融资溢价上升→投资下降→资产价格和净值再下降”的金融加速器及其定量化框架；不支持把特定校准、线性化结果或代表性合同直接当作现实企业的因果系数。' },
  { id: 3, authors: 'Nobuhiro Kiyotaki & John Moore', year: '1997', title: 'Credit Cycles', publication: 'Journal of Political Economy 105(2), 211–248', url: 'https://www.journals.uchicago.edu/doi/10.1086/262072', use: '【模型】支持耐久资产同时作为生产投入与抵押品时，资产价格、借款容量和产出之间的动态反馈；不支持把模型中的土地、固定抵押比率或确定性执行结构无条件映射到所有资产和合同。' },
  { id: 4, authors: 'Ben S. Bernanke & Mark Gertler', year: '1995', title: 'Inside the Black Box: The Credit Channel of Monetary Policy Transmission', publication: 'Journal of Economic Perspectives 9(4), 27–48', url: 'https://www.aeaweb.org/articles?id=10.1257/jep.9.4.27', use: '【综述/模型】支持区分银行贷款供给渠道与借款人资产负债表渠道，并把净值、抵押品和外部融资溢价接入支出；不支持把两条渠道混成同一观测量，也不识别任一时期的结构效应大小。' },
  { id: 5, authors: 'Oliver Hart & John Moore', year: '1994', title: 'A Theory of Debt Based on the Inalienability of Human Capital', publication: 'Quarterly Journal of Economics 109(4), 841–879', url: 'https://academic.oup.com/qje/article-abstract/109/4/841/1866476', use: '【模型】支持有限承诺与控制权使可夺取、可转售的资产决定可质押收入和债务合同边界；不支持把账面资产总额当作可执行担保价值，也不直接决定现实破产顺位。' },
  { id: 6, authors: 'Bengt Holmström & Jean Tirole', year: '1997', title: 'Financial Intermediation, Loanable Funds, and the Real Sector', publication: 'Quarterly Journal of Economics 112(3), 663–691', url: 'https://academic.oup.com/qje/article-abstract/112/3/663/1926881', use: '【模型】支持内部资本、可监控性与可质押收入共同限制外部融资，并解释企业净值异质性如何进入真实投资；不支持把模型中的道德风险阈值视为可直接观测的会计比率或银行审批规则。' },
  { id: 7, authors: 'United Nations Commission on International Trade Law', year: '2007; adopted 2008', accessedAt: '2026-09-03', title: 'UNCITRAL Legislative Guide on Secured Transactions', publication: 'United Nations · official legislative guide', url: 'https://uncitral.un.org/en/texts/securityinterests/legislativeguides/secured_transactions', use: '【制度】支持以资产范围、设立、对第三方效力、优先权和执行条件定义动产担保权的法律可用性；不支持判定某笔资产在具体法域、实体、时点已无先置权利或必然可执行。' },
  { id: 8, authors: 'World Bank', year: 'Principles revised 2021; current page 2026-02-24', accessedAt: '2026-09-03', title: 'Principles for Effective Insolvency and Creditor/Debtor Regimes', publication: 'World Bank · Insolvency and Creditor Rights Standard', url: 'https://www.worldbank.org/en/brief/2026/02/24/the-world-bank-principles-for-effective-insolvency-and-creditor-rights', use: '【制度】支持把债权确认、担保执行、破产重组和机构能力作为抵押价值能否转化为信用容量的法域条件；不支持用国际基准替代当地成文法、判例、合同法律意见或个案回收率。' },
  { id: 9, authors: 'Chen Lian & Yueran Ma', year: '2021', title: 'Anatomy of Corporate Borrowing Constraints', publication: 'Quarterly Journal of Economics 136(1), 229–291', url: 'https://academic.oup.com/qje/article-abstract/136/1/229/5911133', use: '【经验/模型】支持区分资产型与基于经营收益的借款约束，并显示美国非金融企业债务合同中收益型约束的重要性；不支持把样本占比、Dealscan覆盖或美国合同语言外推为所有企业和法域的固定结构。' },
  { id: 10, authors: 'Thomas Drechsel', year: '2023', title: 'Earnings-Based Borrowing Constraints and Macroeconomic Fluctuations', publication: 'American Economic Journal: Macroeconomics 15(2), 1–34', url: 'https://www.aeaweb.org/articles?id=10.1257/mac.20210099', use: '【模型/经验】支持经营收益约束与抵押约束对投资冲击产生不同借款响应，并提供可估计宏观模型；不支持把 EBITDA、利息覆盖率或 DSCR 互换，也不证明所有企业都由收益约束主导。' },
  { id: 11, authors: 'Robert M. Townsend', year: '1979', title: 'Optimal Contracts and Competitive Markets with Costly State Verification', publication: 'Journal of Economic Theory 21(2), 265–293', url: 'https://www.sciencedirect.com/science/article/abs/pii/0022053179900310', use: '【模型】支持在状态核验有成本时债务式合同与外部融资成本的微观基础；不支持把核验成本直接等同于现实信用利差、违约损失或抵押折扣。' },
  { id: 12, authors: 'Efraim Benmelech & Nittai K. Bergman', year: '2009', title: 'Collateral Pricing', publication: 'Journal of Financial Economics 91(3), 339–360', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X08002043', use: '【经验】支持在美国航空融资中，更可再部署的飞机抵押品对应更低利差、更高评级和更高 LTV；不支持把航空器样本的点估计外推到房地产、存货、知识产权或无担保融资。' },
  { id: 13, authors: 'Adriano A. Rampini & S. Viswanathan', year: '2010', title: 'Collateral, Risk Management, and the Distribution of Debt Capacity', publication: 'Journal of Finance 65(6), 2293–2322', url: 'https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.2010.01616.x', use: '【模型】支持融资与风险管理共同占用稀缺抵押容量，并解释低净值企业为何可能少对冲、错失投资或缩表；不支持把所有对冲保证金、授信额度和资产担保视为同一法律池，本章也不展开 7.12 的保证金螺旋。' },
  { id: 14, authors: 'Adriano A. Rampini & S. Viswanathan', year: '2013', title: 'Collateral and Capital Structure', publication: 'Journal of Financial Economics 109(2), 466–492', url: 'https://people.duke.edu/~rampini/papers/Rampini%20Viswanathan%202013%20JFE.pdf', use: '【模型】支持资产所有权、租赁、可质押性与资本结构在有限执行下联合决定债务容量；不支持把租赁一概列为表外融资或认为租赁必然放松所有企业的总约束。' },
  { id: 15, authors: 'Steven M. Fazzari, R. Glenn Hubbard & Bruce C. Petersen', year: '1988', title: 'Financing Constraints and Corporate Investment', publication: 'Brookings Papers on Economic Activity 1988(1), 141–206', url: 'https://www.brookings.edu/articles/financing-constraints-and-corporate-investment/', use: '【经验】支持以融资层级和投资—现金流关系提出融资约束的经典经验假说；不支持把现金流敏感度本身当作净值冲击、抵押渠道或融资约束强度的无条件充分统计量。' },
  { id: 16, authors: 'Steven N. Kaplan & Luigi Zingales', year: '1997', title: 'Do Investment-Cash Flow Sensitivities Provide Useful Measures of Financing Constraints?', publication: 'Quarterly Journal of Economics 112(1), 169–215', url: 'https://academic.oup.com/qje/article-abstract/112/1/169/1870889', use: '【经验/批判】支持企业约束分类与投资—现金流敏感度之间并非单调对应，并要求回到合同与融资可得性证据；不支持据此否定融资摩擦，也不提供普适的 KZ 指数阈值。' },
  { id: 17, authors: 'Stewart C. Myers', year: '1977', title: 'Determinants of Corporate Borrowing', publication: 'Journal of Financial Economics 5(2), 147–175', url: 'https://doi.org/10.1016/0304-405X%2877%2990015-0', use: '【模型】支持既有债务使新投资收益部分转移给债权人而产生债务悬置与投资不足；不支持把每次高杠杆后的投资下降都归因于债务悬置，也不处理完整重谈和破产制度。' },
  { id: 18, authors: 'Christopher A. Hennessy, Amnon Levy & Toni M. Whited', year: '2007', title: 'Testing Q Theory with Financing Frictions', publication: 'Journal of Financial Economics 83(3), 691–717', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X06001991', use: '【模型/经验】支持在融资摩擦下把内部资金、债务悬置与投资响应纳入结构检验，并显示简单 Q 模型的遗漏；不支持把估计参数移植为单家企业的即时借款容量或项目批准规则。' },
  { id: 19, authors: 'Martin C. Schmalz, David A. Sraer & David Thesmar', year: '2017', title: 'Housing Collateral and Entrepreneurship', publication: 'Journal of Finance 72(1), 99–132', url: 'https://onlinelibrary.wiley.com/doi/10.1111/jofi.12468', use: '【经验】支持用法国房主、租客及不能二次抵押的有按揭房主比较，识别住房抵押价值对创业进入与成长的局部效应；不支持把法国制度下的家庭住房结果直接外推到上市公司、其他法域或 3.16 的完整住房机制。' },
  { id: 20, authors: 'International Monetary Fund, Statistics Department', year: '2019', accessedAt: '2026-09-03', title: 'Financial Soundness Indicators Compilation Guide 2019', publication: 'IMF Manuals and Guides', url: 'https://www.elibrary.imf.org/display/book/9781484396209/9781484396209.xml', use: '【官方统计方法】支持非金融企业部门的杠杆、偿债能力和财务报表汇总口径及元数据要求；不支持用部门 FSI 代替企业级 DSCR、契约定义、抵押净额或因果信用供给冲击。' },
  { id: 21, authors: 'Thomas Chaney, David Sraer & David Thesmar', year: '2012', title: 'The Collateral Channel: How Real Estate Shocks Affect Corporate Investment', publication: 'American Economic Review 102(6), 2381–2409', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.102.6.2381', use: '【经验】支持以企业既有房地产暴露和当地房价变化研究抵押价值、借款与投资之间的联系；不支持仅凭房价与投资相关性排除本地需求、资产所有权选择、无担保融资或预趋势。' },
  { id: 22, authors: 'Jie Gan', year: '2007', title: 'Collateral, Debt Capacity, and Corporate Investment: Evidence from a Natural Experiment', publication: 'Journal of Financial Economics 85(3), 709–734', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X07000608', use: '【经验】支持日本土地价格崩跌中房地产持有异质性与企业债务容量、投资变化的准实验设计；不支持把房地产暴露完全视为随机，也不排除银行健康、当地需求和企业选择的所有共同冲击。' },
  { id: 23, authors: 'Atif Mian & Amir Sufi', year: '2011', title: 'House Prices, Home Equity-Based Borrowing, and the US Household Leverage Crisis', publication: 'American Economic Review 101(5), 2132–2156', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.101.5.2132', use: '【经验】支持住房净值上升与美国既有房主增加抵押借款、真实支出和随后违约之间的局部证据；不支持将家庭住房提款系数用于企业抵押贷款，也不替代 3.16 的住房供需与按揭制度分析。' },
  { id: 24, authors: 'Atif Mian, Kamalesh Rao & Amir Sufi', year: '2013', title: 'Household Balance Sheets, Consumption, and the Economic Slump', publication: 'Quarterly Journal of Economics 128(4), 1687–1726', url: 'https://academic.oup.com/qje/article-abstract/128/4/1687/1849337', use: '【经验】支持高杠杆地区在房价下跌后的消费收缩异质性及家庭资产负债表—总需求接口；不支持把地区消费变化全部归因于借款容量，也不直接识别企业投资或银行贷款供给。' },
  { id: 25, authors: 'Bank for International Settlements', year: 'living quarterly dataset; last release 2026-06-15', accessedAt: '2026-09-03', title: 'Debt Service Ratios', publication: 'BIS Data Portal · official dynamic data and methodology', url: 'https://data.bis.org/topics/DSR', use: '【官方动态数据】支持按季度观察家庭、非金融企业与私人非金融部门利息加摊还占收入的统一近似指标；不支持跨国比较绝对水平、替代微观合同 DSCR 或把固定平均期限假设当作现实摊还表。' },
  { id: 26, authors: 'Andrei Shleifer & Robert W. Vishny', year: '1992', title: 'Liquidation Values and Debt Capacity: A Market Equilibrium Approach', publication: 'Journal of Finance 47(4), 1343–1366', url: 'https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.1992.tb04661.x', use: '【模型】支持行业共同受压时潜在买家受限会降低清算价值，从而缩小以可再部署资产支持的债务容量；不支持在 3.11 展开内生火售、市场冲击与交易反馈，后者路由至 7.13。' },
  { id: 27, authors: 'Board of Governors of the Federal Reserve System', year: 'current release 2026-06-11', accessedAt: '2026-09-03', title: 'S11.1.b — Balance Sheet of Nonfinancial Corporate Business', publication: 'Financial Accounts of the United States, Z.1 · official current table', url: 'https://www.federalreserve.gov/releases/z1/current/html/S11_1_b.htm', use: '【官方动态数据】支持按 2026 年新表号读取美国非金融公司部门资产、负债与净值存量及明确的计价基础；不支持把部门净值等同企业可质押净值、流动性或贷款 headroom，且不得回退到旧编号体系。' },
  { id: 28, authors: 'Board of Governors of the Federal Reserve System', year: 'current release 2026-06-11', accessedAt: '2026-09-03', title: 'S11.1.t — Transactions of Nonfinancial Corporate Business', publication: 'Financial Accounts of the United States, Z.1 · official current table', url: 'https://www.federalreserve.gov/releases/z1/current/html/S11_1_t.htm', use: '【官方动态数据】支持按 2026 年新表号区分利润、内部资金、资本支出、融资缺口与金融交易流量；不支持用部门净借款流反推企业获批额度、贷款供给或抵押品使用，且不得回退到旧编号体系。' },
  { id: 29, authors: 'Ben S. Bernanke, Mark Gertler & Simon Gilchrist', year: '1996; NBER version 1994', title: 'The Financial Accelerator and the Flight to Quality', publication: 'Review of Economics and Statistics 78(1), 1–15; NBER Working Paper 4789', url: 'https://www.nber.org/papers/w4789', use: '【模型/经验综述】支持不利冲击通过代理成本差异对低净值、高信息成本借款人产生更强融资与支出反应；不支持把规模、年龄或无评级状态单独解释成已识别的净值冲击。' },
  { id: 30, authors: 'Murillo Campello & Mauricio Larrain', year: '2016', title: 'Enlarging the Contracting Space: Collateral Menus, Access to Credit, and Economic Activity', publication: 'Review of Financial Studies 29(2), 349–383', url: 'https://academic.oup.com/rfs/article-abstract/29/2/349/1903031', use: '【经验】支持以东欧动产担保改革和资产构成异质性识别可担保资产菜单扩大后的借款、投资、就业与效率变化；不支持假定改革随机落地、平行趋势自动成立或把跨国平均结果套到任一法域。' },
  { id: 31, authors: 'World Bank', year: 'living dataset; metadata updated 2024-11-26', accessedAt: '2026-09-03', title: 'Enterprise Surveys', publication: 'World Bank Data Catalog · official firm survey data', url: 'https://datacatalog.worldbank.org/search/dataset/0037947/enterprise-surveys', use: '【官方动态数据】支持跨经济体企业层面的融资障碍、贷款申请、抵押要求、企业特征与绩效指标及其抽样元数据；不支持忽略调查权重、波次与问卷变化，也不把自报障碍或横截面相关性当作因果约束。' },
  { id: 32, authors: 'Basel Committee on Banking Supervision', year: 'published 2020-11-26; effective 2023-01-01', accessedAt: '2026-09-03', title: 'CRE22 — Standardised Approach: Credit Risk Mitigation', publication: 'Basel Framework · current in-force bank prudential standard', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/cre/22/inforce/2023-01-01/published/2020-11-26', use: '【制度】支持银行标准法下抵押品、保证与净额结算获得资本缓释须满足法律确定性、资格、估值和操作条件；不支持把监管认可抵押品等同借款人的法律可质押资产、实际放款额度或具体法域实施。' },
  { id: 33, authors: 'United Nations Commission on International Trade Law', year: '2013', accessedAt: '2026-09-03', title: 'UNCITRAL Guide on the Implementation of a Security Rights Registry', publication: 'United Nations · official registry guide', url: 'https://uncitral.un.org/en/texts/securityinterests/legislativeguides/security_rights_registry', use: '【制度】支持登记通知、第三方效力、查询与优先权透明度是动产担保制度的关键操作层；不支持把登记记录本身当作所有权证明、资产估值、无争议优先顺位或执行成功保证。' },
  { id: 34, authors: 'Michael R. Roberts & Amir Sufi', year: '2009', title: 'Renegotiation of Financial Contracts: Evidence from Private Credit Agreements', publication: 'Journal of Financial Economics 93(2), 159–184', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X09000798', use: '【经验】支持契约违反触发贷款重谈、条款调整和控制权重新配置，并说明名义债务容量并非不可变；不支持把所有重谈观察为无摩擦，也不证明违约企业必然恢复投资。' },
  { id: 35, authors: 'Murillo Campello, Robert A. Connolly, Gaurav Kankanhalli & Eva Steiner', year: '2022', title: 'Do Real Estate Values Boost Corporate Borrowing? Evidence from Contract-Level Data', publication: 'Journal of Financial Economics 144(2), 611–644', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X21002919', use: '【经验/反例】支持企业房地产升值后总借款增加可能由无担保债务而非新担保债务驱动，从而要求追踪融资工具构成；不支持据此否定所有抵押渠道，也不允许把总债务变化直接解释为抵押容量变化。' },
  { id: 36, authors: 'Bo Becker & Victoria Ivashina', year: '2014; NBER version 2011', title: 'Cyclicality of Credit Supply: Firm Level Evidence', publication: 'Journal of Monetary Economics 62, 76–93; NBER Working Paper 17392', url: 'https://www.nber.org/papers/w17392', use: '【经验】支持对有债券市场准入且正在融资的企业，用银行贷款与公共债券之间的替代刻画银行信贷供给周期；不支持覆盖无债券准入的小企业，也不把工具替代等同总外部融资或真实支出必然下降。' },
  { id: 37, authors: 'Board of Governors of the Federal Reserve System', year: 'current release 2026-06-11', accessedAt: '2026-09-03', title: 'S11.1.r — Changes in Net Worth of Nonfinancial Corporate Business', publication: 'Financial Accounts of the United States, Z.1 · official current revaluation bridge', url: 'https://www.federalreserve.gov/releases/z1/current/html/S11_1_r.htm', use: '【官方动态数据】支持按 2026 年新表号把净值变动分解为净投资、持有收益和其他物量变化，并与 S11.1.b 期末存量核对；不支持把持有收益当作现金流、可执行抵押增量或企业级因果冲击，且不得回退到旧编号体系。' },
  { id: 38, authors: 'Murillo Campello, John R. Graham & Campbell R. Harvey', year: '2010', title: 'The Real Effects of Financial Constraints: Evidence from a Financial Crisis', publication: 'Journal of Financial Economics 97(3), 470–487', url: 'https://doi.org/10.1016/j.jfineco.2010.02.009', use: '【经验/调查】支持受约束企业在危机中计划更深削减资本、技术与就业支出，并更多提款、耗用现金和出售资产；不支持把管理者自报分类当作外生约束、把计划等同实现值或把危机样本外推到常态。' },
  { id: 39, authors: 'Heitor Almeida & Murillo Campello', year: '2007', title: 'Financial Constraints, Asset Tangibility, and Corporate Investment', publication: 'Review of Financial Studies 20(5), 1429–1460', url: 'https://academic.oup.com/rfs/article-abstract/20/5/1429/1591748', use: '【模型/经验】支持资产有形性可通过融资乘数改变受约束企业投资—现金流关系，并强调资产结构异质性；不支持把 PPE 比率直接等同可执行、未设押、同币种的可质押价值。' },
  { id: 40, authors: 'Geraldo Cerqueiro, Steven Ongena & Kasper Roszbach', year: '2016', title: 'Collateralization, Bank Loan Rates, and Monitoring', publication: 'Journal of Finance 71(3), 1295–1322', url: 'https://onlinelibrary.wiley.com/doi/10.1111/jofi.12214', use: '【经验】支持瑞典贷款微观数据中抵押安排、贷款利率与银行监控的联合变化，并警示抵押的选择性；不支持用有无抵押的简单横截面差异识别抵押的纯价格效应或普适因果方向。' },
  { id: 41, authors: 'Murillo Campello & Erasmo Giambona', year: '2013; NBER version 2012', title: 'Real Assets and Capital Structure', publication: 'Journal of Financial and Quantitative Analysis 48(5), 1333–1370; NBER Working Paper 18147', url: 'https://www.nber.org/papers/w18147', use: '【经验】支持可出售性和再部署性比粗糙有形资产比率更贴近债务容量，且在紧信用期对受约束企业更重要；不支持把行业资产交易活跃度当作某笔担保品的净清算价值或法定优先权。' },
  { id: 42, authors: 'Charles W. Calomiris, Mauricio Larrain, José M. Liberti & Jason D. Sturgess', year: '2017; NBER version 2016', title: 'How Collateral Laws Shape Lending and Sectoral Activity', publication: 'Journal of Financial Economics 123(1), 163–188; NBER Working Paper 21911', url: 'https://www.nber.org/papers/w21911', use: '【经验】支持弱动产担保法对应更低动产贷款 LTV、偏向不动产的信贷配置，并以斯洛伐克改革补充识别；不支持把法律文本评分替代执行质量，也不外推固定的改革乘数。' },
  { id: 43, authors: 'Vikrant Vig', year: '2013', title: 'Access to Collateral and Corporate Debt Structure: Evidence from a Natural Experiment', publication: 'Journal of Finance 68(3), 881–928', url: 'https://onlinelibrary.wiley.com/doi/10.1111/jofi.12020', use: '【经验/反例】支持印度强化债权执行后企业可能减少担保债务、缩短期限并增加现金，显示更强权利也可能带来清算偏向；不支持“债权人保护越强，借款容量必然越大”的单调结论或跨法域直接外推。' },
  { id: 44, authors: 'Pablo Ottonello & Thomas Winberry', year: '2020', title: 'Financial Heterogeneity and the Investment Channel of Monetary Policy', publication: 'Econometrica 88(6), 2473–2502', url: 'https://onlinelibrary.wiley.com/doi/10.3982/ECTA15949', use: '【模型/经验】支持企业违约风险和财务状况异质性改变货币政策后的投资响应，并提供模型—微观证据桥；不支持把信用等级当作净值或抵押容量本身，也不把银行风险容忍度留在 3.11。' },
  { id: 45, authors: 'Joan Farre-Mensa & Alexander Ljungqvist', year: '2016', title: 'Do Measures of Financial Constraints Measure Financial Constraints?', publication: 'Review of Financial Studies 29(2), 271–308', url: 'https://academic.oup.com/rfs/article-abstract/29/2/271/1902640', use: '【经验/批判】支持常用企业特征指数可能错分融资约束，并以外生融资需求检验分类有效性；不支持据此证明企业没有融资摩擦，也不允许将任一单一指数作为本章 canonical constraint state。' },
  { id: 46, authors: 'Charles J. Hadlock & Joshua R. Pierce', year: '2010', title: 'New Evidence on Measuring Financial Constraints: Moving Beyond the KZ Index', publication: 'Review of Financial Studies 23(5), 1909–1940', url: 'https://academic.oup.com/rfs/article-abstract/23/5/1909/1602852', use: '【经验/测量】支持根据文本判断审视融资约束指标，并提出规模—年龄指标作为低成本代理；不支持把 SA 指数当作合同借款容量、外部融资溢价或跨样本不变的真实约束。' },
  { id: 47, authors: 'Board of Governors of the Federal Reserve System & Bureau of Economic Analysis', year: 'current release 2026-06-11', accessedAt: '2026-09-03', title: 'S11.1.i.a — Integrated Macroeconomic Accounts for Nonfinancial Corporate Business, Annual', publication: 'Integrated Macroeconomic Accounts for the United States · official current table', url: 'https://www.federalreserve.gov/releases/z1/current/html/S11_1_i_a.htm', use: '【官方动态数据】支持把非金融公司部门收入、储蓄、资本形成、净借贷与资产负债表变化放在一致的年度账户桥中；不支持从年度部门账户识别企业抵押冲击、短期 headroom 或个体支出因果效应。' },
  { id: 48, authors: 'European Central Bank', year: 'living quarterly survey; latest published 2026-Q2', accessedAt: '2026-09-03', title: 'Survey on the Access to Finance of Enterprises (SAFE)', publication: 'ECB · official dynamic survey, reports, data and methodology', url: 'https://www.ecb.europa.eu/stats/ecb_surveys/safe/html/index.en.html', use: '【官方动态数据】支持按企业规模、行业与国家观察融资需求、可得性、价格/非价格条件以及投资和就业预期；不支持把净回答比例当作约束强度、实际贷款金额或外生信用冲击，波次问卷与频率变化必须记录。' },
  { id: 49, authors: 'International Monetary Fund', year: 'living dataset', accessedAt: '2026-09-03', title: 'Global Debt Database', publication: 'IMF Data · official dynamic cross-country dataset', url: 'https://data.imf.org/Datasets/FAD_GDD', use: '【官方动态数据】支持跨 190 个经济体长期追踪公共与私人非金融部门总债务，并为宏观杠杆背景提供可比入口；不支持把总债务/GDP 当作企业净值、可质押资产、债务服务或融资约束的替代量。' },
  { id: 50, authors: 'Organisation for Economic Co-operation and Development', year: '2026', accessedAt: '2026-09-03', title: 'Financing SMEs and Entrepreneurs 2026: An OECD Scoreboard', publication: 'OECD · official cross-country scoreboard', url: 'https://www.oecd.org/en/publications/financing-smes-and-entrepreneurs-2026_075d8058-en/full-report.html', use: '【官方动态数据】支持 48 个国家 SME 贷款、利率、拒绝、担保、租赁和股权等融资条件的定义化比较与政策背景；不支持忽略各国数据源和覆盖差异，也不从聚合趋势识别企业抵押渠道的因果效应。' },
  { id: 51, authors: 'Joseph E. Stiglitz & Andrew Weiss', year: '1981', title: 'Credit Rationing in Markets with Imperfect Information', publication: 'American Economic Review 71(3), 393–410', url: 'https://www.jstor.org/stable/1802787', use: '【模型】支持逆向选择和激励效应可使贷款人预期回报对利率呈非单调，从而在竞争均衡中出现价格之外的信贷配给；不支持把现实中的任何拒贷、额度缩减或高利率直接归因于该模型，也不提供跨市场统一配给阈值。' },
  { id: 52, authors: 'Andrew B. Abel & Janice C. Eberly', year: '1994', title: 'A Unified Model of Investment Under Uncertainty', publication: 'American Economic Review 84(5), 1369–1384', url: 'https://www.jstor.org/stable/2117777', use: '【模型】支持固定调整成本、买卖价差与不可逆性共同产生投资、不行动和退出区间，从而解释等待与阈值响应；不支持把模型阈值当作可直接观测的融资约束，也不识别贷款冲击的经验效应。' },
  { id: 53, authors: 'Tim C. Opler & Sheridan Titman', year: '1994', title: 'Financial Distress and Corporate Performance', publication: 'Journal of Finance 49(3), 1015–1040', url: 'https://onlinelibrary.wiley.com/doi/10.1111/j.1540-6261.1994.tb00086.x', use: '【经验】支持行业下行中高杠杆企业的销售和权益价值相对下降与显著间接困境成本一致；不支持把差异全部归因于客户、供应商或员工中的单一机制，也不把高杠杆本身视为外生处理。' },
  { id: 54, authors: 'Asim Ijaz Khwaja & Atif Mian', year: '2008', title: 'Tracing the Impact of Bank Liquidity Shocks: Evidence from an Emerging Market', publication: 'American Economic Review 98(4), 1413–1442', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.98.4.1413', use: '【经验/识别方法】支持利用多银行借款企业内的银行差异分离共同借款需求与银行流动性供给冲击，并明确支持样本边界；不支持把借款人固定效应或贷款人×时间固定效应当作所有配对层供需与选择的完全控制，也不直接识别抵押品渠道。' },
  { id: 55, authors: 'Mark Gertler & Simon Gilchrist', year: '1994', title: 'Monetary Policy, Business Cycles, and the Behavior of Small Manufacturing Firms', publication: 'Quarterly Journal of Economics 109(2), 309–340', url: 'https://academic.oup.com/qje/article-abstract/109/2/309/1870303', use: '【经验】支持货币紧缩后小型制造企业在制造业收缩和库存调整中表现出不同动态，并以资产负债表差异讨论金融传播；不支持把企业规模等同低净值、把库存先行写成跨行业定律，或排除需求与银行供给共同变化。' },
];

export const lesson311ReadingList: LessonReading[] = [
  {
    title: '机制地基：净值、代理成本与金融加速器',
    scope: 'Bernanke–Gertler (1989) 全文；BGG (1999) 第 21 章 pp. 1341–1393；Bernanke–Gertler–Gilchrist (1996) pp. 1–15',
    reason: '先建立净值为何改变外部融资溢价，再区分初始冲击与内生放大，避免把资产价格下跌本身叫作金融加速器。',
    url: lesson311References[0].url,
    group: 'core',
    guide: '第一遍只画出净值、代理成本、外部融资溢价、投资和下一期净值五个节点；第二遍记录每个结论依赖的风险中性、合同和校准假设。',
    links: [
      { label: 'BG 1989', url: lesson311References[0].url },
      { label: 'BGG 1999', url: lesson311References[1].url },
      { label: 'Accelerator / flight to quality', url: lesson311References[28].url },
    ],
  },
  {
    title: '有限执行：为什么资产只能产生“可质押收入”',
    scope: 'Hart–Moore (1994) pp. 841–879；Holmström–Tirole (1997) pp. 663–691；Kiyotaki–Moore (1997) pp. 211–248',
    reason: '把账面净值、控制权、可夺取资产与均衡抵押反馈拆开，理解“资产价值高”为何仍可能无法借款。',
    url: lesson311References[4].url,
    group: 'models',
    guide: '逐篇写下谁能承诺什么、违约后谁控制什么、哪项状态可验证；不要把三篇论文的约束式混成同一个经验公式。',
    links: [
      { label: 'Hart–Moore', url: lesson311References[4].url },
      { label: 'Holmström–Tirole', url: lesson311References[5].url },
      { label: 'Kiyotaki–Moore', url: lesson311References[2].url },
    ],
  },
  {
    title: '资产型与收益型借款约束',
    scope: 'Lian–Ma (2021) pp. 229–291，重点 §§I–III 与附录合同分类；Drechsel (2023) pp. 1–34，重点模型冲击响应与估计部分',
    reason: '直接修正“企业借款都由抵押品决定”的过度简化，并把 LTV、EBITDA multiple、interest coverage 与 DSCR 分成不同原生口径。',
    url: lesson311References[8].url,
    group: 'core',
    guide: '先复核样本、债务金额加权和合同文本分类，再比较投资冲击下两类约束为何给出相反的借款方向；占比不可外推为自己的样本先验。',
    links: [
      { label: 'Anatomy of constraints', url: lesson311References[8].url },
      { label: 'Earnings-based macro model', url: lesson311References[9].url },
    ],
  },
  {
    title: '抵押品不是一个数：再部署性、定价与债务容量',
    scope: 'Benmelech–Bergman (2009) pp. 339–360；Rampini–Viswanathan (2010) pp. 2293–2322；Campello–Giambona (2013) pp. 1333–1370',
    reason: '把市值逐层收紧为可识别、可转让、可执行、未设押且压力状态下可回收的价值，并理解保留容量的机会成本。',
    url: lesson311References[11].url,
    group: 'evidence',
    guide: '为每篇列出资产类型、价值概念、融资工具和识别支持；航空器、行业可出售性与一般动态模型不能共享同一 haircut。',
    links: [
      { label: 'Collateral pricing', url: lesson311References[11].url },
      { label: 'Debt-capacity model', url: lesson311References[12].url },
      { label: 'Real-asset redeployability', url: lesson311References[40].url },
    ],
  },
  {
    title: '抵押渠道的识别、反例与支持边界',
    scope: 'Chaney–Sraer–Thesmar (2012) pp. 2381–2409；Gan (2007) pp. 709–734；Schmalz–Sraer–Thesmar (2017) pp. 99–132；Campello et al. (2022) pp. 611–644；Khwaja–Mian (2008) pp. 1413–1442',
    reason: '学习用所有权、地区需求、预趋势、多银行借款企业、融资工具构成与制度可抵押性构造反事实，并保留“无担保融资驱动”和支持样本收缩等反例。',
    url: lesson311References[20].url,
    group: 'evidence',
    guide: '每篇分别填写处理、对照、冲击、排除限制、样本支持和替代融资六格；只要未观察担保债务构成，就不能把总借款反应命名为纯抵押渠道。',
    links: [
      { label: 'Corporate real estate', url: lesson311References[20].url },
      { label: 'Japan natural experiment', url: lesson311References[21].url },
      { label: 'Owner-renter design', url: lesson311References[18].url },
      { label: 'Unsecured-debt counterevidence', url: lesson311References[34].url },
      { label: 'Within-firm multi-bank identification', url: lesson311References[53].url },
    ],
  },
  {
    title: '法律与合同工程：担保权、登记、优先顺位与重谈',
    scope: 'UNCITRAL Secured Transactions Guide，重点 chapters I–III、V、VIII–IX；Registry Guide，重点 paras. 10–38；World Bank ICR Principles A1–A5、B1–B5；Roberts–Sufi (2009) 全文',
    reason: '把经济模型中的 pledgeability 落到实体、资产、法域、顺位、登记、执行和重谈时点，防止将监管认可或账面所有权误写成可执行抵押。',
    url: lesson311References[6].url,
    group: 'rules',
    guide: '制度材料只作为核对清单；个案仍须读取当地法律、合同、登记簿和法律意见。将 Basel CRE22 单列为银行资本接口，不把它当借款人财产权规则。',
    links: [
      { label: 'UNCITRAL secured transactions', url: lesson311References[6].url },
      { label: 'UNCITRAL registry', url: lesson311References[32].url },
      { label: 'World Bank ICR', url: lesson311References[7].url },
      { label: 'Basel CRE22', url: lesson311References[31].url },
      { label: 'Contract renegotiation', url: lesson311References[33].url },
    ],
  },
  {
    title: '测量与争论：现金流敏感度不是约束本身',
    scope: 'Fazzari–Hubbard–Petersen (1988) pp. 141–206；Kaplan–Zingales (1997) pp. 169–215；Farre-Mensa–Ljungqvist (2016) pp. 271–308；Hadlock–Pierce (2010) pp. 1909–1940',
    reason: '理解融资约束经验文献的经典起点与随后反驳，建立“代理变量必须通过行为或合同验证”的识别纪律。',
    url: lesson311References[14].url,
    group: 'evidence',
    guide: '分别记录 constraint 的定义、分类依据、反事实与可证伪预测；不要把 KZ、SA、规模、年龄、现金流或是否分红单独写成 canonical state。',
    links: [
      { label: 'FHP', url: lesson311References[14].url },
      { label: 'Kaplan–Zingales critique', url: lesson311References[15].url },
      { label: 'Farre-Mensa–Ljungqvist', url: lesson311References[44].url },
      { label: 'Hadlock–Pierce', url: lesson311References[45].url },
    ],
  },
  {
    title: '从融资约束到真实支出：债务悬置、替代与实现值',
    scope: 'Myers (1977) pp. 147–175；Hennessy–Levy–Whited (2007) pp. 691–717；Abel–Eberly (1994) pp. 1369–1384；Opler–Titman (1994) pp. 1015–1040；Gertler–Gilchrist (1994) pp. 309–340；Becker–Ivashina (2014) pp. 76–93；Campello–Graham–Harvey (2010) pp. 470–487',
    reason: '区分有项目但股东不愿投资、调整成本带来的等待、财务困境的经营损失、库存响应、银行贷款被债券替代、总融资减少以及企业真实削减支出等不同结果。',
    url: lesson311References[16].url,
    group: 'systems',
    guide: '依次核对项目 NPV、对股东的私人 NPV、各工具净发行、现金缓冲和实现投资；融资构成变化只有在总资金与现金使用同步后才能接到真实支出。',
    links: [
      { label: 'Debt overhang', url: lesson311References[16].url },
      { label: 'Q with frictions', url: lesson311References[17].url },
      { label: 'Investment under uncertainty', url: lesson311References[51].url },
      { label: 'Distress and operating performance', url: lesson311References[52].url },
      { label: 'Small firms and inventory dynamics', url: lesson311References[54].url },
      { label: 'Loan-bond substitution', url: lesson311References[35].url },
      { label: 'CFO survey', url: lesson311References[37].url },
    ],
  },
  {
    title: '家庭边界阅读：住房净值、借款与消费',
    scope: 'Mian–Sufi (2011) pp. 2132–2156；Mian–Rao–Sufi (2013) pp. 1687–1726；Schmalz–Sraer–Thesmar (2017) pp. 99–132',
    reason: '用家庭证据理解净值—借款—支出接口，同时明确企业资产负债表章节与 3.16 住房专门机制的边界。',
    url: lesson311References[22].url,
    group: 'systems',
    guide: '只抽取可迁移的识别逻辑：既有所有权、可提款净值、当地需求对照和支出用途；按揭合同、住房供给和止赎外溢全部路由到 3.16。',
    links: [
      { label: 'Home-equity borrowing', url: lesson311References[22].url },
      { label: 'Household consumption', url: lesson311References[23].url },
      { label: 'Entrepreneurship collateral', url: lesson311References[18].url },
    ],
  },
  {
    title: '官方数据复算路径：存量、交易、重估、偿债与调查',
    scope: 'Fed Z.1 S11.1.b / S11.1.t / S11.1.r / S11.1.i.a；BIS DSR methodology；IMF FSI chapter 10；World Bank Enterprise Surveys metadata；ECB SAFE methodology',
    reason: '建立可复算的部门净值桥与宏观偿债背景，同时把企业级合同状态与聚合统计严格分层。',
    url: lesson311References[26].url,
    group: 'rules',
    guide: '固定 provider、releaseDate、observationDate、sector、valuationBasis、unit、frequency、currency、seasonalAdjustment 与 revision；Fed 只用 2026-06-11 后 S11.1 新表号，存量、交易和重估不得相加混用。',
    links: [
      { label: 'Fed balance sheet S11.1.b', url: lesson311References[26].url },
      { label: 'Fed transactions S11.1.t', url: lesson311References[27].url },
      { label: 'Fed revaluation bridge S11.1.r', url: lesson311References[36].url },
      { label: 'Fed integrated account S11.1.i.a', url: lesson311References[46].url },
      { label: 'BIS DSR', url: lesson311References[24].url },
      { label: 'IMF FSI Guide', url: lesson311References[19].url },
      { label: 'World Bank Enterprise Surveys', url: lesson311References[30].url },
      { label: 'ECB SAFE', url: lesson311References[47].url },
    ],
  },
  {
    title: '价格为何不能总是出清：逆向选择与信贷配给',
    scope: 'Stiglitz–Weiss (1981) pp. 393–410；并回看 Townsend (1979) 的核查成本与 Lian–Ma (2021) 的现实契约分类',
    reason: '理解提高利率如何改变申请者和风险选择，为什么贷款人可能转向拒绝、额度与非价格条款；同时把抽象配给模型与现实借款约束分开。',
    url: lesson311References[50].url,
    group: 'models',
    guide: '先写出贷款人预期回报非单调所需的类型与行为假设，再寻找申请母体、拒绝、额度和合同证据；不要把任何一次拒贷直接贴上“Stiglitz–Weiss配给”标签。',
    links: [
      { label: 'Credit rationing', url: lesson311References[50].url },
      { label: 'Costly state verification', url: lesson311References[10].url },
      { label: 'Borrowing constraints in contracts', url: lesson311References[8].url },
    ],
  },
];
