import CycleLabStatic from '../components/CycleLabStatic';
import CycleQuiz from '../components/CycleQuiz';
import CycleStaticQuiz from '../components/CycleStaticQuiz';
import CycleDiagram from '../components/CycleDiagram';
import '../components/CyclePrint.css';
import {cycleLabs,cycleLabAudit} from '../components/cycleLabDefinitions';
import {cycleScenarios,cycleScenarioAudit} from '../components/cycleScenarios';
import {cycleConcepts,cycleThesis} from './cycleConcepts';
import {lesson322References,lesson322ReadingList} from './cycleReferences';
import {cycleChecks,cycleGlossary,cycleInvariants,cycleInterfaces} from './cycleStudy';
import {canonicalCycleStateExample,canonicalCycleFields,canonicalCycleAudit} from './cycleState';
import type {LessonRecord} from './types';
export {canonicalCycleStateExample,canonicalCycleFields,canonicalCycleAudit} from './cycleState';
function Cites({ids}:{ids:readonly number[]}){return <>{ids.map(id=><a key={id} href={`#ref-${id}`} aria-label={`参考文献${id}`}>[{id}] </a>)}</>;}
const extras=[{id:'scope-route',label:'对象／单位／时钟'},{id:'cycle-condition-map',label:'条件反馈关系图'},{id:'cycle-model-map',label:'账桥／测量／研究任务'},{id:'cycle-interactive-section',label:'Interactive M1–M10'},{id:'cycle-static-twins',label:'Static K1–K10'},{id:'checks-glossary',label:'Checks / Audit / Glossary'},{id:'evidence-boundaries',label:'State / Sources / Interfaces'}];
const sectionIds=['thesis',...cycleConcepts.map(c=>c.id),...extras.map(e=>e.id)],sources=new Set(lesson322References.map(r=>r.id));
const citationIds=[...cycleConcepts.flatMap(c=>c.sourceIds),...cycleLabs.flatMap(l=>l.sourceIds),...cycleScenarios.flatMap(s=>s.sourceIds),...cycleChecks.flatMap(c=>c.sourceIds)];
export const lesson322IntegrityAudit=[
 {key:'27 single-mechanism units,81 connected paragraphs and explicit condition/source boundaries (structure alone is not semantic approval)',passed:cycleConcepts.length===27&&cycleConcepts.every(c=>c.paragraphs.length===3&&c.paragraphs.every(p=>p.length>=90)&&c.boundary.length>=30&&c.sourceNote.length>=20&&c.sourceIds.length>0)},
 {key:'all section IDs unique and seven independent experiments attached exactly once',passed:new Set(sectionIds).size===sectionIds.length&&cycleConcepts.flatMap(c=>c.labIds??[]).length===7&&new Set(cycleConcepts.flatMap(c=>c.labIds??[])).size===7&&cycleConcepts.flatMap(c=>c.labIds??[]).every(id=>cycleLabs.some(l=>l.id===id))},
 {key:'ten primary-source routes and ten deeper readings, every citation resolves to declared scope',passed:lesson322References.length===10&&lesson322ReadingList.length===10&&citationIds.every(id=>sources.has(id))&&lesson322References.every(r=>r.use.length>=60&&r.url.startsWith('https://'))},
 {key:'20 understanding checks,40 terms,16 invariants and eight specific interfaces',passed:cycleChecks.length===20&&cycleGlossary.length===40&&cycleInvariants.length===16&&cycleInterfaces.length===8},
 {key:'finite contract/source-structure guards pass but do not register two whole-lesson approvals',passed:[...cycleLabAudit,...cycleScenarioAudit,...canonicalCycleAudit].every(a=>a.passed)},
] as const;
function Lesson322Content(){return <>
 <noscript><style>{'.lesson-page[data-lesson-id="3.22"] .cycle-interactive-only{display:none!important}'}</style><p>脚本已关闭：七C固定默认输入、95行结果、完整手算与条件说明，K1–K10三候选及三条推理、原生关系图与引用仍可阅读。折叠记录可以直接展开；纸本只保留一次完整固定记录。</p></noscript>
 <section id="thesis" className="lesson-section"><p className="section-kicker">ONE CENTRAL MECHANISM · ACTIVITY IS NOT FINANCIAL COMMITMENT</p><h2>经济活动的方向，不足以确定金融承诺和承损状态。</h2>{cycleThesis.map(p=><p key={p}>{p}</p>)}<p className="section-sources"><Cites ids={[1,2,3,6,10]}/></p></section>
 <section id="scope-route" className="lesson-section"><p className="section-kicker">OBJECT / UNIT / INFORMATION PASSPORT</p><h2>先固定量什么、相对谁、何时可得，再解释周期。</h2>
 <p>Master硬先修是3.01 Real Growth和3.14 Credit Cycle，分别提供活动测量与金融承诺反馈。它们实际已批准的课节对象、版本、审稿记录及3.14的真实canonical对象保留原身份；本节不消耗旧数值作校准。按需回查T01/T03/T05/T06/T08，补增长、概率、相关/因果、两侧账本和资料频率；3.11/3.15/3.16/3.21是语义接口，不新增强制前置课程或共同国家轨迹。</p>
 <p>从零开始可分三段学习：01–08先辨活动、方向、恢复与正式定年；09–18把信用存量、资产估值、合同兑现与承损接回主体；19–27再辨测量、资料/训练时钟、共动及危机标签。每次遇到C先手算固定默认，再单改条件并解释哪一对象变了。十M/K是独立固定题，不跟随实验控件；术语、理解检查和原典深化可在第二遍完成，不用一口气读所有附件。</p>
 <p>机构先解码：NBER是National Bureau of Economic Research，美国全国经济研究局；本课FAQ描述其美国商业周期定年，不是全球统一衰退法。BIS是Bank for International Settlements，国际清算银行；IMF是International Monetary Fund，国际货币基金组织；BoE是Bank of England，英格兰银行。WP是working paper工作论文，不意味着全部争论已有定论。原文只支持各自声明范围，不为作者SYN数字背书。 <Cites ids={[1,3,5,10]}/></p>
 <p>量与方法先解码：GDP是gross domestic product国内生产总值，GDI是gross domestic income国内生产总收入，以生产形成的收入测量对应活动总量，不等同家庭可花的收入；窗口与价格口径都需说明。HP是Hodrick–Prescott滤波；OLS是ordinary least squares普通最小二乘。Level水平、growth增长率、旧峰差和趋势缺口是不同量；百分率变化与百分点也不同。Credit-to-GDP gap需要另定趋势，信用/产出水平不是该指标。Hamilton的回归、HP、WP380程序和本课三点均值各自保留算法，不改名互代。 <Cites ids={[1,4,5,7]}/></p>
 <p>SYN表示synthetic合成条件。本课36个原始控件用各自安全整数域，指数/产出分母与起始C7权益须正，贷款金额可零；损失率为整数百分比，不是房价跌幅。七C没有共同国家或连续时点，表中有效0与未知null不同。C5序号只给发布先后，非真实日期；有限除法和十二位显示不变成精确有理数轨迹或现实历史PIT。PIT（point-in-time）指判断时点可得资料，还要核真实版本、标签与训练参数。</p>
 <div className="precision-note"><span>{canonicalCycleStateExample.evidenceState.twoFullApprovalsRegistered?'审批状态：完整同版正文已由两位非作者独立审查通过':'审批状态：完整成稿仍待同版两位非作者正式审查'}</span><p>{canonicalCycleStateExample.evidenceState.twoFullApprovalsRegistered?'正式两份记录对应同一冻结完整正文，作者自检和教学附件作者不占两位审批席。首轮修改要求、有限预审及原失败保留；教材审批不认证真实国家定年、危机分类、法律、因果、PIT或样本外性能。':'七C及十题已做有限数学和参数文案预审，r1教学修改要求与原失败保留，r2有限复核通过；这不批准完整27机制、十来源、附件、网页或纸本。作者自检和教学附件作者不能占两位正式审批。当前不注册任何完整内容approved记录，不认证真实国家定年、危机分类、法律、因果、PIT或样本外性能。'}</p></div>
 </section>
 {cycleConcepts.map((c,i)=><section id={c.id} key={c.id} className="lesson-section"><p className="section-kicker">{String(i+1).padStart(2,'0')} · CORE MECHANISM</p><h2>{c.title}</h2>{c.paragraphs.map(p=><p key={p}>{p}</p>)}{c.formula?<div className="equation-card"><span>只用于澄清对象的必要算式</span><div><code>{c.formula.expression}</code></div><p>{c.formula.explanation}</p></div>:null}<div className="precision-note"><span>成立条件、反例与跨章接口</span><p>{c.boundary}</p></div>{c.labIds?.map(id=><CycleLabStatic labId={id} key={id}/>)}<p className="section-sources"><b>本机制依据：</b><Cites ids={c.sourceIds}/>{c.sourceNote}</p></section>)}
 <section id="cycle-condition-map" className="lesson-section"><p className="section-kicker">CONDITIONAL FEEDBACK · NOT A FIXED PHASE WAVE</p><h2>活动、金融与信息之间，需要有条件的主体桥。</h2><p>四卡不是必然依次发生的四阶段，而是帮助定位现金流、长承诺、承损和资料时钟。每条候选反馈都问首先影响谁、哪道合同或信息门改变、真实选择是否有证据。七组SYN不串成四卡共同路径；正反馈有条件，也可能被现金、权益、合同调整或政策缓冲截断。</p><CycleDiagram/></section>
 <section id="cycle-model-map" className="lesson-section"><p className="section-kicker">ACCOUNT / MEASUREMENT / RESEARCH TASK</p><h2>账桥能闭合，标签能定义，研究仍要另外验证。</h2><div className="model-card-grid">
 <div><h3>封闭题设的账与算式</h3><p>C1/C2区分参照和分母，C3接毛额桥，C7按另给损失更新两侧；算对只批准明示条件的结果。真实损失、贷款选择和法律仍未知。 <Cites ids={[3,10]}/></p></div>
 <div><h3>测量与信息依赖</h3><p>C4/C5显式区分事后量和截止可得量，C6比较四格和另设边际基准。HP/峰谷/版本各有规则，不能由数学一致性认证实际定年、显著性或PIT。 <Cites ids={[1,4,5,7]}/></p></div>
 <div><h3>描述、解释与预测</h3><p>共动可描述，因果需主体冲击与对照，预测需当时资料/参数和样本外基线。特定危机数据库还需锁版本及borderline范围，不用事后标签解释成实时知识。 <Cites ids={[6,8,9]}/></p></div>
 </div><p>不要把“计数通过”“读过经典文献”“两位教材审批”合并成现实准确性总证书。它们分别支持有限算术、声明原文范围和教材成品，研究结果需要其自己的证据。</p></section>
 <section id="cycle-interactive-section" className="lesson-section cycle-interactive-only"><p className="section-kicker">INTERACTIVE M1–M10 · FIXED INDEPENDENT QUESTIONS</p><h2>先辨参照、毛净和时钟，再作中性选择。</h2><p>十题各自固定对应C的默认输入、护照及所求单位。ABC只显示数值，选择后才显示当前正确或错路解释；改选立即替换旧诊断。它们不是当前可编辑实验的快照，也不随C控件更改，更不能拼成同国家路径。</p><CycleQuiz/></section>
 <section id="cycle-static-twins" className="lesson-section"><p className="section-kicker">STATIC K1–K10 / NATIVE / PRINT</p><h2>无脚本和纸上，仍能读完整题设与三条推理。</h2><p>每K与M同一固定题库、完整输入、单位和ABC顺序。先写对象、参照与截止点，再原生展开正确推理和两条错路；打印只展开一次完整记录。错误值可能正确回答另一问题，所以需要指出偷换了什么，而非只记住一个正确数字。</p><CycleStaticQuiz/></section>
 <section id="checks-glossary" className="lesson-section"><p className="section-kicker">UNDERSTANDING / INTEGRITY / GLOSSARY</p><h2>把“尚缺什么证据”也作为理解的一部分。</h2><div className="check-grid">{cycleChecks.map((c,i)=><div key={c.question}><details><summary>{String(i+1).padStart(2,'0')} · {c.question}</summary><p>{c.answer} <Cites ids={c.sourceIds}/></p></details><p className="print-only"><b>{String(i+1).padStart(2,'0')} · {c.question}　答案：</b>{c.answer} <Cites ids={c.sourceIds}/></p></div>)}</div><div className="yield-fixture-audit"><span>有限契约／来源结构门（作者自检，非独立内容审批）</span><ul>{[...cycleLabAudit,...cycleScenarioAudit,...canonicalCycleAudit,...lesson322IntegrityAudit].map(a=><li key={a.key} className={a.passed?'passed':''}>{a.passed?'PASS':'FAIL'} · {a.key}</li>)}</ul></div><div className="term-grid">{cycleGlossary.map(([term,meaning,confusion])=><article className="term-card" key={term}><h3>{term}</h3><p>{meaning}</p><em>不可混同：{confusion}</em></article>)}</div></section>
 <section id="evidence-boundaries" className="lesson-section"><p className="section-kicker">STATE / ACTUAL READING / INTERFACES</p><h2>保留实际版本和未知，不构造虚假的完整国家状态。</h2><p>canonical有{canonicalCycleFields.length}个顶层字段；七输入各保留真实默认对象身份，inputLineage为空，因为没有消费上游数值。Master3.01实际版本{canonicalCycleStateExample.semanticPrerequisiteStates[0].revision}及其两份记录保留，该课未暴露单独canonical数值/冻结marker，本节不补造；3.14实际版本{canonicalCycleStateExample.semanticPrerequisiteStates[1].revision}、真实canonical与原命名reviewFrozenAt {canonicalCycleStateExample.semanticPrerequisiteStates[1].producerMarker.reviewFrozenAt}保留，不重解释成真实历史可得日。本节草稿准备钟为{canonicalCycleStateExample.clockState.draftPreparedAt}，网页注册钟为{canonicalCycleStateExample.scopePassport.registeredAt}，它只记录教材组装，不是历史观测截止日；完整正文批准所对应的冻结钟为{canonicalCycleStateExample.clockState.ownReviewFrozenAt??'null（尚未登记同版完整双审）'}，不能用准备、注册或教材审批时钟证明PIT。</p><div className="precision-note"><span>canonical · {canonicalCycleStateExample.schemaVersion}</span><p><code>{canonicalCycleFields.join(', ')}</code>。真实活动、金融相位、危机/法律、训练、贷款选择、政策、断点、因果/PIT/预测和反馈均保持未知；SYN净信用0、事后残差0、产出0及负权益只限已明示对象。真实市场资料护照为空。</p></div><h3>生产者不变量</h3><ol className="contract-list">{cycleInvariants.map((r,i)=><li key={r}><b>{String(i+1).padStart(2,'0')}</b><span>{r}</span></li>)}</ol>
 <h3>编写者实际读过与尚未读过的原文</h3><p>NBER FAQ全部main实质问答和公告滞后表实际读；Burns–Mitchell首章只读原PDF1–8文字选段及原整页4/7/8，书目TOC仅导航，未读整书/首章余文。WP395读1–14，WP380读1–11及33并真看原11，WP11/88读1–13，WP864读1–9。各原件其余结果/Annex/数据和引用论文未通读或重估；WP380五年40季度异常明确未解，不静改参数。 <Cites ids={[1,2,3,4,5,6]}/></p><p>Hamilton2017原PDF1–19实读含脚注16，不声称20–47完整证明/结果或2018期刊全文已读。2026危机原件只读1–2/5–9并真看原7；2018先读1–2/5–7，来源预备审查后另补原PDF9完整文字核151/边界案例直接声明，新增时点单存，未取数据ZIP/全部事件或2020中间版。各发表和URL日期不同分别保留。BoE2014在本轮较早为3.21实际读完14页文字并真看Figure1原PDF3，现在复用同字节原件，不称复制时又重新全文阅读。原文范围属于各个人，不借他人阅读或检查作为编写者的实读；本页只链接官方来源，不提供版权全文镜像。 <Cites ids={[7,8,9,10]}/></p>
 <h3 id="cycle-cross-interfaces">跨章接口</h3><div className="interface-grid">{cycleInterfaces.map(([name,payload,guardrail])=><article key={name}><span>{name}</span><p><b>传递什么：</b>{payload}</p><p><b>不可跨越：</b>{guardrail}</p></article>)}</div><p>最后复盘一条局部链：活动首先改变谁的现金流，旧承诺何时兑现，损失或抵押门是否真的改变金融选择，支出和价格怎样再反馈收入。每一步分别记已观测、题设给定或仍未知；定年、描述、解释、预测各自锁任务，再交Chapter7验证，不发布固定周期倒计时。</p></section>
 </>;}
const lesson322Reviews:LessonRecord['reviews']=[
 {kind:'accuracy',completedAt:'2026-09-16T02:49:45.248Z',decision:'approved',revision:'3.22-r2',summary:'重新完整审查同版27机制、原典限定范围、七C、30候选和canonical；新24005有限调用及434来源图核查，亲看新纸本35整页。公开指针P2关闭；未认证现实定年、法律、因果/PIT或预测。'},
 {kind:'pedagogy',completedAt:'2026-09-16T02:54:26.270Z',decision:'approved',revision:'3.22-r2',summary:'重新完整审查同版教学产物，独立实测真实Chrome、键盘、390px、真正禁脚本与打印，亲看新纸本42整页；公开指针P2关闭，无剩余P1/P2。个人原文选读与成品检查不升级为现实资料或读屏认证。'},
];
export const lesson322:LessonRecord={slug:'3-22',id:'3.22',chapter:'03',chapterTitle:'Macro State & Financial Conditions',title:'经济周期与金融周期：活动、承诺与危机标签',subtitle:'Business Cycle vs Financial Cycle：区分方向与恢复、信用存量与毛融资、长承诺与承损、居中与训练信息集，再辨不同版本系统性银行危机标签',readingTime:'主线与七C必要手算约70–100分钟；十M/K约20–35分钟、检查/术语/复盘约25–40分钟可第二遍学习。均是估时，原典深化另计，不靠凑字保证阅读时长',prerequisite:'Master：3.01、3.14；按需T01/T03/T05/T06/T08及3.11/3.15/3.16/3.21。实际上游只保留语义与版本身份，不消费数值校准七独立SYN',updatedAt:'2026-09-15',revision:'3.22-r2',reviewStatus:'double-reviewed',reviews:lesson322Reviews,previous:{slug:'3-21',label:'3.21 Capital Flow的国内入口'},next:{label:'3.23 Macro Surprise：Actual vs Expectation'},sections:[{id:'thesis',label:'核心命题'},extras[0],...cycleConcepts.map(({id,label})=>({id,label})),...extras.slice(1)],Content:Lesson322Content,references:lesson322References,readingList:lesson322ReadingList,readingListOrder:'source'};
