import SovereignLabStatic from '../components/SovereignLabStatic';
import '../components/SovereignPrint.css';
import SovereignQuiz from '../components/SovereignQuiz';
import SovereignStaticQuiz from '../components/SovereignStaticQuiz';
import SovereignScopeDiagram from '../components/SovereignScopeDiagram';
import {sovereignLabs,sovereignLabAudit} from '../components/sovereignLabDefinitions';
import {sovereignScenarios,sovereignScenarioAudit} from '../components/sovereignDebtScenarios';
import {sovereignConcepts,sovereignThesis} from './sovereignDebtConcepts';
import {lesson319References,lesson319ReadingList} from './sovereignDebtReferences';
import {sovereignChecks,sovereignGlossary,sovereignInvariants,sovereignInterfaces} from './sovereignDebtStudy';
import {canonicalSovereignDebtStateExample,canonicalSovereignDebtFields,canonicalSovereignDebtAudit} from './sovereignDebtState';
import type {LessonRecord} from './types';
import type {SovereignLabId} from '../components/sovereignLabDefinitions';
export {canonicalSovereignDebtStateExample,canonicalSovereignDebtFields,canonicalSovereignDebtAudit} from './sovereignDebtState';
function Cites({ids}:{ids:readonly number[]}){return <>{ids.map(id=><a key={id} href={`#ref-${id}`}>[{id}] </a>)}</>;}
const sectionIds=['thesis','scope-route',...sovereignConcepts.map(c=>c.id),'dated-support-map','model-map','interactive-lab','sovereign-static-twins','checks-glossary','evidence-boundaries'];
const sourceIds=new Set(lesson319References.map(r=>r.id));
const citations=[...sovereignConcepts.flatMap(c=>c.sourceIds),...sovereignLabs.flatMap(l=>l.sourceIds),...sovereignScenarios.flatMap(s=>s.sourceIds),...sovereignChecks.flatMap(c=>c.sourceIds)];
export const lesson319IntegrityAudit=[
 {key:'27 single-mechanism units, three coherent paragraphs and explicit conditions each',passed:sovereignConcepts.length===27&&sovereignConcepts.every(c=>c.paragraphs.length===3&&c.paragraphs.every(p=>p.length>=90)&&c.boundary.length>=30&&c.sourceIds.length>0)},
 {key:'all section IDs unique, seven C labs attached exactly once with actual IDs',passed:new Set(sectionIds).size===sectionIds.length&&sovereignConcepts.flatMap(c=>c.labIds??[]).length===7&&new Set(sovereignConcepts.flatMap(c=>c.labIds??[])).size===7&&sovereignConcepts.flatMap(c=>c.labIds??[]).every(id=>sovereignLabs.some(l=>l.id===id))},
 {key:'six references with declared reading scope and valid citations, not authority approval',passed:lesson319References.length===6&&citations.every(id=>sourceIds.has(id))&&lesson319References.every(r=>r.use.length>=60&&r.url.startsWith('https://'))},
 {key:'20 checks, 40 decoded terms, 16 invariants and eight interfaces',passed:sovereignChecks.length===20&&sovereignGlossary.length===40&&sovereignInvariants.length===16&&sovereignInterfaces.length===8},
 {key:'all bounded source-contract audits pass; not independent whole-lesson approval',passed:[...sovereignLabAudit,...sovereignScenarioAudit,...canonicalSovereignDebtAudit].every(a=>a.passed)},
] as const;
function Lesson319Content(){return <>
 <noscript><style>{'.lesson-page[data-lesson-id="3.19"] .sovereign-interactive-only,.lesson-page[data-lesson-id="3.19"] #interactive-lab{display:none!important}'}</style><p>脚本已关闭：七个C实验仍有原生展开的固定输入与结果，K1–K10保留题设、答案和两条错路径，引用与机制图也可直接阅读。纸上学习不依赖动态脚本。</p></noscript>
 <section id="thesis" className="lesson-section"><p className="section-kicker">ONE CENTRAL MECHANISM · DATED SUPPORT</p><h2>债务是有日期的承诺；融资报价又会改变承诺的兑现路径。</h2>{sovereignThesis.map(p=><p key={p}>{p}</p>)}<p className="section-sources"><Cites ids={[1,2,6]}/></p></section>
 <section id="scope-route" className="lesson-section"><p className="section-kicker">READING / OBJECT / UNIT PASSPORT</p><h2>先认清欠款、付款与支持各量什么，再问风险怎样进入价格。</h2>
 <p>Master先修是3.17–3.18：前者解释财政处理、实际执行与收入—税基反馈，后者解释央行条件响应、公共费用和跨期承诺。本课不要求零背景读者先补完所有相关学科；公式遇到复利与贴现、期望与协变、会计或时间序列时，按需回查T02/T03/T05/T06/T08，以及3.07–3.08和3.15。正文27个机制单元是这个Subchapter内部的编辑结构，不是另外新增27个课程小章节。</p>
 <p>GDP（gross domestic product）是国内生产总值；用名义GDP衡量债务相对经济规模，不意味着全国GDP都是财政现金。PB（primary balance）是初级余额金额，本课盈余正、赤字负；小写pb是PB除本期名义GDP。SFA（stock-flow adjustment）是存量—流量调整，本课增债正号。GFN（gross financing needs）是声明期间和定义下的总融资需求，不等于已成交发行、净增债务或当前债务存量。利息收入、救助、资产交易与重估在现实表中须逐项桥接，不能因换名重复计算。 <Cites ids={[1,3]}/></p>
 <p>SYN表示独立合成教学单位或情景，不是真实观察。七实验不属于同一国家，输出不自动拼接。率控件用整数基点：100基点等于1个百分点，200表示2%；C7概率50表示50%，m的8000是无量纲万分刻度0.8，不是政策利率或概率。金额上限、有限路径展示域与整数网格服务数值精度，不是现实经济或法律限制。null保留未定义或未识别的含义：零旧债平均费用未定义，与真实主权安全未知都不能填0；域外STOP也不是违约或不可持续判断。</p>
 <p>国际货币基金组织（IMF，International Monetary Fund）的SRDSF（Sovereign Risk and Debt Sustainability Framework）是面向相应市场融资国家的主权风险与债务可持续性框架；GFSM（Government Finance Statistics Manual）是政府财政统计手册。本课核它们指定原文，不运行机构模板或内部概率判断。PIT（point-in-time）要求历史时点真正可得的版本；当前下载旧年文件只能证明本次阅读取得，不能认证历史实时数据。随机贴现因子（SDF，stochastic discount factor）在本文只是进一步模型接口；C7给定有限状态权重，不校准真实SDF。横截条件（TVC，transversality condition）和其他终端限制是对远期资产负债路径的限制，有限十期图不能替无穷期条件作证。</p>
 <div className="precision-note"><span>审稿状态：同版完整正文已通过两位独立审稿人复核</span><p>准确性与教学两位对同一冻结候选分别给出APPROVE，另有该候选67页独立布局PASS。准确性审稿实际重跑997个有限有理案例、30候选值与三种反馈时钟；教学审稿本人270个源级检查、583个浏览器断言和160个补充键盘断言分别通过。审稿批准教材的机制、给定SYN计算、错路径、来源范围及学习体验，不认证真实国家安全、全部无穷期证明、历史PIT、因果、福利或具体法律。正式状态只登记已批准正文身份，不把包装时间或有限通过升级成现实证据。</p></div>
 <p>后文还会遇到消费价格指数（CPI，consumer price index）与外汇（FX，foreign exchange）：前者不是GDP平减指数，后者须落到具体币种与报价。集体行动条款（CAC，collective action clauses）是债券合同修改等法律研究接口，本文不判具体条款效力；信用违约互换（CDS，credit default swap）是信用风险合约接口，本课未导入其市场报价或校准违约概率。先知道简称指哪种对象，不意味着已掌握或认证其完整模型与法律条件。</p>
 </section>
 {sovereignConcepts.map((c,i)=><section id={c.id} key={c.id} className="lesson-section"><p className="section-kicker">{String(i+1).padStart(2,'0')} · CORE MECHANISM</p><h2>{c.title}</h2>{c.paragraphs.map(p=><p key={p}>{p}</p>)}{c.formula?<div className="equation-card"><span>澄清对象的必要算式</span><div><code>{c.formula.expression}</code></div><p>{c.formula.explanation}</p></div>:null}<div className="precision-note"><span>成立条件、反例与跨章接口</span><p>{c.boundary}</p></div>{c.labIds?.map(labId=><SovereignLabStatic key={labId} labId={labId as SovereignLabId}/>)}<p className="section-sources"><b>本机制依据：</b><Cites ids={c.sourceIds}/>{c.sourceNote.replace(/\[\d+\]/g,'')}</p></section>)}
 <section id="dated-support-map" className="lesson-section"><p className="section-kicker">ONE PROMISE / DISTINCT GATES · CONCEPTUAL</p><h2>同一承诺经过四道门，每道门需要自己的证据。</h2><p>下图连接概念，不把C1–C7合成账拼成真实国家。合同决定日期与币种，资产和融资决定当日可用资金，重设与替换把边际条件带入费用，未来财政与资源支持又影响今天的持有判断。会计闭合、条件机制与待识别行为在图中相连，但不能互相顶替。</p><SovereignScopeDiagram/><p className="section-sources"><Cites ids={[1,2,6]}/></p></section>
 <section id="model-map" className="lesson-section"><p className="section-kicker">ACCOUNT / MODEL / JUDGMENT</p><h2>分清三层证据，才能使用复杂地图而不制造万能指标。</h2><div className="evidence-map"><div><h3>统计与可核算账</h3><p>GFSM和SRDSF指定定义帮助确认机构、计价、金额、分母与GFN；本课C1/C3–C6只核明示给定情景。对账成功不生成融资成交、政策效果或安全评级。 <Cites ids={[1,3,6]}/></p></div><div><h3>条件机制与有限反例</h3><p>C2精确有限路径解释未来条件变化；C7逐状态加总解释平均数与匹配。它们另按本课对象推导，不是Bohn回归、完整随机核或无穷期证明。 <Cites ids={[2,4,5]}/></p></div><div><h3>现实判断与可验证研究</h3><p>SRDSF区分压力、基线不稳定和不可持续；真实判断须补可行调整、展期、状态和制度证据。局部研究还须锁事件、期限、口径、历史版本、基线与失败证据，本课未执行这些估计。 <Cites ids={[1,2]}/></p></div></div><p>三层共同服务中心问题，却不互相替代：先知道数正在量谁的哪种承诺，再知道给定账如何变，最后寻找行为与执行的证据。若只把债率、低利率或收益率利差贴成风险等级，就跳过了最重要的中间桥。</p></section>
 <section id="interactive-lab" className="lesson-section"><p className="section-kicker">INTERACTIVE M1–M10</p><h2>先解释所求对象，再从中性数值中作答。</h2><p>每题保留对应C护照与完整输入，三个候选先只显示数值和单位，正确位置分散。题库和后面K题共用排列与诊断，答题后才显示理由。错路径不是随意编造的邻近数，它们分别暴露分母、时钟、存量／融资、币种、日期和状态加总错误。</p><SovereignQuiz/></section>
 <section id="sovereign-static-twins" className="lesson-section"><p className="section-kicker">STATIC K1–K10 / PRINT</p><h2>纸上与无脚本学习也能完整重建推理。</h2><p>先手算并写明单位，再展开答案。每题的ABC顺序与M题一致，答案指出正确候选及两条错误推理；打印时直接保留完整诊断。改变某个题设可以得到另一情景正确值，不意味着原题的错误步骤突然成立。</p><SovereignStaticQuiz/></section>
 <section id="checks-glossary" className="lesson-section"><p className="section-kicker">CHECKS / INTEGRITY / GLOSSARY</p><h2>能指出缺少什么证据，比记住某个安全数字更重要。</h2><div className="check-grid">{sovereignChecks.map((c,i)=><div key={c.question}><details><summary>{String(i+1).padStart(2,'0')} · {c.question}</summary><p>{c.answer} <Cites ids={c.sourceIds}/></p></details><p className="print-only"><b>{String(i+1).padStart(2,'0')} · {c.question}　答案：</b>{c.answer} <Cites ids={c.sourceIds}/></p></div>)}</div><div className="yield-fixture-audit"><span>有限来源完整性与契约检查（不是独立审批）</span><ul>{[...sovereignLabAudit,...sovereignScenarioAudit,...canonicalSovereignDebtAudit,...lesson319IntegrityAudit].map(a=><li key={a.key} className={a.passed?'passed':''}>{a.passed?'PASS':'FAIL'} · {a.key}</li>)}</ul></div><div className="term-grid">{sovereignGlossary.map(([term,meaning,confusion])=><article className="term-card" key={term}><h3>{term}</h3><p>{meaning}</p><em>不可混同：{confusion}</em></article>)}</div></section>
 <section id="evidence-boundaries" className="lesson-section"><p className="section-kicker">STATE / READING / RESEARCH / INTERFACES</p><h2>最终状态保留对象与未知出口，不制造全能偿付答案。</h2><p>canonical有{canonicalSovereignDebtFields.length}个顶层字段，七实验分别保留独立输入身份和结果。唯一直接生产者上下文是3.18已封版对象，十一条路径保留原始对象或值身份，numericCalibration=false；其已批准正文时钟早于本课登记{canonicalSovereignDebtStateExample.scopePassport.registeredAt}。3.17提供财政执行语义，不被重建为另一直接数值生产者。登记时钟不认证历史信息可得性，本课未批准时也不填虚构的批准冻结时钟。</p><div className="precision-note"><span>canonical · {canonicalSovereignDebtStateExample.schemaVersion}</span><p><code>{canonicalSovereignDebtFields.join(', ')}</code>。范围、可用资产、一期债率、有限路径、费用、融资、汇率与状态加权分列；现实反应、承接、银行、央行、服务流、识别和福利保留未知边界，不能从默认返回填出国家评级。</p></div>
 <h3>生产者不变量</h3><ol className="contract-list">{sovereignInvariants.map((r,i)=><li key={r}><b>{String(i+1).padStart(2,'0')}</b><span>{r}</span></li>)}</ol>
 <h3>实际阅读与尚未读取的范围</h3><p>作者实读SRDSF136页中的指定连续原页及Box3原图，不称全算法、全annex或机构模板复现；GFSM470页只读明确列出的机构、计价、余额、债务工具、居住地与期限段，初次截断页另完整重读。两份手册各自的统计范围不被3.18理论外部本金账替代。原PDF只保留私有阅读证据，网页提供官方入口与实际阅读范围，不发布版权全文镜像。 <Cites ids={[1,3]}/></p>
 <p>WP22/16当前28页文字全文、六节、脚注和书目已读，Figure1未看，引用模型未逐篇读；复杂随机核链未完整桥接，所以本文不复制为证明。Bohn工作稿16页全部文字与11尾注已读，表图另文件未读、样本未重估；技术附录9页只读1–6含A1/A2和A3开头、原2–3页已看，7–9及Bohn1995仍待读。原稿与出版身份分列，文件头恢复警告不被自行修复后冒称原出版字节。 <Cites ids={[2,4,5]}/></p>
 <p>2014债务管理指南43页只读指定原页及跨两页Box1和脚注，跨后页的协调段、完整annex、具体法域与衍生品未通读。Blanchard2019只核官方摘要和书目，正文全文待读；其阅读路线不用于未读的量化断言。作者与两位审稿人的个人读取、计算、视觉范围分别记录，不把一个人读过改成所有人全读。 <Cites ids={[6]}/></p>
 <p>来源发行身份、当前取得字节和历史可得版本承担不同任务。当前取得标为1998/2014/2022的文件不保证首发字节相同，更不保证当年已公开同一数据版本。此课没有导入国家债务、历史GDP版本、市场报价、CDS、发行成交或违约目标；所有数值均为声明的独立SYN，真实PIT、预测、因果、福利、法律权限和主权安全仍未认证。</p>
 <h3>把开放风险地图缩成一个研究问题</h3><p>例如固定“当时已知到期结构和可用缓冲，是否增量预测未来一年公开定义的融资压力事件”。先写事件规则与期限，保留非压力样本和基准发生率，再核统计覆盖、公布与修订版本、合约条件；比较全球利率、币种、流动性和持有人约束等替代机制。低信号在压力样本中少见不能倒置成低信号时压力概率低；压力预测也不能改名违约预测。若暂缺资料，就明确未知，不让漂亮合成路径替样本外证据作答。</p>
 <h3>跨章接口</h3><div className="interface-grid">{sovereignInterfaces.map(([name,payload,guardrail])=><article key={name}><span>{name}</span><p><b>传递什么：</b>{payload}</p><p><b>不可跨越：</b>{guardrail}</p></article>)}</div><p>结束时，用自己的话追一条链：承诺首先改变谁的日期资金，持有人如何在约束下反应，报价经哪种合约何时变成公共费用，财政措施如何影响需求与税基，新的融资与支持状态怎样成为下一轮输入。对每条箭头分别问“可对账、条件机制还是待识别”；这才是一张能继续学习、被证据修正的world model。</p>
 </section>
 </>;}
export const lesson319:LessonRecord={slug:'3-19',id:'3.19',chapter:'03',chapterTitle:'Macro State & Financial Conditions',title:'Sovereign Debt & Fiscal Sustainability：日期融资、可行支持与反馈',subtitle:'从合同与统计口径进入精确债率、到期资金和重定价，分清可行财政反应、状态支持、银行—主权与央行信誉，再追风险怎样经持有和融资报价反馈债务路径',readingTime:'正文主线约55–75分钟；C1–C7手算/交互约30–50分钟；M/K十题约20–35分钟，理解检查/术语与复盘约25–40分钟。为学习估时，不靠填字凑时长；经典文献深化另计',prerequisite:'Master：3.17–3.18；按需T02/T03/T05/T06/T08、3.07–3.08、3.15。唯一直接3.18状态只作语义上下文，不作国家统计或数值校准',updatedAt:'2026-09-15',revision:'3.19-r1',reviewStatus:'double-reviewed',reviews:[{kind:'accuracy',completedAt:'2026-09-15',decision:'approved',revision:'3.19-r1',summary:'完整同版正文与来源边界已核；本人重跑997/997有理案例、30候选/20错路、28字段/11身份与三种反馈时钟，无专业阻断。不认证真实国家、PIT、法律或全部无穷期证明。'},{kind:'pedagogy',completedAt:'2026-09-15',decision:'approved',revision:'3.19-r1',summary:'完整同版教学正文已核；本人270源级、583真实浏览器及160补充键盘断言通过。七C、十M/K共享题/三路诊断、390px、无脚本与打印可读；未认证系统读屏或PDF/UA。'}],previous:{slug:'3-18',label:'3.18 Fiscal–Monetary Interaction'},next:{label:'3.20 Exchange Rate 的宏观基础'},sections:[{id:'thesis',label:'核心命题'},{id:'scope-route',label:'阅读与对象护照'},...sovereignConcepts.map(({id,label})=>({id,label})),{id:'dated-support-map',label:'承诺的四道门'},{id:'model-map',label:'账／模型／判断'},{id:'interactive-lab',label:'Interactive M1–M10'},{id:'sovereign-static-twins',label:'Static K1–K10'},{id:'checks-glossary',label:'Checks / Audit / Glossary'},{id:'evidence-boundaries',label:'State / Sources / Interfaces'}],Content:Lesson319Content,references:lesson319References,readingList:lesson319ReadingList,readingListOrder:'source'};
