import type { LessonReading, LessonReference } from './types';

const R = (
  id: number,
  authors: string,
  year: string,
  title: string,
  publication: string,
  url: string,
  use: string,
): LessonReference => ({ id, authors, year, title, publication, url, use, accessedAt: '2026-09-02' });

export const lesson306References: LessonReference[] = [
  R(1, 'Paolo Cavallino, Mathias Drehmann, Richard Finlay and Julie Remache', '2025', 'Monetary Policy Operational Frameworks — A New Taxonomy', 'BIS Quarterly Review, September 2025', 'https://www.bis.org/publications/monetary-policy-operational-frameworks-new-taxonomy', '跨制度primer。支持边际准备金机会成本、超额数量、自治因素和供给方式的分类；不能支持2026名义条款、因果系数或福利排名。'),
  R(2, 'BIS Markets Committee', 'information as of December 2025', 'Monetary Policy Frameworks and Central Bank Market Operations', 'BIS Markets Committee Compendium', 'https://www.bis.org/committees/mc/compendium/overview', '跨国官方汇编。支持统一比较字段与原始央行入口；数据库时点不是2026-09-02实时快照，原央行文件仍为最终依据。'),
  R(3, 'Board of Governors of the Federal Reserve System', '2026', 'Federal Reserve Issues FOMC Statement', 'Press Release, July 29, 2026', 'https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm', '正式政策决定。支持3.50%–3.75%目标区间及ample-reserves立场；不提供完整实施参数。'),
  R(4, 'Board of Governors of the Federal Reserve System', '2026', 'Implementation Note Issued July 29, 2026', 'Federal Reserve, effective July 30, 2026', 'https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a1.htm', '正式实施指令。支持IORB 3.65%、standing overnight repo 3.75%、ON RRP 3.50%、160bn limit、primary credit 3.75%及资产指令；不能识别宏观因果效果。'),
  R(5, 'Federal Reserve Bank of New York', 'current portal', 'Monetary Policy Implementation', 'Markets and Policy Implementation', 'https://www.newyorkfed.org/markets/domestic-market-operations/monetary-policy-implementation', '官方框架入口。支持ample-reserves框架与各工具角色；不能替代逐次implementation note或提供永久数量阈值。'),
  R(6, 'Board of Governors of the Federal Reserve System', 'updated 2025', 'Interest on Reserve Balances (IORB) Frequently Asked Questions', 'Federal Reserve', 'https://www.federalreserve.gov/monetarypolicy/iorb-faqs.htm', '官方说明。支持准备金余额定义、IORB主锚与ON RRP辅助作用；不提供结构系数。'),
  R(7, 'Federal Reserve Bank of New York', 'current portal', 'Effective Federal Funds Rate', 'Reference Rates', 'https://www.newyorkfed.org/markets/reference-rates/effr.html', '官方数据入口。支持EFFR underlying与volume-weighted median；不是因果证据，也不代表全部美元隔夜市场。'),
  R(8, 'Federal Reserve Bank of New York', 'updated April 6, 2026', 'Additional Information about Reference Rates Administered by the New York Fed', 'Reference-rate Methodology', 'https://www.newyorkfed.org/markets/reference-rates/additional-information-about-reference-rates', '官方方法。支持分位数、rounding、exclusions与contingency；不能代表全部美元隔夜交易。'),
  R(9, 'Sriya Anbil, Alyssa Anderson and Zeynep Senyuz', '2020', 'What Happened in Money Markets in September 2019?', 'FEDS Notes', 'https://doi.org/10.17016/2380-7172.2527', '事件分析。支持税期、国债结算、准备金、repo/fed-funds和摩擦的联合机制；staff叙述不证明唯一结构解释。'),
  R(10, 'Federal Open Market Committee', '2019', 'Minutes of the Federal Open Market Committee, January 29–30, 2019', 'Federal Reserve, January 2019', 'https://www.federalreserve.gov/monetarypolicy/files/fomcminutes20190130.pdf', '正式会议记录。支持长期实施框架讨论与ample选择背景；历史讨论不是当前参数。'),
  R(11, 'Gara Afonso, Domenico Giannone, Gabriele La Spada and John C. Williams', '2022; revised 2025', 'Scarce, Abundant, or Ample? A Time-Varying Model of the Reserve Demand Curve', 'Federal Reserve Bank of New York Staff Report No. 1019', 'https://www.newyorkfed.org/research/staff_reports/sr1019', '时间变动模型。支持非线性与实时斜率估计；估计阈值不是政策规则、法定阈值或跨国常数。'),
  R(12, 'Gara Afonso, Gabriele La Spada, Thomas M. Mertens and John C. Williams', '2023; revised 2025', 'The Optimal Supply of Central Bank Reserves under Uncertainty', 'Federal Reserve Bank of New York Staff Report No. 1077', 'https://doi.org/10.59576/sr.1077', '理论研究。支持利率控制与市场中介之间的权衡；模型最优不证明现实央行偏好。'),
  R(13, 'Adam Copeland, Darrell Duffie and Yilin David Yang', '2025 journal issue; online 2024', 'Reserves Were Not So Ample After All', 'Quarterly Journal of Economics 140(1): 239–281', 'https://doi.org/10.1093/qje/qjae034', '交易与网络研究。支持核心中介余额、付款时点和网络约束；美国样本不能直接外推其他制度。'),
  R(14, 'Jerome H. Powell', '2019', 'Data-dependent Monetary Policy in an Evolving Economy', 'Federal Reserve Speech, October 8, 2019', 'https://www.federalreserve.gov/newsevents/speech/powell20191008a.htm', '官方讲话。支持储备管理购买与LSAP目的区分；不证明储备管理购买没有资产价格外溢。'),
  R(15, 'European Central Bank', '2024', 'ECB Announces Changes to the Operational Framework for Implementing Monetary Policy', 'ECB Press Release, March 13, 2024', 'https://www.ecb.europa.eu/press/pr/date/2024/html/ecb.pr240313_1~a3a50a9add.en.html', '官方review结果。支持DFR附近引导、弹性流动性与框架演进；不能冻结2026名义利率。'),
  R(16, 'European Central Bank', '2026', 'Monetary Policy Decisions', 'ECB, July 23, 2026', 'https://www.ecb.europa.eu/press/pr/date/2026/html/ecb.mp260723~29f24d99bc.en.html', '截至审计冻结时点的最新正式决定。支持DFR/MRO/MLF维持2.25/2.40/2.65%；不能单独证明6月17日初始生效日。'),
  R(17, 'European Central Bank', '2026', 'Monetary Policy Decisions', 'ECB, June 11, 2026', 'https://www.ecb.europa.eu/press/pr/date/2026/html/ecb.mp260611~4d41bd5e83.en.html', '正式决定。支持三率升至2.25/2.40/2.65%并自6月17日生效；当前性须与7月决定配合。'),
  R(18, 'European Central Bank', '2026', 'Decisions Taken by the Governing Council of the ECB (in Addition to Decisions Setting Interest Rates)', 'ECB, May 4, 2026; excess-reserve-remuneration section', 'https://www.ecb.europa.eu/press/govcdec/otherdec/2026/html/ecb.gc260504~07dc9bac72.en.html', '官方治理决定。支持6月17日起合格货币政策对手方的excess reserves按DFR计息；不支持required reserves或所有主体。'),
  R(19, 'European Central Bank', 'current methodology', 'The Euro Short-term Rate (€STR)', 'ECB', 'https://www.ecb.europa.eu/stats/financial_markets_and_interest_rates/euro_short-term_rate/html/eurostr_overview.en.html', '官方方法。支持underlying、MMSR、两端各25%成交量trimming与contingency；€STR不等于DFR或全部欧元隔夜市场。'),
  R(20, 'Bank of England', 'last updated July 13, 2026', 'Bank of England Market Operations Guide: Our Objectives', 'Bank of England', 'https://www.bankofengland.co.uk/markets/bank-of-england-market-operations-guide/our-objectives', '官方操作目标。支持repo-led、demand-driven转型；不能替代工具定价通知。'),
  R(21, 'Bank of England', 'last updated July 29, 2026', 'Bank of England Market Operations Guide: Our Tools', 'Bank of England', 'https://www.bankofengland.co.uk/markets/bank-of-england-market-operations-guide/our-tools', '官方工具说明。支持STR、ILTR、OSF、DWF、准入与抵押品；易变pricing须回到market notice。'),
  R(22, 'Bank of England', '2026', 'Report on the Bank’s Official Market Operations March 2025–February 2026', 'Bank of England, June 25, 2026', 'https://www.bankofengland.co.uk/sterling-monetary-framework/report-2025-26', '官方年度报告。支持repo-led转型与facility use；报告期早于访问日，不能作为实时参数。'),
  R(23, 'Bank of England', 'current methodology', 'SONIA Key Features and Policies', 'Bank of England', 'https://www.bankofengland.co.uk/markets/sonia-benchmark/sonia-key-features-and-policies', '官方方法。支持underlying、eligible transactions与central-50% trimmed mean；不能代表secured sterling市场。'),
  R(24, 'Bank of England', '2026', 'Changes to Collateral Eligibility in the Sterling Monetary Framework', 'Market Notice, June 11, 2026', 'https://www.bankofengland.co.uk/markets/market-notices/2026/june/collateral-eligibility-in-the-smf-11-june-2026', '官方条款。支持collateral eligibility与haircut变化；不证明宏观立场改变。'),
  R(25, 'Bank of Canada', 'current framework', 'Framework for Market Operations and Liquidity Provision', 'Bank of Canada', 'https://www.bankofcanada.ca/markets/market-operations-liquidity-provision/framework-market-operations-liquidity-provision/', '官方框架。支持floor、30bp band、facilities、OR/ORR和自2025-01-30的target−5bp deposit条款；旧概括须服从日期明确条款。'),
  R(26, 'Bank of Canada', '2026', 'Bank of Canada Maintains the Policy Rate at 2¼%', 'Fixed Announcement Date Press Release, July 15, 2026', 'https://www.bankofcanada.ca/2026/07/fad-press-release-2026-07-15/', '审计冻结时点最近已发布决定。支持target 2.25%、Bank Rate 2.50%、deposit 2.20%；不能声称9月2日决定已发布。'),
  R(27, 'Bank of Canada', 'current methodology and data', 'Canadian Overnight Repo Rate Average (CORRA)', 'Bank of Canada', 'https://www.bankofcanada.ca/rates/interest-rates/corra/', '官方benchmark入口。支持CORRA的general-collateral repo对象；CORRA不是政策目标本身。'),
  R(28, 'Jean-Sébastien Fontaine, Neil Maru and Sofia Tchamova', '2026', 'A Buoy on Funding Tides: How Client Repo Demand and Dealer Constraints Lifted CORRA', 'Bank of Canada Staff Analytical Paper 2026-15', 'https://www.bankofcanada.ca/2026/05/staff-analytical-paper-2026-15/', 'Staff研究。支持2025年client repo demand与dealer constraints机制；不代表唯一官方解释或普遍系数。Publisher-declared DOI为10.34989/sap-2026-15。'),
  R(29, 'David Jacobs', '2026', 'The Road to Ample — Towards a Demand-driven Liquidity Regime', 'Reserve Bank of Australia Speech, August 25, 2026', 'https://www.rba.gov.au/speeches/2026/sp-so-2026-08-25.html', '官方讲话。支持约200bn ES、70–100bn调查区间、尚未抵达与OMO自动补位；时点状态会过期。'),
  R(30, 'Reserve Bank of Australia', 'updated July 21, 2026', 'Cash Rate Methodology — Overview', 'Reserve Bank of Australia', 'https://www.rba.gov.au/mkt-operations/resources/cash-rate-methodology/', '官方方法。支持AONIA underlying与weighted average；不能代表repo市场。'),
  R(31, 'Reserve Bank of Australia', 'current operational page', 'Domestic Market Operations and Liquidity Facilities', 'Reserve Bank of Australia', 'https://www.rba.gov.au/mkt-operations/domestic-market-ops-and-standing-facilities.html', '官方操作页。支持ES=target−10bp、full-allotment OMO、standing facilities与2027 open-repo transition；不能由正式框架名断言当前余额已需求决定。'),
  R(32, 'Laurence Bristow', '2024', 'Modelling Reserve Demand with Deposits and the Cost of Collateral', 'Reserve Bank of Australia Research Discussion Paper 2024-08', 'https://www.rba.gov.au/publications/rdp/2024/2024-08/full.html', '经验与方法研究。支持存款、抵押品、IV和非线性；澳洲估计不是全球参数。'),
  R(33, 'Reserve Bank of Australia Monetary Policy Board', '2026', 'Statement by the Monetary Policy Board: Monetary Policy Decision', 'Media Release No. 2026-19, August 11, 2026', 'https://www.rba.gov.au/media-releases/2026/mr-26-19.html', '正式政策决定。支持cash-rate target 4.35%；不提供完整实施条款。'),
  R(34, 'Bank of Japan', '2026', 'Change in the Guideline for Money Market Operations', 'Bank of Japan, June 16, 2026', 'https://www.boj.or.jp/en/mopo/mpmdeci/mpr_2026/k260616a.pdf', '正式操作指引。支持6月17日起call target around 1.0%、CDF 1.0%、basic loan 1.25%；around不是硬点目标。'),
  R(35, 'Financial Markets Department, Bank of Japan', '2026', 'Market Operations in Fiscal 2025', 'Bank of Japan, August 12, 2026', 'https://www.boj.or.jp/en/research/brp/mor/mor260812.htm', '官方操作报告。支持call rate略低CDF与套利参与者机制；FY2025 spread不是未来常数。'),
  R(36, 'Bank of Japan', 'methodology; accessed 2026', 'Explanation of Statistics on Call Money Market', 'Bank of Japan', 'https://www.boj.or.jp/en/statistics/outline/exp/exmenu_m.pdf', '官方方法。支持指定信息提供者与brokered/direct call数据中的volume-weighted average；不能代表全部日元隔夜交易。'),
  R(37, 'Bank of Japan', 'current portal', 'Complementary Deposit Facility', 'Bank of Japan', 'https://www.boj.or.jp/en/mopo/measures/mkt_ope/oth_a/index.htm', '官方facility入口。支持工具条款入口；名义数字与生效日须由当次guideline确认。'),
  R(38, '中国人民银行货币政策分析小组', '2026', '2026年第二季度中国货币政策执行报告', '中国人民银行，2026年8月12日', 'https://www.pbc.gov.cn/zhengcehuobisi/125207/125227/125957/2026nhbzczxbg/2026081218435062865/index.html', '季度官方报告。支持7天逆回购主要政策率、DR001转向、±25bp临时工具和隔夜逆回购；不能证明9月2日当日名义利率。'),
  R(39, '中国人民银行货币政策分析小组', '2024', '2024年第二季度中国货币政策执行报告：专栏二 进一步健全市场化的利率调控机制', '中国人民银行，2024年8月9日', 'https://www.pbc.gov.cn/zhengcehuobisi/125207/125227/125957/5347949/2025100917195573922/index.html', '历史制度起源。支持固定利率、数量招标与临时隔夜工具的2024改革；不能支持2026当前条款。'),
  R(40, '中国人民银行', '2020', '参与国际基准利率改革和健全中国基准利率体系', '中国人民银行，2020年8月31日', 'https://www.pbc.gov.cn/zhengcehuobisi/125207/125213/125440/125835/1be3793689194793915ffe8a80f1984f/2020083117120579027.pdf', '官方制度背景。支持DR underlying与基准利率体系；历史规模和规则须另验。'),
  R(41, '中国人民银行', 'current portal', '货币政策工具', '中国人民银行', 'https://www.pbc.gov.cn/zhengcehuobisi/125207/125213/index.html', '官方公告入口。支持工具文件检索；单项公告不能替代综合框架。'),
  R(42, 'William Poole', '1968', 'Commercial Bank Reserve Management in a Stochastic Model: Implications for Monetary Policy', 'Journal of Finance 23(5): 769–791', 'https://doi.org/10.1111/j.1540-6261.1968.tb00316.x', '经典理论。支持随机收盘余额与准备金需求基础；不能作为现行制度条款。'),
  R(43, 'James D. Hamilton', '1996', 'The Daily Market for Federal Funds', 'Journal of Political Economy 104(1): 26–56', 'https://doi.org/10.1086/262016', '日度市场研究。支持维持期内日期不完全替代和交易摩擦；历史Fed不能直接外推现代floor。'),
  R(44, 'James D. Hamilton', '1997', 'Measuring the Liquidity Effect', 'American Economic Review 87(1): 80–97', 'https://www.jstor.org/stable/2950855', '识别研究。支持高频流动性效应的局部识别；特定历史制度估计不是现代系数。'),
  R(45, 'William C. Whitesell', '2006', 'Interest-rate Corridors and Reserves', 'Journal of Monetary Economics 53(6): 1177–1195', 'https://doi.org/10.1016/j.jmoneco.2005.03.013', '理论模型。支持走廊、averaging与波动权衡；原型边界不是现实硬规则。'),
  R(46, 'Todd Keister, Antoine Martin and James McAndrews', '2008', 'Divorcing Money from Monetary Policy', 'Federal Reserve Bank of New York Economic Policy Review 14(2): 41–56', 'https://www.newyorkfed.org/medialibrary/media/research/epr/08v14n2/0809keis.pdf', '理论与制度分析。支持付息准备金下钱量与短端率分离；不支持无限准备金无副作用。'),
  R(47, 'Aleksander Berentsen and Cyril Monnet', '2008', 'Monetary Policy in a Channel System', 'Journal of Monetary Economics 55(6): 1067–1080', 'https://doi.org/10.1016/j.jmoneco.2008.07.002', '一般均衡模型。支持channel/corridor逻辑；不是现实制度事实。'),
  R(48, 'Michael McLeay, Amar Radia and Ryland Thomas', '2014', 'Money Creation in the Modern Economy', 'Bank of England Quarterly Bulletin 2014 Q1', 'https://www.bankofengland.co.uk/quarterly-bulletin/2014/q1/money-creation-in-the-modern-economy', '央行官方会计说明。支持商业银行贷款通常同步创造贷款资产与借款人存款，以及准备金不按固定货币乘数机械限制逐笔贷款；不能支持2026贷款数量、监管约束或信用因果。'),
  R(49, 'Claudio Borio and Piti Disyatat', '2009', 'Unconventional Monetary Policies: An Appraisal', 'BIS Working Paper No. 292', 'https://www.bis.org/publ/work292.htm', '综述。支持按目的与渠道区分资产负债表政策；不识别单项因果。此记录只对应2009 BIS版本。'),
  R(50, 'Joseph Gagnon, Matthew Raskin, Julie Remache and Brian Sack', '2011', 'Large-Scale Asset Purchases by the Federal Reserve: Did They Work?', 'Federal Reserve Bank of New York Economic Policy Review 17(1)', 'https://www.newyorkfed.org/medialibrary/media/research/epr/11v17n1/1105gagn.pdf', '事件与时间序列证据。支持LSAP期限和供给渠道；不能把所有购买自动归为QE。'),
  R(51, 'Gara Afonso, Marco Cipriani, Adam Copeland, Anna Kovner, Gabriele La Spada and Antoine Martin', '2020', 'The Market Events of Mid-September 2019', 'Federal Reserve Bank of New York Staff Report No. 918', 'https://www.newyorkfed.org/research/staff_reports/sr918', '事件研究。支持余额分布、interbank frictions与dealer intermediation；不提供普遍阈值。'),
  R(52, 'Bank of Japan Policy Board', '2026', 'Statement on Monetary Policy', 'Bank of Japan, July 31, 2026', 'https://www.boj.or.jp/en/mopo/mpmdeci/mpr_2026/k260731a.pdf', '正式政策决定。支持7月维持uncollateralized overnight call rate around 1.0%；CDF和basic-loan数字仍由6月guideline确认。'),
  R(53, 'David Lopez-Salido and Annette Vissing-Jørgensen', 'current version September 18, 2023', 'Reserve Demand, Interest Rate Control, and Quantitative Tightening', 'Working Paper, ECB-hosted conference version', 'https://www.ecb.europa.eu/press/conferences/shared/pdf/20231109_money_markets/Vissing-Jorgensen_paper.en.pdf', '研究论文。支持convenience yield、存款与balance-sheet cost；不是官方阈值或最终期刊版本。'),
  R(54, 'Viral V. Acharya, Rahul S. Chauhan, Raghuram G. Rajan and Sascha Steffen', '2023; revised 2024', 'Liquidity Dependence and the Waxing and Waning of Central Bank Balance Sheets', 'NBER Working Paper No. 31050', 'https://doi.org/10.3386/w31050', '经验研究。支持央行余额与银行流动性行为的内生反馈；跨制度解释仍需边界。'),
  R(55, 'Darrell Duffie and Arvind Krishnamurthy', '2016', 'Pass-Through Efficiency in the Fed’s New Monetary Policy Setting', 'Federal Reserve Bank of Kansas City, Jackson Hole Symposium 2016', 'https://www.kansascityfed.org/documents/7030/Duffie_JH2016.pdf', '市场分割分析。支持利率离散与pass-through frictions；不能提供当前定量系数，也不应与其他同编号论文混淆。'),
  R(56, 'Jane E. Ihrig, Zeynep Senyuz and Gretchen C. Weinbach', '2020', 'The Fed’s “Ample-Reserves” Approach to Implementing Monetary Policy', 'Finance and Economics Discussion Series 2020-022', 'https://doi.org/10.17016/FEDS.2020.022', 'Fed staff框架。支持scarce/ample/abundant图形与工具；不能当跨国taxonomy。'),
  R(57, 'Zhuohui Chen, Nikolaos Kourentzes and Romain Veyrune', '2023', 'Modeling the Reserve Demand to Facilitate Central Bank Operations', 'IMF Working Paper WP/23/179', 'https://doi.org/10.5089/9798400253348.001', '方法研究。支持非线性函数、预测区间与模型选择；不能消除内生性或结构漂移。'),
  R(58, 'Pontus Åberg, Marco Corsi, Vincent Grossmann-Wirth, Tom Hudepohl, Yvo Mudde, Tiziana Rosolin and Franziska Schobert', '2021', 'Demand for Central Bank Reserves and Monetary Policy Implementation Frameworks: The Case of the Eurosystem', 'ECB Occasional Paper No. 282', 'https://www.ecb.europa.eu/pub/pdf/scpops/ecb.op282~6017392312.en.pdf', 'Eurosystem研究。支持准备金需求移动与corridor/floor比较；样本早于2024/2026框架调整。'),
  R(59, 'Basel Committee on Banking Supervision', 'current consolidated standard', 'Liquidity Coverage Ratio — LCR30 High-quality Liquid Assets', 'Basel Framework', 'https://www.bis.org/committees/bcbs/basel-framework/standard/lcr', '动态监管标准。支持HQLA资格与monetisation testing；不要求统一准备金比例，也不是货币政策框架。'),
  R(60, 'Committee on Payment and Settlement Systems and Technical Committee of IOSCO', '2012', 'Principles for Financial Market Infrastructures', 'CPSS–IOSCO, CPMI Papers No. 101', 'https://www.bis.org/publications/principles-financial-market-infrastructures', '支付与结算基础。支持支付、清算、结算风险和最终性；不提供准备金需求定量或利率控制规则。'),
];

export const lesson306ReadingList: LessonReading[] = [
  {
    title: 'BIS 2025：用两维替代框架名', scope: '边际机会成本、超额准备金数量和供给方式。', reason: '先建立跨制度同字段语言，再看各央行自称什么。',
    url: lesson306References[0].url, group: 'core', guide: '读primer、two dimensions与Box B；不要抄图制作2026排名。',
  },
  {
    title: '从政策决定到实施指令', scope: '并读Fed statement与implementation note。', reason: '训练target、IORB、standing repo、ON RRP、资产指令与effective date分栏。',
    url: lesson306References[2].url, group: 'systems', guide: '把两份文件逐字段比较；不要把技术条款重复计作多个政策冲击。',
    links: [{ label: 'FOMC Statement', url: lesson306References[2].url }, { label: 'Implementation Note', url: lesson306References[3].url }],
  },
  {
    title: 'EFFR 到底测什么', scope: '合格交易、volume-weighted median、分位数与contingency。', reason: '理解benchmark不是央行牌价，也不是市场全部交易。',
    url: lesson306References[6].url, group: 'evidence', guide: '手算一个weighted median，再记录methodology version与发布时钟。',
    links: [{ label: 'EFFR Portal', url: lesson306References[6].url }, { label: 'Methodology', url: lesson306References[7].url }],
  },
  {
    title: 'Poole 的随机准备金模型', scope: '收盘不确定性、便利与准备金需求。', reason: '理解走廊／地板图形为何从边际短缺概率产生。',
    url: lesson306References[41].url, group: 'models', guide: '列出模型假设，再标出现代支付与监管加入了哪些摩擦。',
  },
  {
    title: 'Averaging 与日度资金市场', scope: '跨日替代、维持期末与走廊。', reason: '说明平均机制为何缓冲冲击却不保证固定率。',
    url: lesson306References[42].url, group: 'models', guide: '并读Hamilton 1996与Whitesell 2006，分开历史制度与一般机制。',
    links: [{ label: 'Hamilton 1996', url: lesson306References[42].url }, { label: 'Whitesell 2006', url: lesson306References[44].url }],
  },
  {
    title: '付息准备金为何分离钱量与立场', scope: '地板系统与边际报酬。', reason: '理解大量准备金下仍可控制短端，同时保留leaky-floor反例。',
    url: lesson306References[45].url, group: 'models', guide: '写出模型中的无摩擦条件，再用19、23、25节逐一放松。',
  },
  {
    title: '实时估计 scarce、ample 与 abundant', scope: '时间变动需求曲线和函数选择。', reason: '防止寻找永久美元阈值。',
    url: lesson306References[10].url, group: 'evidence', guide: '比较实时斜率、置信区间和结构漂移；再读IMF函数比较。',
    links: [{ label: 'NY Fed SR1019', url: lesson306References[10].url }, { label: 'IMF WP/23/179', url: lesson306References[56].url }],
  },
  {
    title: '2019 美国：数量、网络与付款时点', scope: '税款、国债结算、准备金、repo、分布和交易关系。', reason: '用多机制而非神奇阈值重建压力事件。',
    url: lesson306References[8].url, group: 'evidence', guide: '并读S09、S13、S51；三者不是重复证据，而是事件、交易网络与细节互补。',
    links: [{ label: 'FEDS Note', url: lesson306References[8].url }, { label: 'QJE', url: lesson306References[12].url }, { label: 'NY Fed SR918', url: lesson306References[50].url }],
  },
  {
    title: 'ECB 弹性混合框架', scope: 'DFR、MRO、excess remuneration与€STR。', reason: '解释为什么€STR可以低于DFR，又不把ECB永久叫纯地板。',
    url: lesson306References[14].url, group: 'systems', guide: '分开结构review、最新决定、生效沿革、余额资格与benchmark方法。',
    links: [{ label: 'Operational Review', url: lesson306References[14].url }, { label: 'Latest Decision', url: lesson306References[15].url }, { label: '€STR', url: lesson306References[18].url }],
  },
  {
    title: 'BoE repo-led 转型', scope: 'STR、ILTR、OSF/DWF与collateral。', reason: '观察需求驱动供给如何在长期资产退出时接棒。',
    url: lesson306References[19].url, group: 'systems', guide: '比较目标、工具、年度使用与抵押品通知；repo取用增长不等于宽松。',
  },
  {
    title: '加拿大 floor 与 CORRA 压力', scope: 'target−5bp、30bp band、dealer与client repo demand。', reason: '说明官方floor名称和教科书零spread并不相同。',
    url: lesson306References[24].url, group: 'systems', guide: '以日期明确条款覆盖网页旧概括，并把target与CORRA分栏。',
    links: [{ label: 'Framework', url: lesson306References[24].url }, { label: 'CORRA Study', url: lesson306References[27].url }],
  },
  {
    title: 'RBA 的 road to ample', scope: '正式design、当前数量状态与full-allotment OMO。', reason: '严格区分“已经采用的框架”和“尚未抵达的稳态”。',
    url: lesson306References[28].url, group: 'systems', guide: '把200bn余额与70–100bn调查区间标成时点信息，不当永久阈值。',
  },
  {
    title: 'BoJ 的 soft floor', scope: 'CDF资格、call-market贷款人与around target。', reason: '从准入与成本解释细小负spread。',
    url: lesson306References[34].url, group: 'systems', guide: '把6月条款、7月决定、FY2025经验和统计方法四层分开。',
  },
  {
    title: 'PBOC 短端调控演进', scope: '7-day reverse repo、DR001、临时O/N、SLF、RRR与MLF角色变化。', reason: '避免强套Fed target-range模板。',
    url: lesson306References[37].url, group: 'systems', guide: '用2024报告解释起源，用2026Q2解释当前机制；名义值缺证时不补猜。',
    links: [{ label: '2026 Q2', url: lesson306References[37].url }, { label: '2024 Q2 Origin', url: lesson306References[38].url }],
  },
  {
    title: '便利与最优准备金供给', scope: 'rate control与market disintermediation。', reason: '把“更多准备金更稳定”改写为有代价的条件命题。',
    url: lesson306References[11].url, group: 'models', guide: '列出设施价格、市场交易与不确定性的假设；模型最优不等于官方偏好。',
  },
  {
    title: '存款、抵押品与准备金需求', scope: '需求移动、相对价值和balance-sheet cost。', reason: '把quantity effect从共同需求变化中分离。',
    url: lesson306References[31].url, group: 'evidence', guide: '并读RBA估计、Lopez-Salido/Vissing-Jørgensen与Acharya等，逐项标识外推边界。',
  },
  {
    title: '储备管理、QE 与资产负债表政策', scope: 'purpose、duration、signal与market functioning。', reason: '同一T-account不应决定政策标签。',
    url: lesson306References[13].url, group: 'core', guide: '并读Powell、Borio–Disyatat与Gagnon等，写出没有自治缺口时的反事实。',
  },
  {
    title: '研究设计工作坊', scope: '供给误差、threshold、eligibility、network与多时间戳。', reason: '把world model压成局部、可观察、可证伪的边。',
    url: lesson306References[10].url, group: 'evidence', guide: '任选一条边，写estimand、单位、cutoff、排除限制、替代机制和falsification test。',
  },
];
