import type { LessonReading, LessonReference } from './types';

/** Research-backed draft resources. This file is not an approval or a registered lesson. */
export const lesson317References: LessonReference[] = [
  { id: 1, authors: 'U.S. Bureau of Economic Analysis', year: '2010／页面修订2025-03-19', accessedAt: '2026-09-15', title: 'BEA seems to have several different measures of government spending. What are they for and what do they measure?', publication: '官方FAQ552，完整页面核读；未保留原HTML字节。', url: 'https://www.bea.gov/help/faq/552', use: '支持：GDP中的政府消费和总投资不等于预算总支出；转移、利息、补贴及部分资本型交易的计量口径需分开。不支持：会计恒等式证明财政干预的新增真实产出、所有国家预算统计与美国NIPA完全一致。' },
  { id: 2, authors: 'Congressional Budget Office', year: '2024-11-07', accessedAt: '2026-09-15', title: 'Effects of Automatic Stabilizers on the Federal Budget: 2024 to 2034', publication: '官方完整HTML60970及landing60662核读，图表数值未视觉复算，未保留附件PDF／HTML字节。经济信息截止2024-05-02、法律截止2024-05-12，June2024基线，联邦财政年度。', url: 'https://www.cbo.gov/publication/60970', use: '支持：既有税制和资格规则的自动反馈不同于新立法；周期调整后赤字仍可能受主动政策、资本利得与测量影响；潜在GDP为最大可持续产出。不支持：调整后赤字是已识别外生冲击、2024预测为2026当前事实、所有转移都自动稳定、CBO购买与利息不自动反应假设为普适定理。' },
  { id: 3, authors: 'Olivier Blanchard & Roberto Perotti', year: '2002（实读April2001作者稿）', accessedAt: '2026-09-15', title: 'An Empirical Characterization of the Dynamic Effects of Changes in Government Spending and Taxes on Output', publication: 'The Quarterly Journal of Economics117(4):1329–1368，DOI:10.1162/003355302320935043；出版身份核查。实际阅读51页April2001作者稿PDF1–9、17–21，方法及预期部分；final全文未取得，未确认全文等价。NBER页面v107元数据错误不采用。', url: 'https://academic.oup.com/qje/article-abstract/117/4/1329/1875961', use: '支持：制度弹性、税款时滞和季度内裁量反应限制用于结构VAR识别；购买与税收减转移及净利息是特定聚合；剥离自动项后仍需其他限制；预期政策需更强识别。不支持：裁量自动等于外生、所有季度政策不反应、b1=0适用于转移、未读final点估计及稳健性。' },
  { id: 4, authors: 'Valerie A. Ramey', year: '2011', accessedAt: '2026-09-15', title: 'Can Government Purchases Stimulate the Economy?', publication: 'Journal of Economic Literature49(3):673–685，DOI:10.1257/jel.49.3.673；作者当前Stanford主页链接的期刊排版PDF1–13及追加citation页全文核读、原字节留档。', url: 'https://www.aeaweb.org/articles?id=10.1257/jel.49.3.673', use: '支持：购买类型、持续性、融资、资源、货币反应与识别方法限定乘数；地方相对效应不等于全国总效应；同质简化模型的地方反例与GDP／福利分离。不支持：2011综述提供当前任何国家默认系数、军事新闻天然有效工具、地方就业／收入乘数等同国家GDP元／元。本课不导入综述表内估计作为参数。' },
  { id: 5, authors: 'Nicoletta Batini, Luc Eyraud, Lorenzo Forni & Anke Weber', year: 'September2014', accessedAt: '2026-09-15', title: 'Fiscal Multipliers: Size, Determinants, and Use in Macroeconomic Projections', publication: 'IMF Technical Notes and Manuals14/04。33页官方PDF主文、Appendix I–III及参考全文文字核读；封面题名与作者另核，编号见正文页脚、日期见PDF第2页授权页。14/03元数据误标不采用；作者观点不等于IMF政策。', url: 'https://www.imf.org/external/pubs/ft/tnm/2014/tnm1404.pdf', use: '支持：impact／horizon分母区别、进口／资源／货币／信用条件框架；无同一处理效应基线、旧冲击滞后与重复计数、叙事方法和工具排序边界。不支持：bucket启发式分数是因果估计、异常状态可无限加成、Table9为观察数据、潜在GDP／Hodrick–Prescott（HP）滤波为无政策PIT基线、GDP乘数等于福利或债务安全。本课不采用其分组参数。' },
  { id: 6, authors: 'Valerie A. Ramey', year: '2011', accessedAt: '2026-09-15', title: 'Identifying Government Spending Shocks: It’s All in the Timing', publication: 'The Quarterly Journal of Economics126(1):1–50，DOI:10.1093/qje/qjq008；作者当前Stanford主页的final PDF留档，实际仅核读PDF／期刊1–5：引言及§II开头；Figure I未做图形数值复算。', url: 'https://academic.oup.com/qje/article-abstract/126/1/1/1902509', use: '支持：政策新闻、专业预测与实际购买残差可能不同步，处理时间不能默认预算执行日。不支持：仅凭引言批准全部识别、完整样本稳健性或最终估计；本课不导入摘要数量结果。' },
  { id: 7, authors: 'U.S. Bureau of Economic Analysis', year: '官方方法页／修订2026-03-27', accessedAt: '2026-09-15', title: 'Gross Domestic Product Release—Additional Information', publication: '完整官方页面核读，重点Definitions、Statistical conventions及Updates；未导入或复算其修订表。', url: 'https://www.bea.gov/news/gdp-release-additional-information', use: '支持：GDP支出侧定义、私人储蓄定义、季度季调年率水平与增长率区分、链式实际量非加总、发布vintage有修订。不支持：原始季度变动为因果响应、所有组成链式美元可无残差对账、预算年度等同日历季度。' },
  { id: 8, authors: 'U.S. Bureau of Economic Analysis', year: '官方术语页／修订2018-04-09', accessedAt: '2026-09-15', title: 'Chained-dollar estimate', publication: '完整官方词条核读；定义来源而非财政识别论文。', url: 'https://www.bea.gov/help/glossary/chained-dollar-estimate', use: '支持：链式美元表达系列增长率，但非基期一般不具组成项可加性。不支持：不能计算同一系列跨期累计、实际值没有经济意义或必须改用名义乘数；研究仍需一致的量纲与聚合方法。' },
  { id: 9, authors: 'U.S. Bureau of Economic Analysis', year: '2006／修订2018-04-24', accessedAt: '2026-09-15', title: 'Why does BEA publish percent changes in quarterly series at annual rates?', publication: '完整FAQ122核读，原增长率复利定义；未复述页面示例的过时经济数值。', url: 'https://www.bea.gov/help/faq/122', use: '支持：季度环比增长率年化使用四次复利，不是把水平或百分比简单混合。不支持：年化增长率为全年已实现增长、乘数与增长百分点可直接互换。' },
  { id: 10, authors: 'U.S. Census Bureau', year: '官方方法页／修订2021-10-08', accessedAt: '2026-09-15', title: 'Seasonal Adjustment Questions and Answers — question15: annual rates', publication: '仅完整核读第15问及相关第16–17问；未宣称全408行或全部季调软件方法已读。', url: 'https://www.census.gov/data/software/x13as/seasonal-adjustment-questions-answers.html', use: '支持：季度季调年率水平为对应季调季度量的四倍，月度为十二倍；月度流量和库存聚合方式不同。不支持：除四还原未季调原始值、SAAR为过去12个月实际总额、年度基准完全可由任意季调序列加总。' },
];

export const lesson317ReadingList: LessonReading[] = [
  { title: '先把财政支出和GDP的G分开', scope: 'BEA FAQ552；GDP附加信息Definitions', reason: '购买、转移、利息与资产交易先按用途和口径分栏，才知道政策先进入谁的预算。', guide: '把“发100”和“交付100产品”写为两笔不同交易；说明后者何时进入产出以及私人其他支出为何不能默认不变。', url: lesson317References[0].url, group: 'core', links: [{label: 'GDP统计约定',url: lesson317References[6].url}] },
  { title: '自动稳定器不是新财政决定', scope: 'CBO2024完整HTML：估计方法及周期调整赤字说明', reason: '理解经济状态先改变税款和资格，再经可用收入影响主体；赤字既是输入，也会成为经济变化的结果。', guide: '分别列现行规则反馈、新立法改变、其他预算变动；保留2024预测vintage，勿将其预测数字当今天状态。', url: lesson317References[1].url, group: 'core' },
  { title: 'Ramey JEL：把一个乘数拆回完整政策实验', scope: '673–685全文，尤其§2模型、§3识别、§4地方估计与§5福利', reason: '先解释同样GDP响应可能来自不同私人消费与劳动机制，再看为什么方法分歧不只是数字争论。', guide: '冻结工具、持续性、承担成本的主体和货币反应；读地方反例时写明同质与税负条件，不把模型1.5当实证参数。', url: lesson317References[3].url, group: 'core', links: [{label: '作者当前研究入口',url: 'https://valerieramey.stanford.edu/research'}] },
  { title: 'Blanchard–Perotti：统计残差为什么还不是政策冲击', scope: '实读April2001作者稿§2.1–2.3与§8；随后另核2002final完整数据、结果和稳健性', reason: '逐步理解制度弹性和反应时滞到底排除哪条反向因果，而不是背一个“结构VAR”名字。', guide: '注意net taxes包含转移及净利息，b1=0限定购买；写出私人已知未来政策怎样破坏未经改造的当期残差识别。', url: lesson317References[2].url, group: 'evidence', links: [{label: '实际作者稿',url: 'https://didattica.unibocconi.it/mypage/upload/49621_20090119_044303_BLANCHARDPEROTTI4_02.PDF'},{label: '更早NBER版本',url:'https://www.nber.org/papers/w7269'}] },
  { title: 'IMF2014：先读条件，再读投影操作', scope: 'TNM14/04 §I–IV、Appendix I–III；bucket部分作为有判断的操作框架', reason: '把资源、进口、信用、货币与执行条件连到响应路径，理解旧冲击滞后怎样叠加到无同一处理基线。', guide: '重算C5和C6，然后说明Box1没有把本课累计定义作为原式；Table9为示意，bucket参数不进入实验。', url: lesson317References[4].url, group: 'models' },
  { title: '财政新闻：下一步完整核读timing原文', scope: 'Ramey2011 QJE §I后通读§III及后续数据与识别；目前本课仅核读1–5页', reason: '新闻可以早于采购，让预期和实际执行沿不同时间尺度影响家庭、企业与市场。', guide: '分别记录最早公开新闻、研究者收到、预算执行；完整核读后再判断战争资源冲击和专业预测误差的排除限制。不要提前引用点估计。', url: lesson317References[5].url, group: 'evidence', links: [{label: '作者当前研究入口',url:'https://valerieramey.stanford.edu/research'}] },
  { title: '真实数据之前先完成单位审计', scope: 'BEA GDP统计约定、链式美元词条、FAQ122；Census第15–17问', reason: '季调年率水平、年化增速、期间财政流量和链式组成项不相同，错误单位能凭空造出数倍乘数。', guide: '季度SAAR水平转期间季调流量除四；增长年化需复利；组成链式量不保证可加。本课SYN路径无SAAR或链式权重，不冒充官方实际量复算。', url: lesson317References[6].url, group: 'rules', links: [{label:'链式美元',url:lesson317References[7].url},{label:'年化增速',url:lesson317References[8].url},{label:'年率水平',url:lesson317References[9].url}] },
  { title: '从地方政策研究走向全国问题', scope: 'Ramey JEL §4；IMF Appendix II工具与估计对象差异', reason: '地方处理相对对照剔除的共同税负和利率，可能恰好是国家财政问题需要保留的反馈。', guide: '写出地理范围、税负分布、贸易溢出和共同时间项；无法建立桥接时，保留地方结果，不强行给全国GDP元／元。', url: lesson317References[3].url, group: 'systems', links:[{label:'IMF方法附录',url:lesson317References[4].url}] },
  { title: '把产出、预算成本与福利写成三张账', scope: 'Ramey JEL §5；IMF主文条件框架；下一节3.18／3.19接口', reason: '产出增加可以伴随更高劳动负担、税收扭曲或不同分配，初始支出也不等于最终净财政成本。', guide: '区分gross／net成本、税收反馈、利息与融资、项目服务价值及私人机会成本；只传递财政路径和金融反应，不提前声明债务安全或无条件政策排名。', url:lesson317References[3].url, group:'systems', links:[{label:'条件与投影',url:lesson317References[4].url}] },
];
