import type { LessonReading, LessonReference } from './types';

export const lesson312References: LessonReference[] = [
  { id: 1, authors: 'Claudio Borio & Haibin Zhu', year: '2008; published version 2012', title: 'Capital Regulation, Risk-Taking and Monetary Policy: A Missing Link in the Transmission Mechanism?', publication: 'BIS Working Paper 268; Journal of Financial Stability 8(4), 236–251', url: 'https://www.bis.org/publ/work268.htm', use: '【概念/模型】支持把风险承担渠道定义为货币政策影响风险认知、风险定价与金融行为，并强调监管、流动性和政策反应函数的交互；不支持“低利率必然提高风险”的无条件方向，也不提供可移植的因果系数。' },
  { id: 2, authors: 'Leonardo Gambacorta', year: '2009', title: 'Monetary Policy and the Risk-Taking Channel', publication: 'BIS Quarterly Review, December 2009', url: 'https://www.bis.org/publ/qtrpdf/r_qt0912f.htm', use: '【综述/经验】支持安全收益下降、名义目标、资产估值与风险度量可能改变银行风险选择，并总结跨国证据；不支持把跨国平均相关性外推为每类机构、每个利率区间的相同反应。' },
  { id: 3, authors: "Giovanni Dell'Ariccia, Luc Laeven & Robert Marquez", year: '2010; published version 2014', title: 'Monetary Policy, Leverage, and Bank Risk-Taking', publication: 'IMF Working Paper 10/276; Journal of Economic Theory 149, 65–99', url: 'https://www.imf.org/en/publications/wp/issues/2016/12/31/monetary-policy-leverage-and-bank-risk-taking-24424', use: '【模型】支持利率传递、有限责任下的风险转移与杠杆调整三股力量共同决定监控强度，资本结构可使符号反转；不支持把风格化监控选择当作现实银行的直接观测或普适定律。' },
  { id: 4, authors: "Giovanni Dell'Ariccia, Luc Laeven & Gustavo Suarez", year: '2013; published version 2017', title: "Bank Leverage and Monetary Policy's Risk-Taking Channel: Evidence from the United States", publication: 'IMF Working Paper 13/143; Journal of Finance 72(2), 613–654', url: 'https://www.imf.org/external/pubs/ft/wp/2013/wp13143.pdf', use: '【经验】支持美国历史 STBL 内部评级中较低实际短率与更高的新贷款事前风险相关，且银行资本和非危机状态产生异质性；不支持覆盖全部银行、全部贷款或把风险更高直接称为社会过度风险。' },
  { id: 5, authors: 'Gabriel Jiménez, Steven Ongena, José-Luis Peydró & Jesús Saurina', year: '2014', title: 'Hazardous Times for Monetary Policy: What Do Twenty-Three Million Bank Loans Say About the Effects of Monetary Policy on Credit Risk-Taking?', publication: 'Econometrica 82(2), 463–505', url: 'https://www.bde.es/wbe/es/areas-actuacion/analisis-e-investigacion/investigadores/investigadores-orden-alfabetico/hazardous-times-for-monetary-policy-what-do-twenty-three-million-bank-loans-say-about-the-effects-of-2e5dccd9230de91.html', use: '【贷款级经验】支持西班牙贷款申请与登记数据中利率、银行资本、审批、新贷事前风险和后续违约之间的异质联系；不支持无条件外推到其他法域，也不消除匹配支持、申请需求与关系特定冲击的识别要求。' },
  { id: 6, authors: 'Gabriel Jiménez, Steven Ongena, José-Luis Peydró & Jesús Saurina', year: '2017', title: '‘In the Short Run Blasé, In the Long Run Risqué’. On the Effects of Monetary Policy on Bank Credit Risk-Taking in the Short versus Long Run', publication: 'Schmalenbach Business Review 18(3), 181–226', url: 'https://bse.eu/research/publications/short-run-blase-long-run-risque-effects-monetary-policy-bank-credit-risk', use: '【贷款级经验】支持发放前低利率可能提高新贷款选择风险，而存续期低利率又可能降低同一贷款的当期违约，说明时钟可给出相反方向；不支持用同一个利率观测或同一个违约率同时代表两个处理窗口，也不把西班牙样本外推为普遍系数。' },
  { id: 7, authors: 'Vasso Ioannidou, Steven Ongena & José-Luis Peydró', year: '2015; working paper 2009', title: 'Monetary Policy, Risk-Taking, and Pricing: Evidence from a Quasi-Natural Experiment', publication: 'Review of Finance 19(1), 95–144', url: 'https://www.imf.org/external/np/res/seminars/2008/arc/pdf/iop.pdf', use: '【准实验】支持玻利维亚美元化环境中外部政策利率、既往不良或次级借款人获贷与风险加价的联系；不支持跨越1999–2003年制度、币种和银行体系直接移植点估计。' },
  { id: 8, authors: 'Angela Maddaloni & José-Luis Peydró', year: '2010; published version 2011', title: 'Bank Risk-Taking, Securitization, Supervision, and Low Interest Rates: Evidence from the Euro-Area and the U.S. Lending Standards', publication: 'ECB Working Paper 1248; Review of Financial Studies 24(6), 2121–2165', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1248.pdf', use: '【调查经验】支持低短率与较松贷款标准以及监督、证券化条件的交互；不支持把调查净比例解释为条款强度、贷款金额、单笔风险阈值或已识别的长期社会损失。' },
  { id: 9, authors: 'Yener Altunbas, Leonardo Gambacorta & David Marqués-Ibáñez', year: '2010', title: 'Does Monetary Policy Affect Bank Risk-Taking?', publication: 'ECB Working Paper 1166', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1166.pdf', use: '【银行级经验】支持长期偏低的利率与欧美上市银行后续风险指标之间存在条件联系；不支持把估算利率缺口、上市银行样本或事后风险指标直接命名为贷款审批门的因果变化。' },
  { id: 10, authors: 'Claudia M. Buch, Sandra Eickmeier & Esteban Prieto', year: '2014', title: 'In Search for Yield? Survey-Based Evidence on Bank Risk Taking', publication: 'Journal of Economic Dynamics and Control 43, 12–30; Deutsche Bundesbank Discussion Paper', url: 'https://www.bundesbank.de/en/publications/research/discussion-papers/in-search-for-yield-survey-based-evidence-on-bank-risk-taking-703606', use: '【调查经验】支持银行资本、市场势力和监控成本造成风险类别贷款与风险利差反应异质；不支持把历史 STBL 风险类别、抵押与期限的变化全部归因于纯风险容忍度。' },
  { id: 11, authors: 'David Martínez-Miera & Rafael Repullo', year: '2017', title: 'Search for Yield', publication: 'Econometrica 85(2), 351–378', url: 'https://onlinelibrary.wiley.com/doi/10.3982/ECTA14057', use: '【模型】支持安全收益下降可能压缩利差、改变监控与中介分工，并产生内生风险选择；不支持把模型的繁荣—衰退反馈当作本节已识别事实，完整周期必须路由3.14、3.15与7.12。' },
  { id: 12, authors: 'Florian Heider, Farzad Saidi & Glenn Schepens', year: '2018; published version 2019', title: 'Life Below Zero: Bank Lending Under Negative Policy Rates', publication: 'ECB Working Paper 2173; Review of Financial Studies 32(10), 3728–3761', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2173.en.pdf', use: '【准实验】支持负政策利率与存款利率下限使高存款银行相对少贷却向更高风险借款人配置；不支持线性外推到正利率区间、所有贷款类型或所有负债结构。' },
  { id: 13, authors: 'Florian Heider & Agnese Leonello', year: '2021', title: 'Monetary Policy in a Low Interest Rate Environment: Reversal Rate and Risk-Taking', publication: 'ECB Working Paper 2593', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2593~c97d059554.en.pdf', use: '【模型】支持低利率区间内贷款数量与风险承担可能出现非线性甚至方向反转；不支持把模型阈值当作跨国家、跨时期固定的“reversal rate”。' },
  { id: 14, authors: 'Carlo Altavilla, Miguel Boucinha & José-Luis Peydró', year: '2017', title: 'Monetary Policy and Bank Profitability in a Low Interest Rate Environment', publication: 'ECB Working Paper 2105', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2105.en.pdf', use: '【经验】支持把净利息收入、拨备和非息收入分开后，低利率或平坦曲线对银行总体盈利的净效应并非机械为负；不支持用平均盈利分解直接观测风险容忍度或证明任何审批变化。' },
  { id: 15, authors: 'Johannes Bubeck, Angela Maddaloni & José-Luis Peydró', year: '2020', title: 'Negative Monetary Policy Rates and Systemic Banks’ Risk-Taking: Evidence from the Euro Area Securities Register', publication: 'ECB Working Paper 2398', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2398~973038ea61.en.pdf', use: '【证券级经验】支持负利率后特定高存款、系统重要银行向更风险证券配置的异质反应；不支持把证券组合结果等同贷款筛选，或外推到所有银行和利率制度。' },
  { id: 16, authors: 'Gabriel Chodorow-Reich', year: '2014', title: 'Effects of Unconventional Monetary Policy on Financial Institutions', publication: 'Brookings Papers on Economic Activity 2014(1), 155–227; NBER Working Paper 20230', url: 'https://www.nber.org/papers/w20230', use: '【跨机构经验】支持非常规政策可通过旧资产估值再资本化银行和寿险机构，同时部分货币基金、养老金出现温和或短暂的收益追逐；不支持把2008–2013年美国结论外推为所有时期不存在金融稳定权衡。' },
  { id: 17, authors: 'Bo Becker & Victoria Ivashina', year: '2015; NBER version 2013', title: 'Reaching for Yield in the Bond Market', publication: 'Journal of Finance 70(5), 1863–1902; NBER Working Paper 18909', url: 'https://www.nber.org/papers/w18909', use: '【证券级经验】支持保险机构在相同监管评级桶内偏向更高收益、CDS与系统性风险的债券，说明桶内收益追逐；不支持把这一配置直接归因于纯货币政策冲击，也不代表银行贷款筛选。' },
  { id: 18, authors: 'Marco Di Maggio & Marcin Kacperczyk', year: '2017; NBER version 2016', title: 'The Unintended Consequences of the Zero Lower Bound Policy', publication: 'Journal of Financial Economics 123(1), 59–80; NBER Working Paper 22351', url: 'https://www.nber.org/papers/w22351', use: '【基金级经验】支持美国零利率环境下货币基金减费、退出和部分向风险更高资产迁移；不支持把货币基金商业模式外推至银行、保险或养老金，也不证明所有基金都会追逐收益。' },
  { id: 19, authors: 'Margherita Giuzio, Christoph Kaufmann, Ellen Ryan & Lorenzo Cappiello', year: '2021', title: 'Investment Funds, Risk-Taking and Monetary Policy in the Euro Area', publication: 'ECB Working Paper 2605', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2605~5da83010af.en.pdf', use: '【基金级经验】支持宽松冲击可能伴随更风险基金流入、现金持有下降与组合风险变化；不支持把BVAR识别、基金样本或资金流响应改写成银行贷款级风险阈值。' },
  { id: 20, authors: 'Alexandru Barbu, Christoph Fricke & Emanuel Moench', year: '2020', title: 'Procyclical Asset Management and Bond Risk Premia', publication: 'Deutsche Bundesbank Discussion Paper 38/2020', url: 'https://www.bundesbank.de/en/publications/research/discussion-papers/procyclical-asset-management-and-bond-risk-premia-837244', use: '【机构基金经验】支持收益下降与最低收益保证可能使德国机构基金增加久期或信用风险，并接入债券风险溢价；不支持外推至无目标收益负债的机构，完整价格反馈也不属于本节。' },
  { id: 21, authors: 'Sofia Anyfantaki, Haris Giannakidis, Dimitrios Malliaropulos, Petros Migiakis & Filippos Petroulakis', year: '2026', accessedAt: '2026-09-03', title: 'Bond Funds’ Risk Taking and Monetary Policy', publication: 'Bank of Greece Working Paper 358, February 2026', url: 'https://www.bankofgreece.gr/en/publications-and-research/research/research-activity-list/abstract?publication=2f11e437-7e59-4e05-b19c-170e663b8afd', use: '【工作论文】支持美欧债券基金可能通过信用评级与期限结构调整风险，且非常规政策反应更强；不支持把2026年工作论文结论视为定论、外推到银行，或据此推断最终系统损失。' },
  { id: 22, authors: 'Geert Bekaert, Marie Hoerova & Marco Lo Duca', year: '2013', title: 'Risk, Uncertainty and Monetary Policy', publication: 'ECB Working Paper 1565; Journal of Monetary Economics 60(7), 771–788', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1565.pdf', use: '【资产价格经验】支持把VIX分解为不确定性与风险厌恶代理后，宽松政策与两者下降相关且风险厌恶部分更明显；不支持把聚合期权隐含代理直接解释为银行风险偏好或贷款阈值。' },
  { id: 23, authors: 'Tobias Adrian, Emanuel Moench & Hyun Song Shin', year: '2010', title: 'Macro Risk Premium and Intermediary Balance Sheet Quantities', publication: 'Federal Reserve Bank of New York Staff Report 428; IMF Economic Review 58(1), 179–207', url: 'https://www.newyorkfed.org/research/staff_reports/sr428.html', use: '【宏观经验/模型】支持金融中介资产负债表数量、估计的宏观风险溢价与实际活动共同变化，并把资产负债表余量与风险偏好联系起来；不支持把聚合潜变量当作单笔贷款风险阈值，也不单独识别政策冲击。' },
  { id: 24, authors: 'Tobias Adrian & Hyun Song Shin', year: '2008; published version 2014', title: 'Financial Intermediary Leverage and Value-at-Risk / Procyclical Leverage and Value-at-Risk', publication: 'New York Fed Staff Report 338; Review of Financial Studies 27(2), 373–403', url: 'https://www.newyorkfed.org/research/staff_reports/sr338.html', use: '【模型/经验】支持市场价值、测得风险与中介主动杠杆管理之间的顺周期联系；不支持把简单课堂VaR当作当前监管资本规则，完整杠杆、保证金与火售反馈路由7.12–7.13。' },
  { id: 25, authors: 'Emmanuel Farhi & Jean Tirole', year: '2012', title: 'Collective Moral Hazard, Maturity Mismatch, and Systemic Bailouts', publication: 'American Economic Review 102(1), 60–93', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.102.1.60', use: '【模型】支持对非精确政策托底的共同信念可诱发期限错配和相关风险的战略互补；不支持从观察到低利率推断存在救助承诺，也不证明任何个体机构已依赖政策put。' },
  { id: 26, authors: 'Xiaoming Li, Zheng Liu, Yuchao Peng & Zhiwei Xu', year: '2026', accessedAt: '2026-09-03', title: 'Bank Risk-Taking, Credit Allocation, and Monetary Policy Transmission: Evidence from China', publication: 'American Economic Journal: Macroeconomics 18(1), January 2026, 384–415', url: 'https://www.aeaweb.org/articles?id=10.1257/mac.20220177', use: '【贷款级经验】支持特定中国监管制度下宽松可降低监管口径风险却经政府担保借款人产生资源错配，显示监管风险、真实尾部风险和配置效率需分栏；不支持跨法域外推或把风险权重当作真实风险。' },
  { id: 27, authors: 'Committee on the Global Financial System', year: '2018', title: 'Financial Stability Implications of a Prolonged Period of Low Interest Rates', publication: 'CGFS Papers 61, Bank for International Settlements', url: 'https://www.bis.org/publ/cgfs61.htm', use: '【官方评估】支持低利率可能经偿付能力、收益目标、期限与跨部门迁移形成脆弱性，同时观察期内额外风险承担证据有限；不支持作为单一因果估计或各国统一阈值。' },
  { id: 28, authors: 'Jeremy C. Stein', year: '2013', title: 'Overheating in Credit Markets: Origins, Measurement, and Policy Responses', publication: 'Federal Reserve Board speech', url: 'https://www.federalreserve.gov/newsevents/speech/stein20130207a.htm', use: '【政策分析】支持联合观察收益目标、代理问题、尾部风险、价格与非价格信贷条件来诊断过热；不支持把政策演讲当作因果证据，也不授权从低利差直接推断错误定价。' },
  { id: 29, authors: 'Carlo Altavilla, Miguel Boucinha, José-Luis Peydró & Frank Smets', year: '2020', title: 'Banking Supervision, Monetary Policy and Risk-Taking: Big Data Evidence from 15 Credit Registers', publication: 'ECB Working Paper 2349, January 2020', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecb.wp2349~515abecc84.en.pdf', use: '【贷款级经验】支持统一监管提高信贷风险敏感度并改变货币政策与银行风险选择的交互；不支持把SSM制度效应改名为纯货币政策效应，结论只属于15个信贷登记的支持集。' },
  { id: 30, authors: 'Board of Governors of the Federal Reserve System', year: 'living daily series', accessedAt: '2026-09-03', title: 'Selected Interest Rates (Daily) — H.15', publication: 'Federal Reserve official statistical release', url: 'https://www.federalreserve.gov/releases/h15/', use: '【官方动态数据】支持读取美国政策相关利率与多期限市场收益率，并保留频率、单位和发布日期；不支持欧元区政策利率，也不支持把观察利率水平视为外生政策冲击，必须继承3.05的surprise/path护照。' },
  { id: 31, authors: 'Board of Governors of the Federal Reserve System', year: 'current through July 2026', accessedAt: '2026-09-03', title: 'Senior Loan Officer Opinion Survey on Bank Lending Practices', publication: 'Federal Reserve official quarterly survey', url: 'https://www.federalreserve.gov/data/sloos/sloos-202607.htm', use: '【官方动态调查】支持观察贷款标准、条款、较高风险贷款加价、契约、额度、期限与银行报告的risk-tolerance原因；不支持把净比例当作收紧强度、金额、canonical operational tolerance、董事会aggregate appetite或政策因果效应。' },
  { id: 32, authors: 'European Central Bank', year: 'living survey; user guide April 2026', accessedAt: '2026-09-03', title: 'Euro Area Bank Lending Survey: Data, Methodology and User Guide', publication: 'ECB official quarterly survey and data portal', url: 'https://data.ecb.europa.eu/methodology/bank-lending-survey-bls', use: '【官方动态调查】支持按标准、条款、风险感知、来源原词bank’s risk tolerance、资金约束与竞争拆分银行回答，并定义加权净比例；不支持忽略问卷版本、回顾/预期窗口、国家权重或把发布季度当活动季度，也不能把该来源词直接写入本页PD/tail operational tolerance或董事会aggregate appetite字段。' },
  { id: 33, authors: 'Board of Governors of the Federal Reserve System', year: 'current quarterly survey', accessedAt: '2026-09-03', title: 'Senior Credit Officer Opinion Survey on Dealer Financing Terms', publication: 'Federal Reserve official survey', url: 'https://www.federalreserve.gov/data/scoos.htm', use: '【官方动态调查】支持观察证券融资与OTC衍生品的价格/非价格条款、haircut、契约、集中暴露资源和杠杆需求；不支持把回答比例当成交额、实际敞口或已识别风险偏好。' },
  { id: 34, authors: 'Board of Governors of the Federal Reserve System', year: 'discontinued 2017', accessedAt: '2026-09-03', title: 'Survey of Terms of Business Lending — E.2', publication: 'Federal Reserve historical quarterly statistical release', url: 'https://www.federalreserve.gov/releases/e2/', use: '【官方历史调查】支持读取截至2017年5月的美国新发商业贷款利率、规模、期限、担保状态与银行风险类别等历史口径；不支持作为当前调查，也不支持与2018年起的Kansas City Fed小企业贷款调查无断点拼接。' },
  { id: 35, authors: 'Federal Financial Institutions Examination Council', year: 'living quarterly report', accessedAt: '2026-09-03', title: 'FFIEC 041: Consolidated Reports of Condition and Income for a Bank with Domestic Offices Only', publication: 'FFIEC official Call Report form and instructions', url: 'https://www.ffiec.gov/resources/reporting-forms/ffiec041', use: '【官方监管数据】支持读取仅设国内办事处银行法人的资产负债表、损益表及贷款、资本和表外项目等支持附表；不支持控股集团合并口径，也不直接观察单笔审批阈值或风险容忍度。' },
  { id: 36, authors: 'Federal Deposit Insurance Corporation', year: 'living quarterly publication', accessedAt: '2026-09-03', title: 'Quarterly Banking Profile', publication: 'FDIC official aggregate banking-industry statistics', url: 'https://www.fdic.gov/quarterly-banking-profile', use: '【官方动态数据】支持观察FDIC承保机构的行业汇总盈利、贷款与存款活动、资本和资产质量；不支持周度银行资产负债表，也不支持由聚合存量或事后损失单独证明风险容忍度、审批规则或纯政策渠道。' },
  { id: 37, authors: 'European Central Bank Banking Supervision', year: 'current through Q1 2026', accessedAt: '2026-09-03', title: 'Supervisory Banking Statistics', publication: 'ECB Banking Supervision official quarterly statistics', url: 'https://www.bankingsupervision.europa.eu/framework/statistics/html/index.en.html', use: '【官方监管数据】支持显著机构资本、NPL、Stage 2、盈利与流动性口径的季度状态；不支持把合并监管快照等同新发放时的风险选择或银行个体因果反应。' },
  { id: 38, authors: 'International Monetary Fund', year: 'living dataset; 2019 guide', accessedAt: '2026-09-03', title: 'Financial Soundness Indicators', publication: 'IMF official cross-country dataset and compilation guide', url: 'https://data.imf.org/en/Datasets/FSIC', use: '【官方动态数据】支持跨国资本、资产质量、盈利、流动性和外汇敞口指标及其元数据；不支持在未审计国家覆盖、合并、会计、频率和Basel版本时直接比较，也不直接观测风险偏好。' },
  { id: 39, authors: 'Bank for International Settlements', year: 'living quarterly dataset', accessedAt: '2026-09-03', title: 'Consolidated Banking Statistics', publication: 'BIS Data Portal official statistics', url: 'https://data.bis.org/topics/CBS', use: '【官方动态数据】支持按银行国籍、交易对手国家、部门、可用期限维度及即时借款人/最终担保人基础观察合并跨境敞口；不提供通用币种分解，也不支持把敞口水平直接命名为单一银行的风险偏好、资本状态或方向性政策因果效应。币种需另接LBS或其他来源，并保留LBS所在地/非合并与CBS国籍/合并口径差异。' },
  { id: 40, authors: 'U.S. Securities and Exchange Commission', year: 'living monthly filings', accessedAt: '2026-09-03', title: 'Form N-MFP Data Sets', publication: 'SEC Division of Economic and Risk Analysis official as-filed data', url: 'https://www.sec.gov/data-research/sec-markets-data/dera-form-n-mfp-data-sets', use: '【官方动态数据】支持货币基金净资产、收益、WAM/WAL、流动资产、资金流与逐项持仓的月度申报研究；不支持假定as-filed抽取无误，也不能忽略N-MFP/N-MFP3 schema、修订和基金结构。' },
  { id: 41, authors: 'Financial Stability Board', year: '2013', title: 'Principles for an Effective Risk Appetite Framework', publication: 'FSB policy document, 18 November 2013', url: 'https://www.fsb.org/2013/11/r_131118/', use: '【官方原则】支持区分risk capacity、risk appetite、risk limits与risk profile，并要求在正常和压力情景下把风险偏好与战略、资本、财务计划和治理职责连接；不支持把高层原则当作可观测风险偏好指标、监管最低值或货币政策因果证据。' },
  { id: 42, authors: 'Basel Committee on Banking Supervision', year: 'current rule; effective 2023', accessedAt: '2026-09-03', title: 'Internal models approach: capital requirements calculation', publication: 'Basel Framework MAR33; status current', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/mar/33/inforce/2023-01-01/published/2020-06-05', use: '【官方规则】支持MAR33内部模型法以97.5%单尾期望损失计量市场风险，并按10、20、40、60和120日流动性期限缩放；不支持把该IMA交易账簿资本规则外推为银行账簿信用风险、全机构风险偏好或本页教学风险预算的现实校准。' },
  { id: 43, authors: 'European Central Bank', year: 'living official series', accessedAt: '2026-09-03', title: 'Key ECB Interest Rates', publication: 'ECB official policy-rate history', url: 'https://www.ecb.europa.eu/stats/policy_and_exchange_rates/key_ecb_interest_rates/html/index.en.html', use: '【官方动态数据】支持读取欧元区存款便利、主要再融资操作与边际贷款便利利率及其生效日期；不支持市场收益率、政策意外或路径冲击，也不能把一次利率变动本身当作已识别的外生处理。' },
  { id: 44, authors: 'Federal Reserve Bank of Kansas City', year: 'living quarterly survey', accessedAt: '2026-09-03', title: 'Small Business Lending Survey', publication: 'Official FR 2028D survey', url: 'https://www.kansascityfed.org/surveys/small-business-lending-survey/', use: '【官方动态调查】支持观察小企业C&I贷款金额、利率、期限、条款、申请与批准，以及标准、条款和需求变化；不支持把自愿银行面板当作全部美国银行或单笔贷款样本，也不支持与2017年终止的E.2无断点拼接。' },
  { id: 45, authors: 'Board of Governors of the Federal Reserve System', year: 'living quarterly report', accessedAt: '2026-09-03', title: 'FR Y-9C: Consolidated Financial Statements for Holding Companies', publication: 'Federal Reserve official reporting form and instructions', url: 'https://www.federalreserve.gov/apps/reportingforms/Report/Index/FR_Y-9C', use: '【官方监管数据】支持读取符合申报条件的控股公司合并资产负债表、损益表与资本、贷款、证券和表外项目附表；不支持把控股集团口径与FFIEC 041银行法人口径混用，也不直接观察单笔风险筛选或风险容忍度。' },
  { id: 46, authors: 'Board of Governors of the Federal Reserve System', year: 'living weekly release', accessedAt: '2026-09-03', title: 'Assets and Liabilities of Commercial Banks in the United States — H.8', publication: 'Federal Reserve official weekly statistical release', url: 'https://www.federalreserve.gov/releases/h8/', use: '【官方动态数据】支持观察由FR 2644样本和季度Call Reports估算的美国商业银行周度汇总资产负债表及银行分组；不支持个体银行微观敞口、贷款审批阈值或风险偏好，也不能由聚合存量单独识别货币政策因果效应。' },
];

export const lesson312ReadingList: LessonReading[] = [
  {
    title: '概念起点：风险承担渠道不是信用数量渠道的同义词',
    scope: 'Borio–Zhu (2008) pp. 1–9、20–32；Gambacorta (2009) 全文',
    reason: '建立风险感知、风险定价、收益目标和监管交互的原始定义，并学会先写条件再判断方向。',
    url: lesson312References[0].url,
    group: 'core',
    guide: '边读边画两条线：3.10 的资金/容量线与3.12的风险决策线。凡只改变可贷总量、却未改变风险排序或阈值的机制，移回3.10。',
    links: [{ label: 'Borio–Zhu', url: lesson312References[0].url }, { label: 'BIS overview', url: lesson312References[1].url }],
  },
  {
    title: '理论符号：pass-through、risk shifting、leverage 与资本异质性',
    scope: "Dell'Ariccia–Laeven–Marquez (2010) sections II–IV；Martínez-Miera–Repullo (2017) pp. 351–365",
    reason: '理解为何同一次宽松在资本结构固定、可调、存款下限或监控技术不同时可以提高、降低或不改变风险承担。',
    url: lesson312References[2].url,
    group: 'models',
    guide: '不要背结论；逐项标注哪一个收入、成本、有限责任或资本状态改变了最优监控。把完整信用周期留到后续章节。',
    links: [{ label: 'Bank monitoring model', url: lesson312References[2].url }, { label: 'Search for Yield', url: lesson312References[10].url }],
  },
  {
    title: '贷款级识别：申请、审批、新发放风险与后续违约',
    scope: 'Jiménez et al. (2014) pp. 463–485；Ioannidou et al. (2015) pp. 95–122；Dell’Ariccia et al. (2017) pp. 613–641',
    reason: '学习如何把政策输入、银行状态、同一申请或借款人和决策前风险放进可检验设计。',
    url: lesson312References[4].url,
    group: 'evidence',
    guide: '分别记录申请母体、批准、发放、提款和表现样本；任何一步换分母，都重新定义estimand与支持集。',
    links: [{ label: 'Spain registry', url: lesson312References[4].url }, { label: 'Bolivia anchor', url: lesson312References[6].url }, { label: 'U.S. internal ratings', url: lesson312References[3].url }],
  },
  {
    title: '时钟反例：新贷风险上升与当前违约下降可以同时发生',
    scope: 'In the Short Run Blasé, In the Long Run Risqué；Chodorow-Reich (2014) pp. 155–205',
    reason: '防止用旧资产估值、当期NPL或借款人现金流改善去否定新发放环节的风险选择。',
    url: lesson312References[5].url,
    group: 'evidence',
    guide: '为每个结果写decision vintage、performance window与当时信息集；不允许把未来违约回填为审批时PD。',
    links: [{ label: 'Two clocks', url: lesson312References[5].url }, { label: 'Cross-institution counterexample', url: lesson312References[15].url }],
  },
  {
    title: '低于零的非线性：存款利率下限与数量—风险分叉',
    scope: 'Heider–Saidi–Schepens (2019) introduction, design and results；Heider–Leonello (2021) model propositions',
    reason: '理解负利率为何不是普通降息的线性延伸，以及高存款银行为什么可能少贷却更冒险。',
    url: lesson312References[11].url,
    group: 'models',
    guide: '固定存款依赖、存款beta、净息差和资本状态；若这些本身是处理路径，就把结论标成联合渠道而非纯风险偏好。',
    links: [{ label: 'Life Below Zero', url: lesson312References[11].url }, { label: 'Reversal-rate model', url: lesson312References[12].url }],
  },
  {
    title: '非银异质性：保险、养老金、货币基金与债券基金',
    scope: 'Becker–Ivashina (2015) pp. 1863–1892；Di Maggio–Kacperczyk (2017) pp. 59–75；Chodorow-Reich (2014) institution sections',
    reason: '把目标收益、保证负债、费用下限、赎回与监管评级桶分别映射到不同机构的风险选择。',
    url: lesson312References[16].url,
    group: 'systems',
    guide: '每换一种机构都重写负债、监管、退出选项和风险向量；银行结论不能只换名词后复制。',
    links: [{ label: 'Insurance', url: lesson312References[16].url }, { label: 'Money funds', url: lesson312References[17].url }, { label: 'Euro area funds', url: lesson312References[18].url }],
  },
  {
    title: '监管、监督与风险权重：测量风险不等于真实尾部风险',
    scope: 'Altavilla et al. (2020) design and results；Li et al. (2026) abstract, identification and allocation results；FSB (2013) sections I–IV；Basel Framework MAR33.1–33.5、MAR33.12',
    reason: '识别监管和监督如何改变风险门，并防止把RWA、内部评级或资本分类当作真实风险本身。',
    url: lesson312References[28].url,
    group: 'rules',
    guide: '同时保存模型版本、生效日、内部评级、外部代理和表现结果；监管变化必须独立命名，不能归入货币处理。',
    links: [{ label: 'Unified supervision', url: lesson312References[28].url }, { label: 'Basel III allocation counterexample', url: lesson312References[25].url }, { label: 'FSB risk-appetite framework', url: lesson312References[40].url }, { label: 'Basel MAR33', url: lesson312References[41].url }],
  },
  {
    title: '调查方法：SLOOS/BLS 的净比例只表示方向广度',
    scope: 'ECB BLS April 2026 user guide与series-key说明；Fed SLOOS July 2026 questionnaire、tables和chart data',
    reason: '学会按问题、分母、银行类别、回顾窗口、发布时间和权重读取标准与风险容忍度，而不是把净比例当金额。',
    url: lesson312References[31].url,
    group: 'rules',
    guide: '复算net tightening=%tightened−%eased；ECB Data Portal period是发布季度时要另存活动季度。调查贡献项只能描述报告原因，不授予政策因果。',
    links: [{ label: 'ECB BLS methodology', url: lesson312References[31].url }, { label: 'Fed SLOOS', url: lesson312References[30].url }],
  },
  {
    title: '风险向量与系统边界：信用、久期、流动性、FX和杠杆分栏',
    scope: 'CGFS 61 chapters 2–4；Adrian–Shin (2014) pp. 373–392；Farhi–Tirole (2012) pp. 60–82',
    reason: '理解平均信用评级不变时，风险仍可沿久期、流动性、集中度或共同尾部暴露迁移。',
    url: lesson312References[26].url,
    group: 'systems',
    guide: '本节只到机构风险决策与局部损失反馈；保证金、强制去杠杆、价格冲击和网络传染路由7.12–7.13。',
    links: [{ label: 'CGFS low-rate assessment', url: lesson312References[26].url }, { label: 'Intermediary VaR', url: lesson312References[23].url }, { label: 'Collective moral hazard', url: lesson312References[24].url }],
  },
  {
    title: '数据工程路径：监管表、跨境敞口与基金逐项持仓',
    scope: 'Fed H.15与ECB key rates；历史E.2与KC Fed FR 2028D的断点；FFIEC 041银行法人表与FR Y-9C控股集团表；FDIC QBP与Fed H.8；ECB supervisory statistics、IMF FSI、BIS CBS、SEC Form N-MFP',
    reason: '建立从贷款级选择到机构与系统状态的刷新护照，同时避免用聚合存量反推审批阈值。',
    url: lesson312References[34].url,
    group: 'rules',
    guide: '固定法人/合并、表单版本、单位、stock/flow、频率、参考期、发布期、修订和break；所有当前值在研究时重新抓取。',
    links: [{ label: 'FFIEC 041', url: lesson312References[34].url }, { label: 'ECB supervision', url: lesson312References[36].url }, { label: 'IMF FSI', url: lesson312References[37].url }, { label: 'BIS CBS', url: lesson312References[38].url }, { label: 'SEC N-MFP', url: lesson312References[39].url }, { label: 'ECB key rates', url: lesson312References[42].url }, { label: 'KC Fed small-business lending', url: lesson312References[43].url }, { label: 'FR Y-9C', url: lesson312References[44].url }, { label: 'Fed H.8', url: lesson312References[45].url }],
  },
];
