import type { LessonReading, LessonReference } from './types';

export const lesson310References: LessonReference[] = [
  { id: 1, authors: 'Ben S. Bernanke & Alan S. Blinder', year: '1988', title: 'Credit, Money, and Aggregate Demand', publication: 'American Economic Review 78(2); NBER Working Paper 2534', url: 'https://www.nber.org/papers/w2534', use: '支持银行贷款与债券不可完全替代时的信用渠道基准模型；不支持准备金机械乘数、现代充裕准备金制度下的固定方向或宏观效应大小。' },
  { id: 2, authors: 'Christina D. Romer & David H. Romer', year: '1990', title: 'New Evidence on the Monetary Transmission Mechanism', publication: 'Brookings Papers on Economic Activity 1990(1)', url: 'https://www.brookings.edu/articles/new-evidence-on-the-monetary-transmission-mechanism/', use: '支持用银行贷款与商业票据构成变化检验信贷传导的早期经验路径；不能单凭总量时序分离贷款供给、贷款需求或当代银行异质性。' },
  { id: 3, authors: 'Ben S. Bernanke & Alan S. Blinder', year: '1992', title: 'The Federal Funds Rate and the Channels of Monetary Transmission', publication: 'American Economic Review 82(4), 901–921; NBER Working Paper 3487', url: 'https://www.nber.org/papers/w3487', use: '支持联邦基金利率冲击后存款、证券和贷款的动态排序；历史 VAR 与政策指标解释不能自动成为现代结构冲击，也不能单独证明银行贷款供给。' },
  { id: 4, authors: 'Anil K. Kashyap, Jeremy C. Stein & David W. Wilcox', year: '1993', title: 'Monetary Policy and Credit Conditions: Evidence from the Composition of External Finance', publication: 'American Economic Review 83(1), 78–98; NBER Working Paper 4015', url: 'https://www.nber.org/papers/w4015', use: '支持紧缩后银行贷款相对商业票据变化及银行依赖借款人的识别动机；融资构成变化仍可能含需求与借款人选择，不能直接等同供给量。' },
  { id: 5, authors: 'Anil K. Kashyap & Jeremy C. Stein', year: '1994; NBER version 1993', title: 'Monetary Policy and Bank Lending', publication: 'Monetary Policy, University of Chicago Press; NBER Working Paper 4317', url: 'https://www.nber.org/papers/w4317', use: '支持银行贷款渠道的理论条件、证据谱系与银行/借款人两侧必要性；是综述和章节，不给出跨时期通用的因果效应。' },
  { id: 6, authors: 'Anil K. Kashyap & Jeremy C. Stein', year: '1995', title: 'The Impact of Monetary Policy on Bank Balance Sheets', publication: 'Carnegie-Rochester Conference Series on Public Policy 42; NBER Working Paper 4821', url: 'https://www.nber.org/papers/w4821', use: '支持按银行规模观察紧缩后的贷款与证券反应异质性；规模只是融资可得性的代理变量，不能被写成原始机制或完全需求控制。' },
  { id: 7, authors: 'Ben S. Bernanke & Mark Gertler', year: '1995', title: 'Inside the Black Box: The Credit Channel of Monetary Policy Transmission', publication: 'Journal of Economic Perspectives 9(4), 27–48; NBER Working Paper 5146', url: 'https://www.nber.org/papers/w5146', use: '支持区分 bank lending channel 与 borrower balance-sheet channel；不允许把借款人净值/抵押品反馈留在3.10，也不提供单一可直接估计的结构方程。' },
  { id: 8, authors: 'Jeremy C. Stein', year: '1998', title: 'An Adverse-Selection Model of Bank Asset and Liability Management with Implications for the Transmission of Monetary Policy', publication: 'RAND Journal of Economics 29(3), 466–486', url: 'https://www.jstor.org/stable/2556100', use: '支持受信息摩擦影响的存款与非存款融资替代、银行资产负债管理和贷款供给；模型假设不支持所有批发融资必然削弱传导。' },
  { id: 9, authors: 'Anil K. Kashyap & Jeremy C. Stein', year: '2000', title: 'What Do a Million Observations on Banks Say about the Transmission of Monetary Policy?', publication: 'American Economic Review 90(3), 407–428', url: 'https://www.aeaweb.org/articles?id=10.1257%2Faer.90.3.407', use: '支持流动性较弱的小银行对政策更敏感的横截面证据；作者也不据此给出渠道总量重要性的精确数值，银行规模本身不是机制。' },
  { id: 10, authors: 'Piti Disyatat', year: '2011; BIS version 2010', title: 'The Bank Lending Channel Revisited', publication: 'Journal of Money, Credit and Banking 43(4), 711–734; BIS Working Paper 297', url: 'https://www.bis.org/publ/work297.htm', use: '支持从“政策减少存款/准备金”改写为政策改变银行融资成本、资本实力与风险定价；不支持准备金无关或市场融资永远放大渠道的无条件结论。' },
  { id: 11, authors: 'Dwight M. Jaffee & Thomas Russell', year: '1976', title: 'Imperfect Information, Uncertainty, and Credit Rationing', publication: 'Quarterly Journal of Economics 90(4), 651–666', url: 'https://doi.org/10.2307/1885327', use: '支持不完全信息下价格之外的贷款数量约束；特定合同与类型假设不能推出现实银行在任一利率下都实行均衡配给。' },
  { id: 12, authors: 'Joseph E. Stiglitz & Andrew Weiss', year: '1981', title: 'Credit Rationing in Markets with Imperfect Information', publication: 'American Economic Review 71(3), 393–410', url: 'https://www.jstor.org/stable/1802787', use: '支持逆向选择和激励效应使贷款人预期回报对利率非单调，从而出现数量配给；这是模型结果，不是所有贷款市场的普遍经验规律。' },
  { id: 13, authors: 'Stephen D. Williamson', year: '1987', title: 'Costly Monitoring, Loan Contracts, and Equilibrium Credit Rationing', publication: 'Quarterly Journal of Economics 102(1), 135–145', url: 'https://doi.org/10.2307/1884684', use: '支持监督成本、最优债务合同与信用配给之间的机制联系；不能据此把实际审批拒绝全部归因于监督成本或货币政策。' },
  { id: 14, authors: 'Douglas W. Diamond', year: '1984', title: 'Financial Intermediation and Delegated Monitoring', publication: 'Review of Economic Studies 51(3), 393–414', url: 'https://academic.oup.com/restud/article-abstract/51/3/393/1545858', use: '支持银行作为委托监督者及贷款信息资本的理论基础；不直接决定现代贷款定价、资本比率或政策传导系数。' },
  { id: 15, authors: 'Eugene F. Fama', year: '1985', title: "What's Different About Banks?", publication: 'Journal of Monetary Economics 15(1), 29–39', url: 'https://doi.org/10.1016/0304-3932%2885%2990051-0', use: '支持银行借款人与存款合同所包含的信息作用；不能推出银行贷款对所有企业都不可替代或关系银行必然提高福利。' },
  { id: 16, authors: 'Raghuram G. Rajan', year: '1992', title: 'Insiders and Outsiders: The Choice between Informed and Arm’s-Length Debt', publication: 'Journal of Finance 47(4), 1367–1400', url: 'https://doi.org/10.1111/j.1540-6261.1992.tb04662.x', use: '支持知情关系贷款与保持距离融资之间的控制权和信息权衡；不能把关系存续直接解释成宽松供给或因果福利改善。' },
  { id: 17, authors: 'Mitchell A. Petersen & Raghuram G. Rajan', year: '1994', title: 'The Benefits of Lending Relationships: Evidence from Small Business Data', publication: 'Journal of Finance 49(1), 3–37', url: 'https://doi.org/10.1111/j.1540-6261.1994.tb04418.x', use: '支持关系持续时间与小企业信贷可得性/条款的经验联系；横截面关系不能自动净化企业质量、匹配选择或证明政策传导。' },
  { id: 18, authors: 'Allen N. Berger & Gregory F. Udell', year: '1995', title: 'Relationship Lending and Lines of Credit in Small Firm Finance', publication: 'Journal of Business 68(3), 351–381', url: 'https://doi.org/10.1086/296668', use: '支持授信额度、关系年龄与贷款条款的联系及承诺贷款的重要性；不能把承诺额、提款额、发放额和期末余额互换。' },
  { id: 19, authors: 'Mitchell Berlin & Loretta J. Mester', year: '1999', title: 'Deposits and Relationship Lending', publication: 'Review of Financial Studies 12(3), 579–607', url: 'https://doi.org/10.1093/revfin/12.3.0579', use: '支持核心存款融资平滑关系贷款合同的机制；不支持低存款beta必然扩大信贷，因为存款外流和替代融资可改变净效应。' },
  { id: 20, authors: 'Ruby P. Kishan & Timothy P. Opiela', year: '2000', title: 'Bank Size, Bank Capital, and the Bank Lending Channel', publication: 'Journal of Money, Credit and Banking 32(1), 121–141', url: 'https://doi.org/10.2307/2601095', use: '支持规模与资本共同刻画货币政策后的贷款异质性；分类变量仍是代理，不能替代融资、资本余量和借款人需求的直接度量。' },
  { id: 21, authors: 'Skander J. Van den Heuvel', year: '2002', title: 'Does Bank Capital Matter for Monetary Transmission?', publication: 'Federal Reserve Bank of New York Economic Policy Review 8(1)', url: 'https://www.newyorkfed.org/medialibrary/media/research/epr/02v08n1/0205vand.pdf', use: '支持资本约束使银行贷款对政策产生动态响应及资本渠道的概念边界；理论校准不能作为某家银行真实监管容量或即时贷款上限。' },
  { id: 22, authors: 'Leonardo Gambacorta & Paolo Emilio Mistrulli', year: '2004', title: 'Does Bank Capital Affect Lending Behavior?', publication: 'Journal of Financial Intermediation 13(4), 436–457; Bank of Italy Working Paper 486', url: 'https://www.bancaditalia.it/pubblicazioni/temi-discussione/2003/2003-0486/index.html', use: '支持资本与流动性缓冲对意大利银行贷款反应的异质性；单一法域历史样本不能给出现行Basel约束或全球通用弹性。' },
  { id: 23, authors: 'Shekhar Aiyar, Charles W. Calomiris & Tomasz Wieladek', year: '2014', title: 'How Does Credit Supply Respond to Monetary Policy and Bank Minimum Capital Requirements?', publication: 'Bank of England Staff Working Paper 508', url: 'https://www.bankofengland.co.uk/working-paper/2014/how-does-credit-supply-respond-to-monetary-policy-and-bank-minimum-capital-requirements', use: '支持政策利率和银行特定最低资本要求对英国信贷供给的异质影响；监管冲击与货币政策冲击不可混成同一处理。' },
  { id: 24, authors: 'Jonathan Bridges, David Gregory, Mette Nielsen, Silvia Pezzini, Amar Radia & Marco Spaltro', year: '2014', title: 'The Impact of Capital Requirements on Bank Lending', publication: 'Bank of England Staff Working Paper 486', url: 'https://www.bankofengland.co.uk/working-paper/2014/the-impact-of-capital-requirements-on-bank-lending', use: '支持银行特定资本要求后不同贷款部门和时滞的异质调整；过渡期历史估计不能直接外推为未来资本改革的固定乘数。' },
  { id: 25, authors: 'Itamar Drechsler, Alexi Savov & Philipp Schnabl', year: '2017', title: 'The Deposits Channel of Monetary Policy', publication: 'Quarterly Journal of Economics 132(4), 1819–1876', url: 'https://doi.org/10.1093/qje/qjx019', use: '支持存款市场势力、存款利率beta、存款流出与银行资产调整的联合机制；不能将低beta单独解释为低融资成本或更多贷款。' },
  { id: 26, authors: 'Leonardo Gambacorta & Hyun Song Shin', year: '2016 working paper; 2018 journal', title: 'Why Bank Capital Matters for Monetary Policy', publication: 'BIS Working Paper 558; Journal of Financial Intermediation 35', url: 'https://www.bis.org/publ/work558.htm', use: '支持更高银行资本与融资成本、贷款增长和政策传导的联系；跨国银行数据不能识别任一银行的监管约束或因果边际成本。' },
  { id: 27, authors: 'Marcia Millon Cornett, Jamie John McNutt, Philip E. Strahan & Hassan Tehranian', year: '2011', title: 'Liquidity Risk Management and Credit Supply in the Financial Crisis', publication: 'Journal of Financial Economics 101(2), 297–312', url: 'https://doi.org/10.1016/j.jfineco.2011.03.001', use: '支持核心存款、未使用承诺、流动资产与危机贷款调整的异质性；危机相关性不能直接成为常态货币政策冲击。' },
  { id: 28, authors: 'Victoria Ivashina & David Scharfstein', year: '2010', title: 'Bank Lending During the Financial Crisis of 2008', publication: 'Journal of Financial Economics 97(3), 319–338', url: 'https://doi.org/10.1016/j.jfineco.2009.12.001', use: '支持新贷骤降、银团结构和授信额度提款造成存量/流量背离；危机贷款下降不能仅凭总量分解为供给。' },
  { id: 29, authors: 'Viral V. Acharya & Nada Mora', year: '2015', title: 'A Crisis of Banks as Liquidity Providers', publication: 'Journal of Finance 70(1), 1–43', url: 'https://doi.org/10.1111/jofi.12182', use: '支持存款流入、昂贵替代融资和承诺额度履约共同改变银行流动性供给；危机证据不支持存款永远稳定或央行支持必然转化为贷款。' },
  { id: 30, authors: 'Evan Gatev, Til Schuermann & Philip E. Strahan', year: '2009', title: 'Managing Bank Liquidity Risk: How Deposit-Loan Synergies Vary with Market Conditions', publication: 'Review of Financial Studies 22(3), 995–1020', url: 'https://doi.org/10.1093/rfs/hhm060', use: '支持交易存款与未使用贷款承诺之间的流动性协同及状态依赖；不能把承诺额当作已发放信用或假定协同在压力期恒定。' },
  { id: 31, authors: 'Philipp Schnabl', year: '2012', title: 'The International Transmission of Bank Liquidity Shocks: Evidence from an Emerging Market', publication: 'Journal of Finance 67(3), 897–932', url: 'https://doi.org/10.1111/j.1540-6261.2012.01737.x', use: '支持全球银行通过境外融资冲击收缩秘鲁贷款及关系替代分析；特定危机和跨境网络不能代表国内政策的一般效应。' },
  { id: 32, authors: 'Nicola Cetorelli & Linda S. Goldberg', year: '2012', title: 'Banking Globalization and Monetary Transmission', publication: 'Journal of Finance 67(5), 1811–1843; Federal Reserve Bank of New York Staff Report 333', url: 'https://www.newyorkfed.org/research/staff_reports/sr333.html', use: '支持全球银行内部资本市场在政策冲击下跨国调配资金；不能把总部—分支流量机械解释为集团总贷款供给或忽略当地需求。' },
  { id: 33, authors: 'Anamaria Illes, Marco J. Lombardi & Paul Mizen', year: '2015', title: 'Why Did Bank Lending Rates Diverge from Policy Rates after the Financial Crisis?', publication: 'BIS Working Paper 486', url: 'https://www.bis.org/publ/work486.htm', use: '支持以银行融资成本而非单一政策率解释危机后贷款利率楔子；聚合估计不能分离审批、额度、关系匹配或单家银行供给。' },
  { id: 34, authors: 'Carlo Altavilla, Fabio Canova & Matteo Ciccarelli', year: '2020; ECB version 2016', title: 'Mending the Broken Link: Heterogeneous Bank Lending Rates and Monetary Policy Pass-Through', publication: 'Journal of Monetary Economics 110, 81–98; ECB Working Paper 1978', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1978.en.pdf', use: '支持欧元区贷款利率传导的银行、国家和借款人异质性；利率传导本身不证明数量供给渠道，也不能外推到未覆盖法域。' },
  { id: 35, authors: 'Claudio Borio & Leonardo Gambacorta', year: '2017', title: 'Monetary Policy and Bank Lending in a Low Interest Rate Environment: Diminishing Effectiveness?', publication: 'Journal of Macroeconomics 54(B), 217–231; BIS Working Paper 612', url: 'https://www.bis.org/publ/work612.htm', use: '支持低利率状态下贷款增长对进一步宽松可能减弱的跨国证据；不能据此断言存在统一反转利率或忽略需求、资本和存款结构。' },
  { id: 36, authors: 'Florian Heider, Farzad Saidi & Glenn Schepens', year: '2019', title: 'Life Below Zero: Bank Lending under Negative Policy Rates', publication: 'Review of Financial Studies 32(10), 3728–3761', url: 'https://doi.org/10.1093/rfs/hhz016', use: '支持负利率、零售存款依赖与银行贷款/风险调整的异质性；其中风险承担结果属于3.12，不能在3.10内解释为固定供给机制。' },
  { id: 37, authors: 'Gauti B. Eggertsson, Ragnar E. Juelsrud, Lawrence H. Summers & Ella Getz Wold', year: '2024; NBER version 2019', title: 'Negative Nominal Interest Rates and the Bank Lending Channel', publication: 'Review of Economic Studies 91(4), 2201–2275; NBER Working Paper 25416', url: 'https://www.nber.org/papers/w25416', use: '支持存款利率下限、银行净值和负政策利率传导受阻的理论与瑞典证据；不能把估计阈值移作其他制度的普遍反转点。' },
  { id: 38, authors: 'Joseph Abadi, Markus K. Brunnermeier & Yann Koby', year: '2023; NBER version 2018', title: 'The Reversal Interest Rate', publication: 'American Economic Review 113(8), 2084–2120; NBER Working Paper 25406', url: 'https://www.nber.org/papers/w25406', use: '支持利率降低可能因银行资本化与期限结构而在某状态反转贷款供给的理论条件；不提供可跨银行、跨时期直接套用的单一阈值。' },
  { id: 39, authors: 'Philippe Andrade, Christophe Cahn, Henri Fraisse & Jean-Stéphane Mésonnier', year: '2019', title: 'Can the Provision of Long-Term Liquidity Help to Avoid a Credit Crunch? Evidence from the Eurosystem’s LTRO', publication: 'Journal of the European Economic Association 17(4), 1070–1106', url: 'https://academic.oup.com/jeea/article/17/4/1070/5035663', use: '支持期限较长的央行流动性通过暴露异质性影响法国银行贷款供给；LTRO分配与普通政策率冲击不同，不能混为一类。' },
  { id: 40, authors: 'Matteo Benetton & Davide Fantino', year: '2021', title: 'Targeted Monetary Policy and Bank Lending Behavior', publication: 'Journal of Financial Economics 142(1), 404–429', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X21001823', use: '支持TLTRO分配规则下贷款利率、金额与竞争环境的供给效应；目标性融资的局部平均处理效应不代表一般降息或所有银行。' },
  { id: 41, authors: 'Alexander Rodnyansky & Olivier M. Darmouni', year: '2017', title: 'The Effects of Quantitative Easing on Bank Lending Behavior', publication: 'Review of Financial Studies 30(11), 3858–3887', url: 'https://academic.oup.com/rfs/article-abstract/30/11/3858/3867964', use: '支持不同资产购买通过银行事前证券暴露产生异质贷款反应；QE轮次和购入资产类型是识别核心，不能概括为准备金增加必然促贷。' },
  { id: 42, authors: 'Indraneel Chakraborty, Itay Goldstein & Andrew MacKinlay', year: '2020', title: 'Monetary Stimulus and Bank Lending', publication: 'Journal of Financial Economics 136(1), 189–218', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X19302260', use: '支持MBS购买推动抵押贷款同时挤出商业贷款的银行内重配与实体后果；资产定向结果不能推广为所有QE或净总信贷扩张。' },
  { id: 43, authors: 'Asim Ijaz Khwaja & Atif Mian', year: '2008', title: 'Tracing the Impact of Bank Liquidity Shocks: Evidence from an Emerging Market', publication: 'American Economic Review 98(4), 1413–1442', url: 'https://www.aeaweb.org/articles?id=10.1257%2Faer.98.4.1413', use: '支持同一借款人跨银行比较以净化共同需求并追踪贷款对供给；只识别多银行企业的局部效应，不能覆盖单银行企业、替代和一般均衡。' },
  { id: 44, authors: 'Gabriel Jiménez, Steven Ongena, José-Luis Peydró & Jesús Saurina', year: '2012', title: 'Credit Supply and Monetary Policy: Identifying the Bank Balance-Sheet Channel with Loan Applications', publication: 'American Economic Review 102(5), 2301–2326', url: 'https://www.aeaweb.org/articles?id=10.1257%2Faer.102.5.2301', use: '支持利用贷款申请同时观察审批、金额和银行资产负债表异质性；此处bank balance sheet是银行侧，不是3.11借款人抵押品渠道。' },
  { id: 45, authors: 'Hans Degryse, Olivier De Jonghe, Sanja Jakovljević, Klaas Mulier & Glenn Schepens', year: '2019', title: 'Identifying Credit Supply Shocks with Bank-Firm Data: Methods and Applications', publication: 'Journal of Financial Intermediation 40, 100813', url: 'https://doi.org/10.1016/j.jfi.2019.01.004', use: '支持比较多银行固定效应法与包含单银行企业的行业×地区×规模×时间需求控制；替代控制仍依赖同组需求同质假设，不能宣称完美识别。' },
  { id: 46, authors: 'Mary Amiti & David E. Weinstein', year: '2018; NBER version 2013–2017', title: 'How Much Do Idiosyncratic Bank Shocks Affect Investment? Evidence from Matched Bank-Firm Loan Data', publication: 'Journal of Political Economy 126(2), 525–587; NBER Working Paper 18890', url: 'https://www.nber.org/papers/w18890', use: '支持从匹配贷款分解银行供给、企业借款和共同冲击并连接投资；结构分解依赖模型与完整网络，不能由单一银行贷款增长替代。' },
  { id: 47, authors: 'Bo Becker & Victoria Ivashina', year: '2014', title: 'Cyclicality of Credit Supply: Firm Level Evidence', publication: 'Journal of Monetary Economics 62, 76–93; NBER Working Paper 17392', url: 'https://www.nber.org/papers/w17392', use: '支持有债券市场准入企业在银行贷款与债券之间的替代以识别信贷供给周期；样本偏向较大企业，不代表银行依赖型小企业。' },
  { id: 48, authors: 'Manju Puri, Jörg Rocholl & Sascha Steffen', year: '2011', title: 'Global Retail Lending in the Aftermath of the US Financial Crisis: Distinguishing between Supply and Demand Effects', publication: 'Journal of Financial Economics 100(3), 556–578', url: 'https://www.sciencedirect.com/science/article/pii/S0304405X10002904', use: '支持使用同一地区申请数据比较受冲击与未受冲击银行的审批供给；德国零售贷款设计不能直接外推企业贷款或货币政策。' },
  { id: 49, authors: 'Joe Peek & Eric S. Rosengren', year: '2000', title: 'Collateral Damage: Effects of the Japanese Bank Crisis on Real Activity in the United States', publication: 'American Economic Review 90(1), 30–45', url: 'https://www.aeaweb.org/articles?id=10.1257%2Faer.90.1.30', use: '支持日本母行资本冲击通过美国分支贷款影响当地建筑活动的跨境自然实验；银行危机冲击不等于常规政策冲击，行业结果也非宏观总量。' },
  { id: 50, authors: 'Gabriel Chodorow-Reich', year: '2014', title: 'The Employment Effects of Credit Market Disruptions: Firm-Level Evidence from the 2008–09 Financial Crisis', publication: 'Quarterly Journal of Economics 129(1), 1–59', url: 'https://doi.org/10.1093/qje/qjt031', use: '支持关系银行受冲击后企业信贷与就业变化及替代不完全；危机估计、样本支持和银行暴露工具不能直接成为常态政策弹性。' },
  { id: 51, authors: 'Federico Cingano, Francesco Manaresi & Enrico Sette', year: '2016', title: 'Does Credit Crunch Investment Down? New Evidence on the Real Effects of the Bank-Lending Channel', publication: 'Review of Financial Studies 29(10), 2737–2773', url: 'https://academic.oup.com/rfs/article-abstract/29/10/2737/2223378', use: '支持银行间流动性枯竭导致企业投资、增加值、就业与贸易信贷传播；危机反事实依赖工具和局部样本，不能外推统一乘数。' },
  { id: 52, authors: 'Kilian Huber', year: '2018', title: 'Disentangling the Effects of a Banking Crisis: Evidence from German Firms and Counties', publication: 'American Economic Review 108(3), 868–898', url: 'https://www.aeaweb.org/articles?id=10.1257%2Faer.20161534', use: '支持银行贷款收缩通过地区总需求和集聚外溢产生持久实体效应；局部外溢会破坏SUTVA，不能把企业直接效应简单加总。' },
  { id: 53, authors: 'Board of Governors of the Federal Reserve System', year: 'current quarterly survey; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'Senior Loan Officer Opinion Survey on Bank Lending Practices', publication: 'Federal Reserve Data', url: 'https://www.federalreserve.gov/data/sloos.htm', use: '支持区分审批标准、获批后的价格/额度/期限/契约条款和贷款需求；净比例是回答银行占比差而非收紧强度，也不是外生供给冲击。' },
  { id: 54, authors: 'Board of Governors of the Federal Reserve System', year: 'living methodology and weekly release; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'Assets and Liabilities of Commercial Banks in the United States — H.8: About', publication: 'Federal Reserve Statistical Release', url: 'https://www.federalreserve.gov/releases/H8/about.htm', use: '支持美国商业银行周度估计资产负债表、银行组别与调整方法；余额含需求、还款、核销、出售和重分类，不能直接解释为发放或供给。' },
  { id: 55, authors: 'Federal Financial Institutions Examination Council', year: 'current reporting forms and bulk data; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'Reporting Forms', publication: 'FFIEC Central Data Repository · Call Reports and bulk data', url: 'https://www.ffiec.gov/resources/reporting-forms', use: '支持按031/041/051表种、schedule/item/MDRM和RSSD构造银行融资、资本、流动性与贷款暴露；申报口径和修订会变，不能跨版本盲拼。' },
  { id: 56, authors: 'European Central Bank', year: 'living quarterly survey methodology; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'Bank Lending Survey (BLS)', publication: 'ECB Data Portal methodology', url: 'https://data.ecb.europa.eu/methodology/bank-lending-survey-bls', use: '支持欧元区贷款标准、条件、拒绝和需求的调查口径及净比例/扩散指数；调查判断不是贷款数量或结构冲击，临时问题不可与标准题混接。' },
  { id: 57, authors: 'European Central Bank', year: 'living methodology; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'Bank interest rates', publication: 'ECB Data Portal methodology, MFI Interest Rate Statistics', url: 'https://data.ecb.europa.eu/methodology/bank-interest-rates', use: '支持新业务与存量、AAR/APRC、初始固定期、期限、抵押和业务量的统一口径；聚合利率同时反映供需与构成，不能单独识别供给。' },
  { id: 58, authors: 'European Central Bank', year: 'living data-collection framework; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'AnaCredit', publication: 'ECB Statistics', url: 'https://www.ecb.europa.eu/stats/ecb_statistics/anacredit/html/index.en.html', use: '支持欧元区详细银行—法人借款人信用和风险属性的数据架构；机密微观数据并非公众下载资源，网页存在不代表可公开复算。' },
  { id: 59, authors: 'People’s Bank of China', year: 'new formation mechanism from 2019-08-20; accessed 2026-09-02', accessedAt: '2026-09-02', title: 'LPR', publication: 'PBC Monetary Policy Instruments · Loan Prime Rate', url: 'https://www.pbc.gov.cn/en/3688229/3688335/3730276/3883798/19e15ae1-4.html', use: '支持LPR报价行、形成方式、一年期/五年以上期限及其贷款定价参考身份；LPR不是每个借款人的实际报价，也不是结构政策冲击。' },
  { id: 60, authors: 'People’s Bank of China', year: 'living Chinese release index; accessed 2026-09-03', accessedAt: '2026-09-03', title: '数据解读', publication: '中国人民银行调查统计司 · 社会融资规模与金融统计发布栏目', url: 'https://www.pbc.gov.cn/diaochatongjisi/116219/116225/index.html', use: '支持社会融资规模存量/增量及工具覆盖的当前中文官方发布入口；旧英文 Aggregate Financing archive 最新清单停在2022年11月，只能作为历史镜像。社融是实体经济获得资金的聚合统计，不能等同银行新贷、贷款供给或审批标准。' },
  { id: 61, authors: 'Basel Committee on Banking Supervision', year: 'published 2020, effective 2023; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'CRE32 — IRB Approach: Risk Components', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/cre/32/inforce/2023-01-01/published/2020-03-27', use: '权威界定监管信用风险中的PD、LGD、EAD与期限等风险组件，并说明未提款承诺的EAD处理；本章的PD×LGD×EAD只是简化教学预期损失桥，不等于Basel资本公式或会计ECL。' },
  { id: 62, authors: 'Bank for International Settlements, Financial Stability Institute', year: '2022; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'Large Exposures Standard — Executive Summary', publication: 'FSI Executive Summaries', url: 'https://www.bis.org/publications/fsi-summary-large-exposures-standard-executive-summary', use: '支持把单一交易对手与关联交易对手组的大额暴露限制同一般风险资本要求分开；25% Tier 1资本是Basel框架基准，不可替代具体法域、豁免、CRM与内部限额版本。' },
  { id: 63, authors: 'Basel Committee on Banking Supervision', year: 'published 2024, effective 2026; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'SRP31 — Interest Rate Risk in the Banking Book', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/srp/31/inforce/2026-01-01/published/2024-07-16', use: '支持区分利率变化对银行账簿经济价值与收益的影响，并要求识别、计量与治理IRRBB；本标准不提供某家银行的对冲后净暴露或贷款供给弹性。' },
  { id: 64, authors: 'Joel Grant', year: '2011; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'Liquidity Transfer Pricing: A Guide to Better Practice', publication: 'Financial Stability Institute, BIS, Occasional Paper 10', url: 'https://www.bis.org/fsi/fsipapers10.pdf', use: '支持以匹配期限的边际资金成本和内部资金转移定价分配融资与流动性成本；这是风险管理良好实践，不意味着外部研究者能直接观测银行内部FTP曲线。' },
  { id: 65, authors: 'Claudio Borio & Haibin Zhu', year: '2008; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'Capital Regulation, Risk-taking and Monetary Policy: A Missing Link in the Transmission Mechanism?', publication: 'BIS Working Paper 268', url: 'https://www.bis.org/publications/working-paper-268-capital-regulation-risk-taking-and-monetary-policy-missing-link-transmission-mechanism', use: '直接支持货币政策可通过风险感知、定价与容忍度形成风险承担渠道的概念边界；它不支持把收益追逐、薪酬或任何高风险贷款构成变化直接认定为已识别因果效应。' },
  { id: 66, authors: 'IFRS Foundation', year: 'current issued standard landing page; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'IFRS 9 Financial Instruments', publication: 'IFRS Accounting Standards', url: 'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/', use: '支持金融资产转移后终止确认、继续涉入及保留风险与报酬的会计边界；具体证券化还受法域监管资本、法律真实出售和合并范围影响，不能由会计终止确认单独判断风险完全离表。' },
  { id: 67, authors: 'Basel Committee on Banking Supervision', year: 'published 2020, effective 2023; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'RBC20 — Calculation of Minimum Risk-based Capital Requirements', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/rbc/20/inforce/2023-01-01/published/2020-11-26', use: '直接支持以监管资本除以风险加权资产表达风险资本比率及Basel最低要求；资本构成、缓冲、法域实施和单笔贷款边际RWA仍须另行落地，本章合成参数不是合规判断。' },
  { id: 68, authors: 'Basel Committee on Banking Supervision', year: 'published 2020, effective 2023; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'LEV20 — Calculation', publication: 'Basel Framework · Leverage Ratio', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lev/20/inforce/2023-01-01/published/2020-03-27', use: '直接支持Tier 1资本除以杠杆暴露的非风险加权后备约束及最低要求；暴露计量还须读取LEV30，本章局部线性容量式不替代正式报表计算。' },
  { id: 69, authors: 'Basel Committee on Banking Supervision', year: 'current version updated 2022-12-08; effective 2019-12-15; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'LCR20 — Calculation', publication: 'Basel Framework · Liquidity Coverage Ratio', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lcr/20/inforce/2019-12-15/published/2022-12-08', use: '直接支持现行LCR20以高质量流动性资产存量覆盖30个日历日净现金流出的结构及最低要求；该页面状态为Current，生效日为2019-12-15、最后更新日为2022-12-08。HQLA资格、现金流系数和上限仍须读取相关章节与法域规则。' },
  { id: 70, authors: 'Basel Committee on Banking Supervision', year: 'published and effective 2019; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'NSF20 — Calculation and Reporting', publication: 'Basel Framework · Net Stable Funding Ratio', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/nsf/20/inforce/2019-12-15/published/2019-12-15', use: '直接支持可用稳定资金除以所需稳定资金的NSFR结构、至少100%的要求及一年结构期限；ASF/RSF因子仍须读取NSF30和法域实施。' },
  { id: 71, authors: 'Basel Committee on Banking Supervision', year: 'published and effective 2019; accessed 2026-09-03', accessedAt: '2026-09-03', title: 'LEX20 — Requirements', publication: 'Basel Framework · Large Exposures', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lex/20/inforce/2019-12-15/published/2019-12-15', use: '直接支持单一交易对手或关联交易对手组的大额暴露上限以Tier 1资本计量；适用层级、豁免、CRM、G-SIB规则及法域实施必须另行记录，不能外推到行业或地区集中度。' },
];

export const lesson310DynamicCommonRequirements = [
  'provider', 'retrievedAtUTC', 'releaseDate', 'publicationDate', 'observationDate', 'sourceVersion',
  'jurisdiction', 'institutionalUniverse', 'unit', 'frequency', 'methodologyURL', 'licenseAccess',
  'accessStatus', 'confidentiality', 'measurementFlag', 'fieldMissingReasons',
] as const;

export const lesson310DynamicSourceRequirements = [
  { sourceIds: [53], fields: ['surveyVintage', 'exactQuestionText', 'questionNumber', 'respondentUniverse', 'loanCategory', 'standardsOrTermsOrDemand', 'netPercentageDefinition', 'signConvention', 'weightedOrUnweighted', 'retrospectiveWindow', 'expectationsWindow', 'responseWindow', 'specialQuestionFlag', 'retrievedAtUTC'] },
  { sourceIds: [54], fields: ['releaseDate', 'dataThrough', 'weeklyWednesdayOrMonthlyAverage', 'seasonalAdjustment', 'bankUniverse', 'largeBankDefinition', 'benchmarkQuarter', 'panelAdjustment', 'mergerAdjustment', 'reclassificationAdjustment', 'revisionVintage', 'retrievedAtUTC'] },
  { sourceIds: [55], fields: ['formType031Or041Or051', 'reportingDate', 'filingRevisionTimestamp', 'institutionRSSD', 'consolidationBasis', 'schedule', 'itemLabel', 'mdrmCode', 'unit', 'instructionVintage', 'reportingThreshold', 'structuralBreakFlag', 'retrievedAtUTC'] },
  { sourceIds: [56], fields: ['surveyVintage', 'exactQuestionText', 'questionNumber', 'respondentUniverse', 'countryWeighting', 'loanCategory', 'creditStandardsOrTermsOrDemand', 'netPercentageDefinition', 'diffusionIndexDefinition', 'signConvention', 'backwardOrForwardWindow', 'responseWindow', 'adHocQuestionFlag', 'retrievedAtUTC'] },
  { sourceIds: [57], fields: ['datasetAndSeriesKey', 'releaseDate', 'jurisdiction', 'mfiUniverse', 'borrowerSector', 'currency', 'newBusinessOrOutstanding', 'rateConceptAarNderAprc', 'businessVolumeConcept', 'initialRateFixation', 'originalMaturity', 'residualMaturity', 'nextResetBucket', 'collateralOrGuaranteeFlag', 'aggregationWeight', 'renegotiationTreatment', 'revisionVintage', 'retrievedAtUTC'] },
  { sourceIds: [58], fields: ['manualVersion', 'validationRuleVersion', 'reportingThreshold', 'reportingPopulation', 'observedAgent', 'debtorSector', 'instrumentId', 'amountConcept', 'referenceDate', 'confidentialityClass', 'publicOrRestrictedAccess', 'accessApproval', 'revisionStatus', 'retrievedAtUTC'] },
  { sourceIds: [59], fields: ['formationMechanismVersion', 'effectiveFrom', 'tenor', 'fixingDate', 'publicationTimestamp', 'quotingBankPanel', 'quoteStep', 'trimmingRule', 'roundingRule', 'referenceOperationRate', 'officialChineseTextPriority', 'retrievedAtUTC'] },
  { sourceIds: [60], fields: ['releaseDate', 'observationPeriod', 'stockOrFlow', 'instrumentCoverage', 'entityAndResidencyBoundary', 'currency', 'unit', 'seasonalAdjustment', 'methodologyVersion', 'historicalRevision', 'structuralBreakFlag', 'bankLoanSubcomponentDefinition', 'officialChineseTextPriority', 'archiveLatestReleaseDate', 'retrievedAtUTC'] },
] as const;

const lesson310DynamicSourceIds = Array.from(new Set(
  lesson310DynamicSourceRequirements.flatMap(({ sourceIds }) => [...sourceIds]),
)).sort((left, right) => left - right);

export const lesson310SourceIdentityPassports = lesson310DynamicSourceIds.map((sourceId) => {
  const source = lesson310References.find((candidate) => candidate.id === sourceId);
  const requiredRefreshFields = Array.from(new Set(
    [
      ...lesson310DynamicCommonRequirements,
      ...lesson310DynamicSourceRequirements
      .filter((requirement) => requirement.sourceIds.some((candidateId) => candidateId === sourceId))
      .flatMap(({ fields }) => [...fields]),
    ]
  ));

  return {
    sourceId,
    authors: source?.authors ?? null,
    title: source?.title ?? null,
    publication: source?.publication ?? null,
    versionOrDate: source?.year ?? null,
    url: source?.url ?? null,
    identityCheckedOnDate: source?.accessedAt ?? null,
    accessStatus: sourceId === 55
      ? 'blocked-automated-access-needs-manual-or-bulk-data-check'
      : sourceId === 58
        ? 'public-methodology-page-restricted-confidential-microdata'
      : sourceId === 60
        ? 'public-live-chinese-index-with-stale-english-archive'
        : 'public-identity-page',
    backupAccessInstruction: sourceId === 55
      ? 'Use the official FFIEC reporting-forms page and its bulk-data/instructions links in a normal browser; record the form and instruction vintage.'
      : sourceId === 60
        ? 'Refresh from the official Chinese release index. Use https://www.pbc.gov.cn/en/3688247/3688978/3709140/48b09237-8.html only as a historical English archive and record its latest listed release date.'
        : null,
    requiredRefreshFields,
    measurementFlags: source
      ? ['identity-record-only-not-full-snapshot', 'refresh-required-before-empirical-use']
      : ['missing-source-record', 'identity-record-only-not-full-snapshot', 'refresh-required-before-empirical-use'],
  };
});

export const lesson310ReadingList: LessonReading[] = [
  { title: 'Bernanke–Blinder：银行贷款渠道的最小模型与早期动态证据', scope: '1988 模型与 1992 存款—证券—贷款动态', reason: '先理解“银行贷款与债券不完全替代”为什么是渠道成立的必要条件，再观察早期总量证据能与不能识别什么。', url: lesson310References[0].url, group: 'core', guide: '阅读时写出四个必要环节；不要把联邦基金利率创新、准备金变化和贷款供给当成同一个变量。', links: [{ label: '1988 基准模型', url: lesson310References[0].url }, { label: '1992 动态证据', url: lesson310References[2].url }] },
  { title: 'Kashyap–Stein–Wilcox：外部融资构成证据', scope: '银行贷款、商业票据与银行依赖借款人的相对变化', reason: '理解为什么融资构成比单看总贷款更接近渠道，但仍不能彻底排除需求和借款人选择。', url: lesson310References[3].url, group: 'core', guide: '把“贷款减少”和“贷款相对商业票据减少”分开；列出只有大企业能发行商业票据造成的样本选择。' },
  { title: 'Kashyap–Stein：从银行异质性识别贷款供给', scope: '1995 银行规模设计与 2000 流动性设计', reason: '学习横截面异质性如何帮助区分银行供给，同时看到规模只是市场融资能力的粗代理。', url: lesson310References[5].url, group: 'core', guide: '比较 size、liquidity、capital 三种暴露；任何异质性结论都写明借款人构成和政策冲击识别假设。', links: [{ label: '1995', url: lesson310References[5].url }, { label: '2000', url: lesson310References[8].url }] },
  { title: 'Disyatat：现代银行贷款渠道的改写', scope: '从存款/准备金数量改写为融资成本、银行实力与资产端决策', reason: '防止课程退回机械货币乘数，并把3.09的资产负债表状态正确接到3.10贷款供给。', url: lesson310References[9].url, group: 'core', guide: '画出传统叙述和改写叙述两条链；批发融资的作用必须允许随风险与制度状态变号。' },
  { title: '信用配给三论', scope: 'Jaffee–Russell、Stiglitz–Weiss 与 Williamson', reason: '解释为何贷款市场可通过拒绝、额度和合同条款调整，而不必由利率单独清算。', url: lesson310References[10].url, group: 'models', guide: '逐篇记录信息结构、合同空间和均衡概念；正文只把配给写成条件性模型结果。', links: [{ label: 'Jaffee–Russell', url: lesson310References[10].url }, { label: 'Stiglitz–Weiss', url: lesson310References[11].url }, { label: 'Williamson', url: lesson310References[12].url }] },
  { title: '银行为何特殊：监督与信息资本', scope: 'Diamond 委托监督与 Fama 的银行信息角色', reason: '为借款人不能无摩擦替换关系银行提供微观基础，同时避免把“银行特殊”写成绝对命题。', url: lesson310References[13].url, group: 'models', guide: '区分监督技术、私有信息和支付/存款功能；它们不是同一摩擦。', links: [{ label: 'Diamond', url: lesson310References[13].url }, { label: 'Fama', url: lesson310References[14].url }] },
  { title: '关系贷款：信息、锁定与合同平滑', scope: 'Rajan、Petersen–Rajan、Berger–Udell 与 Berlin–Mester', reason: '理解关系既能改善信息和跨期定价，也会增加转换成本并影响银行—借款人匹配。', url: lesson310References[15].url, group: 'models', guide: '把关系年龄、额度、提款、条款和存款融资分别编码；相关性证据不可自动解释为关系的因果收益。', links: [{ label: '知情与保持距离融资', url: lesson310References[15].url }, { label: '小企业关系', url: lesson310References[16].url }, { label: '授信额度', url: lesson310References[17].url }, { label: '存款与关系贷款', url: lesson310References[18].url }] },
  { title: '银行资本如何进入货币传导', scope: 'Van den Heuvel、Gambacorta–Mistrulli、Aiyar 与 Bridges', reason: '把资本比率、资本余量、资本影子价格和监管要求冲击分成不同概念。', url: lesson310References[20].url, group: 'evidence', guide: '资本容量计算只作其他资产固定的教学近似；不要把监管改革冲击等同货币政策冲击。', links: [{ label: '资本渠道理论', url: lesson310References[20].url }, { label: '意大利银行证据', url: lesson310References[21].url }, { label: '货币政策与最低资本要求', url: lesson310References[22].url }, { label: '资本要求与部门贷款', url: lesson310References[23].url }] },
  { title: '存款渠道、融资结构与流动性承诺', scope: '存款beta、存款迁移、核心存款、承诺额度与流动性缓冲', reason: '建立低存款beta既可能保护成本、也可能触发流出的双向机制，并解释压力期存量贷款为何可能因提款而上升。', url: lesson310References[24].url, group: 'evidence', guide: '分别保存平均与边际融资成本、存款价格与数量、承诺与提款；不要预设净方向。', links: [{ label: 'Deposits channel', url: lesson310References[24].url }, { label: '流动性与信贷供给', url: lesson310References[26].url }, { label: '银行作为流动性提供者', url: lesson310References[28].url }, { label: '存款—承诺协同', url: lesson310References[29].url }] },
  { title: '贷款利率传导：政策率、融资成本与银行楔子', scope: '危机后政策率—融资成本—贷款率脱钩及欧元区异质性', reason: '把广义利率传导与独立的银行贷款供给渠道分开，并理解贷款率黏性的银行侧来源。', url: lesson310References[32].url, group: 'evidence', guide: '先对齐币种、期限和重定价期；新业务与存量利率必须分图。', links: [{ label: '融资成本楔子', url: lesson310References[32].url }, { label: '异质传导', url: lesson310References[33].url }] },
  { title: '低利率、负利率与反转边界', scope: '低利率有效性、存款下限、银行资本化与 reversal rate', reason: '学习传导为何可能衰减、非线性甚至反转，同时避免把某一估计阈值普遍化。', url: lesson310References[34].url, group: 'models', guide: '把低存款beta、存款外流、净息差、资产久期和资本分别设为状态变量；3.12才处理风险容忍度变化。', links: [{ label: '低利率跨国证据', url: lesson310References[34].url }, { label: '负利率银行异质性', url: lesson310References[35].url }, { label: '负利率贷款渠道', url: lesson310References[36].url }, { label: 'Reversal rate', url: lesson310References[37].url }] },
  { title: '期限流动性与目标性再融资', scope: 'LTRO 与 TLTRO 的银行暴露、贷款价格和数量', reason: '比较一般期限流动性与带贷款激励的目标性工具，理解政策设计为什么改变estimand。', url: lesson310References[38].url, group: 'systems', guide: '保存分配规则、资格、抵押品、期限、激励阈值和竞争环境；局部处理效应不外推为一般降息。', links: [{ label: 'LTRO', url: lesson310References[38].url }, { label: 'TLTRO', url: lesson310References[39].url }] },
  { title: 'QE、资产暴露与银行内重配', scope: 'MBS/Treasury购买、证券暴露、抵押贷款与商业贷款挤出', reason: '展示非常规政策可以改变资产相对回报和资本空间，而不必产生统一方向的总贷款效应。', url: lesson310References[40].url, group: 'evidence', guide: '逐轮保存购买资产、银行事前持仓和未直接目标贷款；绝不把准备金增加机械写成贷款增加。', links: [{ label: 'QE异质贷款反应', url: lesson310References[40].url }, { label: 'MBS与商业贷款挤出', url: lesson310References[41].url }] },
  { title: '同一借款人设计：能识别什么', scope: 'Khwaja–Mian 与 Jiménez 等贷款申请数据', reason: '学习在借款人需求可比时识别银行供给的核心思路，并区分贷款关系余额与申请审批。', url: lesson310References[42].url, group: 'evidence', guide: '明确估计单位是bank–firm pair；记录多银行样本限制、申请选择、银行暴露及政策冲击护照。', links: [{ label: '同借款人设计', url: lesson310References[42].url }, { label: '贷款申请识别', url: lesson310References[43].url }] },
  { title: '从多银行企业走向单银行企业', scope: 'Degryse 等的替代需求控制与供给冲击估计', reason: '正视同借款人固定效应排除最依赖单一关系的小企业这一外部有效性问题。', url: lesson310References[44].url, group: 'evidence', guide: '比较 borrower×time FE 与 industry×location×size×time FE；后者仍需组内需求同质假设，最好给出敏感性范围。' },
  { title: '银行供给冲击的网络分解与债券替代', scope: 'Amiti–Weinstein 银行/企业冲击分解与 Becker–Ivashina 银行贷款—债券替代', reason: '把贷款对效应、借款人外部融资总额和宏观聚合分开，并测量“spare tire”是否实际存在。', url: lesson310References[45].url, group: 'evidence', guide: '先算银行对贷款，再加总其他银行、债券、非银与商业信用；内部现金另进入资源缓冲，债券样本通常偏向大企业。', links: [{ label: '匹配网络冲击分解', url: lesson310References[45].url }, { label: '银行贷款与债券替代', url: lesson310References[46].url }] },
  { title: '从银行贷款到就业、投资与地区外溢', scope: 'Chodorow-Reich、Cingano等与Huber的实体结果', reason: '建立“供给冲击—总融资—企业决策—地区外溢”的分层因果链，而不是把贷款系数直接称为宏观乘数。', url: lesson310References[49].url, group: 'evidence', guide: '分别报告直接企业效应、替代融资、时滞和空间/投入产出外溢；局部均衡结果不可机械加总。', links: [{ label: '就业效应', url: lesson310References[49].url }, { label: '投资与贸易信贷传播', url: lesson310References[50].url }, { label: '地区外溢', url: lesson310References[51].url }] },
  { title: 'SLOOS 与 ECB BLS：标准、条款和需求', scope: '原题、净比例、扩散指数、回顾/预期窗口与临时问题', reason: '用调查数据观察价格之外的信贷条件，同时防止把回答占比当作连续强度或外生供给冲击。', url: lesson310References[52].url, group: 'rules', guide: '任何图都保存原题和问卷版本；美国与欧元区的符号、样本和加权方式分别处理。', links: [{ label: 'Fed SLOOS', url: lesson310References[52].url }, { label: 'ECB BLS', url: lesson310References[55].url }] },
  { title: 'H.8 与 Call Reports：银行存量和约束字段', scope: '周度估计资产负债表与季度监管申报', reason: '用H.8做聚合状态，用Call Reports构造银行融资、资本、流动性和贷款类别暴露。', url: lesson310References[53].url, group: 'rules', guide: 'H.8保存银行组别与重分类；Call Reports保存表种、schedule/item、MDRM、RSSD和说明书版本。', links: [{ label: 'H.8方法', url: lesson310References[53].url }, { label: 'FFIEC forms', url: lesson310References[54].url }] },
  { title: 'ECB MIR、AnaCredit 与中国动态入口', scope: '新贷/存量利率、贷款级信用架构、LPR及社会融资规模', reason: '训练跨法域数据护照，并明确公开聚合数据、受限微观数据、定价参考与总融资统计的不同身份。', url: lesson310References[56].url, group: 'rules', guide: 'MIR记录rate concept和reset bucket；AnaCredit记录访问权限；LPR不是实际报价；社融不等于银行贷款供给。', links: [{ label: 'ECB MIR', url: lesson310References[56].url }, { label: 'AnaCredit', url: lesson310References[57].url }, { label: 'PBC LPR', url: lesson310References[58].url }, { label: 'PBC Aggregate Financing', url: lesson310References[59].url }] },
  { title: 'Basel五类容量规则、风险组件与IRRBB：原生计量对象不可相加', scope: 'RBC20、LEV20、LCR20、NSF20、LEX20、CRE32 与 SRP31', reason: '把风险资本、非风险加权杠杆、30日流动性、一年稳定融资、单一对手方集中、信用风险参数和银行账簿利率风险拆成独立审计链。', url: lesson310References[66].url, group: 'rules', guide: '分别读取各章的定义、计算式、最低要求、生效版本和适用范围；先保留原生horizon，再映射到同一目标贷款本金容量。Basel基准不等于具体法域规则，也不等于单家银行合规结论。', links: [{ label: 'RBC20', url: lesson310References[66].url }, { label: 'LEV20', url: lesson310References[67].url }, { label: 'LCR20', url: lesson310References[68].url }, { label: 'NSF20', url: lesson310References[69].url }, { label: 'LEX20', url: lesson310References[70].url }, { label: 'CRE32', url: lesson310References[60].url }, { label: 'IRRBB', url: lesson310References[62].url }] },
  { title: '匹配期限FTP与风险转移边界', scope: 'FSI Liquidity Transfer Pricing §3.5/Figure 6；IFRS 9 3.2.15–3.2.17', reason: '用内部FTP理解MCF如何进入报价，同时确认贷款出售后会计终止确认不等于所有经济风险自动消失。', url: lesson310References[63].url, group: 'rules', guide: '先读FTP §3.5及Figure 6，画出reference、term-liquidity premium与其他影子成本的去重账本；再从IFRS 9当前标准入口定位3.2.15–3.2.17。正文访问可能要求免费IFRS登录，实际适用时必须核对当前issued text。', links: [{ label: 'Liquidity transfer pricing', url: lesson310References[63].url }, { label: 'IFRS 9 current landing page · 正文可能需登录', url: lesson310References[65].url }] },
];
