import CapitalFlowLabStatic from '../components/CapitalFlowLabStatic';
import '../components/CapitalFlowPrint.css';
import CapitalFlowQuiz from '../components/CapitalFlowQuiz';
import CapitalFlowStaticQuiz from '../components/CapitalFlowStaticQuiz';
import CapitalFlowScopeDiagram from '../components/CapitalFlowScopeDiagram';
import {flowLabs,flowLabAudit} from '../components/capitalFlowLabDefinitions';
import {flowScenarios,flowScenarioAudit} from '../components/capitalFlowScenarios';
import {capitalFlowConcepts,capitalFlowThesis} from './capitalFlowConcepts';
import {lesson321References,lesson321ReadingList} from './capitalFlowReferences';
import {flowChecks,flowGlossary,flowInvariants,flowInterfaces} from './capitalFlowStudy';
import {canonicalCapitalFlowStateExample,canonicalCapitalFlowFields,canonicalCapitalFlowAudit} from './capitalFlowState';
import type {LessonRecord} from './types';
export {canonicalCapitalFlowStateExample,canonicalCapitalFlowFields,canonicalCapitalFlowAudit} from './capitalFlowState';
function Cites({ids}:{ids:readonly number[]}){return <>{ids.map(id=><a key={id} href={`#ref-${id}`}>[{id}] </a>)}</>;}
const extraSections=[{id:'scope-route',label:'居住／单位／日期护照'},{id:'capital-scope-map',label:'具体账本与反馈'},{id:'model-map',label:'恒等式／菜单／识别'},{id:'interactive-lab',label:'Interactive M1–M10'},{id:'capital-static-twins',label:'Static K1–K10'},{id:'checks-glossary',label:'Checks / Audit / Glossary'},{id:'evidence-boundaries',label:'State / Sources / Interfaces'}];
const sectionIds=['thesis',...capitalFlowConcepts.map(c=>c.id),...extraSections.map(s=>s.id)];
const sourceIds=new Set(lesson321References.map(r=>r.id));
const citations=[...capitalFlowConcepts.flatMap(c=>c.sourceIds),...flowLabs.flatMap(l=>l.sourceIds),...flowScenarios.flatMap(s=>s.sourceIds),...flowChecks.flatMap(c=>c.sourceIds)];
export const lesson321IntegrityAudit=[
 {key:'27 single-mechanism editorial units with three substantive paragraphs and explicit source/conditions each',passed:capitalFlowConcepts.length===27&&capitalFlowConcepts.every(c=>c.paragraphs.length===3&&c.paragraphs.every(p=>p.length>=90)&&c.boundary.length>=30&&c.sourceNote.length>=20&&c.sourceIds.length>0)},
 {key:'all section IDs unique and each of seven independent C labs attached exactly once',passed:new Set(sectionIds).size===sectionIds.length&&capitalFlowConcepts.flatMap(c=>c.labIds??[]).length===7&&new Set(capitalFlowConcepts.flatMap(c=>c.labIds??[])).size===7&&capitalFlowConcepts.flatMap(c=>c.labIds??[]).every(id=>flowLabs.some(l=>l.id===id))},
 {key:'eight primary references and eight deeper reading routes with actual reading scope and valid citation IDs',passed:lesson321References.length===8&&lesson321ReadingList.length===8&&citations.every(id=>sourceIds.has(id))&&lesson321References.every(r=>r.use.length>=60&&r.url.startsWith('https://'))},
 {key:'20 checks,40 decoded terms,16 invariants and eight concrete cross-chapter interfaces',passed:flowChecks.length===20&&flowGlossary.length===40&&flowInvariants.length===16&&flowInterfaces.length===8},
 {key:'finite source and SYN-contract audits pass but do not register two whole-lesson approvals',passed:[...flowLabAudit,...flowScenarioAudit,...canonicalCapitalFlowAudit].every(a=>a.passed)},
] as const;
function Lesson321Content(){return <>
 <noscript><style>{'.lesson-page[data-lesson-id="3.21"] .capital-flow-interactive-only,.lesson-page[data-lesson-id="3.21"] #interactive-lab{display:none!important}'}</style><p>脚本已关闭：七C固定输入、99行完整默认结果与手算，K1–K10三候选和三条诊断、四卡机制图与引用均可原生阅读。展开固定记录即可；打印直接保留完整答案。</p></noscript>
 <section id="thesis" className="lesson-section"><p className="section-kicker">ONE CENTRAL MECHANISM · SPECIFIC RESIDENT BALANCE SHEET</p><h2>跨境交易只有进入具体账本与有日期约束，才能解释国内信用和价格。</h2>{capitalFlowThesis.map(p=><p key={p}>{p}</p>)}<p className="section-sources"><Cites ids={[1,2,3,4,5]}/></p></section>
 <section id="scope-route" className="lesson-section"><p className="section-kicker">RESIDENCE / UNIT / DATE / OPERATION PASSPORT</p><h2>先写谁收钱、欠什么币和何时付款，再问能做多少。</h2>
 <p>Master先修是3.20，延续S=本币/一单位外币：S上升表示本币贬值。本币与外币随观察者定义，不预设人民币／美元。3.20实际批准版本、审稿记录和已存在canonical对象保留原身份；它们只提供语义与版本依据，没有把任何旧实验结果灌入本节七个独立输入。需要时按需回查T02/T05/T06/T08与3.09–3.13，补复利、因果、银行两侧、风险和金融条件，不要求先学完整国际宏观。</p>
 <p>统计先解码：BOP（balance of payments，国际收支）记录期间居民—非居民交易；IIP（international investment position，国际投资头寸）记录参考日外部金融存量，须与交易、重估和其他变化区分。CA是经常账户、KA是资本账户、FA是金融账户；俗称capital flow不意味着全记录在KA。C1注明FA=A−L，再另定义N=L−A讲净向内融资，两者正号相反；|A|+|L|仅教学腿规模，不是官方gross交易总量。 <Cites ids={[1,2,3]}/></p>
 <p>银行最小账中，贷款、证券和央行准备金属资产，存款与借款属负债，权益是资产减负债；总资产/权益杠杆和风险加权资产RWA（risk-weighted assets）资本比率是不同量。PD（probability of default）是违约概率，LGD（loss given default）是违约损失率，两者不等于教学资本下限或风险权重。融资room是合同给定菜单上限，不是等候从准备金桶里贷走的现金。 <Cites ids={[4,5]}/></p>
 <p>单位护照：报价和单位价用整数百分刻度，输入200=2、500=5，不是报价涨200%或500%。资本下限1000基点=10%，新风险权重10000基点=100%，各有独立正整数域，不沿用利率网格。份额40=40%；C7候选价90=题设面值1的90%，200=200%，不是收益率基点。金额、库存与带符号净腿域只限定教学精度和有限显示，不是市场tick、法律额度或经济可行的全部范围。</p>
 <p>SYN表示synthetic合成账／合同／条件菜单。C2的一次借款不自动成为C3融资余量，C1净向内不生成C5央行购汇，C4付款人已在本窗口前持有在岸存款，C6同T可用余额排除单列确认收款，C7固定价与买方容量不生成内生冲击函数。精确符号与账本用安全整数乘积先检查/闭合，除法仍有有限浮点和显示舍入；不能把12位展示叫12位账准确性，更不是精确有理数国家轨迹。</p>
 <div className="precision-note"><span>审稿状态：完整正文修订版已通过同版两位独立正式审批</span><p>有限算术预审不替代完整教材审批。两位非作者独立审稿人已核对同一完整修订稿的机制、八来源与读取边界、七C、十M/K、状态和成品；原r1修改要求与失败证据保留，M3分子、BPM7定位、标题和分页已修正复核。作者自检、附件作者及辅助67页布局检查不计入这两位审批。批准的是有范围的教材；真实贷款、用途、兑换许可、法定违约、政策福利、市场因果与PIT（point-in-time，当时可得资料）仍未认证。</p></div>
 <p>来源机构与范围先解码：BIS（Bank for International Settlements，国际清算银行）、BoE（Bank of England，英格兰银行）、IMF（International Monetary Fund，国际货币基金组织）和FSB（Financial Stability Board，金融稳定理事会）只为所列原文负责，不为本课SYN背书。BPM7指所列March2025第七版综合国际收支/头寸手册白封面预编辑版。FSB2023本次开放式基金建议非直接约束性法律，排除MMF（money market funds，货币市场基金）与ETF（exchange-traded funds，交易所交易基金）；不扩成所有基金即时法规。 <Cites ids={[1,4,7,8]}/></p>
 </section>
 {capitalFlowConcepts.map((c,i)=><section id={c.id} key={c.id} className="lesson-section"><p className="section-kicker">{String(i+1).padStart(2,'0')} · CORE MECHANISM</p><h2>{c.title}</h2>{c.paragraphs.map(p=><p key={p}>{p}</p>)}{c.formula?<div className="equation-card"><span>只用于澄清对象的必要算式</span><div><code>{c.formula.expression}</code></div><p>{c.formula.explanation}</p></div>:null}<div className="precision-note"><span>成立条件、反例与跨章接口</span><p>{c.boundary}</p></div>{c.labIds?.map(id=><CapitalFlowLabStatic key={id} labId={id}/>)}<p className="section-sources"><b>本机制依据：</b><Cites ids={c.sourceIds}/>{c.sourceNote}</p></section>)}
 <section id="capital-scope-map" className="lesson-section"><p className="section-kicker">SPECIFIC ACCOUNTS / CONDITIONAL FEEDBACK · CONCEPTUAL</p><h2>每条入口落在不同账本，反馈还要经过实际行为。</h2><p>四卡按银行、证券收款者、央行另定操作与到期/基金现金呈现完整机制。它们不是必须顺序发生的四阶段，更不是七C共享真实国家路径；卡间箭头仅标下一条应观察的连接，不证明价格、信用或政策已经响应。</p><CapitalFlowScopeDiagram/></section>
 <section id="model-map" className="lesson-section"><p className="section-kicker">IDENTITY / STIPULATED MENU / IDENTIFIED BEHAVIOR</p><h2>账本闭合，最多可行与真的发生，各需自己的证据。</h2><div className="evidence-map">
  <div><h3>定义与隔离账</h3><p>C1净腿、C2借款两侧、C4同银行转账、C5两笔央行操作，先固定交易和对手方。账闭合能否定漏记义务，却不生成市场价、M2、法定许可或发行人后续投资。 <Cites ids={[1,3,4,6]}/></p></div>
  <div><h3>题设可行菜单</h3><p>C3三门、C6外币容量、C7候选价承接，只算给定条件下可得或最多能做多少。真实银行喜好、兑换规则和基金付款没给；菜单不是批准量、违约或完成NAV。 <Cites ids={[4,5,7]}/></p></div>
  <div><h3>条件经验与局部识别</h3><p>WP1051的多银行企业比较有样本、暴露与测量条件，不因企业—时点控制就随机分配融资。价格/资金双向反馈、借款人替代和政策响应另找记录；所读文章不是本课因果系数。 <Cites ids={[2,5,8]}/></p></div>
 </div><p>开放地图可以复杂，具体问题要局部可证伪。知道下一步缺哪个主体、哪天现金和什么操作，比把所有未知填成“流入利好”更有解释力。</p></section>
 <section id="interactive-lab" className="lesson-section"><p className="section-kicker">INTERACTIVE M1–M10</p><h2>先锁净额、权益、门和币种，再作中性数值选择。</h2><p>十题保留对应C的完整输入与同一护照，初始ABC只给数值和单位；选后才显示当前候选诊断，改选立即替换旧反馈。M5只另把RWA改100，明说是独立条件；其余用原默认，不拼共同路径。二十条错误表达分别漏掉或错接符号、负债、分母、已有RWA、收款者、存款抵销、第二笔操作、币种或容量，均不是随意造错数。</p><CapitalFlowQuiz/></section>
 <section id="capital-static-twins" className="lesson-section"><p className="section-kicker">STATIC K1–K10 / NATIVE / PRINT</p><h2>关掉脚本或在纸上，也能重建三条推理。</h2><p>每K与对应M完整同题、同输入、同护照、同ABC顺序。先写对象、日期和单位再展开；原生折叠保留正确路径和两条错路，打印直接保留全部诊断。错误数字有时能回答另一问题，不能因此替本题漏掉一项义务或一个容量门。</p><CapitalFlowStaticQuiz/></section>
 <section id="checks-glossary" className="lesson-section"><p className="section-kicker">CHECKS / INTEGRITY / GLOSSARY</p><h2>知道哪一步仍未知，才能把资本流放回系统。</h2><div className="check-grid">{flowChecks.map((c,i)=><div key={c.question}><details><summary>{String(i+1).padStart(2,'0')} · {c.question}</summary><p>{c.answer} <Cites ids={c.sourceIds}/></p></details><p className="print-only"><b>{String(i+1).padStart(2,'0')} · {c.question}　答案：</b>{c.answer} <Cites ids={c.sourceIds}/></p></div>)}</div><div className="yield-fixture-audit"><span>有限来源完整性与契约门（作者自检，非独立审批）</span><ul>{[...flowLabAudit,...flowScenarioAudit,...canonicalCapitalFlowAudit,...lesson321IntegrityAudit].map(a=><li key={a.key} className={a.passed?'passed':''}>{a.passed?'PASS':'FAIL'} · {a.key}</li>)}</ul></div><div className="term-grid">{flowGlossary.map(([term,meaning,confusion])=><article className="term-card" key={term}><h3>{term}</h3><p>{meaning}</p><em>不可混同：{confusion}</em></article>)}</div></section>
 <section id="evidence-boundaries" className="lesson-section"><p className="section-kicker">STATE / ACTUAL READING / RESEARCH / INTERFACES</p><h2>保留版本、输入、时钟与未知，不输出虚构完整国家。</h2>
 <p>canonical有{canonicalCapitalFlowFields.length}个顶层字段；七个原始输入保留各自Object.is身份，inputLineage为空，因为并未消耗上节数值。实际先修3.20的版本、两位批准记录与真实存在canonical对象保存原身份，其批准正文冻结时钟为{canonicalCapitalFlowStateExample.semanticPrerequisiteState.producerMarker.approvedBodyFrozenAt}；本节登记为{canonicalCapitalFlowStateExample.scopePassport.registeredAt}，本节同版批准正文冻结为{canonicalCapitalFlowStateExample.clockState.ownReviewFrozenAt}，均不是历史市场资料可得时间，也不是之后出版封版包的建立时间。版本依据不变成数值校准或原金融条件。</p>
 <div className="precision-note"><span>canonical · {canonicalCapitalFlowStateExample.schemaVersion}</span><p><code>{canonicalCapitalFlowFields.join(', ')}</code>。实际价格/订单、银行批准/意愿、政策响应、真授权/基金权利、因果/PIT/预测与福利保留未知；C2无新增本币贷款、C4总存款0、C5净基础0只限已给隔离操作。真实数据护照为空，不造国家系列。</p></div>
 <h3>生产者不变量</h3><ol className="contract-list">{flowInvariants.map((r,i)=><li key={r}><b>{String(i+1).padStart(2,'0')}</b><span>{r}</span></li>)}</ol>
 <h3>实际读过与尚未读过的原文</h3>
 <p>BPM7沿用上节指定chapter2/储备/账户选段，本节先完整实读原PDF50–53及281–285文字，完整初稿审查后另补读原PDF55的2.17–2.18及Box2.1开头，核FA资产减负债方向、净借贷和双重记账；新增阅读钟单独留存。前述选段核居民交易、IIP桥和投票关系，不称1076页全文或Annex/OECD/CDIS通读。WP524实读1–11及16–22文字、实际看Graph1原PDF10；WP525先读5–18再补1–4封面/摘要目录。两文其余经验/模型/Annex与引用论文未通读或重估，历史总量和模型周转不移作本课参数。各次读取钟分别保留，不倒称先前笔记已含后读。 <Cites ids={[1,2,3]}/></p>
 <p>BoE2014原14页全部文字与参考目录已读，实际看Figure1原PDF3；其余图数据及所引论文未逐项复现，UK当时制度不是当前全球事实。WP1051实读1–23文字，实际看13的Graph1/Equation1；24–35/Annex、原国别登记与引用研究尚未通读/重估。多银行企业控制、相对资本组和Chile定价/增长范围分别保留，不借论文名认证统一因果系数。 <Cites ids={[4,5]}/></p>
 <p>Lee EI7原23页全部文字含preface与imprint实读；February1997原印记、March网页条目与电子书时间分开，底层WP96/53与现代法域规则未读。旧HTML/电子书正文403并未被伪装为已读，原PDF实际取得并校验。FSB2023实读原1–8及14–17文字；其余和Annex/IOSCO待读，MMF/ETF排除、非约束性与footnote15的先动成本条件明确。历史计划不冒认2026实施成效。 <Cites ids={[6,7]}/></p>
 <p>IMF2022取得98页releasepackage，只实读1–6与9–12完整文字，另读官方FAQ实质问答；其余含四背景说明未通读。staff、Board和release三时钟不同，收益/风险和预防性政策条件不等于当前国家许可或最优结论。八来源原件只作私有阅读证据，网页引用官方入口，不发布版权全文镜像；每位作者/审稿者的个人读取与执行范围各自留存，不把别人的阅读或检查借作自己的。 <Cites ids={[8]}/></p>
 <h3>把地图缩成可以验证的问题</h3><p>若研究资本流对银行信贷，先锁流入类别、币种、居民单位、银行暴露、消息/到账/到期窗口；用合适对照辨供给与企业需求，并检查企业替代融资。若研究资产价，改锁订单、流动性与公布预期，不能沿用银行回归当需求曲线。PIT（point-in-time）要求当时可得版本；当前下载历史文件、预审有理数案例和网站验收都不证明历史因果或样本外预测。研究基线、成本与生产资格需要另行实测。</p>
 <h3 id="capital-cross-interfaces">跨章接口</h3><div className="interface-grid">{flowInterfaces.map(([name,payload,guardrail])=><article key={name}><span>{name}</span><p><b>传递什么：</b>{payload}</p><p><b>不可跨越：</b>{guardrail}</p></article>)}</div><p>最后用一条完整链复盘：外部主体先改哪条交易腿，钱或索赔进入哪个居民账本，哪道有日期约束改变，主体实际如何选择，行为经什么承接改变价格/信用，新状态又如何进入下一轮。每一步分别问“已发生的记录、给定菜单还是待识别行为”；缺证据就留未知，不以复杂地图替证伪，也不以简单净数替全部世界。</p>
 </section>
 </>;}
export const lesson321:LessonRecord={slug:'3-21',id:'3.21',chapter:'03',chapterTitle:'Macro State & Financial Conditions',title:'Capital Flow 国内入口：账本、融资与价格反馈',subtitle:'把海外融资拆回银行借款、集团回流、一级与二级收款者，再辨央行两笔操作、到期外币与本币基金现金承接，追踪异质选择和多时钟反馈',readingTime:'正文主线约50–70分钟，七C必要手算约20–30分钟；M/K十题约20–35分钟、检查/术语/复盘约25–40分钟可另学。均是学习估时，原典深化另计，不靠凑字保证时长',prerequisite:'Master：3.20；按需T02/T05/T06/T08与3.09–3.13。实际批准上游只供语义/版本身份，不把数值灌入七个独立SYN',updatedAt:'2026-09-15',revision:'3.21-r2',reviewStatus:'double-reviewed',reviews:[{kind:'accuracy',completedAt:'2026-09-15',decision:'approved',revision:'3.21-r2',summary:'完整同版27机制、八来源与读取边界已核；本人新跑23,259有理oracle、166源/SSR与382纸本保全检查通过，七C和十题30路径无专业阻断。原分子/来源定位问题已闭合；不认证真实因果、PIT、法律或预测。'},{kind:'pedagogy',completedAt:'2026-09-15',decision:'approved',revision:'3.21-r2',summary:'完整同版教学重审通过；本人357源级检查及真实Chrome覆盖键盘、390px、无脚本、七C与十M/K全部路径。旧标题/分页问题已闭合，私人目录即时比较失败保留并真实补验通过；不认证系统读屏或PDF/UA。'}],previous:{slug:'3-20',label:'3.20 Exchange Rate 的宏观基础'},next:{label:'3.22 Business Cycle vs Financial Cycle'},sections:[{id:'thesis',label:'核心命题'},extraSections[0],...capitalFlowConcepts.map(({id,label})=>({id,label})),...extraSections.slice(1)],Content:Lesson321Content,references:lesson321References,readingList:lesson321ReadingList,readingListOrder:'source'};
