import type { LessonReading, LessonReference } from './types';

export const lesson313References: LessonReference[] = [
  { id: 1, authors: 'Andrea Ajello, Michele Cavallo, Giovanni Favara, William B. Peterman, John W. Schindler IV, and Nitish R. Sinha', year: '2023; updated 2026', accessedAt: '2026-09-11', title: 'A New Index to Measure U.S. Financial Conditions', publication: 'Federal Reserve Board, FEDS Notes; DOI 10.17016/2380-7172.3281', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/a-new-index-to-measure-us-financial-conditions-20230630.html', use: '【官方方法与动态数据入口】支持FCI-G的七变量、三个月变化、动态乘数、1年/3年回看、逐项贡献以及正值为未来一年增长逆风的单位；不支持把观察到且可能内生的金融变量变化当作政策冲击或因果效应，且原文明示遗漏贷款标准与条款。' },
  { id: 2, authors: 'Board of Governors of the Federal Reserve System', year: 'living research dataset', accessedAt: '2026-09-11', title: 'FCG-I Index Quarterly and Monthly Data Definitions', publication: 'Federal Reserve Economic Research Data; the separate baseline monthly CSV is linked in the on-page data passport', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/fcg-i_data_definitions_508-3281.pdf', use: '【官方数据定义】支持日期、总指数与七个贡献分项的字段和mnemonic、1年/3年lookback口径，以及该指标是研究产品、不是官方统计发布、可能延迟/修订/改变方法/停更且仅供信息使用的声明；不支持利率、股票、房价或美元的具体原始变量变换，这些变换仅由Source 1的Technical Appendix支持。定义文件标题保留FCG-I旧名，而现行页面与CSV使用FCI-G，本页显式保留这一版本边界。' },
  { id: 3, authors: 'Federal Reserve Bank of Chicago', year: 'living methodology', accessedAt: '2026-09-11', title: 'National Financial Conditions Index: About and Frequently Asked Questions', publication: 'Chicago Fed official NFCI documentation', url: 'https://www.chicagofed.org/research/data/nfci/about', use: '【官方方法】支持NFCI/ANFCI的105项price、quantity与survey指标、标准化、正值更紧以及统计因子聚合；不支持把零点称为政策中性、把组件z加权和天然称为综合指数一个标准差，或把统计loading解释为因果重要性。' },
  { id: 4, authors: 'Federal Reserve Bank of Chicago', year: 'living weekly release', accessedAt: '2026-09-11', title: 'National Financial Conditions Index: Current Data', publication: 'Chicago Fed official weekly release', url: 'https://www.chicagofed.org/research/data/nfci/current-data', use: '【官方动态数据】支持每周三发布前一周五读数、NFCI/ANFCI分项以及新数据、修订和重新估权会改变历史值；不支持把current-vintage history冒充历史当时可见数据，伪实时研究必须另建vintage。' },
  { id: 5, authors: 'Scott A. Brave and R. Andrew Butters', year: '2011', accessedAt: '2026-09-11', title: 'Monitoring Financial Stability: A Financial Conditions Index Approach', publication: 'Federal Reserve Bank of Chicago, Economic Perspectives 35(1), 22–43', url: 'https://www.chicagofed.org/publications/economic-perspectives/2011/1q-brave-butters', use: '【经典方法】支持用大型非平衡金融面板的共同变动和动态重要性构造金融条件，并区分金融与宏观状态；不支持用2011年成分、指标数或估计权重替代现行NFCI，也不支持把共同因子当作结构冲击。' },
  { id: 6, authors: 'Scott A. Brave and R. Andrew Butters', year: '2012', accessedAt: '2026-09-11', title: 'Diagnosing the Financial System: Financial Conditions and Financial Stress', publication: 'International Journal of Central Banking 8(2), 191–239', url: 'https://www.ijcb.org/journal/v8n2/diagnosing-financial-system-financial-conditions-and-financial-stress', use: '【状态边界】支持区分广义金融条件、危机压力与较慢累积的杠杆脆弱性；不支持用一个总指数直接诊断危机成因、把低压力等同低脆弱性或把普通条件变化称为系统失灵。' },
  { id: 7, authors: 'International Monetary Fund', year: '1997', accessedAt: '2026-09-11', title: 'Monetary Conditions Indices: A Reexamination', publication: 'Monetary Policy in the Nordic Countries, IMF', url: 'https://www.elibrary.imf.org/display/book/9781557756961/ch011.xml', use: '【政策边界】支持把条件指数视为信息指标并讨论其构造假设；不支持把指数当作货币政策立场、操作工具或目标，也不支持从指数与政策利率的相关关系识别政策冲击。' },
  { id: 8, authors: 'Jan Hatzius, Peter Hooper, Frederic S. Mishkin, Kermit L. Schoenholtz, and Mark W. Watson', year: '2010', accessedAt: '2026-09-11', title: 'Financial Conditions Indexes: A Fresh Look after the Financial Crisis', publication: 'NBER Working Paper 16150; U.S. Monetary Policy Forum Proceedings, 3–59', url: 'https://www.nber.org/papers/w16150', use: '【综合基准】支持广义FCI同时纳入价格、数量与调查证据、处理非平衡面板并控制过去GDP和通胀；不支持把FCI解释成结构性金融冲击，作者还明确提醒变量选择部分受危机事后观察影响。' },
  { id: 9, authors: 'Troy Matheson', year: '2011', accessedAt: '2026-09-11', title: 'Financial Conditions Indexes for the United States and Euro Area', publication: 'IMF Working Paper 11/93', url: 'https://www.imf.org/external/pubs/ft/wp/2011/wp1193.pdf', use: '【混频与实时方法】支持大型动态因子、标准化、缺失/发布日期处理、预测比较及历史修订分析；不支持完整样本估计冒充伪实时表现，也不支持把统计因子的权重解释成经济乘数。' },
  { id: 10, authors: 'Simon Gilchrist and Egon Zakrajšek', year: '2012', accessedAt: '2026-09-11', title: 'Credit Spreads and Business Cycle Fluctuations', publication: 'American Economic Review 102(4), 1692–1720', url: 'https://pubs.aeaweb.org/doi/10.1257/aer.102.4.1692', use: '【信用分解】支持把观察公司债利差分为模型按预期违约风险与债券特征预测的部分和excess bond premium，并研究EBP的预测信息；不支持把预测部分缩成纯预期损失，也不支持把原始利差、EBP或总收益率自动称为纯信用供给冲击，或将总收益率与其benchmark、spread重复计入。' },
  { id: 11, authors: 'Tobias Adrian, Nina Boyarchenko, and Domenico Giannone', year: '2019', accessedAt: '2026-09-11', title: 'Vulnerable Growth', publication: 'American Economic Review 109(4), 1263–1289', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.20161923', use: '【增长分布】支持金融条件与未来GDP增长条件分布尤其下尾之间的预测关系，以及均值与下行风险可能不同；不支持把预测系数自动解释为对FCI干预的结构因果效应。' },
  { id: 12, authors: 'Bank for International Settlements', year: '2025', accessedAt: '2026-09-11', title: 'Financial Conditions in a Changing Global Financial System', publication: 'BIS Annual Economic Report 2025, Chapter II', url: 'https://www.bis.org/publications/aer-2025/financial-conditions-changing-global-financial-system', use: '【系统与全球边界】支持安全收益与风险因子分栏、NBFI、主权债和FX swap对现代金融条件传导的重要性及组件可能背离；不支持把两因子框架当成唯一官方FCI、跨主体统一状态或时不变结构。' },
  { id: 13, authors: 'Bank for International Settlements', year: '2025', accessedAt: '2026-09-11', title: 'Financial Conditions and the Macroeconomy: A Two-Factor View', publication: 'BIS Working Paper 1272', url: 'https://www.bis.org/publications/working-paper-1272-financial-conditions-and-macroeconomy-two-factor-view', use: '【两因子证据】支持在声明样本中用安全收益率因子与风险因子解释大部分金融变量共同方差并比较宏观联系；不支持把样本方差解释率外推为因果贡献、普适权重或单一主体融资条件。' },
  { id: 14, authors: 'Iñaki Aldasoro, Stefan Avdjiev, Claudio Borio, and Piti Disyatat', year: '2020', accessedAt: '2026-09-11', title: 'Global and Domestic Financial Cycles: Variations on a Theme', publication: 'BIS Working Paper 864', url: 'https://www.bis.org/publications/working-paper-864-global-and-domestic-financial-cycles-variations-theme', use: '【多尺度周期】支持全球周期更集中于资产价格/资本流动且较短，国内周期更集中于信用/房地产且更长；不支持把本地FCI、全球金融周期与国内信用周期互换，或给美元项全球统一符号。' },
  { id: 15, authors: 'International Monetary Fund', year: '2017', accessedAt: '2026-09-11', title: 'A Financial Conditions Index for France', publication: 'IMF Working Paper 17/269', url: 'https://www.elibrary.imf.org/view/journals/001/2017/269/article-A001-en.xml', use: '【国家构造案例】支持按经济类别组织组件、避免冗余并用预测符号筛选候选指标；不支持把法国样本权重移植到其他法域，也不支持以事后预测表现掩盖实时数据问题。' },
  { id: 16, authors: 'Dario Caldara and Edward Herbst', year: '2019', accessedAt: '2026-09-11', title: 'Monetary Policy, Real Activity, and Credit Spreads: Evidence from Bayesian Proxy SVARs', publication: 'American Economic Journal: Macroeconomics 11(1), 157–192', url: 'https://www.federalreserve.gov/econres/feds/monetary-policy-real-activity-and-credit-spreads-evidence-from-bayesian-proxy-svars.htm', use: '【内生政策反应】支持央行会内生回应信用利差且忽略这种反应会扭曲货币冲击估计；不支持把所有FCI变化归因于货币政策，也不支持由预测先行性推出因果。' },
  { id: 17, authors: 'Board of Governors of the Federal Reserve System', year: 'living quarterly survey', accessedAt: '2026-09-11', title: 'Senior Loan Officer Opinion Survey on Bank Lending Practices', publication: 'Federal Reserve official SLOOS', url: 'https://www.federalreserve.gov/data/sloos.htm', use: '【官方调查】支持区分standards、terms与demand，以及净比例的题目、银行类别和回顾窗口；不支持把净收紧比例当作贷款金额、条件强度、单笔批准概率或已识别信用供给冲击。' },
  { id: 18, authors: 'David Glancy, Robert Kurtzman, and Rebecca Zarutskie', year: '2020', accessedAt: '2026-09-11', title: 'An Aggregate View of Bank Lending Standards and Demand', publication: 'Federal Reserve Board, FEDS Notes', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/an-aggregate-view-of-bank-lending-standards-and-demand-20200504.html', use: '【调查聚合】支持跨银行和贷款种类聚合并说明贷款余额权重的经济含义；不支持认为等银行、余额或申请权重回答同一总体，也不支持用总体净比例替代借款人分布。' },
  { id: 19, authors: 'Federal Reserve Bank of St. Louis', year: 'living documentation', accessedAt: '2026-09-11', title: 'ALFRED, Real-Time Periods, and Series Vintage Dates', publication: 'FRED/ALFRED official API documentation', url: 'https://fred.stlouisfed.org/docs/api/fred/alfred.html', use: '【实时数据规则】支持区分observation date、realtime period与vintage dates，重建某时点可见数据；不支持假定每条FRED序列都保存完整历史vintage，逐系列仍需核验发布时间、修订和可用性。' },
  { id: 20, authors: 'Dániel Holló, Manfred Kremer, and Marco Lo Duca', year: '2012', accessedAt: '2026-09-11', title: 'CISS—A Composite Indicator of Systemic Stress in the Financial System', publication: 'ECB Working Paper 1426', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1426.pdf', use: '【压力边界】支持五个市场板块和时变交叉相关共同刻画压力的系统性共振，以及CISS位于0到1标度、0是极低压力下界而非历史平均零点；不支持度量全部融资成本、信用数量或增长冲量，也不支持以CISS替代普通时期的广义FCI。' },
  { id: 21, authors: 'William F. Bassett, Mary Beth Chosak, John C. Driscoll, and Egon Zakrajšek', year: '2014', accessedAt: '2026-09-11', title: 'Changes in Bank Lending Standards and the Macroeconomy', publication: 'Journal of Monetary Economics 62, 23–40', url: 'https://www.federalreserve.gov/pubs/feds/2012/201224/201224pap.pdf', use: '【信用供给识别】支持用银行级数据控制宏观和银行特征后构造贷款供给指标；不支持把未经调整的SLOOS aggregate net tightening直接称为供给冲击，也不支持用条件于获批者的报价覆盖拒贷。' },
  { id: 22, authors: 'Michele Cavallo, Juan Morelli, Rebecca Zarutskie, and Solveig Baylor', year: '2024', accessedAt: '2026-09-11', title: 'Measuring Bank Credit Supply Shocks Using the Senior Loan Officer Survey', publication: 'Federal Reserve Board, FEDS Notes', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/measuring-bank-credit-supply-shocks-using-the-senior-loan-officer-survey-20240524.html', use: '【调查创新】支持按贷款种类区分持续标准状态与新的信用供给创新；不支持将估计的CSI与原始SLOOS水平、全部银行信贷供给或政策冲击完全等同。' },
  { id: 23, authors: 'Michele Cavallo, Juan Morelli, and Rebecca Zarutskie', year: '2024', accessedAt: '2026-09-11', title: 'Unpacking the Effects of Bank Credit Supply Shocks on Economic Activity', publication: 'Federal Reserve Board, FEDS Notes', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/unpacking-the-effects-of-Bank-credit-supply-shocks-on-economic-activity-20240524.html', use: '【互补渠道】支持把FCI-G市场价格渠道与银行信用供给渠道并列分析、说明二者互补；不支持把两者未经重叠审计直接相加成一个无重复的结构指数。' },
  { id: 24, authors: 'Andrew J. Swiston', year: '2008', accessedAt: '2026-09-11', title: 'A U.S. Financial Conditions Index: Putting Credit Where Credit Is Due', publication: 'IMF Working Paper 08/161', url: 'https://www.imf.org/external/pubs/ft/wp/2008/wp08161.pdf', use: '【信用可得性】支持在VAR/IRF中纳入贷款标准、公司债收益率、股票与实际汇率，并显示标准提供价格之外信息；不支持把估计参数称为deep structural parameters或当前固定权重。' },
  { id: 25, authors: 'Stéphanie Guichard and David Turner', year: '2008', accessedAt: '2026-09-11', title: 'Quantifying the Effect of Financial Conditions on US Activity', publication: 'OECD Economics Department Working Paper 635', url: 'https://www.oecd.org/en/publications/quantifying-the-effect-of-financial-conditions-on-us-activity_236860073636.html', use: '【增长权重案例】支持把高收益利差和贷款标准加入传统利率、汇率与资产价格并映射至增长；不支持将2008年样本估计当作当前实时OECD指数或不变结构。' },
  { id: 26, authors: 'E. Philip Davis, Simon Kirby, and James Warren', year: '2016', accessedAt: '2026-09-11', title: 'The Estimation of Financial Conditions Indices for the Major OECD Countries', publication: 'OECD Economics Department Working Paper 1335', url: 'https://www.oecd.org/en/publications/the-estimation-of-financial-conditions-indices-for-the-major-oecd-countries_5jlnb5b1zw9x-en.html', use: '【方法比较】支持比较IS、VAR、NiGEM与factor/PCA四类权重并展示危机加入后的符号和显著性不稳定；不支持存在跨国跨制度唯一且固定的最佳FCI。' },
  { id: 27, authors: 'Céline Gauthier, Christopher Graham, and Ying Liu', year: '2004', accessedAt: '2026-09-11', title: 'Financial Conditions Indexes for Canada', publication: 'Bank of Canada Staff Working Paper 2004-22', url: 'https://www.bankofcanada.ca/2004/06/working-paper-2004-22/', use: '【多方法案例】支持比较IS方程、广义脉冲响应与因子分析三种构造方式；不支持把加拿大某一方法权重移植到美国、其他主体或其他时期。' },
  { id: 28, authors: 'Gary Koop and Dimitris Korobilis', year: '2014', accessedAt: '2026-09-11', title: 'A New Index of Financial Conditions', publication: 'European Economic Review 71, 101–116', url: 'https://strathprints.strath.ac.uk/55408/', use: '【时变权重】支持TVP-FAVAR、随机波动及动态模型平均/选择，让变量与权重随时间变化；不支持把事后估计路径当作官方实时指数或稳定结构。' },
  { id: 29, authors: 'Goldman Sachs Global Investment Research', year: '2017', accessedAt: '2026-09-11', title: 'Our New G10 Financial Conditions Indices', publication: 'Global Economics Analyst, 20 April 2017', url: 'https://www.gspublishing.com/content/research/en/reports/2017/04/20/c10f888f-4faa-4ffc-b4c2-518cf5ffffe3.pdf', use: '【商业指数方法】支持G10增长映射型FCI常用的政策率、长端安全收益率、公司利差、股票与贸易加权汇率结构；不支持免费复现当前Goldman指数、假定其历史可公开获得或把商业数据当本页事实输入。' },
  { id: 30, authors: 'Sirio Aramonte, Samuel Rosen, and John W. Schindler', year: '2013', accessedAt: '2026-09-11', title: 'Assessing and Combining Financial Conditions Indexes', publication: 'Federal Reserve Board FEDS 2013-39', url: 'https://www.federalreserve.gov/econres/feds/assessing-and-combining-financial-conditions-indexes.htm', use: '【模型比较与反例】支持不同FCI在变量、方法和样本外预测上的巨大异质性，且许多结果离开2008危机后不稳健；不支持基于样本内相关性盲目平均多个指数。' },
  { id: 31, authors: 'James H. Stock and Mark W. Watson', year: '2002', accessedAt: '2026-09-11', title: 'Forecasting Using Principal Components from a Large Number of Predictors', publication: 'Journal of the American Statistical Association 97(460), 1167–1179', url: 'https://www.princeton.edu/~mwatson/papers/Stock_Watson_JASA_2002.pdf', use: '【PCA基础】支持用主成分压缩高维预测变量的共同变动；不支持赋予loading天然经济方向、宏观影响或因果含义，也不支持跳过伪实时样本外评估。' },
  { id: 32, authors: 'Catherine Doz, Domenico Giannone, and Lucrezia Reichlin', year: '2012', accessedAt: '2026-09-11', title: 'A Quasi-Maximum Likelihood Approach for Large, Approximate Dynamic Factor Models', publication: 'Review of Economics and Statistics 94(4), 1014–1024; ECB WP 674', url: 'https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp674.pdf', use: '【动态因子】支持用Kalman smoother、EM和大型近似DFM处理共同因子及非平衡数据；不支持由统计因子自动得到“金融松紧”的经济方向或政策冲击身份。' },
  { id: 33, authors: 'S. Borağan Aruoba, Francis X. Diebold, and Chiara Scotti', year: '2009', accessedAt: '2026-09-11', title: 'Real-Time Measurement of Business Conditions', publication: 'Journal of Business & Economic Statistics 27(4), 417–427', url: 'https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/ads', use: '【ragged edge方法】支持把不同频率、流量/存量变量和不规则发布日期纳入实时潜在因子；不支持把实际活动ADS指数直接用作FCI或金融冲击证据。' },
  { id: 34, authors: 'Michael W. McCracken and Serena Ng', year: '2016', accessedAt: '2026-09-11', title: 'FRED-MD: A Monthly Database for Macroeconomic Research', publication: 'Journal of Business & Economic Statistics 34(4), 574–589', url: 'https://doi.org/10.1080/07350015.2015.1086655', use: '【可复现数据工程】支持公开面板、变换码、数据冻结与可复现宏观研究规范；不支持把FRED-MD称为NFCI底层库或历史实时vintage。' },
  { id: 35, authors: 'Mark A. Carlson, Kurt F. Lewis, and William R. Nelson', year: '2012', accessedAt: '2026-09-11', title: 'Using Policy Intervention to Identify Financial Stress', publication: 'Federal Reserve Board FEDS 2012-02', url: 'https://www.federalreserve.gov/econres/feds/using-policy-intervention-to-identify-financial-stress.htm', use: '【压力识别】支持用市场水平、波动和共同运动测量市场功能压力；不支持把stress index当作广义融资可得性、GDP冲量或完全外生政策标签。' },
  { id: 36, authors: 'Federal Reserve Bank of St. Louis', year: 'living weekly series', accessedAt: '2026-09-11', title: 'St. Louis Fed Financial Stress Index (STLFSI4)', publication: 'FRED official series and release notes', url: 'https://fred.stlouisfed.org/series/STLFSI4', use: '【官方压力指数】支持以18个周频市场序列构造STLFSI4，并把零定义为历史平均压力、正负分别表示高于或低于历史平均；不支持覆盖完整融资数量、银行贷款标准、主体融资菜单或结构性金融冲击。' },
  { id: 37, authors: 'Phillip Monin', year: '2017', accessedAt: '2026-09-11', title: 'The OFR Financial Stress Index', publication: 'Office of Financial Research Working Paper 17-04', url: 'https://www.financialresearch.gov/working-papers/2017/10/25/the-ofr-financial-stability-index/', use: '【日频压力与贡献】支持33个市场变量、日频压力以及地区/类别贡献；不支持把压力等同脆弱性或广义条件，且LIBOR替换等版本变化要求保存方法日期。' },
  { id: 38, authors: 'Andrea Ajello, Giovanni Favara, Gregory Marchal, and Balint Szoke', year: '2024', accessedAt: '2026-09-11', title: 'Financial Conditions and Risks to the Economic Outlook', publication: 'Federal Reserve Board, FEDS Notes', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/financial-conditions-and-risks-to-the-economic-outlook-20240920.html', use: '【分布预测应用】支持把FCI-G映射到GDP、就业和通胀的预测分布并讨论尾部；不支持将结果当作政策目标、结构压力测试或精确尾部概率，作者还提示有效样本较小。' },
  { id: 39, authors: 'International Monetary Fund, Monetary and Capital Markets Department', year: '2017', accessedAt: '2026-09-11', title: 'Are Countries Losing Control of Domestic Financial Conditions?', publication: 'Global Financial Stability Report, April 2017, Chapter 3', url: 'https://www.imf.org/-/media/files/publications/gfsr/2017/april/ch3.pdf', use: '【跨国金融条件】支持价格与非价格融资成本、跨国可比FCI、宏观调整及全球共同因子；不支持把调整残差称为完全外生冲击，或把样本全球份额固定套用于任一国家时期。' },
  { id: 40, authors: 'International Monetary Fund, Monetary and Capital Markets Department', year: '2017', accessedAt: '2026-09-11', title: 'Financial Conditions and Growth at Risk', publication: 'Global Financial Stability Report, October 2017, Chapter 3, 91–118', url: 'https://www.elibrary.imf.org/display/book/9781484308394/ch003.xml', use: '【期限与下尾】支持短期价格/波动与较长期信用/杠杆的期限分工、条件增长分布和国家异质性；不支持一般性因果结论，也不支持假定retrospective real-time练习的所有输入均有完整vintage。' },
  { id: 41, authors: 'Tobias Adrian, Federico Grinberg, Nellie Liang, Sheheryar Malik, and Jie Yu', year: '2018', accessedAt: '2026-09-11', title: 'The Term Structure of Growth-at-Risk', publication: 'IMF Working Paper 18/180', url: 'https://www.imf.org/-/media/files/publications/wp/2018/wp18180.pdf', use: '【GaR期限结构】支持FCI对增长分布下尾与中位数的不同关系、短期收益/中期风险以及特定granular IV检验；不支持把任意FCI—GDP相关性解释成因果或把教学系数当现实估计。' },
  { id: 42, authors: 'Nicolas Arregui, Selim Elekdag, Gaston Gelos, Romain Lafarguette, and Dulani Seneviratne', year: '2018', accessedAt: '2026-09-11', title: 'Can Countries Manage Their Financial Conditions Amid Globalization?', publication: 'IMF Working Paper 18/15', url: 'https://www.imf.org/-/media/files/publications/wp/2018/wp1815.pdf', use: '【全球与国内分解】支持全球共同成分、国内政策仍有作用以及显著国家异质性；不支持“浮动汇率完全隔离”或“全球因素决定绝大部分条件”的无条件结论。' },
  { id: 43, authors: 'Hélène Rey', year: '2013', accessedAt: '2026-09-11', title: 'Dilemma not Trilemma: The Global Financial Cycle and Monetary Policy Independence', publication: 'Jackson Hole Symposium Proceedings, 285–333', url: 'https://www.kansascityfed.org/documents/4575/2013Rey.pdf', use: '【全球周期起点】支持全球风险资产、资本流动和中介杠杆共同成分及其与VIX、中心国条件的联系；不支持把VIX本身、美元或某国FCI等同完整全球金融周期。' },
  { id: 44, authors: 'Silvia Miranda-Agrippino and Hélène Rey', year: '2020', accessedAt: '2026-09-11', title: 'U.S. Monetary Policy and the Global Financial Cycle', publication: 'Review of Economic Studies 87(6), 2754–2776; NBER WP 21722', url: 'https://www.nber.org/papers/w21722', use: '【全球冲击识别】支持已识别美国货币冲击后的全球资产价格、杠杆、国内与跨境信用收缩；不支持认为所有全球金融共同波动都由美联储造成。' },
  { id: 45, authors: 'Eugenio M. Cerutti, Stijn Claessens, and Andrew K. Rose', year: '2017', accessedAt: '2026-09-11', title: 'How Important Is the Global Financial Cycle? Evidence from Capital Flows', publication: 'BIS Working Paper 661', url: 'https://www.bis.org/publications/working-paper-661-how-important-global-financial-cycle-evidence-capital-flows', use: '【全球因子反证】支持在其资本流动样本和方法中全球因子通常解释有限份额；不支持据此否认全球周期对资产价格、国内信用或特定国家的重要性。' },
  { id: 46, authors: 'Stefan Avdjiev, Valentina Bruno, Catherine Koch, and Hyun Song Shin', year: '2018', accessedAt: '2026-09-11', title: 'The Dollar Exchange Rate as a Global Risk Factor: Evidence from Investment', publication: 'BIS Working Paper 695', url: 'https://www.bis.org/publications/working-paper-695-dollar-exchange-rate-global-risk-factor-evidence-investment', use: '【美元资产负债表】支持强美元与跨境美元信用、EME投资走弱的金融渠道；不支持对每个国家机械赋予美元统一符号或因果幅度，效应依赖外币债务、收入与对冲。' },
  { id: 47, authors: 'Burcu Erik, Marco J. Lombardi, Dubravko Mihaljek, and Hyun Song Shin', year: '2020', accessedAt: '2026-09-11', title: 'The Dollar, Bank Leverage and Real Economic Activity: An Evolving Relationship', publication: 'BIS Working Paper 847', url: 'https://www.bis.org/publications/working-paper-847-dollar-bank-leverage-and-real-economic-activity-evolving-relationship', use: '【关系漂移】支持危机后美元与全球活动联系增强、VIX解释力相对变化；不支持使用一个跨时期固定代理或固定美元权重。' },
  { id: 48, authors: 'Bank for International Settlements', year: '2026', accessedAt: '2026-09-11', title: 'BIS Global Liquidity Indicators: Methodology', publication: 'BIS official methodology, January 2026', url: 'https://www.bis.org/statistics/gli/gli_methodology.pdf', use: '【官方全球信用数量】支持按季度追踪非银行借款人的银行贷款和国际债券融资、主要外币及汇率/断点调整；不支持把信用存量称作同期市场松紧、融资可得性或外生供给。' },
  { id: 49, authors: 'Thiago R. T. Ferreira', year: '2022', accessedAt: '2026-09-11', title: 'Cross-Sectional Financial Conditions, Business Cycles and the Lending Channel', publication: 'Federal Reserve Board IFDP 1335', url: 'https://www.federalreserve.gov/econres/ifdp/cross-sectional-financial-conditions-business-cycles-and-the-lending-channel.htm', use: '【横截面分布】支持股票回报与信用利差分布的偏度、尾部及中介横截面状态包含均值遗漏的信息；不支持把某一横截面因子当作现成广义FCI或家庭融资条件。' },
  { id: 50, authors: 'Thiago R. T. Ferreira, Daniel A. Ostry, and John Rogers', year: '2023', accessedAt: '2026-09-11', title: 'Firm Financial Conditions and the Transmission of Monetary Policy', publication: 'Federal Reserve Board FEDS 2023-037', url: 'https://www.federalreserve.gov/econres/feds/firm-financial-conditions-and-the-transmission-of-monetary-policy.htm', use: '【企业异质性】支持企业EBP分布影响货币政策对利差与投资的异质传导；不支持由aggregate FCI推断代表性企业或所有企业同质响应。' },
];

export const lesson313ReadingList: LessonReading[] = [
  {
    title: '构造起点：广义金融条件为何必须包含价格、数量与调查',
    scope: 'Hatzius et al. (2010), pp. 3–59',
    reason: '建立“FCI是用途特定测量模型”的总框架，并理解危机后为什么只看市场价格会遗漏信贷可得性。',
    url: lesson313References[7].url,
    group: 'core',
    guide: '逐项标记组件角色、分母和是否在当时可见；特别阅读作者对危机后事后变量选择的限制。本文不授予结构冲击身份。',
    links: [{ label: 'NBER paper', url: lesson313References[7].url }, { label: 'Chicago NFCI', url: lesson313References[2].url }],
  },
  {
    title: '状态型指数：NFCI、ANFCI、标准化与修订',
    scope: 'Brave & Butters (2011), pp. 22–43；Chicago Fed About / FAQ / Current Data',
    reason: '理解动态因子如何在非平衡面板中提取共同状态，以及为什么零点只是相对历史基准。',
    url: lesson313References[4].url,
    group: 'models',
    guide: '分别记录现行105项、组件方向、历史修订和ANFCI宏观调整；不要把ANFCI称为因果净化后的金融冲击。',
    links: [{ label: 'Method paper', url: lesson313References[4].url }, { label: 'Current documentation', url: lesson313References[3].url }],
  },
  {
    title: '增长冲量型指数：FCI-G从三个月变化到未来一年增长逆风',
    scope: 'Ajello et al. (2023), main text, equations A.1–A.5, Table 1 and Data Appendix',
    reason: '学会把动态乘数、滞后和逐项贡献与普通历史状态z-score彻底分开。',
    url: lesson313References[0].url,
    group: 'models',
    guide: '复算一项变量的三个月变化与滞后贡献；同时抄下作者关于内生性和遗漏贷款条款的两条限制。',
    links: [{ label: 'FEDS Note', url: lesson313References[0].url }, { label: 'Data definitions', url: lesson313References[1].url }],
  },
  {
    title: '权重没有唯一答案：四类方法与危机样本的不稳定性',
    scope: 'Davis, Kirby & Warren (2016), pp. 5–23；Aramonte et al. (2013)',
    reason: '比较IS、VAR、NiGEM、PCA与指数组合，理解预测优胜与经济含义不是同一标准。',
    url: lesson313References[25].url,
    group: 'models',
    guide: '把每种方法的target、训练窗、符号和out-of-sample要求列成护照；不要把危机期拟合优势当成稳定规律。',
    links: [{ label: 'OECD comparison', url: lesson313References[25].url }, { label: 'Fed comparison', url: lesson313References[29].url }],
  },
  {
    title: '信用价格的内部结构：spread、预期违约与excess bond premium',
    scope: 'Gilchrist & Zakrajšek (2012), pp. 1692–1720',
    reason: '理解一条公司债利差为何同时含借款人基本面与中介风险价格，避免把它当纯供给冲击。',
    url: lesson313References[9].url,
    group: 'evidence',
    guide: '画出总收益率=匹配benchmark+spread，以及spread=模型按预期违约风险与债券特征预测的部分+EBP两层账本；同一层只能选总项或分解项。',
    links: [{ label: 'AER article', url: lesson313References[9].url }, { label: 'EBP data note', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/updating-the-recession-risk-and-the-excess-bond-premium-20161006.html' }],
  },
  {
    title: '价格以外的可得性：贷款标准、条款、需求与供给创新',
    scope: 'Fed SLOOS methodology；Bassett et al. (2014)；Cavallo et al. (2024)',
    reason: '学会读取net tightening的方向广度，并理解从调查状态到供给冲击还需要什么识别。',
    url: lesson313References[16].url,
    group: 'evidence',
    guide: '固定question、银行/贷款类别、有效分母、回顾窗和发布日期；净比例不是金额或强度，CSI也不等于原始水平。',
    links: [{ label: 'SLOOS', url: lesson313References[16].url }, { label: 'Macro evidence', url: lesson313References[20].url }, { label: 'Supply innovations', url: lesson313References[21].url }],
  },
  {
    title: '实时数据训练：observation、release、revision与模型vintage',
    scope: 'ALFRED documentation；Matheson (2011)；FRED-MD transformation and freeze rules',
    reason: '建立伪实时FCI的数据工程纪律，避免用未来均值、SD、相关矩阵或loading改写过去。',
    url: lesson313References[18].url,
    group: 'rules',
    guide: '任选一个组件重建as-of数据；核验该系列是否真的有完整vintage，而不是把最新修订历史改名为实时。',
    links: [{ label: 'ALFRED', url: lesson313References[18].url }, { label: 'DFM FCI', url: lesson313References[8].url }, { label: 'FRED-MD', url: lesson313References[33].url }],
  },
  {
    title: '金融条件不是金融压力：普通收紧、系统共振与脆弱性',
    scope: 'Brave & Butters (2012)；Holló et al. (2012)；STLFSI4官方说明；Monin (2017)',
    reason: '区分广义融资环境、尾部市场失灵与慢变量脆弱性，避免在低压力时误判风险已消失。',
    url: lesson313References[5].url,
    group: 'systems',
    guide: '比较各指数的组件、相关结构和零点；CISS的0是0–1标度下界，STLFSI4的0是历史平均，二者不可共用零点解释，也都不能替代融资价格与数量向量。',
    links: [{ label: 'Conditions vs stress', url: lesson313References[5].url }, { label: 'CISS', url: lesson313References[19].url }, { label: 'STLFSI4', url: lesson313References[35].url }, { label: 'OFR FSI', url: lesson313References[36].url }],
  },
  {
    title: '从均值到下尾：Growth-at-Risk的预测对象与期限结构',
    scope: 'IMF GFSR October 2017, Chapter 3, pp. 91–118；Adrian et al. (2018), pp. 10–39',
    reason: '理解同一金融条件为何对未来增长中位数和下尾、短期和中期可能含义不同。',
    url: lesson313References[39].url,
    group: 'systems',
    guide: '先写清quantile、horizon、as-of信息与benchmark，再看系数；相关预测不自动成为干预FCI的因果效应。',
    links: [{ label: 'IMF GFSR', url: lesson313References[39].url }, { label: 'Term structure of GaR', url: lesson313References[40].url }, { label: 'Vulnerable Growth', url: lesson313References[10].url }],
  },
  {
    title: '横截面与全球接口：代表性FCI为何会遗漏真正绑定者',
    scope: 'Arregui et al. (2018), pp. 7–37；Ferreira, Ostry & Rogers (2023), sections 2–5；BIS AER 2025 chapter II',
    reason: '把国家共同因子、企业条件分布、美元暴露和不同融资渠道接到4.07与Chapter 7。',
    url: lesson313References[41].url,
    group: 'systems',
    guide: '同时保存global/local decomposition、企业分位数、币种/对冲和融资渠道；aggregate平均不能替代主体暴露。',
    links: [{ label: 'Globalization', url: lesson313References[41].url }, { label: 'Firm distribution', url: lesson313References[49].url }, { label: 'BIS 2025', url: lesson313References[11].url }],
  },
];
