import type { LessonReading, LessonReference } from './types';

export const lesson316References: LessonReference[] = [
  { id: 1, authors: 'Matteo Iacoviello', year: '2005', accessedAt: '2026-09-15', title: 'House Prices, Borrowing Constraints, and Monetary Policy in the Business Cycle', publication: 'American Economic Review 95(3):739–764. DOI:10.1257/0002828054201477；作者托管期刊final PDF；重点核读引言、§II–V。', url: 'https://www.aeaweb.org/articles?id=10.1257/0002828054201477', use: '支持：一周期名义抵押债务、预期抵押价值及不耐心借款人构成有条件放大，名义债务使不同冲击方向不同。不支持：现实三十年FRM每期重估追缴、全部冲击都放大、后来美国危机的微观因果归因；未复现模型及附录。' },
  { id: 2, authors: 'Greg Kaplan, Kurt Mitman & Giovanni L. Violante', year: '2020', accessedAt: '2026-09-15', title: 'The Housing Boom and Bust: Model Meets Evidence', publication: 'Journal of Political Economy 128(9):3285–3345. DOI:10.1086/708816；Princeton作者托管排版final；重点§II及§IV–VII，不是2017 NBER工作论文。', url: 'https://www.journals.uchicago.edu/doi/10.1086/708816', use: '支持：长期按揭的存量付款与新发LTV/PTI约束分离；租住、未来住房需要与流动性带来异质响应；多渠道均衡反事实。不支持：模型实质固定利率就是现实名义ARM，残差校准的信念是独立观察冲击、消失的银行资本约束是现实不存在。§II脚注7的HELOC优先于按揭是与数据相反的简化，绝不能作为法律瀑布。' },
  { id: 3, authors: 'Atif Mian, Kamalesh Rao & Amir Sufi', year: '2013', accessedAt: '2026-09-15', title: 'Household Balance Sheets, Consumption, and the Economic Slump', publication: 'The Quarterly Journal of Economics 128(4):1687–1726. DOI:10.1093/qje/qjt020；实际核读June2013作者最终手稿主文及Tables IV–VII。作者稿web可读，原始PDF下载403未留存；未核对出版排版全文等价。', url: 'https://academic.oup.com/qje/article/128/4/1687/1849337', use: '支持：2006–09县级支出、ZIP汽车与借款菜单的异质地理响应；供给弹性IV依赖排除限制，并允许当地非贸易收入反馈。不支持：县级结果等于个人MPC、纯抵押与纯财富独立识别、汽车异质性外推全部消费；高住房杠杆的信用卡限额交互与HELOC IV并非均显著；全国外推不是国家共同冲击的因果识别。' },
  { id: 4, authors: 'Adam M. Guren & Timothy J. McQuade', year: '2020（阅读稿2019-11-19）', accessedAt: '2026-09-15', title: 'How Do Foreclosures Exacerbate Housing Downturns?', publication: 'The Review of Economic Studies 87(3):1331–1364. DOI:10.1093/restud/rdaa001；实际阅读November19,2019 BU作者稿主文1–42 PDF页；未取得出版final全文，不声明版本字节或结果逐项等价。', url: 'https://academic.oup.com/restud/article-abstract/87/3/1331/5700747', use: '支持：该作者稿模型中的双触发违约、搜寻匹配、借款人购房排除与中介资本受损可以组成市场级反馈；延迟止赎与持有已止赎房屋是不同政策。不支持：战略违约不存在、普通负权益立即止赎、反事实分解是回归识别、政策有无条件福利排名。固定存量、危机补股限制、流动性恢复与财政成本假设必须保留。' },
  { id: 5, authors: 'Neil Bhutta, Jane Dokko & Hui Shan', year: '2010', accessedAt: '2026-09-15', title: 'The Depth of Negative Equity and Mortgage Default Decisions', publication: 'Federal Reserve FEDS 2010-35，May2010工作论文；不是后来标题不同的2017 Journal of Finance final。核读样本、违约时间及结论。', url: 'https://www.federalreserve.gov/pubs/feds/2010/201035/index.html', use: '支持：负权益、支付能力与违约成本是不同状态；2006年四州非优质、购入CLTV100%样本追踪至September2009，90+逾期持续两月定义有回溯事件时钟。不支持：样本阈值为今日普适违约线、外推全部国家／优质按揭，或将逾期定义直接等同法院止赎与收回房产。' },
  { id: 6, authors: 'Andra C. Ghent & Marianna Kudlyak', year: '2010 revised working paper', accessedAt: '2026-09-15', title: 'Recourse and Residential Mortgage Default: Theory and Evidence from U.S. States', publication: 'Federal Reserve Bank of Richmond WP09-10R，revised2010-06-10；核读引言与§II.A；后续实证与2011 RFS final未完整核读。', url: 'https://www.richmondfed.org/publications/research/working_papers/2009/wp_09-10r', use: '支持：追索威胁、实际收款成本及终止方式区别于简单法条二元标签。不支持：历史州分类为今日法律建议、所有贷款追索相同、借此定义中国或其他国家追索；不引用未经核读的量化final估计。' },
  { id: 7, authors: 'Consumer Financial Protection Bureau', year: 'current official guide', accessedAt: '2026-09-15', title: 'Understand the different kinds of loans available', publication: '美国消费者金融保护局，固定／可调利率与期限部分。', url: 'https://www.consumerfinance.gov/owning-a-home/explore/understand-the-different-kinds-of-loans-available/', use: '支持：普通固定利率本金利息付款稳定、税险等总账单可变，可调利率按合同改变。不支持：所有国家或特殊产品合同均相同、税险恒定、月付降低即总成本降低；不是本课合成LTV或预算上限的法规依据。' },
  { id: 8, authors: 'Consumer Financial Protection Bureau', year: 'current regulation', accessedAt: '2026-09-15', title: 'Regulation Z §1026.40 Requirements for home equity plans', publication: '美国住房担保open-end credit plans；(f)(2)、(f)(3)(vi)及Supplement I解释。', url: 'https://www.consumerfinance.gov/rules-policy/regulations/1026/40/', use: '支持：特定条件下限制额外授信与终止加速清偿的法律门槛不同；解释中的抵押缓冲下降示例不是普适房价阈值。不支持：把额外HELOC提款冻结写成已提款本金立即追缴、适用于每笔closed-end first mortgage或其他法域；不是个人法律意见。' },
  { id: 9, authors: 'Consumer Financial Protection Bureau', year: 'current official explanation', accessedAt: '2026-09-15', title: 'What is a home equity line of credit (HELOC)?', publication: '美国消费者金融保护局，draw period与repayment period说明。', url: 'https://www.consumerfinance.gov/ask-cfpb/what-is-a-home-equity-line-of-credit-heloc-en-107/', use: '支持：房屋净值信贷额度的提款和还款阶段不同，未提款余额不等于手中现金，合同可含可调利率／期末承诺。不支持：各计划期限相同、市场下跌使原本金自动违约、所有净值可无成本即时提取。' },
  { id: 10, authors: 'Consumer Financial Protection Bureau', year: 'current official explanation', accessedAt: '2026-09-15', title: 'For an adjustable-rate mortgage (ARM), what are the index and margin, and how do they work?', publication: '美国消费者金融保护局，index／margin／caps及调整说明。', url: 'https://www.consumerfinance.gov/ask-cfpb/for-an-adjustable-rate-mortgage-arm-what-are-the-index-and-margin-and-how-do-they-work-en-1949/', use: '支持：参考指数、固定加点、重置日期与cap共同决定ARM变化。不支持：新市场报价即重置全部存量FRM、无cap教学公式为真实ARM报价，或未来沿用比较日的本金和剩余期数。' },
  { id: 11, authors: 'Edward L. Glaeser & Joseph Gyourko', year: '2018', accessedAt: '2026-09-15', title: 'The Economic Implications of Housing Supply', publication: 'Journal of Economic Perspectives 32(1):3–30. DOI:10.1257/jep.32.1.3；实际核读官方整期PDF的期刊页3–8及p8脚注3，未声称全文核读。', url: 'https://www.aeaweb.org/articles?id=10.1257/jep.32.1.3', use: '支持：住房供给的地理、规则差异与耐久存量使需求冲击的价格／数量吸收不对称。不支持：每个价格成本差均为已识别监管税、任意地理变量总能作有效工具，或固定存量模型给出现实新建弹性。' },
  { id: 12, authors: 'Federal Housing Finance Agency', year: '2026-09-15 retrieval', accessedAt: '2026-09-15', title: 'FHFA HPI® purchase-only quarterly US and census division dataset', publication: '官方TXT；division=USA，第5列index_po_seasonally_adjusted；季度／名义／SA／1991Q1=100，当前历史快照。', url: 'https://www.fhfa.gov/hpi/download/quarterly_datasets/hpi_po_us_and_census.txt', use: '支持：已保留原始字节的116个展示季度及事后窗口峰谷复算。不支持：单套房评估值、全部现金／非合规／FHA等交易代表性、租金、家庭LTV或因果反馈；最新原始文件至2026Q2但展示固定至2019Q4，活端点可能修订。' },
  { id: 13, authors: 'Federal Housing Finance Agency', year: 'November2025 FAQ', accessedAt: '2026-09-15', title: 'FHFA HPI Frequently Asked Questions', publication: '12页官方方法FAQ，重点覆盖、季度／月度、修订、时间与§32使用归属；保留研究参考PDF。', url: 'https://www.fhfa.gov/document/hpi-faqs', use: '支持：重复销售指数、名义量纲、purchase-only覆盖和数据修订，公开指数归属。不支持：当季交易时间等于当时发布日期／接收时点、月度平均等于季度回归，或今天修订序列是历史PIT；不提供机密逐笔数据再分发授权。' },
  { id: 14, authors: 'Federal Housing Finance Agency', year: '2026-08-25', accessedAt: '2026-09-15', title: 'U.S. House Price Index Report — 2026 Q2', publication: '官方2026Q2报告及发布日期身份；不是此课历史展示的收取时钟。', url: 'https://www.fhfa.gov/reports/house-price-index/2026/Q2', use: '支持：本次原始文件最新参考报告季度与发布日期。不支持：2026-09-15取得字节已证明等于2026-08-25发布字节、历史各季度的当时可见值，或以未发布未来数据写入课程。' },
  { id: 15, authors: 'Albert Saiz', year: '2010', accessedAt: '2026-09-15', title: 'The Geographic Determinants of Housing Supply', publication: 'The Quarterly Journal of Economics125(3):1253–1296，DOI:10.1162/qjec.2010.125.3.1253；仅作者数据页与出版身份核查，全文尚未核读。', url: 'https://urbaneconomics.mit.edu/research/data', use: '支持：KMV／MRS供给弹性来源的文献与原始作者数据入口身份，列入后续阅读。不支持：本课已复现弹性、任意城市参数已被核读或该数据使任何IV自动有效；未导入数据或估计。' },
  { id: 16, authors: 'Marco Di Maggio et al.', year: '2017', accessedAt: '2026-09-15', title: 'Interest Rate Pass-Through: Mortgage Rates, Household Consumption, and Voluntary Deleveraging', publication: 'American Economic Review107(11):3550–3588，DOI:10.1257/aer.20141313；仅出版身份／摘要核查，全文尚未核读，候选深入阅读。', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.20141313', use: '支持：进一步寻找合同重置、消费与自愿偿债微观设计的阅读方向。不支持：本课已核验全文识别稳健性、降息结果对称外推加息或导入通用弹性。' },
  { id: 17, authors: 'Andreas Fuster & Paul S. Willen', year: '2017', accessedAt: '2026-09-15', title: 'Payment Size, Negative Equity, and Mortgage Default', publication: 'American Economic Journal: Economic Policy9(4):167–191，DOI:10.1257/pol.20150007；仅出版身份／摘要核查，全文尚未核读。', url: 'https://www.aeaweb.org/articles?id=10.1257/pol.20150007', use: '支持：在负权益条件下继续核读付款变化与违约微观证据的阅读方向。不支持：已核验全部选择控制、将摘要数字加入违约计算器或普适付款阈值；本课不引入其量化结果。' },
  { id: 18, authors: 'Peter Ganong & Pascal Noel', year: '2020', accessedAt: '2026-09-15', title: 'Liquidity versus Wealth in Household Debt Obligations: Evidence from Housing Policy in the Great Recession', publication: 'American Economic Review110(10):3100–3138，DOI:10.1257/aer.20181243；仅出版身份／摘要核查，全文尚未核读。', url: 'https://www.aeaweb.org/articles?id=10.1257/aer.20181243', use: '支持：继续核读付款流动性与本金减免政策变异的研究方向。不支持：财富从不重要、微观政策效应没有均衡溢出、已经核验RD／DiD全部假设；不导入摘要估计。' },
  { id: 19, authors: 'Ross Batzer, Jonah Coste, William D. Doerner & Michael J. Seiler', year: '2024', accessedAt: '2026-09-15', title: 'The Lock-In Effect of Rising Mortgage Rates', publication: 'FHFA WP24-03；仅论文身份与官方后续说明核查，全文计量设计未独立核读；不引用版本不同的数量估计。', url: 'https://www.fhfa.gov/research/papers/wp2403', use: '支持：比较优惠旧FRM与昂贵新合同、研究迁居与挂牌锁定的后续问题。不支持：本课已识别全国卖房减少数量、锁定一定推高全国价格、原始统计序列就是模型估计；本课锁定讨论是明确合同条件下的机制分析。' },
];

export const lesson316ReadingList: LessonReading[] = [
  { title: '先读真实合同：FRM／ARM／HELOC三种时钟', scope: 'CFPB贷款类型、ARM指数加点与Reg Z §1026.40(f)(2)、(f)(3)(vi)', reason: '先回答存量付款何时变、未来提款何时被冻结、已借本金何时可能加速清偿。三者若分不开，后面的抵押反馈会被误读成证券补仓。', guide: '写一张合同表：余额、重置日、提款期、到期日、触发条件、法域；法规只适用于其美国open-end产品范围。', url: lesson316References[6].url, group: 'core', links: [{ label: 'ARM说明', url: lesson316References[9].url }, { label: 'HELOC规则', url: lesson316References[7].url }] },
  { title: 'Iacoviello：借款约束为何对不同冲击产生不同反馈', scope: '2005 AER §II基本模型、§III家庭抵押扩展、§V动态；基础不足先读739–742引言', reason: '不是先学求解，而是把一周期名义承诺、预期抵押价值与不耐心借款人的边际支出连起来，检查供给冲击为什么不能沿用需求冲击结论。', guide: '将模型的一周期续借换成现实长期存量FRM，逐条标出哪些反馈仍在、哪些只影响新贷；本课未复现估计。', url: lesson316References[0].url, group: 'core', links: [{ label: '作者final PDF', url: 'https://www.matteoiacoviello.com/research_files/AER_2005.pdf' }] },
  { title: 'KMV：长期合同与未来住房需要修正单一财富效应', scope: '2020 JPE §II.A–C，尤其3295–3297；再读§IV与§V替代模型', reason: '逐步理解买／租、固定存量支付、LTV/PTI新发门、cash-out与分组流动性。它不是普通消费者按揭指南，而是具有实质单位与简化HELOC的均衡模型。', guide: '先画家庭选择集合，再核查HELOC脚注7的反事实优先级；模型信念不是直接观察因果冲击，银行深口袋假设限制外推。', url: lesson316References[1].url, group: 'models', links: [{ label: '作者托管final', url: 'https://violante.economics.princeton.edu/sites/g/files/toruqf5621/files/documents/kaplan-et-al-2020-the-housing-boom-and-bust-model-meets-evidence.pdf' }] },
  { title: 'MRS：地理总响应与纯渠道识别之间的距离', scope: 'June2013作者稿§III、§IV.B，Tables IV–VII及Figure6', reason: '把县级支出、ZIP汽车、信用菜单和供给弹性工具变量逐一对齐，区分地方总响应与单一抵押效应。', guide: '说明当地就业反馈为什么可进入估计；查每张表的观察单位、窗口与显著性，而不是把全国外推称为国家共同冲击因果效应。作者稿原始PDF未成功留存。', url: lesson316References[2].url, group: 'evidence', links: [{ label: '作者手稿阅读入口', url: 'https://atif.scholar.princeton.edu/document/41' }] },
  { title: 'Guren–McQuade：从一套止赎房到市场级需求与资本反馈', scope: 'November2019作者稿§2、§4–6；政策先对齐止赎完成、流动性恢复与REO持有时钟', reason: '看见更多卖盘之外，买家信用排除、等待选项与贷款人资本怎样共同影响匹配。版本限于实际核读的作者稿，出版final尚未逐项确认等价。', guide: '反事实分解的次序会影响份额；政策结果不是福利排名。指出固定供给、无法补股与双触发默认假设换掉后需重新检验什么。', url: lesson316References[3].url, group: 'systems', links: [{ label: '实际阅读作者稿', url: 'https://people.bu.edu/guren/guren_mcquade_foreclosures.pdf' }] },
  { title: '住房供给：存量耐久性与需求冲击的不对称吸收', scope: 'Glaeser–Gyourko2018 JEP期刊3–8页，再延伸全文；Saiz2010作为尚待全文核读的原始弹性来源', reason: '先分清房屋总存量、新建设流量、挂牌与成交量，然后判断融资冲击更可能落在价格还是数量。', guide: '本课只依据已核读3–8页讨论定性供给；地理特征也可能改变需求，不能因为它影响建房就自动作为有效IV。', url: lesson316References[10].url, group: 'models', links: [{ label: '官方整期阅读', url: 'https://ftp.aeaweb.org/full_issue.php?doi=10.1257/jep.32.1' }, { label: 'Saiz作者数据页', url: lesson316References[14].url }] },
  { title: '默认事件与法律回收：历史研究不等于当前法律', scope: 'Bhutta–Dokko–Shan2010 §2–4及结论；Ghent–Kudlyak09-10R §II.A', reason: '把负权益、预算缺口、逾期、止赎和最终损失排到不同事件时钟。追索威胁与实际回收成本必须区别。', guide: '保留四州非优质样本与工作论文版本；若研究当代具体国家合同，另外查有效法律、留置权和个人破产制度，不能直接用历史州表。', url: lesson316References[4].url, group: 'rules', links: [{ label: '追索工作论文', url: lesson316References[5].url }] },
  { title: 'FHFA数据：完成一次诚实的历史快照核对', scope: 'HPI FAQ覆盖／修订／时间／§32归属；季度TXT全国SA列', reason: '用本页116季度重画峰谷，记录原始哈希、下载时钟、展示截止和选择窗口，理解为什么一个漂亮图形仍不是反馈识别或PIT研究。', guide: '若端点刷新，另存新快照不覆盖旧字节；同季度修订逐项比较。反事实识别还需收入、合同和信用供给，不要拿指数直接填单套房贷款表。', url: lesson316References[12].url, group: 'evidence', links: [{ label: '官方季度原值', url: lesson316References[11].url }, { label: '参考报告', url: lesson316References[13].url }] },
  { title: '微观付款研究：三篇候选，不把摘要当全文审批', scope: 'Di Maggio等2017 AER；Fuster–Willen2017 AEJ；Ganong–Noel2020 AER', reason: '下一步分别核读合同重置、付款变化与本金减免识别，用它们检验本课二维状态；这些文献目前只核查出版身份／摘要，本课没有导入量化估计。', guide: '通读数据与识别后再评估外推：降息与加息对称吗？微观结果允许怎样的宏观反馈？政策处理改变的是现金流还是净财富？', url: lesson316References[15].url, group: 'evidence', links: [{ label: '付款与负权益', url: lesson316References[16].url }, { label: '流动性vs财富', url: lesson316References[17].url }] },
  { title: '迁居锁定：优惠旧贷与昂贵新贷之间的交易选择', scope: 'FHFA WP24-03全文数据、反事实与识别部分，尚待独立全文核读', reason: '研究既有FRM隔离月供冲击时，为什么新买卖决策仍可能受利率影响。不要混淆挂牌减少、需求减少与净价格效果。', guide: '先明确比较利差符号与版本窗口，再读计量设计；本课不引用锁定房屋数量或价格贡献估计。', url: lesson316References[18].url, group: 'systems', links: [{ label: '官方后续说明', url: 'https://www.fhfa.gov/blog/statistics/the-geography-of-the-lock-in-effect-which-msas-are-most-locked-in' }] },
];
