import JointLabStatic from '../components/JointLabStatic';
import JointQuiz from '../components/JointQuiz';
import JointStaticQuiz from '../components/JointStaticQuiz';
import JointScopeDiagram from '../components/JointScopeDiagram';
import {jointLabs,jointLabAudit} from '../components/jointLabDefinitions';
import {jointScenarios,jointScenarioAudit} from '../components/jointPolicyScenarios';
import {jointConcepts,jointThesis} from './jointPolicyConcepts';
import {lesson318References,lesson318ReadingList} from './jointPolicyReferences';
import {jointChecks,jointGlossary,jointInvariants,jointInterfaces} from './jointPolicyStudy';
import {canonicalJointPolicyStateExample,canonicalJointPolicyFields,canonicalJointPolicyAudit} from './jointPolicyState';
import type {LessonRecord} from './types';
export {canonicalJointPolicyStateExample,canonicalJointPolicyFields,canonicalJointPolicyAudit} from './jointPolicyState';
function Cites({ids}:{ids:readonly number[]}){return <>{ids.map(id=><a key={id} href={`#ref-${id}`}>[{id}] </a>)}</>;}
const sectionIds=['thesis','scope-route',...jointConcepts.map(c=>c.id),'public-scope-diagram','model-map','interactive-lab','joint-static-twins','checks-glossary','evidence-boundaries'];
const sourceIds=new Set(lesson318References.map(r=>r.id));
const citations=[...jointConcepts.flatMap(c=>c.sourceIds),...jointLabs.flatMap(l=>l.sourceIds),...jointScenarios.flatMap(s=>s.sourceIds),...jointChecks.flatMap(c=>c.sourceIds)];
export const lesson318IntegrityAudit=[
 {key:'27 distinct single-mechanism units, three coherent paragraphs and explicit scope each',passed:jointConcepts.length===27&&jointConcepts.every(c=>c.paragraphs.length===3&&c.paragraphs.every(p=>p.length>=90)&&c.boundary.length>=30&&c.sourceIds.length>0)},
 {key:'all section IDs unique; seven independent C labs attached exactly once',passed:new Set(sectionIds).size===sectionIds.length&&jointConcepts.flatMap(c=>c.labIds??[]).length===7&&new Set(jointConcepts.flatMap(c=>c.labIds??[])).size===7},
 {key:'nine references with declared reading scope and valid citations (authority reviewed separately)',passed:lesson318References.length===9&&citations.every(id=>sourceIds.has(id))&&lesson318References.every(r=>r.use.length>=60&&r.url.startsWith('https://'))},
 {key:'20 understanding checks, 40 decoded terms, 16 invariants and eight interfaces',passed:jointChecks.length===20&&jointGlossary.length===40&&jointInvariants.length===16&&jointInterfaces.length===8},
 {key:'source contract audits all pass; these are not independent approval',passed:[...jointLabAudit,...jointScenarioAudit,...canonicalJointPolicyAudit].every(a=>a.passed)},
] as const;
function Lesson318Content(){return <>
 <noscript><style>{'.lesson-page[data-lesson-id="3.18"] .joint-interactive-only,.lesson-page[data-lesson-id="3.18"] #interactive-lab{display:none!important}'}</style><p>JavaScript关闭：请使用每个C实验的原生展开记录与K1–K10。输入、答案、两条错路径、引用和图均保留，不依赖动态脚本。</p></noscript>
 <section id="thesis" className="lesson-section"><p className="section-kicker">ONE CENTRAL MECHANISM · JOINT RESPONSE</p><h2>财政效果属于一个联合响应环境；名义方向相同，不等于传导相同。</h2>{jointThesis.map(p=><p key={p}>{p}</p>)}<p className="section-sources"><Cites ids={[2,3]}/></p></section>
 <section id="scope-route" className="lesson-section"><p className="section-kicker">READING ROUTE / TOOL AND SOURCE PASSPORT</p><h2>先分清主体、工具与时钟，再讨论谁的承诺支持谁。</h2>
 <p>Master先修为3.05和3.17：前者提供条件反应规则，后者提供财政处理、基线与预算。3.06–3.08、3.14/3.16及T02/T03/T05/T06/T08只按需回查，不要求零背景读者先学完额外章节。正文按27个机制推进，先短期融资和需求，再实体合并与费用账，最后进入跨期承诺、经典模型和研究。它们是本Subchapter内部的编辑单元，不是新增27个课程小章节。</p>
 <p>量化宽松（quantitative easing，QE）在本课仅讨论政府债购买；准备金是银行的央行账户资产、央行负债，不是家庭的商业银行存款。SYN表示独立合成教学单位或情景，不是真实观察；PIT（point-in-time）是历史时点可得信息与版本约束，不是封面旧年份。基点是率的单位，100基点等于1个百分点。本课整数基点与金额上限是数值精度护照，不能用作现实经济或法律限制。</p>
 <p>七个实验分属给定购买力、两价格情景、瞬时面值交换、一期固定本金费用、简化汇款账、真实预算身份和局部两根；它们不是同一国家的连续轨迹。符号null表示未知／未识别，不是0。非付息发行相关的铸币税（seigniorage）还需要声明净发行、价格、持有需求与融资连接，不能等同现金存量或负债替换额。FTPL（fiscal theory of the price level）即财政价格水平理论，模型的无违约、无泡沫与约束远期资产负债路径的横截／终端条件不能省去。</p>
 <div className="precision-note"><span>审稿状态：同版正文已通过两位独立审稿人复核</span><p>两位审稿人完整复核同一冻结版：事实、公式、来源支持边界与教学结构均获APPROVE；题目作答前中性选项、M/K与打印答案对应及延伸阅读分页已修正，另经独立64页布局检查。本课未导入观察宏观数据、历史PIT回放、因果估计、预测、福利或主权安全认证；独立执行范围不扩大为所有原文或全模型证明。</p></div>
 <p className="section-sources"><Cites ids={[1,2,3,4,5,6,7,8,9]}/></p>
 </section>
 {jointConcepts.map((c,i)=><section id={c.id} key={c.id} className="lesson-section"><p className="section-kicker">{String(i+1).padStart(2,'0')} · CORE MECHANISM</p><h2>{c.title}</h2>{c.paragraphs.map(p=><p key={p}>{p}</p>)}{c.formula?<div className="equation-card"><span>澄清对象的必要算式</span><div><code>{c.formula.expression}</code></div><p>{c.formula.explanation}</p></div>:null}<div className="precision-note"><span>成立条件、反例与跨章接口</span><p>{c.boundary}</p></div>{c.labIds?.map(labId=><JointLabStatic key={labId} labId={labId}/>)}<p className="section-sources"><b>本机制依据：</b><Cites ids={c.sourceIds}/>{c.sourceNote.replace(/\[\d+\]/g,'')}</p></section>)}
 <section id="public-scope-diagram" className="lesson-section"><p className="section-kicker">THREE ENTITIES / ONE CONSOLIDATION · SYN</p><h2>抵消内部60之前，先认清外部40+60。</h2><p>同一原国债100中，央行买60之后，财政单体的国债负债还是100；央行增加国债资产60并发行准备金负债60，银行持有长期国债40和准备金60。下图只画与C3相关的项目，不是完整真实资产负债表。统计合并取消内部配对，不删除银行的外部债权，也不合并财政与央行权限。</p><JointScopeDiagram/><p className="section-sources"><Cites ids={[3,9]}/></p></section>
 <section id="model-map" className="lesson-section"><p className="section-kicker">MODEL / OBJECT / NON-SUPPORT</p><h2>三种证据层次必须连接，但不能互相顶替。</h2><div className="evidence-map"><div><h3>可核算的交换与资金账</h3><p>C3内部抵消、C4合约利息和C6资金身份都有明确单位与范围；它们不自行决定价格、需求、福利或偿付安全。真实输入预先含价格，更不能倒过来宣布已求出价格。 <Cites ids={[3,5]}/></p></div><div><h3>短期条件响应</h3><p>ECB传导与BIS954的指定框架解释未来工具、融资、资源与学习反馈。BIS954采用货币主导和半结构校准；本课不移植未核清的参数，不把它当S/W财政主导模型。 <Cites ids={[2,8]}/></p></div><div><h3>联合规则与承诺</h3><p>S/W给完整D路径与基础货币增长比较；Leeper给gross利率/税规则和局部根。不同工具、私人设定和终端条件，不合并成一套现实政策系数。 <Cites ids={[4,5]}/></p></div><div><h3>制度反例与现实识别</h3><p>违约演讲需正文与尾注同读；OLS反例表明均衡拟合不自动识别结构。两者都不替本课完成国家类别、因果研究或最优政策。 <Cites ids={[4,7]}/></p></div></div><p>先问来源回答哪个对象，再问条件如何进入因果链，最后问尚缺什么观察或闭合。知道一个模型不能证明什么，是使用它解释陌生新闻的必要能力，不是附在文末的免责声明。</p></section>
 <section id="interactive-lab" className="lesson-section"><p className="section-kicker">INTERACTIVE M1–M10</p><h2>十题把正确对象与两条闭合错路径放在一起。</h2><p>每题是独立SYN；题设、输入、三个候选值及固定排列与后面K题共用同一记录。选项先只显示数值与单位，正确位置分散；先手算并解释所求对象，再选择查看理由，不能依据选项中的评价或固定位置绕过推理。</p><JointQuiz/></section>
 <section id="joint-static-twins" className="lesson-section"><p className="section-kicker">STATIC K1–K10 / PRINT</p><h2>无脚本与纸上学习保留完整输入和诊断。</h2><p>先手算，再原生展开。打印版直接保留答案及两条错路径，不依赖动态选择。每题范围引用对应C护照，不能把合成账拼成国家预测。</p><JointStaticQuiz/></section>
 <section id="checks-glossary" className="lesson-section"><p className="section-kicker">CHECKS / CONTRACT AUDIT / GLOSSARY</p><h2>能指出缺少哪条响应或证据，才真正理解了联合政策。</h2><div className="check-grid">{jointChecks.map((c,i)=><div key={c.question}><details><summary>{String(i+1).padStart(2,'0')} · {c.question}</summary><p>{c.answer} <Cites ids={c.sourceIds}/></p></details><p className="print-only"><b>{String(i+1).padStart(2,'0')} · {c.question}　答案：</b>{c.answer} <Cites ids={c.sourceIds}/></p></div>)}</div><div className="yield-fixture-audit"><span>来源完整性与pure契约检查（不是独立审批）</span><ul>{[...jointLabAudit,...jointScenarioAudit,...canonicalJointPolicyAudit,...lesson318IntegrityAudit].map(a=><li key={a.key} className={a.passed?'passed':''}>{a.passed?'PASS':'FAIL'} · {a.key}</li>)}</ul></div><div className="term-grid">{jointGlossary.map(([term,meaning,confusion])=><article className="term-card" key={term}><h3>{term}</h3><p>{meaning}。</p><em>不可混同：{confusion}。</em></article>)}</div></section>
 <section id="evidence-boundaries" className="lesson-section"><p className="section-kicker">STATE / PROVENANCE / RESEARCH / INTERFACES</p><h2>最终状态记录已知范围和未知出口，不制造全能政策答案。</h2><p>canonical有{canonicalJointPolicyFields.length}个顶层字段，七实验各有独立护照。唯一直接上下文是3.17已封版对象，九条路径保留原始对象或原始值身份、numericCalibration=false；其批准正文修订时钟不晚于本课登记截止{canonicalJointPolicyStateExample.scopePassport.registeredAt}。3.05只有语义先修，没有虚构的canonical生产者；登记时钟也不认证历史PIT。</p><div className="precision-note"><span>canonical · {canonicalJointPolicyStateExample.schemaVersion}</span><p><code>{canonicalJointPolicyFields.join(', ')}</code>。给定购买力、随机情景、合并本金、一期费用、汇款、真实资金账、根配置、需求、支持与识别分列；未知的因果产出、价格、福利和安全不填0。</p></div>
 <h3>生产者不变量</h3><ol className="contract-list">{jointInvariants.map((r,i)=><li key={r}><b>{String(i+1).padStart(2,'0')}</b><span>{r}</span></li>)}</ol>
 <h3>实际阅读与证据版本</h3><p>作者实读ECB两页完整解释正文；BIS2023只读指定政策交互和完整Box A及脚注，未通读43页或复算图。Leeper保留期刊排版19页文字全文及关键原图，不等于读其每篇参考或复现另供数学附录。S/W实读第三方扫描主文印1–7及Appendix A印8–9，B/C未读；官方身份已核，官方PDF本次交付受限，未证明第三方与官方字节等价。版权全文只作私有核读证据，不在网页发布镜像。 <Cites ids={[1,2,3,4,5]}/></p>
 <p>Fed FAM只读三个指定完整小节；Kocherlakota官方正文和全部九尾注已读，所引论文未逐篇读；Tenreyro只读指定资产交换和部分目标/财务段，未看Chart1、未读完整演讲。BIS954实际为当前交付51页中的指定引言/模型/校准页，部分归一化与符号尚需实现桥接，所以不复制量化参数或模拟图。作者阅读范围和两位审稿人的个人执行范围分别登记，不让一个人读过变成所有人全读。 <Cites ids={[6,7,8,9]}/></p>
 <p>来源入口、原始交付、哈希、读取范围和当前下载时间承担不同任务。2026取得标为2021的PDF，不保证2021首次交付同一字节；服务器修改时间也不证明正文改了哪里。没有实际历史可得数据就不声称PIT，无真实处理和排除假设就不声称因果。本文图与所有数值均为明确SYN/模型反例，未知观察结果保持未知。</p>
 <h3>把开放地图转成局部研究</h3><p>选一个政策新闻、一个主体、一个融资或执行结果和一个时间窗口，事先写出联合工具基线、替代机制与失败证据。若长期yield上涨而短率不变，先区分未来路径、信用、流动性与增长信息；若公共费用上升，按合约/本金/时钟对账，再另评宏观基线。不要同时给全回路估计一个万能乘数，也不要让高拟合或来源名气替未识别箭头填值。</p>
 <h3>跨章接口</h3><div className="interface-grid">{jointInterfaces.map(([name,payload,guardrail])=><article key={name}><span>{name}</span><p><b>传递什么：</b>{payload}。</p><p><b>不可跨越：</b>{guardrail}。</p></article>)}</div><p>复盘时用自己的话重建：财政首先改变谁的订单或预算，央行与私人如何条件响应，行为经过哪道融资和资源门，新收入、价格与公共费用如何成为下一轮输入。然后给每条箭头标明“可核算、条件模型、待识别”之一；这比记住某种政策组合总有效，更能支撑后续主权债务和跨市场分析。</p>
 </section>
 </>;}
export const lesson318:LessonRecord={slug:'3-18',id:'3.18',chapter:'03',chapterTitle:'Macro State & Financial Conditions',title:'Fiscal–Monetary Interaction：联合响应、公共费用与跨期承诺',subtitle:'从财政处理与央行条件路径进入融资和资源，分清公共实体合并、付息准备金、净收益汇款、预算身份与财政支持，再核对经典承诺/规则模型及局部识别',readingTime:'正文主线约55–75分钟；C1–C7手算/交互约35–55分钟；M/K十题约20–35分钟，理解检查/术语/复盘约25–40分钟。为学习估时，不以填字凑时长；经典论文深入阅读另计',prerequisite:'Master：3.05、3.17；按需T02/T03/T05/T06/T08及3.06–3.08、3.14/3.16。3.17只作直接合同上下文，不导入数值校准；3.05只作语义先修',updatedAt:'2026-09-15',revision:'3.18-r1',reviewStatus:'double-reviewed',reviews:[
 {kind:'accuracy',completedAt:'2026-09-15',decision:'approved',revision:'3.18-r1',summary:'完整同版复核机制、公式、九来源支持范围与九条上游身份；独立61输出、30选项、20错路径及域反例通过，局部根不认证现实制度、因果或主权安全。'},
 {kind:'pedagogy',completedAt:'2026-09-15',decision:'approved',revision:'3.18-r1',summary:'完整同版复核因果组织、零基础路径与反例；本人206浏览器检查通过，题目前中性数值、分散正确位置和M/K/打印诊断一致，阅读分页已修正；另经独立64页布局检查。'},
],previous:{slug:'3-17',label:'3.17 Fiscal Policy'},next:{label:'3.19 Sovereign Debt & Fiscal Sustainability'},sections:[{id:'thesis',label:'核心命题'},{id:'scope-route',label:'阅读与单位护照'},...jointConcepts.map(({id,label})=>({id,label})),{id:'public-scope-diagram',label:'三实体合并示意'},{id:'model-map',label:'模型与证据对象'},{id:'interactive-lab',label:'Interactive M1–M10'},{id:'joint-static-twins',label:'Static K1–K10'},{id:'checks-glossary',label:'Checks / Audit / Glossary'},{id:'evidence-boundaries',label:'State / Sources / Interfaces'}],Content:Lesson318Content,references:lesson318References,readingList:lesson318ReadingList,readingListOrder:'source'};
