import type { LessonReading, LessonReference } from './types';

export const lesson309References: LessonReference[] = [
  { id: 1, authors: 'Michael McLeay, Amar Radia & Ryland Thomas', year: '2014', title: 'Money creation in the modern economy', publication: 'Bank of England Quarterly Bulletin 2014 Q1', url: 'https://www.bankofengland.co.uk/quarterly-bulletin/2014/q1/money-creation-in-the-modern-economy', use: '贷款与存款同步确认、偿还、银行购买资产、QE 交易对手及固定货币乘数边界；是英国制度的机制解释，不支持银行无限放贷。' },
  { id: 2, authors: 'Michael McLeay, Amar Radia & Ryland Thomas', year: '2014', title: 'Money in the modern economy: an introduction', publication: 'Bank of England Quarterly Bulletin 2014 Q1', url: 'https://www.bankofengland.co.uk/quarterly-bulletin/2014/q1/money-in-the-modern-economy-an-introduction', use: '现金、商业银行存款与准备金的两层货币入门；不是当前监管参数或全球法律来源。' },
  { id: 3, authors: 'Deutsche Bundesbank', year: '2017', title: 'The role of banks, non-banks and the central bank in the money creation process', publication: 'Monthly Report, April 2017', url: 'https://www.bundesbank.de/resource/blob/654284/df66c4444d065a7f519e2ab0c476df58/m/2017-04-money-creation-process-data.pdf', use: '贷款、跨行支付、准备金迁移、事后融资、资产购买与央行卖方身份；欧元区示例不能无条件外推。' },
  { id: 4, authors: 'European Central Bank', year: 'page updated 2024-06-19', accessedAt: '2026-09-02', title: 'What is money?', publication: 'ECB Explainers', url: 'https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me-more/html/what_is_money.en.html', use: '中央银行货币、商业银行货币和贷款创造存款的层级；不把准备金称为公众存款。' },
  { id: 5, authors: 'International Monetary Fund', year: '2016 edition; published 2017-11-09', title: 'Monetary and Financial Statistics Manual and Compilation Guide', publication: 'IMF Statistics Department', url: 'https://www.imf.org/en/publications/manuals-guides/issues/2018/09/21/monetary-and-financial-statistics-manual-and-compilation-guide-43001', use: '机构部门、工具、货币发行/持有部门、货币基础、广义货币、合并及存量—流量桥；统计定义不等于国内存款法。' },
  { id: 6, authors: 'International Monetary Fund', year: 'update launched 2025; completion targeted 2028', accessedAt: '2026-09-02', title: 'Update of the Monetary and Financial Statistics Manual', publication: 'IMF Data Standards', url: 'https://www.imf.org/en/data/statistics/update-of-monetary-and-financial-statistics-manual', use: '说明 MFSM 正在更新及时间表；截至访问日不能把咨询材料当作已完成的新手册。' },
  { id: 7, authors: 'United Nations Statistics Division', year: '2025 pre-edit / white-cover version', accessedAt: '2026-09-02', title: 'System of National Accounts 2025 — Pre-edit Version', publication: 'United Nations', url: 'https://unstats.un.org/unsd/nationalaccount/docs/2025_SNA_Pre-edit.pdf', use: '机构单位、垂直复式、横向对应、四重记账及交易/重估/其他数量变化；公开件身份必须保留为 pre-edit。' },
  { id: 8, authors: 'CPSS & IOSCO', year: '2012', title: 'Principles for Financial Market Infrastructures', publication: 'BIS / IOSCO', url: 'https://www.bis.org/publications/principles-financial-market-infrastructures', use: '法律基础、流动性风险、结算最终性和中央银行货币结算原则；不是各国自动生效的支付法。' },
  { id: 9, authors: 'Committee on Payment and Settlement Systems', year: '2003', title: 'The role of central bank money in payment systems', publication: 'Bank for International Settlements', url: 'https://www.bis.org/cpmi/publ/d55.pdf', use: '中央银行货币作为结算资产及两层货币体系；制度选择与账户准入仍有国别差异。' },
  { id: 10, authors: 'Board of Governors of the Federal Reserve System', year: 'current operating page', accessedAt: '2026-09-02', title: 'Fedwire Funds Services', publication: 'Federal Reserve Payment Systems', url: 'https://www.federalreserve.gov/paymentsystems/fedfunds_about.htm', use: '美国 Fedwire 的实时全额、最终且不可撤销的准备金结算；仅支持美国制度。' },
  { id: 11, authors: 'European Central Bank', year: 'current operating page', accessedAt: '2026-09-02', title: 'T2: real-time gross settlement', publication: 'TARGET Services', url: 'https://www.ecb.europa.eu/paym/target/t2/html/index.en.html', use: '欧元体系 T2 以中央银行货币结算的运营边界；方法与服务状态会更新。' },
  { id: 12, authors: 'Committee on Payments and Market Infrastructures', year: '2016', title: 'Correspondent banking', publication: 'Bank for International Settlements', url: 'https://www.bis.org/cpmi/publ/d147.pdf', use: 'correspondent/respondent、nostro/vostro 与跨境支付链；报文传输不等于最终结算。' },
  { id: 13, authors: 'Bank for International Settlements', year: '2025', title: 'The next-generation monetary and financial system', publication: 'Annual Economic Report 2025, Chapter III', url: 'https://www.bis.org/publ/arpdf/ar2025e3.htm', use: '代理账户更新与多币种结算示例；政策愿景不是当前全球法律事实。' },
  { id: 14, authors: 'Board of Governors of the Federal Reserve System', year: 'release dated 2026-08-25', accessedAt: '2026-09-02', title: 'Money Stock Measures — H.6', publication: 'Federal Reserve Statistical Release', url: 'https://www.federalreserve.gov/releases/h6/current/default.htm', use: '当前美国 M1、M2 与 monetary base 定义和数据入口；动态发布必须保存 release date 与 vintage。' },
  { id: 15, authors: 'Board of Governors of the Federal Reserve System', year: 'current rule page', accessedAt: '2026-09-02', title: 'Reserve Requirements', publication: 'Federal Reserve Monetary Policy', url: 'https://www.federalreserve.gov/monetarypolicy/reservereq.htm', use: '美国净交易账户准备金率自 2020-03-26 起为零的当前官方说明；不支持全球准备金率或无限放贷。' },
  { id: 16, authors: 'European Central Bank', year: 'current methodology page', accessedAt: '2026-09-02', title: 'What are monetary aggregates?', publication: 'ECB Data Portal Methodology', url: 'https://data.ecb.europa.eu/methodology/what-are-monetary-aggregates', use: '欧元区 M1/M2/M3 的工具、发行和持有部门边界；不能移作其他法域定义。' },
  { id: 17, authors: 'European Central Bank', year: 'current rule explainer', accessedAt: '2026-09-02', title: 'What are minimum reserve requirements?', publication: 'ECB Explainers', url: 'https://www.ecb.europa.eu/ecb-and-you/explainers/tell-me/html/minimum_reserve_req.en.html', use: '欧元区特定负债 1% 最低准备金与平均维持安排的当前说明；规则版本与实施日期必须保留。' },
  { id: 18, authors: 'Board of Governors of the Federal Reserve System', year: 'FAQ current through 2026-09-02', accessedAt: '2026-09-02', title: 'Interest on Reserve Balances: Frequently Asked Questions', publication: 'Federal Reserve Monetary Policy', url: 'https://www.federalreserve.gov/monetarypolicy/iorb-faqs.htm', use: '准备金的央行负债/银行资产身份、持有目的与 IORB；准备金不能被直接贷给公众。' },
  { id: 19, authors: 'Board of Governors of the Federal Reserve System', year: 'page updated 2024-05-20', accessedAt: '2026-09-02', title: 'The Discount Window and Discount Rate', publication: 'Federal Reserve Monetary Policy', url: 'https://www.federalreserve.gov/monetarypolicy/discountrate.htm', use: '合格银行以抵押取得央行信用和准备金的美国制度；不是资本注入或全球最后贷款人通则。' },
  { id: 20, authors: 'Federal Reserve Bank of New York', year: 'current operating page', accessedAt: '2026-09-02', title: 'Monetary Policy Implementation', publication: 'Markets & Policy Implementation', url: 'https://www.newyorkfed.org/markets/domestic-market-operations/monetary-policy-implementation', use: '美国 ample-reserves 操作框架与市场操作的动态制度入口；具体条款需保存访问日。' },
  { id: 21, authors: 'Federal Reserve Bank of New York', year: 'FAQ updated 2024-12-18', accessedAt: '2026-09-02', title: 'Standing Repo Facility Frequently Asked Questions', publication: 'Markets & Policy Implementation', url: 'https://www.newyorkfed.org/markets/repo-agreement-ops-faq-241218', use: '有抵押隔夜流动性与回购交易边界；不能把 repo 写成永久证券购买。' },
  { id: 22, authors: 'Board of Governors of the Federal Reserve System', year: 'current balance-sheet guide', accessedAt: '2026-09-02', title: 'Federal Reserve liabilities', publication: 'Credit and Liquidity Programs and the Balance Sheet', url: 'https://www.federalreserve.gov/monetarypolicy/bst_frliabilities.htm', use: '准备金、流通货币与 Treasury General Account 等央行负债；支持财政支付的账户位置。' },
  { id: 23, authors: 'Christopher J. Waller', year: '2025-07-10', accessedAt: '2026-09-02', title: "Demystifying the Federal Reserve's Balance Sheet", publication: 'Federal Reserve Speech', url: 'https://www.federalreserve.gov/newsevents/speech/waller20250710a.htm', use: '税款支付、TGA 与准备金方向的官方操作解释；演讲不等于全球财政结算制度。' },
  { id: 24, authors: 'Annette Vissing-Jorgensen', year: '2025-08-06', accessedAt: '2026-09-02', title: 'Fluctuations in the Treasury General Account and their effect on the Fed’s balance sheet', publication: 'FEDS Notes', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/fluctuations-in-the-treasury-general-account-and-their-effect-on-the-feds-balance-sheet-20250806.html', use: '美国 TGA 变化与准备金的账户机制；历史和机构安排具有时期依赖。' },
  { id: 25, authors: 'Jeffrey Huther, Luke Pettit & Mark Wilkinson', year: '2019-12-16', accessedAt: '2026-09-02', title: 'Fiscal flow volatility and reserves', publication: 'FEDS Notes', url: 'https://www.federalreserve.gov/econres/notes/feds-notes/fiscal-flow-volatility-and-reserves-20191216.html', use: '税收与财政流对美国准备金的短期影响；不支持财政乘数或长期宏观结论。' },
  { id: 26, authors: 'Basel Committee on Banking Supervision', year: 'living consolidated framework', accessedAt: '2026-09-02', title: 'Basel Framework', publication: 'Bank for International Settlements', url: 'https://www.bis.org/committees/bcbs/basel-framework', use: '国际最低审慎标准的版本入口；各法域实施、适用主体和过渡期必须另行确认。' },
  { id: 27, authors: 'Basel Committee on Banking Supervision', year: 'in force 2023-01-01; published 2020-11-26', accessedAt: '2026-09-02', title: 'RBC20 — Calculation of minimum risk-based capital requirements', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/rbc/20/inforce/2023-01-01/published/2020-11-26', use: 'CET1、Tier 1、总资本最低比例与缓冲接口；不是任一银行完整国内合规结论。' },
  { id: 28, authors: 'Basel Committee on Banking Supervision', year: 'in force 2023-01-01; published 2020-03-27', accessedAt: '2026-09-02', title: 'LEV20 — Calculation', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lev/20/inforce/2023-01-01/published/2020-03-27', use: 'Tier 1 对非风险加权暴露的 3% 国际最低后备约束；本地要求可更严。' },
  { id: 29, authors: 'Basel Committee on Banking Supervision', year: 'in force 2019-12-15; published 2022-12-08', accessedAt: '2026-09-02', title: 'LCR20 — Calculation', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lcr/20/inforce/2019-12-15/published/2022-12-08', use: 'HQLA、30 日净现金流出、75% 流入上限与压力期缓冲使用；不等于日内准备金余额。' },
  { id: 30, authors: 'Basel Committee on Banking Supervision', year: 'in force/published 2019-12-15', accessedAt: '2026-09-02', title: 'NSF20 — Calculation and reporting', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/nsf/20/inforce/2019-12-15/published/2019-12-15', use: 'ASF/RSF 与一年期稳定融资最低标准；具体分类和国内实施须按版本核对。' },
  { id: 31, authors: 'Basel Committee on Banking Supervision', year: 'in force/published 2019-12-15', accessedAt: '2026-09-02', title: 'LEX20 — Requirements', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/lex/20/inforce/2019-12-15/published/2019-12-15', use: '单一对手方/关联组大额风险框架、25% 一般上限与报告阈值；豁免和国内实施另查。' },
  { id: 32, authors: 'Basel Committee on Banking Supervision', year: 'consolidated guideline viewed 2026-09-02', accessedAt: '2026-09-02', title: 'PAP10 — Definitions and application', publication: 'Basel Consolidated Guidelines', url: 'https://www.bis.org/committees/bcbs/basel-consolidated-guidelines/module/pap/10', use: 'past due、problem asset、non-performing 与监管 default 的边界；合同、会计与监管定义不能互换。' },
  { id: 33, authors: 'Basel Committee on Banking Supervision', year: 'consolidated guideline viewed 2026-09-02', accessedAt: '2026-09-02', title: 'PAP20 — Credit risk and accounting for expected credit losses', publication: 'Basel Consolidated Guidelines', url: 'https://www.bis.org/committees/bcbs/basel-consolidated-guidelines/module/pap/20', use: 'ECL 治理、allowance、write-off 与 recovery 的审慎边界；不替代适用会计准则。' },
  { id: 34, authors: 'Basel Committee on Banking Supervision', year: 'in force 2023-01-01; published 2025-06-10', accessedAt: '2026-09-02', title: 'CRE20 — Standardised approach: individual exposures', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/cre/20/inforce/2023-01-01/published/2025-06-10', use: '承诺、信用转换、default 与个别暴露的监管接口；须绑定方法和法域。' },
  { id: 35, authors: 'Basel Committee on Banking Supervision', year: 'in force 2023-01-01; published 2020-03-27', accessedAt: '2026-09-02', title: 'CRE35 — IRB approach: treatment of expected losses and provisions', publication: 'Basel Framework', url: 'https://www.bis.org/committees/bcbs/basel-framework/standard/cre/35/inforce/2023-01-01/published/2020-03-27', use: 'IRB 下监管 expected loss 与 eligible provisions 的资本桥；不能代表所有银行或会计准则。' },
  { id: 36, authors: 'IFRS Foundation', year: 'current standard page', accessedAt: '2026-09-02', title: 'IFRS 9 Financial Instruments', publication: 'IFRS Accounting Standards', url: 'https://www.ifrs.org/issued-standards/list-of-standards/ifrs-9-financial-instruments/', use: '分类、初始计量、实际利率、ECL、终止确认和核销的准则入口；本地采纳状态另查。' },
  { id: 37, authors: 'IFRS Foundation', year: '2024 issued standard', accessedAt: '2026-09-02', title: 'IFRS 9 Financial Instruments — issued requirements', publication: 'IFRS Accounting Standards Part A', url: 'https://www.ifrs.org/content/dam/ifrs/publications/pdf-standards/english/2024/issued/part-a/ifrs-9-financial-instruments.pdf?bypass=on', use: '2024 issued requirements 中 12-month/lifetime ECL、write-off 与 derecognition 的具体文本；直达文件可能要求 IFRS 注册或登录，不得与 CECL 或宏观统计口径混写。' },
  { id: 38, authors: 'International Accounting Standards Board', year: '2024-07-04', accessedAt: '2026-09-02', title: 'Post-implementation Review of IFRS 9 — Impairment', publication: 'IFRS Foundation Project', url: 'https://www.ifrs.org/projects/completed-projects/2024/post-implementation-review-of-ifrs-9-impairment/', use: 'IFRS 9 减值实施复核的当前状态；不提供任何银行的具体 ECL 数值。' },
  { id: 39, authors: 'U.S. Federal Banking Agencies', year: 'revised 2023-04-27', accessedAt: '2026-09-02', title: 'Interagency Policy Statement on Allowances for Credit Losses', publication: 'Federal Reserve Supervision Guidance', url: 'https://www.federalreserve.gov/frrs/guidance/interagency-policy-statement-on-allowances-for-credit-losses.htm', use: '美国 CECL、ACL、表外承诺和核销处理边界；CECL 不采用 IFRS 9 三阶段结构。' },
  { id: 40, authors: 'Financial Accounting Standards Board', year: '2016; subsequent codification updates apply', accessedAt: '2026-09-02', title: 'ASU 2016-13 — Measurement of Credit Losses on Financial Instruments', publication: 'Accounting Standards Update', url: 'https://storage.fasb.org/ASU_2016-13.pdf', use: 'CECL 的原始标准更新；应用必须核对后续修订和主体生效安排。' },
  { id: 41, authors: 'Federal Deposit Insurance Corporation', year: 'FAQ updated 2024-04-01', accessedAt: '2026-09-02', title: 'Deposit Insurance FAQs', publication: 'FDIC', url: 'https://www.fdic.gov/resources/deposit-insurance/faq', use: '美国每名存款人、每家受保银行、每个所有权类别的标准 25 万美元保险边界；不是每账户限额。' },
  { id: 42, authors: 'International Association of Deposit Insurers', year: 'September 2025 edition; published 2025-11-28', accessedAt: '2026-09-02', title: 'Core Principles for Effective Deposit Insurance Systems', publication: 'IADI', url: 'https://www.iadi.org/what-we-do/policy/core-principles/', use: '存款保险制度设计的国际原则；不规定全球统一覆盖金额或替代国内法。' },
  { id: 43, authors: 'Financial Stability Board', year: 'revised 2024', accessedAt: '2026-09-02', title: 'Key Attributes of Effective Resolution Regimes for Financial Institutions', publication: 'FSB', url: 'https://www.fsb.org/2024/04/key-attributes-of-effective-resolution-regimes-for-financial-institutions-revised-version-2024/', use: '处置权力、保障、规划与跨境合作的国际原则；具体债权顺位仍由国内法和合同决定。' },
  { id: 44, authors: 'Board of Governors of the Federal Reserve System', year: 'current regulation page', accessedAt: '2026-09-02', title: 'Regulation A — Extensions of Credit by Federal Reserve Banks', publication: 'Federal Reserve Regulatory Resources', url: 'https://www.federalreserve.gov/frrs/regulations/regulation-a-extensions-of-credit-by-federal-reserve-banks.htm', use: '美国联储银行信用工具的法律入口；只适用于相应美国制度。' },
  { id: 45, authors: 'European Central Bank', year: 'dated 2024-09-27', accessedAt: '2026-09-02', title: 'Agreement on emergency liquidity assistance', publication: 'Eurosystem', url: 'https://www.ecb.europa.eu/pub/pdf/other/ecb.agreementemergencyliquidityassistance202410~b8b78cd4f5.en.pdf', use: '欧元体系 ELA 治理、偿付能力和抵押品边界；不支持全球无条件最后贷款人。' },
  { id: 46, authors: 'James Tobin', year: '1963', title: 'Commercial Banks as Creators of Money', publication: 'Cowles Foundation Discussion Paper 159', url: 'https://elischolar.library.yale.edu/cowles-discussion-paper-series/388/', use: '银行资产选择、竞争与货币创造的经典边界；历史制度和理论假设必须保留。' },
  { id: 47, authors: 'Seth B. Carpenter & Selva Demiralp', year: '2010', title: 'Money, Reserves, and the Transmission of Monetary Policy: Does the Money Multiplier Exist?', publication: 'Finance and Economics Discussion Series 2010-41', url: 'https://www.federalreserve.gov/econres/feds/money-reserves-and-the-transmission-of-monetary-policy-does-the-money-multiplier-exist.htm', use: '美国样本中准备金、贷款与存款的经验关系及固定乘数质疑；历史样本不等于所有操作框架。' },
  { id: 48, authors: 'Zoltan Jakab & Michael Kumhof', year: '2015', title: 'Banks are not intermediaries of loanable funds — and why this matters', publication: 'Bank of England Working Paper 529', url: 'https://www.bankofengland.co.uk/working-paper/2015/banks-are-not-intermediaries-of-loanable-funds-and-why-this-matters', use: '融资中介模型与银行融资创造模型的比较；是模型论证，不是逐项会计或当前法规。' },
  { id: 49, authors: 'Douglas W. Diamond', year: '1984', title: 'Financial Intermediation and Delegated Monitoring', publication: 'Review of Economic Studies 51(3)', url: 'https://doi.org/10.2307/2297430', use: '银行集中监督与债务合约的理论基础；不直接生成现代资本或流动性比率。' },
  { id: 50, authors: 'Bengt Holmström & Jean Tirole', year: '1997', title: 'Financial Intermediation, Loanable Funds, and the Real Sector', publication: 'Quarterly Journal of Economics 112(3)', url: 'https://doi.org/10.1162/003355397555316', use: '借款人与中介资本、可融资项目和监督激励；模型资本不能逐字等同 CET1。' },
  { id: 51, authors: 'Basel Committee on Banking Supervision', year: '2019', accessedAt: '2026-09-02', title: 'Launch of the consolidated Basel Framework', publication: 'BCBS d491', url: 'https://www.bis.org/bcbs/publ/d491.pdf', use: 'Basel 标准法律地位与国内实施边界；国际最低标准不具有超国家直接法律效力。' },
  { id: 52, authors: '国家金融监督管理总局', year: '2023; effective 2024-01-01', accessedAt: '2026-09-02', title: '商业银行资本管理办法', publication: '规章', url: 'https://www.nfra.gov.cn/cn/view/pages/rulesDetail.html?docId=1134197&itemId=4214', use: '中国商业银行资本规则的法域示例；不得替代其他国家规则，后续修订需重新核验。' },
  { id: 53, authors: 'European Central Bank', year: 'framework decision announced 2024-03-13', accessedAt: '2026-09-02', title: 'Changes to the operational framework for implementing monetary policy', publication: 'ECB Press Release', url: 'https://www.ecb.europa.eu/press/pr/date/2024/html/ecb.pr240313~807e240020.en.html', use: '欧元体系操作框架演进与最低准备金背景；政策决定和实施细则须带日期。' },
  { id: 54, authors: 'European Central Bank', year: 'current operating page', accessedAt: '2026-09-02', title: 'Monetary policy operations', publication: 'ECB', url: 'https://www.ecb.europa.eu/mopo/implement/html/index.en.html', use: '欧元体系公开市场操作和常备便利入口；动态条款不宜硬编码。' },
  { id: 55, authors: 'Board of Governors of the Federal Reserve System', year: 'latest official release 2026Q1 as of access date', accessedAt: '2026-09-02', title: 'Financial Accounts of the United States — Z.1', publication: 'Federal Reserve Statistical Release', url: 'https://www.federalreserve.gov/releases/z1/default.htm', use: '美国部门—工具存量和流量的当前数据入口；预览、正式发布与表号变更必须分开。' },
  { id: 56, authors: 'Board of Governors of the Federal Reserve System', year: 'published 1999-12-13; revised 2026-06-02', accessedAt: '2026-09-02', title: 'SR 99-37 — Risk Management and Valuation of Retained Interests Arising from Securitization Activities', publication: 'Federal Reserve Supervision and Regulation Letters', url: 'https://www.federalreserve.gov/supervisionreg/srletters/SR9937.htm', use: '证券化留存权益的风险管理、估值与资本边界；旧信件及 2026 修订身份必须同时保留。' },
  { id: 57, authors: 'Bank of England', year: 'current methodology page', accessedAt: '2026-09-02', title: 'Further details about M4 data', publication: 'Bank of England Statistics', url: 'https://www.bankofengland.co.uk/statistics/details/further-details-about-m4-data', use: '英国 M4 作为特定 MFI 负债由特定私营部门持有的统计定义；不是全球广义货币口径。' },
  { id: 58, authors: 'Financial Stability Board', year: '2025', accessedAt: '2026-09-02', title: 'Global Monitoring Report on Non-Bank Financial Intermediation 2025', publication: 'FSB', url: 'https://www.fsb.org/2025/12/global-monitoring-report-on-nonbank-financial-intermediation-2025/', use: '非银部门分类和银行—非银联系的 2024 数据快照；不支持所有非银负债都是货币。' },
  { id: 59, authors: 'European Parliament & Council', year: '2014; consolidated text checked 2026-09-02', accessedAt: '2026-09-02', title: 'Directive 2014/49/EU on deposit guarantee schemes', publication: 'Official Journal of the European Union', url: 'https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:32014L0049', use: '欧盟存款保障制度的法律边界示例；国家转置与修订状态需另查。' },
  { id: 60, authors: '国务院', year: '2015; current official page checked 2026-09-02', accessedAt: '2026-09-02', title: '存款保险条例', publication: '中国政府网', url: 'https://www.gov.cn/zhengce/content/2015-03/31/content_9562.htm', use: '中国存款保险制度的法域示例；覆盖范围与有效文本不得外推到其他国家。' },
];

export const lesson309DynamicSourceRequirements = [
  { sourceIds: [4, 14, 16, 57], fields: ['methodologyVersion', 'releaseDate', 'dataThrough', 'aggregateDefinition', 'retrievedAt'] },
  { sourceIds: [6, 7], fields: ['documentStatus', 'edition', 'publicationDate', 'supersededBy', 'retrievedAt'] },
  { sourceIds: [10, 11, 20, 21, 53, 54], fields: ['operatingFramework', 'serviceVersion', 'effectiveAt', 'accessRule', 'retrievedAt'] },
  { sourceIds: [14, 15, 17, 18], fields: ['jurisdiction', 'ruleVersion', 'effectiveFrom', 'maintenancePeriod', 'retrievedAt'] },
  { sourceIds: [19, 41, 44, 45, 52, 59, 60], fields: ['jurisdiction', 'lawVersion', 'effectiveFrom', 'institutionScope', 'coverageOrEligibility', 'retrievedAt'] },
  { sourceIds: [22, 23, 24, 25], fields: ['accountArchitecture', 'observationPeriod', 'publicationDate', 'institutionalChange', 'retrievedAt'] },
  { sourceIds: [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 51], fields: ['module', 'publishedAt', 'inForceFrom', 'futureVersion', 'domesticImplementationStatus', 'retrievedAt'] },
  { sourceIds: [36, 37, 38, 39, 40], fields: ['accountingFramework', 'standardVersion', 'adoptionStatus', 'transition', 'retrievedAt'] },
  { sourceIds: [42, 43, 58], fields: ['edition', 'dataThrough', 'implementationStatus', 'jurisdictionScope', 'retrievedAt'] },
  { sourceIds: [55, 56], fields: ['releaseDate', 'dataThrough', 'revisionStatus', 'tableOrLetterVersion', 'retrievedAt'] },
] as const;

const lesson309DynamicSourceIds = Array.from(new Set(
  lesson309DynamicSourceRequirements.flatMap(({ sourceIds }) => [...sourceIds]),
)).sort((left, right) => left - right);

export const lesson309SourceIdentityPassports = lesson309DynamicSourceIds.map((sourceId) => {
  const source = lesson309References.find((candidate) => candidate.id === sourceId);
  const requiredRefreshFields = Array.from(new Set(
    lesson309DynamicSourceRequirements
      .filter((requirement) => requirement.sourceIds.some((candidateId) => candidateId === sourceId))
      .flatMap(({ fields }) => [...fields]),
  ));

  return {
    sourceId,
    retrievedAt: source?.accessedAt ?? null,
    sourceIdentity: source ? {
      authors: source.authors,
      title: source.title,
      publication: source.publication,
      editionOrDate: source.year,
      url: source.url,
    } : null,
    requiredRefreshFields,
    measurementFlags: source?.accessedAt
      ? ['reference-record-only-not-full-snapshot', 'refresh-required-before-empirical-use']
      : ['missing-retrievedAt', 'reference-record-only-not-full-snapshot', 'refresh-required-before-empirical-use'],
  };
});

export const lesson309ReadingList: LessonReading[] = [
  { title: 'BoE + Bundesbank — modern money creation', scope: '贷款—存款、支付、偿还、资产购买、事后融资与央行交易', reason: '用英格兰银行的账本入门，再用德国央行把单家银行流动性任务与体系货币创造接起来。', url: lesson309References[0].url, group: 'core', guide: '每读一例都画银行与非银行两张表；重点解释“可事后取得准备金”为什么不等于“融资无关”。', links: [{ label: 'BoE', url: lesson309References[0].url }, { label: 'Bundesbank', url: lesson309References[2].url }] },
  { title: 'IMF MFSMCG', scope: 'Ch. 3–7：部门、工具、存量流量、货币基础与广义货币', reason: '学习货币统计为何取决于发行部门、持有部门和合并边界。', url: lesson309References[4].url, group: 'core', guide: '同时打开更新页，明确 2016 手册与未来版本的身份。', links: [{ label: '现行完整手册', url: lesson309References[4].url }, { label: '更新进度', url: lesson309References[5].url }] },
  { title: '2025 SNA — Pre-edit', scope: '机构单位、四重记账与金融账户', reason: '从单方 T-account 走到交易对手闭合和部门账户。', url: lesson309References[6].url, group: 'core', guide: '保留 pre-edit/white-cover 标签；区分 transaction、revaluation 与 other volume。' },
  { title: 'PFMI + central bank money', scope: 'Principles 1、7–9；央行货币报告', reason: '理解支付指令、清算、净额、最终性和结算资产为何不同。', url: lesson309References[7].url, group: 'rules', guide: '原则不是国内法；真实案例再查 Fedwire 或 T2。', links: [{ label: 'PFMI', url: lesson309References[7].url }, { label: 'Central-bank money', url: lesson309References[8].url }] },
  { title: 'Fedwire + T2', scope: '服务说明与结算最终性', reason: '比较两个央行货币结算系统，而不把一个国家当作全球模板。', url: lesson309References[9].url, group: 'rules', guide: '记录账户资格、结算模式和运营时钟。', links: [{ label: 'Fedwire', url: lesson309References[9].url }, { label: 'T2', url: lesson309References[10].url }] },
  { title: 'Correspondent banking', scope: 'nostro/vostro、代理链与跨境支付风险', reason: '说明外币存款为什么不是本国准备金。', url: lesson309References[11].url, group: 'systems', guide: '区分报文、代理账户更新、FX 两条货币腿和最终结算。' },
  { title: 'Fed H.6 + ECB aggregates + BoE M4', scope: '三套货币总量方法页并读', reason: '训练对 broad money 做法域和版本护照。', url: lesson309References[13].url, group: 'rules', guide: '不要用 M1/M2/M3/M4 名称猜测组成。', links: [{ label: 'Fed H.6', url: lesson309References[13].url }, { label: 'ECB aggregates', url: lesson309References[15].url }, { label: 'BoE M4', url: lesson309References[56].url }] },
  { title: 'Money multiplier boundary', scope: 'Tobin、Carpenter–Demiralp、Jakab–Kumhof', reason: '把会计比率、银行行为与模型假设分开。', url: lesson309References[45].url, group: 'models', guide: '比较三篇文献的制度、样本和模型，避免把任何一篇写成普遍定律。', links: [{ label: 'Tobin', url: lesson309References[45].url }, { label: 'Fed evidence', url: lesson309References[46].url }, { label: 'Bank financing model', url: lesson309References[47].url }] },
  { title: 'Reserve regimes: United States and euro area', scope: '美国 0% 与欧元区 1% 当前规则', reason: '用并列制度直接打破固定准备金乘数的普遍化。', url: lesson309References[14].url, group: 'rules', guide: '每个数字都带法域、基数、生效日和访问日。', links: [{ label: 'Federal Reserve', url: lesson309References[14].url }, { label: 'ECB', url: lesson309References[16].url }] },
  { title: 'TGA and fiscal settlement', scope: 'Fed liabilities、2025 TGA note、Waller speech', reason: '理解税收、支出和发债如何在政府央行账户与准备金间转换。', url: lesson309References[21].url, group: 'systems', guide: '只把材料用于账户路径，不由此估计财政乘数。', links: [{ label: 'Fed liabilities', url: lesson309References[21].url }, { label: 'TGA note', url: lesson309References[23].url }, { label: 'Waller', url: lesson309References[22].url }] },
  { title: 'Basel risk capital and leverage', scope: 'RBC20、LEV20 与法律地位', reason: '区分风险加权资本与非风险加权后备约束。', url: lesson309References[26].url, group: 'rules', guide: '先计算国际最低值，再查国内实施；不得直接下合规结论。', links: [{ label: 'RBC20', url: lesson309References[26].url }, { label: 'LEV20', url: lesson309References[27].url }, { label: 'Legal status', url: lesson309References[50].url }] },
  { title: 'LCR / NSFR / Large exposures', scope: 'LCR20、NSF20、LEX20', reason: '把 30 日流动性、一年稳定融资和单一客户集中度分成三只尺子。', url: lesson309References[28].url, group: 'rules', guide: '每个 ratio 后都换算 headroom；不要把比例相加。', links: [{ label: 'LCR20', url: lesson309References[28].url }, { label: 'NSF20', url: lesson309References[29].url }, { label: 'LEX20', url: lesson309References[30].url }] },
  { title: 'Problem assets and ECL governance', scope: 'PAP10 与 PAP20', reason: '分开 past due、default、allowance、write-off 与 recovery。', url: lesson309References[31].url, group: 'rules', guide: '监管指引不替代 IFRS 或 US GAAP。', links: [{ label: 'PAP10', url: lesson309References[31].url }, { label: 'PAP20', url: lesson309References[32].url }] },
  { title: 'IFRS 9', scope: 'initial measurement、EIR、impairment、write-off、derecognition', reason: '理解会计净贷款变化为何不等于借款人还款。', url: lesson309References[35].url, group: 'rules', guide: '把 issued text 与 2024 PIR 分开记录。', links: [{ label: 'Standard page', url: lesson309References[35].url }, { label: 'Issued text', url: lesson309References[36].url }, { label: '2024 PIR', url: lesson309References[37].url }] },
  { title: 'US CECL', scope: 'FASB ASU 2016-13 与 2023 interagency statement', reason: '避免把 CECL 写成 IFRS 9 的三阶段模型。', url: lesson309References[38].url, group: 'rules', guide: '读完能说明 ACL、合同期和 write-off 分录。', links: [{ label: 'Interagency statement', url: lesson309References[38].url }, { label: 'ASU 2016-13', url: lesson309References[39].url }] },
  { title: 'Deposit insurance across jurisdictions', scope: 'IADI、FDIC、EU 与中国规则', reason: '把国际原则与国内覆盖、账户聚合和限额分开。', url: lesson309References[41].url, group: 'systems', guide: '任何数字必须附法域与有效日。', links: [{ label: 'IADI principles', url: lesson309References[41].url }, { label: 'FDIC FAQ', url: lesson309References[40].url }, { label: 'EU Directive', url: lesson309References[58].url }, { label: '中国条例', url: lesson309References[59].url }] },
  { title: 'Central-bank backstops', scope: 'Discount Window、Regulation A 与 ECB ELA', reason: '区分流动性贷款、资本与处置。', url: lesson309References[18].url, group: 'systems', guide: '逐项记录资格、抵押品、haircut、偿付能力和操作准备。', links: [{ label: 'Discount Window', url: lesson309References[18].url }, { label: 'Regulation A', url: lesson309References[43].url }, { label: 'ECB ELA', url: lesson309References[44].url }] },
  { title: 'Resolution', scope: 'FSB Key Attributes 2024', reason: '理解国际处置原则为何不是全球统一债权瀑布。', url: lesson309References[42].url, group: 'systems', guide: '每次应用都回到法律实体、国内法、合同和处置策略。' },
  { title: 'Non-bank credit and securitisation', scope: 'FSB monitoring、IFRS derecognition 与 Fed SR 99-37', reason: '区分信用创造、货币创造、资产出售和担保融资。', url: lesson309References[57].url, group: 'systems', guide: '不要由“证券化”名称直接推断贷款出表。', links: [{ label: 'FSB NBFI', url: lesson309References[57].url }, { label: 'IFRS 9', url: lesson309References[36].url }, { label: 'Fed SR 99-37', url: lesson309References[55].url }] },
  { title: 'Why banks exist', scope: 'Diamond 与 Holmström–Tirole', reason: '在账本机制之后理解监督、激励与可融资性。', url: lesson309References[48].url, group: 'models', guide: '模型资本不是 CET1；把理论变量和监管字段分别保存。', links: [{ label: 'Diamond', url: lesson309References[48].url }, { label: 'Holmström–Tirole', url: lesson309References[49].url }] },
];
