import type { LessonReading, LessonReference } from './types';

export const lesson324References: LessonReference[] = [
  {
    id: 1,
    authors: 'International Monetary Fund',
    year: '2011',
    accessedAt: '2026-09-16',
    title: 'Macroprudential Policy: An Organizing Framework',
    publication: 'IMF Policy Paper 2011/017, 14 March 2011; DOI 10.5089/9781498339162.007',
    url: 'https://www.elibrary.imf.org/view/journals/007/2011/017/007.2011.issue-017-en.xml',
    use: '编写者核读本地真 PDF 物理页7–12、22–28、30–32；支持系统视角、时间/横截面维度、合成谬误、工具分类、政策搭配与规则/裁量机制。不支持把物理页29复杂图表当数值证据，也不支持把2011制度例或当时Basel III提议写成2026现行法律。',
  },
  {
    id: 2,
    authors: 'International Monetary Fund, Financial Stability Board, and Bank for International Settlements',
    year: '2016',
    accessedAt: '2026-09-16',
    title: 'Elements of Effective Macroprudential Policies: Lessons from International Experience',
    publication: 'Joint report to the G20, 31 August 2016',
    url: 'https://www.imf.org/external/np/g20/pdf/2016/083116.pdf',
    use: '编写者核读本地真 PDF 全部22个物理页，包括附录与图表文字；支持三类中间目标、guided discretion、泄漏、反事实评估、压力期释放与跨境互惠。不支持宣称经验覆盖完整金融周期、存在一体适用方案或任一工具具有普适最优校准。',
  },
  {
    id: 3,
    authors: 'European Systemic Risk Board',
    year: '2013',
    accessedAt: '2026-09-16',
    title: 'Recommendation ESRB/2013/1 on intermediate objectives and instruments of macro⁠-⁠prudential policy',
    publication: 'ESRB Recommendation, 4 April 2013',
    url: 'https://www.esrb.europa.eu/pub/pdf/recommendations/2013/ESRB_2013_1.en.pdf',
    use: '编写者核读本地真 PDF 物理页1–14；支持最终目标到中间目标的映射，以及CCyB、部门资本、杠杆、LTV/LTI与流动性工具的不同近端靶点。不支持把2013欧盟建议与当时法律语境外推成2026全球统一规则。',
  },
  {
    id: 4,
    authors: 'Biljanovska et al.',
    year: '2023',
    accessedAt: '2026-09-16',
    title: 'Macroprudential Policy Effects: Evidence and Open Questions',
    publication: 'IMF Departmental Paper 2023/002; DOI 10.5089/9798400226304.087',
    url: 'https://www.imf.org/en/publications/departmental-papers-policy-papers/issues/2023/03/26/macroprudential-policy-effects-evidence-and-open-questions-527293',
    use: '编写者核读本地真 PDF 物理页12–36（文内页1–25）；支持leaning/resilience、政策内生性、短期代价、非线性、紧缩/放松不对称、缓冲释放及国内/跨境泄漏。不支持声称已核读后续全部技术附录或6000+估计数据库，也不把条件百分比当通用校准。',
  },
  {
    id: 5,
    authors: 'Basel Committee on Banking Supervision',
    year: '2024',
    accessedAt: '2026-09-16',
    title: 'Range of practices in implementing a positive neutral countercyclical capital buffer',
    publication: 'BCBS report, November 2024; landing page marked Current on 28 November 2024',
    url: 'https://www.bis.org/publications/range-practices-implementing-positive-neutral-countercyclical-capital-buffer',
    use: '本地官方真PDF positive-neutral-ccyb-official-retry.pdf 为24物理页、469140 B、SHA⁠-⁠256 09ebe0f53e5b94f0e401f10d54506257969bebd018af1e090274b0caca21944a；编写者核读物理页1–12并核对落地页身份。支持positive neutral CCyB是部分辖区自愿实践及其动机；不支持把2024表中比率当2026实时状态、全球强制规则或跨辖区因果证明。',
  },
  {
    id: 6,
    authors: 'Kuttner, Kenneth N., and Ilhyock Shim',
    year: '2013',
    accessedAt: '2026-09-16',
    title: 'Can non-interest rate policies stabilise housing markets? Evidence from a panel of 57 economies',
    publication: 'BIS Working Papers No 433, 15 November 2013',
    url: 'https://www.bis.org/publications/working-paper-433-can-non-interest-rate-policies-stabilise-housing-markets-evidence-panel-57-economies',
    use: '本地官方真PDF work433-official-pdf.pdf 为43物理页、374761 B、SHA⁠-⁠256 5a02ed6758a44ca84f45093fd893be3ed2001244e14cb4601112e7df44f42824；编写者只核读摘要与文内页1–2。支持利率作为房地产唯一工具可能具有总量代价及估计依赖设计；不支持声称全文已读或LTV/DSTI必然压低房价。',
  },
  {
    id: 7,
    authors: 'Committee on the Global Financial System',
    year: '2010',
    accessedAt: '2026-09-16',
    title: 'Macroprudential instruments and frameworks: a stocktaking of issues and experiences',
    publication: 'CGFS Papers No 38, 21 May 2010',
    url: 'https://www.bis.org/publications/cgfs-paper-38-macroprudential-instruments-and-frameworks-stocktaking-issues-and-experiences',
    use: '本地官方真PDF cgfs38-official-pdf.pdf 为37物理页、186965 B、SHA⁠-⁠256 a45b82caeac784ff8003f4530f5f8002fa449b145edbb55f77886abceea5c586；编写者只核读前言、摘要与出版说明，未读正文全部。支持早期盘点及制度依赖；不支持把谨慎经验措辞升级为严格因果效果。',
  },
  {
    id: 8,
    authors: 'Galati, Gabriele, and Richhild Moessner',
    year: '2011',
    accessedAt: '2026-09-16',
    title: 'Macroprudential policy – a literature review',
    publication: 'BIS Working Papers No 337, 2 February 2011',
    url: 'https://www.bis.org/publications/working-paper-337-macroprudential-policy-literature-review',
    use: '本地官方真PDF work337-official-pdf.pdf 为40物理页、220733 B、SHA⁠-⁠256 42b358e1c18f2a2d480af418f95dcc4b886c63c9581df044bcd695a0d3679b14；编写者只核读官方摘要、身份与40页范围。本课仅作术语史和延伸阅读入口；不支持声称全文已读或把综述转引当已核原始实证。',
  },
];

export const lesson324ReadingList: LessonReading[] = [
  {
    title: '阅读路线一：先定义系统风险，而不是先背工具名',
    scope: 'IMF 2011 本地真PDF物理页7–12；随后由读者补读未核范围',
    reason: '把最终目标、系统功能、时间维度、横截面维度与合成谬误分别写出。已读范围支持组织机制，但不等于2011制度例仍是2026法律。',
    url: lesson324References[0].url,
    group: 'core',
    links: [{ label: '官方DOI', url: 'https://doi.org/10.5089/9781498339162.007' }],
  },
  {
    title: '阅读路线二：从最终目标走到中间目标',
    scope: 'IMF–FSB–BIS 2016 全部22物理页',
    reason: '逐条比较韧性、顺周期与结构脆弱性，再看工具怎样命中不同边际。文件自己保留跨周期经验不足与无一体适用方案的边界。',
    url: lesson324References[1].url,
    group: 'core',
  },
  {
    title: '阅读路线三：把工具和分母对齐',
    scope: 'ESRB/2013/1 本地真PDF物理页1–14',
    reason: '对照资本、部门暴露、LTV、LTI与流动性工具的近端对象；旧欧盟建议用于机制映射，不作为当前全球合规手册。',
    url: lesson324References[2].url,
    group: 'rules',
  },
  {
    title: '阅读路线四：leaning与resilience分栏',
    scope: 'IMF 2023 本地真PDF物理页12–36（文内页1–25）',
    reason: '把繁荣期流量变化、存量分布调整和压力期缓冲使用放在不同时间轴；注意异质、不显著结果与短期代价。',
    url: lesson324References[3].url,
    group: 'evidence',
    links: [{ label: '官方DOI', url: 'https://doi.org/10.5089/9798400226304.087' }],
  },
  {
    title: '阅读路线五：建立、可用与释放不是同一件事',
    scope: 'IMF–FSB–BIS 2016缓冲段落与IMF 2023已读释放段落',
    reason: '逐项记录监管阈值、实际资本、可释放空间、银行行为和信贷结果，避免把降低要求写成凭空增加资本。',
    url: lesson324References[1].url,
    group: 'systems',
    links: [{ label: 'IMF 2023来源入口', url: lesson324References[3].url }],
  },
  {
    title: '阅读路线六：positive neutral CCyB只读成实践范围',
    scope: 'BCBS 2024本地官方真PDF物理页1–12；24页原件已归档，后12页未冒称已读',
    reason: '理解部分辖区为何在风险中性时预置可释放空间，同时保留自愿采用、比率时点和因果识别边界。',
    url: lesson324References[4].url,
    group: 'rules',
    links: [{ label: '官方PDF地址', url: 'https://www.bis.org/publications/range-practices-implementing-positive-neutral-countercyclical-capital-buffer.pdf' }],
  },
  {
    title: '阅读路线七：利率与房地产工具的识别警告',
    scope: 'Kuttner–Shim 2013本地官方真PDF摘要与文内页1–2；43页原件已归档，其余全文未核读',
    reason: '先比较研究问题与识别方法，再读完整结果。摘要中方法间差异提醒我们不能把任何一个估计改写成必然房价效果。',
    url: lesson324References[5].url,
    group: 'evidence',
    links: [{ label: '官方PDF地址', url: 'https://www.bis.org/publications/working-paper-433-can-non-interest-rate-policies-stabilise-housing-markets-evidence-panel-57-economies.pdf' }],
  },
  {
    title: '阅读路线八：把泄漏画成范围图',
    scope: 'IMF–FSB–BIS 2016全篇与IMF 2023已读范围的国内/跨境泄漏段落',
    reason: '分别登记银行、非银、分行、子公司、离岸直接借款与资产替代；未观测渠道保留unknown，不为了闭合写0。',
    url: lesson324References[1].url,
    group: 'systems',
    links: [{ label: 'IMF 2023来源入口', url: lesson324References[3].url }],
  },
  {
    title: '阅读路线九：早期盘点只作制度入口',
    scope: 'CGFS 38本地官方真PDF前言、摘要和出版说明；37页原件已归档，正文尚未完整核读',
    reason: '用它列出制度与市场结构问题，再回到更新的原始规则与数据。谨慎措辞不是因果证书；真PDF已归档也不扩大本人实际阅读范围。',
    url: lesson324References[6].url,
    group: 'systems',
    links: [{ label: '官方PDF地址', url: 'https://www.bis.org/publications/cgfs-paper-38-macroprudential-instruments-and-frameworks-stocktaking-issues-and-experiences.pdf' }],
  },
  {
    title: '阅读路线十：术语史不能替代原始证据',
    scope: 'Galati–Moessner 2011本地官方真PDF摘要、身份与40页范围；全文尚未核读',
    reason: '把综述用于定位问题和文献，再逐项取得原文、数据、政策时钟和识别设计；不把综述转引登记成已核原典。',
    url: lesson324References[7].url,
    group: 'models',
    links: [{ label: '官方PDF地址', url: 'https://www.bis.org/publications/working-paper-337-macroprudential-policy-literature-review.pdf' }],
  },
];
