import type { LessonReading, LessonReference } from './types';

export const lesson409References = [
  {
    id: 1,
    authors: 'Robert A. Mundell',
    year: '1963',
    accessedAt: '2026-09-22',
    title: 'Capital Mobility and Stabilization Policy Under Fixed and Flexible Exchange Rates',
    publication: 'Canadian Journal of Economics and Political Science 29(4), 475–485 · DOI 10.2307/139336',
    url: 'https://www.cambridge.org/core/journals/canadian-journal-of-economics-and-political-science-revue-canadienne-de-economiques-et-science-politique/article/abs/capital-mobility-and-stabilization-policy-under-fixed-and-flexible-exchange-rates/1C0D6743C46645F447F2338146CA61B9',
    use: '支持高资本流动、小型开放经济与固定／浮动汇率下政策传导的经典极端基准；不支持把完全资本流动、即时调整或利率完全相等当成所有现实经济体的事实。',
  },
  {
    id: 2,
    authors: 'J. Marcus Fleming',
    year: '1962',
    accessedAt: '2026-09-22',
    title: 'Domestic Financial Policies Under Fixed and Under Floating Exchange Rates',
    publication: 'IMF Staff Papers 9(3), 369–380 · DOI 10.2307/3866091',
    url: 'https://www.elibrary.imf.org/view/journals/024/1962/003/article-A004-en.xml',
    use: '支持汇率制度会改变货币与财政政策相对传导的经典开放经济逻辑；不支持脱离模型假设给现实政策乘数或普适制度排名。',
  },
  {
    id: 3,
    authors: 'Maurice Obstfeld, Jay C. Shambaugh and Alan M. Taylor',
    year: '2005',
    accessedAt: '2026-09-22',
    title: 'The Trilemma in History: Tradeoffs among Exchange Rates, Monetary Policies, and Capital Mobility',
    publication: 'Review of Economics and Statistics 87(3), 423–438 · DOI 10.1162/0034653054638300',
    url: 'https://doi.org/10.1162/0034653054638300',
    use: '支持以历史制度与利率联动检验三元权衡，并显示固定汇率下基准国利率传导更强；不支持把相关联动直接解释为单一外生冲击或把三个维度处理成无灰度开关。',
  },
  {
    id: 4,
    authors: 'Jay C. Shambaugh',
    year: '2004',
    accessedAt: '2026-09-22',
    title: 'The Effect of Fixed Exchange Rates on Monetary Policy',
    publication: 'Quarterly Journal of Economics 119(1), 301–352 · DOI 10.1162/003355304772839605',
    url: 'https://academic.oup.com/qje/article-abstract/119/1/301/1876076',
    use: '支持用事实汇率行为、基准货币与本外利率关系研究政策利率自主性；不支持把所有共同利率变动都判为丧失自主，亦不测量完整金融条件、产出稳定或福利。',
  },
  {
    id: 5,
    authors: 'Michael W. Klein and Jay C. Shambaugh',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'Rounding the Corners of the Policy Trilemma: Sources of Monetary Policy Autonomy',
    publication: 'American Economic Journal: Macroeconomics 7(4), 33–66 · DOI 10.1257/mac.20130237',
    url: 'https://www.aeaweb.org/articles?id=10.1257%2Fmac.20130237',
    use: '支持制度选择是连续边界、适度汇率灵活性可带来一定自主而有限资本管制未必足够；不支持任何特定经济体只需轻微调整即可获得完整自主。',
  },
  {
    id: 6,
    authors: 'Hélène Rey',
    year: '2015; revised 2018',
    accessedAt: '2026-09-22',
    title: 'Dilemma not Trilemma: The Global Financial Cycle and Monetary Policy Independence',
    publication: 'NBER Working Paper No 21162, issued May 2015, revised February 2018 · DOI 10.3386/w21162',
    url: 'https://www.nber.org/papers/w21162',
    use: '支持Rey（2015）的原始强命题：资本自由流动下，全球金融周期可能不因汇率制度而消失并约束国家货币政策；也支持资本流、风险资产、信用与杠杆共同波动的证据。不支持把统计全球因子自动识别为美国货币政策冲击，也不支持把该工作论文单独升级为“汇率制度对贸易、通胀、资产负债表或全部政策结果均无关”的普适事实；本课较窄的“浮动下广义金融条件仍可共振”须明确标为结果分层后的综合命题。',
  },
  {
    id: 7,
    authors: 'Silvia Miranda-Agrippino and Hélène Rey',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'U.S. Monetary Policy and the Global Financial Cycle',
    publication: 'Review of Economic Studies 87(6), 2754–2776 · DOI 10.1093/restud/rdaa019',
    url: 'https://academic.oup.com/restud/article/87/6/2754/5834728',
    use: '支持经高频工具识别的美国货币紧缩与全球风险资产、信用、杠杆和资本流收缩相联系；不支持对任意时期、资产或经济体移植同一脉冲，也不等于浮动汇率没有任何缓冲。',
  },
  {
    id: 8,
    authors: 'Maurice Obstfeld',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'Trilemmas and Trade-offs: Living with Financial Globalisation',
    publication: 'BIS Working Papers No 480',
    url: 'https://www.bis.org/publications/working-paper-480-trilemmas-and-trade-offs-living-financial-globalisation',
    use: '支持在金融全球化下区分经典货币三元权衡与金融稳定的额外权衡；不支持将所有约束压成一个二选一命题或由单一制度标签推出政策福利。',
  },
  {
    id: 9,
    authors: 'Georgios Georgiadis and Feng Zhu',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Monetary Policy Spillovers, Capital Controls and Exchange Rate Flexibility, and the Financial Channel of Exchange Rates',
    publication: 'BIS Working Papers No 797',
    url: 'https://www.bis.org/publications/working-paper-797-monetary-policy-spillovers-capital-controls-and-exchange-rate-flexibility-and-financial-channel-exchange-rates',
    use: '支持汇率灵活性和资本限制降低本地政策利率对基准国利率的敏感性，同时外币负债可使政策制定者不愿完全使用潜在自主空间；不支持把反应函数系数当作制度结构常数或政策效果。',
  },
  {
    id: 10,
    authors: 'Carlos Caceres, Yan Carrière-Swallow and Bertrand Gruss',
    year: '2016',
    accessedAt: '2026-09-22',
    title: 'Global Financial Conditions and Monetary Policy Autonomy',
    publication: 'IMF Working Paper 16/108 · DOI 10.5089/9781484382066.001',
    url: 'https://www.imf.org/en/publications/wp/issues/2016/12/31/global-financial-conditions-and-monetary-policy-autonomy-43943',
    use: '支持剔除同步国内基本面反应后重新评估浮动经济体的政策利率自主；不支持把工作论文结果当作IMF正式政策或把估计方法消除所有遗漏变量。',
  },
  {
    id: 11,
    authors: 'Christian Friedrich, Pierre Guérin and Danilo Leiva-Leon',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'Monetary Policy Independence and the Strength of the Global Financial Cycle',
    publication: 'Bank of Canada Staff Working Paper 2020-25 · DOI 10.34989/swp-2020-25',
    url: 'https://www.bankofcanada.ca/2020/06/staff-working-paper-2020-25/',
    use: '支持其61国跨境股票流样本中，全球金融周期强度会改变央行政策率对外生通胀缺口变化的反应，并显示资本管制、宏观审慎和更灵活汇率制度与更高货币政策独立性相关；不支持把跨国平均结果或工具相关性解释为某国某时点的已识别处理效果。',
  },
  {
    id: 12,
    authors: 'Joshua Aizenman, Menzie D. Chinn and Hiro Ito',
    year: '2010',
    accessedAt: '2026-09-22',
    title: 'The Emerging Global Financial Architecture: Tracing and Evaluating New Patterns of the Trilemma Configuration',
    publication: 'Journal of International Money and Finance 29(4), 615–641 · DOI 10.1016/j.jimonfin.2010.01.005',
    url: 'https://doi.org/10.1016/j.jimonfin.2010.01.005',
    use: '支持把货币独立、汇率稳定与金融开放量化为连续指数并分析储备配置；不支持把构造指数当作直接观测真值或由相关性给出最优政策组合。',
  },
  {
    id: 13,
    authors: 'Joshua Aizenman, Menzie D. Chinn and Hiro Ito',
    year: '2021 page update',
    accessedAt: '2026-09-22',
    title: 'The Trilemma Indexes',
    publication: 'Portland State University data documentation and downloads · page updated 31 August 2021',
    url: 'https://web.pdx.edu/~ito/trilemma_indexes.htm',
    use: '支持三元指数的数据文件、变量说明、复现程序、覆盖范围与页面版本核对；该页记录MI和ERS至2020、KAOPEN至2019，并指定Aizenman、Chinn和Ito为数据来源作者。不支持把2026访问日倒装成2026数据vintage、把构造指数当作实时制度真值，或用指数替代逐项资本限制、政策率和汇率制度记录。',
  },
  {
    id: 14,
    authors: 'Menzie D. Chinn and Hiro Ito',
    year: '2006; dataset maintained subsequently',
    accessedAt: '2026-09-22',
    title: 'What Matters for Financial Development? Capital Controls, Institutions, and Interactions',
    publication: 'Journal of Development Economics 81(1), 163–192 · DOI 10.1016/j.jdeveco.2005.05.010; KAOPEN data page',
    url: 'https://web.pdx.edu/~ito/Chinn-Ito_website.htm',
    use: '支持基于IMF AREAER法定限制构造资本账户开放指数与下载版本；不支持将de jure开放等同实际跨境头寸、执行强度或逐工具可兑换性。',
  },
  {
    id: 15,
    authors: 'Ethan Ilzetzki, Carmen M. Reinhart and Kenneth S. Rogoff',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Exchange Arrangements Entering the Twenty-First Century: Which Anchor Will Hold?',
    publication: 'Quarterly Journal of Economics 134(2), 599–646 · DOI 10.1093/qje/qjy033',
    url: 'https://academic.oup.com/qje/article-abstract/134/2/599/5274128',
    use: '支持以事实汇率行为、锚货币和外汇限制重构制度历史，并显示申报与实际安排可不同；不支持把年度分类当作日内政策承诺或自动解释制度选择的因果。',
  },
  {
    id: 16,
    authors: 'International Monetary Fund, Monetary and Capital Markets Department',
    year: '2024 edition',
    accessedAt: '2026-09-22',
    title: 'Annual Report on Exchange Arrangements and Exchange Restrictions 2023',
    publication: 'AREAER · DOI 10.5089/9798400260391.012',
    url: 'https://www.elibrary.imf.org/display/book/9798400260391/9798400260391.xml',
    use: '支持成员汇率安排、货币框架、资本交易与支付限制的制度字段；不支持将法律文本等同执行强度、事实金融开放、实时政策意图或福利效果。',
  },
  {
    id: 17,
    authors: 'Gita Gopinath, Emine Boz, Camila Casas, Federico J. Díez, Pierre-Olivier Gourinchas and Mikkel Plagborg-Møller',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'Dominant Currency Paradigm',
    publication: 'American Economic Review 110(3), 677–719 · DOI 10.1257/aer.20171201',
    url: 'https://www.aeaweb.org/articles/pdf/doi/10.1257/aer.20171201',
    use: '支持主导货币计价、进口投入与价格刚性削弱双边汇率的短期支出转换，并强化美元汇率的重要性；不支持浮动汇率永远无效或把论文平均弹性移植到任意国家。',
  },
  {
    id: 18,
    authors: 'Valentina Bruno and Hyun Song Shin',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'Capital Flows and the Risk-taking Channel of Monetary Policy',
    publication: 'Journal of Monetary Economics 71, 119–132 · DOI 10.1016/j.jmoneco.2014.11.011',
    url: 'https://doi.org/10.1016/j.jmoneco.2014.11.011',
    use: '支持全球银行杠杆、美元条件与跨境资本流的风险承担渠道；不支持银行渠道代表全部资本流或由共动自动证明单一美国政策因果。',
  },
  {
    id: 19,
    authors: 'International Monetary Fund',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'Toward an Integrated Policy Framework',
    publication: 'IMF Policy Paper 2020/046 · DOI 10.5089/9781513558769.007',
    url: 'https://www.imf.org/en/publications/policy-papers/issues/2020/10/08/toward-an-integrated-policy-framework-49813',
    use: '支持把货币政策、汇率灵活性、外汇干预、宏观审慎与资本流管理放在冲击—摩擦—工具框架中联合评估；不支持“工具越多越好”、维护失调汇率或忽略必要宏观调整。',
  },
  {
    id: 20,
    authors: 'Suman S. Basu, Emine Boz, Gita Gopinath, Francisco Roch and Filiz D. Unsal',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'A Conceptual Model for the Integrated Policy Framework',
    publication: 'IMF Working Paper 20/121 · DOI 10.5089/9781513549729.001',
    url: 'https://www.imf.org/en/publications/wp/issues/2020/07/07/a-conceptual-model-for-the-integrated-policy-framework-49558',
    use: '支持在主导货币计价、外币错配、外部借款约束与浅层外汇市场下联合建模政策工具；不支持把校准模型最优解当作具体国家的直接处方或IMF董事会正式政策。',
  },
  {
    id: 21,
    authors: 'International Monetary Fund',
    year: '2022',
    accessedAt: '2026-09-22',
    title: 'Review of the Institutional View on the Liberalization and Management of Capital Flows',
    publication: 'IMF Policy Paper 2022/008 · DOI 10.5089/9798400204593.007',
    url: 'https://www.imf.org/en/publications/policy-papers/issues/2022/03/29/review-of-the-institutional-view-on-the-liberalization-and-management-of-capital-flows-515883',
    use: '支持资本流收益、风险、CFM适用条件、执行成本与“不得替代必要宏观调整”的正式政策边界；不支持把CFM视为无成本永久隔离器或用于竞争性操纵贸易条件。',
  },
  {
    id: 22,
    authors: 'International Monetary Fund',
    year: '2023',
    accessedAt: '2026-09-22',
    title: 'Integrated Policy Framework—Principles for the Use of Foreign Exchange Intervention',
    publication: 'IMF Policy Paper 2023/061',
    url: 'https://www.imf.org/-/media/files/publications/pp/2023/english/ppea2023061.pdf',
    use: '支持在浅层／暂时失灵的外汇市场、未对冲币种错配或通胀预期失锚风险下评估FXI，并说明保障条件；不支持以干预长期维持基本面失调汇率、保证价格路径或无视储备与资产负债表成本。',
  },
  {
    id: 23,
    authors: 'Bank for International Settlements',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Monetary Policy Frameworks in EMEs: Inflation Targeting, the Exchange Rate and Financial Stability',
    publication: 'BIS Annual Economic Report 2019, Chapter II',
    url: 'https://www.bis.org/publications/aer-2019/monetary-policy-frameworks-emes-inflation-targeting-exchange-rate-financial-stability',
    use: '支持新兴经济体在通胀目标、汇率与金融稳定之间使用利率、FXI及资产负债表工具的现实权衡；不支持存在唯一EME框架或把章节判断当作每国已识别福利结论。',
  },
  {
    id: 24,
    authors: 'Paolo Cavallino',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'Capital Flows and Foreign Exchange Intervention',
    publication: 'American Economic Journal: Macroeconomics 11(2), 127–170 · DOI 10.1257/mac.20160065',
    url: 'https://doi.org/10.1257/mac.20160065',
    use: '支持在资本流冲击与金融摩擦模型中分析FXI的状态依赖作用；不支持任何等量储备变化必然产生固定汇率或福利效果。',
  },
  {
    id: 25,
    authors: 'Xavier Gabaix and Matteo Maggiori',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'International Liquidity and Exchange Rate Dynamics',
    publication: 'Quarterly Journal of Economics 130(3), 1369–1420 · DOI 10.1093/qje/qjv016',
    url: 'https://doi.org/10.1093/qje/qjv016',
    use: '支持有限中介风险承载下资产供需与汇率、干预的组合平衡渠道；不支持直接观测现实中介约束或由模型推出无条件有效干预。',
  },
  {
    id: 26,
    authors: 'Pierre-Richard Agénor, Timothy Jackson and Luiz Awazu Pereira da Silva',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'Foreign Exchange Intervention and Financial Stability',
    publication: 'BIS Working Papers No 889',
    url: 'https://www.bis.org/publications/working-paper-889-foreign-exchange-intervention-and-financial-stability',
    use: '支持把冲销干预、银行资产组合、冲销成本与金融稳定纳入同一模型；不支持“冲销后没有任何国内影响”或对现实银行组合效应的无条件定量判断。',
  },
  {
    id: 27,
    authors: 'Javier Bianchi',
    year: '2011',
    accessedAt: '2026-09-22',
    title: 'Overborrowing and Systemic Externalities in the Business Cycle',
    publication: 'American Economic Review 101(7), 3400–3426 · DOI 10.1257/aer.101.7.3400',
    url: 'https://pubs.aeaweb.org/doi/10.1257/aer.101.7.3400',
    use: '支持抵押价格外部性可使私人借款超过约束有效水平并为事前审慎工具提供理论动机；不支持现实经济体必然过度借款、固定税率或危机概率。',
  },
  {
    id: 28,
    authors: 'Kristin J. Forbes, Marcel Fratzscher and Roland Straub',
    year: '2015',
    accessedAt: '2026-09-22',
    title: 'Capital-flow Management Measures: What Are They Good For?',
    publication: 'Journal of International Economics 96(S1), S76–S97 · DOI 10.1016/j.jinteco.2014.11.004',
    url: 'https://doi.org/10.1016/j.jinteco.2014.11.004',
    use: '支持资本流管理措施对汇率、资本流组成与金融脆弱性的效果可能因措施和情景不同；不支持用单一总量结论证明CFM普遍有效、无效或无绕道。',
  },
  {
    id: 29,
    authors: 'Michael W. Klein',
    year: '2012',
    accessedAt: '2026-09-22',
    title: 'Capital Controls: Gates versus Walls',
    publication: 'Brookings Papers on Economic Activity, Fall 2012, 317–355',
    url: 'https://www.brookings.edu/wp-content/uploads/2012/09/2012b_Klein.pdf',
    use: '支持区分临时可开关的gates与长期广覆盖walls并比较其宏观关联；不支持把法定措施存在等同执行、即时阻断全部流量或因果福利改进。',
  },
  {
    id: 30,
    authors: 'Charles Engel',
    year: '2016',
    accessedAt: '2026-09-22',
    title: 'Exchange Rates, Interest Rates, and the Risk Premium',
    publication: 'American Economic Review 106(2), 436–474 · DOI 10.1257/aer.20121365',
    url: 'https://www.aeaweb.org/articles?id=10.1257/aer.20121365',
    use: '支持利差、预期汇率变化与风险溢价的资产定价分解及其经验难题；不支持把UIP写成无风险套利恒等式、把残差全称风险溢价或由单次偏离预测资本流。',
  },
  {
    id: 31,
    authors: 'Peter Isard',
    year: '2006',
    accessedAt: '2026-09-22',
    title: 'Uncovered Interest Parity',
    publication: 'IMF Working Paper 2006/096 · DOI 10.5089/9781451863567.001',
    url: 'https://www.elibrary.imf.org/view/journals/001/2006/096/001.2006.issue-096-en.xml',
    use: '支持UIP概念史、经验有效性证据及短期限挑战的综述；不支持把工作论文当作IMF正式政策、把UIP写成无条件事实，或用事后实现汇率无条件替代决策时预期。',
  },
  {
    id: 32,
    authors: 'Claudio Borio, Robert N. McCauley, Patrick McGuire and Vladyslav Sushko',
    year: '2016',
    accessedAt: '2026-09-22',
    title: 'Covered Interest Parity Lost: Understanding the Cross-currency Basis',
    publication: 'BIS Quarterly Review, September 2016',
    url: 'https://www.bis.org/publications/qr-201609/covered-interest-parity-lost-understanding-cross-currency-basis',
    use: '支持CIP无套利基准、危机后cross-currency basis与套保需求／银行资产负债表约束；不支持把basis视为单一资本管制指标或无成本可实现利润。',
  },
  {
    id: 33,
    authors: 'Wenxin Du, Alexander Tepper and Adrien Verdelhan',
    year: '2018',
    accessedAt: '2026-09-22',
    title: 'Deviations from Covered Interest Rate Parity',
    publication: 'Journal of Finance 73(3), 915–957 · DOI 10.1111/jofi.12620',
    url: 'https://doi.org/10.1111/jofi.12620',
    use: '支持后危机CIP偏离的系统证据及资产负债表成本解释；不支持跨币种、抵押、期限和交易成本不匹配的直接比较，或把平均basis移植到单笔融资。',
  },
  {
    id: 34,
    authors: 'Eugenio Cerutti, Stijn Claessens and Andrew K. Rose',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'How Important Is the Global Financial Cycle? Evidence from Capital Flows',
    publication: 'IMF Economic Review 67(1), 24–60 · DOI 10.1057/s41308-019-00073-5',
    url: 'https://doi.org/10.1057/s41308-019-00073-5',
    use: '支持全球变量与共同因子对跨国资本流的平均解释力存在明显上限和异质性；不支持据平均上限否认尾部、资产价格或高暴露经济体的强传导。',
  },
  {
    id: 35,
    authors: 'Maurice Obstfeld, Jonathan D. Ostry and Mahvash S. Qureshi',
    year: '2019',
    accessedAt: '2026-09-22',
    title: 'A Tie That Binds: Revisiting the Trilemma in Emerging Market Economies',
    publication: 'Review of Economics and Statistics 101(2), 279–293 · DOI 10.1162/rest_a_00740',
    url: 'https://doi.org/10.1162/rest_a_00740',
    use: '支持新兴市场中较固定制度对全球金融冲击的信贷、房价与杠杆传导更强，汇率灵活性仍可提供部分缓冲；不支持完全隔离或最优制度结论。',
  },
  {
    id: 36,
    authors: 'Xuehui Han and Shang-Jin Wei',
    year: '2018',
    accessedAt: '2026-09-22',
    title: 'International Transmissions of Monetary Shocks: Between a Trilemma and a Dilemma',
    publication: 'Journal of International Economics 110, 205–219 · DOI 10.1016/j.jinteco.2017.11.005',
    url: 'https://doi.org/10.1016/j.jinteco.2017.11.005',
    use: '支持其样本与设计下外部紧缩／宽松传导的不对称及介于Trilemma与Dilemma之间的结果；不支持把“2.5-lemma”当作新的普适制度定律。',
  },
  {
    id: 37,
    authors: 'Guillermo A. Calvo and Carmen M. Reinhart',
    year: '2002',
    accessedAt: '2026-09-22',
    title: 'Fear of Floating',
    publication: 'Quarterly Journal of Economics 117(2), 379–408 · DOI 10.1162/003355302753650274',
    url: 'https://doi.org/10.1162/003355302753650274',
    use: '支持宣布浮动与实际汇率／储备／利率管理行为可能分离；不支持把任何FXI、低汇率波动或政策率反应一律分类为peg。',
  },
  {
    id: 38,
    authors: 'International Monetary Fund Statistics Department',
    year: '2016',
    accessedAt: '2026-09-22',
    title: 'Monetary and Financial Statistics Manual and Compilation Guide',
    publication: 'IMF Manual · DOI 10.5089/9781513579191.069',
    url: 'https://www.imf.org/en/publications/manuals-guides/issues/2018/09/21/monetary-and-financial-statistics-manual-and-compilation-guide-43001',
    use: '支持央行与存款公司资产负债表、货币基础、存量—流量和估值的统计口径；不支持把简化的NFA/NDA身份等同广义货币或政策因果。',
  },
  {
    id: 39,
    authors: 'International Monetary Fund Statistics Department',
    year: '2013',
    accessedAt: '2026-09-22',
    title: 'International Reserves and Foreign Currency Liquidity: Guidelines for a Data Template',
    publication: 'IMF Guidelines',
    url: 'https://www.imf.org/en/publications/manuals-guides/issues/2016/12/31/international-reserves-and-foreign-currency-liquidity-guidelines-for-a-data-template-40117',
    use: '支持储备资产、预定／或有短期净流出、衍生品与外汇流动性模板；不支持headline reserves等于可用干预容量或私人部门可得现金。',
  },
  {
    id: 40,
    authors: 'Refet S. Gürkaynak, Brian Sack and Eric Swanson',
    year: '2005',
    accessedAt: '2026-09-22',
    title: 'Do Actions Speak Louder Than Words? The Response of Asset Prices to Monetary Policy Actions and Statements',
    publication: 'International Journal of Central Banking 1(1); Federal Reserve FEDS 2004-66',
    url: 'https://www.federalreserve.gov/pubs/feds/2004/200466/200466pap.pdf',
    use: '支持窄窗政策意外需区分当前目标与未来路径因子；不支持把特定美国市场因子直接当作所有央行、资产或国家的统一shock。',
  },
  {
    id: 41,
    authors: 'Marek Jarociński and Peter Karadi',
    year: '2020',
    accessedAt: '2026-09-22',
    title: 'Deconstructing Monetary Policy Surprises—The Role of Information Shocks',
    publication: 'American Economic Journal: Macroeconomics 12(2), 1–43 · DOI 10.1257/mac.20180090',
    url: 'https://doi.org/10.1257/mac.20180090',
    use: '支持区分纯货币意外与央行信息shock及其不同资产价格符号；不支持把符号限制当直接观测真值或无条件外推到所有事件。',
  },
  {
    id: 42,
    authors: 'International Monetary Fund',
    year: '2025 pre-edited white-cover version',
    accessedAt: '2026-09-22',
    title: 'Integrated Balance of Payments and International Investment Position Manual, Seventh Edition (BPM7)',
    publication: 'International statistical manual, pre-edited version',
    url: 'https://www.imf.org/-/media/files/data/statistics/bpm6/draft-bpm7-wcv.pdf',
    use: '支持交易、头寸、重估、其他数量变化、储备与功能类别的最新统计框架；不支持把pre-edited文本称最终实施口径或由统计分类推出政策因果。',
  },
] as const satisfies readonly LessonReference[];

export type PolicyAutonomySourceId = (typeof lesson409References)[number]['id'];

export const policyAutonomyEvidenceGroups = [
  {
    key: 'classic-benchmark',
    title: '经典基准：三元权衡是条件命题，不是政治口号',
    supports: '在高资本流动、可信固定汇率与给定基准利率的经典小型开放经济中，持续偏离需要由汇率预期、风险／分割楔子或储备与资产负债表调整吸收。',
    doesNotSupport: '三个角是现实中的纯0/1变量，或任何短期利差都会立即击穿制度。',
    sourceIds: [1, 2, 3, 4, 5, 30, 31, 32, 33] as const,
  },
  {
    key: 'measurement',
    title: '制度、外部头寸与储备测量：构造变量和会计对象必须分开',
    supports: 'Refs 12–16与37支持用不同构造变量记录货币独立、汇率稳定、资本开放以及de jure／de facto制度，并要求保存锚货币、算法、覆盖期和vintage；refs 38、39与42支持把央行／金融部门资产负债表、储备资产、预定与或有外币流出、交易、估值和其他数量变化分栏。它们共同支持版本化测量护照，而不是一只总“自主性分数”。',
    doesNotSupport: '任何年度制度标签或构造指数就是实时制度真值，法定开放等于具体路线上的事实可执行性，储备存量或变动等于可用FXI容量／等额干预，或统计分类本身识别了政策冲击、处理效果与福利。',
    sourceIds: [12, 13, 14, 15, 16, 37, 38, 39, 42] as const,
  },
  {
    key: 'dilemma',
    title: '全球金融周期：政策率自主不等于金融条件隔离',
    supports: '全球风险资产、信用、杠杆与资本流存在共同波动；美国货币冲击可通过中介与美元渠道传播到浮动经济体。',
    doesNotSupport: '浮动汇率完全无用、所有共动都来自美国政策，或Dilemma逻辑已经否定经典三元约束。',
    sourceIds: [6, 7, 8, 10, 18, 34, 35, 36, 40, 41] as const,
  },
  {
    key: 'buffers',
    title: '缓冲仍存在：汇率灵活性与资本限制可改变敏感度',
    supports: '更灵活的汇率或更强资本分割通常与较低的基准国利率传导相关，但外币负债和金融脆弱性可能使政策制定者少用这份空间。',
    doesNotSupport: '浮动保证完全自主、有限管制足以隔离，或低政策率共动等于宏观稳定成功。',
    sourceIds: [4, 5, 9, 10, 11, 35, 36, 37] as const,
  },
  {
    key: 'exchange-rate-channels',
    title: '汇率双重作用：贸易缓冲器也可能是金融放大器',
    supports: '主导货币计价、外币错配、银行杠杆和有限中介容量会改变贬值的贸易、通胀与资产负债表作用。',
    doesNotSupport: '贬值在任何状态都扩张或收缩，或一个国家层面净外币头寸足以描述全部主体。',
    sourceIds: [9, 17, 18, 20, 23, 25] as const,
  },
  {
    key: 'fxi',
    title: 'FXI与冲销：改变风险分配，不是免费的第四个角',
    supports: '在市场浅薄、风险承载受限或错配约束下，FXI可通过组合平衡、流动性与信号等通道作用；冲销只中和声明的准备金／短率腿。',
    doesNotSupport: '储备变化等于干预、冲销后无国内影响、FXI保证目标汇率或没有财政与资产负债表成本。',
    sourceIds: [19, 22, 23, 24, 25, 26, 38, 39, 42] as const,
  },
  {
    key: 'cfm-mpm',
    title: 'CFM／MPM：工具必须对准外部性、范围与绕道',
    supports: '当资本流放大错配、杠杆或抵押外部性时，事前审慎或特定CFM可能有作用；法律范围、期限与执行决定真实楔子。',
    doesNotSupport: '管制无成本、永久有效、可以替代必要宏观调整，或所有以居民身份区分的措施都能处理同一风险。',
    sourceIds: [19, 20, 21, 27, 28, 29] as const,
  },
  {
    key: 'integrated-policy',
    title: '综合政策：先识别冲击与摩擦，再谈工具组合和福利',
    supports: '利率、汇率灵活性、FXI、MPM与CFM应按冲击、市场深度、计价货币、错配、预期锚定与制度能力联合评估。',
    doesNotSupport: '任何多工具组合天然优于单工具、工具可以无限叠加，或模型最优等于现实执行最优。',
    sourceIds: [19, 20, 21, 22, 23] as const,
  },
] as const;

export const lesson409ReadingList = [
  {
    title: 'Mundell (1963) · 先读假设，再读结论',
    scope: 'pp. 475–485；重点看perfect capital mobility如何限定问题。',
    reason: '建立经典基准，同时看到作者本人明确称极端假设会夸大约束。',
    url: lesson409References[0].url,
    group: 'core',
    guide: '第一遍只圈出汇率制度、资本流动和货币操作的定义；不要先背政策口诀。',
  },
  {
    title: 'Obstfeld, Shambaugh & Taylor (2005) · 历史中的三元权衡',
    scope: '摘要、制度分类、利率联动检验与结论。',
    reason: '把黑板命题转成可观测制度与经验设计。',
    url: lesson409References[2].url,
    group: 'core',
    guide: '记录因变量、锚货币、peg定义和资本控制；区分历史事实与识别假设。',
  },
  {
    title: 'Rey (2015) + Obstfeld (2015) · Dilemma与trade-offs配对读',
    scope: '先读Rey的全球金融周期证据，再读Obstfeld对多个自主维度的回应。',
    reason: '避免把学术争论误写成二选一口号。',
    url: lesson409References[5].url,
    group: 'core',
    guide: '分别写下“政策率可设”“金融条件可控”“宏观目标可稳定”三种命题。',
    links: [{ label: '配对阅读 · Obstfeld BIS 480', url: lesson409References[7].url }],
  },
  {
    title: 'Klein & Shambaugh (2015) · 圆角而非三只开关',
    scope: '制度连续性、适度浮动与部分资本管制的经验结果。',
    reason: '理解现实配置为何位于三角形内部，并训练不把小幅制度变化夸成完整自主。',
    url: lesson409References[4].url,
    group: 'models',
    guide: '先核对论文怎样定义autonomy，再看partial controls与limited flexibility的非对称结果。',
  },
  {
    title: 'Basu et al. (2020) · Integrated Policy Framework模型',
    scope: '摘要、摩擦清单、主要命题和政策交互；证明可选读。',
    reason: '把主导货币、币种错配、外部借款约束和市场深度放入同一政策分配框架。',
    url: lesson409References[19].url,
    group: 'models',
    guide: '每读一项工具，都写出它针对的摩擦、状态变量与不应使用的情形。',
  },
  {
    title: 'Gabaix & Maggiori (2015) · 有限中介与汇率',
    scope: '模型直觉、风险承载与资产供需；技术证明按需。',
    reason: '理解为什么冲销FXI仍可能通过组合平衡作用，也理解为何效果状态依赖。',
    url: lesson409References[24].url,
    group: 'models',
    guide: '先画私人中介与央行之间的风险转移，再读均衡条件。',
  },
  {
    title: 'Miranda-Agrippino & Rey (2020) · 全球金融周期识别',
    scope: '因子、外部工具、脉冲响应及局限。',
    reason: '训练把共同因子、美国政策冲击和跨国结果三层分开。',
    url: lesson409References[6].url,
    group: 'evidence',
    guide: '记录识别工具捕捉什么、排除什么，以及结果不能自动回答的政策反事实。',
  },
  {
    title: 'Georgiadis & Zhu (2019) · 三元约束与金融汇率渠道',
    scope: '反应函数、外币暴露交互与结论。',
    reason: '同一设计中看到“浮动提供空间”与“错配使央行少用空间”如何同时成立。',
    url: lesson409References[8].url,
    group: 'evidence',
    guide: '把潜在自主、实际政策选择和最终金融稳定结果分成三栏。',
  },
  {
    title: 'Aizenman–Chinn–Ito索引 + AREAER · 数据护照',
    scope: '三元指数下载说明、KAOPEN来源与IMF法定制度记录。',
    reason: '建立de jure／de facto、年度／事件时钟与版本治理。',
    url: lesson409References[12].url,
    group: 'evidence',
    guide: '保存下载日、版本、锚货币、国家覆盖和缺失处理；不要覆盖旧vintage。',
    links: [
      { label: '配对数据 · KAOPEN', url: lesson409References[13].url },
      { label: '配对制度源 · AREAER', url: lesson409References[15].url },
    ],
  },
  {
    title: 'IMF (2020) · Toward an Integrated Policy Framework',
    scope: '执行摘要、主要原则、经验边界与保障条件。',
    reason: '从单一三角形进入冲击—摩擦—工具—目标的政策地图。',
    url: lesson409References[18].url,
    group: 'systems',
    guide: '特别标记“深市场和持续市场准入下充分浮动通常适宜”与例外摩擦，避免只摘例外。',
  },
  {
    title: 'IMF (2023) · FXI Principles',
    scope: '浅层市场、错配、预期失锚三类摩擦及FXI保障。',
    reason: '把“干预汇率”改写成条件化的政策诊断，而非方向性交易观点。',
    url: lesson409References[21].url,
    group: 'systems',
    guide: '为每个摩擦写替代工具、资源约束、退出条件和可能副作用。',
  },
  {
    title: 'IMF (2022) · Institutional View Review',
    scope: '核心前提、预防性CFM／CFM-MPM、限制与执行成本。',
    reason: '理解资本流管理的正式适用边界及“不得替代必要调整”。',
    url: lesson409References[20].url,
    group: 'rules',
    guide: '分开记录政策框架、工作人员证据综述与具体国家建议；三者证据身份不同。',
  },
] as const satisfies readonly LessonReading[];
