import type { PolicyAutonomySourceId } from './policyAutonomyReferences';

export const policyAutonomyThesis = {
  title: '政策自主不是一只开关：制度承诺先限定可行工具集合，全球金融状态再穿过主体化摩擦形成不同结果',
  statement: '给定汇率承诺、有效资本流动、外部金融状态、计价／融资币种、期限错配和本地吸收能力，必须先判断哪项国内工具对哪项目标、在何种时域仍有可行空间；再分别观察政策率、汇率、收益率、信用、现金、产出与通胀，最后才评估政策效果和福利。',
  chain: '外部状态 → 汇率承诺 × 有效资本流动 × 资产可比与风险楔子 → 可行国内工具集合 → 主体化金融／宏观结果 → 预期与政策反馈 → 下一期约束',
  inequalities: [
    'Instrument autonomy ≠ financial-condition insulation',
    'Financial insulation ≠ stabilisation effectiveness',
    'Policy effect ≠ welfare optimality',
    'De jure openness ≠ de facto effective mobility',
    'Exchange-rate flexibility ≠ complete insulation',
    'Policy action ≠ identified treatment effect',
    'Double review / build / publish ≠ empirical qualification',
  ],
} as const;

export const policyAutonomyCoreRoute = [
  { time: '00–07分钟', conceptIds: ['policy-autonomy-mechanism-01'], goal: '把自主拆成工具、金融条件、稳定效果与福利四栏。' },
  { time: '07–14分钟', conceptIds: ['policy-autonomy-mechanism-02'], goal: '在声明假设内建立经典三元约束，不把角点当国家评分。' },
  { time: '14–22分钟', conceptIds: ['policy-autonomy-mechanism-03'], goal: '把汇率制度改写为锚、波幅、反应规则与退出时钟。' },
  { time: '22–29分钟', conceptIds: ['policy-autonomy-mechanism-04'], goal: '把资本开放拆成主体、工具、方向、币种、期限与执行。' },
  { time: '29–37分钟', conceptIds: ['policy-autonomy-mechanism-05'], goal: '用C1审计利率平价字段、楔子、unknown与基准相容性。' },
  { time: '37–45分钟', conceptIds: ['policy-autonomy-mechanism-06'], goal: '理解浮动扩大政策率空间，却不保证所有金融条件隔离。' },
  { time: '45–53分钟', conceptIds: ['policy-autonomy-mechanism-07'], goal: '沿风险溢价、中介杠杆和共同基金路线理解Dilemma。' },
  { time: '53–61分钟', conceptIds: ['policy-autonomy-mechanism-08'], goal: '同时追踪汇率的贸易缓冲、进口通胀与资产负债表通道。' },
  { time: '61–69分钟', conceptIds: ['policy-autonomy-mechanism-09'], goal: '用C2比较同政策率空间下的主体现金、吸收与准入。' },
  { time: '69–77分钟', conceptIds: ['policy-autonomy-mechanism-10'], goal: '按shock、friction、target、entity与clock分配多项工具。' },
  { time: '77–85分钟', conceptIds: ['policy-autonomy-mechanism-11'], goal: '用FXI双腿账本理解“可用工具≠免费自主”；冲销只中和声明腿，储备统计与CFM绕道留给第二遍。' },
  { time: '85–92分钟', conceptIds: ['policy-autonomy-mechanism-12'], goal: '区分政策反应、预期、选择偏误与处理效果。' },
  { time: '92–98分钟', conceptIds: ['policy-autonomy-mechanism-13'], goal: '把定义、模型、描述、因果、OOS与福利锁在证据阶梯。' },
] as const;

export const policyAutonomyPassportRules = [
  '工具：明确政策率、准备金价格、FXI、流动性设施、MPM、CFM或财政工具，不写笼统“政策”。',
  '决策者：记录央行、财政、监管、资本流管理或联合机构及其法定权限。',
  '目标：区分通胀、产出、汇率水平／波动、市场功能、信用或金融稳定。',
  '结果：政策率、收益率曲线、信用价格、信用数量、access、汇率和现金分别保存。',
  '主体：政府、银行、企业、基金、家庭与非居民不得被国家均值覆盖。',
  '时域：公告、决策、实施、结算、到期、评价和退出时钟分别记录。',
  '锚货币：固定或管理制度必须声明锚、篮子和基准国。',
  '汇率规则：中心价、波幅、触发器、工具、重设与退出条件需版本化。',
  '官方制度：de jure标签与来源、发布时间、适用期单独保存。',
  '事实制度：de facto分类、算法、窗口与vintage单独保存。',
  '资本方向：居民资产腿与非居民负债腿、流入与流出不得混称开放度。',
  '资本工具：FDI、证券股权、债券、贷款、存款和衍生品按互斥口径记录。',
  '期限：原始期限、剩余期限与现金到期日不得互换。',
  '币种：计价、融资、收入、结算与报告币种分别保存。',
  '市场范围：一级／二级、在岸／离岸、受监管／未监管路线不得默认等价。',
  '资产可比：信用、期限、抵押、流动性、税收和法律权利须核对。',
  '预期汇率：调查、模型、市场价格或实现值的身份必须明确。',
  '风险溢价：只在声明模型中为残差或估计，不伪装成直接观测。',
  'basis／对冲：远期、掉期、保证金、抵押品与对手方可履约性需同窗。',
  '制度楔子：税费、额度、持有期、准备金、审批、豁免和执行分别记录。',
  '全球状态：共同因子、VIX、美元或美债只是代理，shock身份另行识别。',
  '本地状态：通胀、产出、信用与政治信息使用决策时可得vintage。',
  '储备：gross、liquid／usable、已承诺、衍生品与短债覆盖分栏。',
  'FXI：交易、估值、收益与其他储备变化分开；储备变化不自动等于干预。',
  '冲销：声明被中和的是准备金、基础货币、短率还是其他腿。',
  '资格：设施的合格实体、抵押品、币种、期限、价格与上限必须明确。',
  '容量：法律权限、可用资产、市场深度、行政执行与财政成本分别登记。',
  '反事实：无政策、替代工具或不同制度路径必须在效果问题前声明。',
  '证据时钟：as-of、release、retrieval、revision、sample与PIT状态不可省略。',
  '结论等级：definition、MODEL-SYN、descriptive、conditional、causal、OOS、welfare分级。',
] as const;

export const policyAutonomyEntryVocabulary = [
  ['Policy autonomy', '对明确工具、目标、主体与时域的可行决策空间；不是国家永久属性。'],
  ['Instrument autonomy', '国内工具路径能否相对外部基准作出不同选择。'],
  ['Financial-condition insulation', '本地融资价格、数量、可得性和资产价格受到多少外部传导。'],
  ['Stabilisation effectiveness', '政策相对反事实是否改变声明的宏观或金融稳定目标。'],
  ['Welfare optimality', '计入资源、分配、尾部风险、外溢与替代工具后的规范判断。'],
  ['Trilemma', '固定汇率、资本高度流动与独立货币路径在声明经典假设下的相容性约束。'],
  ['Dilemma', 'Rey（2015）的原始强命题主张资本自由流动下全球金融周期可不因汇率制度而消失并约束货币政策；本课另把“浮动下广义金融条件仍可共振”记为较窄的结果分层命题。'],
  ['Anchor currency', '汇率承诺或政策比较所围绕的基准货币。'],
  ['Exchange-rate commitment', '锚、波幅、兑换、反应规则、信誉与退出条件的组合。'],
  ['De jure regime', '法律或官方申报的制度，不必等于实际行为。'],
  ['De facto regime', '根据实际汇率、储备或政策行为分类的制度。'],
  ['Effective capital mobility', '相关主体和资产在声明时钟上实际可跨境替代的程度。'],
  ['Capital account openness', '资本交易法律与事实开放度的集合，不是一条统一水管。'],
  ['UIP', '比较未对冲资产预期回报的无抛补利率平价关系。'],
  ['CIP', '使用远期或掉期锁定汇率后的有抛补回报关系。'],
  ['Expected depreciation', '决策时对未来本币价值变化的预期，不能用实现值无条件替代。'],
  ['Risk premium', '持有特定风险资产要求的补偿；常为模型或估计对象。'],
  ['Basis', '对冲后回报相对基准平价的差异，受资金、资产和中介约束影响。'],
  ['Global financial cycle', '跨国风险资产、信用、杠杆与资本流的共同波动状态。'],
  ['Pass-through', '外部变化进入本地政策率或金融结果的条件敏感度。'],
  ['Dominant currency pricing', '大量贸易价格以少数货币设定并短期粘性，使美元等主导汇率重要。'],
  ['Currency mismatch', '债务／支付币种与收入、资产或可执行对冲币种不匹配。'],
  ['FX intervention', '官方在外汇资产、负债或衍生品中改变头寸以影响市场或风险分配。'],
  ['Sterilisation', '用国内操作中和FXI某一声明流动性腿，而非消除所有影响。'],
  ['Usable reserves', '在相关法律、币种、期限与市场容量下可动用的官方外汇资源。'],
  ['Macroprudential measure', '针对系统性风险、杠杆、期限或金融机构韧性的措施。'],
  ['Capital flow management measure', '以居民身份或跨境性质区分并影响资本流的措施。'],
  ['Leakage / circumvention', '受限活动迁移至其他主体、工具、地区、币种或合同。'],
  ['Reaction function', '政策工具对信息集和目标偏离的系统性响应规则。'],
  ['Policy counterfactual', '同一情景下未采取或采取替代政策时的不可直接观测结果。'],
] as const;

export type PolicyAutonomyCheck = {
  id: string;
  kind: 'M' | 'K';
  title: string;
  question: string;
  options: readonly [string, string, string];
  correct: 0 | 1 | 2;
  answer: string;
  trap: string;
  sourceIds: readonly PolicyAutonomySourceId[];
};

export const policyAutonomyChecks: readonly PolicyAutonomyCheck[] = [
  { id: 'M1', kind: 'M', title: '结果护照', question: '浮动经济体没有跟随锚国加息，但本地信用利差大幅上升。最窄且可支持的结论是什么？', options: ['政策率路径存在差异；金融条件隔离仍需另测', '货币政策已完全自主且有效', 'Dilemma不成立'], correct: 0, answer: '工具路径与金融条件是不同结果；只观察到前者的差异。', trap: '把能设工具升级为全部结果隔离。', sourceIds: [5, 6, 9] },
  { id: 'K1', kind: 'K', title: '经典约束', question: '在可信硬盯住、无摩擦高资本流动和完全可比短债的MODEL-SYN中，国内要持续维持独立利率差，最低限度应怎样表述？', options: ['必然明天爆发危机', '至少一项声明需放松，或存在未声明楔子', '央行只需冲销即可永久维持'], correct: 1, answer: '三元约束给相容性边界，不给危机时点或免费绕行。', trap: '把模型不相容翻译成确定路径。', sourceIds: [1, 2, 3] },
  { id: 'M2', kind: 'M', title: '制度分类', question: '一国官方申报浮动，但在隐含区间边缘持续用利率和FXI抵消。研究护照应怎样记录？', options: ['只记浮动', '只记固定', '并列de jure浮动、de facto反应规则及适用时段'], correct: 2, answer: '官方和事实制度观察不同对象，应同时版本化。', trap: '用一个标签覆盖反应函数。', sourceIds: [15, 16] },
  { id: 'K2', kind: 'K', title: '资本流动', question: '为什么KAOPEN或AREAER中的法定开放不能直接替代有效资本流动？', options: ['实际执行还取决于主体、工具、成本、容量、基础设施与替代路线', '因为法定数据没有任何用途', '因为资本流动只由汇率决定'], correct: 0, answer: 'de jure是重要输入，但不等于具体路线上的de facto可执行性。', trap: '从“不能替代”误跳到“完全无用”。', sourceIds: [13, 14, 16] },
  { id: 'M3', kind: 'M', title: '利率平价', question: '一年期国内利率高于国外2个百分点，但预期贬值、风险、税费和basis未知。最严谨的状态是什么？', options: ['无风险套利2个百分点', '平价账本／回报比较未闭合，关键楔子unknown', '资本流必然流入'], correct: 1, answer: '期限对齐仍不足；预期与楔子未观测时只能把平价账本保持unknown，不能给套利或流向。', trap: '把UIP当会计恒等式。', sourceIds: [30] },
  { id: 'K3', kind: 'K', title: '浮动缓冲', question: '下列哪项最准确？', options: ['浮动保证所有金融条件独立', '全球周期证明汇率制度毫无作用', '浮动通常扩大政策率空间，但金融条件仍可经风险与中介渠道传导'], correct: 2, answer: '经典Trilemma的相容性结论与本课窄化的“浮动下广义金融条件仍可共振”命题可以同时成立；这不等于把Rey原始强Dilemma化解为不同结果。', trap: '把争论写成互相否定，或把本课窄命题冒充Rey原始强结论。', sourceIds: [5, 6, 9, 10] },
  { id: 'M4', kind: 'M', title: '现金缺口', question: '企业有10单位到期美元债、2单位美元收入、3单位可执行对冲收款和4单位本币贷款容量，但没有即时兑换路线。可机械扣除的是什么？', options: ['全部9单位', '只扣2+3，本币容量另栏', '本币贷款和美元收入都不能扣'], correct: 1, answer: '同窗外币现金可扣；没有兑换路线的本币容量不是美元现金。', trap: '把融资容量与币种现金混同。', sourceIds: [19, 20, 23] },
  { id: 'K4', kind: 'K', title: '主导货币', question: '主导货币计价对浮动汇率的含义是什么？', options: ['本币贬值永远不改善贸易', '只影响进口商，不影响政策', '短期支出转换可能弱化，美元汇率和进口通胀更重要，但作用依国家与主体'], correct: 2, answer: '论文给条件化通道和平均证据，不给普适零效果。', trap: '把“弱化”误写成“消失”。', sourceIds: [17] },
  { id: 'M5', kind: 'M', title: '冲销', question: '央行买入外汇并发行等额冲销票据。最窄结论是什么？', options: ['声明的准备金／短率腿可被中和；资产组合、风险与成本仍可能变化', '所有国内影响都被消除', 'FXI必然无效'], correct: 0, answer: '冲销对象必须声明，不能覆盖组合平衡和资产负债表通道。', trap: '把一个中和目标扩成全系统不变。', sourceIds: [23, 24, 25, 26] },
  { id: 'K5', kind: 'K', title: '政策识别', question: '压力最大时央行更常使用FXI，使用期结果更差。可直接推出什么？', options: ['FXI有害', 'FXI无效', '只能观察政策选择与结果共现；效果需反事实并处理选择'], correct: 2, answer: '严重度同时影响政策与结果，简单比较有选择偏误。', trap: '把政策反应当处理效果。', sourceIds: [19, 22] },
  { id: 'M6', kind: 'M', title: '资本流措施', question: '目标短债流在CFM后下降，但贸易信用和离岸借款上升。最合适的记录是什么？', options: ['目标路线下降且存在泄漏候选；总风险效果未识别', 'CFM完全成功', 'CFM必然有害'], correct: 0, answer: '需同时追踪替代路线、价格、期限与主体。', trap: '只看目标桶或直接作福利判断。', sourceIds: [21, 28, 29] },
  { id: 'K6', kind: 'K', title: '证据阶梯', question: '页面通过双审、构建、交互和打印验收后，哪项状态可升级？', options: ['现实因果效果', '内容与交付质量；经验资格仍保持false', '交易有效性'], correct: 1, answer: '审稿与运行QA不导入真实数据、PIT、因果或OOS证据。', trap: '把出版质量当经验验证。', sourceIds: [] },
] as const;

export const policyAutonomyUnderstandingQuestions = [
  '用同一匿名例子分别写出instrument autonomy、financial-condition insulation、stabilisation effectiveness和welfare的可检验问题。',
  '重建经典三元约束的最小假设，并指出每项假设被放松后结论怎样从“不相容”变成“待解释”。',
  '为一个官方“浮动”制度填写de jure与de facto双护照，列出至少四个可能分歧来源。',
  '把“资本账户开放”拆成居民方向、工具、币种、期限、市场位置和执行六个字段。',
  '给出一组期限和信用不匹配的国内外利率，解释为什么不能直接放入UIP。',
  '设计C1的一组合法输入，使利率平价（楔子账本）残差为零，并说明零残差不能证明什么。',
  '用一个例子同时证明“浮动汇率有用”和“浮动汇率不完全隔离金融条件”。',
  '区分global factor、candidate driver和identified shock，并为每层写一个允许的动词。',
  '比较有自然外汇收入企业与无对冲外币借款企业在同一贬值下的现金桥。',
  '解释为何外国持有的本币债降低借款人直接FX错配，却不消除全球金融周期风险。',
  '手算C2的一组外币现金缺口，并把没有兑换路线的本币融资容量放到正确栏目。',
  '为price、quantity与access各设计一个观测指标，说明三者为何不能互作代理。',
  '为FXI写完整工具护照：摩擦、目标、实体、路线、时钟、容量、成本、指标和反证。',
  '画出央行买入外汇并冲销的最小资产负债表，指出哪些影响没有被冲销。',
  '为一项CFM列出至少三条规避路线和一项可能的分配成本。',
  '解释为什么gross reserves不能直接成为私人企业同日可用的美元现金。',
  '画政策反应DAG，标出共同shock、国内状态、预期、政策动作和结果。',
  '为“浮动提高自主性”提出一个可识别estimand、处理、结果、反事实和主要威胁。',
  '比较Trilemma与Dilemma的左侧假设、结果变量、证据类型和政策含义。',
  '给4.10、5.06与7.17各写一份可交付payload和一句禁止越界的结论。',
] as const;

export const policyAutonomyUnderstandingGuides = [
  { kind: '定义', mustInclude: ['同一工具／时域', '四类结果分栏', '反事实只属于效果层'], commonError: '用“有／没有自主”一句覆盖四个问题。', extension: '再加入主体分布，说明国家均值如何误导。' },
  { kind: '模型', mustInclude: ['可信汇率承诺', '有效资本流动与资产可比', '预期与楔子'], commonError: '把不相容写成确定危机路径。', extension: '比较短期储备缓冲与长期可持续性。' },
  { kind: '测量', mustInclude: ['官方标签', '实际反应规则', '版本与适用期'], commonError: '用低汇率波动直接证明peg。', extension: '加入平行市场与隐含波幅。' },
  { kind: '测量', mustInclude: ['主体与方向', '工具和币种', '执行／替代路线'], commonError: '把KAOPEN当作事实跨境头寸。', extension: '设计一份de jure—de facto reconciliation表。' },
  { kind: '资产定价', mustInclude: ['同币种／期限／信用比较', '预期贬值', '风险、basis与制度楔子'], commonError: '只对齐年化期限就称无风险套利。', extension: '区分UIP与CIP的对冲边界。' },
  { kind: '计算', mustInclude: ['完整算式', '输入单位与符号', '零残差的证据上限'], commonError: '把平价残差为零称市场有效或因果闭合。', extension: '把一项数值楔子改为unknown，说明为何平价账本的closed/open二元判定必须停止；同时说明制度字段齐全时，相容性为何仍可独立保留。' },
  { kind: '反例', mustInclude: ['政策率空间', '汇率相对价格通道', '仍存在的风险溢价／信用通道'], commonError: '为了证明一边而否定另一边。', extension: '加入通胀预期失锚状态。' },
  { kind: '识别', mustInclude: ['统计状态', '竞争原因', '外生来源与排除限制'], commonError: '把VIX或美元直接命名为shock。', extension: '说明高频工具仍可能含信息效应。' },
  { kind: '现金流', mustInclude: ['同币、同时窗', '收入／支付／可执行对冲', '主体异质性'], commonError: '用国家净外币头寸替代企业现金。', extension: '加入对冲保证金和对手方违约。' },
  { kind: '渠道', mustInclude: ['借款人币种风险', '外国持有人汇率／久期风险', '市场深度／共同销售'], commonError: '把本币债称为国内风险。', extension: '比较国内养老金承接充足与不足。' },
  { kind: '计算', mustInclude: ['到期外币支付', '只扣可执行外币资源', '本币容量另栏'], commonError: '无兑换路线仍扣除本币贷款。', extension: '加入合法零、unknown与过度覆盖三种边界。' },
  { kind: '测量', mustInclude: ['融资价格', '实际数量', '可得性／资格'], commonError: '价格稳定就判断没有信贷收缩。', extension: '加入贷款期限和抵押条款。' },
  { kind: '政策', mustInclude: ['shock与friction', '实体／路线／时钟', '容量、成本、指标、反证'], commonError: '只写“稳定汇率”而无对象和评价标准。', extension: '列出不行动和替代工具反事实。' },
  { kind: '资产负债表', mustInclude: ['外汇资产腿', '国内负债腿', '冲销工具与未中和通道'], commonError: '等额冲销后写“没有影响”。', extension: '加入银行持有央票对信贷组合的影响。' },
  { kind: '政策', mustInclude: ['工具／主体替代', '在岸／离岸迁移', '执行和分配成本'], commonError: '目标流下降就称总风险下降。', extension: '区分临时gates与长期walls。' },
  { kind: '容量', mustInclude: ['gross与usable区分', '法律资格／时钟', '已承诺与市场容量'], commonError: '把储备／GDP直接映射到企业流动性。', extension: '加入估值变化与衍生品净头寸。' },
  { kind: '因果', mustInclude: ['共同原因', '政策选择', '预期／anticipation和结果'], commonError: '省略反向因果、政策选择和同期共同冲击。', extension: '提出一个负向控制或placebo。' },
  { kind: '研究设计', mustInclude: ['明确estimand', '处理与结果', '反事实及制度选择威胁'], commonError: '用相关系数代替处理效应。', extension: '比较事实制度与工具变量设计。' },
  { kind: '比较', mustInclude: ['经典相容性结果', '广义金融条件结果', '二者可同时成立'], commonError: '写成旧理论被新理论完全推翻。', extension: '加入汇率金融渠道解释央行为何少用潜在空间。' },
  { kind: '接口', mustInclude: ['类型化payload', '证据状态', '明确禁止升级项'], commonError: '4.09提前回答4.10或5.06。', extension: '加入7.10状态向量与7.24数据契约。' },
] as const;

export const policyAutonomyResearchQuestions = [
  { question: '事实汇率灵活性是否降低本地政策率对锚国货币冲击的pass-through？', design: '基于de facto制度的面板局部投影／反应函数，使用高频识别的锚国shock并与制度交互。', evidenceNeeded: '实时国内通胀与增长预期、锚货币、制度vintage、政策率和shock工具。', whatWouldWeakenIt: '制度内生选择、共同宏观消息、锚国信息效应或结果对窗口不稳健。', reject: '若控制国内信息后，浮动与peg的pass-through差异不稳定或方向相反。', sourceIds: [4, 7, 9, 10] as const },
  { question: '浮动提供的政策率空间是否同时降低信用利差与贷款access的外部传导？', design: '将政策率、债券利差、银行贷款价格／数量／拒绝率作为分结果，匹配外部shock。', evidenceNeeded: '主体级信贷与证券数据、汇率制度、外币暴露、本地需求控制。', whatWouldWeakenIt: '只观察总信贷、银行样本迁移或借款需求同步下降。', reject: '政策率pass-through下降但广义金融结果未改善时，拒绝“工具空间等于完全隔离”。', sourceIds: [6, 7, 9, 11] as const },
  { question: '外币负债是否使浮动经济体更倾向跟随锚国紧缩？', design: '以事前外币负债和自然对冲交互锚国shock，比较政策反应及金融条件。', evidenceNeeded: '部门／企业币种、期限、收入与对冲，实时政策信息和制度状态。', whatWouldWeakenIt: '外币负债在shock后测量、净额遮蔽尾部主体或商品出口收入未控制。', reject: '事前错配不改变政策或金融传导，且结果跨定义稳健。', sourceIds: [9, 19, 20, 23] as const },
  { question: '主导货币计价是否削弱双边贬值的短期支出转换并提高进口通胀？', design: '利用企业／产品计价货币差异或制度变化比较价格与数量pass-through。', evidenceNeeded: 'invoice currency、进口投入、价格重置、双边与美元汇率、产品数量。', whatWouldWeakenIt: '计价选择内生、价格频率不齐或美元shock与全球需求混杂。', reject: '控制选择后，主导计价组与本币计价组没有稳定差异。', sourceIds: [17] as const },
  { question: 'FXI在浅层市场或中介受限状态下是否更能改善市场功能？', design: '高频干预记录与事前市场深度／dealer约束交互，使用规则、阈值或工具变量。', evidenceNeeded: '交易级FXI、报价深度、价差、成交失败、衍生品、同步政策公告。', whatWouldWeakenIt: '秘密干预缺失、反应选择或全球波动同期回落。', reject: '识别后效果不随浅层／受限状态增强，或仅短暂价格移动而市场功能不改善。', sourceIds: [22, 24, 25, 26] as const },
  { question: '冲销工具是否通过银行资产组合影响国内信用，即使准备金腿被中和？', design: '利用冲销工具资格／额度或银行事前持仓差异，比较共同借款人信贷。', evidenceNeeded: '央行操作、银行证券与准备金、资本、借款人贷款和需求控制。', whatWouldWeakenIt: '央票持有反映银行风险偏好、借款人选择或其他监管同步变化。', reject: '对同一借款人，受影响银行与对照银行的信贷行为无差异。', sourceIds: [23, 26] as const },
  { question: '临时资本流gates是否减少目标流却把融资迁移到替代路线？', design: '事件研究结合BOP、银行、证券、贸易信用与离岸实体的路线守恒审计。', evidenceNeeded: '措施法律范围、实施预期、逐工具流量／头寸、价格、期限与主体。', whatWouldWeakenIt: '全球状态和国内需求未匹配、数据分类在政策期改变。', reject: '目标流下降但总融资和风险经替代路线完全恢复，则拒绝“全面隔离”。', sourceIds: [21, 28, 29] as const },
  { question: '储备与本地投资者基础是否降低外部risk-off下的本币债价格冲击？', design: '预先测量usable reserves、本地持有人与市场深度，和identified global shock交互。', evidenceNeeded: '持有人、交易、FXI、储备可用性、收益率和基金销售。', whatWouldWeakenIt: '储备以总额代替可用量、本地持有人在shock后内生增加。', reject: '缓冲变量不改变价格或access，或结果仅由政策选择反向因果驱动。', sourceIds: [7, 11, 19, 23] as const },
  { question: '政策率自主、金融条件隔离与宏观稳定是否在跨国数据中呈不同排序？', design: '分别构建三个结果，不预先加总；比较其相关、漂移和制度交互。', evidenceNeeded: '政策shock、FCI成分、实时通胀／产出、制度与资产负债表字段。', whatWouldWeakenIt: '指数权重事后选择、样本内归一化或共同数据源导致机械相关。', reject: '若三个结果在多种定义下完全同序，才可支持单维近似；否则保留向量。', sourceIds: [5, 6, 10, 12] as const },
  { question: '一项综合政策组合是否优于单工具，且收益是否超过成本与外溢？', design: '结构模型、局部识别矩与明确社会福利权重结合；报告替代模型与敏感性。', evidenceNeeded: '冲击、摩擦、工具执行、资源成本、分配、跨境外溢与长期行为反应。', whatWouldWeakenIt: '模型摩擦遗漏、参数不可识别、工具效果来自同一校准目标。', reject: '在合理模型／权重范围内组合不再改善，或成本／外溢逆转排序。', sourceIds: [19, 20, 21, 22, 27] as const },
] as const;

export const policyAutonomyEvidenceBoundaries = [
  '经典Trilemma只在声明的小型开放经济、资本流动、资产可比、预期和政策承诺假设内给相容性结论。',
  'Rey原始Dilemma是资本自由流动下的强制度命题；本课窄化的金融条件共振命题与后续部分缓冲证据必须另栏，不等于证明任何浮动经济体没有政策率空间。',
  '制度指数与年度分类是构造变量；de jure、de facto、实际头寸和执行强度必须分开。',
  '利率平价残差混合预期、风险、basis、成本、限制与测量误差，不能唯一命名。',
  '汇率、资本流、政策率和金融条件是均衡量；相关与时序不自动识别供给或政策shock。',
  'FXI、MPM与CFM的政策框架给条件、摩擦与保障，不是国别处理效果或福利处方。',
  'AUTHOR/MODEL-SYN实验只验证声明算术和逻辑，不是历史回放、PIT数据或现实参数。',
  '双审、构建、浏览器、打印与发布只升级内容／交付资格；observed、causal、OOS、trading、production保持false。',
] as const;

export const policyAutonomyInterfaces = [
  ['4.01 Balance of Payments', '接收居民、资产／负债、交易／估值、储备资产和兑换边界。', '国际收支身份不证明三元约束已经绑定，也不给资本流动因果。'],
  ['4.02 International Monetary System', '接收锚货币、主导计价与货币网络。', '货币份额不自动给政策从属、汇率效果或福利。'],
  ['4.03 Reserve / Safe Asset', '接收储备动机、流动性与安全资产字段。', '储备总额不等于可用FXI容量或私人现金。'],
  ['4.05 Global Dollar Funding', '接收实体、币种、期限、对冲、price／quantity／access和现金时钟。', '美元融资状态不自动决定本地政策率或CFM效果。'],
  ['4.06 Global Banks', '接收typed credit edge、法人／路线与home–host约束。', '贷款共动不自动识别供给或政策自主。'],
  ['4.07 Global Financial Cycle', '接收global state、candidate／identified shock、loading与local residual。', '不把共同因子重命名为美国政策shock或政策无效。'],
  ['4.08 EM Capital Flows', '接收流量方向、工具、币种、期限、投资者基础、边际吸收与政策状态。', '不继承合成数值、事件严重度或政策答案。'],
  ['4.10 Exchange-rate Regime', '交付versioned regime passport、工具可行集合与贸易／金融通道。', '不提前比较具体shock被吸收到哪里或制度总体优劣。'],
  ['5.06 Capital Controls', '交付CFM对象、方向、工具、路线、时钟、执行、泄漏、指标与反证。', '不提前回答CFM有效性、永久性、分配、外溢或福利。'],
  ['7.10 Cross-asset State', '交付有证据状态的政策约束向量、全球／本地状态与主体化结果。', '不输出可交易自主性指数、固定country beta或择时信号。'],
  ['7.17 / 7.24–7.26 Research', '交付DAG、estimand、anticipation、selection、实时vintage、placebo和失败模式。', '反应与结果的同期关系不升级为treatment effect、PIT或OOS资格。'],
] as const;

export const policyAutonomyInvariants = [
  '自主性判断必须带工具、目标、主体与时域。',
  '工具自主、金融条件隔离、稳定效果与福利四栏不得合并。',
  '经典Trilemma的假设必须与结论同屏。',
  'Trilemma与Dilemma不得写成互相否定。',
  '汇率承诺必须声明锚、波幅、反应规则与退出。',
  '官方制度与事实制度并列并带版本。',
  '低汇率波动不自动证明固定。',
  '资本开放按主体、方向、工具、币种、期限与市场分层。',
  'de jure openness不等于de facto effective mobility。',
  '措施存在不等于执行，执行不等于无绕道。',
  'UIP与CIP不得写成无条件会计恒等式。',
  '利率比较必须对齐币种、期限、信用、抵押与结算。',
  '预期贬值与事后实现贬值分开。',
  '风险溢价若为残差必须明确模型身份。',
  'unknown、合法0、不适用与非法输入四态分开。',
  '平价残差不自动预测资金流、储备或危机。',
  '浮动扩大潜在政策率空间不等于实际使用。',
  '政策率空间不等于广义金融条件隔离。',
  '全球共同因子不等于结构shock。',
  'VIX、美元和美债收益率只是代理或候选驱动。',
  '美国政策公告必须处理信息效应与同步消息。',
  '汇率贸易通道与金融通道必须同时保留。',
  '计价货币、融资货币、收入货币和报告货币分开。',
  '国家净外币头寸不得覆盖部门与尾部主体。',
  '本币债降低直接FX错配不等于消除外部风险。',
  '同窗外币现金和本币融资容量分栏。',
  '没有可执行兑换路线时本币容量不得扣减FX gap。',
  'price、quantity与access不得互作代理。',
  '政策工具必须绑定shock、friction、target、entity和clock。',
  '工具护照完整只生成可检验假设，不生成有效性。',
  '储备总额不等于usable reserves。',
  '储备变化不等于等额FXI。',
  '冲销必须声明被中和的具体腿。',
  '冲销不消除组合平衡、风险、成本或信号。',
  'FXI不保证目标汇率，也不是免费第四个角。',
  'CFM目标流下降不等于总风险下降。',
  'CFM不得无条件替代必要宏观调整。',
  'MPM与CFM的法律对象和外溢必须区分。',
  '政策动作不等于政策效果。',
  '政策在压力期内生选择必须进入DAG。',
  '实时决策不得使用事后修订数据解释。',
  '利率共动可来自共同基本面或相似反应函数。',
  '低利率共动也不自动证明高自主。',
  '模型相容、描述相关与局部因果逐层升级。',
  '政策效果、外推与福利分开。',
  '上游只传类型、语义与证据上限，不传合成值或审稿身份。',
  'AUTHOR/MODEL-SYN不得伪装现实数据。',
  '双审、构建、打印与发布不生成经验资格。',
  'observed、PIT、causal、prediction、OOS、trading、production逐轴冻结。',
] as const;
