import type {LessonReference,LessonReading} from './types';
const accessedAt='2026-09-15';
export const lesson319References:LessonReference[]=[
 {id:1,authors:'International Monetary Fund',year:'2022-08-08',accessedAt,title:'Staff Guidance Note on the Sovereign Risk and Debt Sustainability Framework for Market Access Countries',publication:'IMF Policy Paper 2022/039; staff report completed 2022-07-19',url:'https://www.imf.org/-/media/files/publications/pp/2022/english/ppea2022039.pdf',use:'作者保留136页原PDF，实读PDF1–2、6–39、55–64、97–105指定连续段，原PDF30–32已逐页看图；不称全文、全fanchart/near-term算法、全annex或运行模板。支持范围/计价、名义起点、GFN、真实性、银行剩余承接假设与stress/non-stabilization/sustainability区别。本课不复制有待符号桥接的实汇率中间式、不取得内部概率模型/阈值、不给真实国家判断；2026下载不是2022PIT。'},
 {id:2,authors:'Tim Willems; Jeromin Zettelmeyer',year:'2022-01',accessedAt,title:'Sovereign Debt Sustainability and Central Bank Credibility',publication:'IMF Working Paper 22/16; DOI 10.5089/9798400201585.001; author views',url:'https://www.imf.org/-/media/files/publications/wp/2022/english/wpiea2022016-print-pdf.pdf',use:'作者实读当前28页PDF全部文字、六节/脚注/书目，未逐篇读引用原模型、未看Figure1或复现实证。支持本金/市场价值预算对象、终端条件区别、状态权重、财政反应、协调/缓慢危机、央行信誉与本币条件及有界服务流。复杂随机核/期望索引尚需完整桥接，不复制其链条当独立证明；有限C2/C7另按明示定义推导，不把WP作者观点改成机构操作判断。'},
 {id:3,authors:'International Monetary Fund',year:'2014',accessedAt,title:'Government Finance Statistics Manual 2014',publication:'GFSM2014; specified institutional, valuation and debt sections',url:'https://www.imf.org/external/np/sta/gfsm/pdf/text14.pdf',use:'作者保留470页PDF，只实读PDF1–2、38–43、80、102、200、215、237的指定完整段：机构功能/控制，§§3.113–3.115计价，§§4.51–4.57分析，债务工具/居住地/期限。初次截断页40/200已另完整重读；目录截断不算通读。支持nominal≠face≠market、gross/net初级口径和剩余/原始期限；不声称全手册、PSDSGuide、现行所有勘误或具体实体/法律分类认证。'},
 {id:4,authors:'Henning Bohn',year:'1998-02 working paper',accessedAt,title:'The Behavior of U.S. Public Debt and Deficits',publication:'Author-hosted February1998 working paper; publication identity QJE113(3), August1998, 949–963 separately checked',url:'https://www.econ.ucsb.edu/~bohn/papers/SUS98.pdf',use:'作者实际读16页工作稿全部文字、六节/全部11尾注/书目；表图另文件未读/未导入，原样本未重估。支持财政反应机制与起点先扣余额的预算时钟、高债区和状态条件；不把历史正回归当因果或当前国家安全。原文件头/xref有恢复警告，原字节保留，不冒称出版PDF同字节；后来更新数据不是原1916–95样本PIT。'},
 {id:5,authors:'Henning Bohn',year:'1998-08; electronic conversion 2005-10',accessedAt,title:'The Behavior of U.S. Public Debt and Deficits: Technical Appendix',publication:'Author-hosted technical appendix; A1/A2 and beginning of A3',url:'https://www.econ.ucsb.edu/~bohn/papers/qje98app.pdf',use:'作者保留9页，实读PDF1–6含A1/A2完整与A3数据说明开头，原PDF2–3已看；PDF7–9/A3后续未读。保留全高债至少线性、控制项有界、有限状态加权收入等条件；收敛/不等式排版的系数域尚需额外桥接，不据“正系数”一句证明任意域或完整无限期TVC。未读其引Bohn1995、未复现全证明；有限根/C7不是附录算法。'},
 {id:6,authors:'International Monetary Fund; World Bank',year:'2014-04-01',accessedAt,title:'Revised Guidelines for Public Debt Management',publication:'Staff completed 2014-03-26; IMF/World Bank principles, not a universal binding law',url:'https://www.imf.org/external/np/pp/eng/2014/040114.pdf',use:'作者保留43页，实读PDF1、4–6、11–14指定页，Box1跨13–14全部含脚注；跨后页的intro/coordination未全读，未称全annex/法律/衍生品。支持费用与风险权衡、重设/再融资/流动性/币种和担保监测。具体法域/CAC/司法执行仍待读；后来2015书籍身份不覆盖该2014原PDF，本课不认证真实权限、发行或最优策略。'},
];
export const lesson319ReadingList:LessonReading[]=[
 {title:'先画偿付地图：SRDSF范围、计价与融资',scope:'核心读SectionsI–III含Boxes1–3；再按问题读Box4及GFN §§73–83',reason:'先确认是谁欠、欠哪种金额、什么日期需筹钱，再看比率；不先学习内部概率算法。',url:lesson319References[0].url,group:'core',guide:'把gross、资产缓冲、nominal/face/market、期初/当期GDP、GFN/发行/净增各分列。看到银行剩余承接时，写“压力假设”，不写“无限能力”。'},
 {title:'GFSM的机构与计价：读定义而不是只记简称',scope:'按需读§§2.35–2.66、3.113–3.115、4.51–4.57、7.119–7.126、7.263–7.269',reason:'比较数据产品前核机构、工具、计价、居住地与期限，防止同列名变不同对象。',url:lesson319References[2].url,group:'core',guide:'解释零息债face与nominal的区别；明确gross/net初级口径中的利息收入。深化通读相关完整章节须另读，不冒充作者已通读470页。'},
 {title:'债务管理指南：从费用最低转向条件风险权衡',scope:'先读Box1完整两页和§§9–13；深化再读完整coordination/风险管理与annex',reason:'理解旧债票息滞后、再融资、交收和现金缓冲为何有不同门槛。',url:lesson319References[5].url,group:'rules',guide:'用完整年2.8与年中2.4指出计费日；画到期峰值与今日资金。后续法律/衍生品原文属于进一步阅读，不套给所有国家。'},
 {title:'Willems–Zettelmeyer：把平均率与状态支持分开',scope:'核心Sections2–4；再读5–6的r<g、有界服务流及争论范围',reason:'同一预算式可以有不同资产对象，低融资率、财政支持和展期能力也不是同一结论。',url:lesson319References[1].url,group:'models',guide:'先做C7三种协变，再追原随机核的定义/信息集。复杂式链须另核索引与条件，不能用有限加总当无限期证明；引用原模型须另读原文。'},
 {title:'Bohn1998工作稿：从反应思路进入证据条件',scope:'先读SectionsII–III及所有相关尾注，再读V–VI；深化另读表图与原实证',reason:'看清起点余额先扣再计回报，与本课期末GDP份额规则不同。',url:lesson319References[3].url,group:'models',guide:'写出Dnext=(D−S)(1+R)及GDP尺度；把局部正相关、全高债条件与政策可行性分开。表图/回归复制是待读/待做，不使用后来数据伪造原PIT。'},
 {title:'Bohn技术附录：深化前先核全部条件',scope:'核心A1/A2与A3说明；PDF7–9和Bohn1995原论文属继续阅读',reason:'数学命题不是“正响应”四个字，收入可积、状态权重、控制项和系数域都影响证明。',url:lesson319References[4].url,group:'models',guide:'先区分有限n与极限；检查每个求和下标和系数收敛域。本文不替你认证未桥接的全证明，也不将2005转换文件当1998交付字节。'},
 {title:'SRDSF真实性与判断：诊断和结论怎样分层',scope:'SectionIV及SectionVIII §§144–147；深化完整risk/annex需另读',reason:'计划调整、增长、利差、期限可以共同过于乐观；压力、基线不稳定与不可持续不是一个标签。',url:lesson319References[0].url,group:'evidence',guide:'写一个可观察目标/期限，再列替代机制和数据时钟。机械信号、机构判断和个人课堂计算分开；不猜内部方法/阈值。'},
 {title:'进一步待读：Blanchard2019的成本与低利率',scope:'Public Debt and Low Interest Rates，AER109(4),1197–1229；作者目前只核official abstract/书目，全文待读',reason:'深化财政成本、福利成本和r<g边界，不能把本课算术固定点当原论文全部结论。',url:'https://www.aeaweb.org/articles?id=10.1257/aer.109.4.1197',group:'models',guide:'取得全文后分财政/福利/风险成本阅读；不要把登录HTML算成PDF全文。该路线是新增深入阅读建议，不用于本文未核到的量化断言。'},
];
