import type { LessonReference, LessonReading } from './types';

export const lesson323References:LessonReference[]=[
 {id:1,authors:'John H. Boyd, Ravi Jagannathan and Jian Hu',year:'2001',accessedAt:'2026-09-15',title:'The Stock Market’s Reaction to Unemployment News: Why Bad News Is Usually Good for Stocks',publication:'NBER Working Paper8092，January2001；本次原件41物理PDF页，不混成2005期刊版',url:'https://www.nber.org/system/files/working_papers/w8092/w8092.pdf',use:'编写者完整读原PDF3–12文字，并看原整页2核作者/摘要/版本；前两页提取编码异常不称全文读。13–41完整结果/表与2005JF版未本人读或复算。支持该历史样本的状态条件及现金流/利率候选通道，不作坏消息必涨定律。预测代理是作者模型，不是MMS共识；final资料、NBER事后相位和第三法较早final训练/当前preliminary的边界保留。原11所印408与起止月不一致，独立原页/表核查亦见未解，不静改日期、猜样本暖启动或称PIT复现。'},
 {id:2,authors:'Torben G. Andersen, Tim Bollerslev, Francis X. Diebold and Clara Vega',year:'2002',accessedAt:'2026-09-15',title:'Micro Effects of Macro Announcements: Real-Time Price Discovery in Foreign Exchange',publication:'NBER Working Paper8959，May2002；原PDF38页，2003AER最终版未读',url:'https://www.nber.org/system/files/working_papers/w8959/w8959.pdf',use:'编写者完整读原PDF1–11文字并真看原8核标准化与陈旧调查讨论；未读12–38全结果/图、MMS/Olsen数据或底层被引论文全文。支持宣布值相对MMS周五电话中位预测的差、误差标准差尺度、调查可能陈旧以及多个消息/滞后下均值与方差不同对象。作者资料有效性检验不等全市场瞬时预期恒等式；全样本尺度与选型不授本课PIT/OOS资格。本文七SYN不是其数据或算法复制。'},
 {id:3,authors:'Refet S. Gürkaynak, Brian Sack and Eric T. Swanson',year:'2004',accessedAt:'2026-09-15',title:'Do Actions Speak Louder Than Words? The Response of Asset Prices to Monetary Policy Actions and Statements',publication:'FEDS2004-66；稿件November1,2004、官方入口LastupdateDecember2,2004分别记录，原43PDF页',url:'https://www.federalreserve.gov/pubs/feds/2004/200466/200466pap.pdf',use:'编写者完整读原PDF1–8文字/真看原8；未读9–43全结果、AppendixA公告表、AppendixB月均缩放/因子旋转、tick数据或2005期刊版。支持target与futurepath不是单信息维度，以及窄窗减少其他新闻/反向反馈污染的有条件识别理由。原2003例实际降25bp但期货测度13bp相对收紧，不静改为SYN调查差25bp。因子结构解释不是任意价格移动的外生冲击证明；本课不复现原算法或估计收益。'},
 {id:4,authors:'Federal Reserve Bank of Philadelphia',year:'动态官方页面（本次读取2026）',accessedAt:'2026-09-15',title:'Survey of Professional Forecasters — Frequently Asked Questions',publication:'SPF官方实质FAQ；本次取得原HTML，未读62页Documentation或下载完整调查Excel',url:'https://www.philadelphiafed.org/surveys-and-data/real-time-data-research/spf-faqs',use:'编写者实际完整读main实质FAQ；支持匿名专业预测panel、形成日未跟踪、截止和发布日、在GDP首估日发问卷随后截止/公布，以及离散年化与水平问法。不能将稍后这轮调查回填同日首估前公开共识，也不能将专业预测者等同全体边际交易者。未核逐条历史回答、历史汇总vintage、调查无偏性或即时条件分布。'},
 {id:5,authors:'Federal Reserve Bank of St. Louis',year:'动态官方文档（本次读取2026）',accessedAt:'2026-09-15',title:'FRED API — Real-Time Periods',publication:'官方Introduction与两组Examples；本次原HTML，不是已执行API返回',url:'https://fred.stlouisfed.org/docs/api/fred/realtime_period.html',use:'编写者完整读主要定义/两组示例，支持默认today、ALFRED过去信息版本、realtime_start/end为含端点YYYY-MM-DD日期区间。日级版本合同不是公告前08:30可得、私人接收时点或所有原始修订archive证书；未调用API或下载系列。示例key不被当实际凭证，设置as-of字段也不自证严格PIT。'},
 {id:6,authors:'U.S. Bureau of Labor Statistics',year:'动态官方页面（本次读取2026）',accessedAt:'2026-09-15',title:'Revisions to Nonfarm Payroll Employment',publication:'CES官方修订首段；原生HTML下载403/身份未知，保留明确官方web工具表示',url:'https://www.bls.gov/web/empsit/cesnaicsrev.htm',use:'编写者实际读修订首段159–160，未全读1979+历史表或重建benchmark。支持首次约参考期后三周、两次样本修订、之后年度benchmark，final sample-based不是永不修订真值。当前月变化、此前月修订与就业水平分开；本课未取得真实数据包/共识或复算历史首估差。下载失败不改称取得原生HTML，官方工具正文表示与原件身份分开。'},
 {id:7,authors:'U.S. Bureau of Labor Statistics',year:'2026（页面LastmodifiedAugust28,2026）',accessedAt:'2026-09-15',title:'Release and Dissemination Policy',publication:'BLS当前公布政策、技术延迟和提前访问段；原生HTML403，官方web表示另留',url:'https://www.bls.gov/about-bls/dissemination.htm',use:'编写者完整读主要政策163–193及修改日期，未privacy/OMB全文或全微观程序。七PFEI8:30Eastern、非PFEI10:00和数秒内主页发布/技术延迟不等所有BLS都8:30或人人同时收到；有限提前访问依明示指令。历史事件须那次archive、实际release/渠道/时区DST另核，不能把当前规范倒填过去，未认证可交易时钟。'},
 {id:8,authors:'U.S. Bureau of Economic Analysis',year:'2026（页面Lastmodified8/26/26）',accessedAt:'2026-09-15',title:'GDP Revision Information',publication:'官方当次与上月版本比较说明及表/深化目录；本次原HTML，不是已取XLSX',url:'https://www.bea.gov/gdp-revision-information',use:'编写者本人读此次官方web主要比较说明、两类表目录、更多资料目录及修改日，非全动态年份HTML/XLSX、Fixler2024或Holdren2014全文。支持同一参考季度不同版本的比较，不从目录推出第三版永远最终、真实修订幅度、所有发布规范或PIT历史数据集。新参考期和旧参考期的修订不能相互冒名。'},
 {id:9,authors:'John H. Cochrane',year:'2011',accessedAt:'2026-09-15',title:'Discount Rates',publication:'NBER Working Paper16972，April2011；原件65PDF页，不混成作者站不同稿或2011JF最终版',url:'https://www.nber.org/system/files/working_papers/w16972/w16972.pdf',use:'编写者本人完整读原PDF1–8文字，未9–65全理论/附录、原全部图、数据代码或2011JF最终版。支持预期现金流/折现框架、含终端项近似presentvalue关系、DP长期分解与价格/收益变化的区别及回归不能自证因果。作者选定长期样本的DP折现主张不等每次公告价格完全由折现、现金流永远无用或一期SYN为股票普遍定价。risk premium/expected return依原语境，不等无风险短率同义。'},
];

export const lesson323ReadingList:LessonReading[]=[
 {title:'阅读路线一：先审预期代理与新闻单位',scope:'WP8959原PDF1–11，特别8–9的S定义与陈旧调查讨论；随后完整12–38及底层资料',reason:'先写A/代理/误差尺度分别是什么，分清中位与条件平均、均值跳跃与方差、资料有效性与PIT。后半与底层资料是深化目标不是编写者已读声明。',url:lesson323References[1].url,group:'core'},
 {title:'阅读路线二：调查的形成、截止与公开',scope:'SPF全部实质FAQ，然后当前官方Documentation和各问卷/历史Excel由读者另读',reason:'把问卷发行、回答截止、公开和实际形成日分开，辨增长年化与水平定义。先问这轮调查能否先于被研究公告，而非先挑预测最准确的列。',url:lesson323References[3].url,group:'core'},
 {title:'阅读路线三：宏观好坏与股票好坏的条件',scope:'WP8092原PDF3–12方法与状态通道，之后原13–41结果/表与确切后版另核',reason:'逐一审模型预期、final/初值、NBER事后相位；原日期/计数疑点保持未解，不自己纠表。条件反应不是买卖口诀，后版及代码未取得时不能称复制。',url:lesson323References[0].url,group:'evidence'},
 {title:'阅读路线四：现金流、折现与长期分解',scope:'WP16972原PDF1–8，再完整9–65各理论/应用及Appendix；原JF最终版另取得',reason:'把长期DP变化与公告事件收益分开，仔细保留近似恒等式终端项及估计误差。不给单期cashflow公式冒名一般风险定价，也不将折现等同短率。',url:lesson323References[8].url,group:'models'},
 {title:'阅读路线五：当前target与未来path',scope:'FEDS2004-66原PDF1–8，再完整9–43与两Appendix、原始数据/代码',reason:'亲读25bp实际变化与13bp期货差的原例，不混成SYN调查25bp。理解因子/缩放和识别假设后才能复制，不靠标题命名任何价格移动外生冲击。',url:lesson323References[2].url,group:'models'},
 {title:'阅读路线六：版本数据库不等秒级可得',scope:'FRED实时日期Introduction/Examples及对应observations文档；真实系列archive另取',reason:'先区分默认today、过去版本、含端点日期与公告/接收钟；只有日级定义不能完成盘前可得审计。调用真实数据前锁来源、版本与匹配对象。',url:lesson323References[4].url,group:'rules'},
 {title:'阅读路线七：就业首估与修订的不同消息',scope:'BLS CES修订说明与所需历史表、原EmploymentSituation公告及benchmark方法',reason:'画出当前月actual、此前月修订和其他字段的消息向量；final sample-based仍可benchmark。深化表和微观方法需要另读，不能从首段推真实修订分布。',url:lesson323References[5].url,group:'evidence'},
 {title:'阅读路线八：公开时刻、渠道与历史归档',scope:'BLS主要公布政策；若研究旧事件另取那次archive与适用发布规范',reason:'不同发布类别、Eastern/DST、技术延迟和实际接收分别核。今天网页修改日不是旧事件time，政策预定钟也不能保证全体同时可交易。',url:lesson323References[6].url,group:'rules'},
 {title:'阅读路线九：GDP版本与新参考季度',scope:'BEA比较说明、所需second/advance与third/second比较表、Fixler2024和Holdren2014另读',reason:'把同季版本变化与下一季新增长拆开，并核实际/名义、年化与季调。未下载表不推任何当前差；所列后文不是已读证据。',url:lesson323References[7].url,group:'evidence'},
 {title:'阅读路线十：把事件研究缩到可反驳问题',scope:'重读WP8959方法的多消息/滞后与FEDS2004-66窄窗理由；之后完整识别、原数据和稳健性设计',reason:'选择一个公告/代理/资产/窗口，先锁训练和并发消息判据，再检验陈旧、前置移动和窗口敏感性。理论解释、历史关联、结构因果、PIT和可执行盈利需要不同证据。',url:lesson323References[1].url,group:'systems',links:[{label:'FEDS窄窗与政策路径原件',url:lesson323References[2].url}]},
];
