import type { TreasuryCurveSourceId } from './treasuryCurveReferences';

export type TreasuryCurveFormula = {
  kind: 'definition' | 'local-approximation' | 'author-syn' | 'measurement-template';
  expression: string;
  variables: readonly { symbol: string; meaning: string }[];
  explanation: string;
  stopRule: string;
};

export type TreasuryCurveConcept = {
  id: string;
  label: string;
  title: string;
  question: string;
  intuition: string;
  actors: string;
  constraints: string;
  behavior: string;
  transmission: string;
  feedback: string;
  formula?: TreasuryCurveFormula;
  counterexample: string;
  evidenceBoundary: string;
  interfaces: { from: string; to: string };
  sourceIds: readonly TreasuryCurveSourceId[];
  sourceNote: string;
};

export const treasuryCurveConcepts: readonly TreasuryCurveConcept[] = [
  {
    id: 'treasury-curve-mechanism-01',
    label: 'CURVE PASSPORT / NAME THE OBJECT',
    title: '先识别是哪一条曲线：同样写着“美元五年利率”，CMT、zero、SOFR OIS 与 swap rate 仍是不同对象。',
    question: '为什么在讨论全球传导之前，必须先给利率写完整的曲线护照？',
    intuition: '“五年利率”像一句只写了城市、没写街道和门牌的地址。财政部CMT是从官方par curve固定期限点读出的报价；zero yield对应从今天到某日期的一笔零息现金流；SOFR/OIS来自隔夜担保融资及掉期合约；单只券YTM又把多笔现金流压缩成一个内部收益率。数字即使相近，所回答的问题也不同。',
    actors: '财政部决定官方曲线的方法与输入券；纽约联储取得报价并管理SOFR等参考率；交易商、清算机构与合约双方决定可成交曲线、抵押和折现制度；研究者还会为宏观分析拟合off-the-run曲线。使用者必须登记币种、曲线家族、输入工具、报价侧、复利、日计数、估值时点、抵押制度与用途。',
    constraints: '名称不完整时不能把一个点带入估值。CMT由纽约联储约15:30取得的indicative bid-side input quotations派生；这些输入不是实际成交，所得CMT也不是零息曲线。SOFR是隔夜融资参考率而非长期国债收益率；研究者拟合曲线可以平滑个券噪声，却不是可直接购买的证券。不同来源还可能有发布时间、修订和方法断点。',
    behavior: '资产管理人先选与负债币种、现金流和抵押安排匹配的曲线，再计算风险；交易员可能同时监控Treasury、OIS与swap曲线，因为它们分别承担参考、融资、折现或相对价值角色。若护照缺失，专业做法不是补一个“市场常识”默认值，而是停止定量结论。',
    transmission: '曲线身份决定后续每一扇门：哪组discount factors给现金流定价、哪种instrument对冲、spread以什么benchmark计算、融资成本来自哪里，以及跨国比较是否包含币种转换。对象一旦混错，误差会沿估值、对冲、风险归因和跨资产叙事逐层放大。',
    feedback: '某条曲线被更多合约与风险系统采用，会吸引报价、对冲和研究基础设施，进一步强化其公共坐标功能；但制度切换也可能把折现流动性迁向另一曲线。Treasury的影响力因而可以很强，同时仍与OIS或swap曲线共存。',
    counterexample: '一份按SOFR price alignment interest处理的CCP清算美元swap，可以用Treasury期货对冲部分久期，却不能因此把Treasury CMT直接当合同折现曲线。反过来，一条研究用off-the-run zero curve适合宏观分解，却不是某只可成交on-the-run券的报价。',
    evidenceBoundary: '财政部方法与FAQ支持CMT的输入、par性质和zero边界；纽约联储与ARRC支持SOFR及清算折现制度。它们不指定所有私人合约的曲线，也不允许由曲线名称推出资产涨跌。',
    interfaces: { from: '接收3.07的curvePassport语义合同与4.03的“货币单位不等于工具”边界；不消费两课SYN数值。', to: '把通过护照检查的曲线对象交给4.04.2；若任一关键字段缺失，后续定量分支全部STOP。' },
    sourceIds: [1, 2, 7, 8],
    sourceNote: '来源1–2固定官方CMT对象；来源7–8固定repo reference rate与CCP折现制度。四者共同支持“先认对象”，不支持一条万能曲线。',
  },
  {
    id: 'treasury-curve-mechanism-02',
    label: 'CASH FLOWS / SIX COORDINATES',
    title: 'Price、YTM、discount factor、zero、par 与 forward 是同一现金流系统的不同坐标，而不是可互换标签。',
    question: '为什么一个10年期CMT不能直接贴现所有十年内现金流？',
    intuition: '把一张十年票息债想成二十多张到期日不同的小欠条绑在一起。价格是每张欠条现值之和；YTM只是寻找一个统一数字，使这组现金流在特定复利规则下恰好还原当前价格。它方便报价，却不代表市场真的用同一个利率给每笔现金流贴现。',
    actors: '发行者规定票息、到期日与本金；市场形成每只证券价格；曲线构造者从多只券bootstrap贴现因子并插值；投资者再以discount factors给自己的现金流逐期估值。Treasury bills、coupon notes/bonds、TIPS、FRNs与STRIPS具有不同现金流，不能只看“都是国债”。',
    constraints: '复利、日计数、结算、应计利息、clean/dirty price和现金流日期必须一致。Par yield是让假想票息债平价的票息率；zero yield与discount factor一一对应；forward由两个日期的贴现因子比值合成。远期还含期限溢价、流动性和供需，不能读成确定未来短率。',
    behavior: '研究者先把券价转成统一现金流表，再拟合平滑曲线；资产持有人用与每一支付日期匹配的节点重估；风险经理保留“报价层”和“估值层”的转换记录。看到一个10Y headline quote时，他们会问它是实际券YTM、CMT par、zero还是swap rate，而不会直接代入任意NPV。',
    transmission: '同一曲线节点变化会按现金流时点进入现值；票息较早、久期较短的资产暴露较小，远期现金流较重的资产暴露更大。把par错当zero会使短端和长端贴现同时错位，错误随后被误解为spread变化或资产特定消息。',
    feedback: '更多可交易STRIPS、券价与衍生品报价可帮助识别期限结构；更可信的曲线又改善相对价值与对冲。但拟合越平滑，也越可能抹去个券便利或市场功能异常，因此“好曲线”必须服从研究目的。',
    formula: {
      kind: 'definition',
      expression: 'P = Σⱼ CFⱼD(tⱼ);  D(t)=e^(−z(t)t);  f(t₁,t₂)=[lnD(t₁)−lnD(t₂)]/(t₂−t₁)',
      variables: [
        { symbol: 'P', meaning: '含义明确的资产现值；clean或dirty必须另行声明' },
        { symbol: 'CFⱼ', meaning: '时点tⱼ的确定名义现金流' },
        { symbol: 'D(tⱼ)', meaning: '同币种、同制度、同估值时点的贴现因子' },
        { symbol: 'z(t)', meaning: '这里采用连续复利表达的zero yield' },
        { symbol: 'f(t₁,t₂)', meaning: '由今日曲线合成的区间远期，不是无风险预测' },
      ],
      explanation: '前三者是定义关系；真实Treasury还需半年度票息、精确日计数和结算规则。本课交互只用明确标注的简化SYN现金流。',
      stopRule: '若输入是par/YTM却标作zero，或现金流币种、日期、复利、日计数、曲线来源任一缺失，停止计算；unknown不得补0。',
    },
    counterexample: '一只高票息10年券与一只零票息10年STRIP可以有相同最终到期日，却有不同现金流重心与价格敏感度；即使两者YTM相同，用同一个10Y数字替代整条discount curve也可能给出不同错误。',
    evidenceBoundary: 'GSW给出discount/zero/par/forward的严格关系与期限结构估计；Treasury FAQ说明CMT是par、bond-equivalent且不是官方zero curve。它们不保证任何拟合方法唯一，也不把forward解释成纯预期。',
    interfaces: { from: '接收4.04.1通过身份校验的曲线，不重新教授3.07完整期限结构分解。', to: '把逐期discount exposure交给4.04.3的基准服务与4.04.5–4.04.6的风险映射。' },
    sourceIds: [2, 3, 16],
    sourceNote: '来源2–3固定数学与报价边界；来源16固定不同Treasury工具的现金流对象。',
  },
  {
    id: 'treasury-curve-mechanism-03',
    label: 'BENCHMARK / COMMON COORDINATE',
    title: 'Treasury的全球力量首先来自公共参考坐标：市场可以围绕它报价、对冲和解释，而不必让它进入每份合约的折现条款。',
    question: '参考基准如何在不是“万能折现率”的情况下影响全球资产？',
    intuition: '地图的经纬度不等于每栋房子的建造成本，但大家使用同一坐标后，位置、距离和比较都更容易。Treasury期限节点类似公共坐标：信用债可以报“matched Treasury + spread”，久期风险可以换算成Treasury DV01，宏观叙事也常以2Y、10Y、30Y变化表达。',
    actors: '发行人、银行、基金、保险、中央银行、做市商、衍生品交易者与风险系统都消费同一组可观察节点，但目的不同：发行定价、相对价值、久期对冲、资产配置、抵押融资或信息提取。Swap曲线也可能在某些市场承担更强benchmark角色。',
    constraints: '比较只有在币种、现金流、期限、optionality、税、信用、流动性与融资条件被匹配或明确列为spread组成时才有意义。Benchmark是语言和参照，不是无误差复制工具；不同工具之间保留basis risk，危机中basis可以扩大。',
    behavior: '交易者以Treasury curve为起点，再为资产自身风险加减楔子；风险经理把组合映射到关键期限，但会同时监控swap spread与融资basis；研究者用共同节点比较事件响应，却不把所有同步变化都归因于相同结构冲击。',
    transmission: '共同坐标降低比较与对冲成本，使同一Treasury节点变化迅速进入信用债发行、MBS相对价值、股票贴现叙事和外国债券配置。传播并非逐合同复制，而是参与者根据自己暴露主动重新报价、换仓与融资。',
    feedback: '广泛使用带来更多交易、数据和hedge工具，进一步提高benchmark可见性；更强可见性又吸引更多使用。若basis、市场功能或制度安排恶化，参与者可能转向swap/OIS坐标，说明benchmark地位是网络均衡而非自然常数。',
    counterexample: '一家公司债以“5Y Treasury + 180bp”报价，不表示它的每笔现金流只由5Y CMT贴现；180bp内可能混合信用、流动性、资本、税与期权补偿。若该spread扩大100bp，即使Treasury不动，债价仍可显著下降。',
    evidenceBoundary: 'GSW与IAWG支持Treasury的benchmark、hedge与全球制度角色；BIS显示swaps也承担benchmark并存在basis risk。证据不支持Treasury垄断，也不支持固定一比一beta。',
    interfaces: { from: '接收4.04.2已区分的现金流与曲线坐标。', to: '把reference、hedge、RV、collateral和information五种角色拆给4.04.4–4.04.10，避免全部塞进discount rate。' },
    sourceIds: [3, 4, 9],
    sourceNote: '来源3–4支持Treasury公共坐标；来源9提供多benchmark与basis风险的必要反例。',
  },
  {
    id: 'treasury-curve-mechanism-04',
    label: 'ON-THE-RUN / VISIBLE BUT NOT PURE',
    title: 'On-the-run新券既是最醒目的价格发现工具，也最可能携带流动性、交割与repo specialness。',
    question: '为什么最活跃的Treasury报价可能同时是优良市场基准和不纯净的宏观曲线点？',
    intuition: '最热闹的门店最容易观察价格，却可能因为位置、客流和稀缺资格而收取额外溢价。最新发行的同期限Treasury常交易更集中、衍生品和repo用途更强；它的低收益率可能部分来自这些服务，而不只是预期政策路径。',
    actors: '财政部按拍卖日历发行新券；interdealer与dealer-to-client市场集中交易；套利与hedge资金使用cash、futures和repo；需要特定券交割的参与者会借券。曲线构造者必须决定纳入哪些券、怎样处理异常价格和auction周期。',
    constraints: 'On-the-run只是最近发行身份，不是“绝对最流动”的永久保证。Repo specialness、交割选择、税务、short demand与auction cycle会改变相对价格；off-the-run也可能在压力时流动性恶化。官方CMT使用最近拍卖券，而GSW研究曲线剔除on-the-run与first off-the-run，二者用途不同而非互相否定。',
    behavior: '短线交易与风险沟通常以on-the-run节点为中心；宏观研究可能用off-the-run拟合减少个券便利影响；相对价值交易则比较新旧券、futures与swap的basis。正确做法是声明目的，然后选择输入，而不是把一种曲线冠为“真曲线”。',
    transmission: '当特券需求或市场流动性变化时，on-the-run yield可以相对整条宏观曲线移动；若其headline报价被广泛引用，这一局部楔子会进入信用spread、风险归因和媒体叙事。套利通常拉回偏差，但需要repo、资本与dealer承载。',
    feedback: '更高交易集中度强化价格发现与hedge用途，进一步提高新券需求；需求又可能令repo special和便利溢价扩大。若套利资金受保证金或资产负债表约束，同一正反馈会变成basis扩大和流动性分裂。',
    counterexample: '新10Y券因repo special而价格偏高、收益率偏低时，用它与一只不易借券的公司债直接计算spread，会把Treasury特券便利混进所谓信用补偿。改用匹配的off-the-run curve后，spread可能不同。',
    evidenceBoundary: 'Treasury方法说明官方输入来自最近拍卖券；GSW与Fleming支持on/off-the-run、流动性与specialness。证据不支持固定premium，也不说明off-the-run没有自身摩擦。',
    interfaces: { from: '接收4.04.3的benchmark概念，进一步拆出个券便利。', to: '把可交易hedge工具及其basis交给4.04.5–4.04.7；把repo特券支路交给4.04.8。' },
    sourceIds: [1, 3, 6, 7],
    sourceNote: '来源1解释官方CMT输入；来源3、6、7解释研究剔除、流动性和repo specialness。',
  },
  {
    id: 'treasury-curve-mechanism-05',
    label: 'DURATION / LOCAL SENSITIVITY',
    title: 'Duration与PVBP把期限价格变化映射成局部P&L；它们是暴露测量，不是冲击原因。',
    question: '为什么相同10bp变动对短票、长债、远期负债和“长久期股票”的影响不同？',
    intuition: '同样下调一条传送带的速度，站在出口附近的包裹受影响较小，尚需很久才到达的包裹受影响更久。现金流越远，其现值对贴现率变化通常越敏感。Duration把这组时点权重压成一阶敏感度；PVBP把变化换成每1bp的货币金额。',
    actors: '债券投资者计算合同现金流duration；保险与养老金比较资产和负债；dealer用futures、swaps或Treasuries对冲DV01；股票分析者有时用估值模型讨论“equity duration”，但它依赖现金流预测与风险溢价，不能与债券合同久期混为一谈。',
    constraints: 'Modified duration只适合小幅、局部、近似平行的yield变化；大幅变动需convexity甚至完整重估。YTM duration把多节点风险压成一维；callable、MBS等现金流随利率改变时，还存在option-adjusted与负凸性问题。本节不把股票久期当可直接观测常数。',
    behavior: '风险经理先按完整曲线bump-and-reprice，再用duration/PVBP作可沟通摘要；交易者选择hedge notional使目标方向的DV01抵消；研究者则把价格反应与冲击身份分开——duration说明“若节点变化多少，价格近似怎样变”，不说明节点为何变化。',
    transmission: 'Treasury节点变化经资产现金流权重转成价格变化，进而影响保证金、资本、再平衡和发行成本；远期负债或高duration头寸对相同bp更敏感。若持有人被迫调仓，初始估值冲击还会通过流动性反馈放大。',
    feedback: '普遍duration hedging会增加Treasury futures、swaps与现券需求，强化其benchmark角色；在大规模同向对冲中，hedge flow本身也可能推动曲线节点，令原先的外生冲击与内生价格影响交织。',
    formula: {
      kind: 'local-approximation',
      expression: 'ΔP/P ≈ −Dmod·Δy + ½·Convexity·(Δy)²;  PVBP ≈ P·Dmod·0.0001',
      variables: [
        { symbol: 'Dmod', meaning: '给定现金流与当前yield附近的modified duration' },
        { symbol: 'Δy', meaning: '以十进制表示的小幅收益率变动' },
        { symbol: 'Convexity', meaning: '二阶曲率修正；定义与单位需保持一致' },
        { symbol: 'PVBP', meaning: '价格对1bp局部变动的货币敏感度近似' },
      ],
      explanation: '这是局部泰勒近似，不是已实现P&L承诺。对真实多节点曲线，应使用逐节点bump或完整重估。',
      stopRule: '若未声明价格单位、收益率复利、方向、变动幅度、现金流是否随利率改变或曲线是否平行，禁止把结果称为精确P&L。',
    },
    counterexample: 'Modified duration为7的SYN债券遇到+10bp平行小变动，一阶约为−0.7%；但若曲线只在2Y上升、10Y不动，或债券含提前偿付选择权，这个单一数字可能严重误导。',
    evidenceBoundary: 'GSW支持duration与convexity的定义和局部边界；TreasuryDirect支持不同工具现金流结构。证据不把股票久期视为合同事实，也不提供本课SYN参数。',
    interfaces: { from: '接收4.04.2的现金流与discount factors。', to: '把一维局部暴露交给4.04.6升级为key-rate向量，并把margin支路交给4.04.8。' },
    sourceIds: [3, 16],
    sourceNote: '来源3支撑债券数学；来源16提醒Bills、Notes、Bonds、TIPS和FRNs现金流不同。',
  },
  {
    id: 'treasury-curve-mechanism-06',
    label: 'KEY-RATE / VECTOR BEFORE HEDGE',
    title: '非平行曲线需要关键久期向量：总DV01中性只消除了一个方向，不等于整个曲线风险为零。',
    question: '为什么用一只10Y Treasury对冲复杂组合，仍会在steepener或butterfly中产生P&L？',
    intuition: '总重量相同的两座书架，不代表每层承重相同。总DV01像整座书架的重量；key-rate duration则告诉你2Y、5Y、10Y、30Y各层放了多少。只在10Y放一个反向砝码，可以平衡总量，却未必平衡每层。',
    actors: '组合经理持有跨期限债券、MBS或负债；dealer提供Treasury、futures与swaps hedge；模型团队定义节点、插值和bump形状；清算与融资安排又给hedge工具增加basis与roll成本。每种工具的风险向量必须在同一单位和估值约定下比较。',
    constraints: 'KRD依赖节点集合、局部冲击设计和曲线重构方法，不是唯一自然分解。匹配Treasury KRD仍保留credit spread、swap spread、optionality、cheapest-to-deliver、convexity和funding basis。负数或零残余可以是合法结果，不能被验证器自动裁剪。',
    behavior: '风险经理先得到目标组合KRD vector，再选择多个hedge instruments求解目标方向；对不同steepener、flattener与butterfly做压力重估；剩余向量、basis和convexity独立报告。若只有总duration而没有节点暴露，hedge effectiveness保持unknown。',
    transmission: '曲线节点异动通过残余KRD产生P&L；P&L改变margin与资本，导致进一步减仓或追加hedge。多家机构使用相似节点和工具时，集中hedge flow可把局部风险需求传回Treasury曲线和futures basis。',
    feedback: '活跃hedge市场提高Treasury基准的可用性；更强基准又鼓励更多资产按这些节点管理风险。但节点拥挤、交割稀缺或dealer capacity收缩时，对冲流可能扩大basis，使“最常用hedge”自身成为风险源。',
    formula: {
      kind: 'local-approximation',
      expression: 'ΔP/P ≈ −Σₖ KRDₖ·Δzₖ;  residual vector = KRDportfolio + H·notional',
      variables: [
        { symbol: 'KRDₖ', meaning: '对第k个声明节点局部bump的价格敏感度' },
        { symbol: 'Δzₖ', meaning: '同一曲线护照下第k节点的SYN变动' },
        { symbol: 'H', meaning: 'hedge工具的节点暴露矩阵' },
        { symbol: 'notional', meaning: '带方向与单位的对冲名义向量' },
      ],
      explanation: '向量为零只表示所选局部节点与模型内一阶风险被匹配；不消除basis、convexity、liquidity或跳跃风险。',
      stopRule: '节点数、单位、曲线身份、工具暴露矩阵或映射规则任一缺失时，hedge effectiveness输出null；不得用总DV01替代未知向量。',
    },
    counterexample: '组合在2Y有+4、10Y有+6的相对KRD，用10Y hedge −10把总和压到0；若2Y上升20bp而10Y仅上升5bp，残余仍显著。总DV01中性并未覆盖这个steepener方向。',
    evidenceBoundary: 'GSW支持duration/convexity与Treasury hedge背景；Ho是KRD原始书目但全文未取得。因此节点、矩阵和情景均为作者SYN，不能称经验最优。',
    interfaces: { from: '接收4.04.5的局部duration，不改变冲击身份。', to: '把hedge residual交给4.04.7的relative-value basis和4.04.8的融资约束。' },
    sourceIds: [3, 9, 15],
    sourceNote: '来源3、9说明hedge与basis风险；来源15只承担KRD书目来源。',
  },
  {
    id: 'treasury-curve-mechanism-07',
    label: 'RELATIVE VALUE / SPREAD IS A BUNDLE',
    title: '“Benchmark + spread”是有用的报价分解，但spread同时装着信用、流动性、期权、资本与融资楔子。',
    question: '为什么Treasury yield不动，信用债、MBS或swap仍能大幅重估？',
    intuition: '房屋价格可以写成“土地基准价 + 房屋自身调整”，但调整项会随建筑质量、租金、法规和融资改变。固定收益资产的spread也不是一个纯风险标签；它是相对于选定benchmark后尚未解释部分的组合。',
    actors: '发行人以benchmark加spread融资；投资者比较相对收益；dealer和套利基金在cash、futures、swap、MBS与credit之间搬运风险；评级、资本、税收与option exercise又改变资产自身楔子。不同参与者的融资成本决定看似相同spread是否可套利。',
    constraints: '计算spread前必须匹配币种、现金流日期、duration、coupon、call/prepayment、税、信用、流动性和融资；若目标正是某一服务，就应保留该维度并明确命名。Nominal yield spread、OAS、asset-swap spread与Treasury basis不是同一量。',
    behavior: '交易者先选与目标风险相匹配的reference curve，再把资产自身spread按可观测驱动拆解；风险报告同时显示benchmark DV01与spread DV01；相对价值策略保留funding、haircut与exit capacity。缺少匹配时，专业结论是“raw spread，含混合楔子”。',
    transmission: 'Treasury曲线变化先重估共同期限坐标；信用、流动性或期权spread再独立变化。两者可同向放大，也可反向抵消。Spread扩大会提高融资成本、降低持仓价值并触发风险限额，进而影响发行和实体支出。',
    feedback: '套利和做市通常将相似现金流的basis拉回，但它们需要资金与资产负债表。Basis扩大 → margin/haircut上升 → 套利资本退场 → basis进一步扩大，是2020类压力中的关键正反馈之一。',
    counterexample: 'Treasury 5Y node不变而公司信用spread由150bp扩大到250bp，匹配duration约4的债券可因资产自身楔子产生约−4%的局部价格贡献；把全部变化归因于“全球无风险率”会漏掉主要路径。',
    evidenceBoundary: 'GSW与IAWG支持Treasury的relative-value、cash/futures与融资联系；BIS benchmark研究支持不同参考曲线与basis risk。它们不把任意原始yield差解释成纯信用或纯便利收益。',
    interfaces: { from: '接收4.04.3公共坐标、4.04.4个券便利与4.04.6hedge residual。', to: '把funding-dependent arbitrage交给4.04.8，把不同折现制度交给4.04.9。' },
    sourceIds: [3, 4, 9],
    sourceNote: '三项来源共同支持reference、RV和basis；不提供无条件spread解释。',
  },
  {
    id: 'treasury-curve-mechanism-08',
    label: 'COLLATERAL / FUNDING LOOP',
    title: 'Treasury既是被定价的证券，也是取得现金的抵押投入品；因此传播会绕过传统贴现公式进入资产负债表。',
    question: 'Haircut、repo rate与dealer capacity怎样把Treasury变化传到其他资产？',
    intuition: '同一辆卡车既有二手车价格，也能抵押贷款。价格下降会降低抵押价值；放贷方若同时提高首付比例，能借到的现金下降得更快。Treasury也是如此：市场价格、haircut、repo rate、特券供需和可用数量共同决定融资能力。',
    actors: '现金借方以Treasury作collateral；现金出借方与tri-party/DVP基础设施决定可接受条件；dealer为客户融资并承接库存；leveraged funds做basis或relative-value；清算机构收取margin。纽约联储的SOFR聚合广泛隔夜Treasury repo交易，但特定券special仍可能偏离general collateral。',
    constraints: '融资容量不等于证券面值：要扣除haircut，并考虑price、eligible quantity、encumbrance、maturity、counterparty与rollover。Repo special rate低可能表示借券需求强，不是借现金成本普遍下降。SOFR不覆盖每一笔repo；正常期haircut也不能机械延伸到压力期。',
    behavior: '杠杆投资者比较asset carry、repo cost与basis；dealer分配资产负债表并在库存、客户需求与风险限额间权衡；压力时出借方提高margin或缩短期限，借方出售Treasury和其他资产取得现金。官方操作可通过购买、repo或设施缓解特定环节，但效果需逐工具识别。',
    transmission: '价格下降或haircut上升 → 可借现金减少 → 追加保证金/去杠杆 → 现券、期货和其他流动资产卖出 → depth下降、price impact上升 → 价格与融资条件进一步恶化。共同dealer跨市场活动使约束可以同步传到信用、MBS与股票流动性。',
    feedback: '正常期低haircut与窄basis支持杠杆和套利，改善价格一致性；积累的杠杆却使体系在volatility/margin shock时更脆弱。市场流动性与融资流动性因此形成双向反馈，而“安全抵押品”不等于“无流动性风险”。',
    formula: {
      kind: 'author-syn',
      expression: 'cash capacity = eligible market value × (1 − haircut);  funding gap = required cash − capacity',
      variables: [
        { symbol: 'eligible market value', meaning: '对特定对手方与时点合格、可达、未占用的SYN市值' },
        { symbol: 'haircut', meaning: 'SYN融资折扣；范围需为0至1' },
        { symbol: 'required cash', meaning: '同一时点需要满足的SYN现金需求' },
        { symbol: 'funding gap', meaning: '可为负、零或正；正值才表示缺口' },
      ],
      explanation: '这是单笔教学算术，未包含利息、variation margin、交叉抵押、再质押、期限和default waterfall。',
      stopRule: '若eligible quantity、market price、haircut、币种或时间窗口未知，capacity为null而非0；不得用毛持仓替代可用抵押品。',
    },
    counterexample: '持有面值100的Treasury不代表能借到100现金：若市值96、只有80%可用且haircut为5%，SYN容量仅72.96；若价格和可用比例同时下降，融资收缩会超过单一债价变化。',
    evidenceBoundary: 'IAWG支持cash–repo–futures、basis融资和2020约束；纽约联储支持SOFR与specials口径；Fed MPR支持dealer库存和市场功能。来源不提供本课haircut或容量参数。',
    interfaces: { from: '接收4.04.4 specialness与4.04.7 basis。', to: '把funding/intermediary state交给4.04.10–4.04.14；折现制度差异由4.04.9单独处理。' },
    sourceIds: [4, 5, 7],
    sourceNote: '来源4–5支撑网络与压力反馈；来源7固定SOFR和special repo对象。',
  },
  {
    id: 'treasury-curve-mechanism-09',
    label: 'OIS DISCOUNTING / CONTRACT GATE',
    title: '有抵押衍生品的折现曲线由合同、抵押报酬与清算制度约束；Treasury是重要参照，却不是SOFR/OIS的别名。',
    question: '为什么Treasury影响swap定价，却不能直接替代其OIS discount curve？',
    intuition: '同一栋房子的市场比较价与按揭合同利率会互相影响，但它们不是同一个条款。Treasury曲线可以提供期限参照和hedge，清算swap的折现则要服从CCP、PAI和collateral remuneration。制度改变时，即使未来浮动现金流不变，NPV也可能重估。',
    actors: 'CCP、clearing member、swap counterparties、ARRC与风险系统处理PAI、discounting和补偿；Treasury与swap交易员管理相对价值和hedge；法律与运营团队维护CSA或清算规则。每一方都不能用“美元无风险率”替代实际合同字段。',
    constraints: 'OIS curve本身需要完整构造，不是单一SOFR fixing；未担保、不同币种、不同CSA或多曲线现金流可能使用不同框架。Treasury与OIS之间存在swap spread、便利、信用、融资与供需楔子。历史上的EFFR→SOFR迁移是制度实例，不是说所有时期都采用同一曲线。',
    behavior: '估值团队按合约与清算规则选曲线；risk team同时计算OIS discount risk、forecast curve risk与Treasury hedge basis；制度切换时用现金调整或风险补偿维持经济价值。交易者仍用Treasury观察宏观期限价格，但不会把引用与折现合并。',
    transmission: 'Treasury变化可通过hedge成本、swap spread、repo与相对价值影响swap报价；OIS变化又能改变担保衍生品NPV和margin，反过来触发Treasury hedge。两条曲线相互作用，却不具有身份等式。',
    feedback: '更多OIS折现与清算活动提高SOFR衍生品流动性，可能强化swap benchmark；Treasury的深度与futures仍使其在方向风险和宏观信息中关键。多基准并存形成跨市场basis，也为套利和压力传导提供通道。',
    counterexample: '2020年的CCP折现切换需要对存量合约作价值与风险补偿，这恰好说明折现曲线不是由“大家都看10Y Treasury”自然决定。如果两条曲线相同，切换就不会产生这种NPV与hedge处理。',
    evidenceBoundary: 'ARRC提供具体清算折现迁移证据；纽约联储定义SOFR；BIS提供swap与政府债benchmark共存。它们不指定私人合约法律意见，也不说明Treasury与swap完全脱钩。',
    interfaces: { from: '接收4.04.1曲线护照、4.04.7 basis与4.04.8 repo融资。', to: '把多曲线状态交给4.04.10的driver归因；任何跨资产叙事都须保留curveFamily字段。' },
    sourceIds: [7, 8, 9],
    sourceNote: '来源7–8固定融资与折现制度；来源9固定多benchmark事实。',
  },
  {
    id: 'treasury-curve-mechanism-10',
    label: 'DRIVER IDENTITY / SIGN IS NOT A SHOCK',
    title: 'Treasury yield的方向只是观测结果：预期短率、期限溢价、增长信息、供给、便利与融资约束都能产生同号变化。',
    question: '长端收益率上升究竟意味着什么，为什么普通日频变化不能自动命名为Fed shock？',
    intuition: '体温上升可能来自运动、感染或炎热环境；数字方向相同，治疗和后果却不同。10Y yield上升也可能来自更强增长、意外紧缩、通胀风险、期限补偿、供给承载、流动性便利下降，甚至外国冲击。',
    actors: '家庭与企业发布数据；央行释放政策与信息；财政部门发行债务；投资者更新增长、通胀与风险承受；dealer与套利者受融资约束；外国市场也改变全球duration需求。研究者必须用事件时间、联合资产反应或模型假设识别候选driver。',
    constraints: '日频或更低频yield混合消息、风险溢价和交易流。FOMC窄窗口也可能同时含政策与央行信息；term-premium分解依模型和vintage；“overnight”只能是外国冲击的rough proxy。识别不足时driverClass必须为unknown。',
    behavior: '分析者先记录key-rate shock vector和时间窗口，再检查股票、FX、inflation compensation、OIS、term premium候选与新闻surprise；比较至少两种可反驳的叙事。交易或政策结论不能仅由yield sign触发。',
    transmission: '不同driver虽然先使Treasury节点同向移动，却会通过现金流预期、政策反应、风险溢价、美元融资和跨境资本产生不同甚至相反的下游结果。错误命名冲击，会把后续所有共振都当作同一“全球贴现率”效应。',
    feedback: '资产反应又影响金融条件和政策预期，从而返回Treasury曲线；外国配置变化也会改变美国term premium。因此shock与response需在时间和结构上区分，不能把Treasury永远放在因果链起点。',
    counterexample: '增长数据好于预期可让10Y yield与股票同时上升；意外紧缩可让10Y yield上升而股票下降；现金争夺又可能让Treasury价格与股票同时下跌。三种状态共享“yield上升”，却不是同一机制。',
    evidenceBoundary: 'Boehm–Kroner与Jarociński–Karadi支持联合资产反应区分信息与政策候选；Kim–Ochoa支持外国冲击。具体数字受样本与识别约束，不能实时外推。',
    interfaces: { from: '接收前九节给出的curve、basis与funding状态。', to: '把driverClass及unknown分支交给4.04.11跨资产竞赛、4.04.13国际传导与4.04.14压力案例。' },
    sourceIds: [11, 12, 13],
    sourceNote: '来源11提供反向溢出；来源12–13提供增长/信息与政策冲击的联合资产差异。',
  },
  {
    id: 'treasury-curve-mechanism-11',
    label: 'CASH FLOW vs DISCOUNT vs RISK PREMIUM',
    title: '跨资产价格是现金流、无风险期限价格、风险溢价与融资楔子的竞赛；Treasury move只观察到其中一个共同坐标。',
    question: '为什么收益率上升有时伴随股票上涨，有时却触发股票与信用下跌？',
    intuition: '一家公司的价值既看未来赚多少钱，也看投资者用多高回报要求去折现。好增长消息可能同时提高利润与利率；只要现金流上调更大，股价仍会上涨。政策紧缩或风险承受下降则可能让折现与ERP同时上升，股价下跌。',
    actors: '企业与消费者决定真实现金流；央行与债券投资者影响政策路径和term premium；股票、信用和商品投资者重估风险补偿；dealer与资金提供者决定融资楔子。外国资产还多一层汇率与本地政策反应。',
    constraints: '下列分解只是记账框架，不能从价格唯一反演结构冲击。Equity cash-flow news、risk-free exposure和ERP都模型依赖；信用资产还含default与liquidity，MBS含prepayment，商品含库存与便利。若driver unknown，方向结论也应为null。',
    behavior: '分析者把观测价格变化拆成候选贡献，逐项说明数据与识别；至少构造一个yield↑/equity↑和一个yield↑/equity↓反例；比较在相同key-rate move下cash-flow与ERP如何改变净结果。',
    transmission: '增长信息经收入与利润上调现金流，也可能推高Treasury；紧缩经融资条件和风险承受抬升要求回报；市场功能压力经margin与变现同步打击多个资产。共同Treasury节点只是传播枢纽之一，资产自身楔子可放大、抵消或反转。',
    feedback: '风险资产下跌收紧金融条件，可能降低未来增长与政策路径，随后压低Treasury yields；风险偏好恢复又能缩窄spread并抬高长期yield。股债相关方向因此随driver与状态改变，不是永久参数。',
    formula: {
      kind: 'measurement-template',
      expression: 'ΔlnPasset ≈ ΔCF news − ΔRf exposure − ΔRP − ΔBasis/Funding',
      variables: [
        { symbol: 'ΔCF news', meaning: 'SYN预期现金流贡献；正值提高价格' },
        { symbol: 'ΔRf exposure', meaning: '经资产期限暴露映射的无风险曲线贡献' },
        { symbol: 'ΔRP', meaning: '资产特定风险溢价变化' },
        { symbol: 'ΔBasis/Funding', meaning: '相对价值、流动性与融资摩擦贡献' },
      ],
      explanation: '这是作者教学账本，不是可由市场价格唯一识别的结构模型。各项可正、负或零，净结果也可恰好抵消。',
      stopRule: '若driver、现金流币种、资产期限或风险溢价定义未知，不发布固定方向；不得把残差自动命名为ERP或融资冲击。',
    },
    counterexample: '两个SYN情景都令10Y node上升20bp：增长信息把现金流贡献提高3%、贴现与ERP合计拖累1%，净价格上升；紧缩使现金流0%、贴现与ERP合计拖累3%，净价格下降。Yield sign相同，结论相反。',
    evidenceBoundary: 'IFDP 1371支持美国消息的全球风险资产与风险承受通道；AEA publisher abstract支持政策/信息冲击的相反股票共动。它们不提供本课系数，也不把所有事件归入两类。',
    interfaces: { from: '接收4.04.10 driverClass与前文暴露。', to: '把资产特定净贡献交给4.04.12币种门和4.04.13本地制度门。' },
    sourceIds: [12, 13],
    sourceNote: '两项来源只支持方向依赖driver的存在性；分解公式与参数均为作者模板/SYN。',
  },
  {
    id: 'treasury-curve-mechanism-12',
    label: 'FX HEDGE / FOREIGN INVESTOR GATE',
    title: '外国投资者面对三种不同回报：美元资产回报、未套保本币回报与套保后本币回报。',
    question: '为什么更高的Treasury yield未必提高外国投资者的套保后吸引力？',
    intuition: '外国旅客看到美国存款利率更高，但最终还要把美元换回本币。若美元贬值，未套保收益会被侵蚀；若用forward锁汇，短端利差、cross-currency basis与滚续成本又会进入。Headline Treasury yield只覆盖故事的一部分。',
    actors: '外国央行、保险、养老金、银行和基金的本币负债与hedge mandate不同；FX dealer与银行提供swap/forward并占用资产负债表；本地央行反应影响短端利差；投资者决定hedge ratio、tenor与roll schedule。',
    constraints: '必须知道本币、资产持有期、spot convention、hedge ratio、forward points/basis、套保期限和滚续。Covered interest parity是比较起点，不保证无摩擦；hedge maturity短于资产会留下rollover gap。缺失任何关键字段时hedged return为null，不能默认未套保或100%套保。',
    behavior: '未套保投资者把美元资产回报与spot变动合成；套保投资者以forward/swaps锁定部分汇率并支付或获得套保carry；机构还会根据资本、流动性和collateral调整hedge ratio。收益率上升若伴随basis恶化或hedge cost增加，净需求可能不升反降。',
    transmission: 'Treasury变化影响外国配置；hedge需求进入FX swap与cross-currency basis；basis和美元融资条件又改变净回报与回购成本；资产出售或套保调整同时影响Treasury、美元和本地债券。',
    feedback: '大规模同向hedging会占用dealer资产负债表并改变basis，basis恶化又刺激部分投资者减少套保或卖出资产，形成反馈。当地汇率与政策反应随后返回本币收益率和全球配置。',
    formula: {
      kind: 'author-syn',
      expression: 'Rlocal ≈ Rusd + FXspot;  Rhedged ≈ Rusd + (1−h)FXspot − h·hedgeCost',
      variables: [
        { symbol: 'Rusd', meaning: '同一持有期的美元资产总回报' },
        { symbol: 'FXspot', meaning: '按明确报价方向换算的本币汇率贡献' },
        { symbol: 'h', meaning: '0至1之间的SYN hedge ratio' },
        { symbol: 'hedgeCost', meaning: '与期限匹配的SYN forward/basis/roll成本合成项' },
      ],
      explanation: '这是教学近似，未处理复利、现金流时点、collateral、税、quanto与交易成本；符号取决于FX报价方向，界面必须明示。',
      stopRule: '本币、报价方向、h、forward cost、basis、tenor或rollover任一缺失时Rhedged=null；unknown不等于0。',
    },
    counterexample: 'Treasury美元回报+2%，但若100%套保成本为2.4%，SYN套保后贡献约−0.4%；“美国收益率更高”并未自动提高本币投资者净回报。若未给hedge ratio与成本，正确答案不是+2%，而是null。',
    evidenceBoundary: 'BIS Bulletin 105支持FX swaps/forwards、basis与期限错配机制；IAWG支持Treasury全球配置与融资网络。Bulletin事件背景不提供统一hedge ratio或永久关系。',
    interfaces: { from: '接收4.04.11美元资产价格结果，而不是直接接收一个headline yield。', to: '把hedged/unhedged state、basis与rollover gap交给4.04.13国际pass-through。' },
    sourceIds: [4, 14],
    sourceNote: '来源14支撑FX hedge门；来源4支撑Treasury全球资产与融资网络。',
  },
  {
    id: 'treasury-curve-mechanism-13',
    label: 'GLOBAL + REVERSE SPILLOVER',
    title: '国际传导由本地政策、期限溢价、美元融资和市场结构过滤，而且外国冲击也能反向进入Treasury。',
    question: '为什么全球影响既不是一比一复制，也不是永远从美国单向出发？',
    intuition: '同一场上游降雨流入不同城市，会被水库、河道和排水系统改写；下游洪水也可能反过来改变上游调度。美国利率冲击进入各国时，要穿过汇率制度、政策反应、外债、储备、市场深度与风险承受；外国增长和政策又会改变全球duration需求与美国term premium。',
    actors: '美国与外国央行、财政部门、银行、全球基金、官方储备、企业美元借款人与本地债券投资者共同作用。本地央行可能跟随、抵消或容忍汇率变化；全球投资者按relative value和hedge cost重配；dealer连接多个市场。',
    constraints: '跨国beta随driver、国家状态、样本与窗口变化。BIS WP719以FOMC窄窗口2Y Treasury变化识别特定货币政策冲击；FEDS 2021-001的foreign share与overnight proxy依模型。不能把43bp、56bp或20–25%等结果写成实时固定系数。',
    behavior: '研究者先识别美国driver，再分别建模本地expected-short-rate、term-premium、FX/funding与政策反应；同时保留reverseSpilloverFlag。资产管理者按本币负债和hedge成本重配，不以“全球risk-off”替代具体门。',
    transmission: '政策紧缩可经全球参考率、美元融资与风险承受推高本地term premium；增长信息可改善出口或现金流并抵消更高yield；外国低利率或避险需求又可能压低美国远期与term premium。最终共振来自网络，而非一个源点的机械广播。',
    feedback: '本地货币贬值和融资紧张可促使央行收紧、机构卖出外汇资产或提高套保，进一步影响Treasury和美元；反向冲击改变美国金融条件后，又反馈到政策预期。这是跨境闭环，不是单向箭头。',
    counterexample: '同一美国2Y政策冲击，某个汇率稳定且外债高的经济体可能通过本地政策路径强烈跟随；另一个浮动汇率、资产负债表健康的经济体更多由汇率吸收。若观测到美国长端先变，也仍可能是亚洲或欧洲消息在美国开盘前进入term premium。',
    evidenceBoundary: 'BIS WP719支持特定样本下的异质国际渠道；Kim–Ochoa支持外国冲击与反向term-premium传导；BIS FX材料支持套保门。所有量化结果都保留样本、模型与时钟。',
    interfaces: { from: '接收4.04.10 driver、4.04.11资产贡献与4.04.12FX hedge状态。', to: '向4.04.14压力反馈和7.10输出双向、条件化globalRateStateCandidate。' },
    sourceIds: [10, 11, 14],
    sourceNote: '来源10支撑正向异质传导；来源11支撑反向溢出；来源14支撑币种与套保过滤。',
  },
  {
    id: 'treasury-curve-mechanism-14',
    label: 'MARCH 2020 / BENCHMARK CAN BREAK',
    title: '全球安全基准也会内生失灵：2020年3月展示了卖压、保证金、basis与dealer capacity怎样共同破坏市场功能。',
    question: '为什么“最深、最安全的市场”仍会出现depth崩塌与异常价差？',
    intuition: '高速公路平时最畅通，不代表灾害撤离时不会堵塞。Treasury平时具有深度、抵押与benchmark服务；当多类主体同时要现金、套利需要追加margin，而dealer不能无限扩表时，出售规模可以超过即时承接能力。',
    actors: '共同基金、外国官方与私人投资者、风险平价和其他leveraged funds、basis traders、dealers、repo providers、CCPs与联储都在事件链中。不同证据看到不同分段；任何“某一类参与者造成全部问题”的叙事都会忽略并行流和中介瓶颈。',
    constraints: '高volume可来自强迫交易，不等于低成本流动性；需同时看bid–ask、depth、price impact、报价规模与resilience。Hedge fund cash、futures与repo腿不能简单相加；官方复盘是多机制证据，不是单一结构份额估计。个案也不能直接外推下一次危机。',
    behavior: '现金需求与赎回推动出售；hedge关系逆转和volatility使basis扩大、margin上升；部分leveraged positions unwind；dealer吸收库存直至承载收紧；Fed通过大规模购买与融资安排支持市场功能。研究者必须按市场分段、时间和工具重建。',
    transmission: '卖压 → dealer库存与风险限额收紧 → off-the-run和on-the-run liquidity恶化 → basis与融资成本上升 → 更多去杠杆与跨资产出售 → 金融条件收紧。官方购买释放部分dealer capacity并改善承接，但这不等于所有价格变化都是货币政策signal。',
    feedback: '平时套利与dealer intermediation压窄价差，鼓励规模和杠杆；压力时同一网络因margin、haircut与容量约束反向放大偏差。基准地位依赖市场基础设施的韧性，而不是仅依赖发行者信用。',
    counterexample: '2020年3月Treasury成交量显著增加，同时bid–ask扩大、depth下降且price impact恶化。若只看volume会得到“流动性很好”的反结论；若只看yield又会把现金争夺误写成纯粹宏观贴现率变化。',
    evidenceBoundary: 'IAWG与Fed MPR记录多类流、basis、margin、dealer库存及政策响应；Fleming约束流动性指标。材料不提供单因归责或下一次危机的精确阈值。',
    interfaces: { from: '汇合4.04.4 specialness、4.04.7 basis、4.04.8 funding、4.04.10 driver与4.04.13全球流。', to: '向7.10交付带intermediaryCapacity、liquidity dimensions、driver unknown和null reasons的状态，而非单一global discount rate。' },
    sourceIds: [4, 5, 6],
    sourceNote: '来源4–5提供官方事件复盘；来源6提供流动性测量边界。',
  },
] as const;
