import type { LessonReading, LessonReference } from './types';

export type TreasuryCurveSourceId = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;

export const lesson404References: LessonReference[] = [
  {
    id: 1,
    authors: 'U.S. Department of the Treasury, Office of Debt Management',
    year: '2025 methodology revision',
    accessedAt: '2026-09-16',
    title: 'Treasury Yield Curve Methodology',
    publication: 'U.S. Department of the Treasury',
    url: 'https://home.treasury.gov/policy-issues/financing-the-government/interest-rate-statistics/treasury-yield-curve-methodology',
    use: '支持官方名义Treasury曲线是par curve：输入是纽约联储约15:30取得的、最近拍卖证券的indicative bid-side quotations，先由价格转为收益率，再bootstrap并对forward rates作monotone-convex interpolation。它不支持把CMT当成交价、零息曲线、实时可交易组合或任意合约的法定折现曲线。',
  },
  {
    id: 2,
    authors: 'U.S. Department of the Treasury, Office of Debt Management',
    year: 'current FAQ',
    accessedAt: '2026-09-16',
    title: 'Interest Rates — Frequently Asked Questions',
    publication: 'U.S. Department of the Treasury',
    url: 'https://home.treasury.gov/policy-issues/financing-the-government/interest-rate-statistics/interest-rates-frequently-asked-questions',
    use: '支持CMT是从par curve固定期限点读出的bond-equivalent yield，未必对应某只实际证券；Treasury不发布日度zero-coupon curve，CMT也不是APY。它不支持认为CMT没有信息价值，也不允许把par、zero、discount factor与YTM互换。',
  },
  {
    id: 3,
    authors: 'Refet S. Gürkaynak, Brian Sack & Jonathan H. Wright',
    year: '2006',
    accessedAt: '2026-09-16',
    title: 'The U.S. Treasury Yield Curve: 1961 to the Present',
    publication: 'Federal Reserve Board, Finance and Economics Discussion Series 2006-28',
    url: 'https://www.federalreserve.gov/PUBS/FEDS/2006/200628/200628pap.pdf',
    use: '核读PDF pp.2–11、13–14、18–19及26–28。支持discount function、zero/par/forward关系、duration/convexity局部近似、Treasury的benchmark与hedge用途，以及剔除on-the-run/first off-the-run的研究曲线。它不提供实时曲线，不把forward等同无期限溢价的预期，也不证明Treasury是唯一benchmark。',
  },
  {
    id: 4,
    authors: 'U.S. Department of the Treasury, Federal Reserve Board, Federal Reserve Bank of New York, SEC & CFTC staff',
    year: '2021',
    accessedAt: '2026-09-16',
    title: 'Recent Disruptions and Potential Reforms in the U.S. Treasury Market: A Staff Progress Report',
    publication: 'Inter-Agency Working Group on Treasury Market Surveillance',
    url: 'https://home.treasury.gov/system/files/136/IAWG-Treasury-Report.pdf',
    use: '核读PDF pp.2、4–5、9–16、23–24及35。支持Treasury的全球基准、抵押品与政策传导角色，cash–repo–futures连接，以及2020年3月多类卖方、保证金、basis unwind和dealer承载约束共同反馈。它不支持单因归责、无约束套利或“credit-risk-free等于没有价格/流动性风险”。',
  },
  {
    id: 5,
    authors: 'Board of Governors of the Federal Reserve System',
    year: '2020',
    accessedAt: '2026-09-16',
    title: 'Monetary Policy Report, June 2020',
    publication: 'Federal Reserve Board, box on Treasury and agency MBS market functioning, PDF pp.50–51',
    url: 'https://www.federalreserve.gov/monetarypolicy/files/20200612_mprfullreport.pdf',
    use: '支持2020年3月投资者大量出售长期Treasury与agency MBS可与bid–ask明显扩大、posted quote volume／market depth大幅下降并存，也记录了多类投资者、dealer承接与联储市场功能购债。它不直接测量本课所说的总体Treasury trading volume或price impact；二者由来源4与6分别承担，也不能据此单独识别各参与者的因果贡献或把2020当作所有危机的固定模板。',
  },
  {
    id: 6,
    authors: 'Michael J. Fleming',
    year: '2003',
    accessedAt: '2026-09-16',
    title: 'Measuring Treasury Market Liquidity',
    publication: 'Federal Reserve Bank of New York Economic Policy Review, 9(3)',
    url: 'https://www.newyorkfed.org/medialibrary/media/research/epr/03v09n3/0309flempdf.pdf',
    use: '支持Treasury流动性至少要分bid–ask、depth/quantity与price impact；volume与trade frequency单独作为流动性指标较弱，并明确on-the-run与off-the-run定义及repo specialness候选。历史样本数值不能当作2026实时参数，也不覆盖压力后的resilience全维度。',
  },
  {
    id: 7,
    authors: 'Federal Reserve Bank of New York',
    year: 'current methodology',
    accessedAt: '2026-09-16',
    title: 'Additional Information about Reference Rates Administered by the New York Fed',
    publication: 'New York Fed Markets & Policy Implementation',
    url: 'https://www.newyorkfed.org/markets/reference-rates/additional-information-about-reference-rates',
    use: '支持SOFR是以Treasury securities作抵押的广泛隔夜融资成本，且DVP special repos会因取得特定券而以较低repo rate成交；这说明融资率、特券便利与债券收益率是不同对象。它不支持所有repo等于SOFR，也不指定所有合约的折现曲线。',
  },
  {
    id: 8,
    authors: 'Alternative Reference Rates Committee',
    year: '2020',
    accessedAt: '2026-09-16',
    title: 'Consultation on Swaptions Impacted by the CCP Discounting Transition to SOFR',
    publication: 'ARRC, convened by the Federal Reserve Board and New York Fed',
    url: 'https://www.newyorkfed.org/medialibrary/Microsites/arrc/files/2020/ARRC_Swaption_Consultation.pdf',
    use: '核读PDF pp.1–2。支持cleared USD swaps的PAI/discounting制度从EFFR迁移到SOFR会重估合约并需要补偿安排，说明担保与清算约定决定折现制度。它不支持Treasury对swap没有hedge或relative-value影响，也不覆盖未担保或不同CSA合约。',
  },
  {
    id: 9,
    authors: 'Lawrence L. Kreicher, Robert N. McCauley & Philip D. Wooldridge',
    year: '2017',
    accessedAt: '2026-09-16',
    title: 'The bond benchmark continues to tip to swaps',
    publication: 'BIS Quarterly Review, March 2017',
    url: 'https://www.bis.org/publications/qr-201703/bond-benchmark-continues-tip-swaps',
    use: '支持benchmark是定价、对冲与头寸表达的市场坐标；政府债历史上重要，但swaps在多种币种市场也承担benchmark角色，危机时basis risk可使政府债hedge失效。它不支持swaps在所有币种、期限和时期都占优，也不证明Treasury垄断全球基准。',
  },
  {
    id: 10,
    authors: 'Elias Albagli, Luis Ceballos, Sebastian Claro & Damian Romero',
    year: '2018',
    accessedAt: '2026-09-16',
    title: 'Channels of US Monetary Policy Spillovers to International Bond Markets',
    publication: 'BIS Working Papers No 719',
    url: 'https://www.bis.org/publications/working-paper-719-channels-us-monetary-policy-spillovers-international-bond-markets.pdf',
    use: '核读PDF pp.2–4。支持以FOMC窄窗口2Y Treasury变化识别的美国货币政策冲击可经预期短率与期限溢价异质地传到外国长端。其2003–2016、12个发达与12个新兴经济体样本内数值不是实时beta、不是任意Treasury move，也不是一比一传导常数。',
  },
  {
    id: 11,
    authors: 'Don H. Kim & Marcelo Ochoa',
    year: '2021',
    accessedAt: '2026-09-16',
    title: 'International Yield Spillovers',
    publication: 'Federal Reserve Board, FEDS 2021-001',
    url: 'https://www.federalreserve.gov/econres/feds/international-yield-spillovers.htm',
    use: '核读论文abstract、识别限制与结论。支持外国冲击也可经term premium影响美国长端，跨境传导是双向的；论文截至2019样本中的至少20%估计是模型内描述。作者明确说overnight move只是rough proxy，数值不能当结构常数或实时分解。',
  },
  {
    id: 12,
    authors: 'Christoph E. Boehm & T. Niklas Kroner',
    year: '2023',
    accessedAt: '2026-09-16',
    title: 'The U.S., Economic News, and the Global Financial Cycle',
    publication: 'Federal Reserve Board, International Finance Discussion Papers 1371',
    url: 'https://www.federalreserve.gov/econres/ifdp/the-us-economic-news-and-the-global-financial-cycle.htm',
    use: '支持1996–2019窄窗口内美国宏观消息能同时改变多国股票、VIX、商品、债券收益率与风险溢价，并提示债券收益率反应不足以单独解释股票反应。论文的23%等结果依其样本和设计，不能当实时份额；宏观surprise也不自动等同完整结构冲击。',
  },
  {
    id: 13,
    authors: 'Marek Jarociński & Peter Karadi',
    year: '2020',
    accessedAt: '2026-09-16',
    title: 'Deconstructing Monetary Policy Surprises — The Role of Information Shocks',
    publication: 'American Economic Journal: Macroeconomics, 12(2), 1–43',
    url: 'https://www.aeaweb.org/articles?id=10.1257/mac.20180090',
    use: 'publisher abstract支持意外紧缩常对应利率上升、股票下降，而正向央行信息冲击可让利率与股票同升。当前环境未取得全文，因此不引用表格、系数、页内细节或样本外稳定性；它只支持“相同利率方向不识别相同冲击”的存在性。',
  },
  {
    id: 14,
    authors: 'Hyun Song Shin, Philip Wooldridge & Dora Xia',
    year: '2025',
    accessedAt: '2026-09-16',
    title: 'The US dollar’s slide in April 2025: the role of FX hedging',
    publication: 'BIS Bulletin No 105',
    url: 'https://www.bis.org/publications/bulletin-105-us-dollars-slide-april-2025-role-fx-hedging.pdf',
    use: '核读PDF pp.2–5与p.7。支持外国投资者常以FX swaps/forwards套保美元资产，成本受短端利差与cross-currency basis影响，期限错配带来rollover risk。它是特定时期分析，不提供所有投资者统一hedge ratio、当前净流量或永久因果份额。',
  },
  {
    id: 15,
    authors: 'Thomas S. Y. Ho',
    year: '1992',
    accessedAt: '2026-09-16',
    title: 'Key Rate Durations: Measures of Interest Rate Risks',
    publication: 'The Journal of Fixed Income, 2(2), 29–44',
    url: 'https://doi.org/10.3905/jfi.1992.408049',
    use: '作为key-rate duration原始书目，支持以期限节点敏感度管理非平行曲线风险的概念来源。当前环境仅核到DOI与元数据、未取得全文；本课节点、冲击和算术均明确为作者SYN，不声称来自该文的经验最优设置。',
  },
  {
    id: 16,
    authors: 'U.S. Department of the Treasury, Bureau of the Fiscal Service',
    year: 'current product page',
    accessedAt: '2026-09-16',
    title: 'About Treasury Marketable Securities',
    publication: 'TreasuryDirect',
    url: 'https://www.treasurydirect.gov/marketable-securities/',
    use: '支持marketable意味着可在到期前转让/出售，并区分Bills、Notes、Bonds、TIPS、FRNs与STRIPS的现金流结构。它不支持这些工具具有相同duration、通胀暴露、流动性或报价习惯，也不把储蓄债纳入同一可交易曲线。',
  },
];

export const lesson404ReadingList: LessonReading[] = [
  { title: '路线一：先把CMT、par、zero与forward分开', scope: 'Treasury methodology + FAQ；GSW §§2.1–2.4', reason: '先学会给一条曲线贴币种、输入、报价侧、复利、日计数与估值时点护照；没有对象身份，后面的“全球贴现率”只能是含混比喻。', url: lesson404References[0].url, group: 'core', links: [{ label: 'Treasury FAQ', url: lesson404References[1].url }, { label: 'GSW 2006', url: lesson404References[2].url }] },
  { title: '路线二：理解benchmark为何是一种市场制度', scope: 'GSW introduction/security selection；BIS benchmark feature', reason: '比较政府债与swap如何承担参考、hedge和头寸表达角色，避免把benchmark误写成每份合约唯一折现曲线。', url: lesson404References[2].url, group: 'core', links: [{ label: 'BIS benchmark', url: lesson404References[8].url }] },
  { title: '路线三：读cash–repo–futures这张市场网络', scope: 'IAWG pp.4–5、23–24、35；NY Fed SOFR methodology', reason: '把Treasury同时作为证券、抵押品与融资投入品来理解，看到haircut、repo specialness、basis与dealer capacity怎样反馈。', url: lesson404References[3].url, group: 'systems', links: [{ label: 'SOFR/reference rates', url: lesson404References[6].url }] },
  { title: '路线四：把OIS discounting当作合同制度而非同义词', scope: 'ARRC pp.1–2；NY Fed SOFR定义', reason: '折现曲线由抵押、PAI、CCP或CSA安排约束；Treasury仍可影响hedge和relative value，却不是SOFR曲线的别名。', url: lesson404References[7].url, group: 'rules', links: [{ label: 'NY Fed reference rates', url: lesson404References[6].url }] },
  { title: '路线五：非平行曲线风险从duration走向KRD', scope: 'GSW §2.4；Ho (1992)书目信息', reason: '先掌握局部一阶近似，再把风险写成期限节点向量；全文不可得的Ho论文只作原始书目，不承担本课具体数值。', url: lesson404References[2].url, group: 'models', links: [{ label: 'KRD原始DOI', url: lesson404References[14].url }] },
  { title: '路线六：同一yield move为何可对应不同股票方向', scope: 'IFDP 1371；Jarociński–Karadi publisher abstract', reason: '将增长/信息、政策紧缩与风险溢价通道拆开，学习从joint response识别候选驱动，而不是给“收益率上升”套固定risk-off标签。', url: lesson404References[11].url, group: 'evidence', links: [{ label: 'AEA论文页', url: lesson404References[12].url }] },
  { title: '路线七：跨境传导必须同时读正向与反向', scope: 'BIS WP719 pp.2–4；FEDS 2021-001', reason: '美国冲击会被本地政策和term premium过滤，外国冲击也能返回Treasury；所有系数都要保留样本、窗口与模型护照。', url: lesson404References[9].url, group: 'evidence', links: [{ label: 'International Yield Spillovers', url: lesson404References[10].url }] },
  { title: '路线八：外国投资者先过FX hedge gate', scope: 'BIS Bulletin 105 pp.2–5、7', reason: '区分美元本地回报、未套保本币回报与套保后回报；缺少本币、hedge ratio、forward cost或basis时，结果必须保持null。', url: lesson404References[13].url, group: 'systems' },
  { title: '路线九：2020不是“无风险率变了”的单因故事', scope: 'IAWG pp.9–16、35；Fed MPR pp.50–51；Fleming liquidity dimensions', reason: '将赎回、margin、basis unwind、海外/国内卖方和dealer capacity放在同一反馈系统，并用spread、depth、impact而非volume单指标判断市场功能。', url: lesson404References[3].url, group: 'systems', links: [{ label: 'Fed 2020复盘', url: lesson404References[4].url }, { label: '流动性测量', url: lesson404References[5].url }] },
];

export const treasuryCurveEvidenceGroups = [
  { key: 'curve-identity', title: '曲线对象与债券数学', supports: 'CMT输入与方法、par/zero/forward、duration/convexity、工具现金流。', doesNotSupport: '不把官方par quote当零息曲线或实时成交，不把局部近似当精确P&L。', sourceIds: [1, 2, 3, 16] as const },
  { key: 'benchmark-market', title: '基准、流动性与相对价值', supports: 'benchmark/hedge角色、on/off-the-run、流动性多维度、swap benchmark与basis risk。', doesNotSupport: '不宣称Treasury是唯一基准，不用volume单独证明流动性。', sourceIds: [3, 6, 9, 15] as const },
  { key: 'funding-infrastructure', title: '抵押、repo与折现制度', supports: 'cash–repo–futures网络、SOFR融资对象、CCP/PAI折现迁移。', doesNotSupport: '不把SOFR、Treasury yield与OIS curve互换，不假设套利无资产负债表约束。', sourceIds: [4, 7, 8] as const },
  { key: 'driver-cross-asset', title: '冲击身份与跨资产方向', supports: '增长/信息、政策紧缩和风险溢价可令相同yield方向产生不同股票反应。', doesNotSupport: '不从普通日频变化直接识别Fed shock，不把历史系数当实时规则。', sourceIds: [12, 13] as const },
  { key: 'international', title: '国际与双向溢出', supports: '本地反应函数、期限溢价、反向溢出及FX hedge/basis/rollover门。', doesNotSupport: '不设一比一pass-through，不把样本内数字当常数或统一hedge ratio。', sourceIds: [10, 11, 14] as const },
  { key: 'stress', title: '2020市场功能压力', supports: '多类卖压、融资/保证金、basis unwind、dealer承载和流动性指标共同反馈。', doesNotSupport: '不作单因归责，不把高成交量等同良好流动性，也不将个案机械外推。', sourceIds: [4, 5, 6] as const },
] as const;

export const treasuryCurveFailedSourceLedger = [
  { title: 'Jarociński & Karadi (2020) full-text PDF', request: 'https://www.aeaweb.org/articles/pdf/doi/10.1257/mac.20180090', status: 'HTTP 403 on 2026-09-16', resolution: '只使用可访问publisher record/abstract；不引用全文页码、表格或系数。', sourceIds: [13] as const },
  { title: 'Ho (1992) publisher full text', request: 'https://doi.org/10.3905/jfi.1992.408049', status: 'DOI metadata reachable; full text not obtained', resolution: '仅作KRD原始书目；本课节点与算术全部标为作者SYN。', sourceIds: [15] as const },
] as const;
